### ISSUE TITLE
One Apollo Parent appearing for each query within a react app.  

### ISSUE THREAD

**Issue by gl2748** [apollographql/react-apollo#1000]
**Intended outcome:**

Ideally when I wrap my React component in the apollo provider it will appear as the first child.
This is what I am doing:
```jsx
import React from 'react';
import { ApolloProvider } from 'react-apollo';
import { BrowserRouter as Router, Route} from 'react-router-dom';

const Root = ({ initialState, store, client, routePath, reactElement }) => {
  return (
    <ApolloProvider
      initialState={initialState}
      store={store}
      client={client}
    >
      <Router>
        <Route
          path={routePath}
          render={
            () => reactElement
          }
        />
      </Router>
    </ApolloProvider>
  );
};

export default Root;
```

**Actual outcome:**
NB. Everything works as expected, it's just that it looks ugly and I would like some re-assurance I'm not doing something peculiar or unusual...

Instead I get a crazy nested structure on the DOM , basically one <ApolloProvider> parent for each query that is triggered within the app. It looks like this:

![screen shot 2017-08-18 at 7 04 14 pm](https://user-images.githubusercontent.com/3374538/29480773-dc9969b0-8448-11e7-85a3-83db54e79256.png)

**How to reproduce the issue:**
(Possibly) Quirky things I'm doing
This is a react app running from within Ruby-on-Rails. 

**Version**
- apollo-client@^1.9.1
- react-apollo@^1.2.0

**Comment by mrutyna** [comment]
I've been seeing something similar. Also with a react app running from Rails

@gl2748 - Did you ever find out why ?
