### ISSUE TITLE
Get a promise from graphql HOC Query

### ISSUE THREAD

**Issue by barbu110** [apollographql/react-apollo#1004]
Hi guys!

I have a form, it is meant to be used to edit existing resources in my app. I have a React component which is wrapped in the `graphql` HOC in the following way:

```js
const withData = compose(
  graphql(FetchEditorData, {
    props(p) {
      preloadEditorData() => {
        // this function is meant to return a promise with the desired data
        // the documentation only explains what p.data contains (i.e. loading,
        // data etc.)
      },
    },
  },
  graphql(CommitResourceEditMutation, {
    props(p) {
      onSubmit(editorState) => { /* ... */ },
  },
);
```

As you can see, the components reads data from a query, loads it into the form and when the form is submitted, the mutation is executed. 

I need to display a loading indicator both when the data is loading and when the changes are saving. By following the traditional approach the [docs](http://dev.apollodata.com/react/api-queries.html) state, I would need to add a **`loading` prop** and a **`loading` state key** and check on both of them.

Instead, I added a property to my component, `preloadEditorData` which is meant to return a `Promise<EditorState>`, so I can have only one `loading` flag. Is there any way I can return a Promise from the HOC?

**Comment by barbu110** [comment]
@jbaxleyiii any idea on this, please?

**Comment by koenpunt** [comment]
Well, your example code is not even valid JS, so it's not really clear what you want to achieve. If you want to have the options for the query passed in async the best approach is probably a HOC.

**Comment by barbu110** [comment]
@koenpunt, What isn’t valid in my snippet?
