### ISSUE TITLE
Bug: getClient calls `options` with with current props

### ISSUE THREAD

**Issue by koenpunt** [apollographql/react-apollo#1005]
When `skip` transitions from `true` to `false` due to a prop change, the `options` method is called several times. The times it is called to retrieve for example the variables for the query it is called with the components `nextProps`. But the internal `getClient` method calls it with `this.props`. As this hasn't been brought up as of yet, I recon nobody has used `skip` in the way I did.

Take for example this options object: 

```js
{
  options: ownProps => ({
    variables: {
      gender: ownProps.person.gender,
    },
  }),
  skip: ownProps => !ownProps.person,
}
```
So as long as there's no `person` property available I don't want to execute the query.

But the moment the `person` property is set, `options` is called several times. Not sure of the order, but at least for `skip`, `variables` and `client`. When it is called for `skip` or `variables`, the `nextProps` are passed, and `ownProps.person.gender` will return the persons gender.

But when options is called for the client, `this.props` is passed, which at that point does not yet contain the `person` prop, and thus accessing `ownProps.person.gender` will fail with an error.

**Intended outcome:**

For the client, `options` should also be called with the value of `nextProps` 

**Actual outcome:**

App throws an error: `Uncaught TypeError: Cannot read property 'gender' of undefined`
![image](https://user-images.githubusercontent.com/351038/29573740-0954eeec-8760-11e7-9fa3-201f40ad6517.png)

**How to reproduce the issue:**

I've created a minimal example demonstrating the issue using the error-template (note the branch):
Just run it with the developer console open and the problem will present itself.

https://github.com/koenpunt/react-apollo-error-template/tree/get-client-prev-props

**Version**
- apollo-client@1.9.1
- react-apollo@1.4.14

**Comment by jbaxleyiii** [comment]
@koenpunt thanks for the detailed usage and report! I'll take a look!
