### ISSUE TITLE
Can't use update to update a query with a different schema than mutation's one

### ISSUE THREAD

**Issue by NitroBAY** [apollographql/react-apollo#1006]
Hello,
I have a `login` mutation that returns that : 
```
const login = gql`
  mutation loginFromForm($email: String!, $password: String!) {
    login(email: $email, password: $password) {
      currentUser {
        isAdmin
      }
      token
      error
    }
  }
`;
```

I want to use the information `isAdmin` to update the query : 
```
const isAdminQuery = gql`
  query isAdminForLayout($token: String) {
    currentUser(token: $token) {
      isAdmin
    }
  }
`;
```
So I gotta update the cache of currentUser based on the login mutation's response. It seems a quite simple thing to do and indeed with the method `reducer` it is a no-brainer BUT this API is not recommended as it can ge deprecated anytime soon, update is recommended though. So I pass the query `currentUser` to the component that has the mutation so the mutation could logically update the query. Okay so here it gets tricky for me. The update method of the mutation `login` is throwin an error (`Error: Can't find field currentUser({}) on object (ROOT_QUERY)`) whenever I try to do `proxy.readQuery({ query: props.isAdminQuery })`.
So from my understanding the mutation expected the query `isAdmin` to have the same schema as itself. But I didn't design the login mutation to directly return the user but instead the user inside the currentUser object. Am I designing the mutation result wrong ? I don't know but as the mutation both gotta return the token and the user I got to put user data inside a nested field. 
```
  type UserPlusToken {
    currentUser: User
    token: String
    error: String
  }
```

**Comment by NitroBAY** [comment]
Can be related to #995 and many more. But I don't see any solutions inside the issues related to mine.

**Comment by NitroBAY** [comment]
Okay I found the solution, I needed to add a `variables` field in the object passed to readQuery.

**Comment by luisvinicius167** [comment]
I created this function and solve my problem:
```javascript
export const prepareShape = ( shape, obj ) => {
  const shapped = {}
  Object.keys(shape).forEach( key => {
    if (obj[key] !== undefined ) {
      shapped[key] = obj[key]
    } else {
      shapped[key] = null
    }
  })
  return Object.assign({}, shapped, obj);
}
```

When you update a query in your store, the query used must have the same signature as the query you used before, so it returns an object with specific fields. This function prepares its updated object to be written to the store without fields conflict.

The Gist:
```javascript

// my todo to be appended inside store
const updatedTodo = {
  id: 1,
  text: 'TODO'
}

// the shape object used in the query { id, text, value }
const shape = data.todos[0]; 

store.writeQuery({
  query: MY_QUERY,
  data: {
    todos: [ ...data.todos, prepareShape( shape, udpatedTodo ) ]
  }
});

// prepareShape will return:  { id:1, text: 'TODO', value: null } 
```
`preapareShape` will remove the conflicts of fields that the query needs. You'll don't get this warnings more: 
`writeToStore.js:110 Missing field email in field {...}`

That's it! :)
