### ISSUE TITLE
Omitted variables are passed as null, and default values do no kick in

### ISSUE THREAD

**Issue by wesbos** [apollographql/react-apollo#1038]
Hello - I've got this query with some default values:

```
export const ALL_ITEMS_QUERY = gql`
  query AllLinksQuery($skip: Int = 6, $first: Int = 3) {
    _allItemsMeta {
      count
    }
    allItems(orderBy: createdAt_DESC, first: $first, skip: $skip) {
      id,
      title
    }
  }
`
```

Now on page load I run it like this:
```js
const itemsEnahncer = graphql(ALL_ITEMS_QUERY, { name: 'allItemsQuery' });
```

and the causes the variables $first and $skip to be sent as `null`, which isn't enough for a graphql server to kick in the default values. 

Now if I explicitly pass the values as undefined, the default values of the query kick in.

```js
const itemsEnahncer = graphql(ALL_ITEMS_QUERY, { name: 'allItemsQuery', options: {
  // TODO: This is funny, I should be able to omit this all together
  variables: { first: undefined, skip: undefined }
}});
```

Is this a bug? Or am I doing something wrong? 

"react-apollo": "^1.4.14",

**Comment by jbaxleyiii** [comment]
@wesbos it is a bug, though I'm not sure if in this library of the core client. I'll take a look!

**Comment by migueloller** [comment]
@jbaxleyiii,

This still seems to be an issue. When passing `undefined` in a top-level variables, Apollo Client will convert it to null.

**Comment by migueloller** [comment]
Is this still an issue @jbaxleyiii? Or is it gone in Apollo Client 2.0?

**Comment by diegocouto** [comment]
I can confirm that this still happening in Apollo Client 2.0 (I'm using `v2.2.5`).

**Comment by bkonkle** [comment]
We're still seeing this behavior in Apollo Client 2.1.

**Comment by bkonkle** [comment]
@jbaxleyiii Would it be okay to re-open this ticket? It's counter-intuitive that default arguments in our Express server are not triggered by the `null`s vs. the `undefined`s.

**Comment by jeffshadap** [comment]
It is still an issue in  Apollo Client 2.1.

**Comment by asyschikov** [comment]
In versions 1.x the problem was in this function:

https://github.com/apollographql/react-apollo/blob/v1.4.15/src/graphql.tsx#L276

If the variables were passed they would be used as is, if the variables were extracted from props the undefined values were replaced by nulls:

```
          if (typeof props[variable.name.value] !== 'undefined') {
            variables[variable.name.value] = props[variable.name.value];
            continue;
          }

          // allow optional props
          if (type.kind !== 'NonNullType') {
            variables[variable.name.value] = null;
            continue;
          }
```

**Comment by AdamTyler** [comment]
I'm still seeing this issue with Apollo Client v2.5.1. Is there a workaround for this?

**Comment by Niondir** [comment]
Same here with 2.6.4, maybe repoen this?

**Comment by freshedgarT** [comment]
I am also having this issue in 3.1.3
