### ISSUE TITLE
Upgrade Flow types to 0.53.0

### ISSUE THREAD

**Issue by volkanunsal** [apollographql/react-apollo#1042]
In Flow version 0.53.0 the specification of React Components changed somewhat. The first type parameter for default props is removed. That's why I'm seeing a few errors in the Flow definitions.

**Comment by jbaxleyiii** [comment]
@volkanunsal we have a PR for this! Should be out this week

**Comment by volkanunsal** [comment]
@jbaxleyiii Ok, thanks!

**Comment by arahansen** [comment]
Any luck making progress on this? Happy to help out if I can.
