### ISSUE TITLE
react-apollo/apollo-client and graphql compatibility list

### ISSUE THREAD

**Issue by therealedsheenan** [apollographql/react-apollo#1076]
It would be nice if there is a list/guide of compatibility between apollo-client/react-apollo versions and graphql. Since grapql repo is also updating its codebase, it will help people from getting into compatibility issues.

In my case, I resolve the issue below by installing graphql@0.10.5.

**Intended outcome:**
Running apollo client without any errors.

**Actual outcome:**
` Error: Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory.`

**How to reproduce the issue:**
Installation of the latest react-apollo and graphql versions

**Version**
- apollo-client@1.9.2
- react-apollo@1.4..15

**Comment by wrongway4you** [comment]
Agree, - I have the same error with the same package versions.

**Comment by xealot** [comment]
I'm having the same issue and I'm having a hard time finding which versions I should be using.

**Comment by alishir** [comment]
I have the same issue on new project just create with `create-react-app` and `yarn add react-apollo graphql`.
