### ISSUE TITLE
401 Authorization Error Displays As "GraphQL error: undefined"

### ISSUE THREAD

**Issue by johndanek** [apollographql/react-apollo#1079]
**Intended outcome:**
In my React Native app, I attempted to make a GraphQL request without providing the necessary authorization information. Instead of getting an error indicating this, the only error message is "undefined". It would be massively helpful if the 401 Authorization error were showed to the developer.

**Actual outcome:**
![screen shot 2017-09-08 at 2 31 20 pm](https://user-images.githubusercontent.com/6955277/30231997-6a2a7a3a-94a2-11e7-92d8-e06b4d0bdf1a.png)

I eventually figured out that it was a 401 causing havok by using Chrome Developer Tools:
![screen shot 2017-09-08 at 2 37 01 pm](https://user-images.githubusercontent.com/6955277/30232157-350872e8-94a3-11e7-8629-885b4a9b26ad.png)

**How to reproduce the issue:**
Attempt to make a GraphQL request against a GraphQL endpoint that requires auth, but don't include it.

**Version**
- apollo-client@<n/a>
- react-apollo@1.4.15

**Comment by akomm** [comment]
Do you have apollo store in your redux store?
Do you use meta (storage) reducer to save your store over page reloads?

**Comment by johndanek** [comment]
@akomm I'm not sure I understand what you're asking. I don't use redux, as far as I know. I'm also not sure what you mean by "page reloads".

I was able to see the error by just sending a single Apollo request after the app started. So the error would have been before caching or anything involving a store.

**Comment by sneerin** [comment]
@akomm it seems I have the same issue. The biggest problem I wasn't aware of the error until I started Charles proxy and figureout that I've got 401.

**Comment by strukturedkaos** [comment]
I have the same issue as well. 

I tried using the [afterware described in the docs](http://dev.apollodata.com/core/network.html#networkInterfaceAfterware), but this doesn't seem to prevent the unhandled error.

Is there an example of someone handling this 401 error without getting the unhandled error? Something like the below doesn't seem to prevent the error.

```javascript
import ApolloClient, { createNetworkInterface } from 'apollo-client';
import {logout} from './logout';
const networkInterface = createNetworkInterface({ uri: '/graphql' });
networkInterface.useAfter([{
  applyAfterware({ response }, next) {
    if (response.status === 401) {
      logout();
    }
    next();
  }
}]);
const client = new ApolloClient({
  networkInterface,
}); 
```

**Comment by strukturedkaos** [comment]
@jbaxleyiii pinging you on this since we haven't had a response from anyone.

**Comment by lukeggchapman** [comment]
Does your 401 response contain a valid JSON response?
Then this would be your problem: https://github.com/apollographql/apollo-client/issues/2238#issuecomment-335490549
