### ISSUE TITLE
Expected 0 arguments, but got 1. Using typescript and compose from react-apollo

### ISSUE THREAD

**Issue by johhansantana** [apollographql/react-apollo#1080]
Hello

I'm not sure if this is the right place to ask but I'm using typescript and `react-apollo`

my code is the following:
![image](https://user-images.githubusercontent.com/9933887/30232508-6a009da2-94be-11e7-872a-9a42740692a8.png)

If I remove the last `(Index)` the error will go away but I have no idea on how then export the container/component.

Basically, the code works but typescript is not happy with this.

**Comment by ladytellur** [comment]
Based on [Stackoverflow answer](https://stackoverflow.com/a/46138161/2330836) given
Imprecisely defining compose parameters as any will satisfy the compiler.

```
export default compose<any>(
  ...
)(Index)
```
