### ISSUE TITLE
[React-Native] How use react-apollo configuration query after app UI has been loaded?

### ISSUE THREAD

**Issue by thoth-nexlesoft** [apollographql/react-apollo#1092]
I use react-apollo to call Graphql Api, but UI of component always loads after Api has been call. How I load UI of component before I call Api?

**Version**
- apollo-client@<^1.9.2>
- react-apollo@<^1.4.15>

**Comment by pcooney10** [comment]
@thoth-nexlesoft if you're looking to load the component first so you can get some prop(s) to pass apollo, then I think the recommended approach is break your component into two with a HOC
