### ISSUE TITLE
Handle errors after every request

### ISSUE THREAD

**Issue by khotey** [apollographql/react-apollo#1093]
How create middleware which will catch all errors, for example I have request which required token, token can expired or damaged, so I need catch this errors on every request and be able to call queries and mutations.

For example:
On expired token, I must refetch token and repeat request.
On token damaged, I must logout user and refetch all queries.
And type of error witch I need to handle can be many.

In(react-apollo docs)
```
networkInterface.useAfter([{
  applyAfterware({ response }, next) {
    if (response.status === 401) {
      logout();
    }
    next();
  }
}]);
```

I can't access to graphql error, and call queries or mutations.

Tank you!

**Comment by WillBeebe** [comment]
On token expired shouldn't a user have to log in again? So with that and token damaged, delete it from local storage and log the user out? I don't have a ton of experience with token lifecycle but I'm trying to help. Feel free to say that my suggestion is rediculous

**Comment by khotey** [comment]
Problem is that I send requests in every lavel of app, and must catch an error on specific component which I call queries and mutation, I want to write middleware on hight leavel of app to catch every error of request on  children components requests.
