### ISSUE TITLE
Uncaught TypeError: Cannot set property 'middleware' of undefined

### ISSUE THREAD

**Issue by debanjanbasu** [apollographql/react-apollo#1101]
**Intended outcome:**
Connect my existing Redux project to use Apollo Client and connect to the PostgraphQL backend

**Actual outcome:**
![image](https://user-images.githubusercontent.com/10209115/30511223-6ebbda6e-9b17-11e7-9d98-e9c3aa74317d.png)

**How to reproduce the issue:**
After doing an npm i the following are the commands to run the servers
For FE dev:
npm run build:dev
For Prod:
npm run build:prod
For BE:
npm run run:nodemon

**Version**
- react-apollo@1.4.15

**Repository**
https://gitlab.com/debanjanbasu/trade-box

**Comment by debanjanbasu** [comment]
Everything works fine if I remove 
![image](https://user-images.githubusercontent.com/10209115/30511253-164fc6d2-9b18-11e7-99a7-a323b952533c.png)

@graphql from line 47.

I've tried every other method. By disabling the es6 decorations, etc. All in vain.

**Comment by jamiehill** [comment]
Same issue.  Please advise.

```
import gql from 'react-apollo';

const SOME_QUERY = gql`
      query foo {
        bar(id:12345) {
          id
          name
        }
      }
    `;
```
`gql` is causing this error for me.  Removing stops the error

**Comment by jamiehill** [comment]
Update: works fine if I use `apollo-client` and `graphql-tag`

**Comment by rkstar** [comment]
i'm getting this error when i add the `<ApolloProvider>` component at all... i haven't even made a query yet!
