### ISSUE TITLE
ErrorPolicy is not passed to apollo-client

### ISSUE THREAD

**Issue by maktouch** [apollographql/react-apollo#1112]
While `fetchPolicy` is a valid option, `errorPolicy` is not even though apollo-client has an errorPolicy option. This is problematic because the default option is `none`, so even if we have valid data, react-apollo decides to only return `props.errors` instead of the data. 

**Intended outcome:**
I would like to be able to ignore errors and still receive my data in my components

**Actual outcome:**
Only errors is passed, and no data is passed even though there's some valid data. 

**How to reproduce the issue:**
Returning a query like 

```json
{
  "errors": [
    {
      "message": "Name for character with ID 1002 could not be fetched.",
      "locations": [ { "line": 6, "column": 7 } ],
      "path": [ "hero", "heroFriends", 1, "name" ]
    }
  ],
  "data": {
    "hero": {
      "name": "R2-D2",
      "heroFriends": [
        {
          "id": "1000",
          "name": "Luke Skywalker"
        },
        {
          "id": "1002",
          "name": null
        },
        {
          "id": "1003",
          "name": "Leia Organa"
        }
      ]
    }
  }
}
```

**Version**
- apollo-client@1.9.2
- react-apollo@1.4.15

**Comment by maktouch** [comment]
Holy crap. It seems like ErrorPolicy is a new feature from apollo-client 2.0 =|

**Comment by jbaxleyiii** [comment]
@maktouch yep! there will be a release this week for react-apollo supporting it!

**Comment by johndavedecano** [comment]
@jbaxleyiii Any news about the release?
