### ISSUE TITLE
Unhandled promise error due to fetchPolicy

### ISSUE THREAD

**Issue by Milenkoo** [apollographql/react-apollo#1117]
**Intended outcome:**
Just redirect the user when we get a GraphQL error.
We use the fetchPolicy: 'cache-and-network'

**Actual outcome:**
We handle the graphQL error  and redirect the user : 
```js
 if (
      (data.error && data.error.graphQLErrors) ||
      (!data.loading)
    ) {
      return <Redirect to="/errorPage" />;
    }
```
However we had another error that appears, and I can't handle it : 
```js
ApolloError.js:34 Uncaught (in promise) Error: GraphQL error: Not found
    at new ApolloError (ApolloError.js:34)
    at QueryManager.js:752
    at <anonymous>
```
**Workaround:**
If we replace the fetchPolicy with 'network-only' the error doesn't show up.
Reference issue #1003 

**How to reproduce the issue:**
Throw an error in the backend and use the 'cache-and-network' fetchPolicy in react apollo

**Version**
- apollo-client@1.9.1
- react-apollo@1.4.14

**Comment by dotansimha** [comment]
Same here!

**Comment by perrosnk** [comment]
@Milenkoo have you found a solution?

**Comment by mjasnikovs** [comment]
![image](https://user-images.githubusercontent.com/12757881/38404108-6e62808e-3970-11e8-8a69-c6d8d5374097.png)
I got nice error, without stack.  ¯\_(ツ)_/¯

**Comment by prosyarceno** [comment]
@mjasnikovs have you found a solution?

**Comment by mjasnikovs** [comment]
@prosyarceno I use this component to handle my errors.

```JavaScript
import React from 'react'
import PropTypes from 'prop-types'
import {Message} from 'semantic-ui-react'

const Errors = ({errors}) => {
	if (!errors) {
		return null
	} else if (Array.isArray(errors.graphQLErrors) && errors.graphQLErrors.length) {
		return <Message negative>
			<Message.Header>Kļūda</Message.Header>
			<p>{errors.graphQLErrors.map(val => val.message).join(<br />)}</p>
		</Message>
	} else if (errors.message) {
		return <Message negative>
			<Message.Header>Kļūda</Message.Header>
			<p>{errors.message}</p>
		</Message>
	}
	return null
}

Errors.propTypes = {
	errors: PropTypes.oneOfType([PropTypes.object, PropTypes.bool])
}

export default Errors
```

And this kinda dose what Apollo wants you to do?~!?... Never again will use any of Apollo free software. It's just sad, that idea is so great, but execution...

**Comment by mjasnikovs** [comment]
@prosyarceno The HyperText Transfer Protocol (HTTP) 400 Bad Request response status code indicates that the server could not understand the request due to invalid syntax.
