### ISSUE TITLE
GraphQL error: Cannot query field "<Field>" on type "Mutation"

### ISSUE THREAD

**Issue by Bhavesh-Radadiya** [apollographql/react-apollo#1118]
Mutation query works fine in development mode but it's not working if disabled development and enabled minify js in react-native it gives me the error: 

`GraphQL error: Cannot query field "<Field>" on type "Mutation"`

**Comment by narenvaishnavi** [comment]
I am facing the same problem:
GraphQL error: Cannot query field "<Field>" on type "Mutation"

**Comment by Bhavesh-Radadiya** [comment]
Please provide server URL in createNetworkInterface.

**Comment by narenvaishnavi** [comment]
As in AWS?

**Comment by Bhavesh-Radadiya** [comment]
If you are using AWS hosting then put this type of URL in createNetworkInterface : https://{AWS host:port}/graphql
Replace host and port with your aws server ip and port.
