### ISSUE TITLE
Problems updating cache with store.writeQuery

### ISSUE THREAD

**Issue by Eder87rh** [apollographql/react-apollo#1120]
**Intended outcome:**

Im trying to update the store with store.writeQuery after someone vote or unvote an element in the search Component result

this is the updateCacheAfterVote method

`_updateCacheAfterUnvote = (store, deletedVote, storeId) =>{
        const data = store.readQuery({
            query: ALL_STORES_SEARCH_QUERY,
            variables: { 
                searchText:this.state.searchText
                }  
        })
        console.log(data) 

        const votedStore = data.allStores.find(store => store.id === storeId)

        console.log(votedStore.votes)
        
        votedStore.votes = votedStore.votes.filter((vote) => {
            return vote.id !== deletedVote.id
        })

        console.log(votedStore.votes)
        console.log(data)

        try{
            store.writeQuery({ 
                query: ALL_STORES_SEARCH_QUERY, 
                variables: { 
                    searchText:this.state.searchText
                    },
                data, 
            })
        }catch(e){
            console.log(e)
        }
    }`

and this is my Search component complete

`import React, {Component} from 'react'
import {gql,withApollo} from 'react-apollo'
import { Grid, Cell } from 'react-mdc-web'

import Store from './Store'
import SearchForm from './forms/SearchForm'

class Search extends Component{

    state = {
        stores:[],
        searchText:''
    }

    render(){
        return(
            <Grid>
                <Cell col={2} tablet={1} phone={0}></Cell>
                <Cell col={2} tablet={1} phone={0}></Cell>
                <Cell col={4} tablet={4} phone={12}>
                    <SearchForm onSubmit={(values) => this._executeSearch(values)} />
                </Cell>

                {this.state.stores.map(store => (
                    <Cell key={store.id} col={3} tablet={4} phone={12}>
                        <Store key={store.id} 
                                store={store} 
                                updateStoreAfterVote={this._updateCacheAfterVote}
                                updateCacheAfterUnvote ={this._updateCacheAfterUnvote} >
                        </Store>
                    </Cell>
                ))}
            </Grid>
        )
    }

    _executeSearch = async (values) => {
        this.setState({searchText:values.searchText })

        const result = await this.props.client.query({
        query: ALL_STORES_SEARCH_QUERY,
        variables: { 
            searchText:values.searchText 
            }
        })

        const stores = result.data.allStores
        this.setState({ stores }) 
    }

    _updateCacheAfterVote = (store, createVote, storeId) => {//store(react), (query returned data), (store's id voted)
    const data = store.readQuery({
         query: ALL_STORES_SEARCH_QUERY,
         variables: { 
            searchText:this.state.searchText
            } 
        }) //get current storeReact data

    console.log(data)   
    console.log(createVote.store.votes) 
    
    const votedStore= data.allStores.find(store => store.id === storeId)//get store from <- storeReact
    votedStore.votes = createVote.store.votes //Update store's votes <- query votes
    
    try{
        store.writeQuery({ 
            query: ALL_STORES_SEARCH_QUERY, 
            variables: { 
                searchText:this.state.searchText
            }, 
            data 
        }) //write modified data to storeReact

    }catch(e){
        console.log(e)
    }
  }

    _updateCacheAfterUnvote = (store, deletedVote, storeId) =>{
        const data = store.readQuery({
            query: ALL_STORES_SEARCH_QUERY,
            variables: { 
                searchText:this.state.searchText
                }  
        })
        console.log(data) 

        const votedStore = data.allStores.find(store => store.id === storeId)

        console.log(votedStore.votes)
        
        votedStore.votes = votedStore.votes.filter((vote) => {
            return vote.id !== deletedVote.id
        })

        console.log(votedStore.votes)
        console.log(data)

        try{
            store.writeQuery({ 
                query: ALL_STORES_SEARCH_QUERY, 
                variables: { 
                    searchText:this.state.searchText
                    },
                data, 
            })
        }catch(e){
            console.log(e)
        }
    }

}

const ALL_STORES_SEARCH_QUERY = gql`
query AllStoresSearchQuery($searchText: String!) {
    allStores(filter: {
        OR: [{
            name_contains: $searchText
        }, {
            description_contains: $searchText
        }]
    }) {
        id
        name
        description
        createdAt
        postedBy {
            id
            name
        }
        votes {
            id
            user {
                id
            }
        }
    }
}
`

export default withApollo(Search)`

**Actual outcome:**

Currently the store seems to be updated but the component not shows the votes counter updated. I just can see it after page refresh

the votes counter shows always the same number
![image](https://user-images.githubusercontent.com/17674672/30701100-0f481462-9eaf-11e7-98ea-ac299de56275.png)

this is the console output:
![image](https://user-images.githubusercontent.com/17674672/30701146-2b4b0eb2-9eaf-11e7-8f76-0b312a007b56.png)
we can see here the total of votes is now 21 but never shows in component

**How to reproduce the issue:**

https://codesandbox.io/s/40q538n6y7

Write Acro, press search an when get result clin on upvote button. The counter not going to be update but if you refresh the page yo will see the votes updated

**Version**
- apollo-client@1.9.2
- react-apollo@1.4.15

**Comment by dardub** [comment]
Rather than using internal state and withApollo to manually fetch the search query. You can use the graphql HOC with refetch.

In your example you had to manage state independently in your component along with the apollo store. By switching to the graphql HOC, your "Store" component can rely on props passed down from the apollo store rather than component state.

See the modified example:

https://codesandbox.io/s/l9yxz5o1ol
