### ISSUE TITLE
Mocking graphQLError with MockedProvider

### ISSUE THREAD

**Issue by RodMachado** [apollographql/react-apollo#1127]
Hi everyone, I need some help with testing!

I am trying to write an integration test for an container using MockedProvider wrapper.  
Here's how I'm trying to set it up to return an error:

```js
      const apolloError = new ApolloError({
        graphQLErrors: [new Error('insufficient funds')],
        networkError: null,
        errorMessage: 'GraphQL error: insufficient funds',
      });

      const mocks = [
        {
          request: {
            operationName: 'withdrawFromAccount',
            query: withdrawFromAccountMutation,
            variables: { _id: '123', value: 1000 }
          },
          error: apolloError
        }
      ]
      const container = mount(
        <MockedProvider mocks={mocks}>
          <WithdrawFromAccountContainer _id="123" />
        </MockedProvider>
      );
```

The mutation is triggered by a form submit and here's the function that handles the submit action:
```js
onSubmit: props => async event => {
    try {
      event.preventDefault()
      const mutate = await props.mutate({
        variables: {
          _id: props._id,
          amount: props.amount,
        },
      })

      await props.setErrors([]);
      await props.setAmount('');
    }
    catch({ graphQLErrors }) {
      const errors = graphQLErrors.map(error => error.message);
      props.setErrors(errors);
    }
  }
```
Here's how the error looks like:

```
 {"graphQLErrors":[],"networkError":{"graphQLErrors":[{message: 'insufficient funds'}],"networkError":null},"message":"Network error: GraphQL error: insufficient funds"}
```
It appears that the ApolloError that I'm mocking is returning as a networkError, while the graphQLErrors array is empty.

Any ideas on how to get the ApolloError to be properly returned? Am I wrong in returning ApolloError on the mocked object?  

Cheers!

- apollo-client@1.9.3
- react-apollo@1.4.15
- enzyme@2.9.1
- jest@20.0.4

**Comment by rzane** [comment]
@RodMachado, I'm having the exact same problem. It would be great to get an answer here, and ideally some better documentation for the `MockedProvider`.
