### ISSUE TITLE
MockNetworkInterface no longer matches on variables

### ISSUE THREAD

**Issue by numso** [apollographql/react-apollo#1144]
When testing components that are wrapped in Apollo, the mocks no longer match on variables passed in to the query.

After doing a little digging, it looks like the issue is here: https://github.com/apollographql/react-apollo/blob/master/src/test-utils.tsx#L267. The second parameter to JSON.stringify defines all the valid keys that should be stringified. In the example below, since `search` is not in that list it does not get stringified, leaving us with `variables: {}`. 

**Intended outcome:**
When testing a component whose query and variables don't match any mock, I expect a `No more mocked responses for the query` error to be thrown in the test.

**Actual outcome:**
The component matched a mock instead of throwing an error, even though it had different variables.

**How to reproduce the issue:**
In the following snippet, the mock has the variables `{ search: 'one thing' }` and the component has the variables `{ search: 'something else' }` yet the mock incorrectly satisfies the component's query.

```js
import { delay as sleep } from 'bluebird'
import { mount } from 'enzyme'
import React from 'react'
import { MockedProvider } from 'react-apollo/test-utils'
import { gql, graphql } from 'react-apollo'

it("doesn't match a certain query", async () => {
  const query = gql`
    query TestQuery($search: String) {
      users(q: $search) {
        name
        __typename
      }
    }
  `
  const mocks = [
    {
      request: { query, variables: { search: 'one thing' } },
      result: { data: { users: [{ name: 'Bubba', __typename: 'User' }] } }
    }
  ]
  const UsersSearch = graphql(query)(() => null)
  mount(
    <MockedProvider mocks={mocks}>
      <UsersSearch search='something else' />
    </MockedProvider>
  )
  await sleep(100)
})
```

**Version**
- apollo-client@1.9.1
- react-apollo@1.4.14

**Comment by adambisek** [comment]
I've been struggling on this MockNetworkInterface and had to write my own MockNetworkInterface.
If anyone interested, here's the link: https://github.com/siteone/apollo-mocknetworkinterface
