### ISSUE TITLE
React@16 functions that return arrays will break SSR

### ISSUE THREAD

**Issue by bkniffler** [apollographql/react-apollo#1158]
Using something like
```jsx
export default ({}) => [<Component1 key={1} />,<Component2 key={2} />/]
```
breaks the SSR since it doesn't expect arrays.

Valid since React@16 (https://facebook.github.io/react/blog/2017/09/26/react-v16.0.html)

PR here: https://github.com/apollographql/react-apollo/pull/1157

**Comment by clayne11** [comment]
I added a PR with tests to resolve this.
