### ISSUE TITLE
`data.loading` forever true for re-mounted components that use cached data

### ISSUE THREAD

**Issue by joncursi** [apollographql/react-apollo#1160]
Consider the following example:

1. Sign in
2. Navigate to your user profile. When the component mounts, React Apollo will query your data and render the profile screen. Data is now cached.
3. Sign out (unmount the profile screen / component).
4. Sign back in.
5. Navigate back to your user profile. Your profile will be remounted.

Now, there seems to be a bug in React Apollo in step 5: when you navigate back to your user profile, the component is re-mounted, but your data should be loaded instantly from the cache due to step 2. However the `data.loading` key is forever set to `true` (the data never "arrives").  So if you use loading spinners in your UI (i.e. on over top of the user profile to signify loading), they will spin forever.

Any ideas on why the data isn't being returned for re-mounted components?

**Comment by magicmaaaaan** [comment]
This sounds like https://github.com/apollographql/apollo-client/issues/1186, which has been a pretty long-standing issue.

**Comment by joncursi** [comment]
@magicmaaaaan thank you for referencing that issue! [The workaround posted here](https://github.com/apollographql/apollo-client/issues/1186#issuecomment-323513354) works for me. Seems to be an issue with calling a query -> `apolloClient.resetStore()` -> then query again on the same container. I'll close this down here in favor of that issue which has a lot more action.
