### ISSUE TITLE
Apollo version now requires enzyme and react 16 - breaks my build

### ISSUE THREAD

**Issue by dkoi3d** [apollographql/react-apollo#1161]
**Intended outcome:**

NPM install - application was working just fine before latest update.  I have ensured its the apollo package by removing it and doing in install and it works fine...with apollo it breaks per the below.

**Actual outcome:**

npm WARN enzyme-adapter-react-16@1.0.0 requires a peer of enzyme@^3.0.0 but none was installed.
npm WARN enzyme-adapter-react-16@1.0.0 requires a peer of react@^16.0.0-0 but none was installed.
npm WARN enzyme-adapter-react-16@1.0.0 requires a peer of react-dom@^16.0.0-0 but none was installed.
npm WARN enzyme-adapter-react-16@1.0.0 requires a peer of react-test-renderer@^16.0.0-0 but none was installed.

**How to reproduce the issue:**

Just do an NPM install with apollo package.

**Version**

- react-apollo@<1.4.16>

**Comment by baerrach** [comment]
Google brought me here for the same reason.
What was your resolution for closing?

**Comment by mctep** [comment]
@baerrach I think it will be fixed after next version release with this [changes](https://github.com/apollographql/react-apollo/commit/6e38368e722afcb3b0b3b36a7985e50d52def148)
