### ISSUE TITLE
Calling a mutation with a secondary client

### ISSUE THREAD

**Issue by scruffles** [apollographql/react-apollo#1165]
I have an existing wrapped component that uses a query.  I'm trying to change it to a mutation, but I'm getting errors.

**Intended outcome:**
I would expect the code below to work as-is.

**Actual outcome:**

The error from the console is 
```
Main.cjsx:114 Error: Must contain a query definition.
    at getQueryDefinition (getFromAST.js:75)
    at QueryManager.watchQuery (QueryManager.js:424)
    at ApolloClient.watchQuery (ApolloClient.js:183)
    at GraphQL.createQuery (react-apollo.browser.umd.js:437)
    at GraphQL.updateQuery (react-apollo.browser.umd.js:454)
    at GraphQL.componentWillReceiveProps (react-apollo.browser.umd.js:312)
    at ReactCompositeComponent.js:611
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:610)
    at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js:547)
    at Object.receiveComponent (ReactReconciler.js:125)
    at Object.updateChildren (ReactChildReconciler.js:109)
    at ReactDOMComponent._reconcilerUpdateChildren (ReactMultiChild.js:208)
    at ReactDOMComponent._updateChildren (ReactMultiChild.js:312)
    at ReactDOMComponent.updateChildren (ReactMultiChild.js:299)
    at ReactDOMComponent._updateDOMChildren (ReactDOMComponent.js:936)
```
I believe these errors are triggered because we provide a client in the options rather than using the default client (we're calling multiple GraphQL services from our UI).

Here's the failing code:

```
import {graphql, gql} from 'react-apollo'
import InspectionFailure from './InspectionFailure'
import client from '../../inspections/graphQLClient'

//language=GraphQL
const compiledQuery = gql`
    mutation runInspections($groupId: String!) {
        triggerAutomaticInspectionsOn(entityType: Group, entityId: $groupId) {
            results {
                inspection {
                    id
                    url
                    severity
                }
            }
        }
    }
`

const getOptions = ({groupId}) => ({client, variables: {groupId}})

module.exports = graphql(compiledQuery, {options: getOptions})(InspectionFailure)
```

It works fine if I change lines 7-8 to execute a query with the same return type.  It will also make it past this error if I remove the client from the options (obviously at that point I'm initializing with the wrong client, so I can't actually execute the mutation in the child component).

Debugging in Chrome I found [this suspicious code](https://github.com/apollographql/react-apollo/blob/1b28d92cf1a09fe28c40cbad91b31a0208313663/src/graphql.tsx#L192) that checks if the client is different than the default and runs updateQuery().  I suspect the check for mutations on line 198 should have happened earlier, but I'm not entirely sure what the motivation is for that block of code.

**Version**
- apollo-client@1.9.1
- react-apollo@1.4.15

**Comment by scruffles** [comment]
I ended up working around this by making a manual client call and passing the data to the child component manually. I still maintain it’s a bug, and would love to help however I can. @jbaxleyiii

**Comment by blb451** [comment]
Having this exact same issue.

**Comment by vincentdesmares** [comment]
Same issue here. I got away with a manual call to mutate:

```javascript
     client.mutate({
            mutation: gql`
              mutation myMutation($test: String) {
                myMutation( test: $test)
              }
            `,
            variables: {
              a,
              b
            },
            update: (proxy, { data: { createTodo } }) => {}
          })
``` 

It looks like the code of the future versions [is using HOCs](https://github.com/apollographql/react-apollo/blob/master/src/Mutation.tsx). Hopefully this bug will be gone as the related code is no more.
