### ISSUE TITLE
[2.0] Update docs and all examples to import gql from graphql-tag

### ISSUE THREAD

**Issue by peggyrayzis** [apollographql/react-apollo#1166]
Before we release 2.0, we need to communicate to everyone that `gql` will no longer be exported from `react-apollo`.

- [ ] Update README
- [ ] Update docs site
- [ ] Update examples

**Comment by stefanmaric** [comment]
I'm trying apollo 2 and getting issues specifically with this. From where should I be pulling `gql`? `apollo-client`?

**Comment by jaydenseric** [comment]
@stefanmaric `import gql from 'graphql-tag'`

**Comment by stefanmaric** [comment]
> @stefanmaric import gql from 'graphql-tag'

Thanks! Did that but now I'm lost on where should I get  `graphql` from, since it is not provided by `graphql-tag`.

**Comment by stefanmaric** [comment]
> Thanks! Did that but now I'm lost on where should I get graphql from, since it is not provided by graphql-tag.

Alright, so probably `graphql-evevrywhere`. I added the beta version but getting this error:

`Error: Expecting a parsed GraphQL document. Perhaps you need to wrap the query string in a "gql" tag? `

**Comment by jaydenseric** [comment]
@stefanmaric not sure what you mean; pretty sure `import { graphql } from 'react-apollo'` still works.

**Comment by stefanmaric** [comment]
@jaydenseric so I might be doing something wrong or I'm using a buggy version.

```shell
$ npm ls --depth=0
├── apollo-cache-inmemory@0.2.0-beta.4
├── apollo-client@2.0.0-beta.4
├── apollo-link@0.6.1-beta.6
├── apollo-link-http@0.6.1-beta.6
├── graphql@0.10.5
├── graphql-anywhere@4.0.0-beta.3
├── graphql-tag@2.4.2
├── react@16.0.0
├── react-apollo@2.0.0-beta.0
├── react-dom@16.0.0
└── subscriptions-transport-ws@0.9.0
```

My apollo client initialization:

```jsx
import React from 'react'
import ReactDOM from 'react-dom'

import App from './components/App'

import { ApolloLink } from 'apollo-link'
import { ApolloProvider } from 'react-apollo'
import ApolloClient from 'apollo-client'
import InMemoryCache from "apollo-cache-inmemory";
import Link from 'apollo-link-http'

const httpLink = new Link({ uri: '/graphql' })

const middlewareLink = new ApolloLink((operation, forward) => {
  const token = localStorage.getItem('token')

  operation.setContext({
    headers: {
      authorization: token ? `Bearer ${token}` : null
    }
  })

  return forward(operation)
})

const link = middlewareLink.concat(httpLink)

const client = new ApolloClient({
  link: link,
  cache: new InMemoryCache()
})

ReactDOM.render(
  <ApolloProvider client={client}>
    <App />
  </ApolloProvider>
  , document.getElementById('root')
)
```

Component breaking on graphql:

```jsx
import { Component } from 'react'
import gql from 'graphql-tag'
import graphql from 'apollo-client'

class Link extends Component {
  // component code here
}

const CREATE_VOTE_MUTATION = gql`
mutation CreateVoteMutation($userId: ID!, $linkId: ID!) {
  createVote(userId: $userId, linkId: $linkId) {
    id
    link {
      votes {
        id
        user {
          id
        }
      }
    }
    user {
      id
    }
  }
}
`

export default graphql(CREATE_VOTE_MUTATION, {
  name: 'createVoteMutation'
})(Link)
```

Getting this error:

![image](https://user-images.githubusercontent.com/1009040/31237316-3329ab44-a9bc-11e7-8dc5-eaf5471ed12d.png)

**Comment by peggyrayzis** [comment]
Hi @stefanmaric! You should be importing the `graphql` higher order component from `react-apollo`. Let me know if that fixes it! 😀

**Comment by stefanmaric** [comment]
> You should be importing the graphql higher order component from react-apollo.

Damn, how stupid me. That was it!

Thank you all and sorry to waste your time. 💚

**Comment by AllUsernamesHaveBeenTaken** [comment]
I have this issue when using graphql from react-apollo. I also wrap it with gql just like Stefan did.

Expecting a parsed GraphQL document. Perhaps you need to wrap the query string in a "gql" tag? http://docs.apollostack.com/apollo-client/core.html#gql
