### ISSUE TITLE
graphql typescript decorator

### ISSUE THREAD

**Issue by SergeShkurko** [apollographql/react-apollo#1174]
**Intended outcome:**
If add a any method except render() typescript begins to resent

**Actual outcome:**

Only render() method
![default](https://user-images.githubusercontent.com/18213789/31048217-47060384-a632-11e7-8316-4dbff708f01f.PNG)

With any method
![2](https://user-images.githubusercontent.com/18213789/31048272-6495999a-a633-11e7-9527-58a36699f326.png)

And error occurs when render method return type only JSX.Element with out "false"
![3](https://user-images.githubusercontent.com/18213789/31048273-6ba9894e-a633-11e7-9cb4-98f9c89320e0.png)

React works normally in all cases

**How to reproduce the issue:**
Repair typescript types

**Version**
- apollo-client@1.4.16
- react-apollo@1.9.3

**Comment by jimkyndemeyer** [comment]
I came across this as well.

It appears to be a limitation in how TypeScript handles "contextual types": https://github.com/Microsoft/TypeScript/issues/19212

**Comment by jimkyndemeyer** [comment]
For anyone else running into this, here's a workaound:

I've redefined the `graphql` decorator with the return type as `any`. It simply invokes the original graphql decorator.

```
import {graphql as __graphql, OperationOption} from 'react-apollo';

export function graphql<TProps, TResult>(gqlQuery, operationOptions?: OperationOption<TProps, TResult>): any {
    return __graphql(gqlQuery, operationOptions);
}
```

Import the `@graphql` decorator you defined and the TS compiler will no longer complain about the `render()` method having an incompatible type.
