### ISSUE TITLE
Add a way to easily select data from apollo + redux store.

### ISSUE THREAD

**Issue by jjant** [apollographql/react-apollo#1175]
I'm finding it hard to select data from my redux store that depends on both, current redux state and data fetched by Apollo.

An example is the following: I have an `options` model, which has `id, name` properties. These `options` are fetched by apollo from the server. In a form, I have a select field, in which I store a selected option ID (which I use in a mutation, to change the currently selected option).

Now, sometimes I need to pass the currently selected option (stored in redux) name, to another component, for this, I have to do something a bit ugly like the following:

```jsx
const optionNameSelector = ({ options, optionId }) => options.find(option => option.id === optionId);

// And in the component I want:
// ...
const optionName = optionNameSelector({ options: data.options, optionId: state.optionId });
<MyComponent optionName={optionName} />
```

So my component has to know where to get the `options` from, instead of being able to just pass the whole state or something like that.

What's a better solution for this? I think having a denormalized apollo state in the redux store would be nice.

**Comment by blackxored** [comment]
Definitely a +1 for this. Accessing `store` directly needs you to couple it to the shape itself. A common case is to prepare optimistic response by adding the current user (i.e name, avatar).

**Comment by simontegg** [comment]
Yes I find the [reselect](https://github.com/reactjs/reselect) API much easier to work with than the `readQuery`  syntax

**Comment by rosskevin** [comment]
Apollo no longer uses redux.

**Comment by rosskevin** [comment]
Apollo is no longer based on a redux store.  If I'm understanding the issue correctly, this was originally filed with that in mind.  I'm going to close this issue based on that understanding - if I have it wrong please ping me and I'll reopen.
