### ISSUE TITLE
[2.0] Authentication and connecting to redux store

### ISSUE THREAD

**Issue by churcho** [apollographql/react-apollo#1182]
I would like to port an [existing](https://github.com/jferrettiboke/react-auth-app-example/) codebase to use apollo 2.0. A great deal of my confusion is at the store [instantiation](https://github.com/jferrettiboke/react-auth-app-example/blob/master/client/src/index.js#L38), 

How can I approach this? Should I use `setContext ` or `apollo-fetch` and how is that token header implementation supposed to look like?

How can I use it with redux and do I need to instantiate ApolloProvider providing the store?

**Comment by n1ru4l** [comment]
@churcho Authentication: https://github.com/apollographql/apollo-client/issues/2168#issuecomment-334122648
