### ISSUE TITLE
[2.0] variables are not working with cached data

### ISSUE THREAD

**Issue by seeden** [apollographql/react-apollo#1192]
I have component which is used with react-router.
```js
@graphql(PROFILE_CONTAINER_QUERY, {
  options: ({ match: { params: { username } } }) => ({
    variables: {
      username,
    },
  }),
})
```
Everything works fine until I will click on back button in the browser.

I can see that my component is rerendered but I can see old data from previous page. Variable username has correct value but react-apollo is using old variable.

```
    "apollo-cache-inmemory": "^0.2.0-beta.3",
    "apollo-client": "^2.0.0-beta.3",
    "apollo-fetch": "^0.6.0",
    "apollo-link-batch-http": "^0.2.1-beta.6",
    "apollo-link-http": "^0.6.1-beta.6",
    "react-apollo": "^2.0.0-beta.0",`
```

**Comment by hlehmann** [comment]
same issue. data changes after a request response but when returning to a previous set of variables, data doesn't change.

**Comment by hlehmann** [comment]
@seeden I revert apollo-client to 2.0.0-beta.2 as a temp fix. Is it the same for you ?

**Comment by mutewinter** [comment]
Reverting to apollo-client to 2.0.0-beta.2 did not resolve the issue for me.

**Comment by makamekm** [comment]
It still doesn't work!

**Comment by tylerjbainbridge** [comment]
Also having trouble with this.

**Comment by karmajunkie** [comment]
Not 100% sure its from the same cause, but this sounds very similar to some behavior I'm seeing where cached variables seem to be getting passed into my query even though they're correct going into the fetch. I've tried it with network-only as a fetch policy and that doesn't seem to matter. It seems to kick in when a query returns an empty collection for a list return type (i.e. if my query returns  a list of people, after a query returns an empty list I start seeing the cached arguments going into queries.)

**Comment by hwillson** [comment]
This should no longer be an issue with current versions of React Apollo. Thanks!
