### ISSUE TITLE
reducer on client.query options does not appear to be fired

### ISSUE THREAD

**Issue by JofArnold** [apollographql/react-apollo#1193]
Using the `withApollo` HOC I'm doing a query per below (the documentation suggests it's possible http://dev.apollodata.com/core/apollo-client-api.html#ApolloClient.query)

```
this.props.client.query({
  query: doc,
  reducer: someReducer,
  variables: ...
});
```

I would expect `someReducer` to be fired with arguments however that does not appear to be the case; it is not fired at all.

- apollo-client@1.9.3
- react-apollo@1.4.15

**Comment by JofArnold** [comment]
Bumping to stop auto close.

**Comment by JofArnold** [comment]
Bumping again

**Comment by hwillson** [comment]
`query` no longer supports `reducer`. Closing - thanks!
