### ISSUE TITLE
[2.0] error in data prop from HOC is undefined when query has an error

### ISSUE THREAD

**Issue by bogdansoare** [apollographql/react-apollo#1206]
Trying to access the **error** property of the **data** object from HOC returns undefined even when a query has an error.

**Version**
- apollo-client@2.0.0-beta.4
- react-apollo@2.0.0-beta.0
- apollo-link@0.7.0
- apollo-link-http@0.7.0

**Comment by bogdansoare** [comment]
I've recreated the issue on codesandox https://codesandbox.io/s/lrwvwr41pl

**Comment by bogdansoare** [comment]
@jbaxleyiii could you please take a look at the issue. Thanks

**Comment by jbaxleyiii** [comment]
@bogdansoare thanks so much! sorry I missed this early on! It will be fixed via https://github.com/apollographql/apollo-client/pull/2491

**Comment by bogdansoare** [comment]
@jbaxleyiii no worries, thank you for the all the effort ❤️

**Comment by jbaxleyiii** [comment]
@bogdansoare Fixed with `apollo-client2.0.2`!
