### ISSUE TITLE
Unable to catch or handle polling errors

### ISSUE THREAD

**Issue by dotansimha** [apollographql/react-apollo#1216]
When using `pollingInterval` and the server throws an error, the polling error is thrown in another stack trace, causing it to be an unhandled promise rejection error.

This issue might be related:
https://github.com/apollographql/react-apollo/issues/1117
Because the stack trace is the same, and I can't handle the error.

**Intended outcome:**
Component should update and expose `error` inside the `data`.

**Actual outcome:**
Error is thrown and I'm unable to catch it.

```
ExceptionsManager.js:73 Unhandled promise rejection Error: GraphQL error: test-error
    at new ApolloError (apollo.umd.js:1981)
    at apollo.umd.js:3517
    at run (es6.promise.js:66)
    at es6.promise.js:79
    at flush (_microtask.js:18)
    at tryCallOne (core.js:37)
    at core.js:123
    at JSTimers.js:295
    at _callTimer (JSTimers.js:148)
    at _callImmediatesPass (JSTimers.js:196)
```

**How to reproduce the issue:**
Defined a component with `pollingInterval` and cause the server to throw an error.

**Version**
- apollo-client@1.9.3
- react-apollo@1.4.16

**Comment by maka-io** [comment]
Any word on this, it's an issue for me as well.

**Comment by dotansimha** [comment]
@maka-io fixed in apollo-client 2 (in the >beta6 of the package).
