### ISSUE TITLE
[2.0] apolloClient.writeQuery not update componentProps

### ISSUE THREAD

**Issue by zapkub** [apollographql/react-apollo#1218]
Sometime I update store outside React by using `writeQuery()`, I just try ApolloClient 2.0 everything fine except my component doesn't update after call `writeQuery`

**Intended outcome:**
Component props must update data after `writeQuery`

**Actual outcome:**
I take a screenshot of my console, in console after `writeQuery` I call `readQuery` on my sagas,

after that I log data in my container file from HOC and data from `readQuery`

<img width="1039" alt="screen shot 2017-10-09 at 11 00 51" src="https://user-images.githubusercontent.com/4373581/31324857-2a07e512-ace1-11e7-841d-c473eb985a11.png">

**How to reproduce the issue:**
```
// container
graphql<{ profile: UserProfile }, {}>(Query, {
    options: {
      fetchPolicy: 'cache-and-network'
    },
    props: ({ data, ownProps }) => {
      console.log('data from HOC', data.profile)
      if (data.profile) {
        console.log('data from readQuery', ownProps.client.readQuery({query: Query}).profile)
      }
      return ({ value: data.profile || { firstName: '', lastName: '' } })
    }
  })(FormComponent)
```

```
// saga file
      profileQueryResult.profile[fieldName] = value
      apolloClient.writeQuery({
        query: Query,
        data: {
          ...profileQueryResult
        }
      })
      yield put({ type: 'form/updated' })
      console.log(apolloClient.readQuery<{ profile: UserProfile }>({
        query: Query
      }).profile)
```

**Version**
- apollo-client@2.0.0-beta.4
- react-apollo@2.0.0-beta.0

**Comment by esseswann** [comment]
I have a similar problem tough I don't use sagas, just calling update() from mutation. The writeQuery call passes checks but nothing gets updated. With previous redux based cache the same function was working well

**Comment by zapkub** [comment]
I thought I am the only one who see this problem. 

could you provide some advice for us ? @jbaxleyiii

**Comment by zapkub** [comment]
Update:
I found this bug is relate to apollo client itself https://github.com/apollographql/apollo-client/issues/2415

**Comment by zapkub** [comment]
I think this can be close for now until the next version release

**Comment by scottmcpherson** [comment]
I'm sure everyone is trying to write to the cache differently, but here's what ended up working for me:

```
this.props.client.store.cache.writeQuery({
   query: CURRENT_USER_QUERY,
   data: { currentUser }
})
```

Notice that I'm writing directly to the stores cache
