### ISSUE TITLE
flow 0.56 not work

### ISSUE THREAD

**Issue by unordered** [apollographql/react-apollo#1220]
### react-apollo.umd.js.flow line 125 and 136
```
export interface OperationComponent<
  TResult: Object = {},
  TOwnProps: Object = {},
  TMergedProps = ChildProps<TOwnProps, TResult>,
> {
  (
    component:
      | StatelessComponent<TMergedProps>
      | Class<React$Component<any, TMergedProps, any>>,
  ): Class<React$Component<void, TOwnProps, void>>, // error 1 at this line #line number 125
}

declare export function withApollo<TProps>(
  component:
    | StatelessComponent<TProps & ApolloClient>
    | Class<React$Component<any, TProps & ApolloClient, any>>, // error 2 at this line #line number 136
): Class<React$Component<void, TProps & ApolloClient, void>>;
```

### the error 1 is
```
type application of identifier `React$Component`
Too many type arguments. Expected at most 2
See type parameters of definition here
: /private/tmp/flow/flowlib_1a8363d6/react.js:27
```

### the error 2 is
```
identifier `React$Component`
Too few type arguments. Expected at least 1
See type parameters of definition here
: /private/tmp/flow/flowlib_1a8363d6/react.js:27
```

**How to reproduce the issue:**
upgrade flow to v0.56

**Version**
- apollo-client@1.9.3
- react-apollo@1.4.16

**Comment by gforge** [comment]
I fixed this but it was reverted in #1125 - seems that there is an issue with apollo-client that first needs resolving @jbaxleyiii

**Comment by TSMMark** [comment]
What's the latest here? Would love for recent flow support

**Comment by TSMMark** [comment]
@gforge does your fix work and what is the commit hash?

**Comment by gforge** [comment]
@TSMMark I've updated the tests and definitions so that it should work - not really happy with how fragile Flow is in these cases. The complexity is somewhat overwhelming and the flexibility in flow is far from what I would like to see.
