### ISSUE TITLE
Wrapped component never gets updated after an error

### ISSUE THREAD

**Issue by jay1337** [apollographql/react-apollo#1229]
**Intended outcome:**
I have a React component wrapped with the `graphql` function to get data from a GraphQL query.
The query is called on mounting, on `this.props.data.refetch()`, or at some time if `pollInterval` is set.
If any of these calls fails, I expect the component to be updated if a new call succeed, so that:

- I can add a "Retry" button to let the user manually trigger a refetch if the first call on mounting failed. If the refetch succeeds then the `data.error` prop changes to `undefined` and the component gets updated with the data received.
- If `pollInterval` is set and if at some point the network connection is lost, then when the connection is back the polling works as if the connection was never lost. So I want the polling to continue even if a poll has failed in the past and I want the component to be updated if new data is available (coming from a new poll of the same request or from the result of any other query or mutation in the app)

**Actual outcome:**
After an error, `data.error` remains defined and component never gets updated, even if `data.refetch` is called or if `pollInterval` is set.

**My understanding:**
Basically, when there is a network error, observers are unsubscribed. Thus any refetch only update Apollo store but does not trigger a rerender of the component.
I think it's the expected behaviour of the `cleanupSubscription` call in https://github.com/apollographql/apollo-link/blob/master/packages/zen-observable-ts/src/zenObservable.ts
Which is called through `obs.error(error)` in https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/ObservableQuery.ts
But I think `react-apollo` should resubscribe to the query after an error to keep the component updated when new data arrive in the cache (after a `data.refetch`, a poll, or any other query or mutation in the app).

**Version**
- apollo-client@2.0.0-beta.4
- react-apollo@1.4.16

This is the issue asked here https://github.com/apollographql/apollo-client/issues/1186#issuecomment-335508326

**Comment by jay1337** [comment]
Hey !

**Comment by msmfsd** [comment]
BUMP - this is an important issue with v2 - can someone please look at this?

Basically data.error is not cleared on refetch.

**Comment by lnikkila** [comment]
We’re seeing this as well with newer versions of dependencies:

```
apollo-cache-inmemory@1.0.0
apollo-cache@1.0.0
apollo-client@2.0.1
apollo-link-context@1.0.0
apollo-link-dedup@1.0.0
apollo-link-error@1.0.0
apollo-link-http@1.0.0
apollo-link@1.0.0
apollo-utilities@1.0.0
react-apollo@2.0.0
```

**Comment by leethree** [comment]
I'm seeing the same problem with React-Apollo 2.0. The wrapped components are not re-rendered after `data.refetch()`.

**Comment by msmfsd** [comment]
related to https://github.com/apollographql/apollo-client/issues/2513#issuecomment-343954652

**Comment by jozanza** [comment]
Setting `pollInterval` also seems to have no effect for me in `apollo-client@2.0.3` and `react-apollo@2.0.1`

**Comment by slonoed** [comment]
Did anyone found a workaround for it?

**Comment by jay1337** [comment]
@slonoed you can change

```
                        assign(data, (this.queryObservable.getLastResult() || {}).data);
```

by

```
                        assign(data, (this.queryObservable.getLastResult() || {}).data, { retry: () => {
													this.unsubscribeFromQuery();
													this.queryObservable = null;
													this.previousData = {};
			                    this.updateQuery(this.props);
			                    if (!this.shouldSkip(this.props)) {
			                        this.subscribeToQuery();
			                    }
												} });
```

around line 560 of `node_modules/react-apollo/react-apollo.browser.umd.js`

It will pass a `retry` function to the component that you can call with `this.props.data.retry()`.

**Comment by slonoed** [comment]
@jay1337 thanks! I don't really want to change library code.
Did you consider to make a PR? 

Also, I'm curious:
Is it possible to spin up a new query from app code?

**Comment by jay1337** [comment]
I don't have time for a PR and I don't think it would be merged (since
maintainers don't seem to have time for github issues...).

You can fork the repo and apply my patch if you need it.

I forgot to mention that the retry function will be available only when
there is an error (this.props.data.error = true).

Le 23 janv. 2018 15:39, "Dmitry Manannikov" <notifications@github.com> a
écrit :

**Comment by 0m15** [comment]
any news about this issue? I'm experiencing it as well with freshly installed apollo client:
    
    "react-apollo": "^2.0.4"
    "apollo-client-preset": "^1.0.6"

**Comment by mephju** [comment]
I'm also experiencing this.
` "apollo-client": "^2.2.8"
"react-apollo": "^2.1.3"`

**Comment by jasonpaulos** [comment]
Hi everyone! PR #3107 solves the problem of resubscribing to the observable after _all_ errors. If anyone still wants to pursue an explicitly 'retry' mechanism, I suggest that you make an issue here: https://github.com/apollographql/apollo-feature-requests/issues Thanks!
