### ISSUE TITLE
How to use the "client" option on the server.

### ISSUE THREAD

**Issue by j** [apollographql/react-apollo#1232]
See this comment: https://github.com/apollographql/react-apollo/issues/1232#issuecomment-339783150

I noticed when using multiple clients, it's a pain on the server side to pass around client instances per request.  This is managed with a single client b/c it's in the context.

A comment suggests to use it like so:

```js
import MyOtherClient from "../other-client"

export default graphql(MyQuery, {
  client: MyOtherClient,
})(MyComponent);
```

However, on the server, this is a lot harder.  You'd have to have a container hoc that stores the extra clients and passes them down as a prop to the graphql wrapped component which seems kind of ugly.

What's a clean way to do this?

**Comment by j** [comment]
I'm trying to create a pullable example of this issue, but just realized that my app creates a client and passes the initialState to it on redux execution.  The client option would be simple without this.  I think the "client" option should have instead been "networkInterface" to switch interfaces and re-use the same client?  Or how can I go about re-using a created client.  The only way I can think of is to use something like context to store the created clients, but that will get ugly fast.

**Comment by j** [comment]
Also, unrelated maybe, but why does ApolloProvider require a redux store and the client have an initialState option?

**Comment by j** [comment]
Just saw that 2.0 is coming soon.  Redux is no longer the store, which makes me now question if the clients and defaultClient props fit now since collisions shouldn't happen if stores are managed in each client independently.

**Comment by j** [comment]
Just got back to this issue.  What I'm finding a pain is that the graphql hoc re-uses client form the ApolloProvider context.  So on server render, it's easy to pass the client + cache down to my wrapped component.  The way to get around it is to create my own wrapped component and pass my second client in the context and use recompose or so to add it to the props then use that prop in the client options configuration.. This just seems way harder and more painful to do than just having it be like:

```js
// this uses defaultClient
const Store = graphql(..., {
  // ...
};

const Repositories = graphql(..., {
  options: () => ({
    client: 'github'
  })({ ... }) => {
  // ...
};

<ApolloProvider clients={{ shopify, github }} defaultClient={shopify}>
  <App>
    <Store />
    <Repositories />
  </App>
</ApolloProvider>
```

In comments, I see this example:
```js
import MyOtherClient from "../other-client"

export default graphql(MyQuery, {
  client: MyOtherClient,
})(MyComponent);
```

which is great and clean... until you want to do this on the server side.  Thoughts?

/cc @jbaxleyiii @flexzuu

**Comment by j** [comment]
I created this PR to see if this method fixes my SSR issues and it does: https://github.com/apollographql/react-apollo/pull/1292

**Comment by flexzuu** [comment]
Hey I just saw your mention so sry for the late reply. At my company we don't use SSR so i have Thoughts to give. But i think the most versatile would be to set the client via props. Then you can add it via a contex hoc or whatever you desire.

**Comment by hwillson** [comment]
Since there hasn't been any recent activity here, and this issue was opened for React Apollo 1.x, we'll close this for now. Please try using a 2.x version of React Apollo and post back if this is still an issue. Thanks!
