### ISSUE TITLE
Immutable JS Data from apollo

### ISSUE THREAD

**Issue by fenos** [apollographql/react-apollo#1237]
Hi, 

We are trying to implement `react-apollo` in our react app 🎉  one of the blocker that we came across is: 

How can I tell the `apollo-client` that I want the data stored into `redux-store` as an immutable object?

So that i can access it in this way:

```js
const MyGqlComponent = ({data}) {
   return <div>data.myquery.get('myField')</div>;
}
```

I remember in the previous versions there was a prop called `immutable` available in the `ApolloProvider` that allowed me to do exactly that!

it doesn't seem to be there anymore, any help please

**Comment by fenos** [comment]
Please can someone help with this

**Comment by hwillson** [comment]
Since there hasn't been any recent activity here, we'll close this for now. Please try using a more recent version of React Apollo and post back if this is still an issue. Thanks!
