### ISSUE TITLE
The whole site fails when a single SSR query fails.

### ISSUE THREAD

**Issue by coyolero** [apollographql/react-apollo#1253]
I'm using the example from code [here](http://dev.apollodata.com/react/server-side-rendering.html#renderToStringWithData) for SSR.

```
import { renderToStringWithData } from "react-apollo"
const client = new ApolloClient(....);

renderToStringWithData(app).then((content) => {
  const initialState =  client.getInitialState();
  const html = <Html content={content} state={initialState} />;
  res.status(200);
  res.send(`<!doctype html>\n${ReactDOM.renderToStaticMarkup(html)}`);
  res.end();
});

```

It works great, now all my components that have the `graphql` HOC will retrieve the data.

But, if I a query fails, the whole site will crash because of a single fail on a query.

**Intended outcome:**
If a query fails, I should be able to handle that error. 
The site should continue working normally but without that piece of data.

**Version**
- react-apollo@1.4.15

**Comment by coyolero** [comment]
@jbaxleyiii 

Am I missing some other configuration?

**Comment by flipxfx** [comment]
Having this issue also. It's hard to pinpoint exactly where the error needs to be fixed, but I do know before apollo-link-http 1.3.2 it's fine and doesn't crash.

**Comment by amannn** [comment]
There's an existing issue about this: #615. It's been closed due to inactivity, but I think it's still important.

**Comment by amannn** [comment]
Apparently [this is fixed now](https://github.com/apollographql/react-apollo/issues/615#issuecomment-459692471). I didn't have time to verify this yet though.

**Comment by hwillson** [comment]
This should no longer be an issue with current day `react-apollo`. Thanks!
