### ISSUE TITLE
GraphQL HoC doesn't re-render with data.error set when GraphQL error occurs

### ISSUE THREAD

**Issue by jimkyndemeyer** [apollographql/react-apollo#1257]
**Intended outcome:**

To access `data.error` inside a `graphQL` HoC wrapped component to do error handling.

**Actual outcome:**

The `data.error` prop is never passed to the child as expected. I did a little digging and it appears that the logic to prevent unnecessary re-renders in the `graphql` HoC doesn't take the error state into consideration and uses stale data props.

**How to reproduce the issue:**

I've updated your Apollo 2.0 Client example to illustrate the issue: https://codesandbox.io/s/pyp1zw702q

See the use of `data.error` in `list.js`. I console log when an error occurs using the apollo-link-error setup in `index.js`

**Version**
- apollo-client@2.0.0-rc.1
- react-apollo@2.0.0-beta.0

**Comment by mattiasewers** [comment]
This is an issue for me as well.

**Comment by jimkyndemeyer** [comment]
This issue appears to be more critical than I initially thought.

I'm now seeing stale data.props that are out of sync with what is in the InMemoryCache after mutations. See the attached screenshot which demonstrates a customer name being out of sync.

![image](https://user-images.githubusercontent.com/15837712/31819538-6248d930-b59d-11e7-9343-77454d8af4b4.png)

**Comment by mitjade** [comment]
Same problem for me.

**Comment by niklasvh** [comment]
Experiencing same issue, the `error` prop never seems to return anything else than `undefined`, and when a component that had an `error` gets unmounted, it throws an `Unhandled error` error right after.

**Comment by muuki88** [comment]
[This test](https://github.com/apollographql/react-apollo/blob/apollo-client-2.0/test/react-web/client/graphql/queries/errors.test.tsx#L128-L166) should validate that this actually works. Is the {{error}} field only for non-graphql errors (e.g. network failure, 5xx responses, etc.)?

**Comment by jimkyndemeyer** [comment]
As far as I can tell, the test doesn't cover the optimization logic in render: https://github.com/apollographql/react-apollo/blob/master/src/graphql.tsx#L604-L622

It focuses mainly on componentWillReceiveProps which is no guarantee that the wrapped component will be given the right props during render.

**Comment by mitjade** [comment]
With apollo-client 2.0.2 the `error` now get's correctly set for me, but I still get the `Unhandled error` error right after.

**Comment by hwillson** [comment]
This should no longer be an issue with current versions of React Apollo. Thanks!
