### ISSUE TITLE
Not working with CDN

### ISSUE THREAD

**Issue by ravilution** [apollographql/react-apollo#1266]
Can you please add the distribution to cdnjs.com similar to every other react libraries. For example https://cdnjs.cloudflare.com/ajax/libs/react-relay/0.10.0/relay.min.js. Thanks in advance.

**Comment by ravilution** [comment]
I also tried using `https://unpkg.com/react-apollo@2.0.0/react-apollo.umd.js`. But there is a lot of dependency issues :-(

**Comment by ravilution** [comment]
The code structure and built files are not resolving one another. 
https://www.jsdelivr.com/package/npm/react-apollo

Can you share an example react app running in browser with apollo libraries loading from CDN? Thanks in advance.

**Comment by devth** [comment]
+1

**Comment by wombat86** [comment]
@jbaxleyiii any updates on this? This issues has a significant footprint on the bundle size.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, React Apollo feature requests are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Not%20working%20with%20CDN&body=Migrated%20from:%20apollographql/react-apollo%231266) to start the feature request migration process. This manual migration process is intended to help identify which of the outstanding feature requests are still considered to be of value to the community. Thanks!
