### ISSUE TITLE
Bunch of flow errors

### ISSUE THREAD

**Issue by marcel-devdude** [apollographql/react-apollo#1267]
Hey,

i got a bunch of flow errors with the following versions.

**Intended outcome:**
No flow errors

**Actual outcome:**

53 errors, like that:

```
Error: node_modules/apollo-client/node_modules/graphql/validation/rules/OverlappingFieldsCanBeMerged.js.flow:637
637:     return type1 instanceof GraphQLList ?
                                 ^^^^^^^^^^^ GraphQLList. This type is incompatible with
628:   type1: GraphQLOutputType,
              ^^^^^^^^^^^^^^^^^ union: GraphQLScalarType | GraphQLObjectType | GraphQLInterfaceType | GraphQLUnionType | GraphQLEnumType | type application of class `GraphQLList` | type application of class `GraphQLNonNull`
```

**How to reproduce the issue:**
New project with flow, react-apollo, apollo-client.

.flowconfig
```
[ignore]

[include]

[libs]

[lints]

[options]
esproposal.decorators=ignore
```

**Version**
- apollo-client@1.9.3
- react-apollo@1.4.16
- flow-bin@0.57.3

**Comment by mimccio** [comment]
Same here.

https://github.com/apollographql/react-apollo/issues/1105 was closed but it still doesn't work

**Comment by jaredly** [comment]
This is still broken :/ @jbaxleyiii plz halp

**Comment by hwillson** [comment]
React Apollo no longer supports flow (we're all in on Typescript). Thanks!
