### ISSUE TITLE
Clarification needed (possible bug) on fetchPolicy cache-and-network

### ISSUE THREAD

**Issue by Panoplos** [apollographql/react-apollo#1271]
I have an HOC react container that composes in a `graphql` query with `fetchPolicy` set to `cache-and-network`. When the query's `loading` state is set (i.e. when it fetches from the server), I display a Loading component via `recompose` `branch`. When the data is fetched from cache, loading is never set, which is good, as it avoids mounting the Loading component. However, after the cache read, during the network fetch, the `react-apollo` HOC's `loading` property is getting set, which is causing a _bounce_ of sorts in the base component's mounting. So, I get the following flow:

Apollo Query => Cache => Base Component Mounts => Apollo Network Fetch => Loader Mounts => Base Component Mounts

This is not desirable, as loading in the case of `cache-and-network` should be transparent to the Base Component...otherwise what is the point of this fetch policy?

I would expect the following flow:

Apollo Query => Cache => Base Component Mounts => Apollo Network Fetch (sans loading state) => Update Cache => Base Component Gets New Props

In the scenario that the cache doesn't exist, then the network fetch is immediate and loading is set, as one would normally expect.

Is this an absurd assumption? Have I completely missed the point of the `cache-and-network` fetch policy?

**Version**
- apollo-client@1.9.3
- react-apollo@1.4.16

**Comment by clayne11** [comment]
Anytime data loading from the network the `loading` prop will be set. It's up to your component to decide how to handle this situation.

In the case where you already have data from the cache you can decide to not show the loading component. Other people may want to handle it differently, though, so it makes sense to set the `loading` prop anytime the network is being hit.

**Comment by Panoplos** [comment]
Hello Clayne, is there a suggested way to go about this? I mean, if I were to depend on the current functionality, I would have to make every single reference to my query result check `loading`, which is a massive amount of repetitive code. In order to avoid this, I have implemented a catch-all, as it were, in a `branch` Loader, which causes the base component's mount sequence to bounce on `cache-and-network` fetches. I have animations on certain components that this behaviour interferes with.

If the `cache-and-network` refetch silently queried the server and updated the props, it seems like it would make this type of fetch policy meaningful. Again, am I missing something with regards to the usefulness of this policy?

**Comment by Panoplos** [comment]
OK, I think I have figured this out after a little testing. It seems that the cached value is being returned by the query, even if `loading` is set, so I can simply ignore loading and check for the existence of the result data, instead. This way I am avoiding the bouncing phenomenon. Somethin that explains this may be good for the documentation. :-)
