### ISSUE TITLE
Can't resolve 'graphql/language/printer'

### ISSUE THREAD

**Issue by mech** [apollographql/react-apollo#1274]
Using these deps:

```
"apollo-cache-inmemory": "^1.0.0",
"apollo-client": "^2.0.1",
"apollo-link": "^1.0.0",
"apollo-link-http": "^1.0.0",
"react": "^16.0.0",
"react-apollo": "^2.0.0",
```

I am getting this strange `Module not found: Can't resolve 'graphql/language/printer' in apollo-client`

I thought we're using graphql-tag?

**Comment by spencercarli** [comment]
I had to explicitly add `graphql` to my project dependencies to get this error to go away.

**Comment by nfatah** [comment]
@spencercarli could you elaborate. thanks

**Comment by spencercarli** [comment]
I just ran `yarn add graphql`, restarted the React Native packager and this particular error went away. Still trying to figure out the rest of it 😄

**Comment by mech** [comment]
Okay, just so everyone can get it to work, you need these:

```
"apollo-cache-inmemory": "^1.0.0",
"apollo-client": "^2.0.1",
"apollo-link": "^1.0.0",
"apollo-link-error": "^1.0.0",
"apollo-link-http": "^1.0.0",
"graphql": "^0.11.7",
"graphql-tag": "^2.5.0",
"react-apollo": "^2.0.0"
```

The non-obvious 2 packages to use to make react-apollo@2.0.0 works are:

* graphql
* graphql-tag

Use it like so:

```js
import gql from 'graphql-tag'
import { graphql } from 'react-apollo'
```

**Comment by mauscoelho** [comment]
thanks @mech 
resolved my problem with react native

**Comment by kyler-hyuna** [comment]
Thank you! Knocked my head too long on setting up graphql.

**Comment by peggyrayzis** [comment]
Here are all the packages you'll need to get started, including `graphql-tag` & `graphql`: https://www.apollographql.com/docs/react/basics/setup.html#installation

**Comment by kyler-hyuna** [comment]
Thanks for updating the docs @peggyrayzis  :)

**Comment by morgansierrasnyder** [comment]
@peggyrayzis do we need to upgrade to `"graphql": "^0.11.7"` on our GraphQL server, as well? can't find this in the migration docs.

**Comment by agm1984** [comment]
This still appears to be true as of today.

**Comment by Stevearzh** [comment]
seems I met the same problem when using `"graphql": "^0.13.2"` in project, solved by downgrade it to `"graphql": "0.13.0"`

![clipboard - may 18 2018 12_21 pm](https://user-images.githubusercontent.com/4365999/40227874-46e0b986-5ac2-11e8-8219-172402d5c20c.jpg)

**Comment by AurangzaibRamzan** [comment]
@mech  thanks

**Comment by chrisbull** [comment]
@peggyrayzis  This is still a major problem. Even with a fresh build. Can you guys please look into it? Thanks

@mech Thanks! Adding graphql dependency worked!

**Comment by sis-dk** [comment]
September and still a problem.

**Comment by iamdanthedev** [comment]
upgraged graph from 0.13-something to ^14 and bumped into this problem again

**Comment by paul-phan** [comment]
Don't know whether it needs to be another issue or not so I'll leave a comment here.
This problem occurs again in the new version of `create-react-app` which is using Babel 7 and Webpack 4...
Here is the error I've got:
``` 
Failed to compile.

./node_modules/apollo-link-state/lib/utils.js 21:51-56
  'graphql' does not contain an export named 'print'.

```

Code: 
`
import ApolloClient from 'apollo-boost'
import gql from 'graphql-tag';

const client = new ApolloClient({
	uri: '/graphql'
})
console.log(gql)
`

`npx create-react-app@next --scripts-version=@next test-next`

**Comment by JustFly1984** [comment]
I have same issue with `graphql@0.13.2`, only my webpack gives me this error:
```
Attempted import error: 'print' is not exported from 'graphql'.
```
per each file I use `import { print } from 'graphql'`

When I downgrade to 0.13.0 I got dev server running, but there is runtime errors about undefined environment variables. I do not use `create-react-app`, I use `react-static instead`.

I have no idea where to dig, cos environment variables passed with any other version of graphql, but not with 0.13.0

**Comment by jayliew** [comment]
Adding this worked for me:
```
import { ApolloProvider } from 'react-apollo'
import { BrowserRouter } from 'react-router-dom'
ReactDOM.render(
  <BrowserRouter>
    <ApolloProvider client={client}>
      <App client={client} />
    </ApolloProvider>
  </BrowserRouter>,
  document.getElementById('root')
)
````

**Comment by hadnazzar** [comment]
I think graphql is not installed as package. 

**npm install --save graphql**
or 
**yarn add graphql**

Hope fixes your problem!

**Comment by deenMuhammad** [comment]
installing 
`react-dom` helped me

**Comment by ReadySoftTeam** [comment]
Esto funciono para mi:

npm install --save  react-apollo graphql

**Comment by Aichnerc** [comment]
Just install graphql.

`npm i graphql`
or
`yarn add graphql`

It isn't rocket science 🚀 - is it?

**Comment by ronatory** [comment]
For me it just was `yarn add graphql` and restarting the server

**Comment by aldegoeij** [comment]
might help someone from going mad / bald: https://github.com/apollographql/apollo-client/issues/4764

**Comment by jpenna** [comment]
Installing `graphql` solved the problem.

This was opened in 2017 and is tagged as Closed.

@peggyrayzis Should `graphql` continue to be installed separately if it is required by the lib?

**Comment by EdwardGoomba** [comment]
This is still an ongoing issue. Using 3.0 beta on an Expo project and ran into the same problem. Installing `graphql` as suggested above solved the error.

**Comment by mthines** [comment]
To me, the problem was not the missing dependency.
I had added `graphql` in the webpack alias resolver. Removing it from there fixed the problem. :)

**Comment by mattdenkers** [comment]
I also had this issue when trying to create a webpack alias for `graphql`.

**Comment by NiyongaboEric** [comment]
I encountered the same error.

> Module not found: Can't resolve 'graphql/language/printer' ...

I installed `npm i graphql` and it gets solved.

Thank you everyone for the support.

**Comment by nathanjwtx** [comment]
This issue is still happening. I'm trying to use Apollo Client beta 3.0.0-rc.12

I have installed graphql and graphql-tag.

**Comment by jamilAbbas** [comment]
"npm i graphql" fixed **it.******
