### ISSUE TITLE
`createNetworkInterface` in @2.0.0 ?

### ISSUE THREAD

**Issue by lluia** [apollographql/react-apollo#1283]
Hi,

First of all, congrats for the great work you're doing with Apollo and its integration with **React**
👌🏻 💖 🎈

### Intended outcome

Following the first step from the [React-Apollo HowToGQL](https://www.howtographql.com/react-apollo/1-getting-started/) tutorial, I wanted to have an instance of *Apollo Client* running.

### Actual outcome

I get `undefined` when trying to import `createNetworkInterface` from react-apollo:
```js
import { createNetworkInterface } from 'react-apollo'
```
This seems to happen because `react-apollo@2.*.*` doesn't export `createNetworkInterface` anymore. I couldn't find this explicitly documented neither on the README or on the docs. 

When you run `yarn add react-apollo` it installs `2.0.0`.

### How to reproduce the issue

https://codesandbox.io/s/oqz905xwn6

### Versions

- apollo-client@2.0.0
- react-apollo@2.1.0

**Comment by b3nab** [comment]
I fix this problem using the latest release version from this repo, 1.4.15.
For now all works pretty well.
I think that before release a new version on npm, the package should be tested.. but seems that react-apollo v2.0.0 is in beta. (??)

**Comment by wesbos** [comment]
react-apollo doesn't export gql anymore either. 

I don't think this is intentional because 2.0 was supposed to have no breaking changes and there is zero documentation on these things being taken out.

**Comment by wesbos** [comment]
So createNetworkInterface is deprecated in favor of apollo-link and apollo-link-http

I think we need to wait for some more migration docs :)

**Comment by spencercarli** [comment]
For others stumbling on this - here's a [PR migrating the examples to the v2 api](https://github.com/apollographql/react-docs/pull/306/files).

**Comment by mwickett** [comment]
This is helpful: https://www.apollographql.com/docs/react/2.0-migration.html

**Comment by mwickett** [comment]
@wesbos I think the removal of `gql` might have been intentional. In the "After" example [here](https://www.apollographql.com/docs/react/2.0-migration.html#install), they show importing `gql` from `graphql-tag`

**Comment by lluia** [comment]
@mwickett great, I think everything is explained in the [docs section](https://www.apollographql.com/docs/react/2.0-migration.html) you linked 🎊

 I think we can close this issue 👍🏻

**Comment by Fi1osof** [comment]
> So createNetworkInterface is deprecated in favor of apollo-link and apollo-link-http

Deprecated, but still used in demo docs. https://github.com/apollographql/react-docs/blob/master/source/server-side-rendering.md

**Comment by wildcod** [comment]
Hi,
I'm trying to use createNetworkInterface from 'react-apollo' but it show 
![screenshot from 2018-12-22 00-21-23](https://user-images.githubusercontent.com/31349042/50358551-bb210680-057f-11e9-83ae-92c56e0a39e1.png)

how can I fix?

**Comment by farminf** [comment]
since all the links are deprecated:
https://github.com/apollographql/apollo-client/blob/master/docs/source/recipes/2.0-migration.md

**Comment by onurarpapay** [comment]
> For others stumbling on this - here's a [PR migrating the examples to the v2 api](https://github.com/apollographql/react-docs/pull/306/files).

unfortunately this link doesn't work anymore, along with any other link found anywhere. Why would anyone delete a migration document?
