### ISSUE TITLE
feature idea: Manual Cache updating outside of mutations

### ISSUE THREAD

**Issue by falconmick** [apollographql/react-apollo#1293]
Hi guys.

I've been doing some looking through the docs but the closest thing I could find to an answer was to use apollo-link, I will get to that in a sec.

I've been working on adding Apollo GraphQL to my companies Wordpress API Proxy so that we use GraphQL as the transport between the WP Proxy to the React Client, I've hit a little issue though. After reading what feels like almost all of the docs I cannot find a way to manually insert a record into the cache store (except in mutations).

I need to be able to do this because the way we build pages is via the following data structure:

individual page -> Components inside of page 

So when the user navigates the page x, my query fetches all of the generic page data aswell as the list of components and their data. Then the components are mounted in my react front end aannnd If the component has to fetch data from the server to power itself (say a form) the page has to wait for this query to complete. This is a real bummer for me because we use SSR, so the page loads instantly how it should look, except my form shows loading!

What I was going to try and do was on the server, when I get back the list of components that the page will display, look at the Component and find whatever queries it will run and the args for em and then fetch the data on the server! 

The data would then be attached to a Prefetch type on the Page's query, and the client would deserialise the prefetched data and insert it into the store!

The only two ideas i've had to do this are to use mutations for the page or look further into the new apollo-link.

Using mutations:
To do it this way I would simply send a mutation including the page I want as the request, and then return the default page data in the result of this mutation and use the update function that mutate gets to insert my prefetched data! But this sucks because why am I mutating a page request!

apollo-link:
Tis friday and my ability to better asses the viability of apollo-link as a good solution is limmited. But if I could find a way to use link to make a stock standard apollo client, but inject some code like express middleware to search all queries for any which return PreFetch data and auto-magically update the store somhow.. This feels like (if once again my mush brain understands why apollo-link was made) a really good solution. Maybe instead of using the apollo in-built cache it will have a seperate cache for pre-fetch and I will stop the request for data if I notice I have the data prefetched?? 

OR

Why can't my queries have access to the update functionality that mutate has? That way I could manually update my store without having to use mutations!

Thanks for reading if you made it this far. I have re-read this to make sure it makes atleast 1% sense, however I am rather smashed from this week so I wouldn't be supprised if it's hard to read. If that's the case please leave some questions about my question and I will get back to you in Aussie hours!

Cheers,
Michael.

**Comment by k** [comment]
Do you have to update the store? The store is meant to be a cache of back end data. Perhaps you can map data from the store into the final version you will show in your UI?

**Comment by falconmick** [comment]
To simplify, 1st query causes another query to have to be run. Right now that means the front end has to spend 2x as long purely on ping from server to client. When I run the 1st query, as soon as it gets to the resolver of the type I can figure out all the extra data I need and add it to what ever the query returns. The issue is that I cannot use update from within a query to manually fix the cache whereas if it were a mutation theoretically I could (theoretically as I’ve never used update before, just read doco)

Does that help?

Cheers

**Comment by k** [comment]
Hm what about storing that data separately in the redux store? If you have a unique id for each object in the store then you could store that data separately and combine it in your components.

**Comment by falconmick** [comment]
I could, but then I cannot utilise one of apollo’s Key gains which is it’s basically magic automatic cache. I would then need to intercept queries before I send em and parse them looking for any in my cache... 

And if I just resolve the data that was prefetched for the sub components to my components I could still get the benefits of the cache for that query, but if the data returned were to be a part of a direct query (not sub query like from a page) I would have to fetch it as it’s not in apollo cache. Not to mention the queries attached to my component would need to be somehow told to not fetch as I have already passed em to the component.

However it is definitely an option, if using mutations is either too messy OR not viable I’ll give it a go. Also once I upgrade to 2.0 I’ll have a go at adding update to queries and maybe make a PR

**Comment by k** [comment]
Hm I still don't think I completely understand your problem, but there is something like readQuery/writeQuery and readFragment/writeFragment that allows you to operate directly on the ApolloClient that may be useful.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, React Apollo feature requests are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=feature%20idea%3A%20Manual%20Cache%20updating%20outside%20of%20mutations&body=Migrated%20from:%20apollographql/react-apollo%231293) to start the feature request migration process. This manual migration process is intended to help identify which of the outstanding feature requests are still considered to be of value to the community. Thanks!
