### ISSUE TITLE
Feature Idea: Interacting With Apollo's Underlying Redux Store

### ISSUE THREAD

**Issue by chris-guidry** [apollographql/react-apollo#1295]
To save the application's state I am currently using PouchDB, but I'd like to switch over to Redux. Since Apollo already uses a Redux store under the hood, I was wondering if there is a way to use that store directly from a component?

The documentation [Integrating with Redux](http://dev.apollodata.com/react/redux.html) assumes there is an existing Redux store to integrate with, but in my case there is no store yet and I just want to utilize Apollo's Redux store.

**Comment by tsnieman** [comment]
Apollo 2.0 does not use Redux under the hood. @chris-guidry

**Comment by chris-guidry** [comment]
@tsnieman I got an email stating, "Apollo 2.0 does not use Redux under the hood." That comment isn't showing up in this string, but do you know what v2 is using as a store and whether or not it will be directly accessible? I'm currently using v1.2, but open to upgrading to 2.x.

**Comment by cesarsolorzano** [comment]
@chris-guidry Apollo Client 2.0 does not use Redux anymore. It now allows you to use custom stores. The recommended for Apollo 2.0 is `apollo-cache-inmemory`, more info [here](https://www.apollographql.com/docs/react/2.0-migration.html#redux).
