### ISSUE TITLE
⁉️ Master branch should not have been updated to 2.0.0 when documentation is so outdated.

### ISSUE THREAD

**Issue by shahzeb1** [apollographql/react-apollo#1303]
It doesn't make any sense to move the master branch (and npm) to version 2.0.0 when the [usage README](https://github.com/apollographql/react-apollo#usage) and the [usage on NPM](https://www.npmjs.com/package/react-apollo#usage) has not caught up with documentation.

2.0.0 should have been kept as a release candidate until the documentation (at least the very basic usage) has been added.

Feel free to let me know if I'm the only one that feels this.

**Comment by albinekb** [comment]
I have the same feeling, but I think it's because 2.0 is not ready yet? I'm having issues with my mutations and react-apollo not working like before.

**Comment by lifeiscontent** [comment]
@shahzeb1 @albinekb the docs are updated. You're just looking at the old ones. https://www.apollographql.com/docs/react/index.html

**Comment by albinekb** [comment]
One thing I'm missing in the migration guide is how to reset the store, in 1.x that was `client.resetStore()` but there's no mention how to do it in 2.x with the new separate inMemoryCache. Should I open a new issue for this?

**Comment by green-arrow** [comment]
@albinekb - `resetStore` looks like it's still a function in 2.0

https://www.apollographql.com/docs/react/reference/index.html#ApolloClient\.resetStore

I'm currently using 2.0 + `client.resetStore()` and it's working as expected.

**Comment by albinekb** [comment]
Oh, then I must have struck some other issue 🙂  I'm having a hard time knowing what versions of all the new libs that I need, some are still 1.x? Some guides mention `2.x`, some `latest` tag and another one mentions the `next` tag, and some libs are still on `1.x`...

**Comment by green-arrow** [comment]
@albinekb - fwiw I followed the new setup guide for an app that doesn't currently use Apollo. I installed `apollo-client-preset` along with the other libs mentioned and everything seems to be working fine. :) 

https://www.apollographql.com/docs/react/basics/setup.html

I think if you stick with the above link and the links in the sidebar you should be ok.

**Comment by jbaxleyiii** [comment]
That branch was left open to it could be merged on stage at GraphQL Summit. All branches are cleaned up and I'm fixing doc links today 👍
