### ISSUE TITLE
fetchData never returns with big data

### ISSUE THREAD

**Issue by brunorzn** [apollographql/react-apollo#1307]
**Intended outcome:**

I have a website (already in production, of course, it wouldn't be fun otherwise) with many queries, which all seem to work with SSR (queries work both on client and server side). 
Except one, which doesn't work, on server-side only (it works well on client-side)
I expect all my queries to be fetched in server-side.

**Actual outcome:**
(Note that it's probably the biggest query, with nested data. )
In this case, renderToStringWithData() never returns, thus SSR never works.
I've tested it with only this query, and it's the same.
I've tested it with the result of the query being stringified on the GraphQL server, and it's still the same, so it's not due to nested data, but probably to data size.
Actually, it's the fetchData() function that never returns.
(ie : _var query = instance.fetchData();_ in _getQueriesFromTree_ function)
It doesn't crash, nor sends an exception or timeouts... it just does nothing.

**How to reproduce the issue:**
Just send a huge String in a query to Apollo SSR.
(i've tested with 10^5 long strings)

**Version**
- apollo-client@1.9.3
- react-apollo@1.4.16

**Comment by jbaxleyiii** [comment]
@brunorzn have you tried the newest build (2.0)? I'm curious as to if this is still an isse

**Comment by brunorzn** [comment]
We did split the big query before updating to the newest build... So I'm not really sure if it's still an issue or not, I will have to try it out again :)

**Comment by jbaxleyiii** [comment]
I'd love to see how it performs!

**Comment by jbaxleyiii** [comment]
I'll close this for now, but if it still locks up please let me know!

**Comment by brunorzn** [comment]
OK, I've tested it again with react-apollo@2.0.0" and apollo-client:@2.0.2, and everything seems to work as expected.
