### ISSUE TITLE
flow typing with query + mutation

### ISSUE THREAD

**Issue by green-arrow** [apollographql/react-apollo#1308]
**Intended outcome:**

Figuring out how to properly flow-type a component with GraphQL queries + mutations.

**Actual outcome:**

Documentation says to use the `OperationResult` type, but it is not clear how to properly define a flow-type when a component has a query + a mutation. Looking into the flow types, it seems there is a `MutationFunc` type. Would the correct way to flow-type be to manually define a type with a `mutate` key and use the `MutateFunc` type, then create an intersection type to pass to `OperationResult`?

Example:

```javascript
import type { OperationResult, MutationFunc, QueryProps } from 'react-apollo';

type Hero = {
  name: string,
  id: string,
  appearsIn: string[],
  friends: Hero[]
};

type Response = {
  hero: Hero
};

type Mutation = {
  mutate: MutationFunc<{SomeOtherFlowtypeForResult}>
};

type Props = {
  data: Response
} & QueryProps & Mutation;

const withCharacter: OperationComponent<Response, {}, Props> = graphql(HERO_QUERY, {
  options: ({ episode }) => ({
    variables: { episode }
  })
});
```

Apollo version 2.0

**Comment by jbaxleyiii** [comment]
@green-arrow yeah sadly we haven't gotten around to adding back in flow types for the 2.0. I'd LOVE some help with this if anyone is able / interested. We need to convert the TS types to flow and included them in the bundle. Most of it can be copied from the 1.0 work but still needs to be done

**Comment by rovansteen** [comment]
So `react-apollo` basically has no real support for flow? I'm building an application that relies heavily on Apollo and a GraphQL API so if there's no real support (and attention) for flow it might be better to use typescript?

**Comment by TSMMark** [comment]
What's the best way to know which types need to be added so people can contribute easily?

**Comment by rosskevin** [comment]
@TSMMark you can look at the `test/flow-usage.js` file and  supplement it with usage samples, which would be used to validate the flow definitions.  The flow definitions definitely need some attention, I merged a few fixes but they need more help.

**Comment by hwillson** [comment]
React Apollo no longer supports flow (we're all in on Typescript). Thanks!
