### ISSUE TITLE
 TS2688:Cannot find type definition file for 'react'

### ISSUE THREAD

**Issue by adnan1naeem** [apollographql/react-apollo#1316]
I am using typescript version 2.3.4 in my app . I am getting  the above error  in server.d.ts file in react-apollo node modules.kindly   patch this  in your package.As I am unable to use it.I am following versions for my App
 typescript version 2.3.4
"react-apollo": "^1.4.15",

**Comment by EItanya** [comment]
I solved this issue by installing '@types/react' Im new to TS though so that may be incorrect.

**Comment by rosskevin** [comment]
This is because our `@types` are in `devDependencies`, and they should be in `dependencies` so that downstream projects get the same transitive @types requirements.

**Comment by rosskevin** [comment]
I've found it is not customary to include `@types` modules in the `dependencies` from looking at several other projects. If you are using react+typescript in your project you will need to add `@types/react`.
