### ISSUE TITLE
Update Readme examples for 2.0

### ISSUE THREAD

**Issue by Skaronator** [apollographql/react-apollo#1323]
Edit: I'm a idiot.

**Comment by Skaronator** [comment]
Just checked the history of my package.json and looks like I've updated from 1.4.16 to 2.0.0 which is probably the reason for this.

And the readme is probably just outdated.

**Comment by scko823** [comment]
+1 just started exploring apollo and graphQL today, and it is not beginner friendly if the github readme is outdated.
Also why is the release section not listing v2.0? The last release is at v1.4.15 at https://github.com/apollographql/react-apollo/releases
