### ISSUE TITLE
2.x: Include 'object-assign' in dependencies and 'react-dom' in peerDependencies

### ISSUE THREAD

**Issue by voodooattack** [apollographql/react-apollo#1328]
This is occurring as part of a huge project that's installing dependencies using `supi`, so I can't be certain that this is reproducible in all cases.

**Intended outcome:**
Requiring `react-apollo` after install with `pnpm` should not fail.

**Actual outcome:**
Fails with errors about missing dependencies.

**How to reproduce the issue:**
`pnpm install react-apollo` then `require('react-apollo')`, `pnpm` is not aware of the dependency on `react-dom` and `object-assign` and does not provide them. Due to the atypical `node_modules` structure, those packages are not readily available at the top-level `node_modules` like what `npm` would provide.

**Workaround:**
Pass a special hook in `supi` options to patch the `package.json` data:

```ts
            hooks: {
              readPackage: (pkg: any) => {
                if (pkg.name === 'react-apollo') {
                  pkg.peerDependencies = pkg.peerDependencies || {};
                  pkg.peerDependencies['react-dom'] = '^16.0.0';
                  pkg.dependencies['object-assign'] = 'latest';
                }
                return pkg;
              }
            },
```
**Version**
- apollo-client@2.0.2
- react-apollo@2.0.0

**Comment by voodooattack** [comment]
@jbaxleyiii Sorry to bother you, but I don’t want this closed.

**Comment by yujuiting** [comment]
Same as I, currently install object-assign manually.

**Comment by vjpr** [comment]
Just ran into this again.

**Comment by hwillson** [comment]
This should no longer be an issue with current versions of React Apollo. Thanks!
