### ISSUE TITLE
Refetch does not update loading to true

### ISSUE THREAD

**Issue by wojcikiewiczm** [apollographql/react-apollo#1331]
Hello,

when I use refetech loading is not updated to true and after fetch to false. Is it issue or I'm doing something wrong?

```javascript
const FoldersContainerWithGraphQL = compose(
	withApollo,
	graphql(GET_FOLDERS_REVIEW, {
		options: () => {
			return {
				variables: {limit: FOLDERS_PER_PAGE, offset: 0}
			};
		},
		props: ({data, data: {fetchMore}}) => {
			return {
				folders: {
					...data,
					loadMoreEntries(pageNumber) {
						return fetchMore({
							variables: {
								offset: FOLDERS_PER_PAGE * pageNumber
							},
							updateQuery: (previousResult, {fetchMoreResult}) => {
								if (!fetchMoreResult) {
									return previousResult;
								}
								return fetchMoreResult;
							}
						});
					}
				}
			};
		}
	})
)(FoldersContainer);
```

**Comment by msmfsd** [comment]
Related issues:
https://github.com/apollographql/apollo-client/issues/1622
https://github.com/apollographql/apollo-client/issues/2513

**Comment by jaredly** [comment]
Looks like refetch doesn't update the component at all? I'm having to manage that state myself

**Comment by bxt** [comment]
You could try setting `notifyOnNetworkStatusChange` to true.

**Comment by rosskevin** [comment]
See https://github.com/apollographql/apollo-client/issues/1622#issuecomment-418175001
