### ISSUE TITLE
(0, _reactApollo2.default) is not a function. (In '(0, _reactApollo2.default)'(MY_QUERY), '(0, _reactApollo2.default)' is undefined

### ISSUE THREAD

**Issue by KenilDomadia** [apollographql/react-apollo#1334]
Below is the App.js file I have used for my react-native expo project with Apollo. The last line throws error saying `(0, _reactApollo2.default) is not a function. (In '(0, _reactApollo2.default)'(MY_QUERY), '(0, _reactApollo2.default)' is undefined `.

[App.js file](https://gist.github.com/KenilDomadia/e751073eee67c0d10da10ddc04a5e4ce)

The AppNavigation file used in the above file is [here](https://gist.github.com/KenilDomadia/effca86d4babde5d4587745a3476a585)
The apollo connection is setup and working properly. Is there anything wrong in the above file? Please guide.

**Comment by SkReD** [comment]
@KenilDomadia You should change your import statement to
```js
import {graphql} from 'react-apollo'
```
because `graphql` is not a default export of `react-apollo` package

**Comment by KenilDomadia** [comment]
That helped. It was a real silly mistake. Thanks.
