### ISSUE TITLE
`loading` always true when re-render after error received from server

### ISSUE THREAD

**Issue by SkReD** [apollographql/react-apollo#1336]
Simple todo list is rendered with data from server
```js
class Todos extends Component {
    render() {
        if (this.props.data.loading) {
            return <img src={logo} className="App-logo" alt="logo"/>;
        } else if (this.props.data.error) {
            return JSON.stringify(this.props.data.error, null, 4);
        }
        else {
            return this.props.data.todos.map(todo =>
                <div key={todo.id}>
                    {todo.name}
                    <button onClick={() => this.props.onEdit(todo)}>edit</button>
                </div>
            );
        }
    }
}

const TodosWithData = graphql(todosQuery)(Todos);
```

where `todosQuery` is:
```js
import gql from 'graphql-tag';

export const todosQuery = gql`
    query Todos($withError: Boolean) {
        todos(withError: $withError) {
            id,
            name
        }
    }
`;
```
When `withError`  variable is set to true the error on server generated and query returns an error.
Then this error is rendered in section of `Todos` component.

The main react containers is contains following code
```js
class App extends Component {
    constructor(...args) {
        super(...args);
        this.state = {withError: false};
    }
    render() {
        return (
            <div className="App">
                <header className="App-header">
                    <img src={logo} className="App-logo" alt="logo"/>
                    <h1 className="App-title">Welcome to React</h1>
                </header>
                <div className="App-intro">
                    <button onClick={() => this.setState({withError: !this.state.withError})}>
                        {this.state.withError ? 'Request without error' : 'Request with error'}
                    </button>
                    <button onClick={() => this.setState({rerender: !this.state.rerender})}>Rerender</button>
                    <button onClick={() => this.setState({unmountTodosOnEdit: !this.state.unmountTodosOnEdit})}>
                        {this.state.unmountTodosOnEdit ? 'Dont unmount todos on edit' : 'Unmount todos on edit'}
                    </button>
                    {
                        this.state.editTodo &&
                            <TodoFormWithMutation editTodo={this.state.editTodo} onSuccess={() => this.setState({editTodo: null})}/>
                    }
                    {
                        this.state.unmountTodosOnEdit && this.state.editTodo
                            ? null
                            : <TodosWithData withError={this.state.withError} onEdit={(todo) => this.setState({editTodo: todo})}/>
                    }
                </div>
            </div>
        );
    }
}
```

...so when `rerender` state is chaning all childrens of app are re-rendered.

**Intended outcome:**
When re-render occures error should be still presented in returned data of `TodosWithData`

**Actual outcome:**
Error is present in first render of component, but all subsequent renders are containing `loading` set to true, and no `error` or `data` props setted.

**How to reproduce the issue:**
I create a reproduction app from `create-react-app` and `apollo-server-express`
(can be cloned  from https://github.com/SkReD/apollo-demo.git)
To run it you need to start express server by `npm run start-server` command and then run
webpack-dev-server by command `npm start`.
Then do following steps:
1. Press 'Request with error' button (error should be displayed)
2. Then press 'Rerender' button (loading icon should be presented)

**Investigation results**
Looks like `currentResult` method of `ObservableQuery` ([link](https://github.com/apollographql/apollo-client/blob/07079badb32c3125efe8d3036d1bda3be01940d3/packages/apollo-client/src/core/ObservableQuery.ts#L153)) is returning wrong result because it cannot find `queryStoreValue` for query and there is a logic that `loading` is set to true if  `queryStoreValue` is undefined, yet there is `lastError` presented, which contains actual error from server.
![image](https://user-images.githubusercontent.com/938036/32703422-e5f4f20c-c806-11e7-9d83-4ea813f6feb6.png)

**Version**
- apollo-client@2.0.2
- react-apollo@2.0.1

**Comment by jay1337** [comment]
hey !

**Comment by YuryIlinikh** [comment]
+1

**Comment by alerg** [comment]
+1

**Comment by jorihardman** [comment]
+1

**Comment by dbelchev** [comment]
+1

**Comment by dbelchev** [comment]
@jbaxleyiii This is happening both with refetch and polling features, as well. I see that most of the people commenting on the issue are using v2.x, but I'm experiencing this on react-apollo 1.4.16, as well.

**Comment by juank11memphis** [comment]
+1 Any update on when is this gonna get fixed?

**Comment by tdeedlesATX** [comment]
+1

**Comment by rad182** [comment]
+1

**Comment by thomhos** [comment]
+1

**Comment by jbaxleyiii** [comment]
This should be fixed in the current beta!

**Comment by kiran-sonnad-ck** [comment]
+1 on 2.0.4

**Comment by ksonnad** [comment]
+1 on v2.0.4

**Comment by tysonmatanich** [comment]
+1 on v2.1.5

**Comment by mhmahmoodalam** [comment]
+1 on 2.4.2

**Comment by pavan-shipmnts** [comment]
+1 on ` "react-apollo": "^2.5.1"`

**Comment by supachaic** [comment]
+1 on "react-apollo": "^2.5.4"

**Comment by panzelva** [comment]
Setting `errorPolicy="all"` on Query component fixed this issue for me.

**Comment by hwillson** [comment]
The original issue here should be resolved (thanks to https://github.com/apollographql/react-apollo/pull/2718) in `react-apollo` >= 2.5.3. For all other outstanding issues, please consider opening a new issue. Thanks!
