### ISSUE TITLE
TypeScript: Type definition for graphql operation options doesn't work with named queries

### ISSUE THREAD

**Issue by Jannis** [apollographql/react-apollo#1349]
The type definition of the `graphql` function currently includes `operationOptions?: OperationOption<TProps, TResult>`. In other words, if `{ props: props => ... }` is passed as the options, these `props` are typed as `OptionProps<TProps, TResult>` and will include a `data` member with the query result.

However, this doesn't work with named queries.

Assume the following setup:
```
type UserQueryProps = {
  allUsers: QueryResult & { users: Array<User> },
}

const withAllUsers = graphql<{}, InputProps, UserQueryProps>(USERS_QUERY, {
  name: 'allUsers',
  props: props => ({
     ...
  }),
})
```

Here, the `props` passed in to the props option function is typed as `OptionProps<InputProps, {}>`, meaning it doesn't have an `allUsers` member. This means that things like `props.allUsers.subscribeToMore(...)` don't work. Note: With named queries, `props.data` is undefined and can (of course) not be used.

This could be solved by changing the type of `graphql` from
```
export default function graphql<TResult = {}, TProps = {}, TChildProps = ChildProps<TProps, TResult>>(document: DocumentNode, operationOptions?: OperationOption<TProps, TResult>): ComponentDecorator<TProps, TChildProps>;
```
to
```
export default function graphql<TResult = {}, TProps = {}, TChildProps = ChildProps<TProps, TResult>>(document: DocumentNode, operationOptions?: OperationOption<TChildProps, TResult>): ComponentDecorator<TProps, TChildProps>;
```

**Version**
- apollo-client@2.03
- react-apollo@2.0.1

**Comment by Jannis** [comment]
I correct myself, the solution I'm proposing does not work. However, the problem itself is real.

**Comment by jtmthf** [comment]
I think I might have a solution that will make `name` statically typed after some brief testing. This seems to be possible by making name a generic that extends string and then using mapped types to map the literal name as a property on the result type. Below I've attached a screenshot of an extremely minimal example of how this could work. I think I can apply this principle to full graphql signature with some effort.

![graphql_name](https://user-images.githubusercontent.com/8162598/33291887-f5e67866-d38c-11e7-8cf5-70cd9a0758e1.PNG)

**Comment by samba6** [comment]
Here [1](https://github.com/apollographql/react-apollo/blob/master/test/typescript.ts) and [2](https://www.apollographql.com/docs/react/features/static-typing.html)

**Comment by Slessi** [comment]
@samba6 as of today at least, your `1` is a broken link, and ur `2` link's solution doesnt work, even if i use `any` everywhere

```ts
import gqltag from 'graphql-tag';
import { graphql, NamedProps, QueryProps } from 'react-apollo';

export const withCharacter = graphql<any, any, any>(gqltag``, {
  name: 'character',
  props: ({ character }: NamedProps<{ character: QueryProps }, any>) => ({
    ...character,
  }),
});
```


```
[ts] Argument of type '{ name: string; props: ({ character }: NamedProps<{ character: QueryProps<any, OperationVariables...' is not assignable to parameter of type 'OperationOption<any, any, any, Partial<DataProps<any, any>> & Partial<MutateProps<any, any>>> | u...'.
       Type '{ name: string; props: ({ character }: NamedProps<{ character: QueryProps<any, OperationVariables...' is not assignable to type 'OperationOption<any, any, any, Partial<DataProps<any, any>> & Partial<MutateProps<any, any>>>'.
         Types of property 'props' are incompatible.
           Type '({ character }: NamedProps<{ character: QueryProps<any, OperationVariables>; }, any>) => QueryPro...' is not assignable to type '((props: OptionProps<any, any, OperationVariables>, lastProps?: void | (Partial<DataProps<any, an...'.
             Type '({ character }: NamedProps<{ character: QueryProps<any, OperationVariables>; }, any>) => QueryPro...' is not assignable to type '(props: OptionProps<any, any, OperationVariables>, lastProps?: void | (Partial<DataProps<any, any...'.
               Types of parameters '__0' and 'props' are incompatible.
                 Type 'OptionProps<any, any, OperationVariables>' is not assignable to type 'NamedProps<{ character: QueryProps<any, OperationVariables>; }, any>'.
                   Type 'OptionProps<any, any, OperationVariables>' is not assignable to type '{ character: QueryProps<any, OperationVariables>; }'.
                     Property 'character' is missing in type 'OptionProps<any, any, OperationVariables>'.
```

**Comment by samba6** [comment]
@Slessi if you check here [react-apollo-test-typescript-usage](https://github.com/apollographql/react-apollo/blob/3c231f3ceff7aeccb3da1eecb6ccabfc4c7d7434/test/typescript-usage.tsx#L128), there is a comment about using `name` being discouraged.

**Comment by Slessi** [comment]
@samba6 Yea it says to use manually map the prop instead but, that makes it a bit difficult to use with my `compose` func. Maybe I have overcomplicated matters, but my setup is as follows:

`helpers.ts`

> Have a helper function that creates HOCs from a `graphql-tag` `DocumentNode` with an interface to help with props

```ts
export function createQuery<Response, Variables = {}>(gql: DocumentNode) {

  function hoc<P>(name: string, queryOptions?: Partial<QueryOpts<Variables>>) {
    return graphql<Variables & P, Response, Variables>(gql, {
      name,
      options: variables => queryOptions,
    });
  }

  return { hoc };
}
```

`MyQuery.ts`

> Use helper function to wrap a `graphql` query file

```ts
export const MyQuery = createQuery<MyQuery>(gqltag`whatever`);
```

`MyComponent.ts`

> Use `compose` from `redux` to join multiple HOCs together for a given component

```ts
const composed = compose( 
  MyQuery.hoc('MyQueryStuff'),
  MyOtherQuery.hoc('MyOtherQueryStuff'),
  withStyles(styles),
)(MyComponent);
```

In the end when using my `compose()` I need to make use of `name` in multi-query contexts to prevent conflicts my composed props. If I use just one query, it is possible to omit name but I might get conflicts with props from other places

**Comment by samba6** [comment]
Will this work for you?

```typescript
import { DataValue, QueryOpts } from "react-apollo";
import { DocumentNode } from "graphql";

export function createQuery<Response, Variables = {}>(gql: DocumentNode) {
  function hoc<P>(name: string, queryOptions?: QueryOpts<Variables>) {
    return graphql<
      Variables & P,
      Response,
      Variables,
      { [key: string]: DataValue<Response> | undefined }
    >(gql, {
      props: ({ data }) => ({ [name]: data }),
      options: queryOptions
    });
  }

  return { hoc };
}
```

**Comment by Slessi** [comment]
@samba6 No, as then it also assumes `props.propWhichDoesntExist.loading` is valid, due to using `[key: string]`.

Can't fix it with `[key in typeof name]` either

**Comment by samba6** [comment]
You are right.

**Comment by samba6** [comment]
@Slessi : take a look:
```typescript
import { DataValue, QueryOpts, graphql, compose } from "react-apollo";
import { DocumentNode } from "graphql";
import * as React from "react";
import gql from "graphql-tag";

enum NAME {
  NAME_1 = "name1",
  NAME_2 = "name2"
}

type HocReturn<TResponse> = { [k in NAME]?: DataValue<TResponse> | undefined };

export function createQuery<TResponse, TVariables = {}>(doc: DocumentNode) {
  function hoc<P>(name: NAME, queryOptions?: QueryOpts<TVariables>) {
    return graphql<TVariables & P, TResponse, TVariables, HocReturn<TResponse>>(
      doc,
      {
        props: ({ data }) => ({ [name]: data }),
        options: queryOptions
      }
    );
  }

  return { hoc };
}

interface Response {
  user: { name: "me" };
}

const Comp = (props: HocReturn<Response>) => {
  const { name1, name2 } = props;

  if (name1) {
    // do something with name1
  }

  if (name2) {
    // do something with name2
  }

  return <span>default</span>;
};
const Hoc = createQuery<Response>(gql`doc`);
export const composed = compose(
  Hoc.hoc(NAME.NAME_1),
  Hoc.hoc(NAME.NAME_2)
)(Comp);
```

**Comment by hwillson** [comment]
If this is still an issue, and anyone feels like submitting a PR to address this, we'll definitely take a look. Thanks!
