### ISSUE TITLE
Basic query not working

### ISSUE THREAD

**Issue by BWillis98** [apollographql/react-apollo#1350]
**Intended outcome:**
The query returns 
{
  "data": {
    "otsUserByUserId": {
      "firstName": "Test",
      "lastName": "User"
    }
  }
}

Then, when I do: <Text>{this.props.data.otsUserByUserId.firstName} was queried</Text> in my React Native app, "Test was queried" will appear on my app.

**Actual outcome:**
![image](https://user-images.githubusercontent.com/14190965/33110796-109999ee-cf10-11e7-95ff-cd7136ceed28.png)

**How to reproduce the issue:**
Link to repo: https://github.com/BWillis98/Apollo-Error
You're not going to have access to this GraphQL endpoint, but I can confirm that this endpoint works in GraphiQL query. 
![image](https://user-images.githubusercontent.com/14190965/33110693-4d615f52-cf0f-11e7-8b1f-c2c0e4bb6b9c.png)

The code I have written is extremely simple and hopefully the error is able to be seen straight away and hopefully it's on my part. If after looking over the repo (Just the App.js and User.js files) you feel the issue is not on my part, we'll figure something out on how to reproduce the issue. However, I am very confident that something is wrong on my part, but I've had a ton of people look at my code and no one has been able to see anything wrong and I've had this issue for about a week now. I'm sure you could easily change the Apollo client to point to a public GraphQL endpoint, run a GraphQL query, and replace {this.props.data.otsUserByUserId.firstName} with {this.props.data.[dependsOnQuery]} and get the same result.

**Version**
- apollo-client@2.0.3
- react-apollo@2.0.1

**Comment by stevengeorgeharris** [comment]
`{this.props.data.otsUserByUserId && this.props.data.otsUserByUserId.firstName}`

**Comment by BWillis98** [comment]
We got it figured out.

**Comment by yosufali** [comment]
@BWillis98 I'm having the same issue, curious how you solved it?
