### ISSUE TITLE
Changing prop to a `graphql` whilst polling can leading to `loading: true`

### ISSUE THREAD

**Issue by tmeasday** [apollographql/react-apollo#1353]
This one is sort of subtle because it only occurs whilst a polling query is in flight.

When the props to a RA HOC change (in a way that doesn't affect the variables), typically it fetches the query from cache without entering any loading state.

However, if it happens to have a polling query in-flight, it actually enters loading until the query returns.

Psuedo-code repro:

```js
// Note that `prop` is *NOT* used by the HoC
const AppWithData = graphql(...., { pollInterval: ...});

// thing that renders AppWithData:
<AppWithData prop={firstValue} />

// sometime later, *during a poll*
<AppWithData prop={secondValue} />
```

**Intended outcome:** The behaviour should be the same as if the prop changes outside of the period while the polling query is in flight, i.e. it has no effect on `AppWithData` as `AppWithData` does not care about `prop`.

**Actual outcome:** In the above case, `AppWithData` will become `loading: true`, even though the only thing that is "loading" is polled data.

**Reproduction:** https://github.com/tmeasday/apollo-loading-state-for-inflight-polling-queries

**Version**
- apollo-client@2.0.3
- react-apollo@2.0.0

## Note

I tried to remember how all this stuff works but the code path from a `setVariables` to a listener firing is still super convoluted. I think the reason comes down to `observableQuery.result()` getting called (from `setVariables`) and that triggering the `QueryManager` to broad cast queries where it wouldn't normally for a polling query. But that's a guess. Happy to investigate a bit further into AC if its deemed helpful.

**Comment by timbotnik** [comment]
Think I just ran into this one as well.  In my case, I had overlapping queries between Parent and Child.  Child would poll, which would trigger a re-render of parent (I'm guessing due to overlapping queries) - the re-render would cascade back to the child _while it was loading_ and result in `loading: true`.

**Comment by tmeasday** [comment]
@timbotnik sounds the same! In my case the parent prop change was due to user interaction, and it was just random whether the polling was happening at the time or not.

**Comment by JAMesserman** [comment]
for anyone else running into this problem you can simply check the `NetworkStatus` on the query thats in flight to determine whether or not the query in flight is a polling query.  https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/networkStatus.ts

**Comment by hwillson** [comment]
See the workaround mentioned in https://github.com/apollographql/react-apollo/issues/1353#issuecomment-490228782. Thanks!
