### ISSUE TITLE
Proper github release for 2.xx ?

### ISSUE THREAD

**Issue by goldo** [apollographql/react-apollo#1359]
Hello,

Would it be possible to follow version history with proper github releases like you used to do ?
npm versions is higher than github's one:
On github: 1.4.15 https://github.com/apollographql/react-apollo/releases
on npm: 2.0.1 https://www.npmjs.com/package/react-apollo

Thanks a lot for your amazing work

**Comment by jbaxleyiii** [comment]
@goldo absolutely! The first of the year I'm going to work on the workflow for releases and go back to CI based deploys. Sorry for the delay in this but please hang with me a little longer here ;)

**Comment by hwillson** [comment]
This was resolved - thanks!
