### ISSUE TITLE
OptionProps Flow type only supports mutations named 'mutate'

### ISSUE THREAD

**Issue by TSMMark** [apollographql/react-apollo#1378]
**Intended outcome:**
Should be able to name a mutation.

**Actual outcome:**
It is not possible to use the existing flow types if you name a mutation. You get this flow error:

```js
Error: xxx.js:63
 63:     props: ({ customMutation }) => ({
                   ^^^^^^^^^^^^^^ property `customMutation`. Property not found in
108:   props?: (props: OptionProps<TProps, TResult>) => any;
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ OptionProps. See: node_modules/react-apollo/react-apollo.umd.js.flow:108
```

**How to reproduce the issue:**

Something like

```js
type WithMutationType = OperationComponent<
  { foo: string },
  OptionDescription<{}>,
  {}
>

const withMutation: WithMutationType = graphql(
  gql`mutation customMutation($input: CustomMutationInput!) {
    customMutation(input: $input) {
      foo
    }
  }`, {
    name: 'customMutation',
    props: ({ customMutation }) => ({
      customMutation: (input: customMutationInput) => customMutation({
        variables: {
          input
        },
      }),
    }),
  }
)
```

The reason it works without a custom name is the type definition for `OptionProps` has `mutate` hardcoded into it, which is the default name of a mutation:

```js
export interface OptionProps<TProps, TResult> {
  ownProps: TProps;
  data: QueryProps & TResult;
  mutate: MutationFunc<TResult>;
}
```

**Version**
- apollo-client@2.1.0
- react-apollo@ 1cd331e14214fd5bdad806812776540bd11210b6

**Comment by rosskevin** [comment]
Please submit a PR - the maintainers use typescript so we'll need the community's help to support flow.

**Comment by TSMMark** [comment]
I'm not sure if this is the new intended way to handle custom-naming of mutations, or multiple mutations per component, but I think it works:

### Use the default name of `mutate` and then use the `props` reducer option of react-apollo's `graphql` function to rename the mutation prop within the underlying component.

```js
type WithMutationType = OperationComponent<
  { foo: string },
  OptionDescription<{}>,
  {}
>

const withMutation: WithMutationType = graphql(
  gql`mutation customMutation($input: CustomMutationInput!) {
    customMutation(input: $input) {
      foo
    }
  }`, {
    // name: 'whateverYouWantToCallTheMutationFunction' // LEAVE OUT THE `name` OPTION!
    props: ({ mutate }) => ({
      whateverYouWantToCallTheMutationFunction: (input: customMutationInput) => mutate({
        variables: {
          input
        },
      }),
    }),
  }
)
```

Now the mutation function is available in the underlying component via `this.props.whateverYouWantToCallTheMutationFunction`. 

To have multiple mutations you can do the same thing (i.e. define another withMutation HOC for the other mutation), then you rename within `props` reducer to something else:

```js
    // name: 'whateverYouWantToCallTheMutationFunction2' // LEAVE OUT THE `name` OPTION!
    props: ({ mutate }) => ({
      whateverYouWantToCallTheMutationFunction2: (input: customMutationInput) => mutate({
        variables: {
          input
        },
      }),
    }),
```

**Comment by hwillson** [comment]
React Apollo no longer supports flow (we're all in on Typescript). Thanks!
