### ISSUE TITLE
impossible to trigger refetch() in subscribeToMore/updateQuery callback

### ISSUE THREAD

**Issue by helios1138** [apollographql/react-apollo#1380]
- It is impossible to trigger `data.refetch()` in `subscribeToMore`/`updateQuery` callback
- Suspected reason: the `props.data`  inside `updateQuery` is in a closure and comes from `props` callback, i.e. it holds the value it had when `updateQuery` callback is created, not when it is called.

**Comment by rosskevin** [comment]
If this is still an issue please consider submitting a PR with a test exemplifying your issue.  Ping me and I'll reopen.
