### ISSUE TITLE
Please cut a release

### ISSUE THREAD

**Issue by clayne11** [apollographql/react-apollo#1382]
SSR on my site is failing a lot due to the `null` array element issue that was fixed by https://github.com/apollographql/react-apollo/pull/1355. It was merged 6 days ago. Can we get a new patch release?

**Comment by KevinGrandon** [comment]
Also looking forward to the flow 0.59.0 fixes so we can upgrade.

**Comment by HugoGiraudel** [comment]
We also happen to have the problem at N26. That would be lovely to have a release!

**Comment by clayne11** [comment]
Also please merge https://github.com/apollographql/react-apollo/pull/1384 in first. It supports `undefined` elements as well as `null` elements which is allowed by React.

**Comment by jbaxleyiii** [comment]
I'll be cutting a release today! Going to merge / fix as many PR's as I can first then release!
