### ISSUE TITLE
Feature Request: updateQuery for queries / startPolling function

### ISSUE THREAD

**Issue by peterpme** [apollographql/react-apollo#1383]
@jbaxleyiii and I briefly spoke on Slack about an `updateQuery` function that would work for `startPolling` and queries in general.

`fetchMore` is lovely, but sometimes I'd like to poll for data and process it the way `fetchMore` would work.

My use case:

I query and order a list of data by points:
- 1
- 5
- 10

Sometimes, there will be new points added, this happens:
- 1
- 2
- 3
- 5
- 10
- 12

This is *exactly* what's supposed to happen in terms of spec and tech.

Unfortunately in my case, these are swipeable rows. If new data appears above and / or below, the user gets thrown off.

I'd like to be able to transform my queries in 1 spot in order to get this intended result:
- 1
- 5
- 10
- 2
- 3
- 12

(the new data is appended to the bottom of the array)

_of course_ I can do this within my component! But I <3 Apollo and feel like this could be a feature folks would like in an effort to keep their data separate from their components

I suppose this _could_ be called a query transformation?

cc @nevir

**Comment by nevir** [comment]
This also occurs for cases where you've got filtered (or sorted) collections of things.  

Say you've got a list of todos shaped something like `{ id text complete }`, and a collection of them as `{ incompleteTodos }`.  Now, let's say the cache currently contains:

```yaml
incompleteTodos:
  - { id: 1, text: 'caching is hard', complete: false }
  - { id: 2, text: 'seriously!', complete: false }
  - { id: 3, text: 'also naming', complete: false }
```

But let's say you also want to support refreshing data for individual todos.  So you kick off a query like `{ todo(id: 2) { id text complete }`.  Unfortunately, that todo might come back with `complete: true`, at which point the cache now looks like:

```yaml
incompleteTodos:
  - { id: 1, text: 'caching is hard', complete: false }
  - { id: 2, text: 'seriously!', complete: true }
  - { id: 3, text: 'also naming', complete: false }
```

And now the cache is inconsistent with your business logic.  One way to address this is to not trust the cache, and perform a filter over `complete: false` whenever retrieving the todos, but that's annoying and error prone…

**Comment by nevir** [comment]
I think having to transform on each operation becomes pretty cumbersome and error-prone (if you forget to include an updater, the cache is now in an inconsistent state!).  Something more centralized would probably be easier to juggle

We've been experimenting with ways of dealing with this sort of cache inconsistency via some additions to [Hermes](https://github.com/convoyinc/apollo-cache-hermes).  Namely the [ability to declare callbacks](https://github.com/convoyinc/apollo-cache-hermes/blob/master/src/context/CacheContext.ts#L88-L98) that fire (for whitelisted entities) whenever they change, no matter the source (query, mutation, subscription, fragment).

Building on the example above (and assuming a `__typename` of `Todo`), you'd be able to _guarantee_ that `incompleteTodos` is _always_ accurate via the following configuration for the cache:

```ts
new ApolloLink({
  initialCache: new Hermes({
    entityUpdaters: {
      // This is called synchronously any time any todo is modified.
      Todo: (dataProxy, todo, previous) => {
        const nextIsComplete = todo && todo.complete;
        const prevIsComplete = previous && previous.complete;
        if (nextIsComplete === prevIsComplete) return;

        const { incompleteTodos } = dataProxy.readQuery({ query: gql`{ incompleteTodos { id } }` });

        let newList;
        if (nextIsComplete) {
          newList = incompleteTodos.filter(t => t.id == todo.id);
        } else {
          newList = [...incompleteTodos, { id: todo.id }];
        }

        dataProxy.writeQuery({ query: gql`{ incompleteTodos { id } }`, data: newList });
      },
    },
  },
  …
}),
```

(we're also working on map/filter style helpers to make this sort of thing less verbose)

**Comment by nevir** [comment]
While this sort of thing is currently Hermes-only, I think similar concepts could probably be made cache-agnostic.  The updaters would probably need to declare a fragment, or similar, so the cache knows which data to provide during an update  

(it's particularly in Hermes, though, because that cache orients around more coarse-grained entities, rather than each node in the graph)

**Comment by hwillson** [comment]
[`updateQuery`](https://www.apollographql.com/docs/react/api/apollo-client.html#ObservableQuery.updateQuery) was added - closing. Thanks!
