### ISSUE TITLE
ApolloClient.query() always resolves to null data with cache-and-network fetchPolicy

### ISSUE THREAD

**Issue by joeyparis** [apollographql/react-apollo#1386]
**Intended outcome:**

To receive query results from the network when the cache does not contain the stored data.
```javascript
const client = new ApolloClient({
	// By default, this client will send queries to the
	//  `/graphql` endpoint on the same host
	link: concat(authMiddleware, httpLink),
	cache: new InMemoryCache(),
	defaultOptions: {
		query: {
			fetchPolicy: 'cache-and-network'
		}
	}
})

client.query({ query: gql `
	{
		users() {
			id
			full_name
			email
		}
	}
`}).then(r => {
	console.info( r ) // {data: {}, loading: false, networkStatus: 7, stale: false}
})
```

**Actual outcome:**

Instead of receiving data from the network null is returned. I am assuming this is because the data has yet to be stored in the cache. Using `network-only` behaves as expected but `network-and-cache` always returns no data.

```javascript
client.query({ query: gql `
	{
		users() {
			id
			full_name
			email
		}
	}
`}).then(r => {
	console.info( r ) // {data: null, loading: true, networkStatus: 1, stale: true}
})
```

**How to reproduce the issue:**

Set the fetchPolicy to `cache-and-network` and try to load data via the `ApolloClient.query()` function.

**Version**
- apollo-client@2.1.0
- react-apollo@2.0.1

**Comment by hwillson** [comment]
This should no longer be an issue with recent versions of Apollo Client / React Apollo. Thanks!
