### ISSUE TITLE
refetch-query results ignored due to page navigation

### ISSUE THREAD

**Issue by dchambers** [apollographql/react-apollo#1388]
**Intended outcome:**
The data returned by any `refetchQueries` should always be normalized and written to the store, regardless of which other queries are being performed due to navigation.

**Actual outcome:**
If after a mutation completes, but before the refetch query has completed, I navigate to a page that includes the same query as specified within the refetch-query for the mutation, that causes the eventual results of that refetch-query to be ignored.

**Version**
- react-apollo@1.4.15

**Full Description**
I have a list-view page and an item-detail page. After making a change to the item in the item-detail page I navigate back to the list-view page, where the item should have been removed from the list.

I wait for the promise returned by the mutation to resolve before navigating back, and this seems to resolve after the mutation is complete, but before the refetch queries have been run. Although I can subsequently see the data come back from the refetch-query in the network panel, the updated contents never make it into the store -- presumably because the list-view page performs the very same query, but with a fetch-policy of `cache-first`, which I guess then causes Apollo to ignore the updated data for the same query when it does finally arrive.

I can work around this issue in a couple of ways, neither of which are really acceptable to me:

1. I can set a delay before navigating back, and provided the delay was big enough to delay the navigation till after the refetch-query arrives, everything works (this of course just creates a race condition within the app).
2. I can navigate back without waiting the for the mutation promise to resolve (this creates a bad experience for users since the list updates after about 1.5s and I have no way of dealing with mutation errors, and also involves a potential race condition, though unlikely to ever be seen).

There's a lot of text there. Hope that makes some sense at least!

**Comment by harry-gao** [comment]
👍 same issue here

**Comment by rosskevin** [comment]
Master-detail scenarios/mutations are common and usually solved with the `update` option on `mutation` and using `writeQuery`.  This allows pinpoint updates to cache/list items without refetching everything.  This is an apollo-client thing and docs mention it, look for "updating the store with writeQuery" for more info.  I don't think there is anything to do here, but if you navigate away from any render tree before a promise has a chance to resolve, it will not continue.
