### ISSUE TITLE
does 'refetch' suppose to update data props?

### ISSUE THREAD

**Issue by kdong007** [apollographql/react-apollo#1391]
seems calling props.data.refetch only returns a promise but not update the component. Is this as designed or a bug?

**Comment by alewiahmed** [comment]
I'm having this issue too. When you call a refetch it returns a promise. When the promise is resolved you get the data, errors, networkStatus, etc. But those fields should have updated the component props, IMO.

**Comment by alewiahmed** [comment]
@kdong007 if you're still having trouble with data.refetch, you should checkout https://github.com/apollographql/apollo-client/issues/2513 .The solution of @adambom helped.

**Comment by kdong007** [comment]
@alewiahmed it doesn't change anything. calling refry doesn't update the component

**Comment by kdong007** [comment]
@alewiahmed that works. refetch -> retry :D

**Comment by adambom** [comment]
@kdong007 if you keep scrolling down I came up with a better workaround that allows you to continue using refetch instead of retry. I published it under the package react-apollo-temp-adambom if you want to try that

**Comment by alewiahmed** [comment]
@kdong007 , @adambom is right, I used his package, react-apollo-temp-adambom. You don't need the retry stuff, just used refetch as you always.

**Comment by kdong007** [comment]
@adambom  just found an issue with the fix.  First you get an error state for the component, and then update some props of the component, data.loading become true and data.error is cleared.

I tracked the issue down to apollo-client, the issue is related to unsubribe/create query, so the old error result is removed by tearDownQuery()

**Comment by adambom** [comment]
@kdong007 Can you provide repro steps and let include line numbers of the code you're referencing?

I'll do my best to address the issue if possible if you're able to provide some more information, but it was really only meant to be a hack, so there may be a better way of addressing the problem.

**Comment by kdong007** [comment]
@adambom 
I just realized it is not refetch related. I posted another one here. https://github.com/apollographql/react-apollo/issues/1509

**Comment by Elijen** [comment]
@kdong007 @adambom So what is the answer to the original question? Is `refetch` supposed to update the component's props? I think the linked issue is only relevant if one of the `refetch` queries fails.

**Comment by rosskevin** [comment]
Closing - housekeeping - ping me if it needs to be reopened.
