### ISSUE TITLE
Some component forever in `loading: true` when navigating with react-router. Simple reproduction.

### ISSUE THREAD

**Issue by ghost** [apollographql/react-apollo#1397]
**Intended outcome:**
Switch my Routes with react-router.

**Actual outcome:**
When I switch routes with react-router `Link` my components exported with `export default graphql(CURRENT_USER_QUERY)(Menu);` are forever in `loading: true`;

**How to reproduce the issue:**
- Codesandbox: https://codesandbox.io/s/p90q6674qq

I simply use:

```javascript
export default graphql(CURRENT_USER_QUERY)(Menu);
```

on the `Menu` component and simply this code in `App` component:

```javascript
    class App extends Component {
      render() {
        return (
          <div>
            {/* <Menu /> */}
            <Route component={Menu} />
            <Route exact path="/" component={Home} />
            <Route path="/login" component={Login} />
          </div>
        );
      }
    }
```

A bug?

Where am I wrong?

**Version**
- apollo-client-preset@1.0.5
- react-apollo@2.0.4

**Comment by nfantone** [comment]
Possibly related to #1385?

**Comment by hwillson** [comment]
Tracking in https://github.com/apollographql/react-apollo/issues/1385; closing here. Thanks!
