### ISSUE TITLE
How to declare fragment in functional component in Typescript?

### ISSUE THREAD

**Issue by goldenbearkin** [apollographql/react-apollo#1406]
I can easily declare a fragment in a class component by adding a static method.

```js
export default class PokemonCard extends React.Component {

  static fragments = {
    pokemon: gql`
      fragment PokemonCardPokemon on Pokemon {
        url
        name
      }
    `
  }
  // ...
}
```

How do i do the same in functional component in Typescript?

```js
PokemonCard.fragments = {
  pokemon: gql`
    fragment PokemonCardPokemon on Pokemon {
      url
      name
    }
  `,
};
```

<img width="422" alt="screen shot 2017-12-13 at 11 00 24 pm" src="https://user-images.githubusercontent.com/11225712/33945257-7b5976b4-e059-11e7-8071-3b3c6d880c4f.png">

// error: 'fragments' does not exist on type 'typeof PokemonCard'

**Comment by rosskevin** [comment]
`fragments` isn't known to `React.StatelessFunctionalComponent`, so you'll have to cast as `any` if you want to use this approach.

```js
(PokemonCard as any).fragments = {
  pokemon: gql`
    fragment PokemonCardPokemon on Pokemon {
      url
      name
    }
  `,
};
```

**Comment by lewisf** [comment]
We've run into this problem a bunch because the actual documentation for `react-apollo` says to do this: https://www.apollographql.com/docs/react/features/fragments.html

Unfortunately, this is going to break any type guarantees w/ both Typescript and Flow.

Can we instead recommend exporting the fragments object as an `export const`?

**Comment by jacobwgillespie** [comment]
I believe it's also possible to extend the definition of React's StatelessComponent - something like this:

```typescript
import * as react from 'react'

declare namespace React {
  interface StatelessComponent<P = {}> {
    fragments?: {[name: string]: any}
  }
}
```
