### ISSUE TITLE
how to pass query variables to query 

### ISSUE THREAD

**Issue by ketankulkarni** [apollographql/react-apollo#1411]
/* eslint-disable*/

import React, { Component } from 'react'
import ItemsList from './ItemsList'
import { Stats, BigBreadcrumbs, WidgetGrid, JarvisWidget } from '../components'
import Datatable from './tables/Datatable'
import SparklineContainer from './graphs/inline/SparklineContainer'
import CreateItem from './createItem.js'
import { graphql } from 'react-apollo';
import gql from 'graphql-tag';
import { log } from 'core-js/library/web/timers';
import Itemtable from './itemTable.js';

class Items extends Component {
  constructor(props) {
    super(props);
    this.handleSearch = this.handleSearch.bind(this);
    this.state = {
      searchText: '',
      searchResult: []
    }
    render(){
         return(
               <div>
                         <input type="text"  onChange={(e)=>{this.setState({searchText:e.target.value})}}/>
                           { /*      code to display data from getItemInfo  */ }
                </div>
          )
    }

  }

const query = gql`
query getItemInfo($name:String){
	getItemInfo(name:$name){ 
  	id, 
  	name 
	},
  items{
    id,
    name
  }
}
`
export default graphql(query, {
  options: {
    variables: {
      name: "%Agent%"
    }
  }
}
)(Items);

expected  - set state then pass state value to query

**Comment by mauscoelho** [comment]
@ketankulkarni here an example https://www.apollographql.com/docs/react/basics/queries.html#graphql-config-options-variables

**Comment by ceeceeS** [comment]
@ketankulkarni have you found a solution for your solution ? if so ! can you help me please? I have the same issue. Thank you

**Comment by julianmnst** [comment]
@mauscoelho what about with the graphql() function? There are no examples for that.

**Comment by jiradeto** [comment]
@julianmnst 

using **option**

```javascript
export default graphql(QueryTodos, {
  options: (props) => ({ variables: { userId: props.userId } })
})( Home );
```

**Comment by SteveAtSentosa** [comment]
I also believe that by default the HOC created by graphql will look for needed variable names on incoming props.  So if props.userId passed in (as in the example above) to the HOC, I think this would work also
```
// pulls `userId` from incoming props
export default graphql(QueryTodos)( Home );
```

**Comment by howdyhyber** [comment]
@jiradeto how to pass state value to the variables in 
options: (props) => ({ variables: { userId: props.userId } })

in my case it returns null

**Comment by dandv** [comment]
@mauscoelho: that link no longer works. Can you please update your post to link to https://www.apollographql.com/docs/react/essentials/queries.html#data ?

**Comment by mauscoelho** [comment]
@dandv thank you for helping to keep this updated

**Comment by Sagaryalioe** [comment]
> @julianmnst
> 
> using **option**
> 
> ```js
> export default graphql(QueryTodos, {
>   options: (props) => ({ variables: { userId: props.userId } })
> })( Home );
> ```

Now how do you call that QueryTodos Query?? Is it something like this.props.sth?

**Comment by gcfabri** [comment]
How can I use a result from the last graphql as a variable in second request?

```javascript
compose(
  graphql(readOfferQuery, {
    name: 'readOfferQuery',
    options: ({ id, slug }) => ({
      variables: {
        [id ? 'id' : 'slug']: id ? id : slug
      }
    })
  }),
  graphql(featuredOffersQuery, {
    name: 'featuredOffersQuery',
    options: ({ readOfferQuery }) => {
      return {
        variables: {
          limit: 20,
          prizes: readOfferQuery.readOffer.prizes,
          type: readOfferQuery.readOffer.type
        }
      };
    }
  })
)
```

**Comment by rosskevin** [comment]
@gcfabri this would be easier without the HOC - use the `<Query />` component and nest another that uses the result.

**Comment by natterstefan** [comment]
@gcfabri Not sure if this is still relevant for you, but I did exactly what is described here https://stackoverflow.com/a/49320606/1238150 and it worked for me. Maybe this helps you too.

**Comment by gcfabri** [comment]
@natterstefan thanks, but I used the `<Query />` component. I was having problems with `skip` and` graphql` HOC as in this StackOverflow example.

**Comment by khuznain** [comment]
//Incase some one needed it .
import { withFormik } from "formik";
import React from "react";
import { compose, graphql } from "react-apollo";
import * as Yup from "yup";
import { createUser } from "../queries/user";

//this is the query being imported 
export const createUser = gql`
  mutation($email: String!, $password: String!) {
    createUser(userInput: { email: $email, password: $password }) {
      _id
      email
    }
  }
`;

//This is our form
const LoginForm = props => {
  const {
    values,
    touched,
    errors,
    isSubmitting,
    handleChange,
    handleBlur,
    handleSubmit
  } = props;

  return (
    <form onSubmit={handleSubmit}>
      <h4 className="card-title">Login</h4>
      <div className="form-group">
        <label>Email</label>
        <input
          name="email"
          type="text"
          className={`form-control ${errors.email &&
            touched.email &&
            "is-invalid"}`}
          value={values.email}
          onChange={handleChange}
          onBlur={handleBlur}
        />
        {errors.email && touched.email && (
          <div className="invalid-feedback">{errors.email}</div>
        )}
      </div>
      <div className="form-group">
        <label>Password</label>
        <input
          name="password"
          type="password"
          className={`form-control ${errors.password &&
            touched.password &&
            "is-invalid"}`}
          value={values.password}
          onChange={handleChange}
          onBlur={handleBlur}
        />
        {errors.password && touched.password && (
          <div className="invalid-feedback">{errors.password}</div>
        )}
      </div>

      <div className="form-group m-0">
        <button
          type="submit"
          className="btn btn-primary btn-block"
          disabled={isSubmitting}
        >
          {isSubmitting ? "Wait Please" : "Login"}
        </button>
      </div>
      <div className="mt-4 text-center">
        Don't have an account? <a href="register.html">Create One</a>
      </div>
    </form>
  );
};

//compose with graphql
export default compose(
  graphql(createUser),
  withFormik({
    mapPropsToValues: () => ({ email: "", password: "" }),

    validationSchema: Yup.object().shape({
      email: Yup.string()
        .email("E-mail is not valid!")
        .required("This field is requuired !"),
      password: Yup.string().required("This field is requuired !")
    }),

    handleSubmit: async (
      values,
      { props: { mutate }, setSubmitting, resetForm }
    ) => {
      try {
        const { data } = await mutate({
          variables: values
        });
        setSubmitting(false);
        console.log(data);
      } catch (error) {
        setSubmitting(false);
        console.log(error);
      }
    }
  })
)(LoginForm);

**Comment by Ethaan** [comment]
@SteveAtSentosa i was wondering why the hellll was this working

```
export default compose(graphql(TRIBE_ALL_MEMBERS_QUERY, {
  props: ({ data: { memberStatus } }) => ({ memberStatus }),
}))(({ memberStatus, isTribeOwner }) => (
```

if i never pass any `variables: {...}` the component was called like

`<TribeMemberButton isTribeOwner={tribeOwner === _id} tribeId={tribeId} profileId={_id} />`

jajaj, your comment just help me think i'm not stupid/crazy

**Comment by andrevenancio** [comment]
Going through the documentation from a frontend point of view makes sense, but having to build the API and the Frontend myself Its a bit confusing. on the example on the documentation there is

```javascript
query Dog($breed: String!) {
    dog(breed: $breed) {
        // some code
    }
}
```

But where is that uppercase `Dog` defined? and the lowercase `dog` ? Would be useful to see the client part of the examples.

**Comment by joaquincastillo** [comment]
@andrevenancio Could you understand that example in the docs?

**Comment by mauscoelho** [comment]
@andrevenancio the `Dod` is just an alias for your query. The `dog` is defined in the schema in your API. You can take a look in this [site](https://graphql.org/) for more explanation.
