### ISSUE TITLE
No autorefetch after first prop change

### ISSUE THREAD

**Issue by Ziker22** [apollographql/react-apollo#1429]
Hi guys,
I'm still faire new to this so maybe thats my mistake but here we go
I have simple table wich checkboxes when user checks checkbox its id goes to array and this array is then used to create filter object which is inserted as queryVariable

Heres my code

```
`export const MULTI_CLIENT_ALERTS_QUERY = gql`
  query multiClientAlerts($filter: GraphQLFilter) {
   report {
     a(filter : $filter) {
      computerName
  }
}
}
`;

export const MULTI_CLIENT_ALERTS_QUERY_OPTIONS = {
    name : "multiClientAlertsReport",
    options: (ownProps : any) =>(
        {
            skip: ownProps.multiSelectedIds.length === 0,
            variables: {
                filter :  createGQLUuidFilter("OP_IN_EXACT", 657, ownProps.multiSelectedIds)
            },
            fetchPolicy: 'cache-and-network',

        })}`

```
createGQLUuidFilter is very basic function

```
export function createGQLUuidFilter(operator , symbolId, values)  {
    return {
        uuidFilters : {operator: operator, symbolId : symbolId, value : values},
    }
}
```

Now to my problem. When user checks first checkbox request is fired with right id and right result will come back. But second and also every other request wont even fire despite `ownProps.multiSelectedIds` are updating properly. 

Not sure if its is not similar to https://github.com/apollographql/react-apollo/issues/289

**Comment by ShockiTV** [comment]
Well, first, `skip` is not part of the `options`, but should be set on same level as `name` which would probably explain the freeze/crashing of HoC if you are not receiving something marked as mandatory.

**Comment by Ziker22** [comment]
```
export const MULTI_CLIENT_ALERTS_QUERY_OPTIONS = {
    name: "multiClientAlertsReport",
    skip: (ownProps: any) => {
        console.log(ownProps.multiSelectedIds.length === 0);
        return ownProps.multiSelectedIds.length === 0
    },
    options: (ownProps: any) => {
        return {
            variables: {
                filter: createGQLUuidFilter("OP_IN_EXACT", 657, ownProps.multiSelectedIds)
            },

        }
    }
}
```

Changed to this but no change :/

**Comment by rosskevin** [comment]
Closing - housekeeping - this looks better suited to stackoverflow.
