### ISSUE TITLE
JSON value '<null>' of type NSNull cannot be converted to NSString

### ISSUE THREAD

**Issue by mauscoelho** [apollographql/react-apollo#1441]
**Intended outcome:**
I am requesting a simple query on a graphcool server.  I'm not sure that the problem is `react-apollo`, but always that is requested something with `react-apollo` de red screen is showed.

The query is performed with success, and everything works normally, but, this red screen is always showed

**Actual outcome:**

<img width="388" alt="screen shot 2017-12-20 at 15 07 46" src="https://user-images.githubusercontent.com/5712300/34225712-815a25d6-e5ae-11e7-912a-dd3b8e22d450.png">

**How to reproduce the issue:**

```
export const ALL_CUSTOMERS_QUERY = gql`
  query AllCustomersQuery {
    allCustomers {
      id
      name
    }
  }
`;
```

```
graphql(ALL_CUSTOMERS_QUERY, {
    name: 'allCustomersQuery',
  })
```

**Version**
- apollo-client@^2.1.0
- react-apollo@^2.0.1
- react-native@0.51.0

**Comment by rosskevin** [comment]
Unfortunately, this is not something that we can reproduce in this repository with the information you provided. I encourage you to look to our slack channel or stackoverflow for some help.  If you find a bug, a breaking test case as a PR is very helpful.

**Comment by mauscoelho** [comment]
I think that I configured `apollo-link-error` and `apollo-link-http` wrong. I removed this packages and did a simple setup and it worked. 
Thanks for response

**Comment by chrise86** [comment]
Sorry to drag up and old issue but @mauscoelho can you shed some light on what you think the issue was? Facing the same issue now.

**Comment by mauscoelho** [comment]
Hey @chrise86, it was some wrong incompatible version. Try to delete all your npm_modules, cache. Update all your Apollo libs and try clean and rebuild :)
