### ISSUE TITLE
2.0.4 requires unstated dependency @types/lodash.flowright

### ISSUE THREAD

**Issue by jonaskello** [apollographql/react-apollo#1445]
Error description is already in #1286 but it is closed so I open another issue because this error is also in 2.0.4 (which has been confirmed several times in #1286). 

Basically, if you just install 2.0.4 it is broken from the start with this error. The easiest work-around is to add a file `fix-react-apollo.d.ts` (the name does not matter) which contains one line `declare module "lodash.flowright";` as described in [this comment](https://github.com/apollographql/react-apollo/issues/1286#issuecomment-350591666).

**Comment by rosskevin** [comment]
Watchers please check and discuss my comment https://github.com/apollographql/react-apollo/pull/1478#issuecomment-354132340 in the PR.
