### ISSUE TITLE
missing documentation for flow

### ISSUE THREAD

**Issue by maasencioh** [apollographql/react-apollo#1446]
Currently is very criptic to add any flow checker using `withApollo`. Reading and playing a bit with the code we found the `MutationFunc<MutationInput>` type, but we are not able to find the one for the queries.

In addition, it would great to explain the signature of the graphql tag itself, `graphql<Response, InputProps, WrappedProps>` is not very easy to understand and I could not find any docs explaining this.

I would be glad to help documenting, but is quite messing to understand the current flow file.

**Versions**
- apollo-client-preset@1.0.5
- react-apollo@2.0.4
- flow-bin@0.61.0

**Comment by rosskevin** [comment]
Flow is not up to date in this project and we need a flow maintainer.  If you want to help, feel free to jump-in.  Types are checked in `test/flow-usage.js`, and flow types are listed in `index.js.flow`.

**Comment by hwillson** [comment]
Flow is no longer support in React Apollo. Thanks!
