### ISSUE TITLE
Can't connect my graphql server to Apollo

### ISSUE THREAD

**Issue by goodbeysr** [apollographql/react-apollo#1470]
Hello guys ! Well I Created a java graphql server and when i try to connect it with my apollo client this is the
error i get  : 

![image](https://user-images.githubusercontent.com/22368199/34368701-bcc0e188-eaad-11e7-93c2-f47b6b6b2703.png)

The java server lunched with maven is working perfectly via the http://localhost:8080/graphql , and this is my apollo config : 

![image](https://user-images.githubusercontent.com/22368199/34368721-f5e90a44-eaad-11e7-81be-2378b0b447b9.png)

**Comment by rosskevin** [comment]
Please try our slack channel referenced on the Readme or stackoverflow for support questions.

http://www.apollostack.com/#slack
