### ISSUE TITLE
[TypeScript] errorPolicy is not typed in QueryOpts

### ISSUE THREAD

**Issue by renatorib** [apollographql/react-apollo#1486]
In Apollo docs says about `errorPolicy` on `options`

![image](https://user-images.githubusercontent.com/3277185/34418276-58d2d25c-ebe4-11e7-90bd-1ce8e95464fe.png)

But it's not typed properly

![image](https://user-images.githubusercontent.com/3277185/34418287-669506a8-ebe4-11e7-83ff-1df7040954a8.png)

```ts
export interface QueryOpts<TVariables = OperationVariables> {
    ssr?: boolean;
    variables?: TVariables;
    fetchPolicy?: FetchPolicy;
    pollInterval?: number;
    client?: ApolloClient<any>;
    notifyOnNetworkStatusChange?: boolean;
    skip?: boolean;
}
```
(do not have errorPolicy property in QueryOpts)

**Version**
- apollo-client@2.0.2
- react-apollo@2.0.1

**Comment by emaren84** [comment]
May I work on it? It's literally my first issue though.
