### ISSUE TITLE
Compose break multiple querys with same variable

### ISSUE THREAD

**Issue by Skaronator** [apollographql/react-apollo#1487]
I'm fairly new to Apollo and GraphQL. Maybe I made a mistake but this looks like an actual bug.

**Intended outcome:**
I got 2 querys, both with the same variable called `limit` which are composed together via the `react-apollo` compose function. When I refetch the 1st query it should only modify the 1st query's data. When refetching the 2nd query it should only modify the 2nd query's data.

**Actual outcome:**
I can refetch each query simply with `refetch({limit: 12})` which works fine if as long as you refetch only the first query of the compose. **When refetch the second query** on the compose **it actually modify the on the first query** back to the default value.

**How to reproduce the issue:**
Here is a video how it looks like https://streamable.com/6qitn
And here can you find the code snippet of that page: https://pastebin.com/jqbhhcWV

I'll provide a example later, maybe you're already able to reproduce it with this information.

**Version**
```
"apollo-cache-inmemory": "1.1.4",
"apollo-client": "2.1.0",
"apollo-link": "1.0.7",
"apollo-link-context": "1.0.3",
"apollo-link-http": "1.3.2",
"react-apollo": "2.0.4",
```

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
