### ISSUE TITLE
Mutation Component

### ISSUE THREAD

**Issue by lifeiscontent** [apollographql/react-apollo#1515]
Hi there,

I noticed you guys are starting work on a Subscriptions and Query component. Are there plans for mutations as well?

I was thinking of writing my own based off the Query component, but curious if/when this might be available.

Thanks!

Also, any chance you guys could add the ability to get the latest code of apollo through npm? Currently I don't believe there's a way to use the Query component without ripping it out of the codebase.

I'd love to spend time using these components and giving feedback early.

**Comment by excitement-engineer** [comment]
Hey, @lifeiscontent! We will probably start providing an @next version through npm that will allow you to start using all these new components.

We are still debating whether to implement a Mutation component and if so what the API of this component should look like. Expect to hear some updates on this soon

**Comment by lifeiscontent** [comment]
@excitement-engineer awesome if you guys are interested in feedback I’d love to help

**Comment by excitement-engineer** [comment]
I've got a PR up #1520 with an initial idea. If you have some feedback let me know:)

**Comment by klarstrup** [comment]
This is in the RC, time to close the issue.
