### ISSUE TITLE
2.1 examples update

### ISSUE THREAD

**Issue by rosskevin** [apollographql/react-apollo#1525]
All examples need to be updated for 2.1 (or whatever we call the next release).  I started on the `typescript` example but it is not yet completed.  My desire is to have the `examples/typescript` usable from codesandbox.io and stuck in our issue template.

Examples to update:
- [ ] typescript
- [ ] ssr
- [ ] flow
- [ ] components
- [ ] base

**Comment by mvestergaard** [comment]
How close are you to be able to release a preview of 2.1?  
I tend to dislike HOCs, especially in typescript, because the types generally don't flow as naturally through them. I really like the new component based approach.

We're starting a new project, and would like to base it on the component approach rather than the HOC one.  
It's ok - for us at least; if the API isn't final/feature complete

**Comment by rosskevin** [comment]
@mvestergaard we are working towards more frequent releases, but I don't have an answer when 2.1 is going to be out.  @jbaxleyiii was discussing yesterday.  

Feel free to try out my temp build if you are prototyping `@alienfast/react-apollo`.

**Comment by nfantone** [comment]
@rosskevin I'm willing to help here. Could you elaborate on what is exactly is needed, please?

**Comment by rosskevin** [comment]
Thanks @nfantone updating any of the examples listed to work would be great.  I was switching the `typescript` example to a strongly typed usage of the new `Query` component.  But all updates to any of the examples are appreciated.

**Comment by nfantone** [comment]
Care to share a link with an example of what you are currently working on? As a guideline to collaborators.

**Comment by rosskevin** [comment]
Here's work in progress on typescript: https://github.com/apollographql/react-apollo/blob/master/examples/typescript/src/Character.tsx#L20

Now that I look, all of the examples are quite different from each other - which I did not expect.  I actually expected them to be the same but slightly different flavors.  I'm not sure that what we have is the best/simplest way or not as I have not reviewed them all.

@jbaxleyiii do you have feedback on what ideal examples directory would look like?  I was thinking identical in content with variations for the tech - typescript/flow/ssr.

**Comment by kandros** [comment]
willing to help too

**Comment by kandros** [comment]
> identical in content with variations for the tech - typescript/flow/ssr.  

+1 for this 

As of today the typescript example is broken due to some dependencies, upgrading them raises new errors from the examples itself. there's so much going in the project that is hard to touch at the moment.

**Comment by kandros** [comment]
I had the typescript exampes to work, very painful but it works :D 
#1586

**Comment by hwillson** [comment]
This was done - thanks!
