### ISSUE TITLE
Query component is not present in the build

### ISSUE THREAD

**Issue by kandros** [apollographql/react-apollo#1530]
**Intended outcome:**
Importing Query component https://github.com/apollographql/react-apollo/blob/master/src/Query.tsx

**Actual outcome:**
The file is not present in the version installed via npm (2.0.4)

**How to reproduce the issue:**
Install react-apollo via npm

The Query file is present in `node_modules/react-apollo`

**Version**
- apollo-client@2.0.4
- react-apollo@2.0.4

**Comment by kandros** [comment]
Looks like running the compilation script and publish to npm will be enough

**Comment by rosskevin** [comment]
This is not a bug, it is not yet release.
