### ISSUE TITLE
props.data.error is always undefined for a query with variable

### ISSUE THREAD

**Issue by petromoldovan** [apollographql/react-apollo#1546]
Team, thanks for the awesome job!

**Intended outcome:**
graphQL errors must be shown in props.data.error

**Actual outcome:**
props.data.error is always undefined for a query with variable

**How to reproduce the issue:**
I am sending this query to my golang graphql server
```
export const getUserQuery = gql`  
    query GetUser($filter: Filter!) {
        user (filter: $filter) {
            id,
            username
        }
    }
```
where filter is 
```
filter: {
   id: '12345'
}
```
so basically i am fetching user with id.

I am providing false id to get graphql error. I am able to catch the error in apollo client with standard implementation of `apollo-link-error`:
```
const errorLink = onError(({ graphQLErrors }) => {
      if (graphQLErrors) {
        graphQLErrors.map(({ message, locations, path }) => {
            console.log(`[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`)
          }
        )
      }
    })
```

Nevertheless, the error is not communicated to the react component. `data.props.error` is always undefined in react component that initiated the query.

I am confused because `data.props.error` gets updated when i have problems with "get all" query:
```
export const getALLUsers = gql`
    query getALLUsers {
        users {
            username,
        }
    }
```

Please let me know if I am doing smth wrong.

**Stack:**
"react-apollo": "^2.0.4",
"graphql": "^0.12.3",
"graphql-tag": "^2.6.1",
"apollo-cache-inmemory": "^1.1.5",
"apollo-client": "^2.2.0",
"apollo-link": "^1.0.7",
"apollo-link-error": "^1.0.3",
"apollo-link-http": "^1.3.2",

**Comment by daryn-k** [comment]
Same issue. Did you solve that?

**Comment by DannyvanHolten** [comment]
Any progress on this?

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!

**Comment by semy** [comment]
I use React Apollo 3.1.3, the bug still exists :-/

**Comment by Pau1fitz** [comment]
still seeing this bug.
