### ISSUE TITLE
Unable to upgrade Apollo stack to graphql v0.12.3

### ISSUE THREAD

**Issue by kavink** [apollographql/react-apollo#1559]
I have tried upgrading my dependencies to grapqhl v0.12.3, but after I do that the app does not work anymore. Wondering if anyone else has had this issue for Apollo-client/react-apollo and apollo stack in general?

Will the upgrade to grapqhl v0.12.3 be supported ?

**Comment by kavink** [comment]
``` instanceOf.js:11 Uncaught Error: Cannot use e "__Schema" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.```

**Comment by knipferrc** [comment]
Im having this same issue, were you able to fix it? @kavink

**Comment by kavink** [comment]
@knipferrc do you have a dependency on graphql data type JSON ?

**Comment by barbalex** [comment]
This seems to be a graphql issue that was solved with graphql v13: https://github.com/graphql/graphql-js/pull/1174
