### ISSUE TITLE
Syntax Error: Expected Name, found $

### ISSUE THREAD

**Issue by michaelcuneo** [apollographql/react-apollo#1566]
I've set up a query to wp-graphql-jwt-authorisation and I can't seem to find a way to stop it from telling me

**Syntax Error: Expected Name, found $**

GraphQL request (3:15)
2:       mutation {
3:         login($username: Username!, $password: Password!) ( input: {
                 ^
4:           clientMutationId: "loginID"

**Here is the way I have set up my requests.**

  const username = yield select(makeSelectUsername());
  const password = yield select(makeSelectPassword());

  const client = new ApolloClient({
    link: new HttpLink({ uri: 'http://localhost/graphql' }),
    cache: new InMemoryCache()
  });

    const request = gql`
      mutation {
        login($username: Username!, $password: Password!) ( input: {
          clientMutationId: "loginID"
          username: $username
          password: $password
      } )
      {
        authToken
      }
    }`

    const result = graphql(request, {
      options: { variables: { username: username, password: password } },
    });

- apollo-client@2.2.0
- react-apollo@2.0.4

**Comment by nandito** [comment]
For me the syntax error in the mutation seems valid. If you would like to pass variables to a mutation you have to define their types next to the `mutation` keyword. Check the Apollo's [mutations docs](https://www.apollographql.com/docs/react/basics/mutations.html#calling-mutations).

In your case it should look like something like this:

```
const request = gql`
  mutation login($username: Username!, $password: Password!){
    login(
      input: {
        clientMutationId: "loginID"
        username: $username
        password: $password
    }
  )
  {
    authToken
  }
}`
```

**Comment by hwillson** [comment]
As mentioned in https://github.com/apollographql/react-apollo/issues/1566#issuecomment-360490436, the error you're getting is valid.
