### ISSUE TITLE
SSR should check that instance belongs to Apollo before calling `fetchData`

### ISSUE THREAD

**Issue by asmockler** [apollographql/react-apollo#1571]
**Intended outcome:**

`fetchData` should not be called on components that do not belong to `react-apollo` during server render.

**Actual outcome:**

If the component is not expecting `fetchData` to be called, SSR will fail. Right now, when walking the tree, `react-apollo` only checks if an instance exists and that it has a function called `fetchData`:

https://github.com/apollographql/react-apollo/blob/9222ab3c003467bd0b0e1bf47b3ba50dc6e32840/src/getDataFromTree.ts#L139-L154

That is problematic if the instance has a function called `fetchData` that should not be called during server rendering.

**How to reproduce the issue:**

Add something along the lines of the following to a component being server rendered:

```javascript
class MyComponent extends React.Component {
  fetchData() {
    throw new Error('fetchData should not be called');
  }

  render() { return null; }
}
```

**Version**
- apollo-client@2.0.3
- react-apollo@1.4.15

**Comment by benjamn** [comment]
The implementation of `getDataFromTree` has changed substantially in `react-apollo@2.3.1` (the latest version), thanks to #2533. In particular, we no longer attempt to detect whether component instances have a `fetchData` method. Please try updating, and feel free to reopen this issue if the problem persists.
