### ISSUE TITLE
Local development - How to contribute?

### ISSUE THREAD

**Issue by kandros** [apollographql/react-apollo#1583]
I'm having a hard time understanding how to develop locally, considering the non-trivial build-pipeline some documentation about it would make contribution much easier.

for example:
the `watch` npm script create a different result than the `compile` script.

I would like to help document this, but obviously, I need some support from someone already involved.

**Comment by rosskevin** [comment]
Please feel free to ping me on the slack channel with questions. Specifically there is an open contributors channel.

**Comment by danilobuerger** [comment]
Issues here are reserved for bugs, but one of the following resources should help:

* Apollo's Slack: https://www.apollographql.com/slack
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests
