### ISSUE TITLE
Document client prop

### ISSUE THREAD

**Issue by estaub** [apollographql/react-apollo#1588]
Support for the client option on old-school `graphql()` queries is absent from &lt;Query>.

[`graphql()` options](https://github.com/apollographql/react-apollo/blob/master/src/types.ts#L27) 
[`<Query>` options](https://github.com/apollographql/react-apollo/blob/master/src/Query.tsx#L64)  

This may have happened because [the client option was never documented](https://www.apollographql.com/docs/react/basics/queries.html#graphql-query-options).

The original author of the `client` option PR was silent for 6 months, then posted [this](https://github.com/apollographql/react-apollo/pull/729#issuecomment-359870398), indicating that he's no longer interested in working on it.

If the `client` option is deprecated, it would probably be good to post something, including a comment on the PR above so that subscribers see it, and a recommended approach to addressing a requirement for multiple clients.

The best way forward may be influenced by the functionality provided by the  `QueryRecyclerProvider` in `<ApolloProvider>`; I'm afraid I don't understand what it does.  

(Thanks!)

**Comment by kandros** [comment]
It was proposed to pass client as the second parameter to the renderer function, can't remember where I read it though.

**Comment by astorije** [comment]
That would be great! We currently have a use case where we need to talk to more than one client, so that would make things cleaner.

**Comment by peaonunes** [comment]
The following code line from current version (2.1.9) and both `Query` and `Mutation` gives precedence to props `client`. So we can indeed override the `default client` via `props`. 
```
// https://github.com/apollographql/react-apollo/blob/master/src/Query.tsx#L167
// https://github.com/apollographql/react-apollo/blob/master/src/Mutation.tsx#L120
...
this.client = props.client || context.client;
...
```

You would use like:
```
<Query query={query} client={client}>
...
</Query>
```

The feature is not documented though. 
In addition to that the most common approach would be having a Gateway API running GraphQL and managing queries to different targets APIs. I wrote this [article](https://medium.com/@peaonunes/apollo-multiple-clients-with-react-b34b571210a5) discussing some approaches if you really want to do that and pointing out some pros and cons.

**Comment by rosskevin** [comment]
Please PR any docs you would like to see. Client prop is definitely not going away.

**Comment by danilobuerger** [comment]
Documented here: https://www.apollographql.com/docs/react/api/react-apollo.html#query-render-prop
