### ISSUE TITLE
Allow config.skip to access previous props

### ISSUE THREAD

**Issue by randing89** [apollographql/react-apollo#1593]
`config.skip` function is called before render. However, currently, it only has access to `props`. It is essentially `nextProps` in react lifecycle. The `config.skip` doesn't have fine-grained control for skipping the query for a particular prop change.

**Intended outcome:**
passing the previous props through parameters
```
{
    skip: (props, prevProps) => {
        return props.id === prevProps.id;
    },
}
```

or passing the component instance
```
{
    skip: (props) => {
        return props.id === this.props.id;
    },
}
```

**Actual outcome:**
No access to current props.

**Comment by smeijer** [comment]
I think this would be welcome for other methods as well. For example the `props` part.

```js
props: ({ data, ownProps, prevProps }) => ({
  entries: [...data.entries, ...prevProps.entries],
})
```

**Comment by nfantone** [comment]
This is exactly what I was looking for today and would be a neat addition to both `skip` and `props`.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, React Apollo feature requests are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Allow%20config.skip%20to%20access%20previous%20props&body=Migrated%20from:%20apollographql/react-apollo%231593) to start the feature request migration process. This manual migration process is intended to help identify which of the outstanding feature requests are still considered to be of value to the community. Thanks!
