### ISSUE TITLE
CacheResolvers seems to not do the job

### ISSUE THREAD

**Issue by 0m15** [apollographql/react-apollo#1597]
**Intended outcome:**

I've a list of `Items` and a `Item` detail.
Configured `cacheResolvers` in this way:

```
dataIdFromObject: o => {
    return o.id
  },
cacheResolvers: {
    Query: {
      product: (_, args) => {
        return toIdValue(cache.config.dataIdFromObject({
          __typename: 'Item', id: args.id
        }))
      },
    },
  },
```

When I fetch `items` I expect that on a subsequent fetch to `item(id)` I'll get the `item` with id `id` to be already present.

**Actual outcome:**

Instead `item(id)` is `undefined` and data aren't ready until fetched from network.

**How to reproduce the issue:**

Need to put up a minimal repo with it.
Essentially:

1. Create an `graphql` HOC using react-apollo to fetch items list
2. Create an `graphql` HOC using react-apollo to fetch item detail
3. Navigate between two components
 

**Version**

* apollo-client-preset@1.0.6 (it ships apollo-client@2.2.0)
* react-apollo@2.0.4

**Comment by rosskevin** [comment]
Please file an issue with apollo-client, it is responsible for this area.
