### ISSUE TITLE
Passing components state (select value) to query variable

### ISSUE THREAD

**Issue by ceeceeS** [apollographql/react-apollo#1598]
Hello guys, I'm having a little problem. Being a beginner in "react apollo ...", I want to pass the value of my state "selectCarcolor" as parameter of my query.This must be done when I select a color from the drop-down list.I read a lot of things in the documentation but I do not know where to start.

You can see all of my code here:  [https://github.com/ceeceeS/PI_Carre_Project/blob/master/idj-front/src/components/RequestEditor.js](url)

onChangeCarColor(e){
  //const selectCarcolor = this.state.selectCarcolor
  this.setState({ selectCarcolor:e.target.value})

    console.log("color "+this.state.selectCarcolor);
}

const Cquery =  gql` query getAllUsers($color: String!){
    getAllUsers(color: $color) {
    name
      _id
      color 
    }
  }
}
`
;
const datafetch = graphql(Cquery,{
  options: props=> ({
    variables: { color:  **Here I want to pass the select value**},
  })
})
Hoping for a little help from you.

Thank you guys!

**react version :16.2.0
react-apollo version : 2.0.1**

**Comment by alexandprivate** [comment]
Any solution so far ??? I'm with the same problem here.
