### ISSUE TITLE
HOC violates contract of `componentWillReceiveProps`

### ISSUE THREAD

**Issue by rocketraman** [apollographql/react-apollo#1611]
**Intended outcome:** When I wrap a component with a `graphql` HOC, the behavior of React's calls to `componentWillReceiveProps` on the underlying component should not change.

**Actual outcome:** Currently, when wrapping with a HOC, `componentWillReceiveProps` is no longer called in situations in which it should be.

This is due to the shallowEquals done on all props here:

https://github.com/apollographql/react-apollo/blob/b1e346c7b8de1187f736a437888b4206c224fda8/src/graphql.tsx#L179

This comparison should either be removed, or it should account for props not managed by the HOC.

**How to reproduce the issue:**

1) https://codesandbox.io/s/4q0645k8w
2) Click on `render`. 
3) Click on `Set state foo=false`. 
4) Click on `render` again.

In step 4, the component state should update via `componentWillReceiveProps`. It does not.

In this sandbox, we have the exact same `App` component, without the Apollo HOC: https://codesandbox.io/s/xpyjmknp14 and you can see that the behavior is now correct.

**Version**: 2.0.4

* apollo-client@2.2.1
* react-apollo@2.0.4

**Comment by rocketraman** [comment]
This issue necessitates crummy workarounds like adding a `uuid` or `counter` prop to the component where it is used.

**Comment by shoebmogal** [comment]
@rocketraman can you give an example on how to force componentWillReceiveProps?

Thanks

**Comment by rocketraman** [comment]
> @rocketraman can you give an example on how to force componentWillReceiveProps?

@shoebmogal  This is the repro recipe using the Apollo HOC "fixed" with a uuid prop: https://codesandbox.io/s/1v23om57v7. It's an ugly hack but it works.

**Comment by simonjoom** [comment]
I found the same issue, for me the workaround was to changed to a componentWillMount because our component is rebuilded every state..

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
