### ISSUE TITLE
[2.1] Prop to skip execution in <Query/> component

### ISSUE THREAD

**Issue by scarmuega** [apollographql/react-apollo#1616]
*Use case*:
* you have an optional query, which should only be executed under certain scenarios
* you also have children inside the <Query/> component which should be rendered statically, for every scenario.

*Workaround*: I currently choose to avoid rendering the <Query/> component altogether, but this changes the tree structure, which makes children unmount and re-mount again. Also thought of passing a null gql to the query prop, but that throws an exception.

*Proposal*: add a `skip` prop to the <Query/> component. When flagged, it should bypass the graphql call, but still execute the children render prop, to maintain the same virtual dom tree structure.

**Comment by abenhamdine** [comment]
https://www.apollographql.com/docs/react/basics/queries.html#graphql-skip ?

**Comment by scarmuega** [comment]
@abenhamdine I'm referring to the new `<Query/>` component that uses render props, not the `graphql` container HOC (maybe I should make that clearer in the issue description).

AFAIK, the link you provided details the "skip" option for the later.

**Comment by abenhamdine** [comment]
>  I'm referring to the new <Query/> component that uses render props, not the graphql container HOC (maybe I should make that clearer in the issue description).

Oh yes, sorry, I realized after having posted that you were referring to the Query component.
Nethertheless, perhaps it would be useful to explain if your proposal is the equivalent (or not equivalent, and so why) of the HOC `skip` property, to be clearer for everyone.

**Comment by arahansen** [comment]
I would also really appreciate a `skip` property that is equivalent to the HOC's skip property. ie, we should still render the underlying component (children here), but not execute the query.

**Comment by arahansen** [comment]
I'm currently working around this by setting `fetchPolicy={skip() ? 'cache-only' : undefined}`

**Comment by f2net** [comment]
I think this property would be useful, too.
In real world web apps you often need to skip queries for not-logged users to avoid useless not-authenticated errors.

Thank you,
Matteo

**Comment by arahansen** [comment]
This feature should be available on 2.1.0-beta.3. Check out this PR for more info: https://github.com/apollographql/react-apollo/pull/1715
