### ISSUE TITLE
GraphQL Request Response and props are NOT identical

### ISSUE THREAD

**Issue by kondricz** [apollographql/react-apollo#1632]
Hi,

First of all, thank You for the amazing job. I bumped into a really interesting bug, and I was watching all around in my application to find the source. After checking my graphQL, my database everything is working as supposed. However:

Network request:

![image](https://user-images.githubusercontent.com/30053409/35805416-10d697a2-0a7c-11e8-9de9-770778ce3e30.png)

Logging the props:

![image](https://user-images.githubusercontent.com/30053409/35805424-1a73f7d2-0a7c-11e8-93de-ebaa601b580c.png)

Look at the email addresses. When looking at the response to the REQUEST it is pulling data properly, however something goes south once they become props.

Have You encountered this bug? My setup is : 

`    "apollo-cache-inmemory": "^1.1.5",
    "apollo-client": "^2.2.0",
    "apollo-link-http": "^1.3.2",
    "autoprefixer": "7.2.5",
    "babel-plugin-module-resolver": "^3.0.0",
    "babel-plugin-wrap-in-js": "^1.1.1",
    "concurrently": "^3.5.1",
    "express": "^4.16.2",
    "express-graphql": "^0.6.11",
    "glob": "^7.1.2",
    "graphql": "^0.12.3",
    "graphql-tag": "^2.6.1",
    "isomorphic-unfetch": "^2.0.0",
    "js-cookie": "^2.2.0",
    "materialize-css": "^0.100.2",
    "next": "^4.2.3",
    "next-apollo": "^1.0.10",
    "node-sass": "^4.7.2",
    "normalize.css": "^7.0.0",
    "now": "^9.1.0",
    "postcss-easy-import": "^3.0.0",
    "postcss-loader": "^2.0.10",
    "raw-loader": "^0.5.1",
    "react": "^16.2.0",
    "react-apollo": "^2.0.4",
    "react-dom": "^16.2.0",
    "react-modal": "^3.1.10",
    "react-quill": "^1.2.2",
    "recharts": "^1.0.0-beta.9",
    "sass-loader": "^6.0.6",
    "shortid": "^2.2.8",
    "timeme.js": "^2.0.3"`

**Comment by kondricz** [comment]
FYI:

I removed these things from my gql query:

```
      _id
      url
```

they were evaluating to null anyway. But removing them from my query fixed the issue.

**Comment by hwillson** [comment]
Sounds like this was resolved - closing, thanks!
