### ISSUE TITLE
requires a peer of graphql@^0.11.3 || ^0.12.3 but none is installed

### ISSUE THREAD

**Issue by arvi** [apollographql/react-apollo#1646]
**Intended outcome:**
Successful packages installation

**Actual outcome:**

```sh
npm WARN apollo-link@1.0.7 requires a peer of graphql@^0.11.3 || ^0.12.3 but none is installed. You must install peer dependencies yourself.
npm WARN subscriptions-transport-ws@0.9.5 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-tag@2.7.3 requires a peer of graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-cache-inmemory@1.1.7 requires a peer of graphql@0.11.7 || ^0.12.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-client@2.2.2 requires a peer of graphql@^0.11.0 || ^0.12.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-link-http@1.3.2 requires a peer of graphql@^0.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ react-apollo@2.0.4
+ graphql@0.13.0
+ apollo-client-preset@1.0.8
+ graphql-tag@2.7.3
added 14 packages in 14.528s
```

**How to reproduce the issue:**

I am following the documentation in https://www.apollographql.com/docs/react/basics/setup.html, specifically:

`npm install apollo-client-preset react-apollo graphql-tag graphql --save
`

I also tried
`npm install apollo-client apollo-cache-inmemory apollo-link-http react-apollo graphql-tag graphql --save`

**Version**

* apollo-client@^2.2.2
* react-apollo@^2.0.4

** Temporary workaround **

change graphql from `^0.13.0` to `^0.11.7`

**Comment by billnbell** [comment]
Same here!!

**Comment by samtheson** [comment]
Any resolve for this?

**Comment by bsotodo** [comment]
any  news?

**Comment by n1ru4l** [comment]
@bsotodo The warning should be surpressed by installing a "compatible" version (`npm install graphql@0.12.3`)

**Comment by bsotodo** [comment]
I had to downgrade for that but cool, the warning is gone and everything is working. Thanks @n1ru4l

**Comment by JorgeAndreiArias** [comment]
I have the same problem, I tried using "npm install graphql@0.12.3" but it did not works in my case
npm WARN apollo-link-persisted-queries@0.2.1 requires a peer of graphql@^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-subscriptions@0.5.8 requires a peer of graphql@^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-subscriptions@0.5.8 requires a peer of graphql@^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-tools@3.1.1 requires a peer of graphql@^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN @apollographql/apollo-upload-server@5.0.3 requires a peer of graphql@^0.13.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\@vue\cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by rosskevin** [comment]
Closing as out of date, confirmed more lenient peer dependencies:

 "graphql": "^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0"
