### ISSUE TITLE
[2.1 Query] throws react error

### ISSUE THREAD

**Issue by serle** [apollographql/react-apollo#1664]
I have installed react-Apollo 2.1 beta 2. 

When trying to include Query component in my render method

`
import { Query } from "react-apollo"

render() {
    return <Table>
        <Query query={query} variables={lhs_variables}>
            {
                (result) => {
                    if (result.loading) return <LoadIndicator />
                    if (result.error) return <LoadError error={result.error} />
                    return <div>Query Works!!</div>
                }
            }
        </Query>
    </Table>
}
`

It never even executes the Query and I get:

Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by serle** [comment]
Restart required after beta install

**Comment by lorensr** [comment]
Haha same problem, thanks for the solution 😊
