### ISSUE TITLE
[Feature idea] Allow mutations in Query

### ISSUE THREAD

**Issue by lorensr** [apollographql/react-apollo#1691]
One of the reasons for a render prop API is: 

> Choosing a dynamic query based on what props are used

This applied to mutations, eg `<PostForm createOrEdit='edit' />`

**Intended outcome:**

Child function is given a `mutate` param.

**Actual outcome:**

Error: `The <Query /> component requires a graphql query, but got a mutation.`

**How to reproduce the issue:**

`<Query query={MUTATION}>() => 'test'</Query>`

**Version**

* apollo-client@2.0.4
* react-apollo@2.1.0-beta.2

**Comment by arahansen** [comment]
A Mutation render-prop component [was merged a couple days ago](https://github.com/apollographql/react-apollo/pull/1683). Does this cover your use case?

**Comment by lorensr** [comment]
Ah, thank you! 😊
