### ISSUE TITLE
Mutation component operation check issues

### ISSUE THREAD

**Issue by dyst5422** [apollographql/react-apollo#1713]
The new Mutation component checks the operation. This causes problems in certain configurations where objects returned by queries have mutational methods on them.

Example:

```graphql
query ChangeUserName ($userId: String!, $newName: String!){
  user(userId: $userId) {
    changeName(newName: $newName) {
      id
      name
    }
  }
}
```

to be used as
```tsx
<Mutation mutation={changeUserNameMutation}>
{mutate => (
  <button onClick={() => mutate({ variables: { userId: 'someid', newName: 'myNewName' } })}>Change Name</button>
)}
</Mutation
```

Where my schema looks like so

```graphql
type User {
  id: String!
  name: String!
  ## Mutations
  changeName(newName: String!): User!
}

type Queries {
  user(userId: String!): User
}

type Mutation {
  createUser(name: String!): User
}

```

This pattern of having the root Queries and Mutations merely be entrants into your node graph is a very powerful pattern that I would think should be supported by Apollo.

I would want to be able to specify the above query in the Mutation component and use is just as if I had tagged it as a `mutation`.

Currently, it throws an error if it is not tagged as a `mutation`

**Comment by dyst5422** [comment]
As a side note, I removed the check for mutation operations in my local copy and it works like a charm.

**Comment by dyst5422** [comment]
I'd really like to hear from the Apollo team on this one so I know whether I'm going to have to continue to roll my own components for fetching or not.

**Comment by rosskevin** [comment]
I don't quite understand your problem, but it seems you are at odds with the graphql spec itself.  You seem to be calling something a query and using it as a mutation.  I don't see any rationale for a design change here, but happy to discuss/reopen if you can clearly state what you want different.
