### ISSUE TITLE
Compilation bug in the beta

### ISSUE THREAD

**Issue by evan-scott-zocdoc** [apollographql/react-apollo#1738]
**Intended outcome:**
Should be able to consume `react-apollo/test-utils`

**Actual outcome:**
```
ERROR in ./node_modules/react-apollo/test-utils.js
Module not found: Error: Can't resolve '../src' in '/[redacted]/node_modules/react-apollo'
```

**How to reproduce the issue:**
If you look at the transpiled output for this file, there seems to be some relative path replacement happening that breaks things:

```js
import { ApolloProvider } from './';
```

becomes

```js
var src_1 = require("../src");

// ...

src_1.ApolloProvider
```

And it should be:

```js
var index_1 = require("./");

// ...

index_1.ApolloProvider
```

**Version**

* react-apollo@2.1.0-beta.3

**Comment by evan-scott-zocdoc** [comment]
Okay this is weird... it looks fine if I pull down the repo and compile it myself. It just seems to be wrong in NPM?

**Comment by mchandler-cng** [comment]
@evan-scott-zocdoc That's correct. This was fixed in #1721 but a new release has not yet been pushed to npm.

**Comment by evan-scott-zocdoc** [comment]
Oh, I see. @jbaxleyiii could another beta be pushed?

**Comment by wildvalcom** [comment]
When can we expect a new release? This issue is very annoying.

**Comment by isuhendro** [comment]
Is this the same problem that caused ApolloProvider getting undefined i.e. _Element type is invalid_ as soon as I upgraded to `react-apollo@2.1.0-beta.3`?

``` javascript
import { ApolloProvider } from "react-apollo";
```

**Comment by rosskevin** [comment]
Closing - housekeeping
