### ISSUE TITLE
getDerivedStateFromProps: Cannot read property `currentResult` of undefined. React 16

### ISSUE THREAD

**Issue by larryranches** [apollographql/react-apollo#1748]
**Intended outcome:**
Just updated my project to React@16.3.0-alpha.1 and got many warnings about deprecation.
So i started on fixing it and one of the features of new React that componentWillReceiveProps gets removed. So this method was replaced by static one - getDerivedStateFromProps which is called both on initial mounting and on re-rendering of the component.

**Actual outcome:**
After componentWillReceiveProps replace with getDerivedStateFromProps i got error. (Attached)
image uploaded from ios 2

How to reproduce the issue:
Simply upgrade to React@16.3.0-alpha.1 and replace componentWillReceiveProps with getDerivedStateFromProps.
You will get an error

Version

react-native@<0.54.0-rc.4>
react@<16.3.0-alpha.1>
apollo-client@<2.2.2>

https://github.com/apollographql/apollo-client/issues/3101

**Comment by Nickersoft** [comment]
I got the same issue as well! Just upgraded to the React 16.3 alpha.

**Comment by Rusya44** [comment]
Same.

**Comment by heatherbooker** [comment]
I'm on react@16.2 with react-apollo@2.0.4, didn't touch any component life cycle methods just added a graphql query to a component which doesn't use any component life cycle methods and getting this error also.

**Comment by dcflow** [comment]
Update to `react-apollo@next` it fixes an issue with `getDerivedStateFromProps`

**Comment by rosskevin** [comment]
Closing - housekeeping
