### ISSUE TITLE
apollo-link-state and react-apollo: useless re-rendering of components. DEMO.

### ISSUE THREAD

**Issue by ghost** [apollographql/react-apollo#1752]
This is the console log:
![image](https://user-images.githubusercontent.com/21275217/36942107-65e7f052-1f6b-11e8-887c-457b339e43be.png)

## The reproduction demo is here: https://codesandbox.io/s/8n89yrwjx0

This is the relevant code:

```javascript
const cache = new InMemoryCache();

const stateLink = withClientState({
  cache,
  resolvers: {
    Mutation: {
      updateStatus: (_, { isEnabled }, { cache }) => {
        const data = {
          status: {
            __typename: "status",
            isEnabled
          }
        };
        cache.writeData({ data });
        return null;
      }
    }
  },
  defaults: {
    status: {
      __typename: "status",
      isEnabled: false
    }
  }
});

const client = new ApolloClient({
  link: stateLink,
  cache
});
```

Everytime it re-renders `Hello` component. **Why?**

I noticed in my Chrome console a difference in the "refetch" prop.

But, in any case, also if I use this code:

```javascript
export default graphql(STATUS_QUERY, {
    props: ({ data: { loading, error, isEnabled } }) => {
      if (loading) {
        return { loading };
      }

      if (error) {
        return { error };
      }

      return {
        loading: false,
        isEnabled
      };
    }
  }
)(Hello);
```

it seems to re-render because `props` are different by reference. **Why?**

**Version**

* apollo-client@^2.2.5
* react-apollo@^2.0.4

**Comment by adrienharnay** [comment]
Also facing this as well. Really easy to reproduce, as I have noticed any Query component will render 3 times.

**Comment by pleunv** [comment]
Also noticing that `refetch` is returning a new reference on every call. Is this intentional? Was trying to memoize a debounced filter handler (that's calling `refetch({ filter })`) but seems I'll have to stick to a class.

**Comment by hwillson** [comment]
This should no longer be an issue with current day versions of `react-apollo` (please let us know otherwise). Thanks!
