### ISSUE TITLE
feature idea: network-first fetchPolicy for Query FaC

### ISSUE THREAD

**Issue by cmberard** [apollographql/react-apollo#1756]
So I'm loving the new `<Query />` FaC Component, but I'm seeing that I end up with more hits to the server when using `cache-and-network` as my fetchPolicy than I did when using the `graphql` HOC. Basically since it is a renderProp, the query is run every time the component renders (shocking, I know). 

Below is a pattern I've implemented to minimize fetch requests with the <Query /> component...

```js
class Current extends Component {
  state = {
    fetchPolicy: 'cache-and-network'
  }

  componentDidMount () {
    this.setState({ fetchPolicy: 'cache-first' })
  }

  render () {
    const { fetchPolicy } = this.state
    const { id } = this.props

    return (
      <Query query={SomeQuery} variables={{ id }} fetchPolicy={fetchPolicy}>
        {(result) => {
          return <View {...result} />
        }}
      </Query>
    )
  }
}
```

I'm inquiring about the posibility of adding another fetchPolicy, which I'm calling `network-first` for sake of discussion. This fetchPolicy would essentially implement the pattern above:
- First request is `cache-and-network`
- Subsequent requests are `cache-first`

```js
const Desired = ({ id }) => (
  <Query query={SomeQuery} variables={{ id }} fetchPolicy='network-first'>
    {(result) => {
      return <View {...result} />
    }}
  </Query>
)
```

Not sure if anyone else is seeing similar issues, or if there are any proposals to achieve something similar that are simpler than this one. Maybe just adding another prop for `initialFetchPolicy` would make it more flexible? Regardless, thanks for all your work, really looking forward to 2.1.

* apollo-client@2.2.2
* react-apollo@2.1.0-beta.3

- [ ] has-reproduction
- [x] feature
- [ ] blocking
- [ ] good first issue

**Comment by tim-soft** [comment]
I've done something pretty similar to avoid loading screens
1. Pull from the cache first if possible -> Avoid loading screen
2. Do a refetch _once_ on the client afterwards to make sure the cache is up-to-date -> Update UI
3. Rely on cache + subscriptions after the refetch so long as the component is still mounted

The real question is if similar patterns are common enough to merit it's own fetch policy params

**Comment by cmberard** [comment]
@tim-soft I think it will become more common as the Query component gains broader usage. Now that I've had more time to play with it, the main pattern seems to be that there is an initial fetchPolicy, and a fetchPolicy for all subsequent requests on that mounted Query. What those fetch policies are varies based on whether the render is caused by a change to the query variables or not.

I think the current fetch policies probably encompass everything that's needed, but it would be handy to specify initial fetchPolicy vs fetchPolicy for subsequent renders. 

At any rate, it's not difficult to work around, just have to change how you think about fetch polices vs using the HOC.

**Comment by rosskevin** [comment]
fetch policy and cache management is the realm of apollo-client, please propose this in that repo for discussion.
