### ISSUE TITLE
In Apollo/React-Apollo 2 Child Components with other props get stuck in data.loading = true forever if child component's graphql query returns an error

### ISSUE THREAD

**Issue by cagdastulek** [apollographql/react-apollo#1758]
**Intended outcome:**

When there are 2 nested components where both components are wrapped with `@graphql` if the child component's query gets a graphql error, it should have `data.error = Error` and `data.loading = false`.

**Actual outcome:**
At first, the child component gets `data.error = Error` and `data.loading = false` but then in the next cycle it gets `data.error = null` and `data.loading = true` and gets stuck there.

**How to reproduce the issue:**
- Have a Parent component with an arbitrary graphql query
- Have a Child component inside the Parent which is wrapped by another graphql query
- Child component should have other **none-scalar props** passed to it. (See the gist below which can be used to reproduce the issue)

I created a gist as a self contained mocha test. It shows how a Parent with 3 Child components experiences this issue where first Child has no props, second has a scalar prop and third one has a props with as an object. Although the first 2 Child components render an error message, the last child ends up showing "Loading...".
https://gist.github.com/cagdastulek/113d7e30d2078a91029dcd1fc47790d7

I caught this issue in our tests while migrating our code from Apollo 1.9 to Apollo 2.2 and react-apollo 1.4 to 2.0. I have then isolated it with a test the code of which I have shared in the above link.

**Version**

* apollo-client@2.2.5
* react-apollo@2.0.4

- [x] has-reproduction
- [x] blocking

**Comment by jbaxleyiii** [comment]
@cagdastulek this is fixed on the beta which is coming out ASAP (just needs docs for added features!)

**Comment by cagdastulek** [comment]
This is great news. I will try the beta version to confirm that it is fixed on my end. Thanks!

**Comment by Jinnified** [comment]
having the same issue, is it going to be released in beta 4?

**Comment by cagdastulek** [comment]
This was fixed for me with version 2.1.1
