### ISSUE TITLE
Wrong return type of withApollo with TypeScript?

### ISSUE THREAD

**Issue by nilshartmann** [apollographql/react-apollo#1759]
I wrap a React Component with the `withApollo` HOC using TypeScript. My React Component has no "own properties", only receives the ApolloClient via the HOC. 

```
interface MyAppProps {
  client: ApolloClient<any>;
}

function MyApp(props: MyAppProps) {
  props.client.resetStore(); // OK, WORKS!

  return <div>Lorem Ipsum</div>;
}
```

When I use my component, TypeScript complains due to missing `client` property (complete error see below):

```
const MyAppWithApollo = withApollo(MyApp);

<ApolloProvider client={apolloClient}>
    <MyAppWithApollo />  <!--- ERROR: Property client is missing
  </ApolloProvider>,
```

**Intended outcome:**
One should be able to use `withApollo` without type args if the wrapped component has no own props.

**Actual outcome:**
The TypeScript compiler complains when I use the wrapped component in my code:
```
[ts]
Type '{}' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<MyAppProps, ComponentState>> & Readonly<...'.
  Type '{}' is not assignable to type 'Readonly<MyAppProps>'.
    Property 'client' is missing in type '{}'.
```

When I add type arguments to withApollo it works:
```
const MyAppWithApollo=withApollo<{}, {}>(MyApp)
```
it works.

TypeScript shows the following types for the return value of `withApollo:`

*  without type args: `React.ComponentClass<MyAppProps>`
*  with "dummy" type args ({}, {}): `React.ComponentClass<{}>

The second is correct and would also be correct IMHO also for the first case.

**How to reproduce the issue:**

* Create a React Component with out own properties
* wrap the component with `withApollo` 
* embed the wrapped component in your code

You can find an example here: https://gist.github.com/nilshartmann/8b7ffb6429708dfae19bf6b4b1b5dfd5#file-withapollobug-tsx

**Version**

* apollo-client@2.2.5 (installed via apollo-boost 0.1.1)
* react-apollo@2.1.0-beta.2 (also tried beta.3 with same result)
* typescript@2.7.2
You can find my dependencies here: https://gist.github.com/nilshartmann/8b7ffb6429708dfae19bf6b4b1b5dfd5#file-package-json

**Comment by clentfort** [comment]
Another solution is to import [`WithApolloClient`](https://github.com/apollographql/react-apollo/blob/d57f25237c69f78a7e52b586d2303844baf2d4e0/src/withApollo.tsx#L13) from `react-apollo/withApollo` and wrap your props with it. 

```tsx
interface MyAppProps {
}

type MyAppPropsInternal = WithApolloClient<MyAppProps>;

function MyApp(props: MyAppPropsInternal) {
  props.client.resetStore(); // OK, WORKS!

  return <div>Lorem Ipsum</div>;
}
```

**Comment by nilshartmann** [comment]
Hi @clentfort, while this would be possible, I still think the original typing of `withApollo` is buggy (or at least very hard to understand).

**Comment by harrygr** [comment]
With TypeScript 3 it's possible to define an `Omit` type like so:
```typescript
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
```

Now, the declaration of `withApollo` could be this:

```typescript
export default function withApollo<TProps, TResult = any>(WrappedComponent: React.ComponentType<WithApolloClient<TProps>>, operationOptions?: OperationOption<TProps, TResult>): React.ComponentClass<Omit<TProps, 'client'>>;
```

**Comment by hwillson** [comment]
If anyone is still interested in addressing this, we'd be happy to review a PR as outlined in https://github.com/apollographql/react-apollo/issues/1759#issuecomment-425755126. Thanks!

**Comment by StevenVerbiest** [comment]
I can't get withApollo to work with a class component. @clentfort's solution is not working for me. Maybe I'm implementing it wrong? 

```
interface MyComponentProps {}
interface MyComponentState {}

type MyComponentPropsInternal = WithApolloClient<MyComponentProps>

export class PropertyDetailApplicationsBase extends React.Component<MyComponentPropsInternal, MyComponentState> {
  public constructor(props: MyComponentPropsInternal) {
    super(props)
  }

  public render() {
    return <div>Lorem Ipsum</div>
  }
}

export const PropertyDetailApplications = withApollo<MyComponentProps, MyComponentState>(PropertyDetailApplicationsBase)
```

The above code throws the following error: 
The context `client` is marked as required in `ApolloConsumer`, but its value is `undefined`

**Comment by RigoTheDev** [comment]
@hwillson All done!
