### ISSUE TITLE
Why is the Mutation component's result `undefined` before the mutation is called?

### ISSUE THREAD

**Issue by rylanc** [apollographql/react-apollo#1773]
This is more of a clarification than a bug report or feature request.

When using the `Mutation` component and the mutation hasn't been called, the component passes a result that is `undefined` (see https://github.com/apollographql/react-apollo/blob/master/src/Mutation.tsx#L137).

This is clearly intentional, but it prevents the user from destructuring the result argument:
```js
<Mutation>
  {(mutate, { loading }) => (loading ? <Loading /> : <Button onClick={mutate />)}
</Mutation>
```

It's easy enough to work around:
```js
<Mutation>
  {(mutate, result) => (result && result.loading ? <Loading /> : <Button onClick={mutate />)}
</Mutation>
```

It seems to me that it would be less confusing if the result behavior more closely matched the `Query` component (the result is always an object). If the intention is to convey that the mutation hasn't been called yet, could a `called`/`notCalled` entry be added to the result?

**Version**

* apollo-client@any
* react-apollo@2.1.0-rc.3

**Comment by excitement-engineer** [comment]
@rylanc, I was also running into this issue myself. The idea of the nullable prop is that it signifies that the mutation has not been called yet. However, this does complicate destructuring.

I will create a PR to investigate the possibilities to resolve this.

Thanks for creating this PR and providing your feedback:)

**Comment by excitement-engineer** [comment]
I created a PR. Let me know if this API clears things up for you?

**Comment by rylanc** [comment]
The PR is just what I was imagining. Thanks!

**Comment by Gregoirevda** [comment]
I don't get the issue about destructuring above. The initial result always is: 
```
called: false
loading: false
data: undefined
error: undefined
```
`data` is `undefined`, but result is not. Which doesn't prevent you to 

```
<Mutation>
  {(mutate, { loading }) => (loading ? <Loading /> : <Button onClick={mutate />)}
</Mutation>
```

Is there a confusion between result and data?
