### ISSUE TITLE
🐛  Can't find field <field> on object (ROOT_QUERY) undefined [on readQuery in mutation update]

### ISSUE THREAD

**Issue by speedtreammanga** [apollographql/react-apollo#1776]
**Intended outcome:**
I'm trying to write to the Apollo store returned data from my `login mutation` on update.

Very simple query, which takes in no variables/parameters:
```javascript
export const MeQuery = gql`
  query me {
    me {
      id
      name
      email
    }
  }
`
```

Here's my `login` mutation:
```javascript
export const LoginMutation = gql`
  mutation login($email: String!, $password: String!) {
    login(email: $email, password: $password) {
      token
      beeKeeper {
        id
        name
        email
      }
    }
  }
`
```

I have this `mutation` running on a button `onClick` event
```javascript
import React from 'react'
import { graphql } from 'react-apollo'
import { LoginMutation, MeQuery } from './login.queries'

class LoginContainer extends React.PureComponent {
 // ...
  handleLogin = async () => {
    const { email, password } = this.state
    const res = await this.props.loginMutation({
      variables: { email, password },
      update: (store, { data: { login } }) => {
        const data = store.readQuery({ query: MeQuery })
      },
    })
  }
 // ...
}

export default graphql(LoginMutation, {
  name: 'loginMutation',
})(LoginContainer)

```

**Actual outcome:**
Apollo throws this error: `Can't find field me on object (ROOT_QUERY) undefined.` for this line of code:
```javascript
const data = store.readQuery({ query: MeQuery })
```
The flow goes like this, `login mutation` => `store.readQuery` => `update store`.

However, this is the first time I'm trying to fetch data from the store (by doing `store.readQuery`), so I'm guessing the ROOT_QUERY is not defined and then I'm trying to `readQuery` of an undefined store.

**How to reproduce the issue:**
none

**Version**

* apollo-client@**apollo-client-preset@^1.0.8**
* react-apollo@**^2.0.4**

# Thanks!

**Comment by gatzjames** [comment]
Hi! Reading from the store is not guaranteed to return a result - if the query you try to read is not on the cache it will throw an error -
You should wrap the readQuery / readFragment in a try catch to make sure your app doesn't break in such cases!

**Comment by speedtreammanga** [comment]
All right, I see.
Thank you James

**Comment by kimobrian** [comment]
But if you wrap the operation in a try...catch clause, how the UI update if it's depending on the cache.

**Comment by mjasnikovs** [comment]
try...catch is not proper solution to handle such issue.
I think in such situation readQuery should return null or instance of Error object.

**Comment by n1ru4l** [comment]
@mjasnikovs `null` is not possible, since it is a valid graphql return type.

**Comment by mjasnikovs** [comment]
@n1ru4l Yes, i know it. In context of readQuery it can't return plain null. You have to pass query, or maybe i am wrong...

It will return:
```JavaScript
{someQueryObject: null}
```
not
```JavaScript
null
```

**Comment by n1ru4l** [comment]
@mjasnikovs What about readFragment? Possible also an edge case... I do not see why try/catch is not a proper solution..

**Comment by mjasnikovs** [comment]
@n1ru4l Why would you design read statements, to trow exceptions by default?

This would be much cleaner and more readable solution. In my opinion.
```JavaScript
const state = cache.readQuery({query})

if (state instanceof Error) {
  return // (handle Error)
}
return // (handle cache)
```

or
```JavaScript
// Returned when cache is empty
const defaults = {iAmEmpty: 'someData'}
const state = cache.readQuery({query, defaults})
```

**Comment by JulianCurrie** [comment]
Create a default state in your store with the desired query

**Comment by myhendry** [comment]
I have the same issue "Can't find field ... on object (ROOT_QUERY) { .. }

It was working ok when I was using Apollo Boost.  I migrated to separate packages by adding inMemory, Apollo Link State etc and from there, I get the above issue without changing a single line of code in my Add and Delete handler

I switched back to Apollo Boost and the issue still persists

Any solutions? 

@JulianCurrie, how do you create a default state? Sorry for my ignorance. I only know how to create a default state for client using Apollo Link State. Tq

**Comment by myhendry** [comment]
The solution is to pass variables into your update function

the github link below will help

[https://github.com/apollographql/apollo-client/issues/2051#issuecomment-341696989](url)

**Comment by GAS2** [comment]
@myhendry dead link (404)

**Comment by n1ru4l** [comment]
@GAS2 https://github.com/apollographql/apollo-client/issues/2051#issuecomment-341696989

**Comment by norbertkeri** [comment]
Ran into this as well. If you try to readQuery on a query that was not executed before, I get the error message mentioned above. Is it expected that every readQuery call is wrapped in a try/catch? The docs don't mention anything about this.

**Comment by rosskevin** [comment]
This is an api of apollo-client, not react-apollo.  If you would like the behavior changed of `readQuery`, perhaps file an issue in apollo-client and state the case.  In the case stated, react-apollo is not intervening and you are using apollo-client directly.

**Comment by rosjio99** [comment]
Hi, I am also experiencing this issue. Did anyone solve this??

**Comment by dandv** [comment]
@rosjio99: https://github.com/apollographql/apollo-client/issues/1701#issuecomment-416851092
