### ISSUE TITLE
fetchMore doesn't set networkStatus to 3

### ISSUE THREAD

**Issue by migueloller** [apollographql/react-apollo#1779]
**Intended outcome:** When calling `fetchMore`, either when using the HOC, render prop component, remote data, or local client state, `networkStatus` should change to `3`.

**Actual outcome:** `networkStatus` never changed and when attempting to reproduce just using Apollo Client, it resulted in an error thrown.

**How to reproduce the issue:** https://codesandbox.io/s/yqyjll6931

**Version**

* apollo-client@2.2.6 (apollo-boost@0.1.2)
* react-apollo@2.1.0-rc.3

**Comment by trojanowski** [comment]
@migueloller You should set the [notifyOnNetworkStatusChange](https://www.apollographql.com/docs/react/basics/queries.html#graphql-config-options-notifyOnNetworkStatusChange) option to `true`. A working fork of your example: https://codesandbox.io/s/4w54m67k79

**Comment by migueloller** [comment]
@trojanowski,

Thanks so much for pointing that out! I thought this was set to `true` by default.
