### ISSUE TITLE
When credentials on HttpLink is set to true and no basic auth provided it fails in Safari

### ISSUE THREAD

**Issue by creeonix** [apollographql/react-apollo#1780]
**Intended outcome:**

Same in all browsers: fail or work.
In Chrome it just works.

**Actual outcome:**

When following setup is used in Safari it breaks with "Unhandled error".
<img width="976" alt="image 2018-03-12 at 10 36 44 am" src="https://user-images.githubusercontent.com/108764/37273142-89ac8d8c-25e1-11e8-810d-706c0af12821.png">

if `credentials: true` line removed it works.

**How to reproduce the issue:**

With following setup:
```
const authLink = setContext((_, { headers }) => {
  return {
    headers: {
      ...headers,
      authorization: 'Bearer some_token',
    },
  };
});

const httpLink = createHttpLink({
  uri: config.graphql,
  credentials: true,
});

const client = new ApolloClient({
  link: authLink.concat(httpLink),
  cache: new InMemoryCache(),
});
```
**Version**

* apollo-client@2.2.5
* react-apollo@2.0.4

**Comment by simsim0709** [comment]
If nobody is working on this issue, I want to try out.

**Comment by creeonix** [comment]
Oh, my bad. Thank you.
