### ISSUE TITLE
[Feature request] enable set uri async

### ISSUE THREAD

**Issue by gengjiawen** [apollographql/react-apollo#1784]
**Feature idea**
In react native, sometimes the graphql endpoint url is configured in native (in our case different flavor for dev, prod). In this case, get uri is a async function. But apollo is not support it right now.

**Comment by gengjiawen** [comment]
Is is possible we can hack this by request, something like this, but to put the uri in it
```js
  request: async operation => {
    const token = await BridgeManager.getToken()
    operation.setContext({
      headers: {
        authorization: token,
      },
    })
  },
```

**Comment by n1ru4l** [comment]
@gengjiawen It seems like this is already possible by setting the `uri` prop on the context with `apollo-link-context` (The documentation for this is currently terrible imho).

https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-http/src/httpLink.ts#L61
https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-http-common/src/index.ts#L259

This should actually work:

```js
import { ApolloLink } from 'apollo-link';
import { setContext } from "apollo-link-context";
import HttpLink from 'apollo-link-http';

const setUriLink = setContext(
  request =>
    new Promise((success, fail) => {
      // do some async lookup here
      setTimeout(() => {
        success({ uri: `http://YOUR_URI` });
      }, 10);
    })
);

const link = ApolloLink.from([
  setUriLink
  new HttpLink({ uri: '/fallback_endpoint' })
]);
```

Maybe you can test this and give some feedback? We could also improve the docs on `apollo-link-context` in combination with `apollo-link-http`, in order too provide common recipes (like this) and showcase whats possible.

**Comment by gengjiawen** [comment]
Thanks, I will give it a try.

**Comment by ccanalesb** [comment]
My current solution is something like this
`
import { ApolloClient } from 'apollo-client';
import { setContext } from 'apollo-link-context';
import { createHttpLink } from 'apollo-link-http';
import { ApolloLink } from 'apollo-link';
import { InMemoryCache } from 'apollo-cache-inmemory';
import Session from './async-session';
import { API_VERSION } from './api-version';

const httpLink = createHttpLink();

const authMiddleware = setContext(async req => {
  const token = await Session.getAccessTokenHeaders();
  const id = await Session.currentAccountId();
  return {
    headers: token,
    uri: `/${API_VERSION}/graphql${id ? `?current_account_id=${id}` : ''}`
    )
  };
});

const cache = new InMemoryCache();

const client = new ApolloClient({
  link: ApolloLink.from([authMiddleware, httpLink]),
  cache
});

export default client;
`

but i can`t get it work with one ApolloLink that use un `forward(operation).map` with a another **async** function

**Comment by rosskevin** [comment]
This is not a react-apollo issue, but something configured with apollo-client/apollo-link.
