### ISSUE TITLE
Default values are passed as null

### ISSUE THREAD

**Issue by vickvasquez** [apollographql/react-apollo#1787]
Hello, I have this query with default values

```javascript
 status: gpl`
        query ($inicio: String="", $fin:String="", $tipoServicio: Int=0) {
            seguimientos(inicio: $inicio, fin: $fin, tipoServicio: $tipoServicio) {
                data {
                    vendedor {
                        nombre
                        usuario
                    }
                    cliente {
                        nombre
                        telefono
                    }
                    tipoServicio {
                        nombre
                    }
                    created_at
                    status
                    ubicacion_equipo
                    falla
                }
            }
        }
    `,
```

In my componente i have like this
```javascript
export default graphql(status)(MyComponent)
```

When i running code the variables are sent as null,  I don't know if this is a general issue  or am I doing something wrong?

"react-apollo": "^2.0.4",

**Comment by excitement-engineer** [comment]
Can you provide a reproduction of this issue using codesandbox or some other tool? I tried to reproduce it myself but I didn't manage.

**Comment by vickvasquez** [comment]
Hi, I have created an example in codesandbox, here I leave the link, https://codesandbox.io/embed/zn54v90vkx

When the code is executed,  appId is sent as null
![devtools](https://user-images.githubusercontent.com/5327805/37826850-bcae8506-2e5a-11e8-8100-07c79cc8c9ea.png)

**Comment by sshmyg** [comment]
Any suggestions?

**Comment by ekfn** [comment]
somehow it works fine if you pass empty object on `variables`

```
export default graphql(query, { options: () => ({ variables: {} }) })(Home);
```

**Comment by ShepelievD** [comment]
hey guys, any update? still has the bug `2.5.3`

**Comment by hwillson** [comment]
This reproduction in https://github.com/apollographql/react-apollo/issues/1787#issuecomment-375634479 doesn't seem to show an issue. If anyone here can supply a new reproduction using `react-apollo` >= 2.5.6, we'll take a look. Thanks!
