### ISSUE TITLE
SSR: Query crawler not passing stateless components

### ISSUE THREAD

**Issue by Bram-Zijp** [apollographql/react-apollo#1803]
**Intended outcome:**
Preload data with Server side rendering

**Actual outcome:**
'loading' state on initial page view

**How to reproduce the issue:**

1. Setup server side rendering
2. Give a route (GrandParent) a stateless component (Parent)  with a statefull Graphql decorated(containing a Query) component (Child)

**Version**

* apollo-client@2.2.7
* react-apollo@2.0.4

**Comment by testbuddy** [comment]
I am not sure if i understand u correctly... ;) but u need to rehydrate the client store https://www.apollographql.com/docs/react/features/server-side-rendering.html#store-rehydration after this u shouldnt have loading state in the component

**Comment by fenok** [comment]
Same here

**Comment by hwillson** [comment]
This issue has been resolved in current day versions of `react-apollo`. Thanks!
