### ISSUE TITLE
[Question] Estimated 2.1 official release and docs

### ISSUE THREAD

**Issue by TheGrimSilence** [apollographql/react-apollo#1807]
Not an issue, I just wanted to know if there was a set release date or estimated date for when 2.1 will be released as well as docs being updated?

**Comment by mbj36** [comment]
@TheGrimSilence Next week 2.1 will be released 

Source -  Tweet by @peggyrayzis - https://twitter.com/peggyrayzis/status/975453172662759424

**Comment by peggyrayzis** [comment]
It's here!! 🎉 

https://dev-blog.apollodata.com/introducing-react-apollo-2-1-c837cc23d926
