### ISSUE TITLE
[Discussion] add compiled code to version control

### ISSUE THREAD

**Issue by kandros** [apollographql/react-apollo#1808]
**Intended outcome:**
I would like to install the latest version directly from github url in order to test pull requests and features without using npm link or building the code myself

**Actual outcome:**
currently, the code is compiled before publishing to NPM

**How?:**
This could be enforced with a pre-push hook.

thoughts and feelings about it?

**Comment by rosskevin** [comment]
We will not be putting compiled artifacts in git.
