### ISSUE TITLE
2.1.0-rc.4 is missing Typescript definitions

### ISSUE THREAD

**Issue by patrys** [apollographql/react-apollo#1810]
**Intended outcome:**

Type information being part of the package.

**Actual outcome:**

The package only contains JS files.

**How to reproduce the issue:**

`npm install react-apollo@2.1.0-rc.4`

**Version**

* apollo-client@2.2.7
* react-apollo@2.1.0-rc.4

**Comment by vjpr** [comment]
`index.js` contains `export` keyword. Seems like publish was done with broken transpilation.

**Comment by rosskevin** [comment]
Closing - housekeeping
