### ISSUE TITLE
getDataFromTree queryErrors just references itself

### ISSUE THREAD

**Issue by brandonmp** [apollographql/react-apollo#1812]
**Intended outcome:**
When using `getDataFromTree()`, query errors should be individually accessible

**Actual outcome:**
When a query throws >1 errors, the error messages are swallowed and the resultant error object just circularly references itself, i.e.,  `error.queryErrors === error`

```
{ Error: 2 errors were thrown when executing your GraphQL queries.
    at /mnt/c/Users/brand/code/admitbrain/node_modules/react-apollo/graphql.js:4:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7) queryErrors: [ [Circular] ] }
```

**Version**

* apollo-client@2.2.5
* react-apollo@2.1.0-beta.3

**Comment by anand-sundaram-zocdoc** [comment]
This actually happens specifically in the situation when a wrapped component that makes a GraqphQL query contains at least 2 other wrapped components that make GraqphQL queries further down the tree that both throw errors. This might be useful to know if you're trying to work around the issue.

**Comment by anand-sundaram-zocdoc** [comment]
I think this is fixed in https://github.com/apollographql/react-apollo/pull/1978

**Comment by anand-sundaram-zocdoc** [comment]
After testing locally, it's not completely fixed in https://github.com/apollographql/react-apollo/pull/1978. There's one instance of this which no longer occurs in 2.1.6, but the issue can still happen. 😞

**Comment by hwillson** [comment]
Would someone here be able to put together a small runnable reproduction that shows this happening? Thanks!

**Comment by anand-sundaram-zocdoc** [comment]
@hwillson did you see the new unit test? If you run that unit test on master the last 2 assertions are not satisfied. But if you want I can certainly convert that unit test into an example. (Is there any example repro for another issue I should try to emulate?)

**Comment by hwillson** [comment]
@anand-sundaram-zocdoc Sorry, I missed the PR link completely (not enough ☕️ yet). No need to worry about the repro - I'll review the PR shortly. Thanks!

**Comment by hwillson** [comment]
https://github.com/apollographql/react-apollo/pull/2133 was merged, so this should be resolved in the next `react-apollo` release. Thanks!
