### ISSUE TITLE
Imperatively update store with Query component

### ISSUE THREAD

**Issue by dyst5422** [apollographql/react-apollo#1814]
The new Query component has no way to imperatively update the store. This is necessary for updating lists and I'm not sure why it cannot be an optional prop on the Query component.

**Comment by peggyrayzis** [comment]
`updateQuery` is on the object passed to the render prop function in `Query`: https://www.apollographql.com/docs/react/essentials/queries.html#render-prop

**Comment by dyst5422** [comment]
Thanks. The name change combined with all the type extension made it hard to find in the source (especially since the docs were still catching up)
