### ISSUE TITLE
[React Native] Error after resetStore(): Network error: 400 (undefined)

### ISSUE THREAD

**Issue by joncursi** [apollographql/react-apollo#1818]
**Intended outcome:**

After I run a mutation, I want to reset the entire store and not have the React Native app crash when doing so.

**Actual outcome:**

Every time I do this, the app crashes with the following error:

![simulator screen shot - iphone 7 - 2018-03-21 at 11 38 09](https://user-images.githubusercontent.com/4974609/37719847-615372e8-2cfc-11e8-8249-705c7a5dccc7.png)

**How to reproduce the issue:**

```js
async _runMutation() {
  try {
    await runSomeMutation();
    client.resetStore(); // this line causes the app to crash
  } catch (err) {}
}
```

Every place in my app where I attempt to reset the store after a mutation, this crash happens.

**Version**

* apollo-client@2.2.7
* react-apollo@2.0.4

**Comment by joncursi** [comment]
Even if I wrap the client.resetStore() in it's own try/catch, this still errors out with react native's red screen of death:

```js
async _runMutation() {
  try {
    await runSomeMutation();

    // do other stuff

    try {
      client.resetStore(); // this line causes the app to crash
    } catch (err) {
      console.log(err);
    }

    // do more stuff

  } catch (err) {}
}
```

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
