### ISSUE TITLE
Typescript @graphql directive

### ISSUE THREAD

**Issue by lifeiscontent** [apollographql/react-apollo#1826]
Can someone point me to an example of how to use `graphql` as a directive from react-apollo in typescript?

**Comment by kandros** [comment]
As far as I know decorators in typescript does not support generics, so it should not be possible to use graphql HOC as decorator.

**Comment by lstanden** [comment]
It works fine, but there's some severe limitations, as I'm finding out today.
The GraphQL Test file has the best documentation I've found to date: 
https://github.com/apollographql/react-apollo/blob/master/test/typescript-usage.tsx

The documentation on the official site is flat out wrong and doesn't even compile.
