### ISSUE TITLE
onCompleted and onError callbacks also with graphql HOC.

### ISSUE THREAD

**Issue by johnunclesam** [apollographql/react-apollo#1828]
**Intended outcome:**

Use `onCompleted?: (data: TData) => void;` and `onError?: (error: ApolloError) => void;` also with `graphql()` HOC.

**Actual outcome:**

It doesn't work.

**Version**

* apollo-client@^2.2.7
* react-apollo@^2.1.0

**Comment by dennislaupman** [comment]
Facing the same problem

**Comment by silvestrevivo** [comment]
This works for me:
```
<Mutation mutation={SEND_MUTATION} onError={this.error} onCompleted={this.completed}>
//.....
</Mutation>
```

**Comment by agermanov** [comment]
Work for me:
```
export default graphql(gql`
  mutation ($foo: String!, $bar: String!) {
    ...
  }
`, {
  options: (props) => ({
    onCompleted: props.onCompleted,
    onError: props.onError
  }),
})(MyComponent);
```
Version
- apollo-client@2.3.0
- react-apollo@2.1.3

**Comment by hwillson** [comment]
https://github.com/apollographql/react-apollo/issues/1828#issuecomment-388268767 outlines the way to do this with the HOC. Closing - thanks!

**Comment by raelmiu** [comment]
@hwillson The comment by @agermanov doesn't actually explain how to use it. What's going on here, is props.onCompleted being set in the component? To what?

**Comment by raelmiu** [comment]
I've tried the following:
```
options: (props) => ({
    fetchPolicy: 'cache-and-network',
    onCompleted: true,
    onError: props.onError
  }),
```

Result: Sets onComplete prop on <Query> HOC to true.

```
options: (props) => ({
    fetchPolicy: 'cache-and-network',
    onCompleted: props.onCompleted,
    onError: props.onError
  }),
```

Result: nothing. Nothing added, nothing happens.

**Comment by iujisato** [comment]
@raelmiu I've just started with graphql and apollo, but I think that you can pass the `loading` props to your children components. I don't really know if its the best approach, but I'm sure it'll work.

You can check this behavior on https://www.apollographql.com/docs/react/api/react-apollo.html#graphql-query-data-loading

**Comment by raelmiu** [comment]
Thanks @iujisato ! You're right, it doesn't solve my use case though. I'm trying to scroll to a new piece of data.

**Comment by lucianD** [comment]
Hi @raelmiu ,

I'm not sure if this helps you but here is my use case below, maybe does the trick for somebody else.
You can get the apollo client from props and you can write some data to the cache. This way you can have any component react to that flag that you've just changed using writeData. In my case initialQueryLoaded. Also the data from the query is passed as an argument.

`export default compose(withApollo, graphql(INITIAL_QUERY, {
    options: props => ({
        onCompleted: data => {
            props.client.writeData({ data: { initialQueryLoaded: true, initialQueryData: data } })
        },
        onError: props.onError,
        data: props.data
    })
}))(Header)
`
