### ISSUE TITLE
2.1.0 error on webpack compile

### ISSUE THREAD

**Issue by wroughtec** [apollographql/react-apollo#1829]
**Intended outcome:**
React Apollo builds succesfully

**Actual outcome:**
In the latest React Apollo (2.1.0) I get the following error when compiling with webpack:

```node_modules/react-apollo/index.js:1
(function (exports, require, module, __filename, __dirname) { export * from './browser';
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at eval (webpack-internal:///24:1:18)
error An unexpected error occurred: "Command failed.
```

This occurs when compiling on the server code and was not an issue with RC3, after some experimenting the issues seems to have started from RC4

**How to reproduce the issue:**
I have a SSR react app with the server compiled with webpack with the babel-loader set to node: 8.10.0 (using node 8.10.0). I am guessing it is probably something I will need to change my side, just odd in RC3 (and earlier) had no issues but in the stable version had issues :(

**Version**

* apollo-client@2.2.7
* react-apollo@2.1.0

**Comment by wesbos** [comment]
this is likely because your babel isn't converting to commonjs modules

**Comment by wroughtec** [comment]
its odd as the rest of the server uses es6 `import` & `export` with no issue using babel-loader with:
```
presets: [
  [
    '@babel/preset-env',
    {
       targets: {
          node: '8.10.0'
        },
        loose: true,
        modules: false
     }
   ],
  '@babel/react'
]
```

Have tried various things including using `babel register` & `@babel/plugin-transform-modules-commonjs` etc. It only seems to be an issue on the server side. wondering if its the `export *` that causes the issue but am guessing at the mo lol

**Comment by LawJolla** [comment]
Same issue.  Very frustrating.  No messing with configs has solved this.

**Comment by LawJolla** [comment]
I'm still having issues with this problem and would love some input.

I'm running NextJS.  Here's my .babelrc

```
{
  "presets": [
    "next/babel"
  ],
  "plugins": [
    ["styled-components",
      {
        "ssr": true,
        "displayName": true
      }
    ]
  ]
}
```
I see that @wesbos had:

```
"plugins": [
      [
        "module-resolver",
        {
          "alias": {
            "react-apollo": "react-apollo/react-apollo.browser.umd.js"
          }
        }
      ]
    ]
```
But then later removed it here.  I'm not sure what else changed in the code that he was able to remove it.  Any help is really appreciated!

https://github.com/wesbos/Advanced-React/commit/400a1c3028429d4a0946e29be65b32479eada02a#diff-0a6694dd0d6b93a2aa14f32e3d873b4c

**Comment by wesbos** [comment]
That was a shot at trying to fix something that never worked - not sure how I got around this..

**Comment by Frolanta** [comment]
Had a similar problem today, got the same error only from server side.
The problem was I believe my IDE's auto import feature (or me) who messed up,

I had: `import { graphql } from "react-apollo/index";` In one of my components.
Change to: `import { graphql } from "react-apollo;`

Maybe you did something similar idk, hope it's help.
