### ISSUE TITLE
Possible cache bug in 2.1.0-beta.3 +

### ISSUE THREAD

**Issue by harmon25** [apollographql/react-apollo#1833]
**Intended outcome:**

I have just attempted upgrading to `2.1.0` and am noticing some odd issues.

This is on `2.1.0-beta-2`, everything seems work as intended.
The below screenshot shows 4 discrete projects in the DB, fetched by graphql.

![working-2 1 0-beta 2](https://user-images.githubusercontent.com/6964054/37850640-556ad2ca-2eb2-11e8-9f83-ea9b3c2ed311.png)

**Actual outcome:**

On 2.1.0-beta.3 -> 2.1.0 
The same database content - with newer versions of `react-apollo`, seems to be repeating one project 4 times. Not what I expect...

![broken-2 1 0-beta 3](https://user-images.githubusercontent.com/6964054/37850645-5dc5065c-2eb2-11e8-9f9f-487dde3592ff.png)

I am not getting any errors to help pinpoint what could be causing it, all I know is what is being placed in the DOM is not what I would expect. 

It is likely to do with the following change in 2.1.0-beta.3 
- `Refactored and removed old graphql implementation in favor of new components`

If 2.1.0 is backward compatible, I would expect it to work as it did previously.

**How to reproduce the issue:**

Not sure how to reproduce this...I have a pretty big app, with a lot of queries and mutations.
I am not leveraging the new render prop pattern,  everything is still using the `graphql` HOC.

Has anyone else noticed something like this?

**Version**

* apollo-client@2.1.0-beta.3 -> 2.1.0
* react-apollo@2.2.7

Thanks!

**Comment by rosskevin** [comment]
I'm not seeing actionable information here though I have no doubt what you are seeing.  We have a more refined set of open issues, hopefully you can spot something relevant now and join in on one of those.  If you can reproduce with the codesandbox example or sample repo, please ping me and I'll reopen.
