### ISSUE TITLE
Cannot access result from mutation hoc

### ISSUE THREAD

**Issue by doniyor2109** [apollographql/react-apollo#1842]
I have used ```mutation-hoc``` for RN Component. I can access ```mutation``` function however I cannot access the ```_result``` from mutation.

https://github.com/apollographql/react-apollo/blob/8d06f4f84f1209b8ba661f1bc933b09f50b61c9c/src/mutation-hoc.tsx#L61

**Comment by doniyor2109** [comment]
Here is PR for this issue #1843

**Comment by doniyor2109** [comment]
Here is PR #1844

**Comment by fenok** [comment]
I need this badly. However, I don't think that #1844 does this right. What if there are multiple mutations in HOCs chain? I believe the right way is:
`let childProps = { [name]: Object.assign(mutate, _result) };`
It's 100% backward-compatible and allows accessing each mutation's state individually.

**Comment by doniyor2109** [comment]
Maybe temporary workaround is to use old `graphql`

**Comment by fenok** [comment]
Could you explain that a bit further? What do you mean by “old graphql”? Currently graphql uses mutation-hoc internally.

**Comment by doniyor2109** [comment]
Sorry for mixing, I mean currently `graphql`

**Comment by fenok** [comment]
I still don't get it, because 

> Currently graphql uses mutation-hoc internally.

Can you provide an example?

**Comment by doniyor2109** [comment]
It is possible to get `loading` and `error` states with the help of some additional hocs. There is some solution in #421

**Comment by doniyor2109** [comment]
I opened new PR which only adds new prop called `mutationResult` #1881

**Comment by fenok** [comment]
> It is possible to get loading and error states with the help of some additional hocs. There is some solution in #421

I'm aware of it, but I want this functionality included in react-apollo itself.

> I opened new PR which only adds new prop called mutationResult #1881

Again, this will fail if component is wrapped by several `mutation-hoc`s. You could at least use ``${name}Result: _result``. But I'm still convinced that it should be done like `let childProps = { [name]: Object.assign(mutate, _result) };`.

**Comment by doniyor2109** [comment]
Yes you are right. It overrides when there are multiple hocs. You should also create PR for your solution. That could be the right solution.

**Comment by brendanmoore** [comment]
I am a little bit baffled as to why `_result` is not passed to the child with the `mutation-hoc` I cannot find any documentation explaining the decision. If somebody "in the know" could share, that would be great.

**Comment by ekfn** [comment]
Is there any good workarounds?

**Comment by rosskevin** [comment]
Explanation:
https://github.com/apollographql/react-apollo/pull/1844#issuecomment-376191081

> jbaxleyiii commented on Mar 26
> @doniyor2109 this is actually intentional to keep backwards compat 100%. I'm curious why you wouldn't use the Mutation component instead?

FYI - In-house, we don't use the Mutation component or hoc, we just `mutate` directly on the `client`.

Given this explanation from a core maintainer, I'm going to close this in an effort to keep the tracker focused on actionable issues.  I suspect a `hooks` implementation in 2019 will make us think about our patterns of use and perhaps transition us to something simpler yet to use.
