### ISSUE TITLE
errorPolicy should be settable on MutationOptions

### ISSUE THREAD

**Issue by testbuddy** [apollographql/react-apollo#1847]
**Intended outcome:**

on Query Component and on Mutation Component i can set errorPolicy

**Actual outcome:**

i can only set errorPolicy on query, but cant do it on the new Mutation Components
is there a reason why someone cant do this anymore ? i find out u can still set it in the options maybe someone should update the docs

**How to reproduce the issue:**

**Version**

* apollo-client@<2.2.7>
* react-apollo@<2.1.0-beta.3>

/label question

**Comment by Elijen** [comment]
For me the option is ignored :(

**Comment by rosskevin** [comment]
`MutationOptions` does not currently extend it's counterpart from apollo-client `mutate` and it should, which would allow passing of `errorPolicy` as defined by apollo-client `MutationBaseOptions`

**Comment by willisplummer** [comment]
I'm running into this bug too. It was a source of much confusion.

**Comment by callmenick** [comment]
@rosskevin any update on the priority of this bug? Will it be addressed, or should we work around? Thanks :)

**Comment by mmanela-test** [comment]
I am glad this issue exists, just searched for a while trying to figure out why errorPolicy wasn't exposed.

**Comment by mmanela** [comment]
Just hit this same issue. I am thankful someone already filed this. It would be good to expose this errorPolicy on the Mutation component or at least at the Link config level

**Comment by Anahkiasen** [comment]
Would really love this as well

**Comment by danleydmello** [comment]
I am using "react-apollo": "^2.5.8", and still don't see errorPolicy option in Mutation,d,ts

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
