### ISSUE TITLE
Should it throw an Error/Warning when the store contains data with missing fields ?

### ISSUE THREAD

**Issue by eltonio450** [apollographql/react-apollo#1850]
Hello everyone :),

I am using the AWS Appsync client, but I think this comes from react-apollo, hence I post the issue here,

**Intended outcome:**

An error should be raised or the component should stay connected to the apollo store

**Actual outcome:**

The component is disconnected from the store if a mutation does not contain all the required fields.

**How to reproduce the issue:**

I have a query, a mutation and a corresponding (optimistic) response. My query is general, and has more fields than returned by the server (a bit complicated to use fragments in appsync at the moment, that's why I use nullable fields)

```
const imagesList = gql
    query imagesList ($uploadBatch: String!, $nextToken: String){
        imagesList(uploadBatch: $uploadBatch, limit: 5, nextToken: $nextToken){
            items {
                id
                name
                deleted
                infos {
                    image
                    id
                    image_hash
                    author
                    owner
                    source
                    type
                    deleted
                    value
                    group
                    x
                    y
                    height
                    width
                    __typename
                }
            }
            nextToken
        }
};
```

Mu mutation looks like:

```
const addInfo = gql
    mutation addInfo($input: InfoInput!) {
        addInfo(input: $input){
            image
            id
            image_hash
            author
            owner
            source
            type
            deleted
            __typename
            value
            group
            x
            y
            height
            width
        }
    };
```

I have a component linked to this query via an HOC: 

```
graphql(imagesList, {
    options: (props) => {
      return ({
        fetchPolicy: 'cache-and-network',
        variables: {
          uploadBatch: props.dataset || 'default',
        },
      });
    },
    props: (props) => {
      return ({
        imagesList: (props.data.imagesList && props.data.imagesList.items) || [],
      });
    }
```
The server always provides 'null' if the fields are empty

but if I provide an optimistic reponse, let's say:

```
    props: props => ({
      addInfo: input => props.mutate({
        variables: { input },
        optimisticResponse: {
          __typname: 'Mutation',
          addInfo: {
            ...input,
            author: 'unknown',
            // group: null, (disabled for the exmple here !)
            id: 'temporary', // A temporary id. The server decides the real id.
            owner: 'empty',
            deleted: false,
          },
        },

      }),
    }),
```
and this optimisticReponse has missing fields, the React component gets 'disconnected'. I mean disconnected because:
- the Apollo store works as expected (the item with key 'temporary' is added at the right place)
- the imagesList props is set to [], as if the HOC was not aware of the store

The situation persists until the actual update arrives from the server (with all the fields). The optimistic reponse is correctly replaced.

** Note **

I am not really sure of the expected behaviour. The missing fields are nullable

However, my store contains a list of info, some of them with all the fields, some of them with missing fields. It seems that if the HOC refuses to pass the list to the children component, it could raise a warning (writeQuery raises a warning but performs the store update), or better, an error.

EDIT: furthermore, the error props is set to undefined, even if the component gets disconnected.

Let me know if I missed something,

Thanks,

**Version**
-     "apollo-client": "^2.2.6",
-     "react-apollo": "^2.0.4",

**Comment by takticcode** [comment]
Did you solve that one?

**Comment by eltonio450** [comment]
I think there were two issues here: one with optimistic responses: null should be added for undefined fields IMO. This one is not solved I guess

The second one is the question of the cache break if a mutation does not contain enough fields. This is adressed in the Apollo Client 3 roadmap (https://github.com/apollographql/apollo-feature-requests/issues/33, check 4)
