### ISSUE TITLE
"SyntaxError: Unexpected token import" error when importing in create-react-app test

### ISSUE THREAD

**Issue by excitement-engineer** [apollographql/react-apollo#1852]
I get the error:

```
import * as React from 'react';
    ^^^^^^

    SyntaxError: Unexpected token import
```

When running tests in create-react-app.

I think the solution is to compile the source code down to CommonJs so it will work with this tool.

**Comment by zamiang** [comment]
Believe this is related to https://github.com/apollographql/react-apollo/issues/1829

**Comment by lucasconstantino** [comment]
I've basically cloned the repo, built react-apollo myself, and added the resulting lib directory inside my app for test only purposes. Quite lame.

**Comment by excitement-engineer** [comment]
A fix is on its way! See #1855. Will be released soon:)

**Comment by excitement-engineer** [comment]
It is merged and will be included in the next release

**Comment by hiramhibbard** [comment]
Is there a workaround until the next release?

**Comment by lucasconstantino** [comment]
Mine is sad, but works.
