### ISSUE TITLE
get context.store.get is not a function when using IntrospectionFragmentMatcher

### ISSUE THREAD

**Issue by nguyenviethoa** [apollographql/react-apollo#1860]
Hi,
   
    I got this error (in the picture attached) 

![preview-chat-screen shot 2018-03-28 at 5 28 02 pm](https://user-images.githubusercontent.com/3621738/38026550-ae0f06b4-32b6-11e8-990d-4010bc705fcd.png)

The code that i use for apolloclient : 

import { ApolloClient } from 'react-apollo';
import networkInterface from '../NetworkInterface';
import { IntrospectionFragmentMatcher, InMemoryCache } from 'apollo-cache-inmemory';

const PARTIAL_SCHEMA = {
  __schema: {
    "types":[
      {
        "kind":"INTERFACE",
      
        "name":"FeedItemInterface",
        "possibleTypes":[
          {"name":"FeedItemActivity"},
          {"name":"FeedItemAggregated"},
          {"name":"FeedItemClubNews"},
          {"name":"FeedItemFines"},
          {"name":"FeedItemForumPost"},
          {"name":"FeedItemLinkCreated"},
          {"name":"FeedItemMessage"},
          {"name":"FeedItemMomWinner"},
          {"name":"FeedItemNote"},
          {"name":"FeedItemPicturesUploaded"},
          {"name":"FeedItemTeamNews"},
          {"name":"FeedItemVideoShared"},
          {"name":"FeedItemVote"}
        ]
      },
      {
        "kind":"INTERFACE",
        "name":"NewsInterface",
        "possibleTypes":[
          {"name":"ClubNews"},
          {"name":"TeamNews"}
        ]
      }
    ]
  }
};

const fragmentMatcher = new IntrospectionFragmentMatcher({
  introspectionQueryResultData: PARTIAL_SCHEMA
});

const Client = new ApolloClient({
  networkInterface,
  reduxRootSelector: state => state.differentKey,
  dataIdFromObject: object => mapObjectId(object),
  fragmentMatcher
});

const mapObjectId = (object) => {
  return object.id;
};

export default Client;

please help,
 
many thanks,

**Intended outcome:**

**Actual outcome:**

**How to reproduce the issue:**

**Version**

* apollo-client@<version number>
* react-apollo@"react-apollo": "^1.4.15"

**Comment by nguyenviethoa** [comment]
I found the problem: i used the wrong version of IntrospectionFragmentMatcher, use the IntrospectionFragmentMatcher from react-apollo resolve problem.

Thanks

**Comment by rosskevin** [comment]
Closing - housekeeping

Please close your own issues when solved.
