### ISSUE TITLE
Apollo 2, useless re-rendering also with react-apollo 2.1.1 fix.

### ISSUE THREAD

**Issue by ghost** [apollographql/react-apollo#1861]
**How to reproduce the issue:**

Also after react-apollo 2.1.1 I have useless re-rendering. Codesandbox: **https://codesandbox.io/s/kmork0rxkv**

I added `why-did-you-update` and there is still some problem:

![image](https://user-images.githubusercontent.com/21275217/38036761-bcb8380c-32a7-11e8-9bb2-fda7683077ae.png)

![image](https://user-images.githubusercontent.com/21275217/38036783-c93a49ee-32a7-11e8-9fd6-099949bbf438.png)

**Version**

* apollo-client@^2.2.8
* react-apollo@^2.1.1

**Comment by rosskevin** [comment]
Closing - housekeeping
