### ISSUE TITLE
Mutation client prop support

### ISSUE THREAD

**Issue by pyromaniac** [apollographql/react-apollo#1863]
Hello, thanks for this awesome client first of all!

We considering to upgrade to 2.1 and we really like newly implemented components, however, during the code review we've noticed that Mutation component doesn't support client passed as props (https://github.com/apollographql/react-apollo/blob/master/src/Mutation.tsx#L117) unlike Query (https://github.com/apollographql/react-apollo/blob/master/src/Query.tsx#L163)

Maybe I'm missing something. Do you have any plans to add client prop support there?
Thanks in advance!

**Comment by pyromaniac** [comment]
Never mind, just figured out how to have multiple endpoints with a single client.

**Comment by victorgb6** [comment]
Hi @pyromaniac  I have landed here looking for information on how to have multiple endpoints with a single client, could you say how you achieve this?
Thanks!

**Comment by pyromaniac** [comment]
sure

```
new ApolloClient({
    link: ApolloLink.from([
      errorLink(),
      ApolloLink.split(
        ({ getContext }) => (getContext().endpoint === 'first'),
        httpLink('/graphql/first'),
        httpLink('/graphql/second')
      )
   ])
})
```

And then in the HOC:
```
mutate({
  context: { endpoint: 'first' },
  variables: { ...variables }
})
```
