### ISSUE TITLE
Loading true when skipped

### ISSUE THREAD

**Issue by lucasconstantino** [apollographql/react-apollo#1869]
**Intended outcome:**
When I configure a query to be skiped, I expect the injected `loading` prop not to be `true` for the data is not acctually being loaded.

**Actual outcome:**
The injected `loading` prop is set to `true` when the query is skipped.

**How to reproduce the issue:**
```js
const Comp = () => (
  <Query query={ query } skip>
    { ({ loading }) => loading ? 'Loading!' : 'Not loading!' }
  </Query>
)
```

**Version**

* apollo-client@^2.2.5
* react-apollo@2.1.0

**Issue Labels**

- [x] has-reproduction
- [ ] feature
- [ ] docs
- [ ] blocking
- [ ] good first issue

**Comment by ZwaarContrast** [comment]
Running into the same issue with:

- react-apollo@2.1.2
- apollo-client@2.2.1

**Comment by AdrianZielonka** [comment]
Running into the same issue with:

react-apollo@2.1.3
apollo-boost@0.1.4 (apollo-client@2.2.8)

**Comment by AdrianZielonka** [comment]
Still an issue with:

react-apollo@2.1.4
apollo-boost@0.1.6 (apollo-client@2.3.1)

**Comment by lucasconstantino** [comment]
@jbaxleyiii any opinion on this?

**Comment by FranciscoGileno** [comment]
Running into the same issue here.

react-apollo@2.1.4

We managed to workaround this relying on networkStatus too. Not sure if it works for everyone.

```
const Comp = () => (
  <Query query={ query } skip>
    { ({ loading, networkStatus }) => loading && networkStatus !== 1 ? 'Loading!' : 'Not loading!' }
  </Query>
)
```

Gotcha: The first time the query loads, networkStatus === 1, so the loading does not show.

Any suggestions?

**Comment by andreylh** [comment]
Running into the same issue here.

react-apollo@2.1.9
apollo-boost@0.1.10 (apollo-client@2.3.5)

**Comment by veryscarycary** [comment]
Still an issue.

react-apollo@2.1.8,
apollo-boost@0.1.10
apollo-client@2.3.5

**Comment by andrewtpoe** [comment]
I'm running into the same issue. 

react-apollo@2.1.9
apollo-client@2.3.7

Can provide any other details as needed.

**Comment by zapo** [comment]
We workaround it by using our own Query wrapper as suggested in #1909 

```
import { Query as WrappedQuery, OperationVariables, QueryProps, QueryResult } from 'react-apollo';

function Query<TData = any, TVariables = OperationVariables>(props: QueryProps<TData, TVariables>)
: JSX.Element {
  const children = (result: QueryResult<TData, TVariables>) => (
    props.children({ ...result, loading: result.loading && !props.skip })
  );
  return <WrappedQuery { ...props } children={ children }/>;
}

export { Query };
```
