### ISSUE TITLE
react-apollo@2.1.1 graphql() componentWillReceiveProps called with strange this.props (causing shallowEqual() to always fail)

### ISSUE THREAD

**Issue by tnrich** [apollographql/react-apollo#1870]
**Intended outcome:**
I would expect the shallowEqual comparison in componentWillReceiveProps method added by wrapping a component with graphql() to be getting called with the props getting passed to the component. IE if foo=true is passed as a prop you would see this: 
![image](https://user-images.githubusercontent.com/2730609/38109501-2db0bd2c-334d-11e8-9687-25b19b4f9e94.png)

**Actual outcome:**

Here you can see componentWillReceiveProps getting called with props that are not explicitly passed to the component and which will always fail the shallowEqual()!

![image](https://user-images.githubusercontent.com/2730609/38108950-4ce07f22-334b-11e8-80ad-3826f4fcde0b.png)

https://github.com/apollographql/react-apollo/blob/b1e346c7b8de1187f736a437888b4206c224fda8/src/graphql.tsx#L179

This seems not to be the case when just a few minor versions lower at react-apollo@2.0.4. 

**How to reproduce the issue:**

Go to this codesandbox and add a breakpoint like seen above in react-apollo.browser.umd.js and see that the props it is being called with are strange: 
https://codesandbox.io/s/0plj6mx3j0

You can go to a previous version of this codesandbox ( https://codesandbox.io/s/4q0645k8w ) that is using react-apollo@2.0.4 and see that this is not the case: 
![image](https://user-images.githubusercontent.com/2730609/38109436-f74ba062-334c-11e8-93c1-e9684e018230.png)

**Version**

* apollo-client@2.2.8
* react-apollo@2.1.1

**Comment by tgreen7** [comment]
I am seeing an issue where a query seems to be refetching unnecessarily which I think is caused by this.

**Comment by tnrich** [comment]
bump as this is still happening and is almost certainly a bug

**Comment by hwillson** [comment]
A lot has changed since this issue was reported. If this is still happening with a current day version of `react-apollo`, definitely let us know. Thanks!
