### ISSUE TITLE
Component created with graphql() does not update query variables when props change

### ISSUE THREAD

**Issue by tuananhtd** [apollographql/react-apollo#1873]
**Intended outcome:**

When create react component using `GraphQLComponent = graphql(query, options)(MyComponent)` it is expected that we can pass query variable via `GraphQLComponent`'s props and but I found a bug that when that props change the graphql query isn't got updated. You can take a look at the `Query` component in the picture below.

![inspected](https://user-images.githubusercontent.com/14288059/38142838-2a4323e8-3468-11e8-9dfa-1caf6e59cdaa.gif)

**Actual outcome:**
The graphql query isn't updated according to the props change.

**How to reproduce the issue:**
I created a repo to reproduce a code [here](https://github.com/tuananhtd/apollo-react-bug-reproduce).

**Version**

* apollo-client@<2.1.0>
* react-apollo@<1.3.4>

I believe [this line](https://github.com/apollographql/react-apollo/blob/master/src/query-hoc.tsx#L57) cause the bug. It eventually sets `operationOptions.options.variables` and cause the subsequence render thing that we already pass the variables from the beginning. Because of this we have to pass a non empty option to the graphql function to reproduce the issue. In my case I used this:
```
const BookGraphQLComponent = graphql(QUERY, {options: {pollInterval: 10 * 1000}})(Book);

```

**Comment by doomsower** [comment]
I'm also facing this bug. This works:
```ts
graphql(query, { options: () => ({ fetchPolicy: 'network-only' }), alias: `${formName}FormQuery` }),
```

However, this return stale date with previous variables:

```ts
graphql(query, { options: { fetchPolicy: 'network-only' }, alias: `${formName}FormQuery` }),
```

Something is wrong with `mapPropsToOptions`, on this screenshot it totally ignores sourceId from props and uses old sourceId value:
![image](https://user-images.githubusercontent.com/12031673/38468533-21380798-3b50-11e8-9d41-d3b1e4722542.png)

**Comment by hyperborea** [comment]
Facing the same issue, wrapping options in function as suggested by @doomsower works.
