### ISSUE TITLE
React does not recognize the `tReady` prop on a DOM element

### ISSUE THREAD

**Issue by Cedcn** [apollographql/react-apollo#1887]
Hi! Do you have any ideas why this warning appears?

"react": "^16.3.0",
"react-apollo": "^2.1.1"

<img width="900" alt="wx20180403-111110 2x" src="https://user-images.githubusercontent.com/11457566/38227235-e3fc10dc-372f-11e8-9192-f5efeea3f952.png">

**Comment by mnemanja** [comment]
Could you please provide the reason for closing? How did you resolve your issue? Thanks!

**Comment by Cedcn** [comment]
You can refer to https://github.com/i18next/react-i18next/issues/407

**Comment by mnemanja** [comment]
Thanks!
