### ISSUE TITLE
2.1.x changelog and git tags

### ISSUE THREAD

**Issue by astorije** [apollographql/react-apollo#1893]
Hi there!

https://www.npmjs.com/package/react-apollo?activeTab=versions mentions v2.1.2 was released a couple days ago. I've noticed [the changelog](https://github.com/apollographql/react-apollo/blob/master/Changelog.md) is not fully up-to-date. Is #1882 part of v2.1.2?

Additionally, would you mind pushing git [tags](https://github.com/apollographql/react-apollo/tags) and maybe [releases](https://github.com/apollographql/react-apollo/releases) for versions you publish on npm? It would make it easier to track changes/diff (I also think tools like @greenkeeperio-bot and https://david-dm.org/ use those to reconcile changes across versions).

Thanks!

**Comment by astorije** [comment]
Bump! 👋

With v2.1.3 released and the release notes / changelog still not showing v2.1.2, I believe there is effectively no way to get a list of changes, except by manually comparing release dates and PR merge dates and listing what goes where.
That's a very easy way to miss something unfortunately :(

I'd be happy to be wrong, is there another easy way to easily access this until the Apollo team publishes release notes?
I have confirmed https://david-dm.org is unable to list changes, but have not found a Greenkeeper PR yet, has anyone seen one we could confirm is unable to list changes?

**Comment by Dremora** [comment]
I'm not even sure released package has corresponding code in this repository. The version in `package.json` still says `2.1.0`.

**Comment by astorije** [comment]
Nice! It would still be nice to rely on git tags / GitHub releases though, so tools like David, Greenkeeper, etc. can use this to diff changes. Also to be able to use GitHub's compare view, such as https://github.com/apollographql/react-apollo/compare/v1.4.3...v1.4.4 for example.
