### ISSUE TITLE
Excited about asyncMode - trying to kick the tires a bit

### ISSUE THREAD

**Issue by onpaws** [apollographql/react-apollo#1912]
This is about `3.0.alpha.0` -- I realize it says alpha for a reason :)
I'm just another React developer super excited to kick the async tires. So if you have more important fish to fry, please consider this low pri.

Thanks @jbaxleyiii for your awesome work here. Very excited about async in 2018! 

I started by reading the [PR](https://github.com/apollographql/react-apollo/pull/1742#issue-172291547) and decided to give it a try.

**Intended outcome:**
`<Query asyncMode>` should work.

**Actual outcome:**
`<Query>`'s `getQueryResult()` throws `this.state.queryObservable.result()` and I'm not sure what to do about it.
![image](https://user-images.githubusercontent.com/182515/38454375-85f4fdde-3a66-11e8-8dec-e00c8c7aafca.png)

**How to reproduce the issue:**

Tiny repro [sandbox](https://codesandbox.io/s/9lv3prpv64).
Apologies if I'm missing something obvious, I may well be a little rusty on my Apollo understanding.

I suspect I need to learn more about queryObservable.  
Here's the relevant area:
```
if (loading) {
  if (this.props.asyncMode) {
    throw this.state.queryObservable.result();
  }
  Object.assign(data.data, this.previousData, currentResult.data);
}
```

Any tips would be appreciated :)

Bonus: on a whim I tried wrapping the `<App>` component with React 16.3's new `<React.unstable_AsyncMode>` but no difference.

**Version**

* apollo-boost@0.1.4
* react-apollo@3.0.0-alpha.0
* react@16.3.1

**Comment by onpaws** [comment]
Thanks for this handy [write up](https://dev-blog.apollodata.com/a-first-look-at-async-react-apollo-10a82907b48e) @peggyrayzis, it's helping demystify things.
Read a bit more over the weekend and learned throwing a Promise is actually how async React works. 
Sure, why not, another round of [rethinking best practices](https://www.youtube.com/watch?v=x7cQ3mrcKaY)! :)

As Peggy aptly explained:
> If we’re in async mode and we’re loading, which means the request isn’t found in Apollo’s cache, we throw the promise that will eventually resolve to the result of our query.

So if I'm understanding things correctly here, it seems like my `<Query>` component is powered by a `queryObservable` object that fired a Promise. 
The Promise was supposed to resolve to the result of the query, but it isn't. Why? 🤔

**Comment by onpaws** [comment]
I tried wrapping the `<Query>` with `<React.unstable_asyncMode>` on my little [repro](https://codesandbox.io/s/9lv3prpv64), no change. Feels a bit like I'm missing something obvious 🙈

**Comment by onpaws** [comment]
I made a bit of [forward motion](https://github.com/apollographql/apollo-react-async-demo/blob/master/package.json#L13) matching the React versions to Peggy's demo.

Now studying `<AsyncValue>`...

**Comment by onpaws** [comment]
Success! 🍾 

TL, DR:
• Update react & react-dom to `v16.4.0-alpha.0911da3`
• Use `ReactDOM.unstable_deferredUpdates()`. In my case I wrapped regular `render()` on index.js:
```
ReactDOM.unstable_deferredUpdates(() => {
  ReactDOM.render(<App />, document.getElementById('root'));
})
```
Now seeing what look like fibers in action:
![image](https://user-images.githubusercontent.com/182515/38555487-903c2832-3cc6-11e8-861f-3c1a68d614ba.png)

**Comment by onpaws** [comment]
Still have some learning to do here.
I'm curious why the [Apollo demo](https://github.com/apollographql/apollo-react-async-demo/blob/master/src/AsyncValue.js#L10) calls `unstable_deferredUpdates()` strictly from the `<AsyncValue`> component.
```
deferSetState(state) {
  ReactDOM.unstable_deferredUpdates(() => {
    this.setState(state);
  });
}
```
What are the tradeoffs when wrapping my whole app with deferred updates vs just one component's `setState()`? 

Also curious what exactly `<AsyncMode>` does? 
It didn't seem to make a difference when I wrapped my `<App>` or not.

Still more to learn here but glad to be past the error.

**Comment by onpaws** [comment]
deferredUpdates is [apparently](https://github.com/koba04/react-fiber-resources#1-use-reactdomunstable_deferredupdates) a synonym for "Low Priority"

So wrapping `<App /`> would keep all components async by default, with, I think, a [synchronous](https://github.com/koba04/react-fiber-resources#2-use-reactunstable_asyncmode) option individual components could invoke that I assume means "High Priority"?

**Comment by onpaws** [comment]
Eager to continue testing this out.

Yarn tells me the 3.0 alpha was released March 1.
`'3.0.0-alpha.0': '2018-03-01T08:06:04.069Z',

Sorry to pester -- curious is there a timeline for updates on 3.0?

**Comment by onpaws** [comment]
For those of you curious, I just saw that this has been made available:
https://github.com/apollographql/react-apollo/tree/3.0-alpha-2

**Comment by onpaws** [comment]
Have there been any new async releases?
Don't see any new 3.0 tags...curious where this is at these days

**Comment by hwillson** [comment]
The version 3 alpha this issue was associated with did not see the light of day. We're working on a new RA 3 version (which will be launching soon), but it won't include React's Suspense + Data loading functionality (it isn't quite ready for prime time yet). When the React team says it's ready, we'll get it in place. Thanks!

**Comment by Levino** [comment]
I think it is ready now, is it not?
