### ISSUE TITLE
typescript error while adapting the hackernews-react-apollo tutorial to typescript 

### ISSUE THREAD

**Issue by divramod** [apollographql/react-apollo#1918]
i also posted this issue on stackoverflow: https://stackoverflow.com/questions/49750875/typescript-error-2345-while-using-react-apollo-and-graphql

i am starting using react-apollo with Typescript. For that i am trying to adapt the react-apollo-hackernews example from here:

- tutorial: https://www.howtographql.com/react-apollo/1-getting-started/
- code: https://github.com/howtographql/react-apollo

In the Link.tsx file I added an interface for the react props but now i am getting an error i am not sure what to do with:

    (87,4): Argument of type 'typeof Link' is not assignable to parameter of type 'ComponentType<Partial<DataProps<{}, {}>> & Partial<MutateProps<{}, {}>>>'.
      Type 'typeof Link' is not assignable to type 'StatelessComponent<Partial<DataProps<{}, {}>> & Partial<MutateProps<{}, {}>>>'.
        Type 'typeof Link' provides no match for the signature '(props: Partial<DataProps<{}, {}>> & Partial<MutateProps<{}, {}>> & { children?: ReactNode; }, context?: any): ReactElement<any> | null'.

The error is in the last line. Can someone help me with that?

    import * as React from 'react'
    import { Component } from 'react'
    import { AUTH_TOKEN } from '../constants'
    import { timeDifferenceForDate } from '../utils'
    import { graphql } from 'react-apollo'
    import gql from 'graphql-tag'
    
    interface MyProps {
        index: number;
        link: {
            description: string;
            url: string;
            votes: number[];
            postedBy: any;
            createdAt: any;
            id: any;
    
        };
        voteMutation: Function;
        updateStoreAfterVote: Function;
    }
    
    class Link extends Component<any, any> {
      props: MyProps
      render() {
        const authToken = localStorage.getItem(AUTH_TOKEN)
        return (
          <div className="flex mt2 items-start">
            <div className="flex items-center">
              <span className="gray">{this.props.index + 1}.</span>
              {authToken && (
                <div className="ml1 gray f11" onClick={() => this._voteForLink()}>
                  ▲
                </div>
              )}
            </div>
            <div className="ml1">
              <div>
                {this.props.link.description} ({this.props.link.url})
              </div>
              <div className="f6 lh-copy gray">
                {this.props.link.votes.length} votes | by{' '}
                {this.props.link.postedBy
                  ? this.props.link.postedBy.name
                  : 'Unknown'}{' '}
                {timeDifferenceForDate(this.props.link.createdAt)}
              </div>
            </div>
          </div>
        )
      }
    
      _voteForLink = async () => {
        const linkId = this.props.link.id
        await this.props.voteMutation({
          variables: {
            linkId,
          },
          update: (store, { data: { vote } }) => {
            this.props.updateStoreAfterVote(store, vote, linkId)
          },
        })
      }
    }
    
    const VOTE_MUTATION = gql`
      mutation VoteMutation($linkId: ID!) {
        vote(linkId: $linkId) {
          id
          link {
            votes {
              id
              user {
                id
              }
            }
          }
          user {
            id
          }
        }
      }
    `
    
    export default graphql(VOTE_MUTATION, {
      name: 'voteMutation',
    })(Link)

**Comment by jackh726** [comment]
I'm not 100% sure this is it, but you class definition line should be `class Link extends Component<MyProps, any> {` and you shouldn't define `props: MyProps` below that.

**Comment by rosskevin** [comment]
Closing - housekeeping
