### ISSUE TITLE
Watch store changes on writeFragment()

### ISSUE THREAD

**Issue by sebastian-schlecht** [apollographql/react-apollo#1933]
Hey,

 most likely this is not the best place to ask this but I‘m happy for any pointers. 

We‘re building an offline-capable app using apollo-react and react-native. Our approach would be to sync multiple projects using large queries and then we‘d like to simply query the store to display the data. Now my question is: what‘s the best way to query the client side store/cache directly? More so, what‘s the best way to update the store locally (also execute a server side mutation if a connection is available) in a way that  components update automatically? I considered readFragment()/writeFragment() but it does not allow to watch for changes. 

I‘m glad for any hints!

**Comment by rosskevin** [comment]
You are asking about apollo-client apis, but I'll tell you that you need to act like the code here, e.g. use watchQuery to observe changes to the cache. Those changes can be introduced by both writeQuery and writeData.
