### ISSUE TITLE
Support React.createContext

### ISSUE THREAD

**Issue by neoziro** [apollographql/react-apollo#1937]
I am the creator of [Loadable Components](https://github.com/smooth-code/loadable-components/). I would like to thank you for this awesome library. I inspired from your code, especially the [getDataFromTree](https://github.com/apollographql/react-apollo/blob/master/src/getDataFromTree.ts).

I found that React.createContext is not supported. I patched it in https://github.com/smooth-code/loadable-components/pull/65. You can take the patch, it works.

But I think it would be nice to create a separated package to walk a tree in React, a lot of other libraries rely on it.

**Comment by neoziro** [comment]
Follow up https://github.com/facebook/react/issues/12640

**Comment by andiwinata** [comment]
I think it is in [this PR](https://github.com/apollographql/react-apollo/pull/1742/files#diff-f8938b597e7a7647b9ea5589d55d3a26)

**Comment by hamlim** [comment]
Are there any plans to release a 2.x minor that includes support for createContext?

**Comment by hamlim** [comment]
We also forked the getDataFromTree utility at my company in order to implement createContext support, would you all be interested in adding that to a 2.x release if I opened a PR with those changes?

**Comment by hamlim** [comment]
Sure: https://gist.github.com/hamlim/58aec71b7d91871ee0d001621a4969e8

The createContext related changes happen around line 100

**Comment by piglovesyou** [comment]
I would definitely like this support. Without this, server-side rendering with `<Query>` under `<Context.Consumer>` fails because `function walkTree` cannot get a child of it.

**Comment by Dremora** [comment]
@piglovesyou it's been resolved, see #1978.

**Comment by piglovesyou** [comment]
@Dremora Ah.. it's just great... it's on [2.1.6](https://github.com/apollographql/react-apollo/blob/master/Changelog.md#216-june-19-2018). Thanks for letting me know.
