### ISSUE TITLE
Useless re-render component with `graphql(MYQUERY)(Navbar)` everytime.

### ISSUE THREAD

**Issue by ghost** [apollographql/react-apollo#1938]
**Intended outcome:**

Do not re-render simply component in `App` with `graphql(MYQUERY)(Navbar)` everytime when I change route because I already have query results in cache.

**Actual outcome:**

It re-renders my `Navbar` component useless. It doesn't need re-render because `graphql(MYQUERY)` already in cache.

**How to reproduce the issue:**

Simply go here: https://codesandbox.io/s/zqk59nkmk4 and click "Home" and "Players". In console you will see "Navbar this.props e nextProps different" every time you change route.

![image](https://user-images.githubusercontent.com/21275217/38943117-e2f80f62-4330-11e8-88a1-6fd3b8aed667.png)

**Version**

* apollo-client@2.2.8
* react-apollo@2.1.3

@jbaxleyiii, maybe the same as: https://github.com/apollographql/react-apollo/issues/1777 ?

@tnrich, maybe the same as: https://github.com/apollographql/react-apollo/issues/1870 ?

**Comment by johnunclesam** [comment]
Here there is the same problem with `Query` component and without `graphql` HOC.

**Comment by quentin-** [comment]
I believe this is `react-router` rerending your `Navbar`. 
You can try for yourself by removing all graphql related code in your example.

**Comment by loonywizard** [comment]
Having the same Issue, Query rerenders when changing route in React Router

**Comment by casperle** [comment]
Hi guys, is there any plan to fix this issue?

**Comment by adorum** [comment]
Same here. I'am afraid rerender happening because `graphql` HOC produce each time new instance of query object into props even if data are same.

My workaround with recompose:
```
...
graphql(MYQUERY)
branch(({ data }) => data.loading, renderComponent(LoadingComponent)),
lifecycle({
  shouldComponentUpdate(nextProps) {
     //compare query response data from current and next props
  }
})

**Comment by casperle** [comment]
@adorum I was thinking to create a variable outside the `graphql()` HOC, and provide the same references of first level objects of data props in `graphql()` second arguments (the config object) props property. But this is just an overhead - it would be better to solve it inside `graphql()`.
example:
```
const propsData = {};

graphql(MY_QUERY, {
  props: (data) => {
    // do the magic with propsData 
  }
})
```

**Comment by hwillson** [comment]
This should no longer be an issue with current day versions of `react-apollo`, but if anyone is still encountering this issue (and can provide a small runnable reproduction), we'll take a look. Thanks!
