### ISSUE TITLE
Variables coerced to type, but not when reading from cache

### ISSUE THREAD

**Issue by daviestar** [apollographql/react-apollo#1941]
Hey,

I spent a while figuring this out today.  It's debatable whether this is a bug, or intended behaviour, but perhaps it should be documented if it's intended.

I have a query:
```js
graphql(getGallery, {
  options: ({match}) => ({
    variables: {
      id: match.params.gallery
    }
  }),
  props: ({data}) => ({
    gallery: data.gallery || {}
  })
})
```
The `id` variable passed to the query comes from react router URL params, and hence is always a string.  However my query expects an `Int`:
```js
const getGallery = gql`
  query GetGallery($id: Int!) {
     ...
  }
}
```
I realised some time ago that apollo doesn't need me to `parseInt` these variables, so I've not been doing it.  However after a mutation composed on the same component such as:
```js
graphql(destroyImage, {
  name: 'destroyImage',
  props: ({destroyImage}) => ({
    destroyImage: (hash) => destroyImage({variables: {hash}})
  }),
  // the 'gallery' prop here is the outcome of the 'getGallery' query above
  options: ({gallery: {id}}) => ({
    update: (cache, {data: {destroyImage: {destroyed}}}) => {
      const data = cache.readQuery({query: getGallery, variables: {id}})
      // throws
      data.gallery.images.splice(data.gallery.images.findIndex((o) => o.hash === destroyed), 1)
      cache.writeQuery({query: getGallery, data})
    }
  })
}),
```
`cache.readQuery` fails, as the variable used is now an `Int`.

**Actual behaviour**
`query` behaves differently from `cache.readQuery`

**Intended behaviour**
`query` and `cache.readQuery` should be consistent.

**Version**
react-apollo@2.1.3

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
