### ISSUE TITLE
Typescript typings do not work with React 15 and react-apollo 2.1.3

### ISSUE THREAD

**Issue by pasih** [apollographql/react-apollo#1949]
First of all, correct me if I'm wrong but I assume react-apollo 2.1.3 is meant to be compatible with React 15 (peerDependencies lists React versions down to 14.x).

Currently, I'm having difficulty getting the combination of React 15, Typescript and react-apollo 2.1.3 to work.

**Intended outcome:**

Working app. :)

**Actual outcome:**

```
work/tests/ts-apollo-test/node_modules/react-apollo/ApolloProvider.d.ts
(25,5): Property 'render' in type 'ApolloProvider<TCache>' is not assignable to the same property in base type 'Component<ApolloProviderProps<TCache>, {}>'.
  Type '() => ReactNode' is not assignable to type '() => false | Element | null'.
    Type 'ReactNode' is not assignable to type 'false | Element | null'.
      Type 'undefined' is not assignable to type 'false | Element | null'.
```

I assume this is somehow related to React 16's extended idea of an element (strings, arrays etc. are included) and Apollo assuming a React 16-style ReactNode. React 15 types have a more limited definition of ReactNode.

**How to reproduce the issue:**

Here's a repository that reproduces the issue:

https://github.com/pasih/react15-apollo-ts-issue

(Just `npm install` and you should already see the error in your editor. If not, try compiling the app).

**Version**

* apollo-client@2.2.8
* react-apollo@2.1.3
* react@2.1.3
* react-dom@2.1.3
* @types/react@15.6.15
* @types/react-dom@15.5.7

**Issue Labels**

- [x] has-reproduction
- [ ] feature
- [ ] docs
- [ ] blocking
- [ ] good first issue

**Comment by pierrebiver** [comment]
The example from the website does not work neither:
```
import React from "react";
import gql from "graphql-tag";
import { graphql, ChildDataProps } from "react-apollo";

const HERO_QUERY = gql`
  query GetCharacter($episode: Episode!) {
    hero(episode: $episode) {
      name
      id
      friends {
        name
        id
        appearsIn
      }
    }
  }
`;

type Hero = {
  name: string;
  id: string;
  appearsIn: string[];
  friends: Hero[];
};

type Response = {
  hero: Hero;
};

type InputProps = {
  episode: string
};

type Variables = {
  episode: string
};

type ChildProps = ChildDataProps<InputProps, Response, Variables>;

const withCharacter = graphql<InputProps, Response, Variables, ChildProps>(HERO_QUERY, {
  options: ({ episode }) => ({
    variables: { episode }
  }),
  props: ({ data }) => ({ ...data })
});

export default withCharacter(({ loading, hero, error }) => {
  if (loading) return <div>Loading</div>;
  if (error) return <h1>ERROR</h1>;
  return ...// actual component with data;
});
```

I use:
- Typescript@2.8.1
-  apollo-client@2.2.8
- react-apollo@2.1.3
- react@16.3.2

**Comment by reem** [comment]
Yup, also having this exact issue. Deleting the re-declaration of `render` in the type declaration for `ApolloProvider` fixes the issue.

**Comment by lukebarton** [comment]
I think @pierrebiver's issue is separate - but I'm experiencing his - the example fails type checks specifically with:
```
[ts]
Argument of type '{ options: ({ episode }: InputProps) => { variables: { episode: string; }; }; props: ({ data }: O...' is not assignable to parameter of type 'OperationOption<InputProps, Response, Variables, ChildDataProps<InputProps, Response, Variables>>'.
  Types of property 'props' are incompatible.
    Type '({ data }: OptionProps<InputProps, Response, OperationVariables>) => { error?: ApolloError; netwo...' is not assignable to type '(props: OptionProps<InputProps, Response, OperationVariables>, lastProps?: void | ChildDataProps<...'.
      Type '{ error?: ApolloError; networkStatus: number; loading: boolean; variables: OperationVariables; fe...' is not assignable to type 'ChildDataProps<InputProps, Response, Variables>'.
        Type '{ error?: ApolloError; networkStatus: number; loading: boolean; variables: OperationVariables; fe...' is not assignable to type 'InputProps'.
          Property 'episode' is missing in type '{ error?: ApolloError; networkStatus: number; loading: boolean; variables: OperationVariables; fe...'.
```

**Comment by ebenoist** [comment]
Just ran into this as well. It would seem that these components are simply not useable if using React 15.6 type definitions. I'd be happy to PR @reem's fix if this is desirable.

**Comment by rosskevin** [comment]
Update your stack of dependencies and potentially rebuild your workspace - `ncu -a && rm -rf node_modules && yarn install`.  Given the stack of dependencies used these can get out of date, but as of now they are working.
