### ISSUE TITLE
Query with fetchPolicy: network-only called continuously. Query returns data, but loading is true and networkStatus 2

### ISSUE THREAD

**Issue by spjharper** [apollographql/react-apollo#1952]
In the compose HOC below the last PatientVectors query needs the data returned from the PlanListWorkspaces that will be set by a call to newProps. 
With a fetchPolicy of network-only (which we really need to use) the query executes continuously (you can see it going round trip repeatedly in DevTools Network tab and returning all the expected data each time). 

A breakpoint set in renderWhileLoading shows that each returned query props has networkStatus 2, loading: true, and the expected patientVectors array returned with the complete set of data. The component's render is never called since renderWhileLoading  always gets called with loading: true. renderWhileLoading is just a wrapper around recompose's branch.

If I take the fetchPolicy off the PatientVectors query and use the default, then it executes the query just once the first time, and then never again for the session. This is a problem since the data can be updated by an external process at the server, hence the need for network-only.

We were using this same pattern to use results from a previous query as variables in the next with the first 2 queries. It seems in adding the third I've done something wrong or have hit some strange bug in apollo. I did see an old issue with network status getting stuck at 2. But that was in 1.4.

We are using apollo-cient 2.2.3 with recompose 0.26.0 and react 16.2.0

===============================================================================
const newProps = props => {
  const {facilityData, workspaceData, systemConfigData} = props
  const workspaces = collectWorkspaces(facilityData.facilities, workspaceData.workspaces)
  const departments = collectDepartments(facilityData.facilities)
  const systemConfigs = systemConfigData.configs
  return {...props, workspaces, departments, systemConfigs}
}

export const PlanListView = compose(
  withMutations([
    PlanGQL.mutations.updateProgressionIndicator,
    VisitGQL.mutations.updatePatientProblem,
    VisitGQL.mutations.updateWorkingDischargeDisposition,
    VisitGQL.mutations.updateBedRequestStatus,
    VisitGQL.mutations.updateAnticipatedDischargeTime
  ]),
  withPinMutations,
  withApollo,
  graphql(ConfigGQL.queries.alertIconConfig, {name: 'alertIconConfig'}),
  graphql(ConfigGQL.queries.caAppConfigs, {name: 'systemConfigData'}),
  graphql(WorkAreaGQL.queries.FacilityBeds, {
    name: 'facilityData',
    options: {
      variables: {assignedBedsOnly: true},
      fetchPolicy: 'network-only'
    }
  }),
  renderWhileLoading(LoadingIndicator, 'facilityData', 'facilities'),
  graphql(WorkspaceGQL.queries.PlanListWorkspaces, {
    name: 'workspaceData',
    options: ({facilityData}) => {
      const currentVisitIds = collectCurrentVisitIds(facilityData.facilities)
      const dischargedVisitIds = collectDischargedVisitIds(facilityData.facilities)
      return {
        variables: {
          visitIds: [...currentVisitIds, ...dischargedVisitIds]
        },
        fetchPolicy: 'network-only'
      }
    }
  }),
  renderWhileLoading(WorkspaceLoadingIndicator, 'workspaceData', 'workspaces'),

  mapProps(props => newProps(props)),
  connect(mapStateToProps, mapDispatchToProps),

  graphql(VectorGQL.queries.PatientVectors, {
    name: 'patientVectorData',
    skip: () => !isJvionEnabled(),

    options: ({workspaces}) => {
      const currentMRNs = collectCurrentMRNs(workspaces)
      return {
        variables: {
          ids: [...currentMRNs]
        },
        fetchPolicy: 'network-only'
      }
    }
  }),
  renderWhileLoading(WorkspaceLoadingIndicator, 'patientVectorData', 'patientVectors')

)(PlanList)

**Comment by fastie9000** [comment]
have the same issue. with networy-only it just sends query every second and returns the correct data with loading=true, but networkStatus=1

**Comment by hwillson** [comment]
Please try this again using `react-apollo` >= 2.5.6. This should no longer be an issue, but let us know otherwise. Thanks!
