### ISSUE TITLE
config.skip not working on graphql()mutations - does work on graphql()query

### ISSUE THREAD

**Issue by carllippert** [apollographql/react-apollo#1954]
**Intended outcome:** 
  
Config.skip should allow me to call this.props.select({id}) in many different contexts. This is a reusable selection modal. It worked with react-apollo 2.0.4.

```
export default compose(
  graphql(mountedPens, {
            skip: (props) => props.navigation.state.params.modalType != "FeedingPen",
            props: ({data: { mountedPens, loading }}) => ({ data: mountedPens, loading }),
            }),
  graphql(mountedPens, {
            skip: (props) => props.navigation.state.params.modalType != "Pen",
            props: ({data: { mountedPens, loading }}) => ({ data: mountedPens, loading }),
            }),
  graphql(setSelectedPen, {
            skip: (props) => props.navigation.state.params.modalType != "Pen",
            props: ({ mutate }) => ({
              select: ({id}) => mutate({ variables: { pen_id: id } }),
            })
          }),
  graphql(setActiveBatchPen, {
            skip: (props) => props.navigation.state.params.modalType != "FeedingPen",
            props: ({ mutate }) => ({
              select: ({id}) => mutate({ variables: { pen_id: id } }),
            })
          }),
  graphql(mountedRations, {
            skip: (props) => props.navigation.state.params.modalType != "Ration",
            props: ({data: { mountedRations, loading }}) => ({ data: mountedRations, loading }),
            }),
    graphql(setSelectedRation, {
            skip: (props) => props.navigation.state.params.modalType != "Ration",
            props: ({ mutate }) => ({
              select: ({id}) => mutate({ variables: { ration_type_id: id } }),
            })
          }),
    graphql(mountedVendors, {
            skip: (props) => props.navigation.state.params.modalType != "Vendor",
            props: ({ data: { mountedVendors, loading }  }) => ({ data: mountedVendors, loading }),
          }),
    graphql(setSelectedVendor, {
            skip: (props) => props.navigation.state.params.modalType != "Vendor",
            props: ({ mutate }) => ({
              select: ({id}) => mutate({ variables: { vendor_id: id } }),
            })
          }),
  graphql(setSelectedIngredient, {
            skip: (props) => props.navigation.state.params.modalType != "Ingredient",
            props: ({ mutate }) => ({
              select: ({id}) => mutate({ variables: { ingredient_id: id } }),
            })
          }),
  graphql(mountedIngredients, {
            skip: props => props.navigation.state.params.modalType != "Ingredient",
            props: ({ data: { mountedIngredients, loading }  }) => ({ data: mountedIngredients, loading }),
        }),
)(SelectionModal);
```

**Actual outcome:**

Last mutation in the compose functions always gets called with this.props.select({ id }).
As I understand compose calls functions backwards so this means the first mutation it see's its calling and ignoring the skip function. 

Downgrading back to 2.0.4 did in fact fix it too. Docs don't seem to reflect a change in implementation in this area as far as I can tell. 

**Version**

* apollo-client@<2.2.8>
* react-apollo@<2.1.3>

<!--**Issue Labels**

While not necessary, you can help organize our issues by labeling this issue when you open it.  To add a label automatically, simply [x] mark the appropriate box below:

- [x] has-reproduction
- [ ] feature
- [ ] docs
- [ ] blocking
- [ ] good first issue

**Comment by coder-guy22296** [comment]
+1

**Comment by TheMickeyMike** [comment]
+1

**Comment by lasersox** [comment]
Just ran into this today, any plan to resolve it?

**Comment by aopsfan** [comment]
Ran into this as well. I found a quick workaround. Citing your example above:

    graphql(setSelectedPen, {
        props: ({ mutate, ownProps }) => {
          const skip = ownProps.navigation.state.params.modalType !== "Pen"
          if (skip) return {}
          return {
            select: ({ id }) => mutate({ variables: { pen_id: id } }),
          ...

**Comment by rps** [comment]
+1, workaround is to use ownProps to selectively call mutate, per above comment

**Comment by kouak** [comment]
Ran into this with react-apollo@2.5.2

**Comment by track0x1** [comment]
Aside from the fact that this is not supported, why not just name your mutations and handle the conditional logic in your application?

```js
let mutate;

if (something === 1) {
  mutate = this.props.mutateFirst;
} else if (something === 2) {
  mutate = this.props.mutateSecond;
}

mutate();
```

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
