### ISSUE TITLE
Subscription using subscribeToMore shows up in Network tab and Playground but does not update in React

### ISSUE THREAD

**Issue by pojntfx** [apollographql/react-apollo#1957]
**Intended outcome:**

I'm trying to update a feed of proposals when a new one gets created using `graphql-subscriptions`. I query the initial data, then use subscribeToMore to query updates. In my case this means adding a new card with a new proposal.

**Actual outcome:**

The feed of proposals does not update after the first publish in the channel, but does so after the second. Using the playground to subscribe works and Chrome's network monitor shows activity on the WebSocket, but the client does not update.

Initial version:

![image](https://user-images.githubusercontent.com/28832235/39427466-1885f8e0-4c84-11e8-9947-1bed1494afe2.png)

After running 
```gql
mutation {
  createProposal(text:"Second proposal", author: "me") {
    text
  }
}
```
in the Playground:

![image](https://user-images.githubusercontent.com/28832235/39427527-519a01e4-4c84-11e8-8237-4df4122c7128.png)

As you can see in the network monitor, there is some activity and the WebSocket seems to work, but the new proposal doesn't show up.

After then running
```gql
mutation {
  createProposal(text:"Third proposal", author: "me") {
    text
  }
}
```
in the Playground:

![image](https://user-images.githubusercontent.com/28832235/39427558-7a13698a-4c84-11e8-9a37-cde558dfaf98.png)

As you can see, the second proposal now shows up, but the newest one is missing.
After reloading:

![image](https://user-images.githubusercontent.com/28832235/39427610-b6dcb97a-4c84-11e8-9c69-d3340198790b.png)

Using the Playground to subscribe works.

**How to reproduce the issue:**

```bash
git clone https://github.com/pojntfx/simple-direct-democracy-backend
cd simple-direct-democracy-backend 
npm install
npm run dev
git clone https://github.com/pojntfx/simple-direct-democracy-frontend
cd simple-direct-democracy-frontend 
npm install
npm run dev
```
Then follow the steps from above. The relevant frontend code:

```js
<Query query={ALL_PROPOSALS_QUERY}>
          {({ loading, error, data, subscribeToMore }) => {
            if (loading) return `Loading ...`;
            if (error) return `Error! ${error.message}`;

            return (
              <ProposalList
                proposals={data.allProposals}
                subscribeToNewProposals={() => {
                  subscribeToMore({
                    document: ALL_PROPOSALS_SUBSCRIPTION,
                    updateQuery: (prev, { subscriptionData }) => {
                      if (!subscriptionData.data) return prev;
                      return {
                        allProposals: subscriptionData.data.updatedProposals
                      };
                    }
                  });
                }}
              />
            );
          }}
        </Query>
```

and

```js
class ProposalList extends Component {
  componentDidMount() {
    this.props.subscribeToNewProposals();
  }

  render() {
    const { proposals } = this.props;

    return (
      <Transition.Group as={List} duration={200} animation="scale">
        {proposals.map(({ text, votes, id }, index) => (
          <List.Item key={index}>
            <Proposal votes={votes} id={id} key={index}>
              {text}
            </Proposal>
          </List.Item>
        ))}
      </Transition.Group>
    );
  }
}
```

**Version**

* apollo-client@2.2.8
* react-apollo@2.1.3

**Comment by rosskevin** [comment]
If it does not cause a rerender, you likely have a cache normalization issue, like you did not request an id in the payload for cache matching. I. This case, the existing cache object is not updated and the UI components will not rerender because the object they are observing indeed has not changed. This is the most common case with these sort of issues. If you verify this is not the case, please ping me and I'll reopen.

**Comment by khaphannm** [comment]
I have the same issues, while the subscription works find on the playground. But on the client does not get the updated data.
