### ISSUE TITLE
ownProps not updating when Component receives new props

### ISSUE THREAD

**Issue by pavship** [apollographql/react-apollo#1958]
**Intended outcome:**

ownProps in subscription handler should always match the props of the Component

**Actual outcome:**

ownProps in subscription handler are always equal to the initial props of the Component and never change when the Component receives new props.

**How to reproduce the issue:**

Chart component has showFromDate property, which can be changed with datepicker. In order to display only those items that fit into chosen time period, I need to compare new items received within subscribtion with the current props of the Component.
```javascript
export default graphql(
  chartItems,
  {
    name: 'chartItems',
    props: ({ chartItems, ownProps }) => {
      // the following log always prints up-to-date ownProps (GOOD)
      console.log(ownProps) 
      return {
        chartItems: chartItems,
        subscribeToItems: () => chartItems.subscribeToMore({
          document: newItem,
          updateQuery: (prev, { subscriptionData: { data : { newItem } } }) => {
            // the following log always prints initial Component's props (BAD)
            console.log(ownProps)
            // only push newItem if condition is true (CANNOT DO THIS CHECK AS ownProps ARE WRONG)
            if (ownProps.showFromDate < newItem.date) {
              const filteredItems = prev.chartItems.filter(item => item.id !== newItem.id)
              return { chartItems: [...filteredItems, newItem] }
            } else {
              return { chartItems: prev.chartItems }
            }
          }
        })
      }
    }
  }
)(Chart)
```

**Version**

* apollo-client@2.2.6
* react-apollo@2.0.4

**Comment by rosskevin** [comment]
Please consider providing a codesandbox from the template with a reproduction. If you do so ping me and I'll reopen. Please understand it's important that we draw attention to issues with reproductions and optimize the time of the few core developers we have (I am not one, just trying to help though).
