### ISSUE TITLE
Feature Idea: additional callback on Query component onChange(networkstatus) 

### ISSUE THREAD

**Issue by serle** [apollographql/react-apollo#1965]
I need to update/recalculate the state of my component in response to Query data. However due to the Query render prop approach I can't update the state in the render function as we are in the rendering phase. I would prefer the networkStatus updates to be received via a separate callback function so that I could recalculate and update my component state there outside of the rendering phase.

**Comment by serle** [comment]
similar to #1947, just need the ability to update component state once query has resolved, but before the render cycle. Work-around is to have a child component receive the result as props, but then we are back to something similar to a HOC with a wapper component and an inner component.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, React Apollo feature requests are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Feature%20Idea%3A%20additional%20callback%20on%20Query%20component%20onChange(networkstatus)%20&body=Migrated%20from:%20apollographql/react-apollo%231965) to start the feature request migration process. This manual migration process is intended to help identify which of the outstanding feature requests are still considered to be of value to the community. Thanks!
