### ISSUE TITLE
Mutation HoC WrappedComponent additional props

### ISSUE THREAD

**Issue by pyromaniac** [apollographql/react-apollo#1967]
Hello guys, thanks for the great react integration. It definitely got better with each release.
There is one thing I don't understand. What is the reason to omit all the useful properties like `loading` in mutation HoC (https://github.com/apollographql/react-apollo/blob/e2147f8448e691ff5a7244c8aab68c28e94df4be/src/mutation-hoc.tsx#L61)? Why don't pass them under some key like `mutation` or even `[name]` like it is done for queries?

**Comment by jamesjryan** [comment]
Any progress on this?

**Comment by rosskevin** [comment]
PR welcome.

**Comment by kwiss** [comment]
because https://github.com/apollographql/apollo-client/issues/3253#issuecomment-410539778
