### ISSUE TITLE
query overwrites subelement array of other query

### ISSUE THREAD

**Issue by TromPeter15** [apollographql/react-apollo#1971]
**Description of procedure:**

I have two queries fetching the category types of a company. The employee query includes a subset of types of the company query types in the database. If I just query the employee query, the employee types array includes 2 elements. If I just query the company query, the company types array includes 4 elements. Well.. But if i query both, the types array of employee gets updated and suddenly includes 4 elements instead of 2.

**Current Error behaviour:**

Actually the problem is, that apollo merges the responses of the types subelement but the employee types is a filtered subset of the company types array. Apollo assumes, that elements have been added and automatically overwrites the whole employee types array. Not only the existing elements get updated, but also the whole array length changes by adding the new elements from the company call

**Code snippet:**

`
query GetEmployee ($id: ID!) {
  employee (id: $id) {
  id,
  companyTaskCategories{
      id,
      title,
      color,
      archived,
      types(restrictEmployee: true)  {
        id,
        title,
        archived,
      }
  }
}

query company {
company {
  id,
  taskCategories {
    id,
    title,
    color,
    archived,
    types(restrictEmployee: false) {
      id,
      title,
      archived,
    }
  }
}
}`

**Version**

* react-apollo@2.1.4

**Comment by rosskevin** [comment]
This is not a react-apollo issue.  Perhaps apollo-client and cache management.

Closing - housekeeping
