### ISSUE TITLE
SSR ERROR not pass down to children `renderToStringWithData`

### ISSUE THREAD

**Issue by theasia-Ashish** [apollographql/react-apollo#1972]
Error on `renderToStringWithData` error data can't reach to components on SSR. Even If i apply `errorPolicy: "all"`.

**Intended outcome:** `this.props.data.error=error_data`

**Actual outcome:**`this.props.data.error= undefined`

**How to reproduce the issue:** Try server rendering with a query(component) return any error on graphql resolver.

**Version**

* apollo-client@2.2.8
* react-apollo@2.1.3

**Comment by adamesque** [comment]
Dup of #1781

**Comment by theasia-Ashish** [comment]
@adamesque Its also not working with default `errorPolicy`.

**Comment by migueloller** [comment]
@adamesque, these are separate problems.

#1781, is about errors not being cached and thus losing the ability to handle them when mounting and remounting components.

This one is about the fact that `getDataFromTree` and `renderToStringWithData` throw an error when any error occurs, even when `errorPolicy` is set to `all`.

#615 has more detail.

**Comment by tobobo** [comment]
I've opened a PR to fix the inaccurate documentation around error cacheing in Apollo. https://github.com/apollographql/apollo-client/pull/4237
