### ISSUE TITLE
Several issues with 2.1.x

### ISSUE THREAD

**Issue by rafaponieman** [apollographql/react-apollo#1974]
First of all, thanks for Apollo, it's great, and I really like it.

I've bumped into several problems with the latest version.

1. Cache would return the same data if I changed variables for the same value as a previous query. It's described in detail in #1853. It seems like it's a serious bug that shouldn't be present on 2.1.4 (it could be on an alpha, or beta, but not on a final release), plus, it was reported on March 27th and not yet fixed.

2. I bumped onto another issue, that I can't currently define in detail, because I haven't been able to pin down the exact cause or way to repeat, but it's happening on 2.1.x and NOT on 2.0.4. I have a query that I pass an array as a parameter. When updating that array for ["4"], it runs the query, then I update again for ["4", "6"], and the query gets called, but it doesn't get to the server, and it returns null results (no error reported). I tried both with the new Query component as with the graphql HOC, same problem with both. With the exact same code, I downgraded to 2.0.4 and the problem was instantly fixed. If I get some guidance I can gladly help identify the issue.

3. The documentation for 2.0.x doesn't seem to be available any more. This shouldn't happen, as docs should still be available for previous versions when new ones are released.

4. There aren't tags on this repository for 2.0, 2.0.1, 2.0.4, etc, many tags are missing.

I'm available to help in any way possible. Thank you.

**Comment by rosskevin** [comment]
Please open individual issues for anything you need.  If you would like to help, the best way to start is by submitting PRs with failing tests reproducing your errors, PRs for docs, or PRs for build process etc.  

Closing - housekeeping
