### ISSUE TITLE
If initial Query errors, data is undefined instead of empty object

### ISSUE THREAD

**Issue by TLadd** [apollographql/react-apollo#1977]
**Intended outcome:**
The data prop passed to the Query component is never undefined. That's my understanding anyways, from reading https://github.com/apollographql/react-apollo/blob/master/src/Query.tsx#L89

**Actual outcome:**
If your first request for a Query errors, data ends up being null. It ends up hitting this line, https://github.com/apollographql/react-apollo/blob/master/src/Query.tsx#L378, which overwrites the default-created empty object and replaces it with `(this.queryObservable!.getLastResult() || {}).data,`, which will be undefined if the query doesn't have a result yet

**How to reproduce the issue:**
On any react-apollo application with a Query, force an error to occur and log the data passed to children. I personally encountered this when I had accidentally not had my graphql server running. As a result, the first Query request failed due to a network error, and I got an exception because I was assuming data would be an empty object and not undefined.

**Version**

* apollo-client@2.3.0
* react-apollo@2.1.4

**Comment by alamothe** [comment]
The typings say `data` is either `TData` or `undefined` - never empty object: https://github.com/apollographql/react-apollo/blob/3985b47f086f38f891099732842ca2f16c7966c4/src/Query.tsx#L97

So which one is it?
