### ISSUE TITLE
getDataFromTree ignores context consumer

### ISSUE THREAD

**Issue by Rusya44** [apollographql/react-apollo#1979]
**Intended outcome:**

Working SSR :)

**Actual outcome:**
getDataFromTree ignores context (React 16.3 new API) consumer.

Cache data with context consumer usage:
![image](https://user-images.githubusercontent.com/8863448/39966333-c5ad1c0a-56b2-11e8-8b5e-e08b6c5bbb9d.png)

Without context consumer:
![image](https://user-images.githubusercontent.com/8863448/39966335-d37bcaca-56b2-11e8-9e45-bc378946c2af.png)

**How to reproduce the issue:**

https://codesandbox.io/s/qv1m0v35zq

**Version**

* react@16.3.2
* react-dom@16.3.2
* apollo-client@2.3.1
* react-apollo@2.1.4

<!--**Issue Labels**

While not necessary, you can help organize our issues by labeling this issue when you open it.  To add a label automatically, simply [x] mark the appropriate box below:

- [x] has-reproduction
- [ ] feature
- [ ] docs
- [ ] blocking
- [ ] good first issue

**Comment by Rusya44** [comment]
Oh, there is already PR #1978. Didn't see.

**Comment by leanazulyoro** [comment]
Hello, I have tried this with the last version available today (2.1.9). And even then, the problem persists.
I see that the PR #1978 claims solving this, but I don't see how it does.
Here's a sandbox with react-apollo updated to 2.1.9: https://codesandbox.io/s/pkow5xzwkq

**Comment by leanazulyoro** [comment]
Sorry, I was messing it up. I fixed the sansbox, now it works.
