### ISSUE TITLE
[3.0] Loading state bug with suspense

### ISSUE THREAD

**Issue by peggyrayzis** [apollographql/react-apollo#1981]
Brain dumping this so we don't forget:

While I was building the suspense demo for React Europe, I ran into a bug fetching a low-priority query. The first request successfully suspends. For the second request, if the Timeout threshold was lower than the response time, React would enter an infinite loop of unmounting and remounting the Query component.

Unmounting the Query component caused the query subscription to unsubscribe and the request to cancel. Commenting this line out temporarily fixes the demo. React's `simple-cache-provider` doesn't currently have a way to clean up a "canceled" request, which makes sense within the context of suspense. If we suspend a request and initiate a new request before the old one resolves, we should store the old request's response in the cache anyway instead of canceling it all together. This makes sense for queries but becomes problematic when you introduce mutations into the mix.

After some digging, we found that the second request was never successfully suspending because `loading` was false. This is because we call `queryObservable.currentResult()` to grab the loading state, which is set to false because the currentResult has already completed. We need a way to set the loading state to true here if we're in async mode to kick off suspense.

Another possible source of the bug could be in `getDerivedStateFromProps`. Currently, we store all props on state. Instead of returning an updated state object, we return the previous state (which reflects the old props instead of `nextProps`).

We have an interesting couple months ahead to make sure React Apollo is fully compatible with suspense, but I'm excited about the direction we're heading and that we have a (mostly) working demo. 🎉

**Comment by hwillson** [comment]
A lot has changed since this issue was created, so closing for now. Thanks!
