### ISSUE TITLE
Doubly nested array produces incorrect values

### ISSUE THREAD

**Issue by danyim** [apollographql/react-apollo#1982]
**Intended outcome:**
I expect the tagged `graphql(query)` to return a prop that's consistent with what was inspected on the network tab.

**Actual outcome:**
A nested array has the wrong values/references:

![image](https://user-images.githubusercontent.com/442889/40026284-96da394e-5789-11e8-94a4-f712502eec21.png)
Notice how the props produced by Apollo at the bottom console is not consistent with the payload from the `graphql` network call.

I would have expected the output of
```js
data.test.trajectories[0].objects.slice(0, 5).map(v => v.outline[0])
```
to be 
```js
[
  [-2112.486083418982, 1732.0826704674218],
  [-2106.8766382275658, 1732.6464890664752], 
  [-2095.448650393578, 1721.2946472946403], 
  [-2105.9516151264206, 1750.3747253285662],
  ...
]
```

**How to reproduce the issue:**
Not sure how to reproduce.

**Version**

* react-apollo@^2.1.3

**Comment by hxuanhung** [comment]
I got the same problem for `2.1.0`

**Comment by rosskevin** [comment]
Closing - housekeeping
