### ISSUE TITLE
Using only fragment on Query type causes data not to be fetched

### ISSUE THREAD

**Issue by asafigan** [apollographql/react-apollo#1986]
**Intended outcome:**
Query is executed.

**Actual outcome:**
No data returned. No network traffic. No query executed. Loading is false. Error is null

**How to reproduce the issue:**
Send query with just a fragment to React Apollo.

example query: 
```
{
    ... on Query {
        # something
    }
}
```

**Version**

* apollo-client@2.1.0
* react-apollo@2.0.4

**Comment by rosskevin** [comment]
Closing - housekeeping
