### ISSUE TITLE
Not restore ot not connect cache on client rehydrate with SSR rendering

### ISSUE THREAD

**Issue by apapacy** [apollographql/react-apollo#1992]
**Intended outcome:**

J'm use SSR and rehydrate on client with in-memory cache

**Actual outcome:**

SSR generate valid html with data. Cache object on client seems as valid (data.data is contain actual info) but not connect to component.  On client hydrate data re-fetching from server and component re-render with empty data and with data after take data from server

**How to reproduce the issue:**

```
import { InMemoryCache } from "apollo-cache-inmemory";
import ApolloClient from 'apollo-boost';

const cache = new InMemoryCache().restore(window.__APOLLO_STATE__);
const client = new ApolloClient({
  uri: 'https://api.graph.cool/simple/v1/ciyz901en4j590185wkmexyex',
  cache,
});

hydrate(<App client={client} />, document.getElementById('app'));

```

branch 'ssr' on repository https://github.com/apapacy/apollo-lesson/tree/ssr

```
    "apollo-boost": "^0.1.6",
    "apollo-cache-inmemory": "^1.2.1",
    "apollo-client": "^2.3.1",
    "apollo-client-preset": "^1.0.8",
    "apollo-link-http": "^1.5.4",
...
    "react": "^16.3.2",
    "react-apollo": "^2.1.4",
    "react-dom": "^16.3.2",
    "react-router-dom": "^4.2.2",
```

**Comment by rosskevin** [comment]
Closing - housekeeping
