### ISSUE TITLE
Typescript with Query component. QueryType does not appear to be interpreted correctly

### ISSUE THREAD

**Issue by dan-kez** [apollographql/react-apollo#1993]
**Intended outcome:**

I'm attempting to use the new `<Query />` component API with Typescript. 

**Actual outcome:**

I receive an error that `data` does not have the associated type. The example below reproduces this issue.

```
Type 'CocktailListViewQuery | undefined' has no property 'cocktails' and no string index signature.
```

**How to reproduce the issue:**

See the following code for a reproduced example

[![Edit TypeScript playground](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/71715qjpx6)

**Version**

* apollo-client@^2.3.1
* react-apollo@^2.1.4

**Comment by dmk255** [comment]
Follow up - I started sifting through the tests cases and found that none of them unpack `data`.

https://github.com/apollographql/react-apollo/blob/master/test/client/Query.test.tsx#L221-L227

If I do edit the test to unpack data I get the same error as in the CodeSandbox above.

**Comment by rosskevin** [comment]
Closing - housekeeping

**Comment by shunjilin** [comment]
I am facing the same issue too, not sure if there is a better way to do this
