### ISSUE TITLE
Typescript: graphql-wrapper mutate prop is missing typings for 'variables' field

### ISSUE THREAD

**Issue by ChrisGitter** [apollographql/react-apollo#1997]
**Intended outcome:**

```
interface Variables {
  foo: string;
}

graphql<InputProps, Response, Variables, ChildProps>(
  Mutation,
  {
    props:({ ownProps: { ... }, mutate }) => ({
      exampleMutation: () => mutate({
        variables: {
          baz: 'example' // => type error
        }
      })
    })
  }
)
```

**Actual outcome:**

The variables property inside the mutate prop above is not typed correctly.

**How to reproduce the issue:**

**Version**

* apollo-client@2.3.1
* react-apollo@2.1.4

Checking the `types.d.ts` file it looks like line 117 is missing a type variable.
```
props?: (props: OptionProps<TProps, TData> ...
```

should be
```
props?: (props: OptionProps<TProps, TData, TGraphQLVariables> ...
```
shouldn't it?

**Comment by veeramarni** [comment]
@ChrisGitter  Do you still have the problem?

**Comment by ChrisGitter** [comment]
Nope, works now :)
