### ISSUE TITLE
 Feature: Subscription Component to pass Context(headers)

### ISSUE THREAD

**Issue by trentis** [apollographql/react-apollo#1999]
1. Use case: 
Right now I am trying to develop an app that can add servers(hosts) to connect to. The way I decided to implement this is forward a header to the back end which would end up sending the request to the appropriate server.  

The forwarder seems to be  fine as the query component works with the context however I can't seem to add context to the subscription component or using the query component with subscribeToMore().

2. Could this be a plugin? I'm not to sure as I think we currently import the subscription-transport-ws. Let me know if this is the wrong project as I figured the component is created here which is why I am asking the issue here

3. Is there a workaround? I'm not to sure if there is a work around currently as I have tried looking for the past few hours. It may be that the documentation isn't listing this functionality somewhere.

What I am trying to say is I love this 
`<Query query={GetBuckets} context={{
"headers":{
"server":"name"
}
}}>`

And I want this
`<Subscription subscription={SubGetProjects} context={{
"headers":{
"server":"name"
}
}}>`

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, React Apollo feature requests are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=%20Feature%3A%20Subscription%20Component%20to%20pass%20Context(headers)&body=Migrated%20from:%20apollographql/react-apollo%231999) to start the feature request migration process. This manual migration process is intended to help identify which of the outstanding feature requests are still considered to be of value to the community. Thanks!
