### ISSUE TITLE
Feature: add `component` prop to Query component

### ISSUE THREAD

**Issue by WickyNilliams** [apollographql/react-apollo#2000]
**Intended outcome:**

It it fairly common to wrap a component in a Query, and forward all props, like so:

```js
<Query query={foo} variables={{ id : 1 }}>
  {props => <SomeComponent {...props} />
</Query>
```

It would be good if there were a `component` prop, [akin to react-router's](https://reacttraining.com/react-router/web/api/Route/component), which reduced this simple use-case down to:

```js
<Query query={foo} variables={{ id : 1 }} component={SomeComponent} />
```

**Actual outcome:**

This would simplify usage in a common case.

**How to reproduce the issue:**

N/A

**Version**

* apollo-client@2.2.8
* react-apollo@2.1.2

**Comment by rosskevin** [comment]
We are trying to stay away from too many variations on the API.  If this is your preferred pattern, there is nothing stopping you from doing this a a decoration in your own lib/app (we decorate Query in ours with our internal patterns/standards).
