### ISSUE TITLE
Feature: Add client to Mutation render Props

### ISSUE THREAD

**Issue by immortalx** [apollographql/react-apollo#2001]
I'm using react-native with Apollo and when the user logs out i need to reset the cache.

https://www.apollographql.com/docs/react/recipes/authentication.html#login-logout
The example uses the Query component which exposes the client as a render prop. Some apis implement logout as a mutation instead. 

I could nest the mutation inside a query component to access the client but i would like to be able to do this:

```
<Mutation mutation={MUTATION_LOGOUT}>
                {( logOut, { client } ) => {
                  return (
                    <View>
                      <Text
                        onPress={async () => {                  
                            await logOut()                            
                            await client.cache.reset()
                        }}>
                        Logout
                      </Text>
                    </View>
                  )
                }}
</Mutation>

```
**Intended outcome:**

Access the client render prop from Mutation component to be able to reset the cache.

**Actual outcome:**

The client render prop is only available in the Query component.

**How to reproduce the issue:**

N/A

**Version**

- apollo-client@2.3.1
- react-apollo@2.1.4

Thank you

**Comment by rosskevin** [comment]
As of now, client is part of the `MutationResult`.
