### ISSUE TITLE
Using custom resolvers in Typescript

### ISSUE THREAD

**Issue by majelbstoat** [apollographql/react-apollo#2002]
[The documentation for custom resolvers](https://www.apollographql.com/docs/react/features/performance.html) shows this:

```typescript
import { toIdValue } from 'apollo-utilities';
import { InMemoryCache } from 'apollo-cache-inmemory';

const cache = new InMemoryCache({
  cacheRedirects: {
    Query: {
      book: (_, args) => toIdValue(cache.config.dataIdFromObject({ __typename: 'Book', id: args.id })),
    },
  },
});
```

However, this gives a type error:

```
[ts] 'cache' implicitly has type 'any' because it does not have a type annotation
and is referenced directly or indirectly in its own initializer.
```

If we add an `InMemoryCache` type annotation, this gives two different errors:

```
[ts] Cannot invoke an object which is possibly 'undefined'.
[ts] Property 'config' is protected and only accessible within class 'InMemoryCache'
and its subclasses.
```

What's the correct way to use custom resolvers with Typescript?

**Version**

* apollo-client@2.3.0
* react-apollo@2.1.4
* typescript@2.8.1

**Comment by majelbstoat** [comment]
For the time being, my workaround is:

```typescript
import defaultDataIdFromObject from 'apollo-cache-inmemory'

  const cache = new InMemoryCache({
    dataIdFromObject: defaultDataIdFromObject,
    cacheRedirects: {
      Query: {
        user: (_, args) => {
          return toIdValue(defaultDataIdFromObject({ __typename: 'Book', id: args.id }) || '')
        },
      },
    },
  })
```

**Comment by rosskevin** [comment]
The link is dead so I could not verify as changed.  I also looked in the same area and did not spot the block of code in question.  I'm going to close, if you find it is still out of date please ping me with the right url and I'll reopen.
