### ISSUE TITLE
Feature: add context to refetchQueries

### ISSUE THREAD

**Issue by elmasse** [apollographql/react-apollo#2009]
**Use Case**:
Using a Link `split` and rely on `operation.getContext()` as in the example:

```js
import { ApolloLink } from 'apollo-link';
import { RetryLink } from 'apollo-link-retry';
import HttpLink from 'apollo-link-http';

const link = new RetryLink().split(
  (operation) => operation.getContext().version === 1,
  new HttpLink({ uri: "/v1/graphql" }),
  new HttpLink({ uri: "/v2/graphql" })
);

```

When executing a mutation that triggers a refetch there is no way to pass the `context`. 

```js
  graphql(mutateQueryAndRefetch, {
    options: () => ({
      context: { version: 1 },
      refetchQueries: [{
        query: SomeOtherQuery,
        context: { version: 1 },    // <-- need this to split the link correctly but refetchQueries only accepts `query` and `variables`.  Also context might be different than the mutate query.
        variables: {/*...*/ }
      }]
    }),
    props: ({ ownProps, mutate }) => {
      return {
        mutateAndRefetch: async (name) => {
          await mutate(/* .... */);
        }
      };
    }
  })(MyComponent);

```

**Workaround**:

Use `withApollo` and perform a `client.query` right after the mutation is executed:

```js
compose(
  withApollo,
  graphql(mutateQueryAndRefetch, {
    options: () => ({
      context: { version: 1 }
    }),
    props: ({ ownProps, mutate }) => {
      return {
        mutateAndRefetch: async (name) => {
          await mutate(/* .... */);
          await client.query({
            query: SomeOtherQuery,
            context: { version: 1 }    // <-- need this to split the link correctly
          })
        }
      };
    }
  })
)(MyComponent)

```

**Version**

* apollo-client@2.3.1
* react-apollo@2.1.4

**Issue Labels**

While not necessary, you can help organize our issues by labeling this issue when you open it.  To add a label automatically, simply [x] mark the appropriate box below:

- [ ] has-reproduction
- [x] feature
- [ ] docs
- [ ] blocking
- [ ] good first issue

To add a label not listed above, simply place `/label another-label-name` on a line by itself.

**Comment by elrumordelaluz** [comment]
I have a similar _issue_ described [here](https://stackoverflow.com/questions/50613562/apollo-authentication-with-gatsby), where the refetched `Query` don't have the updated info to pass to _Link_s as `context`.

**Comment by horva** [comment]
Hi there, this feature request is probably related to https://github.com/apollographql/apollo-client/pull/3580.
I've also noticed that in previous versions (disappeared after 2.1.0-beta.2) context was reused from cached query when using string value for refetchQueries, but now it's gone. Not sure if accidentally or with purpose. And why npm shows versions which are not present here as releases or tags?

**Comment by japrogramer** [comment]
what is the status of this? also could i re-use this context to tell the apollo to re-use the variables from the last query.

**Comment by japrogramer** [comment]
hello it's been almost a year, I need this feature for some refetches that take a long time.

**Comment by hwillson** [comment]
Apollo Client now supports passing `context` details when refetching queries. Thanks!
