### ISSUE TITLE
Flow types no longer exist

### ISSUE THREAD

**Issue by hammadj** [apollographql/react-apollo#2049]
**Intended outcome:** Type errors are detected when using flow

**Actual outcome:** Flow types no longer exist, and nothing is being type checked anymore

**Version**

* apollo-client@2.1.0
* react-apollo@2.1.4

**Comment by PascalSenn** [comment]
Note: Apollo no longer ships with Flow types. If you want to help contribute to add these, please reach out!

Https://www.apollographql.com/docs/react/recipes/static-typing.html

**Comment by KevinGrandon** [comment]
Very sad to see these types removed from react-apollo. Some of my old projects lost a lot of type safety. I'd be open to trying to build a community to maintain these types, but would they be accepted into the react-apollo core, or should we contribute to the flow-typed repo?

**Comment by rosskevin** [comment]
Flow types were not being maintained - the maintainers did not use them and the community was not active in PRing changes.  If you would like to maintain them, please look at creating a community effort for them on flow-typed.
