### ISSUE TITLE
Webpack externals

### ISSUE THREAD

**Issue by vangogh500** [apollographql/react-apollo#2052]
Hi so I was wondering if it were possible to include some of the apollo packages in externals for my webpack so that I don't have to recompile everything from scratch every single time. In order for this to happen I'd need some kind of minified/non-minified js file for the browser that I can just include with a link tag. However I don't know if this is available or possible.

My desired webpack:
`externals: {
        "react": "React",
        "react-dom": "ReactDOM",
        "react-apollo": //smthing here
    }`

My desired html:
`<script src="./js/smthing goes here"></script>`

Thanks!

**Comment by rosskevin** [comment]
Closing - housekeeping

**Comment by nikolay-slavov** [comment]
@vangogh500 did you find solution?

**Comment by colonaut** [comment]
//bundle into standalone script 
import {foo, bar} from apollo-react;
const ApolloReact = {
foo,
bar
}
export {
ApolloReact
}

//webpack
externals: [
react: 'React',
'react-dom': 'ReactDOM'
'apollo-react': 'ApolloReact'
]
