### ISSUE TITLE
Undocumented "prevProps" in graphql() config.props() ?

### ISSUE THREAD

**Issue by mefjuu** [apollographql/react-apollo#2054]
I've noticed during using HOC version of Apollo (`graphql()` fn) there is a second argument in `config.props()` function (https://www.apollographql.com/docs/react/api/react-apollo.html#graphql-config-props) containing something like _previous props_. It can be very useful at computing changed data from server into new props (instead of using the new `static getDerrivedStateFromProps()` React component's lifecycle method).

However I'm not sure if I can rely on it, because it's undocumented feature. Can anybody throw some light on it?

**Comment by danilobuerger** [comment]
Typing is
```
  props?: (
    props: OptionProps<TProps, TData, TGraphQLVariables>,
    lastProps?: TChildProps | void,
  ) => TChildProps;
```
So yes, the last props are returned as second argument. This is missing from the docs.

**Comment by mefjuu** [comment]
Okay, but hey! Those lastProps aren't cleared in a new component's instance!

**Comment by hwillson** [comment]
The [`config.props`](https://www.apollographql.com/docs/react/api/react-apollo/#configprops) section of the docs has been updated to mention and demonstrate `lastProps`. Thanks!
