### ISSUE TITLE
Query Component refetch() throw ApolloError when errorPolicy is "none"

### ISSUE THREAD

**Issue by leeric92** [apollographql/react-apollo#2058]
**Intended outcome:**

When errorPolicy is not set (or `none`) on ApolloClient and refetch is called inside the Query component to retrieve new set of data, Apollo should not throw ApolloError in console

**Actual outcome:**

When calling refetch(), the result came back as object with `data` attributes that contains the GraphQL JSON data and `errors` attribute which is an empty array (in scenario where there is no network error nor server error). Apollo see the result.errors && errorPolicy === `none` and automatically reject with ApolloError

<img width="304" alt="screen shot 2018-05-30 at 11 00 09 am" src="https://user-images.githubusercontent.com/9619534/40739028-f57cb388-63f9-11e8-9322-b82d632106ae.png">

<img width="654" alt="screen shot 2018-05-30 at 11 00 21 am" src="https://user-images.githubusercontent.com/9619534/40739038-fcc644a6-63f9-11e8-84c2-7876b552a3a5.png">

<img width="515" alt="screen shot 2018-05-30 at 11 03 38 am" src="https://user-images.githubusercontent.com/9619534/40739049-016e2118-63fa-11e8-9cce-cd682325e235.png">

**How to reproduce the issue:**

Create any Query component with GraphQL query, schema and resolver. Call refetch() inside the Query component and observe the error

<img width="640" alt="screen shot 2018-05-30 at 11 16 08 am" src="https://user-images.githubusercontent.com/9619534/40739393-e2cfa1cc-63fa-11e8-8b73-7e421049a794.png">

**Version**

* apollo-client@2.2.3
* react-apollo@2.1.0

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
