### ISSUE TITLE
Add flow typings

### ISSUE THREAD

**Issue by jbaxleyiii** [apollographql/react-apollo#207]

**Comment by rricard** [comment]
Still not done ? I could do that if still interested...

**Comment by helfer** [comment]
@rricard yes, please do!

**Comment by rricard** [comment]
Will do that for apollo-client as well...

**Comment by Grmiade** [comment]
Any update on this?

**Comment by helfer** [comment]
@Grmiade what kind of flow typings are you looking for? For queries, we usually generate flow types with apollo-codegen. If you're looking for flow typings for the react-apollo API, we'd be happy to get a PR from someone to add them (if that's possible).

**Comment by jbaxleyiii** [comment]
Starting on this project this week 👍

**Comment by TSMMark** [comment]
Hey guys what is this issue regarding exactly? I'm using apollo-codegen and it works great.

However, I have another issue which may or may not be related to this issue. 

If I type the props of an inner / unconnected component, it does not make it up to the connected component, after all the higher-order components are applied. For example:

```jsx
class MyInnerComponent extends Component {
  props: {
    myProp: string
  }

  // ... etc

}

const MyConnectedComponent = compose(
  connect(mapStateToProps, null, null, { withRef: true }),
  graphql(query, queryOptions), 
  graphql(mutation, mutationOptions) // mutationOptions includes withRef: true
)(MyInnerComponent)

// Flow notices the invalid number type
<MyInnerComponent myProp={5} />

// Flow does not notice the invalid number type here. Sad!
<MyConnectedComponent myProp={5} />
```

Not sure if it matters but both `queryOptions` and `mutationOptions` contain `withRef: true`.

Am I doing something wrong?

**Comment by TSMMark** [comment]
I think I got something working. I'm manually typing the connected component, like so:

```js
const MyConnectedComponent: Class<React$Component<DefaultProps, Props, State>> = compose(
```

The only issue with that is that `type Props` includes Apollo props such as `data`. To make it work I broke `Props` type into pieces using flow intersection types `&`.

```js
const MyConnectedComponent: Class<React$Component<DefaultProps, OwnProps, State>> = compose(
```

**Comment by Panoplos** [comment]
Any update on this? I am looking to use flow types in my HOC definitions, especially for the propType that is being pushed down into the enhanced component. Something like:

```es6
const withl10n = (name: string, resourceIds: [string]) => compose(
	setPropTypes({
		[name]: <NEEDS GRAPHQL RESULT TYPE>
	}),
	withLocaleInfo(false, true),
	graphql(
		gql`
			query localise($locale: LocaleType!, $resourceIds: [String]) {
				l10nSlugs(locale: $locale, resourceIds: $resourceIds) {
					id
					resourceId
					slug
				}
			}
		`,
		{
			name,
			options: ({ locale }) => ({
				variables: {
					locale,
					resourceIds
				},
			})
		}
	)
)
```
