### ISSUE TITLE
Absent Id's in "adjacent" query causing app to crash

### ISSUE THREAD

**Issue by dan-weaver** [apollographql/react-apollo#2073]
This is probably a weird edge case, but we've run into it a couple times by accident. When a query is mounted that contains sub entities (in the reproduction's case, pets), and a subsequent query which doesn't contain id's of sub entities the query results are undefined and that often causes the react component to crash. 

I'm assuming this is happening because it's an ambiguous situation.  Apollo has normalized objects residing in one of it's queries, and it's getting objects that it can't normalize in the new query.  It's technically user error, but it's a somewhat easy error to run into.  I'm not really sure if this should be fixed in the react integration or the client itself.

**Intended outcome:**
There should be some sort of warning that indicates there was a problem writing to the cache.  I've run into similar issues like this where react-apollo and apollo-client both have not reported a problem.  I'm wondering if it's a good idea to monitor some kind of invariant even if at this very moment we can't quite discern the problem and at least produce a warning.  For instance, while a query is mounting, should loading ever be false while the query result is undefined?  Or maybe something else along those lines.

**Actual outcome:**
The query results return undefined and the component will most likely crash as it's not expecting this to be the case

**How to reproduce the issue:**
I've reproduce the issue here https://github.com/dan-weaver/react-apollo-error-template.  Just run `yarn install && yarn start` and it should occur.

**Version**

* apollo-client@2.3.2
* react-apollo@2.1.4

I'd love to help out but hope for a bit of guidance if possible thanks!

- [x] has-reproduction

**Comment by rosskevin** [comment]
react-apollo is not responsible for the cache or normalization funtionality. Please file an issue with apollo-client.
