### ISSUE TITLE
Query context `client` should not have PropType `isRequired`

### ISSUE THREAD

**Issue by gtod** [apollographql/react-apollo#2074]
The `client` context [here in Query.tsx](https://github.com/apollographql/react-apollo/blob/38f07d6b2ed8ca3c7cea2320473a827af70a253b/src/Query.tsx#L127) should not be marked as `isRequired` as follows:
```ts
export default class Query<TData = any, TVariables = OperationVariables> extends React.Component<
  QueryProps<TData, TVariables>
> {
  static contextTypes = {
    client: PropTypes.object.isRequired,
    operations: PropTypes.object,
  };
  ...
```
_because it is optional_ specifically in the case that `Query` is supplied an explicit `client` prop, as evidenced in the constructor:
```tsx
  constructor(props: QueryProps<TData, TVariables>, context: QueryContext) {
    super(props, context);

    this.client = props.client || context.client;
    invariant(
      !!this.client,
      `Could not find "client" in the context of Query or as passed props. Wrap the root component in an <ApolloProvider>`,
    );
    this.initializeQueryObservable(props);
  }
```
[from here in Query.tsx](https://github.com/apollographql/react-apollo/blob/38f07d6b2ed8ca3c7cea2320473a827af70a253b/src/Query.tsx#L163)

#### Intended outcome
No console warning when an `ApolloProvider` is not used and an explicit `client` prop is supplied to `Query`. 

#### Actual outcome
See Reproduce below.
#### Reproduce
This sandbox https://codesandbox.io/s/mj2p2qwry8 works, but if you check the console log you will see the error:
```
Warning: Failed context type: The context `client` is marked as required in `Query`, but its value is `undefined`.
    in Query (created by ExchangeRates)
    in ExchangeRates (created by App)
    in div (created by App)
    in App
```

#### Version
- apollo-boost 0.1.7 (=> apollo-client 2.3.2)
- react-apollo 2.1.4

**Comment by xialvjun** [comment]
https://github.com/apollographql/react-apollo/pull/2112    wait for merge... or reject...

**Comment by rosskevin** [comment]
I verified this has been fixed on master
