### ISSUE TITLE
Recommended way to replicate `onCompleted` in Mutation children

### ISSUE THREAD

**Issue by Emsu** [apollographql/react-apollo#2079]
I am using Ant.Design Forms which uses an imperative function `resetFields` to clear a form. Currently, I can't figure out a way to use called, data, error and loading to replicate a one time onCompleted function to call resetFields once upon mutation success.

I'm thinking maybe I need to wrap the whole Mutation element in a Form and then pass the form props down to the Mutation children but it seems really hacky. Is there a recommended way to replicate onCompleted in the Mutation children? Or a way to reset the `data` prop pass down in a mutation back to undefined as if the mutation never happened?

**Comment by danilobuerger** [comment]
Issues here are reserved for bugs, but one of the following resources should help:

* Apollo's Slack: https://www.apollographql.com/slack
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests
