### ISSUE TITLE
snapshot tests with mockdata will always render components in `loading: true`state

### ISSUE THREAD

**Issue by macrozone** [apollographql/react-apollo#2088]
Using snapshot testing with mockdata is a simple way to test the "wiring" of your components to the server's graphql schema. Using storybook and https://github.com/abhiaiyer91/apollo-storybook-decorator  allows you to test your components with graphql data in isolation. Storybooks' storyshot feature can do automatic snapshot testing with the defined stories.

This setup is very easy to do, unfortunatly, jest will always snapshot the components while loading is true: `{loading: true}` and before the data arrives. So there should be some api to disable this loading step.

Is there an api to do that? 

**Intended outcome:**

I am able to do use apollo's mock features with snapshottesting and bypass the loading step.

**Actual outcome:**

The snapshot will alway render the component when `{loading: true}`

**Version**

* apollo-client@2.1.3
* react-apollo@2.1.3

**Comment by brunoreis** [comment]
Please @macrozone, have you found any workaround for this? I'm looking for the same thing right now.

**Comment by JAFong** [comment]
Any ideas on how to do this with `jest` `.toMatchSnapshot()`?  I've tried adding the code below but it doesn't seem to change the output of the snapshot:

```
expect.addSnapshotSerializer({
  test: element => wait(0).then( () => element ),
  printL element => prettyFormat(element, {
    plugins: [ReactTestComponent],
    printFunctionName: false,
  })
})

expect(toJSON(component)).toMatchSnapshot()
```

**Comment by rosskevin** [comment]
Closing - housekeeping

**Comment by remolueoend** [comment]
Not sure since when this feature is available, but storybook/storyshot-core describes here how to snapshot async components: https://github.com/storybooks/storybook/tree/master/addons/storyshots/storyshots-core#storyshots-for-async-rendered-components
