### ISSUE TITLE
Replace ObservableQueryFields with ObservableQuery in apollo-client

### ISSUE THREAD

**Issue by skovy** [apollographql/react-apollo#2092]
**Intended outcome:**

 - [ ] `react-apollo` uses the types defined in `apollo-client` added in https://github.com/apollographql/apollo-client/pull/3140

**Actual outcome:**

- [ ] The types are defined twice, in both `react-apollo` and `apollo-client` 😱 

**How to reproduce the issue:**

This is a basic example. With the update `previousQueryResult` should be typed as `PersonQueryResult`. See this `apollo-client` issue: https://github.com/apollographql/apollo-client/issues/3391

```typescript
const GET_PERSON = gql`
  {
    person {
      id
      name
    }
  }
`;

interface PersonQueryResult {
  person: {
    name: string;
  }
}

class PersonQuery extends Query<PersonQueryResult> {};

class MyComponent extends React.Component {
  render() {
    return <PersonQuery query={GET_PERSON}>
      {({ subscribeToMore }) => {
        subscribeToMore({
          document: GET_PERSON,
          updateQuery: (previousQueryResult) => {
            return previousQueryResult;
          }
        });

        return <div />;
      }}
    </PersonQuery>
  }
}
```

**Relevant PRs**:

- [Improve subscribeToMore types](https://github.com/apollographql/react-apollo/pull/2093)
- [Improved type definitions for the observable query](https://github.com/apollographql/apollo-client/pull/3140)
- [Improve Query and graphql types. Strict type check with Typescript](https://github.com/apollographql/react-apollo/pull/1617/files#diff-45a733ae4e94396f8fa0947302418680)

**Comment by rosskevin** [comment]
PR welcome.

**Comment by hwillson** [comment]
This was addressed in https://github.com/apollographql/react-apollo/pull/2281. Thanks!
