### ISSUE TITLE
Umd entries appear to be wrong - react-dom being pulled into native 

### ISSUE THREAD

**Issue by L0wry** [apollographql/react-apollo#2096]
When running react-native with react-apollo @2.1.4

there are two umd entry files 
`react-apollo.umd`
`react-apollo.browser.umd`

When running React Native on a device the packer fails due to 
`react-dom/cjs/react-dom-server.node.production.min.js`: Module does not exist in the module map`

I have noticed that in 
`react-apollo.umd` you are pulling in `react-dom` stuff 
and in 
`react-apollo.browser.umd` you are not 

This to me suggests that the umd entry files are incorrect.

To replicate run a react native project packager for Ios or android

- [ x] has-reproduction
- [ x] blocking

**Comment by L0wry** [comment]
#tumbleweed

**Comment by L0wry** [comment]
@rosskevin any possibility to shed some light?

**Comment by rosskevin** [comment]
@L0wry I am not a native user but an entry that transitively references it sounds plausible. I would start by looking at the roll up configs. PRs are welcome

**Comment by rosskevin** [comment]
PR welcome.

**Comment by hwillson** [comment]
This should no longer be an issue with current day versions of `react-apollo` (see the `react-apollo` 2.3.2 [changelog](https://github.com/apollographql/react-apollo/blob/master/Changelog.md#bug-fixes-8) for details). Thanks!
