### ISSUE TITLE
Should not attempt to parse the body-text of 5xx errors as JSON

### ISSUE THREAD

**Issue by MikeTaylor** [apollographql/react-apollo#2100]
**Intended outcome:**

Access in my client code to the diagnostic information that a GraphQL server sent along with a 5xx diagnostic code.

**Actual outcome:**

Apollo tries to parse the non-JSON body text, and fails. As a result, `data.error.message` does not helpfully contain the body text from the failed request's response, "proxyRequestResponse failure: mod-graphql-0.1.0 http://127.0.0.1:3000: Connection refused", but an error about the failure to parse it: "Unexpected token p in JSON at position 0".

**How to reproduce the issue:**

Submit any query against any GraphQL server that fails with a 5xx error. A diagnostic code in the 5xx space means that all bets are off regarding what kind of context will come back in the response body, and the client library should not attempt to interpret it as XML, JSON, or whatever.

**Version**

* apollo-client@^2.0.3
* react-apollo@^2.1.3

**Comment by rosskevin** [comment]
react-apollo does no parsing, perhaps look at apollo-link-http or apollo-client and submit an issue there.
