### ISSUE TITLE
Query Component (returns data = {}) when re-render with same query and variables objects

### ISSUE THREAD

**Issue by serle** [apollographql/react-apollo#2101]
When re-rendering the query component with the same query and variable objects, but with changes to fields within the variables object, the render function inside <Query/> gets called with the data property = {} instead of an actual query result. It seems to not make a query at all either form the cache or the network. This is independent of the fetchPolicy set on the <Query/> component.

Reproduce the error by 
1) store the query and variables in state.
2) retrieve them and use them to render the <Query/>
3) in a callback modify the variables object (in state) and either forceUpdate or modify another state variable to cause a re-render
4) monitor the { data, loading, error } props on re-render

To prevent the error.
Just before rendering the <Query/> create a new object with the variables in e.g. `new_vars = Object.assign({}, old_vars)`. This causes it all to work.

**Comment by vchrpng** [comment]
I have the same issue here.

**Comment by matsimitsu** [comment]
Wow, this took me almost a full day to debug. In my case I was modifying an array of strings but it had the same result. 

E..g for this query:

```graphql
export default gql `query PerformanceIncidentsQuery(
    $appId: String!,
    $namespaces: [String],
  ) {
    app(id: $appId) {
      id
      performanceIncidents(namespaces: $namespaces) {
        ...PerformanceIncidentRow
      }
    }
  }
  ${PerformanceIncidentRowFragment}
`
``` 

And this HoC:

```js
export const withIncidents = graphql(PerformanceIncidentsQuery, {
  options: ({ appId, namespaces }) => ({
    notifyOnNetworkStatusChange: true,
    variables: {
      appId: appId,
      namespaces: namespaces
    }
  }),
})
```

I would get `app` is undefined on data on every 1 in 4/5 requests and not consistently with the same data.

Even when disabling caching it would still cause an undefined error. 

The solution was to slice the `namespaces` array.

```js
export const withIncidents = graphql(PerformanceIncidentsQuery, {
  options: ({ appId, namespaces }) => ({
    notifyOnNetworkStatusChange: true,
    variables: {
      appId: appId,
      namespaces: namespaces.slice()
    }
  }),
})
```

**Comment by hwillson** [comment]
To address this, set the `returnPartialData` prop of your `Query` component to `true` (assuming you're using `react-apollo` >= 2.5.6). For the full details on why this helps, see the [release notes](https://github.com/apollographql/react-apollo/blob/master/Changelog.md#improvements-1). Thanks!
