### ISSUE TITLE
Question: getDataFromTree performance and caching

### ISSUE THREAD

**Issue by darkowic** [apollographql/react-apollo#2122]
**Question**
I would like to know how to improve and cache getDataFromTree execution. Is it possible now?

`getDataFromTree` is slow - 1.5 slower than render to string in my case
```
getDataFromTree: 323.082ms
renderToString: 264.504ms
```
In my application I have around 6 queries executed on server side. Few of them are queries that could be easily cached and they do not need to walk the tree every time the request comes to server.

Do you have any recommendation, tips etc how to improve it? I did't found any usefull posts/issues about performance of `getDataFromTree` function

**Version**

* apollo-client@2.2.5
* react-apollo@2.1.4

**Comment by mike-marcacci** [comment]
Hey @darkowic, I doubt that delay is coming from walking the tree, unless it is really huge. Do you happen to know how much time the queries themselves are taking?

One thing that can help improve performance is making sure no nested `Query`'s depend on the results of ancestral `Query`'s, since this requires them to be executed sequentially.

**Comment by mjamado** [comment]
I'm also seeing this. Right now, I have this timings (dev machine):

Full render: 728.751ms
 |-- getDataFromTree: 542.266ms
 |----|-- fetch: 197.089ms (5 queries, batched together)
 |-- renderToStaticMarkup: 169.255ms

It seems that getDataFromTree is the bottleneck here. Is there something that can be done?

**Comment by benjamn** [comment]
The implementation of `getDataFromTree` has changed substantially in `react-apollo@2.3.1` (the latest version), thanks to #2533. Please try updating!

**Comment by rosskevin** [comment]
Closing - housekeeping.
