### ISSUE TITLE
skip + pollInterval keeps polling

### ISSUE THREAD

**Issue by ksmth** [apollographql/react-apollo#2127]
**Intended outcome:**
No network requests and/or queries are run

**Actual outcome:**
Apollo polls every 1s

**How to reproduce the issue:**
```
<Query skip pollInterval={1000} />
```

**Version**

* apollo-client@2.3.1
* react-apollo@2.1.4

**Comment by serranoarevalo** [comment]
Any workaround for this?

**Comment by zapo** [comment]
We workaround it using our own wrapper which will drop the `pollInterval` prop when `skip`ing:

```
import React from 'react';
import { Query as WrappedQuery, OperationVariables, QueryProps, QueryResult } from 'react-apollo';

function Query<TData, TVariables = OperationVariables>(props: QueryProps<TData, TVariables>)
: JSX.Element {
  // FIXME: https://github.com/apollographql/react-apollo/issues/2127
  const { pollInterval, ...propsNoPoll } = props;
  return <WrappedQuery { ...props.skip ? propsNoPoll : props }/>;
}

export { Query };
```

**Comment by azurechen** [comment]
I met the same issue but only happened at re-rendering.
The first time rendering `pollInterval` respected `skip` props but after re-rendering, polling every time even the `skip` is true.

**Comment by yleviel-notarize** [comment]
The workaround is to set pollInterval to 0 or the value.
```
<Query pollInterval={shouldSkip ? 0 : 1000 } />
```

**Comment by theJian** [comment]
Is it considered a bug? Will it be fixed?

**Comment by mikeyshing88** [comment]
I'm using state to hide/show a component that is using the `useQuery` hook with a set poll interval. Once the component is hidden, the query keeps on polling.

I don't believe this is intended and is a bug?

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!

**Comment by lucasconstantino** [comment]
This is still happening with:

```
"@apollo/react-hooks": "^3.1.3",
"react-apollo": "^3.1.3",
```

**Comment by shachyjr** [comment]
I'm seeing this also. My query looks like this:
```
useQuery(GET_CATS, {
        variables: {
            breed,
            domestic,
        },
        skip: !breed || !domestic,
        pollInterval: 10000
    });
```
I get this error that the required variable `breed` is not provided. So, it seems to me like the poll interval is ignoring the skip.
For the time being, the fix `pollInterval: breed ? 10000 : 0` worked but this should be addressed.

The versions I'm using:
```
"@apollo/react-hooks": "3.1.1",
"@apollo/react-ssr": "3.1.1",
```

**Comment by niamleeson** [comment]
Please re-open this issue. This issue is still happening with hooks.

**Comment by slorber** [comment]
Hey,


It's not totally clear to me how to achieve:
- Do not run the query on mount
- Set poll interval to "x"
- Start first polling after "x"


Also it's not clear how polling works regarding fetchPolicy. Does polling always hit the network?

**Comment by aaronmcadam** [comment]
I've just. hit this. Can this issue be reopened?

**Comment by niamleeson** [comment]
Because we wanted `skip` to ignore `pollInterval`, we just wrapped `useQuery` like this:

```
import { useQuery as useQueryApollo } from '@apollo/react-hooks';

export const useQuery = (query, options = {}) => {
    if (options.pollInterval) {
        options.pollInterval = options.skip ? 0 : options.pollInterval;
    }

    return useQueryApollo(query, options);
};
```

**Comment by aaronmcadam** [comment]
Yeah I'm doing something similar, thanks @niamleeson. I just thought it was worth bumping this again. Hopefully it's something that could be fixed in Client v3.
