### ISSUE TITLE
Feature idea: `mapMutationsToProps`

### ISSUE THREAD

**Issue by barlock** [apollographql/react-apollo#2132]
**Intended outcome:**
Adding mutation functions to props can be a bit tedious and verbose. The current pattern can be tricky to test and is hard to reuse. Taking the [ducks pattern](https://github.com/erikras/ducks-modular-redux) connecting a component to apollo could be made a bit simpler and easier to test in isolation. 

**Proposed API:**

Code often speaks better than descriptions:
```js
// ApolloToDo.js
import { AddTodoMutation, RemoveToDoMutation } from './mutations.graphql'; 
import { mapMutationsToProps } from 'react-apollo';

const ToDo = ({ addTodo, removeTodo }) => (
  <div>
    <button onClick={addTodo}>Add</button>
    <button onClick={removeTodo}>Remove</button>
  </div>
);

// Create some "mutationCreators", functions that take some input and return a "mutation"
const addToDo = (todo) => ({ mutation: AddTodoMutation, variables: { todo } });
const removeToDo (todo) => ({ mutation: RemoveToDoMutation, variables: { todo } });

export default mapMutationsToProps({
  addTodo,
  removeTodo 
})(ToDo); 
```

vs

```js
// ApolloToDo.js
import { AddTodoMutation, RemoveToDoMutation } from './mutations.graphql'; 
import { graphql } from 'react-apollo';

const ToDo = ({ addToDo, removeTodo }) => (
  <div>
    <button onClick={() => addToDo(variables: { ... }}>Add</button>
    <button onClick={() => removeTodo(variables: { ... }}>Remove</button>
  </div>
);

export default compose(
	graphql(AddTodoMutation, { name: 'addToDo' }),
	graphql(RemoveToDoMutation, { name: 'removeTodo' }),
)(ToDo); 
```

The `mapMutationsToProps` would appropriately wrap the `mutationCreator` with a `client.mutate` call. This would also make transitioning from redux to apollo-link-state a bit easier as there are famillar concepts. I envision the api to be identical to redux's taking either a plain map of mutationCreators or a function taking `(mutation, ownProps)` and returning a map of mutationCreators.

Rough solution for clarity:
```js
export const mapMutationsToProps = mutationMapper => compose(
  withApollo,
  withHandlers(({ client, ...ownProps }) => {
    if (typeof mutationMapper === 'function') {
      const mutations = mutationMapper(client.mutate, ownProps);

      return Object.keys(mutations)
        .reduce((handlers, mutation) => {
          const mutationCreator = mutations[mutation];

          handlers[mutation] = props => (...args) => mutationCreator(...args);

          return handlers;
        }, {});
    } else {
      return Object.keys(mutationMapper)
        .reduce((handlers, mutation) => {
          const mutationCreator = mutationMapper[mutation];

          handlers[mutation] = props => (...args) =>
            props.client.mutate(mutationCreator(...args));

          return handlers;
        }, {});
    }
  })
);
```

I'd be happy to make a pr.

Similar issue for reference https://github.com/apollographql/react-apollo/issues/29

**Comment by rosskevin** [comment]
We are favoring render callback patterns over hocs, and I suspect in the near future will instead be favoring hooks over all of the above. I don't think we want to take on more helper code to maintain and document for hocs, so I'm going to close this out. Please feel free to change my mind!
