### ISSUE TITLE
SSR: `instance.fetchData()` does not resolve

### ISSUE THREAD

**Issue by freder** [apollographql/react-apollo#2136]
hi,

I am trying to implement SSR for an application, but `getDataFromTree` never resolves, because `instance.fetchData()` in `getPromisesFromTree` never resolves (nor is there an error).

I'm using the simplest possible setup: rendering a single component with a single (simple) query.

obviously everything works fine in the browser.

```
npm ls --depth=1 | ag apollo
├─┬ apollo-client-preset@1.0.8
│ ├── apollo-cache-inmemory@1.2.1
│ ├── apollo-client@2.3.1
│ ├── apollo-link@1.2.2 deduped
│ ├── apollo-link-http@1.5.4 deduped
├─┬ apollo-link@1.2.2
│ ├── apollo-utilities@1.0.12 deduped
├─┬ apollo-link-context@1.0.8
│ └── apollo-link@1.2.2 deduped
├─┬ apollo-link-http@1.5.4
│ ├── apollo-link@1.2.2 deduped
│ └── apollo-link-http-common@0.2.4
├─┬ apollo-link-ws@1.0.8
│ └── apollo-link@1.2.2 deduped
├── apollo-utilities@1.0.12
│ ├── apollo-link@0.7.0
│ ├── apollo-link-http@0.7.0
├─┬ react-apollo@2.1.6
```

**Comment by freder** [comment]
made a stripped down example: https://github.com/freder/react-apollo-2136

looks like, as long as I only use the http link, it works. but now it looks like this is happening, as well: https://github.com/apollographql/react-apollo/issues/1361

[loggin](https://github.com/freder/react-apollo-2136/blob/master/src/SsrTest.js#L11) reveals that the component gets rendered twice. the first time it has received the data already, the second one is in loading state:

```
{ variables: {},
  refetch: [Function],
  fetchMore: [Function: bound ],
  updateQuery: [Function: bound ],
  startPolling: [Function: bound ],
  stopPolling: [Function: bound ],
  subscribeToMore: [Function: bound ],
  loading: false,
  networkStatus: 7,
  error: undefined,
  allItems:
   [ { id: '11111', __typename: 'Item' },
     { id: '22222', __typename: 'Item' } ] }
{ variables: {},
  refetch: [Function],
  fetchMore: [Function: bound ],
  updateQuery: [Function: bound ],
  startPolling: [Function: bound ],
  stopPolling: [Function: bound ],
  subscribeToMore: [Function: bound ],
  loading: true,
  networkStatus: 1,
  error: undefined }
<span data-reactroot="">no allItems</span>
```

**Comment by benjamn** [comment]
The implementation of `getDataFromTree` has changed substantially in `react-apollo@2.3.1` (the latest version), thanks to #2533. Please try updating!

**Comment by rosskevin** [comment]
Closing - cleanup.
