### ISSUE TITLE
getDataFromTree does not call getDerivedStateFromProps

### ISSUE THREAD

**Issue by darkowic** [apollographql/react-apollo#2137]
**Intended outcome:**

`getDerivedStateFromProps` should be called before executing query

**Actual outcome:**
`getDerivedStateFromProps` is not called

**How to reproduce the issue:**
`getDataFromTree` just do not call the `getDerivedStateFromProps` when parsing the tree

**Version**

* apollo-client@^2.2.5
* react-apollo@^2.1.4

Workaround for now
```
class SomeComponent extends React.Component {
  constructor(props) {
    super(props);
    // react-apollo's getDataFromTree does not call getDerivedStateFromProps method
    // https://github.com/apollographql/react-apollo/issues/2137
    this.state = SomeComponent.getDerivedStateFromProps(props)
  }
```

**Comment by rosskevin** [comment]
You have described something that should happen without describing a problem.  If you are experiencing misbehavior of one of the components, please consider PRing a failing test.
