### ISSUE TITLE
Graphql HOC not passing properly variables for mutations

### ISSUE THREAD

**Issue by nacho-carnicero** [apollographql/react-apollo#2140]
**Intended outcome:**
Hello, 

I have recently upgraded react-apollo to the latest version from v2.0.4 and I am facing problems to carry out mutations properly. Indeed, my architecture is such that I wrap my component where I will use the mutation with the `graphql` HOC providing the authentification token such as:

```JS
const MyComponentWithMutations = compose(
  graphql(myFirstMutation, {
    name: "firstMutation",
    options: props => {
      return {
        fetchPolicy: "no-cache",
        variables: { token: props.auth.token },
        pollInterval: 0
      };
    }
  }),
  graphql(mySecondMutation, {
    name: "secondMutation",
    options: props => ({
      fetchPolicy: "no-cache",
      variables: { token: props.auth.token },
      pollInterval: 0
    })
  })
)(MyComponent);
```

Now inside `MyComponent` when I need to mutate data I call the mutation function with some additional variables:
```JS
this.props.firstMutation({
          variables: {
            firstVariable: "something",
            secondVariable: "somethingElse"
          }
        })
```

Finally in my client configuration I have an authentication link set up which looks for `token` in the mutation variables and fills the `header` with it:

```JS
// Auth Link
const authLink = new ApolloLink((operation, forward) => {
  const token = operation.variables.token;
  operation.setContext({
    headers: {
      authorization: token ? `Bearer ${token}` : null
    }
  });
  return forward(operation);
});
```

All of this used to work fine in v2.0.4, but it does not work anymore in versions v2.1.0 to v2.1.7.

The problem is that the `token` variable is not passed to the mutation. Indeed, if I log the variables that arrive to the authentication link like this:

```JS
// Auth Link
const authLink = new ApolloLink((operation, forward) => {
  const token = operation.variables.token;
  console.log(operation.variables);
  operation.setContext({
    headers: {
      authorization: token ? `Bearer ${token}` : null
    }
  });
  return forward(operation);
});
```

The only variables that I am able to see are:
```
{ firstVariable: "something",secondVariable: "somethingElse"}
```

Therefore the `token` that was defined in the upper-level `variables` field is not passed to the mutation, therefore my authentication header is empty and I am not able to perform mutations.

**Actual outcome:**
I would expect that, such as in v2.0.4, all the variables are correctly passed to my mutation.

**How to reproduce the issue:**
See code above

**Version**

* apollo-client@2.3.5
* react-apollo@2.1.7

**Comment by hwillson** [comment]
If this is still a problem using a current day version of `react-apollo`, and you can provide a small runnable reproduction that demonstrates this, we'll take a look. Thanks!
