### ISSUE TITLE
2.1.7 Release broken

### ISSUE THREAD

**Issue by danilobuerger** [apollographql/react-apollo#2143]
**Intended outcome:**

Upgrading from 2.1.6 to 2.1.7 works without any errors as semver just had a patch bump.

**Actual outcome:**

Running react-native tests does not work anymore:
```
Cannot find module 'react-apollo/test-utils'
```
Running react-native builds does not work anymore:
```
Couldn't find preset "env" relative to directory "node_modules/react-apollo"
```

node module contains whole git repos instead of just lib dir as in previous builds.

**How to reproduce the issue:**

Upgrade a react-native project with react-apollo 2.1.6 to 2.1.7 and run build

**Version**

* apollo-client@2.3.4
* react-apollo@2.1.7

**Comment by hwillson** [comment]
`react-apollo` 2.1.8 should now fix this @danilobuerger. Thanks for reporting this!

**Comment by danilobuerger** [comment]
confirmed, 2.1.8. fixes this issue. Thanks!
