### ISSUE TITLE
need some way to disable returnPartialData

### ISSUE THREAD

**Issue by kdong007** [apollographql/react-apollo#2160]
**Intended outcome:**
disable returnPartialData

**Actual outcome:**
no way to disable returnPartialData

**How to reproduce the issue:**
N/A

**Version**

"apollo-client": "^2.3.5",
"react-apollo": "^2.1.9",

**Comment by hwillson** [comment]
`returnPartialData` is disabled by default. If you want to enable it (as of React Apollo 2.5.6), you can set the `returnPartialData` prop to `true` in the `Query` component.
