### ISSUE TITLE
General: Update Apollo Client object on runtime

### ISSUE THREAD

**Issue by metpb** [apollographql/react-apollo#2167]
I am working on a project where I am using a Rest API for data (token) to be passed on to the GraphQL API later after authentication. 
The whole app is wrapped in an ApolloProvider object like the example below. 

```
const Client = new ApolloClient({
    link: new HttpLink({
        uri: [Broker Address],
        headers: {
            authorization: `[Bearer token to be retrieved using a Rest API]`,
         }
    }),
    cache: memoryCache
})
```

```
<ApolloProvider client={Client}>
    <AppNavigator />      
</ApolloProvider>
```

But since I am retrieving the graphql token after authentication from the Rest API, I won't be able to pass the data at initialisation.

The obvious (i might be wrong since I am really new to JS and RN) alternative is to have two separate navigators (one for the Rest auth flow, and the other for the GraphQL flow) and only to wrap the GraphQL based navigator with ApolloProvider.

But just wanted to check if there is a way to dynamically update the `HttpLink` or the `ApolloClient` object on the `ApolloProvider` wrapper later during runtime?

[Not sure if this a relevant question to be posted here as an issue, but did it anyway since the `react-apollo` community on StackOverflow is relatively small. Appreciate your understanding. Thanks!]

**Comment by metpb** [comment]
Never mind, solved using `setContext`.

**Comment by SimplyComplexable** [comment]
@metpb I'm encountering this same problem. Could you clarify how you solved it with `setContext`?
