### ISSUE TITLE
Distinguish Query error origin for pagination

### ISSUE THREAD

**Issue by bdrobinson** [apollographql/react-apollo#2173]
**Intended outcome:**

When rendering a `Query` component to retrieve a paginated list, I would like to be able to distinguish whether the `error` render prop arg corresponds to a failed initial request or a request due to `fetchMore`. This is because I want my UI to look different depending on the two situations.

**Actual outcome:**

The `error` arg does not give any indication as to whether it is from an initial request or an append request.

**How to reproduce the issue:**
Any `Query` that uses `fetchMore` and/or `refetch`.

**Version**

* apollo-client@2.3.5
* react-apollo@2.1.9

Thanks very much – I hope that makes sense.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, React Apollo feature requests are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Distinguish%20Query%20error%20origin%20for%20pagination&body=Migrated%20from:%20apollographql/react-apollo%232173) to start the feature request migration process. This manual migration process is intended to help identify which of the outstanding feature requests are still considered to be of value to the community. Thanks!
