### ISSUE TITLE
v3 bombs out npm install

### ISSUE THREAD

**Issue by chaffeqa** [apollographql/react-apollo#2179]
[The postinstall script](https://github.com/apollographql/react-apollo/blob/f0fbd4e103dcd514f365387df16a88fc7e668bdf/package.json#L30) bombs out `npm install` if `enzyme-adapter-react-16` is not installed (which is always in production... since that should be a dev dep).

Also to note that this approach seems poor... is there a better on?

**Comment by benjamn** [comment]
Enzyme is no longer involved in any npm scripts in this repository, so this issue should be resolved now.
