### ISSUE TITLE
Typescript type of props in graphql operation requires all props, even ones passed through

### ISSUE THREAD

**Issue by dobesv** [apollographql/react-apollo#2183]
When providing a `props` function to the `graphql` function, the return type of `props` is `TChildProps`, which means the function must return *all* props in `TChildProps` to avoid type errors.  However, the implementation actually merges the existing props in `TProps` with any newly added props returned by `props`.  Thus, the return type of `props` should be setup such that any props already in `TProps` are optional as they will be passed through.  Only attributes of `TChildProps` not in `TProps` should be required in the return type.

I'm not 100% sure what typescript magic is required to make this work, though.

As a workaround, I separated `TProps` and `TChildProps` completely and recombined them when I created the component using `&`, e.g. `class X extends React.Component<TProps & TChildProps>`.

**Comment by NAlexPear** [comment]
Just ran into this ☝️ issue, with an additional wrinkle that might help when repro-ing: this issue, from what I can tell, only affects `class` components for some reason. Here's a quick example case:

```javascript
import gql from 'graphql-tag'
import { graphql } from 'react-apollo'
import React, { Component } from 'react'


interface Props {
  id: string
}

interface Response {
  foo: string
}

type Variables = Props

interface ChildProps {
  results: string[]
}

// the results of this query will be mapped away later
const GET_THROWAWAY_RESULTS = gql`
  query getResults($id: String!){
    getResults(id: String!){
      foo
    }
  }
`

// ignores inputs in favor of results consistent with ChildProps
const mapResponseToProps = () => ({ results: ['foo', 'bar'] })

const mapResults = results => results.map((result, index) =>
  <li key={ index }>{ result }</li>
)


// FunctionComponent and ClassComponent should behave identically
const FunctionComponent = ({ results = [] }: ChildProps) =>
  <ol>
    { mapResults(results) }
  </ol>

class ClassComponent extends Component<ChildProps> {
  render(){
    const { results = [] } = this.props

    return <ol>
      { mapResults(results) }
    </ol>
  }
}

// type error: Property 'id' is missing in type 'Readonly<{ children?: ReactNode; }> & //Readonly<ChildProps>' but required  in type 'Readonly<ChildProps & Props>'. 
// (notice the union of ChildProps and Props)
export default graphql<Props, Response, Variables, ChildProps>(
  GET_THROWAWAY_RESULTS,
  {
    options: ({ id }) => ({
      variables: {
        id,
      },
    }),
    props: mapResponseToProps,
  }
)(ClassComponent) // types work fine with FunctionComponent
```

As @dobesv mentioned, the workaround for `class` components is to pass `<ChildProps & Props>` to `Component`, but this relaxes type checking against errors related to that initial `id`. Functional components seem to be appropriately typed in this example.

**Comment by hwillson** [comment]
Happy to review a PR for this - thanks!
