### ISSUE TITLE
"errors were thrown when executing your fetchData functions" doesn't show request in error

### ISSUE THREAD

**Issue by vjpr** [apollographql/react-apollo#2187]
```
{ error: { Error: 2 errors were thrown when executing your fetchData functions.
    at /xxx/node_modules/.registry.npmjs.org/react-apollo/2.1.9/node_modules/react-apollo/react-apollo.umd.js:156:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) queryErrors: [ [Object], [Object] ] } }
```

Notice how `queryErrors: [ [Object], [Object] ]` is not stringified.

This is in a SSR environment so its important that I see the errors printed in the console.

Related to https://github.com/apollographql/react-apollo/issues/282

**Comment by vjpr** [comment]
Turns out it was my own error handling being poor...

**Comment by vjpr** [comment]
However, the network error doesn't show the request so it is still hard to trace down.

**Comment by rosskevin** [comment]
Please PR a change if you would like to see one. Please feel free to ping me for a review on any PR
