### ISSUE TITLE
Mutation error is cached on re-render

### ISSUE THREAD

**Issue by metpb** [apollographql/react-apollo#2191]
I am using `react-apollo` on a `react-native` project and I am really new to the render-props way of thinking and react native, so please bear with me if this question sounds stupid.

I have a component (representational code below) which renders a list of buttons on whose tap the component state is updated and re-rendered, then on a separate button tap the `mutationCall` mutation function would be called using the `state`. (Not sure if the right way to do it though) The first call works fine if their was no error returned from the server. But I'm really confused on what's happening after I get an error from the server. After receiving an error it looks like the `Mutation` component is holding on to the error object instead of refreshing itself, due to which the alert message is shown on every subsequent re-render due to state change.

So I have two questions.
- Am I implementing it the wrong way?
- What's a better way to use `Query` & `Mutation` on a `react-native` project?

**Note:** I went to through the recently updated Mutation doc on the ApolloGraphql website but honestly they weren't helpful at all since there were no general `react-native` (or is it not aimed towards `react-native` users) examples on the site. Nor was anything written on what's a good way to use Mutation & Query. Was really excited to be using graphql on my app but this was a big turn-off because the learning curve felt, well, really steep.

Suggestions and criticisms are most welcome. Thanks!

```
render() {
    return (
      <View style={{ flex: 1 }}>
        <Mutation mutation={mutations.MutationCall}>
          {(mutationCall, { data, loading, error, called }) => {
            if (loading) {
              return (
                <LoadingIndicator />
              );
            }

            if (error) {
              Alert.alert("Error", error.message);
              return (
                <View style={styles.container}>
                  {this._renderHeader()}
                  {this._renderMainContent()}
                  {this._renderButton(mutationCall)}
                </View>
              );
            }

            return (
              <View style={styles.container}>
                {this._renderHeader()}
                {this._renderMainContent()}
                {this._renderButton(mutationCall)}
              </View>
            );
          }}
        </Mutation>
      </View>
    );
  }
}
```

**Version**

* apollo-client@2.3.5
* react-apollo@2.1.6

**Comment by AviIhej** [comment]
Hi,

I am having this exact same problem.
If anybody has found the solution to this please share it. Thanks!
I have a form and when someone tries to submit the form (thus triggering a GQL mutation), I get an error thrown from the server, but when the person wants to go and fill in the missing fields an error is thrown on every keystroke. Again, after the initial error is thrown from the server, the same error is thrown every time the user presses a key.

I am using React Apollo and the Mutation component.

Let me know if you found the solution!

**Comment by hwillson** [comment]
This should no longer be an issue with current day `react-apollo`. Let us know otherwise - thanks!
