### ISSUE TITLE
Feature Request: Subscription component need a property similar to skip on the Query

### ISSUE THREAD

**Issue by serle** [apollographql/react-apollo#2200]
I would like to be able to be subscribed to events only while a given property holds true. This would be similar to the skip property on the Query component but it should control the subscribe/unsubscribe messaging.

If skip == true the Subscription unsubscribes
if skip == false the Subscription subscribes or reSubscribes

**Comment by hotgazpacho** [comment]
What's interesting is that the subscribe HOC explicitly allows you to pass in a skip option (a function that allows you to compute from props whether execution should be skipped or not): 
https://github.com/apollographql/react-apollo/blob/a3c49ce6bab44bf9a7c130d060da74aaa2e162d0/src/subscription-hoc.tsx#L30

which it executes https://github.com/apollographql/react-apollo/blob/a3c49ce6bab44bf9a7c130d060da74aaa2e162d0/src/subscription-hoc.tsx#L63 

and then passes on to the `Subscription` component https://github.com/apollographql/react-apollo/blob/a3c49ce6bab44bf9a7c130d060da74aaa2e162d0/src/subscription-hoc.tsx#L78
 
However, if you look at the code for the `Subscription` component, nowhere does it DO anything with the skip prop! It just merrily goes about subscribing! https://github.com/apollographql/react-apollo/blob/a3c49ce6bab44bf9a7c130d060da74aaa2e162d0/src/Subscriptions.tsx#L73-L75

It seems to me that:
1. `componentDidMount` should check for the `skip` prop before subscribing
2. `componentWillUnmount` should check if a subscription exists before attempting to unsubscribe.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, React Apollo feature requests are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Feature%20Request%3A%20Subscription%20component%20need%20a%20property%20similar%20to%20skip%20on%20the%20Query&body=Migrated%20from:%20apollographql/react-apollo%232200) to start the feature request migration process. This manual migration process is intended to help identify which of the outstanding feature requests are still considered to be of value to the community. Thanks!
