### ISSUE TITLE
The triggering of the mutation props "update" / "refetchQueries" / "onCompleted" is confused 

### ISSUE THREAD

**Issue by softhib** [apollographql/react-apollo#2201]
**Intended outcome:**
We expect the possibility to control the order of the triggering for the following mutation props:
- `update`
- `refetchQueries`
- `onCompleted`

Personally I expect that order:
1. mutation is executed
2. all the instructions of the `update` bloc are executed
3. then `refetchQueries` is triggerd
4. `onCompleted` is triggered at the very end 

**Actual outcome:**
It's very complicated (impossible ?) to know in what order this functions are triggered. 
It seems that `refetchQueries` cancel the triggering of `onCompleted`. In addition, `refetchQueries` is triggered before the end of the `update`. It is a real problem to not being able to control in which order the instructions are executed because it is a source of bugs

**How to reproduce the issue:**
Try something like this: 
```javascript
<Mutation
        mutation={MutationLogin}
        update={async (cache, { data: { login } }) => {
          console.log("===============start update=====================");
          await AsyncStorage.setItem("jwt", login.jwt);
          console.log("===============after setItem jwt=====================");
          const data = await cache.readQuery({ query: QueryUserLoggedInfos });
          data.userLogged = login;
          console.log("===============before write=====================");
          await cache.writeQuery({ query: QueryUserLoggedInfos, data });
          console.log("===============after write=====================");
        }}
        errorPolicy="all"
        onCompleted={async data => {
          console.log("================onCompleted====================");
        }}
        refetchQueries={() => {
          console.log("================refetchQueries====================");
          return ["UserLoggedInfos"];
        }}
>

result : 
16:54:45
===============start update=====================
16:54:45
================refetchQueries====================
16:54:45
===============after setItem jwt=====================
16:54:45
===============before write=====================
16:54:45
===============after write=====================
```

- To me `refetchQueries` must be trigged after `after  `.
- It seems that `refetchQueries` cancel the triggering of `onCompleted`. 
- In addition, `refetchQueries` is triggered before the end of the `update`.

 

It is a real problem to not being able to control in which order the instructions are executed.
 
**Version**
* react-apollo@<2.1.9>

**Comment by escapiststupor** [comment]
Same here for `"react-apollo": "^2.1.11"`

**Comment by mattdamon108** [comment]
I'm experiencing same problem here. It seems refetchQueries cancel onCompleted callback.

**Comment by rosskevin** [comment]
Perhaps you are over thinking this. It seems to me that either you don't need the update block if you are going to refetch, or you can trigger the refetch after you have made your modifications in the update block. 

I think the tools for flow control are already provided. If not, please ping me with an explanation why it is not and I will reopen.
