### ISSUE TITLE
graphql HOC pass null to optional arguments if the variables is omitted in options

### ISSUE THREAD

**Issue by trungtin** [apollographql/react-apollo#2205]
**Intended outcome:**

Consistent behavior when either `options` include `variables` or not

**Actual outcome:**

When the variables object is omitted the optional argument is pass null. Which in turn throw error similar to "Argument to $skip must be a number not a null"

**How to reproduce the issue:**
```
query FeedQuery($limit: Int, $skip: Int) {
  FeedQuery(limit: $limit, skip: $skip){
    hasNextPage
  }
}

// This work
graphql(JoynFeedQuery, {
    options: () => {
      return {
        variables: {},
      }
    },
  })

// This return error
graphql(JoynFeedQuery, {
    options: () => {
      return {},
      }
    },
  })
```

**Version**

* apollo-client@2.3.5
* react-apollo@2.1.9

**Comment by nandito** [comment]
I created a [Sandbox](https://codesandbox.io/s/kkk90vo10r) on CodeSandbox to reproduce this issue.

I think I found the source of the problem, it seems that it is the condition of [this](https://github.com/apollographql/react-apollo/blob/master/src/query-hoc.tsx#L60) statement:

```js
if (!shouldSkip && !opts.variables && operation.variables.length > 0) {
  opts.variables = calculateVariablesFromProps(
    operation,
    props,
    graphQLDisplayName,
    getDisplayName(WrappedComponent),
  );
}
```

Here, when

* `options: () => ({ variables: {} })`:
  * the `!opt.variables` is `false`
  * so the whole condition is false, it does not calculate the variables from props,
* `options: () => ({})`:
  * the `!opt.variables` is `true`
  * so the whole condition is true, it calculates the variables from props.

I'm not sure if it is a bug though. There might be a case when someone needs to reset the variables by passing an empty object.

**Comment by trungtin** [comment]
okay I understood, thank you, close this for now
