### ISSUE TITLE
MockProvider mocking but not resolving.

### ISSUE THREAD

**Issue by joepuzzo** [apollographql/react-apollo#2234]
So i have a test that looks like the following: 

```
it.only('passes the correct props to EditBenefit when query is successfull', async () => {
    const wrapper = mount(
      <MockedProvider mocks={[successfullMock]} addTypename={false}>
        <EditBenefitContainer />
      </MockedProvider>,
    );
    await wait(1000); // wait for response
    console.log("AFTER WAIT");
    const editBenefit = wrapper.find('EditBenefit');
    expect( editBenefit.props() ).to.deep.equal({
      ... stuff
    });
  });
```

I know for a fact that my mock is working correctly because i have logged on the following line in the source code: https://github.com/apollographql/react-apollo/blob/64ddc1f7e1b5edc0cb5dc7c553c9c725e032bdd1/src/test-links.ts#L95 . 

So my issue is that even though it looks like the mock is mocking.. when i check the props after waiting they are never updated :(. I see that others have this same code working  https://codesandbox.io/s/40k7j708n4 see that sandbox, with no issues. Any ideas on what i may be doing wrong? It seems like there is a bug where using MockProvider will mock but not update state.

**Comment by joepuzzo** [comment]
The solve: 
await new Promise(resolve => setTimeout(resolve))
wrapper.update()

**Comment by mackbrowne** [comment]
@joepuzzo this is the correct answer ^^

Just want to make a note, if you have nested <Query> components you need to do this twice to render the full response.

```
<Query>
    ${ result => <Query /> }
</Query>
```

to fully update the inside query 

```
await new Promise(resolve => setTimeout(resolve))
wrapper.update()

// and again

await new Promise(resolve => setTimeout(resolve))
wrapper.update()
```
