### ISSUE TITLE
update lifecycle methods for React 16.3+

### ISSUE THREAD

**Issue by devdoomari3** [apollographql/react-apollo#2237]
according to https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html 
componentWillReceiveProps is deprecated (along with other lifecycle methods).

there's a lot of components using componentWillReceiveProps / etc.

**Comment by jfrolich** [comment]
This is quite important, because `react-apollo` will now not work in concurrent mode.

**Comment by arianon** [comment]
I'm interested on taking a stab at this.

What do the maintainers think? Should I make a PR, or not yet?

**Comment by jfrolich** [comment]
Is there any roadmap for this, as now Concurrent React shipped for some time, and the lifecycles have been marked as deprecated for over a year now.

**Comment by hwillson** [comment]
Done and coming in `react-apollo` 3 (https://github.com/apollographql/react-apollo/pull/2892). Thanks!
