### ISSUE TITLE
errorPolicy: all in defaultOptions causes error to be undefined

### ISSUE THREAD

**Issue by adrienharnay** [apollographql/react-apollo#2253]
**Intended outcome:**

Trying to define `errorPolicy: all` in ApolloClient `defaultOptions`.

**Actual outcome:**

`errorPolicy: all` causes `error` in `<Mutation>{(func, { error }) => <SomeComponent />}</Mutation>` to always be `undefined`.

[Screen 1](https://gyazo.com/e32f1fe358bcd206343e77d8cc1df5fc)
[Screen 2](https://gyazo.com/2615f3eca460e360190df72e5d5762b9)

```js
const client = new ApolloClient({
  defaultOptions: {
    watchQuery: {
      fetchPolicy: 'cache-and-network',
      // errorPolicy: 'all',
    },
    query: {
      fetchPolicy: 'cache-and-network',
      // errorPolicy: 'all',
    },
    // mutate: {
    //   errorPolicy: 'all',
    // },
  },
});
```

Commenting it makes errors appear again.

`<Mutation errorPolicy="all">{(func, { error }) => <SomeComponent />}</Mutation>`

Specifying it at Mutation level, and not glabally, also works.

**How to reproduce the issue:**

```js
const client = new ApolloClient({
  defaultOptions: {
    watchQuery: {
      fetchPolicy: 'cache-and-network',
      errorPolicy: 'all',
    },
    query: {
      fetchPolicy: 'cache-and-network',
      errorPolicy: 'all',
    },
    mutate: {
      errorPolicy: 'all',
    },
  },
});
```

when declaring the client, and then performing a mutation with an error.

**Version**

* apollo-client@2.3.7
* react-apollo@2.1.9

Thanks in advance!

**Comment by amacleay** [comment]
I made a branch to demonstrate this issue in [react-apollo-error-template](https://github.com/amacleay/react-apollo-error-template/tree/no-error) in case it's helpful.

I do believe #2297 would resolve this issue.

**Comment by adrienharnay** [comment]
Yes it seems like it did! Thanks for your help on this :+1:
