### ISSUE TITLE
No more mocked responses for the query: mutation

### ISSUE THREAD

**Issue by scottmcpherson** [apollographql/react-apollo#2258]
**Intended outcome:**
For tests to pass without cryptic errors

**Actual outcome:**
```
/Users/scottmcpherson/Documents/Development/React/react-graphql-apollo-semanticui-starter/client/node_modules/react-scripts/scripts/test.js:20
  throw err;
  ^

Error: No more mocked responses for the query: mutation createPublicTask($input: CreatePublicTaskInput!) {
  createPublicTask(input: $input) {
    id
    title
    __typename
  }
}
```

**How to reproduce the issue:**
1. You can clone the repo and use this commit [here]https://github.com/scottmcpherson/react-graphql-apollo-semanticui-starter/tree/91c19c55ae9a0ce2df72245ff9f61deb0fefb14c).
2. cd into client folder
3. Install deps
4. run `yarn test`

Here's the [test file](https://github.com/scottmcpherson/react-graphql-apollo-semanticui-starter/blob/91c19c55ae9a0ce2df72245ff9f61deb0fefb14c/client/src/routes/Tasks/components/AddTask/AddTask.test.js) that's failing 

**Version**
*"apollo-boost": "0.1.10"
*"react-apollo": "2.1.9"

Similar to the closed out issue #617

**Comment by escapiststupor** [comment]
Has this been resolved?

**Comment by SenhorBardell** [comment]
@escapiststupor It is working fine, check out [testing mutation section](https://www.apollographql.com/docs/guides/testing-react-components.html#Testing-mutation-components) over Apollo docs.
What I've found is mocked provider does not work properly in `Componed` wrapped with `withApollo` wrapper.
