### ISSUE TITLE
Could Subscription re-render when Mutation modifies underlying data

### ISSUE THREAD

**Issue by blainekasten** [apollographql/react-apollo#2259]
## Info

I'm working on app that gets it's initial rendering payload via a `<Subscription>`. After we are hydrated with data, a user interacts with the app and can fire a `<Mutation>`.

## I was expecting:

A mutation which modifies data the `<Subscription>` component provided, I expected the render prop to re-render, because the data it listened for has been updated. Similar to how Mutation + Query can re-render.

## What actually happens:

Nothing. The mutation updates the cache, but there is nothing to trigger re-rendering of the application.

## Request

Ultimately I need to have this workflow, where a Subscription is given data, and mutations argue against it.

But I need to know if:

1. there should be a supported way to do this within Apollo
1. or if there is a different way to approach this

I currently have a working implementation by extending the `InMemoryCache` and overriding `write` to keep my own (secondary) data structure cache and use React's new Context API to propagate updates.

**Comment by rosskevin** [comment]
Yes this should work. The most common error with this is nod requesting an id in the payload of the mutation so that the cache data updates the watching components. If you can provide a reproduction please ping me and I'll reopen.
