### ISSUE TITLE
withApollo does not inject client into graphql() function config props

### ISSUE THREAD

**Issue by allenylzhou** [apollographql/react-apollo#2296]
**Intended outcome:**
This recipe https://www.apollographql.com/docs/react/advanced/caching.html#reset-store should work

**Actual outcome:**
`client` is undefined

**How to reproduce the issue:**
https://github.com/allenylzhou/react-apollo-error-template

**Version**

* apollo-client@^2.3.2
* react-apollo@2.1.4

**Comment by nandito** [comment]
It seems this is an issue of the docs. The `client` prop is passed, just not next to the `data` directly, but inside an `ownProps` object.

So the docs should be updated to this:

```js
export default withApollo(graphql(PROFILE_QUERY, {
  props: ({ data: { loading, currentUser }, ownProps: { client }}) => ({
    loading,
    currentUser,
    resetOnLogout: async () => client.resetStore(),
  }),
})(Profile));
```

**Comment by hwillson** [comment]
As mentioned in https://github.com/apollographql/react-apollo/issues/2296#issuecomment-417087194, this was a docs issue (that was fixed in https://github.com/apollographql/apollo-client/pull/3865). Thanks!
