### ISSUE TITLE
[Feature Idea] Mutation onStart prop

### ISSUE THREAD

**Issue by thomassuckow** [apollographql/react-apollo#2299]
**Intended outcome:**

It should be possible to use the Mutate component without arrow functions in render without necessitating making a subcomponent to get the mutation function.

**Actual outcome:**

If you disallow arrow functions in render, you end up needing a subcomponent to handle event functions if you would like to do anything other than JUST call the mutation.

**How to reproduce the issue:**

```jsx
class SaveButtonButton extends React.PureComponent {
  onClick = () => {
    this.props.onSave();
    this.props.doSave();
  };

  render() {
    return (
      <button
        onClick={this.onClick}
        disabled={this.props.disabled}
      >
        Save
      </button>
    );
  }
}

class SaveButton extends React.PureComponent {
  onSave = () => {
    this.props.onLoading(true);
  };

  onCompleted = (data) => {
    this.props.onLoading(false);
  };

  renderButton = (doSave, result) => {
    return <SaveButtonButton doSave={doSave} onSave={this.onSave} disabled={this.props.disabled} />;
  };

  render() {
    return (
      <Mutation
        mutation={SaveMutation}
        onCompleted={this.onCompleted}
        children={this.renderButton}
        variables={this.props.variables}
      />
    );
  }
}
```

**Proposed Syntax:**

I propose adding an `onStart` prop to the Mutation that would be called just before the mutation is invoked. I chose onStart because of the existing internal method `onMutationStart`

```jsx
class SaveButton extends React.PureComponent {
  onStart = () => {
    this.props.onLoading(true);
  };

  onCompleted = (data) => {
    this.props.onLoading(false);
  };

  renderButton = (doSave, result) => {
    return (
      <button
        onClick={this.doSave}
        disabled={this.props.disabled}
      >
        Save
      </button>
    );
  };

  render() {
    return (
      <Mutation
        mutation={SaveMutation}
        onStart={this.onStart}
        onCompleted={this.onCompleted}
        children={this.renderButton}
        variables={this.props.variables}
      />
    );
  }
}
```

**Version**

* apollo-client@2.4.0
* react-apollo@2.1.11

**Comment by JoviDeCroock** [comment]
Would it make sense to also implement this for `Query` (i assume so).

**Comment by thomassuckow** [comment]
I can't see adding it to Query hurting and for consistency it is probably better to have it. I've not used Query in ways that would necessitate it, but I can imagine cases where it could be useful if utilizing refetch/fetchmore.

**Comment by quentin-** [comment]
Why not just use the HOC? It's a bit hidden in the documentation but not deprecated (AFAIK).

**Comment by JoviDeCroock** [comment]
Well i've added it in the `Mutation` component it doesn't hurt anyone to extend functionality i assume? The PR is open :)

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, React Apollo feature requests are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=%5BFeature%20Idea%5D%20Mutation%20onStart%20prop&body=Migrated%20from:%20apollographql/react-apollo%232299) to start the feature request migration process. This manual migration process is intended to help identify which of the outstanding feature requests are still considered to be of value to the community. Thanks!
