### ISSUE TITLE
Use import for lodash/flowRight to allow for tree shaking

### ISSUE THREAD

**Issue by Pajn** [apollographql/react-apollo#2306]
`browser.ts` exports `lodash/flowRight` as compose, however it import this module using `require()`which makes it impossible for Webpack to treeshake it away. This causes quite a bit of lodash to be pulled in even though compose from react-apollo is not used at all. Replacing this require call with import should allow it to be treeshaked and its cost only paid if actually used.

https://github.com/apollographql/react-apollo/blob/9d02df8998f37c7188d0a06652e6b5d1ee69defe/src/browser.ts#L27

**Comment by rosskevin** [comment]
You could PR this just like https://github.com/apollographql/react-apollo/pull/2045.  At least it would solve the problem in the next patch/minor release before it is removed entirely.

**Comment by Pajn** [comment]
The thing is that I have no idea if changing it to
```typescript
import * as compose from 'lodash/flowRight';
export { compose };
```
would break stuff for some users.

I have not used require imports since Typescript 1.6 is released so there might very well be minor differences that I have forgotten. 
Since you use ES imports everywhere else they question is rather, why isn't this one? Is there a reason?

**Comment by Pajn** [comment]
Okey, types from DefinitlyTyped where bad. That I guess that was simply the reason. See the PR
