### ISSUE TITLE
Unexpected render is called introduced by a mutation under a Query component with query containing fragments 

### ISSUE THREAD

**Issue by raymondsze** [apollographql/react-apollo#2310]
**Intended outcome:**
Only Mutation component should be re-rendered.

**Actual outcome:**
All components belong to the nearest Query component are re-rendered.

**How to reproduce the issue:**
`git clone https://github.com/raymondsze/apollo-fragment-issue`
`yarn start`

Open **React dev tools**, tick the **highlight on update** checkbox.
**Click the first mutate button, all components under the Query component got re-rendered.**
**Click the second mutate button, this more make sense. Only the Mutation component got re-rendered.**
**PS: My mutation actually do nothing, it should never affect the Query data. It affect the rendering performance seriously**

**Version**

* apollo-client@2.4.1
* react-apollo@2.1.11

**Comment by hwillson** [comment]
This should no longer be an issue with current day `react-apollo`. Thanks!

**Comment by gjergjk71** [comment]
I think I'm having the same issue.
