### ISSUE TITLE
WebSocketLink not working for React Native

### ISSUE THREAD

**Issue by yuxiaoma** [apollographql/react-apollo#2312]
Tried to use subscriptions in React Native.
My backend is fully working and I followed the guide from Apollo to setup the client side: https://www.apollographql.com/docs/react/advanced/subscriptions.html
```javascript
import { split } from 'apollo-link';
import { HttpLink } from 'apollo-link-http';
import { WebSocketLink } from 'apollo-link-ws';
import { getMainDefinition } from 'apollo-utilities';

// Create an http link:
const httpLink = new HttpLink({
  uri: 'http://127.0.0.1:3000/graphql'
});

// Create a WebSocket link:
const wsLink = new WebSocketLink({
  uri: `ws://127.0.0.1:3000/graphql/subscriptions`,
  options: {
    reconnect: true
  }
});

// using the ability to split links, you can send data to each link
// depending on what kind of operation is being sent
const link = split(
  // split based on operation type
  ({ query }) => {
    const { kind, operation } = getMainDefinition(query);
    return kind === 'OperationDefinition' && operation === 'subscription';
  },
  wsLink,
  httpLink,
);

const client = new ApolloClient({
  link,
  cache: new InMemoryCache()
});

export default client;
```
However, nothing fires when doing subscription queries, no errors, no network traffic, monitored from both apollo link and graphql, no error from anywhere. This is happening for both on iOS and Android (simulators and devices).
I can clearly see the `subscription` query is passed through the link split and landed at the `wsLink`, but nothing happens afterwards.
Tried `onError` link from 'apollo-link-error', not producing anything.

Also tried this approach with `SubscriptionClient`, the same problem remains.
```javascript
const httpLink = new HttpLink({
  uri: 'http://127.0.0.1:3000/graphql'
});

const wsClient = new SubscriptionClient(
  `ws://127.0.0.1:3000/device/api/graphql/subscriptions`,
    {
      reconnect: true,
    }
 );
const wsLink = new WebSocketLink(wsClient);

const link = split(
  ({ query }) => {
    const { kind, operation } = getMainDefinition(query);
    return kind === 'OperationDefinition' && operation === 'subscription';
  },
  wsLink,
  httpLink,
);

const client = new ApolloClient({
  link,
  cache: new InMemoryCache()
});

export default client;
```
Is anyone experiencing the same problem?

**Version**
apollo-cache-inmemory@^1.1.1
apollo-client@^2.0.3
apollo-link@^1.0.3, apollo-link@^1.2.2
apollo-link-ws@^1.0.8
subscriptions-transport-ws@^0.9.14

**Comment by slorber** [comment]
@yuxiaoma any hint how you debugged this?
