### ISSUE TITLE
reFetchObservableQueries doesn't notifyOnNetworkStatusChange

### ISSUE THREAD

**Issue by lorensr** [apollographql/react-apollo#2324]
**Intended outcome:**

On `client.reFetchObservableQueries`, component should be rerendered and `loading` should true.

**Actual outcome:**

`loading` never becomes true.

**How to reproduce the issue:**

https://codesandbox.io/s/mm6zp1l6x

**Version**

* react-apollo@2.1.11

**Comment by hwillson** [comment]
This is no longer an issue with current day versions of `react-apollo`. Closing - thanks!
