### ISSUE TITLE
Apollo / Graphql requests destroyed by Proxy Servers or Antivirus software

### ISSUE THREAD

**Issue by mmuth** [apollographql/react-apollo#2342]
Hi there!

we are implementing an App using react-apollo and just started to leverage our api to graphql more and more (coming from REST). We already use graphql with apollo in production successfully. 

However, we with our latest release, we experiences some unexpected problems on the customer side. For some customers, the requests failed sporadically. In one case, all grapqhl requests failed with 401 and we found out that the proxy server (which was Symantec blue coat proxysg) is removing the authorization headers (for no reason?!?!).

Another customer reported sporadic failures, where Chrome showed net::ERR_SSL_VERSION_INTERFERENCE errors in the console, when doing graphql requests with react-apollo. But all other requests (thousands of!) work without hassle. We know this is done by a Antivirus software (Forticlient) on the client, as it works when disabled the protection software. 

So my question is:
Is there anything special about react-apollo requests, so that Proxies or Antivirus-Software/Firewalls consider the requests as non trustable? Are there best practices or known pitfalls that could cause problems like this? It would even help us if we knew, that someone had the same problems...

Our requests are pretty simple. One example of a request, where Symantec Proxy removes the auth headers is as simple as

```
query GWTUrlSync {
    me {
      id
      scenario {
        id
      }
      portfolio {
        id
      }
      compareToScenario {
        id
      }
    }
  }
```

At initial load of the application, we do seven similiar requests (like the one described above) and all fail. (I can post the other requests as well, if that helps).

Kind Regards
Matthias

**Comment by rosskevin** [comment]
There is nothing special about react-apollo network requests.
