### ISSUE TITLE
Loading and error as props when using graphql hoc

### ISSUE THREAD

**Issue by flip-it** [apollographql/react-apollo#2343]
I use the graphql hoc for a mutation. Like:

```
export default compose(
    [...]
    graphql(SEND_MESSAGE, {
        props: ({ mutate }) => ({
            sendMessage: (message) => {
                mutate({
                    variables: {
                        message,
                    },
                });
            },
        }),
    }),
)(Message);
```

The loading and error state are not available using this approach – they only come as render props in the `Mutation` component. It would be very useful to also get these as props when using the hoc. Would it be possible to add this?

**Comment by ljones87** [comment]
+1 on this. I am just learning react-apollo w/graphQL and spent hours thinking I wasn't providing the right config object.  Not sure why these (error, loading, called, etc) props would be available on the renderProps (Mutation in particular) and not the hoc.

**Comment by conanak99** [comment]
+1 on this.

**Comment by flip-it** [comment]
I ended up writing my own HOC for this.

```
import React from 'react';
import { Mutation } from 'react-apollo';

const withMutation = (mutation, options) => WrappedComponent => props => (
    <Mutation mutation={mutation} {...options}>
        {(mutate, result) => {
            const childProps = options.props({
                mutate,
                result,
                ownProps: { ...props },
            });
            return <WrappedComponent {...childProps} {...props} />;
        }}
    </Mutation>
);

export default withMutation;
```

Use it just like Apollo's own HOCs.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, React Apollo feature requests are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Loading%20and%20error%20as%20props%20when%20using%20graphql%20hoc&body=Migrated%20from:%20apollographql/react-apollo%232343) to start the feature request migration process. This manual migration process is intended to help identify which of the outstanding feature requests are still considered to be of value to the community. Thanks!
