### ISSUE TITLE
onComplete callback - data parameter is null

### ISSUE THREAD

**Issue by orgoldfus** [apollographql/react-apollo#2344]
Im trying to get the data returned from my mutation using the `onCompleted` callback, but the data is always null.

Here is my code:
```
export const ADD_CURRICOO = gql`
  mutation AddCurricoo(
    $title: String!
    $description: String
    $tags: [String]
  ) {
    createCurricoo(input: {
      title: $title, description: $description, tags: $tags,
    }) {
      id
      title
      description
      tags
    }
  }`

class CreateCurricoo extends Component {
  render () {
    return (
      <Mutation 
        mutation={ADD_CURRICOO} 
        onCompleted={data => console.log(data)} 
        ignoreResults={false}
      >
        {(createCurricoo, { data }) => (
          <CreateCurricooComponent onSubmit={createCurricoo}/>
        )}
      </Mutation>
    )
  }
}
```

That's the response from the server:
```
{"data":{"createCurricoo":{"id":"2bec435b-3d9e-45d1-af36-d1f979a4ae7b","title":"Some title","description":"Some description","tags":["example","tag","only"],"__typename":"Curricoo"}}}
```

and that's the log:
```
{createCurricoo: null}
```

Am I doing something wrong?

Version:
* client: aws-appsync@1.3.4,
* react-apollo@2.1.11

**Comment by stigmat4j** [comment]
Bumb! I have the same problem

**Comment by hari-mohan-choudhary** [comment]
I have same problem...

**Comment by tab00** [comment]
I got this problem after updating to react-apollo@2.2.3. Then onCompleted worked again after downgrading to 2.1.11.

**Comment by adrienharnay** [comment]
Hey, I also bumped into this problem. The `data` parameter is null when the mutation fails, but the types say it should never be.

**Comment by hwillson** [comment]
Can someone confirm that this is still an issue with current day `react-apollo` (ideally by sharing a small runnable reproduction)? Thanks!
