### ISSUE TITLE
Breaking change: skip doesn't work

### ISSUE THREAD

**Issue by sandorvasas** [apollographql/react-apollo#2345]
[*] blocker bug

After upgrading react-apollo from 2.0.4 to 2.1.11, graphql HOC's skip doesn't work like before. We have a pretty large application which makes use of the graphql HOC extensively and can't afford breaking changes like this. We are experiencing errors app-wise.

Even worse I'm unable to find any description about this change. How to upgrade our components so skip works as expected (to achieve the same behavior as in 2.0.4) ?

Also there seems to be an issue with refetchQueries after mutations. Queries that have an id parameter are now refetched parameterless, causing error.

**Comment by goldo** [comment]
Same problem with the `skip` @ v`2.1.11` :(

**Comment by goldo** [comment]
I've just seen this breaking change, it should be the reason why itt doesn't work anymore:
``` 
BREAKING CHANGES [Removal of deprecated code]

Remove deprecated operationOptions.options.skip, use operationOptions.skip instead
```
https://github.com/apollographql/react-apollo/releases/tag/v2.1.0-beta.0

**Comment by mariusbrn** [comment]
The `subscription` HOC pass the `skip` prop to the `Subscription` [component](https://github.com/apollographql/react-apollo/blob/master/src/subscription-hoc.tsx#L78), but the component does'nt seems to use it.

**Comment by mariusbrn** [comment]
The `subscription` HOC pass the `skip` prop to the `Subscription` component:
https://github.com/apollographql/react-apollo/blob/master/src/subscription-hoc.tsx#L78

but the component does'nt seems to use it.

**Comment by rosskevin** [comment]
Please provide a reproduction.  There are other open items with `skip`, perhaps this is a duplicate.  Without more information, I cannot leave this open as it will just linger unattended.  If you do have a reproduction, by all means let's reopen this, just ping me.  It would be ideal if you PR a new test or an additional assertion to an existing test.
