### ISSUE TITLE
2.1.11, refetchQueries omits parameters

### ISSUE THREAD

**Issue by sandorvasas** [apollographql/react-apollo#2347]
[*] blocker bug

After upgrading from 2.0.4 to 2.1.11, refetchQueries skip any previously set parameters. i.e.

```
having a query getUser({ id: "someId" })
then, after a mutation:
2.0.4 refetchQueries: [ 'getUser' ] executes getUser({ id: "someId" })
2.1.11 refetchQueries: [ 'getUser'] executes getUser()        <- ERROR
```

P.S: Please put back the 2.0.4 documentation to the site. If there are such serious issues with the library for months (I tried to upgrade first around april, then mid summer, then now), at least let developers work with the prev versions. We have several components we need to rewrite from 2.1.11 to 2.0.4 due to these bugs, but there are no docs for that anymore.

**Comment by JoviDeCroock** [comment]
I can't really see your component but I think it should be `refetchQueries={[{ query: getUserQuery, variables: {...} }]}`

**Comment by JoviDeCroock** [comment]
@rosskevin this has an answer and should be solved. Also outdated.
