### ISSUE TITLE
<Query> refetch doesn't work

### ISSUE THREAD

**Issue by sandorvasas** [apollographql/react-apollo#2353]
```
<Query ...>
({ data, loading, refetch }) => {
    setTimeout(()=> refetch(), 2000);
 return <div>whatever</div>
}
</Query>
```

does nothing. no request in chrome network tab.

react-apollo@2.1.11
apollo-client@2.4.1

**Comment by axe-z** [comment]
same here, not sure what it does.. simple thing are ending up being very tedious to type with cache.readQuery and writeQuery. 
A simple mongo $inc +1 . on a like button is keeping me from a full head of hair. 
It does work on a browser refrech. 

on a Mutation, I get the refetch on this.props from an HOC. 

if (this.state.liker) {
  likeRecette().then(async ({ data }) => {
        await this.props.refetch();
        console.log("likeRecette", data); //the data is one step behind alway
      }) else {
      unlikeRecette().then(async ({ data }) => {
        await this.props.refetch();
        console.log("unlikeRecette", data);
      });


tryed with 
refetchQueries={() => [
//it does work in some situation.
  ]}

**Comment by rosskevin** [comment]
Please use the codesandbox template and provide a reproduction. As-is, refetch is working in our app, so in order to help we need a bit more from you. Please ping me if you have a reproduction and I'll reopen.

**Comment by axe-z** [comment]
You've got a working example ??
