### ISSUE TITLE
Errors never disappear? Right way to display query errors

### ISSUE THREAD

**Issue by EugeneDraitsev** [apollographql/react-apollo#2355]
**Intended outcome:**
Hi! 
I'm trying to use react-apollo and I faced with error handling problem.
I have veery simple query and some component, that represent twitter data.
if I have an error - I display error, if all works fine - I display user data:

```jsx
const GET_USER = gql`
  query getTwitterUser($userid: UserIdentity!) {
    twitter {
      user(identifier: name, identity: $userid) {
        created_at
        description
        id
        screen_name
        name
        profile_image_url
        url
        tweets_count
        followers_count
        tweets(limit: 1) {
          text
        }
      }
    }
  }
`;

const TwitterUser = ({ userid }) => (
  <Query query={GET_USER} variables={{ userid }} notifyOnNetworkStatusChange>
    {({
      loading,
      error,
      data: {
        twitter: {
          user: {
            screen_name,
            profile_image_url,
            description,
            tweets_count,
            followers_count,
            tweets: [{ text: tweet }] = [{}]
          } = {}
        } = {}
      } = {}
    }) => {
      if (loading) return <CircularProgress size={100} />;
      if (error) return <div>{JSON.stringify(error)}</div>;

      const profileImage = profile_image_url.replace("_normal", "");

      return (
        <UserCard
          screenName={screen_name}
          profileImage={profileImage}
          description={description}
          tweetsCount={tweets_count}
          followersCount={followers_count}
          tweet={tweet}
        />
      );
    }}
  </Query>
);
```

**Actual outcome:**

If I get an error while I fetch query, f.e. user is not exist - I can display it, but! when I change query variables back to existing user, error is still there! There is only 1 way to remove this error - use query with not-cached value. Every time when you return to any cached query - error will be there.

![screencast 2018-09-06 15-45-05](https://user-images.githubusercontent.com/16540432/45161366-ffb0ae00-b1eb-11e8-952c-6fbb61e31aae.gif)

Why error is not disappear, when I return query to working state? How I should handle this situation? 

**How to reproduce the issue:**

Working demo is [here](https://codesandbox.io/s/jl0vwvo9l5)

**Version**

* apollo-client@ 2.3.2
* react-apollo@ 2.1.3

**Comment by csharad** [comment]
Related #2070.

**Comment by rosskevin** [comment]
Closing in favor of #2070
