### ISSUE TITLE
[Feature idea] Schema aware Mutation

### ISSUE THREAD

**Issue by jgoux** [apollographql/react-apollo#2361]
Hello,

I'm just starting with GraphQL, and so far using react-apollo is a pure joy, so I'd like to thanks the team and all the contributors for that. 👏 

After some time writing mutation queries client-side, I noticed that mutation queries were very often a reflection of the mutation defined in my schema server-side.

For example : 
```graphql
  mutation addTodo($type: String!) {
    addTodo(type: $type) {
      id
      type
    }
  }
```

I write this kind of mutation in 90% of the cases.

I thought these queries could easily be generated by leveraging the schema own mutations definitions, so we just have to pass a mutation's name and a selector set : 

```graphql
<Mutation mutation={{ name: "addTodo", select: "{ id, type }" }}>
{addTodo => {
  // do awesome stuff!
}}
</Mutation>
```

I see two benefits in this approach : 
- Saving a few keystrokes
- Keeping our mutation queries signatures in sync with the schema

Here is a working example : https://codesandbox.io/s/973ly9kow

As react-apollo already requires an URL to the GraphQL API, getting + caching the whole schema with an introspection query on startup wouldn't be difficult I suppose?

**Comment by rosskevin** [comment]
While saving a few keystrokes, this would be creating another dialect.  Given the configurability of mutations and payload queries, I think doing so would be out of scope from react-apollo.
