### ISSUE TITLE
How to avoid lambda in props?

### ISSUE THREAD

**Issue by lazywei** [apollographql/react-apollo#2369]
**Intended outcome:**
Avoid using lambda in onClick in the doc of using local state management with apollo

**Actual outcome:**
No doc on how to do this

**How to reproduce the issue:**

When following the guide to use local state management on the [doc](https://www.apollographql.com/docs/react/essentials/local-state.html), we have the example:

```
import React from 'react';
import { ApolloConsumer } from 'react-apollo';

import Link from './Link';

const FilterLink = ({ filter, children }) => (
  <ApolloConsumer>
    {client => (
      <Link
        onClick={() => client.writeData({ data: { visibilityFilter: filter } })}
      >
        {children}
      </Link>
    )}
  </ApolloConsumer>
);
```

However, this will result in TSLint complains about "Lambdas are forbidden in JSX attributes due to their rendering performance impact".

I'm wondering how can we avoid this? It seems to be a little bit tricky as the client is only available in the ApolloConsumer (or Query) component. If we want to avoid using lambda in the "onClick" attribute, we might need to somehow be able to pass the client as a props or argument. However, we don't have any doc on how we can write the type of a `ApolloClient`. I'm wondering if someone can help me out on this?

Thanks

**Version**

* apollo-boost@0.1.15
* react-apollo@2.1.11

**Comment by PascalSenn** [comment]
To just bypass the linter you could use a creator function or store it in a variable.
But this is not really solving the problem. The reason for not having arrow brackets in jsx is because they return a new instance on every render. 
What you could do is memoize the creator.

```javascript 
createOnClickHandler(client, visibilityFilter){
 return () => client.writeData({ data: { visibilityFilter} })}
}

memoizedCreateOnClickHandler = memoize(createOnClickHandler);

```

**Comment by lazywei** [comment]
@PascalSenn thanks for the reply. I thought about this usage. However, what I couldn't figure out is how can we type the creator function then? If I just use the client inside the ApolloConsumer, typescript will infer the type of the client for me. But if we want to write a function on the client, we will need to explicitly specify its type, which seems to be quite nontrivial to me --- couldn't find any doc on the website.
Do you have any idea on how we may achieve this?

Thanks.

**Comment by PascalSenn** [comment]
https://codesandbox.io/embed/mjn0o8mj38?codemirror=1

**Comment by rosskevin** [comment]
You can disable the linter or declare the fn in a larger scope.
