### ISSUE TITLE
onSubscriptionData is not working on latest version of react-apollo

### ISSUE THREAD

**Issue by alexfqc** [apollographql/react-apollo#2371]
**Intended outcome:**

I'm not getting to use the onSubscriptionData prop from Subscription Component. I asked on [stackoverflow](https://stackoverflow.com/questions/52264429/apollo-client-onsubscriptiondata-is-not-working/52265722#52265722) and the answer is correct. But onSubscriptionData is only at master of repo. So if I want to use onSubscriptionData I will have to compile the master code at my project.

**Actual outcome:**

onSubscriptionData is the docs but it's only available at master of repo

**How to reproduce the issue:**

```
const MESSAGE_CREATED = gql`
  subscription {
    messageCreated {
      id
      content
    }
  }
`;

const MyComponent = () => (
  <Subscription
      subscription={MESSAGE_CREATED}
      onSubscriptionData={() => {
        console.log('subs');
      }}
    >
      {({ data, loading }) => {
        if (loading && !data) return <View />;
        return (
          <Text>New comment: {!loading && data.messageCreated.content}</Text>
        );
      }}
    </Subscription>
);
```

**Version**

* apollo-client@2.3.5
* react-apollo@2.1.11

**Issue Labels**

- [x] blocking

**Comment by frederikhors** [comment]
Same here.

If you call it directly the first time the next times it works.

Seems broken.

**Comment by danielwong2268** [comment]
Ditto - `onSubscriptionData`is not a valid prop in my typescript app.

`react-apollo: ^2.1.11`

**Comment by JonLundy** [comment]
@alexfqc i followed the steps in the SO post to compile and then pushed up the lib directory as a repo ([sour-is/react-apollo](https://github.com/sour-is/react-apollo)). feel free to fork it for yourself. 

i add it into my package.json as `"react-apollo": "sour-is/react-apollo"` 

imports are as expected with `import { Subscription } from 'react-apollo'`

**Comment by rosskevin** [comment]
I checked and `onSubscriptionData` is in `2.3.3`.
