### ISSUE TITLE
After upgrade client to 2.x.x refetch return undefined data and error

### ISSUE THREAD

**Issue by Mjafko** [apollographql/react-apollo#2372]
We upgrade client and server from 1.x to 2.x. After we expect some strange behavior. 
`this.props.getInfoById.refetch({
			skip: false,
			infoID: info.id,
			language:  'en' 
		})
		.then((response) => {
			console.log(response)
		})`
this return (in console )
`data:undefined
errors:undefined
loading:false
networkStatus:7
stale:false`

But the strange thing is if I check in network tab I can view query and correct response without any issue or errors.
Did anyone have the same problem?

Greetings,
Marko.

**Comment by csharad** [comment]
Related #2070.

**Comment by 7yp0** [comment]
also related to #1811

**Comment by danilobuerger** [comment]
Closing as not reproducible. If reproducible, please provide a sample showing it.
