### ISSUE TITLE
MockLink splices results

### ISSUE THREAD

**Issue by mikebm** [apollographql/react-apollo#2375]
Hello,

We use MockedProvider within Storybook. We have some components that perform pagination. To implement this, we define an array of MockedResponses for each of the page fetches. Moving forward through the pages works great. The issue is that when you want to go back to a previous page that was defined in the mocks, then you receive an error because of this line of code:

https://github.com/apollographql/react-apollo/blob/a6021bb7f1e834d7f118ff69d7cbee4fa45ef1b6/src/test-links.ts#L76

The above line is splicing out the result once used. It would be nice to have an option to disable this functionality so it can be used outside of simple one use tests.

**How to reproduce the issue:**
Should be able to create a mock for a single graphql request that has a fetchPolicy of no-cache.
Create a button that triggers the graphql request. Clicking that button should issue the request and return data. Clicking it again results in an exception of "No more mocked responses for the query:"

**Version**

* apollo-client@2.4.1
* react-apollo@2.1.11

**Comment by rosskevin** [comment]
Please PR something that works for you, otherwise I'm afraid this issue is likely to linger open indefinitely.  Feel free to ping me for a review.
