### ISSUE TITLE
why every item re-render when list change in apollo

### ISSUE THREAD

**Issue by wukong1995** [apollographql/react-apollo#2380]
I update list by `update` in `immutability-helper`.

when I push some items to list, and found every item(extends PureComponent and have key) run re-render.

```
// List
list.map(edge => (
  <div key={edge.node.id} className="xxxx">
    <Item {...edge.node} />
  </div>
))

// Item
class Item extends React.PureComponent {
  render() {
    const { id, title ...otherProps } = this.props;

    return (
      <div>
        // ....
      </div>
    )
  }
}
```

`PureComponent` use shallowEqual. Apollo's data is immutable.

why Pre-existing items run re-render?

**Comment by captDaylight** [comment]
When you update an item  in a list with immutablility helper its returning a brand new array, so it'll have a _new reference_. So that list in React's eyes is completely new, even if structurally most of the items in the array are the same. Thus each item will be re-rendered.

**Comment by wukong1995** [comment]
@captDaylight  thank you very much.
The only solution I can think of at this time is add `shouldComponentUpdate()` to my components.
Let me check the immutable data related documents and find whether has other solutions.
