### ISSUE TITLE
It's very useful to have a way to compare a query with the mocked one(s) to see the diff

### ISSUE THREAD

**Issue by brunoreis** [apollographql/react-apollo#2384]
Sometimes I think I have a correct mocked query in place, but there is some small difference between my query and the one in the mocked responses set. I found that when facing an issue with the @connection directive and now with different variables. So you usually go into node_modules/react-apollo/test-utils and start printing the mockedResponsesByKey keys, variables and the requested query to make a diff and understand what is going on. 

I suggest having an easy way to debug what queries/variables are on the mocked responses and what query is being tested against those. That way a dev can grab them and paste in a diff tool to quickly see what is going on.

**Comment by rosskevin** [comment]
You might look at the current jest matchers to see if their diff function is already exposed, otherwise feel free to PR something for review.
