### ISSUE TITLE
How to reset only a specific part of the client store (cache) ?

### ISSUE THREAD

**Issue by doums** [apollographql/react-apollo#2385]
Hi,

I'm facing a problem with my react/prisma app. I have a simple query that fetch a list of posts. I use pagination for this query with first/last and skip (the offset) args. It works well. I implemented subscriptions for create/update/delete post event and I update the cache manually (I write the new post in the cache or I delete it for example). The problem is that when a create/delete event is fired, I would like to reset the cache for all the actives queries of that list of posts.

```
export const ALL_POSTS = gql`
    query AllPosts($orderBy: PostOrderByInput, $skip: Int, $first: Int, $last: Int) {
        allPosts(orderBy: $orderBy, skip: $skip, first: $first, last: $last) {
            id
            title
            createdAt
            author {
                id
                username
            }
        }
    }
`
```

Because, when a post is created/deleted, all the previous queries (that are chached) I made become staggered. If I use refetch, this get fresh data only for the current chunk/page (specified with the first/last and skip args passed to the query). But all the other chunks which are chached (if there is any) still not refresh and became offbeat. There is any way to perform an `client.resetStore()` equivalent but only for this specific query ?

"apollo-client": "^2.4.2",
"apollo-link-ws": "^1.0.8",
* react-apollo@^2.1.11

**Comment by rosskevin** [comment]
Look at apollo-client methods, specifically writeQuery and writeData may be what you are looking for.
