### ISSUE TITLE
getDataFromTree throws on styled-jsx tags with variables

### ISSUE THREAD

**Issue by srslafazan** [apollographql/react-apollo#2388]
**Intended outcome:**
getDataFromTree should skip style jsx tags.

**Actual outcome:**
getDataFromTree fails to parse and throws.

**How to reproduce the issue:**
Use style jsx with variables and ssr with getDataFromTree

**Version**

* apollo-client@<2.4.2>
* react-apollo@<2.1.11>

**Comment by benjamn** [comment]
The implementation of `getDataFromTree` has changed substantially in `react-apollo@2.3.1` (the latest version), thanks to #2533. Please try updating, and feel free to reopen this issue if the problem persists.
