### ISSUE TITLE
Unmet Peer Dependencies

### ISSUE THREAD

**Issue by quadsurf** [apollographql/react-apollo#2394]
when npm installing "react-apollo": "^1.4.8", I get the following warning:

warning "react-apollo > graphql-tag@2.9.2" has unmet peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
___________________________________________________________________________________________

when npm installing "subscriptions-transport-ws": "^0.8.2", I get the following warning:

warning "subscriptions-transport-ws > graphql-subscriptions@0.4.4" has unmet peer dependency "graphql@^0.7.0 || ^0.8.0 || ^0.9.0 || ^0.10.1".
___________________________________________________________________________________________

Since I do not have any ```npm install``` control over peer dependency installation (or do I?), how do I resolve these unmet peer dependencies?

**Comment by darylf** [comment]
It sounds like you don't have graphql defined in your `package.json`.
`npm install graphql --save` (as per readme)
 
However, doing this will only shift your warning from "unmet peer dependency " to a warning about having _incorrect_ peer depenency. It looks like issues are already logged with `graphql-tag`: 
* https://github.com/apollographql/graphql-tag/issues/208
* https://github.com/apollographql/graphql-tag/issues/217

I've learned to live with it until graphql-tag (and apollo-cache-inmemory) updates their dependency list, unless someone else has a better solution :smirk:

**Comment by quadsurf** [comment]
thanks @darylf , but... which is the lesser of two evils between ```unmet vs incorrect``` peer dependency?

**Comment by darylf** [comment]
I'm not sure if either one is better. To each their own I guess. Personally, in this scenario, I prefer "incorrect" as it feels like a step in right direction. Once `graphql-tag` updates their dependencies, your `package.json` will be correct.

**Comment by OllieJennings** [comment]
@quadsurf This should be resolved now, this issue can be closed
