### ISSUE TITLE
Is there a way to detect API calls (internet traffic) on my site with React Apollo?

### ISSUE THREAD

**Issue by frederikhors** [apollographql/react-apollo#2395]
Is there a way to detect API calls (internet traffic) on my site with React Apollo?

I need to know in React Apollo (true / false) if something is requested through my browser page...

With jQuery I was using $(document).ajaxStart(() => {} - $(document).ajaxStop(() => {}

Is there something similar in React Apollo world?

**Comment by danilobuerger** [comment]
Issues here are reserved for bugs, but one of the following resources should help:

* Apollo's Slack: https://www.apollographql.com/slack
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests

**Comment by frederikhors** [comment]
@danilobuerger do you have any hint?
