### ISSUE TITLE
update props of mutation, result from readQuery is undefined.

### ISSUE THREAD

**Issue by Herikle** [apollographql/react-apollo#2408]
I have this code 

```
<Mutation mutation={Add_Message}
        update={(cache, {data :{addMessage}}) => {
            console.log(addMessage)
            const { messages } = cache.readQuery({ query: QueryAll})
            cache.writeQuery({
                query: QueryAll,
                data:{ messages : messages.concat(addMessage)}
            })
        }}
```

variable "QueryAll" is exactly the same query that I using before to get data from server, but it's don't works, cache is not updated and on console I receive the following message "Cannot read property 'concat' of undefined". What i'm doing wrong? i'ts exactly like documentation example.

apollo-client version is 2.1.11

**Comment by daniel-teixeira-ad** [comment]
How did you fixed it?
