### ISSUE TITLE
Query rerendering when child rerenders

### ISSUE THREAD

**Issue by Cottin** [apollographql/react-apollo#2420]
I ran into a tricky issue:

I'm using [react-virtualized](https://github.com/bvaughn/react-virtualized) to render a huge Grid of data and I'm wrapping it in a apollo `<Query>` component to load all data for the Grid to have client side (3000 rows, 70 columns tabular data ~ 3 MB).

I need to optimise things for smooth behaviour when filtering the huge dataset when user types in a `<input type="text" ` to apply a filter so I wrap the query in a `React.PureComponent` like so:

```
class QueryWrapper extends React.PureComponent {
  render() {
    console.log('RENDER QueryWrapper')
    return (
      <Query query={MY_QUERY}>
        {({ loading, error, data }) => {
          return (
            <div>
              {console.log('RENDER-function for Query')}
              {loading && <div>Loading...</div>}
              {data && <HugeDataGridWrapper data={data} />}
            </div>
          )
        }}
      </Query>
    )
  }
}
```

`HugeDataGridWrapper` is subscribed to `location.search` changes where filtering text is stored.

The problem is, whenever `HugeDataGridWrapper` re-renders as a result of `location.search` changes, the render-function inside `Query` is also re-run causing the total re-render to be slower than wanted. However the nature of the `PureComponent` seems to work since the render method is not called.

i.e. printed in the console is `RENDER-function for Query` but `RENDER QueryWrapper` is not printed.

I can do a workaround and instead of using the `Query` component, I use the `ApolloConsumer` and manually kick off the query and make sure to set the state.data of the Pure wrapper. And then things works as expected.

If I add a `PureComponent` "blocker" in the render-function it gets re-rendered and I see that the `data` prop from the `Query` component changed (i.e. does not hold reference equality but the data content is the same):

```
class QueryWrapper extends React.PureComponent {
  render() {
    console.log('RENDER QueryWrapper')
    return (
      <Query query={MY_QUERY}>
        {({ loading, error, data }) => {
          return (
            <Blocker loading={loading} error={error} data={data} />
          )
        }}
      </Query>
    )
  }
}

class Blocker extends React.PureComponent {  
  constructor(props) {
    super(props)
    this.last = {}
  }
  render() {
    console.log('RENDER Blocker')
    const {loading, error, data} = this.props
    console.log('last loading == new loading ?', this.last.loading == loading)
    console.log('last error == new error ?', this.last.error == error)
    console.log('last data == new data ?', this.last.data == data)
    this.last = {loading, error, data}
    return (
      <div>
              {console.log('RENDER-function for Query')}
              {loading && <div>Loading...</div>}
              {data && <HugeDataGridWrapper data={data} />}
      </div>
    )
  }
}
```

..i.e. the console loggs this when child (`HugeDataGridWrapper`) re-renders:

```
RENDER Blocker
last loading == new loading ? true
last error == new error ? true
last data == new data ? false
```

Why is the render-function/child-function being re-run when a "child" of that function (in this case the `HugeDataGridWrapper`) component re-render itself? Is this something about the child-functions pattern that always causes this or is there something special about the `Query` component? ...or is it more possible that I messed something else up and should just keep trouble-shooting?

Sorry if this is too much, and should be labeled as "Spam", I just spent the whole day digging into this and can let it go before I understand the root cause :)

**Comment by thekevinbrown** [comment]
I'm no React or Apollo expert, but my suspicion is that it's from here:

```javascript
{({ loading, error, data }) => {
...
}
```

When you declare an arrow function like this, it'll make a new instance of that function every time the render runs. That'll get passed in as the children prop, and the Query component will see that its props are no longer reference equal, so it needs to re-render.

The way to fix this is to declare the arrow function outside of the component, either as a const at the top of the file or (what I'd do in your case) set it as a property on your component class, then just pass it by doing this:

```
class QueryWrapper extends React.PureComponent {
  queryChildren = args => <Blocker {...args} />

  render() {
    console.log('RENDER QueryWrapper')
    return (
      <Query query={MY_QUERY}>
        {this.queryChildren}
      </Query>
    )
  }
}
```

That being said, I suspect the whole blocker / PureComponent wrappers setup is actually unnecessary once you stop passing a new instance of the arrow function on every render.

You can read more about this here: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md

**Comment by rosskevin** [comment]
This is a good catch and probably good optimization advice. Definitely two renders of a function will be different unless the fn is declared in a larger scope. 

I'm doing cleanup and going to close this, but in my work today I have seen several issues and one PR discussing rerenders. I would follow the advice above then search for open issues on rerenders to see if you have a match.
