### ISSUE TITLE
Release 2.2 depends on SyntheticDefaultImports for ts definitions

### ISSUE THREAD

**Issue by daugsbi** [apollographql/react-apollo#2433]
**Intended outcome:**
The published library should not depend on any additional configuration. The types of the wrapped components need to be inferred correctly.

**Actual outcome:**
The published release has the following typings throughout the project i. e. in graphql.d.ts
`import React from 'react';`
This only works, if the tsconfig.json has the following compiler options defined.
`"allowSyntheticDefaultImports": true`

The typings in previous released defined it as 
`import * as React from 'react'`

The wrapped components are typed as any. 

**How to reproduce the issue:**
Set allowSyntheticDefaultImports: false.
Try to use graphql HOC. The types are any, although stronlgy typed.
![apolloissue](https://user-images.githubusercontent.com/5528706/46205470-003af100-c321-11e8-8046-584e053f5616.png)

With the allowSyntheticDefaultImports the types are inferred.
![apolloissueresolved](https://user-images.githubusercontent.com/5528706/46205482-06c96880-c321-11e8-86d1-2efcfd1c2526.png)

**Version**

* apollo-client@2.4.2
* react-apollo@2.2.1

**Comment by danilobuerger** [comment]
Caused by #2430

**Comment by meyer** [comment]
The `Query` component is broken by this change as well:

![screenshot 2018-09-28 14 12 13](https://user-images.githubusercontent.com/13781/46233733-a2120c00-c328-11e8-9089-fd61038eaba2.png)

**Comment by danilobuerger** [comment]
@hwillson any insight into this? you changed this in 9a96519d390783dfd9a431dc2dbaa476a24f7b80
