### ISSUE TITLE
[typescript] the "query" parameter in fetchMore should not be mandatory

### ISSUE THREAD

**Issue by jemerald** [apollographql/react-apollo#2443]
When using `Query` with `fetchMore` for pagination, typescript complains that the argument with just `variables` and `updateQuery` is not assignable to parameter of type `{ query: DocumentNode; } & FetchMoreQueryOptions<SearchCustomerVariables, "offset" | "limit"> & FetchMoreOptions<SearchCustomer | undefined, SearchCustomerVariables>`.

Sample code

```
fetchMore({
  variables: {
    offset: newOffset,
    limit: newLimit
  },
  updateQuery: (prev, { fetchMoreResult }) => fetchMoreResult
});
```

Adding the `query` field would make typescript stop complaining, but results in the unspecified variables being reset.

**Intended outcome:**

The typing for fetchMore should not have mandatory restriction on `query` field.

**Actual outcome:**

Typescript complains when the argument is actually correct.

**How to reproduce the issue:**

Use `fetchMore` in any react typescript project.

**Potential fix**

https://github.com/apollographql/react-apollo/blob/master/src/Query.tsx#L30

Change `{ query: DocumentNode }` to `{ query?: DocumentNode }`

Or just remove `{ query: DocumentNode }` altogether as `query?: DocumentNode` already exists in `FetchMoreQueryOptions` see [apollo-client](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/watchQueryOptions.ts#L112)

**Version**

- apollo-client@2.4.2
- react-apollo@2.2.3

**Comment by EricMcRay** [comment]
I am currently using react-apollo@2.2.4 and I dont have this issue. Looks like its fixed.

**Comment by jemerald** [comment]
Turns out there are two overloads for the `fetchMore` function, with the following signatures:

- `<K extends keyof TVariables>(fetchMoreOptions: FetchMoreQueryOptions<TVariables, K> & FetchMoreOptions<TData, TVariables>) => Promise<ApolloQueryResult<TData>>`
- `<TData2, TVariables2, K extends keyof TVariables2>(fetchMoreOptions: {
        query: DocumentNode;
    } & FetchMoreQueryOptions<TVariables2, K> & FetchMoreOptions<TData2, TVariables2>) => Promise<ApolloQueryResult<TData2>>`

For some reason typescript defaults to the second signature. The error goes away by adding type hints to the call, e.g. changing

```js
fetchMore({
  variables: {
    offset: newOffset,
    limit: newLimit
  },
  updateQuery: (prev, { fetchMoreResult }) => fetchMoreResult
});
```

to 

```js
fetchMore({
  variables: {
    offset: newOffset,
    limit: newLimit
  },
  updateQuery: (prev, { fetchMoreResult }: {fetchMoreResult: SearchCustomer}) => fetchMoreResult
});
```

**Comment by johnnyoshika** [comment]
@jemerald's solution helped me a little bit, but typescript still won't compile. I'm still getting a `No overload matches this call` error:

![image](https://user-images.githubusercontent.com/504505/81243348-6f2fff80-8fc4-11ea-978c-9e348f33d8fc.png)

Anyone else encounter this?

I'm using:

```
    "@apollo/react-hooks": "^3.1.5",
    "apollo-cache-inmemory": "^1.6.5",
    "apollo-client": "^2.6.8",
    "apollo-link": "^1.2.14",
    "apollo-link-context": "^1.0.20",
    "apollo-link-error": "^1.1.13",
    "apollo-link-http": "^1.5.17",
```

**Comment by dleavitt** [comment]
@johnnyoshika try `fetchMoreResult?` (with the question mark) in the type

**Comment by johnnyoshika** [comment]
Thanks @dleavitt. Where would you put the question mark? I tried many places with no luck.

**Comment by dleavitt** [comment]
The type of the second argument provided by `updateQuery` is what did it for me. Though I'm on `@apollo/client ^3.0.0-beta.41` so ymmv

```typescript
fetchMore({
  variables: {
    query: {
      ...queryVars,
      textSearch: searchTerm,
      page: pageData.nextPage,
    },
  },
  // this did it for me
  updateQuery: (prev, { fetchMoreResult }: { fetchMoreResult?: Q }) => {
    // ...
  },
})
```

**Comment by Kaschman** [comment]
@johnnyoshika had a similar issue, for me I was able to fix by defining a return type on the `updateQuery` function -> it mismatched a `void` return type with the query return type

so if your `useQuery` type signature looks like this:
```
useQuery<GetObject, GetObjectVariables>
```

change the `updateQuery` line to look like:
```
updateQuery: (previousResult, { fetchMoreResult }): GetObject => {
```

**Comment by johnnyoshika** [comment]
@dleavitt It must be a @apollo/client ^3 solution, as your solution doesn't work for me. I'm using apollo-client ^2.6.8

@Kaschman Could you share more of your code? Where/how do you define your `useQuery` type signature?

**Comment by 1st8** [comment]
@johnnyoshika I had a very similar issue, also when following the relay pagination example. It seems to be a mismatch on the return type, which coincides with what @Kaschman said.

I didn't feel like replicating the exact response object with my changes, so the solution I found is a little different and looks like this:

```typescript
fetchMore({
  variables: {
    cursor: data.family?.pictures?.pageInfo.endCursor,
  },
  updateQuery: (previousResult, { fetchMoreResult }) => {
    // fetchMoreResult can be undefined from its typing, so we can't return it directly
    if (!fetchMoreResult) return previousResult;

    if (fetchMoreResult?.family?.pictures?.edges)
      // Mutation is hopefully okay here, since fetchMoreResult is a new object and not cached yet
      // Otherwise create a new object and return this instead
      fetchMoreResult.family.pictures.edges = [
        ...(previousResult.family?.pictures?.edges || []),
        ...fetchMoreResult.family.pictures.edges,
      ];

    return fetchMoreResult;
  },
});
```

**Comment by 1st8** [comment]
After upgrading to apollo client v3, I was able to replace the `updateQuery` function with the new `relayStylePagination` feature without any typescript issues. (see https://www.apollographql.com/blog/announcing-the-release-of-apollo-client-3-0/ for an example)

10/10 would recommend, if you can upgrade to v3.

CC @johnnyoshika
