### ISSUE TITLE
[TypeScript] optimisticResponse does not allow __typename when generated types omit it

### ISSUE THREAD

**Issue by disintegrator** [apollographql/react-apollo#2447]
**Intended outcome:**

I was trying to setup an optimistic response to a mutation with passing TypeScript type checks.

**Actual outcome:**

The value passed to `optimisticResponse` is no longer valid as of react-apollo@2.2.3.

**How to reproduce the issue:**

This issue came to light after #2340 was merged.

Roughly the steps are:

- Use apollo-cli to generate TypeScript types for a mutation document
  - ensure that `--addTypename` is **NOT** enabled
- Use the Mutation component and pass a value to optimisticResponse

  ```ts
    <Mutation<UpdateName, UpdateNameVariables>>
      {mutate => (
        <button
          onClick={() => mutate({
            variables: { name: "Jane Doe" },
            optimisticResponse: {
              __typename: "Mutation",
              updateName: {
                __typename: "UserProfile",
                name: "Jane Doe"
              }
            }
          })}
        >
          Test
        </button>
      )}
    </Mutation>
  ```

At this point TypeScript will complain that:
`Object literal may only specify known properties, and '__typename' does not exist in type 'UpdateName'.`

This is due to the generated types not containing the `__typename` property. The problem is we need to specify `__typename` when setting `optimisticResponse` to update the appropriate parts of Apollo cache.

**Version**

- apollo-client@2.4.2
- react-apollo@2.2.3

cc @danilobuerger

**Comment by danilobuerger** [comment]
Whats the reason for not enabling `--addTypename`? Also see https://github.com/apollographql/apollo-cli#typescript-and-flow

**Comment by disintegrator** [comment]
🤦‍♂️ I missed that notice on apollo-cli. Thanks for pointing me at it 👍
