### ISSUE TITLE
Example code with TypeScript does not compile

### ISSUE THREAD

**Issue by mdazy** [apollographql/react-apollo#2450]
I'm trying to add TypeScript support to my Apollo client code. Following the example from https://www.apollographql.com/docs/react/recipes/static-typing.html works fine until TypeScript is actually added.

**Intended outcome:**
I expected the example code given in the URL above to work out of the box without any errors.

**Actual outcome:**
TypeScript reports errors when trying to destructure the response data.

The code below is adapted from the mentioned example, over react-apollo-error-template:
```javascript
type Person = {
  id: string;
  name: string;
}

type Response = {
  people: Person[];
}

const PEOPLE_QUERY = gql`
  query ErrorTemplate {
    people {
      id
      name
    }
  }
`;

const withPeople = graphql<{}, Response>( 
  PEOPLE_QUERY, {}
);

export default withPeople( ( { data: { loading, people, error } } ) => {
  if( loading ) {
    return <p>Loading...</p>;
  }
  if( error ) {
    return <h1>Error!</h1>;
  }
  return <ul>
    {people.map( p => <li>{p.id} - {p.name}</li>)}
  </ul>;
} );
```
This reports three errors on the use of withPeople():
    Type 'DataValue<Response, {}> | undefined' has no property 'loading' and no string index signature.
    Type 'DataValue<Response, {}> | undefined' has no property 'people' and no string index signature.
    Type 'DataValue<Response, {}> | undefined' has no property 'error' and no string index signature.

**How to reproduce the issue:**
Please clone from https://github.com/mdazy/react-apollo-error-template.git and use the branc apollo-client-test.

Thanks.

**Version**
- apollo-client@2.3.2
- react-apollo@2.1.4
- typescript@2.9.2

**Comment by danilobuerger** [comment]
Please try with up-to-date dependencies

**Comment by mdazy** [comment]
I updated everything to the current latest. I still have the same errors with apollo-client@2.4.2, react-apollo@2.2.4 and typescript@3.1.1.

**Comment by danilobuerger** [comment]
@mdazy 
```
diff --git a/src/App.tsx b/src/App.tsx
index 632f6cc..1dcd858 100644
--- a/src/App.tsx
+++ b/src/App.tsx
@@ -1,5 +1,5 @@
 import React, { Component } from "react";
-import { graphql } from "react-apollo";
+import { graphql, ChildDataProps } from "react-apollo";
 import gql from "graphql-tag";
 
 type Person = {
@@ -20,7 +20,9 @@ const PEOPLE_QUERY = gql`
   }
 `;
 
-const withPeople = graphql<{}, Response>( 
+type ChildProps = ChildDataProps<{}, Response, {}>;
+
+const withPeople = graphql<{}, Response, {}, ChildProps>(
   PEOPLE_QUERY, {}
 );
```

**Comment by mdazy** [comment]
Awesome <3
Thanks!
