### ISSUE TITLE
[Feature Request] Deep merge Mutation variables

### ISSUE THREAD

**Issue by chentsulin** [apollographql/react-apollo#2451]
Mutation component now applies shallow merge to mutation props and mutation options.

Ref: https://github.com/apollographql/react-apollo/blob/64ac74046fd2b0e369188eaccd0a7139841a5714/src/Mutation.tsx#L213-L214

```js
    const mutateVariables = Object.assign({}, variables, mutateOptions.variables);
    delete mutateOptions.variables;
```

But it won't work if we use Relay spec Mutation:

```graphql
input IntroduceShipInput {
  factionId: ID!
  shipName: String!
}
```

Ref: https://facebook.github.io/relay/docs/en/graphql-server-specification.html#mutations

For example:

```js
<Mutation mutation={...} variables={{ 
  input: { 
    factionId: '1' 
  } 
}}>
  (mutate => (
    <button onClick={() => mutate({
      variables: { 
        input: {
          shipName: 'B-Wing'
        }
      }
    })}>
  ))
</Mutation>
```

When we click the button and call the mutation, we get mutation call with the following variables:

```js
{
  "input": {
    "shipName": "B-Wing",
  }
}
```

And not this one:

```js
{
  "input": {
    "factionId": "1",
    "shipName": "B-Wing",
  }
}
```

Can we support this style as well?

**Comment by JoviDeCroock** [comment]
I think this is a good addition for nested mutations aswell :-)

**Comment by rosskevin** [comment]
If this is considered, this is related regarding defaults set directly on the client #2360

**Comment by danilobuerger** [comment]
Should a merge func be inlined or a dependency be added?

**Comment by rosskevin** [comment]
If it adds a lot of weight, perhaps see what inlining would look like.  Judgement call...

**Comment by hwillson** [comment]
Reasonable request - thanks @chentsulin! Using an inline merge function or dep doesn't matter that much to us, but bundle size does for sure. Using something like `lodash.merge` wouldn't be great for example, since it's almost 4k gzip'd. We're adding a nice and tight custom `mergeDeep` function to Apollo Client thanks to @benjamn (https://github.com/apollographql/apollo-client/pull/4338/files#diff-5138596e964b9a16ea1722e9481e2215), so it might be nice to share that. Marking as `help-wanted` - thanks!

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, React Apollo feature requests are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=%5BFeature%20Request%5D%20Deep%20merge%20Mutation%20variables&body=Migrated%20from:%20apollographql/react-apollo%232451) to start the feature request migration process. This manual migration process is intended to help identify which of the outstanding feature requests are still considered to be of value to the community. Thanks!
