### ISSUE TITLE
[Feature Request] Create dynamicVariables for mutation MockedProvider

### ISSUE THREAD

**Issue by gabrieluizramos** [apollographql/react-apollo#2466]
**Intended outcome:**
Use components at storybook, mocking a response for a mutation based on dynamic variables (e.g: using [HoC](https://www.apollographql.com/docs/react/api/react-apollo.html#graphql) that updates the variables and refetch the mutation) 

**Actual outcome:**
Was throwing an error like `no mocked responses for the query`
<img width="923" alt="screen shot 2018-10-03 at 11 10 24 am" src="https://user-images.githubusercontent.com/13336905/46416024-06ecae00-c6fd-11e8-9469-9d84e6624463.png">

**How to reproduce the issue:**
Creating a component with `MockedProvider` and using dynamic values as variables, such as: 
https://codesandbox.io/s/w27mz5r44w

**Version**

- apollo-boost@0.1.16
- react-apollo@2.1.11

---------------

Maybe, creating some kind of `dynamicVariables` inside the mocks array for mockedProvider would be a nice way to help these cases, as [PR 2467](https://github.com/apollographql/react-apollo/pull/2467)

**Comment by gabrieluizramos** [comment]
@hwillson Hi! Could help me with this Feature request (and the PR too), please? :)

**Comment by danilobuerger** [comment]
Feature requests and non-bug related discussions are no longer managed in this repo. Feature requests should be opened in https://github.com/apollographql/apollo-feature-requests.
