### ISSUE TITLE
[Feature request] Allow MockedProvider to pass down props to child component

### ISSUE THREAD

**Issue by miachenmtl** [apollographql/react-apollo#2470]
My use case is testing a component using the `Query` component that changes in response to a change in props. The problem is enzyme's `setProps` only works on the root node, so since I have to wrap the component in `MockedProvider`, the props only change for `MockedProvider`, not the component itself. If `MockedProvider` passed down other props to its child component, like the [React docs recommend for HOCs](https://reactjs.org/docs/higher-order-components.html#convention-pass-unrelated-props-through-to-the-wrapped-component), testing would be easy.

I realize that there is a workaround in separating out the component rendered by `Query` and testing that, but that seems to defeat the purpose of using the render props pattern instead of the `graphql` HOC.

- apollo-boost@0.1.16
- react-apollo@2.2.3

**Comment by JoviDeCroock** [comment]
The purpose of the render props is that it shares props with the parent component, so in non-testing there's not really a benefit to this in my opinion.

**Comment by miachenmtl** [comment]
I'm only suggesting a change to `MockedProvider`, so it's only supposed to be used in testing.

**Comment by miachenmtl** [comment]
I put together a PR showing what I mean. I've never worked with TypeScript before, so I apologize for the clumsiness in the code, but the idea is there. #2482

**Comment by danilobuerger** [comment]
Feature requests and non-bug related discussions are no longer managed in this repo. Feature requests should be opened in https://github.com/apollographql/apollo-feature-requests.
