### ISSUE TITLE
When the skip is set to true render prop function is being rendered anyway

### ISSUE THREAD

**Issue by kocur4d** [apollographql/react-apollo#2492]
**Intended outcome:**

When `skip` is true I would expect a query not to fire and the render prop function not to be rendered.

I am using a code from a tutorial:

```
const DogPhoto = ({ breed }) => (
  <Query
    query={GET_DOG_PHOTO}
    variables={{ breed }}
    skip={!breed}
  >
    {({ loading, error, data, startPolling, stopPolling }) => {
      if (loading) return null;
      if (error) return `Error!: ${error}`;

      return (
        <img src={data.dog.displayImage} style={{ height: 100, width: 100 }} />
      );
    }}
  </Query>
);
```

Initially `breed` prop is `null`

**Actual outcome:**

Query is not firing, but the render prop function is being rendered. Which causes error:

<img width="590" alt="screen shot 2018-10-10 at 18 13 56" src="https://user-images.githubusercontent.com/1427354/46753643-53fdf080-ccb8-11e8-881a-b8c71b1b865b.png">

Reason for the error makes sense since `data` hasn't been populated because the query didn't fire.
But shouldn't render be skipped as well when the `skip` is true?

**Version**

- aapollo-boost@0.1.16
- apollo-client@^2.4.2
- react-apollo@2.2.4

**Comment by JoviDeCroock** [comment]
I have hard of the same issue before, maybe a solution like having a prop named `isSkipping` would be in order. Where the library consumer can decide whether or not to render the body. Correct me if this is totally out of order.

**Comment by quentin-** [comment]
Isn't not wanting the query to fire and the render prop function not to be called is equivalent to simply not mounting the Query component in the first place?

```jsx
const DogPhoto = ({ breed }) => {
  if (!breed) { 
    return null 
  }

  return (
    <Query
      variables={{ breed }}
      query={GET_DOG_PHOTO}>
      {() => {}}
    </Query>
  );
);

**Comment by kocur4d** [comment]
@JoviDeCroock just to clarify you are suggesting to add another prop to the render prop function named `isSkipping`?

So that would imply that rendering render prop function when `skip` is `true` is a valid use case not a bug?

EDIT:

OK I know where my confusion is coming from. When I run it on codesandbox, as the tutorial suggest, `skip` was "behaving" the way how I was expecting it to behave and when I run the example locally it didn't.  I have assumed that there is a difference between versions and a bug.

The problem must be related to timing because when I run the code on codesandbox

https://codesandbox.io/s/6yn1ykl9lw

the `loading` prop is still set to `true` so the `if (loading) return null;` branch is being run.
I haven't checked `loading` and I have assumed that when `skip` is set to `true` it skips both query and the render.

If this is correct then @quentin solution is fine and I am happy to close this issue.

**Comment by kocur4d** [comment]
But on the other hand why is `loading` set to `true` in a codesandbox version if the `skip` was set to `true`. So no loading should be started in a first place.

**Comment by Kjagd** [comment]
@kocur4d This `loading` being `true` bug was fixed in 2.2.0 (https://github.com/apollographql/react-apollo/pull/1916), your sandbox is using an old version.

**Comment by kocur4d** [comment]
@Kjagd OK. Thank you. All makes sense now.

@JoviDeCroock going back to your initial question I think that introducing a new prop `isSkipping` is a good idea.

It would let us to do this:

```
const DogPhoto = ({ breed }) => (
  <Query query={GET_DOG_PHOTO} variables={{ breed }} skip={!breed}>
    {({ isSkipping, loading, error, data }) => {
      if (isSkipping) return null;
      if (loading) return null;
      if (error) return `Error!: ${error}`;
      return (
        <img
          src={props.data.dog.displayImage}
          style={{ height: 100, width: 100 }}
        />
      );
    }}
  </Query>
);
```
Small advantage of this over the @quentin solution would be to continue keeping the component as a simple `Query` component and be able to define prop function without a need to know the outside context, for example moving it to separate file etc.

What do you think?

**Comment by lorensr** [comment]
So the question is whether `isSkipping` is a large enough improvement to warrant another arg to the render prop. 

My personal inclination is to only use `skip` when I want the render prop to be called. And if I didn't, returning early:

```js
if (!breed) {
  return null
}

return (
  <Query query={GET_DOG_PHOTO} variables={{ breed }}>
```

>  Only point one could bring up (which is irrelevant to me personally) is that you have to replace your shorthand return to a normal function.

But I do take your point, that is nice. Let's see what others think.

**Comment by danilobuerger** [comment]
See also comment in source:
```
    // When skipping a query (ie. we're not querying for data but still want
    // to render children), make sure the `data` is cleared out and
    // `loading` is set to `false` (since we aren't loading anything).
```

`skip` does not query but render the children.
