### ISSUE TITLE
onCompleted callback typedef is not destructuring friendly

### ISSUE THREAD

**Issue by jozanza** [apollographql/react-apollo#2495]
**Intended outcome:**
I'd like to have a destructuring-friendly type definition for <Query> component's `onCompleted` callback property.

**Actual outcome:**

I want to be able to destructure the `onCompleted` callback argument in a type-safe way:

```ts
<Query<{ foo: string }> query={GetFoo} onCompleted={({ foo }) => {}} />
```
This works at runtime, but TypeScript complains about the definition of the parameter passed to the `onCompleted` callback:

```
[ts] Type '{} | { foo: string; }' has no property 'foo' and no string index signature.
```

![screen shot 2018-10-11 at 7 31 39 pm](https://user-images.githubusercontent.com/740794/46839532-66e1f500-cd8c-11e8-88b7-61f5ac3163e5.png)

**How to reproduce the issue:**

Check out this CodeSandbox: https://codesandbox.io/s/lpjj2pom0z

**Version**

- react-apollo@2.2.4

**Comment by JoviDeCroock** [comment]
Normally the callback provided in `onCompleted` is wrapped in an object named `data`. This implies the result from your completed Query. Since this is handled by Apollo you should be ensured of the answer or am i overlooking something here?

**Comment by jozanza** [comment]
@JoviDeCroock If I were to create a schema and connect Apollo, `foo` would indeed be a string. The data is there working properly, so that's awesome. No runtime issue 👍

The problem is that `onCompleted` is defined as 

```ts
(data: TData | {}) => void
```

So TypeScript thinks the `data` object passed to the callback is either `TData`, which I defined as `{ foo: string }` or, for no reason I can infer, an unindexed empty object `{}`.

Since that latter case is unindexed and does not contain my `foo` prop, destructuring fails static typing.

Does that make sense?

**Comment by jozanza** [comment]
@JoviDeCroock Is there anything you need me to change about this PR? Or can it be considered for merging?

**Comment by JoviDeCroock** [comment]
@jozanza I'm not a contributor or a member, just trying to help out where I can PR seems fine for me personally. I think the Apollo team is a bit swamped with the upcoming event.

**Comment by jozanza** [comment]
Ah sorry! Mybad.

**Comment by JoviDeCroock** [comment]
Made a small comment on your PR of something i just thought about :)

**Comment by andykenward** [comment]
For now, I define the typing for the argument directly to overcome this. 

```
<Query<QueryEditCompany, QueryEditCompanyVariables>
  query={COMPANY}
  onCompleted={(data: QueryEditCompany) => {//do something}
>
```
