### ISSUE TITLE
TypeScript declarations of Mutation.propTypes and MutationProps do not match

### ISSUE THREAD

**Issue by patrys** [apollographql/react-apollo#2500]
I've upgraded React to the following versions:

```
@types/react 16.4.16
@types/react-dom 16.0.9
```

It seems that `React.ComponentType` does a stricter type checking now on the `propTypes` attribute.

The following code no longer works:

```typescript
const StrictTypedMutation: React.ComponentType<
    MutationProps<TData, TVariables>
  > = Mutation;
```

**Intended outcome:**

The code above gives me a strictly typed alias of Mutation that I can use in JSX.

**Actual outcome:**

The assignment fails because `Mutation.propTypes` is missing two fields that appear in `MutationProps`: `context` and `ignoreResults`.

**How to reproduce the issue:**

Try the following code with any valid declaration of TData and TVariables:

```typescript
const StrictTypedMutation: React.ComponentType<
    MutationProps<TData, TVariables>
  > = Mutation;
```

**Version**

- apollo-client@2.4.2
- react-apollo@2.2.4

**Comment by rosskevin** [comment]
PR is welcome.

**Comment by danilobuerger** [comment]
The error I am getting is:
```
Types of property 'mutation' are incompatible.
          Type 'Validator<object>' is not assignable to type 'Validator<DocumentNode>'.
```
Which would mean, not only do we have to add `context` and `ignoreResults` but we would also have to shape everything.

**Comment by hwillson** [comment]
This should be resolved with current day versions of `react-apollo`. Thanks!
