### ISSUE TITLE
Cache-only fetchPolicy results in 4x renders

### ISSUE THREAD

**Issue by frederikhors** [apollographql/react-apollo#2505]
Original issue: https://github.com/apollographql/apollo-link-state/issues/289 from @pcmaffey.
Opened here because of @hwillson's request (https://github.com/apollographql/apollo-link-state/issues/289#issuecomment-429645149).

**Intended outcome:**

I would expect with cache only, it would render fewer times than cache-and-network.

**Actual outcome:**

With default cache-and-network, the render function runs twice (with no changes to data, loading, or networkStatus).
With cache-only, it runs 4x (also with no changes).

**How to reproduce the issue:**

Add fetchPolicy: 'cache-only' to TodoList query in examples. Then console.log(todos)...

**Version**

- apollo-client@2.4.2
- react-apollo@2.2.4

**Comment by hwillson** [comment]
This should no longer be an issue with current day versions of `react-apollo`. If this is still happening, definitely let us know. Thanks!
