### ISSUE TITLE
React StrictMode yields warnings

### ISSUE THREAD

**Issue by wes-r** [apollographql/react-apollo#2509]
```
componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: Mutation
```

React Blog post about this: https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

Looks like this is only used in a few spots in the codebase (excluding test code):
* [Mutation](https://github.com/apollographql/react-apollo/blob/62de2074fe01cde5d21dbfc582c5bb87c2011a36/src/Mutation.tsx#L135)
* [Subscriptions](https://github.com/apollographql/react-apollo/blob/e6fe3077c97d622c939cf6585838c385cd81b880/src/Subscriptions.tsx#L77)
* [Subscription-hoc](https://github.com/apollographql/react-apollo/blob/62de2074fe01cde5d21dbfc582c5bb87c2011a36/src/subscription-hoc.tsx#L54)
* [Query](https://github.com/apollographql/react-apollo/blob/5ea92e0fa98b6a9d660774c95fde5686c1f0b17a/src/Query.tsx#L199) -- Mentioned here: https://github.com/apollographql/react-apollo/pull/2076#issuecomment-412560567

**Version**

- apollo-client@2.3.5
- react-apollo@2.24

**Comment by JoviDeCroock** [comment]
Normally the upgrade to `componentDidUpdate` is rather small but the implications should be checked, I can check it out later this week if no one else wants to :)

**Comment by mike-marcacci** [comment]
This appears to already be addressed in the 3.0 alpha, and [I'm definitely interested in breaking out these changes](https://github.com/apollographql/react-apollo/pull/1742#issuecomment-402528780). I don't really see adoption of "async mode" [on the roadmap](https://github.com/apollographql/react-apollo/blob/master/ROADMAP.md), maybe somebody from the core team can comment?

**Comment by JoviDeCroock** [comment]
That PR/Branch seems pretty stale

**Comment by onpaws** [comment]
I enjoyed doing a [bit of experimenting](https://github.com/apollographql/react-apollo/issues/1912) with async Apollo back when 3.0.0-alpha.0 first appeared in March (and later, 3.0.0-alpha.2).

As the React team has regularly mentioned through the year, the public async API isn't finished. I recently noticed things indeed changed a bit as of 16.7.0-alpha -- if I'm not mistaken, `ReactDOM.unstable_deferredUpdates` should now be accomplished via `ReactDOM.createRoot()`.

I'm no expert but amidst these changes, the overall concepts seem to be stable (right?), community interest in this seems to remain high, and with the initial version of [Suspense shipping](https://reactjs.org/blog/2018/10/23/react-v-16-6.html#reactlazy-code-splitting-with-suspense) recently, I'm curious where concurrency falls on the apollo-react roadmap.

**Comment by onpaws** [comment]
This is what happened when I tried to use `<ApolloProvider>` in a new CRA-generated app, using `ReactDOM.createRoot()` in my index.js:
![image](https://user-images.githubusercontent.com/182515/47875835-586c8380-ddf6-11e8-97e5-7d1f64cc2e18.png)

So yeah, a StrictMode warning. I am hardly qualified to comment -- based on that warning it looks like there will be at least some work needed to adopt the new Context API? (I imagine that's already started somewhere on this repo...)

Would be nice if someone from the Apollo team in a position to know could chime in. Would be happy to contribute to the effort, just need some help identifying what it will take to get us to 3.0.0-alpha.3.

@jbaxleyiii @peggyrayzis

\* specific versions:
react-apollo v2.3.4
react & react-dom v16.7.0-alpha
react-script 2.1.1

**Comment by rosskevin** [comment]
Please feel free to enable strict mode and submit PRs to update components. Every little bit helps.

**Comment by Viperwow** [comment]
Is there any plans to fix this issue in the nearest future?

**Comment by hwillson** [comment]
The [RA 3 release](https://github.com/apollographql/react-apollo/pull/2892) (coming soon) will address all warnings. Thanks!
