### ISSUE TITLE
[Typescript]: Change children prop to optional

### ISSUE THREAD

**Issue by cncolder** [apollographql/react-apollo#2515]
**Intended outcome:**
```tsx
<Query query={MY_TASKS} />
```

The components `Query` `Mutation` and `Subscription` works without `children` prop. But type definition mark them as `required`.

Query component without children maybe use for warm up data?

I need this because `react-adopt`.

```tsx
adopt({
    // myTasksQuery: <Query query={MY_TASKS} />
    // to avoid type warn, you must pass render arg to children prop.
    myTasksQuery: ({ render }) => <Query query={MY_TASKS} children={render} />
})
```

**Actual outcome:**
```shell
# tsc error:
missing children prop
```

**How to reproduce the issue:**

**Version**

- apollo-client@<version number>
- react-apollo@2.2.4

**Comment by rosskevin** [comment]
The general use case (greater than 80%) is that you need to provide children to make use of the component.  I suggest you create a wrapper to suit your own case, as we cannot solve all issues.

The lack of children error for the > 80% use case is a good signal.  I don't think there is anything to be done here.  I'm also not sure that providing noop wrappers is a worthwhile thing to do in this lib.

I'm open to changing my mind but the current types used solve for the majority.
