### ISSUE TITLE
Using cached data across queries

### ISSUE THREAD

**Issue by mmahalwy** [apollographql/react-apollo#2528]
**Intended outcome:**
Given two queries happening at the same time:
```javascript
const GET_PERSON_WITH_NAME = gql`
  query Person($id: ID!) {
    person(id: $id) {
      id
      name
    }
  }
`;
const GET_PERSON_WITH_AGE = gql`
  query Person($id: ID!) {
    person(id: $id) {
      id
      age
    }
  }
`;
function ShowPerson() {
  return (
    <div>
      <Query query={GET_PERSON_WITH_NAME} variables={{ id }}>
        {({ data }) => <div>{data.person.age}</div>}
      </Query>
      <Query query={GET_PERSON_WITH_AGE} variables={{ id }}>
        {({ data }) => <div>{data.person.name}</div>}
      </Query>
    </div>
  );
}
```

One would expect that the data in the cache/store would be shared across the various queries for a given object, in this case a `Person`. Notice that the first query will not actually get access to `.age` although it is in the case from the `GET_PERSON_WITH_AGE` query. The expectations are since they are in the store, they should be accessible. 

My assumption is this should work, but not ideal?
```javascript
function ShowPerson() {
  return (
    <div>
      <Query query={GET_PERSON_WITH_NAME} variables={{ id }}>
        {({ data, client }) => (
          <div>
            {
              client.readFragment({
                id: `Person:${id}`,
                fragment: gql`
                  fragment Person on Person {
                    id
                    name
                    age
                  }
                `,
              }).person.age
            }
          </div>
        )}
      </Query>
      <Query query={GET_PERSON_WITH_AGE} variables={{ id }}>
        {({ data }) => <div>{data.person.name}</div>}
      </Query>
    </div>
  );
}
```
Is this the correct way? My feeling is this is a solution: https://www.apollographql.com/docs/react/features/performance.html#query-splitting although not an ideal outcome when you want different queries to add to the cache while being able to access cache data anywhere without a fetch. 

**Actual outcome:**

**How to reproduce the issue:**

**Version**

- apollo-client@<version number>
- react-apollo@2.2.3

**Comment by rosskevin** [comment]
Your original code should be using the same entity from cache but it requests different information so it will always be two network requests.

```
function ShowPerson() {
  return (
    <div>
      <Query query={GET_PERSON_WITH_NAME} variables={{ id }}>
        {({ data }) => <div>{data.person.age}</div>}
      </Query>
      <Query query={GET_PERSON_WITH_AGE} variables={{ id }}>
        {({ data }) => <div>{data.person.name}</div>}
      </Query>
    </div>
  );
}
```

If you fired another query requesting name and age after these, it would read from cache.
