### ISSUE TITLE
getDataFromTree breaks again with React v16.6

### ISSUE THREAD

**Issue by serwer-WittGruppe** [apollographql/react-apollo#2530]
**Intended outcome:**

We updated to React v16.6 and saw that `getDataFromTree` is not hitting our routes behind `@reach/router` anymore. The router seems to be quite heavy at using the new Contect and `forwardRef`. Possibly something internally changed in React.

**Actual outcome:**

Data is generally being fetched for components outside of the routing root e.g. our navigation structure is loaded correctly via GraphQL. Previously we saw two of our resolvers doing requests (navigation + page content) we now see only one.

**How to reproduce the issue:**

In browser demonstration is actually impossible as this is an SSR issue.

I think easiest would be to use some `Query` inside of `@reach/router`s routing system.

**Version**

- apollo-client@2.4.3
- react-apollo@2.2.4

It works fine going back to React v16.5.2 BTW.

**Comment by benjamn** [comment]
The implementation of `getDataFromTree` has changed substantially in `react-apollo@2.3.1` (the latest version), thanks to #2533. Please try updating, and let us know if this is fixed!

**Comment by serwer-WittGruppe** [comment]
Looks good to me. Only error handling is still quite cumbersome in SSR cases.
