### ISSUE TITLE
Mutation callbacks not called if component re-rendered immediately before calling mutation

### ISSUE THREAD

**Issue by leanne2** [apollographql/react-apollo#2531]
**Intended outcome:**

onCompleted or onError mutation callbacks always called

**Actual outcome:**

When using a mutation render props inside render(), onCompleted or onError mutation callbacks are not called and mutation data (e.g networkStatus etc) not updated if the component is re-rendered immediately before calling the mutation. This could be, for example, by calling setState immediately before calling the mutation

**How to reproduce the issue:**

Create a react component with a method callMuation()
In render() include a mutation render prop, 
Include a button whose onClick handler, when called calls this.callMutation, passing the the mutation render prop method as an argument to this.callMuation
In this.callMutation, call this.setState() or this.forceUpdate() to trigger a re-render then immediately call the mutation prop function. In this scenario, the mutation fires and any update methods are fired, but onCompleted or onError do no get called. Also the mutation data does not get updated e.g. loading and error render props
 
**Version**

- apollo-client@2.4.2
- react-apollo@2.2.3

**Comment by Rkuro** [comment]
I just ran into this issue also, my solution was to make the onClick handler asynchronous and then wait for the mutation function.

```
class foo extends React.Component {
  
  state = {
    bar:false
  }  

  handleClick = async (mutationFn:MutationFn) => () => {
      await mutationFn(...variables)
      this.setState({bar:true})
  }    

  render () {
        ... Button here somewhere ...
       <Button onClick={this.handleClick(mutationFn)}/>
  }

}
```

Hope this helps.  Definitely not expected behavior from the client.

**Comment by rosskevin** [comment]
We cannot control or change the react component lifecycle or control a parent's rerendering.  Therefore, I don't think there is any action we can take here.  If I am mistaken and there is something actionable that can be done please ping me and I will reopen.

**Comment by dafapramudya** [comment]
Hi @rosskevin i have the same problem too. Here is my code:

https://gist.github.com/dafapramudya/98684603c3c465713f9c26858655ab62

So the problem is in ternary operation. When mutation is success, it will update data.topup.Status, and then onCompleted doesn't run because data.topup.Status is changed.

Can u help me pls? Thank you
