### ISSUE TITLE
Stop checking graphql operation type in Query and Mutation components

### ISSUE THREAD

**Issue by dyst5422** [apollographql/react-apollo#2542]
I have a query that I do that I want to fire on click.

```graphql
query JoinGame($gameId: String!) {
    game(gameId: $gameId) {
      joinGame {
        id
      }
    }
  }
```

Is there a technical reason the component needs to check the operation type? Because right now, I'd have to go the ApolloConsumer route and that is quite obnoxious to have to do. Previously, I was using the Mutation component to do this, some update started checking the operation type though and throwing.

Additionally, I can't specify refetchQueries with a client.query() operation. This is incredibly limiting.

**Comment by JoviDeCroock** [comment]
I can't really see how this would improve t he quality of life. You are using a Query as a Mutation this is more of a backend consistency issue than a library one.

Even IF you say that theoretically you query the game you are doing a mutation by joining the game.
