### ISSUE TITLE
refetch prop of Query doesn't trigger loading state

### ISSUE THREAD

**Issue by olalonde** [apollographql/react-apollo#2560]
I noticed that calling refetch doesn't set loading to true in the Query component's children function.

**Comment by OHUSAR** [comment]
Just checking, but don't you need to pass the notifyOnNetworkStatusChange prop to Query component? Because otherwise your component won't get rerendered on network status change and you won't be able to proprely detect loading state.

e.g.
```
 <Query>
     query={query}
     notifyOnNetworkStatusChange={true}
    >
```

**Comment by hwillson** [comment]
This doesn't seem to be an issue, so I'll close it for now. Happy to re-open if there is still a problem here. Thanks!
