### ISSUE TITLE
How do you use 2 clients pointing to separate graphql servers?

### ISSUE THREAD

**Issue by jloveric** [apollographql/react-apollo#2567]
I want 2 clients that each point to a different graphql server.  It appears that the example will only work with one server.  How do I create 2 clients, each pointing to a different graphql server?

**Comment by OurMajesty** [comment]
You can use `ApolloLink.split`  

```
ApolloLink.split(
    ({ operationName }) => operationName == 'GetAttributes',
    attributesHttpLink,
    anotherStuffHttpLink,
)
```

https://www.apollographql.com/docs/link/composition.html#directional

**Comment by rosskevin** [comment]
You can also create two different clients and provide the explicitly to components such as Query or provide the different clients to different render trees via different Apollo-client so.

**Comment by arindamINT** [comment]
**It is as simple as that**

```
const apolloclient = new ApolloClient({
    link: ApolloLink.split(
      operation => operation.getContext().clientName === "second", // Routes the query to the proper client
      secondLink,
      firstLink
    ),
    cache: new InMemoryCache().restore(initialState || {})
  })
}
```
**An this the calling part of the mutation/query**

>  const [blogListFn, { loading: blogLoading }] = useLazyQuery(blogList, {
>         context: { clientName: 'graphCms' },
>         onCompleted: (data) => {
>             console.log('blogListFn', data);
>         },
>         onError: ({ graphQLErrors, networkError }) => {
>             if (graphQLErrors) {
>                 if (graphQLErrors.length > 0) notify(graphQLErrors[0].message, 'error');
>             } else if (networkError) {
>                 notify('Please check your network connection!', 'error');
>             }
>         },
>     });
