### ISSUE TITLE
Typescript graphql() hoc issue with option.prop and ChildDataProps typings

### ISSUE THREAD

**Issue by slorber** [apollographql/react-apollo#2568]
**Intended outcome:**

The documentation TS examples should work.

**Actual outcome:**

The documentation TS examples do not compile due to typings related to the "prop" option and ChildDataProp

https://www.apollographql.com/docs/react/recipes/static-typing.html#props

**How to reproduce the issue:**

Create a project with the example here: https://www.apollographql.com/docs/react/recipes/static-typing.html#props

**Version**

- apollo-client@latest
- react-apollo@latest

**Comment by slorber** [comment]
cc @danilobuerger? 

This compile with:

```js
type ChildProps = ChildDataProps<InputProps, Response, Variables>;

const withCharacter = graphql<InputProps, Response, Variables, ChildProps>(HERO_QUERY, {
  options: ({ episode }) => ({
    variables: { episode }
  }),
  props: ({ data, ownProps }) => {
    const props: ChildProps  = { data: data!, ...ownProps }
    return props;
  }
});
```

alternatively I could write my own ChildProps type.

Also note that prop receives an optional `DataProp<>` type, which can be undefined, while the ChildDataProp expect it to always be there.

I'm a typescript newbie but from what I understand I suspect we should rather have something like `type ChildDataProps = TProps & (DataProps<TData, TGraphQLVariables> | undefined)`. Current form of ChildDataProps seems not really helpful.

Also note that the example repo does not contain any TS example based on the graphql HOC. This would be helpful to ensure the types are correct.

https://github.com/apollographql/react-apollo/tree/master/examples/typescript/src

**Comment by RIP21** [comment]
I've got these issues as well.
it says that data is `DataProps<TData, ...> | undefined` that's why when you try to spread `data` you fail to do so since everything is red and you need to cast it.
Problem is that `OptionProps` extends `DataProps` and `MutateProps` but wrapped in `Partial`, hence all fields get `| undefined` after them.
So fix to the problem effectively is to remove `Partial` type helper. And everything is start to work just fine.

Like that.
```typescript
export interface OptionProps<TProps = any, TData = any, TGraphQLVariables = OperationVariables> extends DataProps<TData, TGraphQLVariables>, MutateProps<TData, TGraphQLVariables> {
    ownProps: TProps;
}
```

**Comment by danilobuerger** [comment]
Not a great idea, as then both `data` and `mutate` are typed as being set, but are actually not (depending on the document used).

**Comment by RIP21** [comment]
Casting is a better idea?

**Comment by danilobuerger** [comment]
Personally, I think the easiest fix without breaking would be exporting the mutation, query, subscription hocs while keeping the generic graphql hoc. Then tightening the typing of the newly exposed hocs.

**Comment by RIP21** [comment]
@danilobuerger this sounds like a good idea indeed. Because right now it's hell on earth, especially for people who are not heavily familiar with TS.

**Comment by danilobuerger** [comment]
@slorber @RIP21 Please see (and support)  https://github.com/apollographql/react-apollo/pull/2573

**Comment by slorber** [comment]
great thanks @danilobuerger

I don't know if this is even related, but can someone explain me how to handle mutation results in a typed way?

```js
export const deleteOrderMutation = async (orderId: Id): Promise<Id> => {
  const result = await AppApolloClient.mutate<
    DeleteOrderMutation,
    DeleteOrderMutationVariables
  >({
    mutation: gql`
      mutation DeleteOrderMutation($orderId: ID!) {
        deleteOrder(orderId: $orderId)
      }
    `,
    variables: {
      orderId,
    },
  })
  return result.data!.ICANPUTWHATEVERIWANTHERE.id
}
```

I'm not totally sure to understand the types and not sure either to have seen a typescript example of this in Apollo examples. Any idea?

**Comment by RIP21** [comment]
@slorber I think it's more about `apollo-client` than about `react-apollo` but I think you can get typed result if you will say
```typescript
if(result.data !== null && result.data !== undefined) {
  return result.data.id // Inside there it will be typed to the data type here and not null if you have null | SomeType type of data
}
```
If i'm not wrong `!` syntax is to reduce things above when developer kind of "I know what I'm doing".

**Comment by RIP21** [comment]
Another option in addition to [this comment](https://github.com/apollographql/react-apollo/issues/2568#issuecomment-436695135) that make typing a bit better until PR above is not merged is to use.
```typescript
import { mutation } from 'react-apollo/mutation-hoc' // import directly mutation-hoc

// Use it instead of `graphql`
mutation<
    TProps,
    CreateMessageMutation,
    CreateMessageVariables,
    CreateMessageProps<TChildProps>
  >(CreateMessageDocument, operationOptions)
```
