### ISSUE TITLE
Loading = true, when it should be false

### ISSUE THREAD

**Issue by jacargentina** [apollographql/react-apollo#2575]
**Intended outcome:**
Query `Loading = false`

**Actual outcome:**
Query `Loading = true`

**How to reproduce the issue:**
My simple app gets stuck with the "loading indicator" event when data is already there
Reproduction repo here https://github.com/jacargentina/react-apollo-error-template
Simply run `npm start`
Then play searching with terms Smith, Deey... clear some letters... wait... After some tries the bug would be visible. **Loading never quits**

**Version**

- apollo-client@2.3.1
- react-apollo@2.1.4

**Comment by strongpauly** [comment]
I am seeing this too with react-apollo@2.2.4

**Comment by anied** [comment]
I think this is probably a duplicate of https://github.com/apollographql/react-apollo/issues/1931 , which I am also encountering.

**Comment by hwillson** [comment]
Closing as a duplicate of https://github.com/apollographql/react-apollo/issues/1931. Thanks!
