### ISSUE TITLE
feature?: config to override default value to `true` for partialRefetch

### ISSUE THREAD

**Issue by benmosher** [apollographql/react-apollo#2576]
**Intended outcome:**

Use `<Query>` component without remembering to set `partialRefetch` to `true` 100% of the time.

**Actual outcome:**

Can't remember to use `partialRefetch` and see mysterious "failure" to load data for valid queries whose cached data has been invalidated by mutations.

**How to reproduce the issue:**

I was hoping that I could set `partialRefetch: true` in my Apollo client construct, but looking into the code it became clear that `partialRefetch` is implemented in the `Query` component itself instead of the core client. 

I did not find any precedent for overriding default Query props so I'm not sure what I'm even asking for. 

**Version**

- apollo-client@2.4.5
- react-apollo@2.2.4

**Comment by SnidelyWhiplash** [comment]
Agreed, the default for `partialRefetch` should definitely be overridable, especially given that the docs state the following:
>The default value is false for backwards-compatibility’s sake, but should be changed to true for most use-cases.

According to the [Apollo Client constructor docs](https://www.apollographql.com/docs/react/api/apollo-client.html#apollo-client), we _can_ set default query options for `fetchPolicy`, `errorPolicy`, and I think a couple others, but the following does not work:
```js
const client = new ApolloClient({
  cache,
  defaultOptions: {
    query: { // or `watchQuery`
      partialRefetch: true,
    },
  },
})
```

**Comment by benmosher** [comment]
Just ran into another bug caused by this. Until there is an official solution or an updated version with partialRefetch always on by default, I have found that this does the trick:

```js
// file: src/apollo/hacks.js
// this file is imported by the entry point before any React code runs

import { Query } from 'react-apollo'

/**
 * partialRefetch should always be true, but it defaults to false for reasons
 * that are totally unimaginable to me. this hacks it on for us.
 * 
 * note: today, Query has no defaultProps but this Object.assign ensures it works either way
 * and will explicitly override any current or future value for `partialRefetch`.
 */
Query.defaultProps = Object.assign({}, Query.defaultProps, { partialRefetch: true })

// note: DEBUG is injected globally by web pack to be roughly equivalent to `process.env.NODE_ENV!=="production"`
// so this assertion is minified out of production builds
if (DEBUG && !Query.defaultProps.partialRefetch) {
  throw new Error("Unable to default partialRefetch for Apollo Query component.");
}
```

**Comment by Niondir** [comment]
Same for me, did cost me half a day to find the option. Now I would love to set it as default option in the client.

**Comment by danilobuerger** [comment]
Thanks for your interest in helping make Apollo Client better!

Feature requests and non-bug related discussions are no longer managed in this repo. Feature requests should be opened in https://github.com/apollographql/apollo-feature-requests.

**Comment by HugoLiconV** [comment]
could someone explain me the use of partialRefetch? It isn't clear for me
