### ISSUE TITLE
react-apollo-browser.umd.js requiring react-dom/server on react native

### ISSUE THREAD

**Issue by lijtong** [apollographql/react-apollo#2592]
**Intended outcome:**

When using react-apollo with a react-native app (specifically an expo app), the app should be able to successfully build and run

**Actual outcome:**

Expo app is unable to build, throwing this error:
`Unable to resolve "react-dom/server" from "node_modules\react-apollo\react-apollo.browser.umd.js"`

So it seems like the newest version(s) of react-apollo is incompatible with react native due to react-apollo.browser.umd.js

![image](https://user-images.githubusercontent.com/10734512/48643694-36960380-e995-11e8-9b4e-1b39228d4ef6.png)

**How to reproduce the issue:**

1. Create a new expo app
2. npm install react-apollo
3. Import ApolloProvider from react-apollo
4. Run expo start and open app on expo client on device

Issue reproduced on expo snacks

App throwing react-dom/server error:
https://snack.expo.io/@lijtong/apollo-new-umd

App without react-dom/server error:
https://snack.expo.io/@lijtong/apollo-old-umd

It seems to be these lines specifically (version 2.3.1):
`    typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('react-dom/server'), require('apollo-client'), require('prop-types'), require('react')) :`
`    typeof define === 'function' && define.amd ? define(['exports', 'react-dom/server', 'apollo-client', 'prop-types', 'react'], factory) :`

Whereas the version that works (2.1.11) has:
`    typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('react'), require('prop-types'), require('apollo-client')) : `
`    typeof define === 'function' && define.amd ? define(['exports', 'react', 'prop-types', 'apollo-client'], factory) :`

**Version**

Working versions
- apollo-client@<2.3.8>
- react-apollo@<2.1.11>

Incorrect UMD versions
- apollo-client@<2.3.8>
- react-apollo@<2.3.1>

**Comment by benjamn** [comment]
Any idea why React Native would not be able to understand `require('react-dom/server')`? Does it not fully support CommonJS? This is especially bizarre because it's a miscommunication between ReactDOM and React Native, which are maintained by the same vendor (if not the same teams).

**Comment by benjamn** [comment]
Just to be clear: requiring `react-dom/server` is intentional, per #2533. The `react-dom` package has a [`package.json`](https://github.com/facebook/react/blob/a22fabc2a110a40ead576ada5b3bf66840e852ba/packages/react-dom/package.json#L37-L39) file with
```json
browser: {
  "./server.js": "./server.browser.js"
}
```
which means importing `react-dom/server` in a browser-like environment should be perfectly safe (as promised by [these docs](https://reactjs.org/docs/react-dom-server.html#overview)).

**Comment by lijtong** [comment]
Upon testing with the snack, if react-dom is added into the previous non-working snack it is able to resolve correctly.

https://snack.expo.io/@lijtong/apollo-new-umd

Whereas on my app it throws the follow error:
`The package at "node_modules\react-dom\cjs\react-dom-server.node.production.min.js" attempted to import the Node standard library module "stream". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq.html#can-i-use-nodejs-packages-with-expo`

The snack is running on expo sdk 31 and react-native 0.57, while my app is running on sdk 29 and react-native 0.55.4 so I assume it's to do with the older react-native version

**Comment by benjamn** [comment]
Oh, this is much simpler than I realized! In #2533 we forgot to include `react-dom` as a dependency (rather than just a dev dependency) of `react-apollo`, I think. At least I hope that's all it is.

**Comment by nemcek** [comment]
I actually have a very similar problem right now. Why bundling my app I get an error:
```error: bundling failed: Error: Unable to resolve module `stream` from `<path-to-project>\node_modules\react-dom\cjs\react-dom-server.node.production.min.js`: Module `stream` does not exist in the Haste module map```

I was able to track it down to react-apollo.

**Comment by renato-bvdash** [comment]
I am having the same issue. I uninstalled and reinstalled react-apollo and nothing.

**Comment by benjamn** [comment]
@lijtong Ok, your https://snack.expo.io/@lijtong/apollo-new-umd app now works for me with the following `package.json`:
```json
{
  "dependencies": {
    "apollo-client": "^2.3.8",
    "graphql": "^14.0.0",
    "react-apollo": "2.3.2-beta.0",
    "react-native-paper": "2.1.3",
    "react-dom": "16.6.3"
  }
}
```
The key being `react-apollo@2.3.2-beta.0` and the presence of `react-dom` (which is now enforced as a peer dependency).

**Comment by lijtong** [comment]
It seems like the expo snack behaves differently than my production app, I'm still receiving this error:

`The package at "node_modules\react-dom\cjs\react-dom-server.node.production.min.js" attempted to import the Node standard library module "stream". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq.html#can-i-use-nodejs-packages-with-expo`

Currently running using 
` 
   "graphql": "^14.0.2",
   "react-apollo": "^2.3.2-beta.0",
   "react-dom": "^16.6.3",
`

I agree with your previous sentiment that it's really odd for react native not being able to support react-dom, but even with the peer dependency it doesn't seem to fix the production app. The snack is able to use it without error...

**Comment by b33son** [comment]
Hit the same error today following the Apollo Client setup guide but on a React Native project: https://www.apollographql.com/docs/react/essentials/get-started.html

Adding "react-dom": "16.6.3" to dependencies + npm install fixed it for me too.

**Comment by nemcek** [comment]
Still the same problem as @lijtong

**Comment by AnselmMarie** [comment]
I was getting the same problem as @lijtong and @nemcek with the "stream" error. Since I'm using Expo I updated the SDK to 31 including the dependencies below and it worked. SDK 31 adds some cool additions but drops iOS 9 and Android 4.4. https://blog.expo.io/expo-sdk-v31-0-0-is-now-available-cad6d0463f49

```
{
  "dependencies": {
    "apollo-client": "^2.4.6",
    "graphql": "^14.0.2",
    "react-apollo": "2.3.2-beta.0",
    "react-dom": "16.6.3"
  }
}
```

**Comment by svegan** [comment]
Same here. Pure app, not expo. Installing react-dom and beta.0 or beta.3 of react-apollo did not help.

**Comment by benjamn** [comment]
Multiple commenters have suggested that React Native 0.57 (Expo SDK 31) works, whereas previous versions of React Native have problems importing the Node built-in `stream` module.

Is there anything keeping you from updating to the latest version of React Native?

**Comment by lijtong** [comment]
Not in particular, updating to the newer SDK can take a bit of time to test for any breaking functionality and incompatibility with our other packages.

**Comment by jpaas** [comment]
I was already on 0.57.3. I tried upgrading to 0.57.5 and it didn't help

**Comment by erodactyl** [comment]
Adding react-dom as a dependency to my project worked. Can you please fix this? I don't want to have react-dom as a dependency in a react native project

**Comment by WillsonHaw** [comment]
I also have the same issue using react-apollo in fuse-box using SSR.

**Comment by nenti** [comment]
When suddenly without any dependency change your react-native project is not working anymore with an untracable error message, it is time to remove `^` from dependencies.

Downgrading `react-apollo` solves the issue for now. Working setup until bugfix is:
``` js
{
  "dependencies": {
    "apollo-client": "2.4.7",
    "react-apollo": "2.2.4",
  }
}
```
Thank you for your hard work on this awesome software package anyways. :)

**Comment by benjamn** [comment]
We're trying a different strategy in the latest beta (`react-apollo@2.3.2-beta.4`), which should make everyone happy (🤞): https://github.com/apollographql/react-apollo/pull/2627

In short, the React Native bundler will now ignore dependencies on `react-dom/server` within the `react-apollo` package, so importing `react-apollo` in your React Native app should no longer require `react-dom` to be installed.

Please try running
```bash
npm install react-apollo@2.3.2-beta.4
```
and report your results in #2627 (along with whatever version of React Native and/or the Expo SDK you're using)!

**Comment by xerotolerant** [comment]
@benjamn This update worked for me. I am react native 0.57.5

**Comment by benjamn** [comment]
Just published `react-apollo@2.3.2` as the `next` version on npm. We will promote it to `latest` soon, pending confirmation that this version solves folks' problems. Please give it a try!

**Comment by ujwal-setlur** [comment]
@benjamn version 2.3.2 works for me, thanks!

**Comment by MLDimitry** [comment]
Version 2.3.2 looks to be working for me.

With react-native v0.57.6

**Comment by b33son** [comment]
Update works!
