### ISSUE TITLE
`cache-first` is showing data from three days ago

### ISSUE THREAD

**Issue by lukepighetti** [apollographql/react-apollo#2600]
Hey all,

I'm using `cache-first` because it is the default and I'm noticing that cached data is three days old. Had to switch to a different policy and can't seem to set a default in `Apollo-boost`. Seems like a serious issue. 

Would really benefit from a TTL for both `cache-first` and `cache-and-network`

I would *LOVE* to set a 1m TTL for `cache-and-network` to get a better balance of performance, as well as for `cache-first` so my users aren't looking at data from three days ago.

**Comment by rosskevin** [comment]
Please file an issue for the apollo-client, it has the caching functionality.  You could use client.resetStore() on a timer if you need to wipe the store in the interim.
