### ISSUE TITLE
Element Query doesn't have required attribute

### ISSUE THREAD

**Issue by jurajkrivda** [apollographql/react-apollo#2608]
In react-apollo 2.3.1 I have this issue: Element Query doesn't have required attributes client, fetchPolicy, onError etc.

My usage of Query component

```
<Query query={query}>
....
</Query>

**Comment by ChristophDietrich** [comment]
Hello Team,

i'm running also into this TS Error in my Webstorm with react-apollo 2.3.2 also, when i use 2.3.1 before it also throws an error on TS Lint check, but after updating to 2.3.2 version the TS Lint check on the webpack dev server is fine. It stays in Webstorm.

Its quite confusing. Hopefully someone say a solution, how to config this. 💛  

`TS2741: Property '[Invalid_propTypes]' is missing in type '{ children: ({ loading, error, data }: QueryResult<any, OperationVariables>) => Element; query: any; fetchPolicy: "network-only"; }' but required in type 'Invalid_propTypes<Readonly<{ children?: ReactNode; }> & Readonly<QueryProps<any, OperationVariables>>, { children: Validator<(...args: any[]) => any>; fetchPolicy: Requireable<string>; notifyOnNetworkStatusChange: Requireable<...>; ... 5 more ...; ssr: Requireable<...>; }>'.
`

**Comment by romucci** [comment]
Disable the inspection. :D

**Comment by rosskevin** [comment]
I'm not sure of the problem based on the information provided.  If you can provide a codesandbox with a reproduction just ping me and I'll reopen.  As-is, our ci tests this usage at length without a problem.
