### ISSUE TITLE
mutating proxy.readQuery({ query }) results in re-render of components

### ISSUE THREAD

**Issue by Dumlias** [apollographql/react-apollo#2617]
**Intended outcome:** the object returned by proxy.readQuery({ query }) in a mutate's update function shouldn't trigger re-renders of components when mutated, for performance and stability reasons.

**Actual outcome:** Mutating the object returned by proxy.readQuery({ query }) triggers re-renders across components sharing the query's cached data. Surely this isn't meant to happen - presumabely this is why we have the writeQuery method.

I see this either as a bug or lacking information in the docs - as the docs' own example mutates the data returned by readQuery, I'm assuming it isn't meant to be treated immutably. Mutating data without registering it (via writeQuery or analogically via setState in vanilla react) shouldn't by itself trigger a re-render anywhere and it is not clear what internal mechanism of apollo causes this to happen (how does it even keep track of such direct changes?).

**How to reproduce the issue:** Go to the docs segment about updating after mutation : https://www.apollographql.com/docs/react/api/react-apollo.html#graphql-mutation-options-update
comment out the writeQuery line like so : 
```
options: {
    update: (proxy, { data: { createTodo } }) => {
      const data = proxy.readQuery({ query });
      data.todos.push(createTodo);
      // proxy.writeQuery({ query, data });
    },
  }
```
and witness a re-render in any components sharing the query's cache.

**If this is not a bug but a misunderstanding on my part, I would appreciate some explanation about this mechanism  or a tip on where to find such information.**

**Version**

- apollo-client@5.6.0
- react-apollo@5.6.0

**Comment by glynkwei** [comment]
If I'm understanding this correctly, this is expected and has nothing to do with readQuery. When a mutation finishes, the data response from the mutation is written into the cache. Any queries that had its data changed will then rerender. The update option just gives you finer control over the cache (via read/writeFragment and read/writeQuery) before this query check takes place.

**Comment by TheoMer** [comment]
OS: Windows 10 Pro
apollo-boost": "^0.1.16"   
apollo-client": "^2.4.2"   
react-apollo": "^2.2.1"

@Dumlias I am having this exact same problem, which I have posted here:  https://stackoverflow.com/questions/53725029/apollo-push-method-causing-component-to-unmount-on-optimisticresponse-update

I have narrowed things down to it being the push() method where the wheels fall off and the component un-mounts. If you comment out `data.todos.push(createTodo);` and do:

```
proxy.writeQuery({ 
  query, 
  data: {
     createTodo
  }
});
```
does your component re-render (un-mount), or does it, as is the case in my instance, write the data to cache but not instantly as is the case with push()?

**Comment by rosskevin** [comment]
@Dumlias you succinctly stated it here:

> mutating the object received from readQuery changes the cache and re-renders my components with or without writeQuery

This may have been done for performance reasons e.g. avoiding a deep copy result returned from `readQuery` which can be expensive. 

Either way, this is an issue you will have to take up in the apollo-client repository.  react-apollo uses the observable to trigger updates to rendering, and if you alter the observable, it will cause a rerender.
