### ISSUE TITLE
Query component doesn't update variables

### ISSUE THREAD

**Issue by lifeiscontent** [apollographql/react-apollo#2623]
**Intended outcome:**

when calling fetchMore, I'd expect the variables that are returned from a `Query` component to be updated as well.

**Actual outcome:**

variables are not updated as render props after calling fetchMore.

this isn't idea, because calling setState to update the variables will cause a rerender to the entire tree vs just the part of the tree the `Query` component is the root of.

**How to reproduce the issue:**

create a query component, use fetchMore and console.log the variables that come from the render props in a `Query` component.

**Version**

- apollo-client@alpha
- react-apollo@alpha

**Comment by Memfisrain** [comment]
I have the same issue.

I need to get actual variables in order to make user of `writeQuery` with pagination.

If you know any solution we can do this please let me know

**Comment by pleunv** [comment]
There's a long-standing issue around this subject [here](https://github.com/apollographql/apollo-client/issues/2499).

**Comment by FunkSoulNinja** [comment]
maybe this will help. I found a workaround and posted it here: https://github.com/apollographql/apollo-client/issues/2499#issuecomment-468879255

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
