### ISSUE TITLE
Cannot get Query to re-render when testing click event

### ISSUE THREAD

**Issue by djamiem** [apollographql/react-apollo#2626]
I have a React container that has a Query nested inside a mutation. I can test that the initial render works by using MockedProvider to pass through mocked responses for the Mutation and the Query.

For instance, on the initial render I am mocking the query to return a message, like "TEST MESSAGE".

When I click a button inside of MyComponent, it does call into the mutationFn(), I have verified that with a console.log, but the Query does not re-render with the new message as 'null'

I would like to make sure that when clicking a button, either the child component's props update from the Query or the Mutation's return function get called.

The react container (simplified):
```
class MyContainer extends PureComponent {
  public render() {
    return (
      <Mutation mutation={MY_MUTATION}>
        {(mutationFn) => {
          return (
            <Query query={MY_QUERY}>
              {({ data, loading, error }: QueryResult<IAppUIQuery>) => {
                if (loading || error || !data || !data.appUI || !data.myQuery.message) {
                  return null;
                }
                const message = data.myQuery.message;

                return (
                  <MyComponent
                    message={message}
                    closeButtonClick={this.createCloseButtonHandler(mutationFn)}
                  />
                );
              }}
            </Query>
          );
        }}
      </Mutation>);
  }

  private createCloseButtonHandler = (mutationFn: MutationFn<null, IVars>) => {
    return () => {
      mutationFn({ variables: { message: null } });
    };
  }
```

The test: 
```
it('should pass message to message component', async (done) 
    => {
    await new Promise((resolve) => setTimeout(resolve));
    comp.update();

    comp.find('Button').simulate('click');
    await new Promise((resolve) => setTimeout(resolve, 10));
    comp.update();
    expect(comp.find(MyComponent.props('message')).toBeNull();
    done();
  });
```

Is there a way to force the Query to re-render on click? Or is there a way to spy on the mutationFn()?

Cross posting from stackoverflow: https://stackoverflow.com/questions/53034367/react-apollo-testing-nested-query-in-mutation

**Comment by rosskevin** [comment]
As @sbrichardson mentioned, I think you want `query.refetch()` here since they are in close proximity and will refetch exactly what you want.  Alternatively, make sure you mutation and query documents have appropriate ids and add the data you want to reload to your mutation response payload.
