### ISSUE TITLE
Non working `defaultOptions.query.errorPolicy` when set to all

### ISSUE THREAD

**Issue by bwlt** [apollographql/react-apollo#2629]
**Intended outcome:**

ApolloClient `defaultOptions.query.errorPolicy` does not work when set to "all"

**Actual outcome:**

When setting ApolloClient `defaultOptions.query.errorPolicy` to "all" should work like this example:
https://www.apollographql.com/docs/react/features/error-handling.html#policies .
I'm expecting that `defaultOptions` passed to the ApolloClient are "system wide" options.

**How to reproduce the issue:**

This is a working reproduction like the one [documented](https://www.apollographql.com/docs/react/features/error-handling.html#policies):
https://codesandbox.io/s/6x5zlx771n

This is a non working example (almost equal of the above example) of the issue
https://codesandbox.io/s/rrqjk4jpmm

**Version**

- apollo-boost@0.1.22
- react-apollo@2.3.2

**Comment by thril** [comment]
This bug may be related... https://github.com/apollographql/apollo-client/issues/2555

**Comment by Piwaii** [comment]
temporary workaround: https://github.com/apollographql/apollo-client/issues/2555#issuecomment-449871538

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!

**Comment by ankitjaincst** [comment]
I am using useQuery . I set errorPolicy: "all" . I have 2 queries in a query . Eg .
 const GET_MULTI_QUERY = gql`
  query GetMulti {
    ldapGroups(email: "myemail")
    listQueues(request: {}) {
      queues {
        uuid
        version
        name
      }
    }
  }
`;

Now if one of them errors out , I expect to get data for the other one as well as get the error with what has been said in the documentation . However, I am not getting the error . I get error as undefined . I tried errorPolicy: 'none' , this sets data to null and only gives the error . Also, errorPolicy: 'ignore' does not work . I am using SSR but that should not matter .  

This is a long thread and I guess the expectation is get the error as well as the data possible . 

Any progress or anyone working on this ? This looks like a very basic requirement as the playgroung even works like that .
