### ISSUE TITLE
Import statement for ApolloProvider causes Error

### ISSUE THREAD

**Issue by b33son** [apollographql/react-apollo#2630]
**Intended outcome:**
import { ApolloProvider } from "react-apollo";
Should do nothing aside from unused import linting, etc. 

**Actual outcome:**
object prototype may only be an object or null: undefined

**How to reproduce the issue:**
I tried using the latest version of react-apollo and also reverting to some previous versions that I thought might be working. The result is the same. This leads me to believe I must be making some stupid mistake or something else in my package.json config isn't right. However, this could be some bug with apollo-boost. I'm just not sure. 

So I've included the entire project here to reproduce the issue:
https://github.com/b33son/expo-apollo-issues

The import statement is here: 
https://github.com/b33son/expo-apollo-issues/blob/master/src/apollo.js

**Version**

    "@expo/vector-icons": "^8.0.0",
    "apollo-boost": "^0.1.22",
    "dotenv": "^6.1.0",
    "expo": "^31.0.2",
    "formik": "^1.3.2",
    "graphql": "^14.0.2",
    "graphql-request": "^1.8.2",
    "moment": "^2.22.2",
    "native-base": "^2.8.1",
    "react": "16.5.0",
    "react-apollo": "^2.3.2",
    "react-dom": "16.6.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz",
    "react-native-formik": "^1.5.5",
    "react-native-hide-with-keyboard": "^1.2.0",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-router": "^4.3.1",
    "react-router-native": "^4.3.0",
    "yup": "^0.26.6"

**Comment by b33son** [comment]
I created a project with expo and setup apollo client and it worked correctly. There must be some babel setting or something that's causing the import to resolve incorrectly. Although, other import statements are working. I'm confused.

**Comment by danilobuerger** [comment]
Closing as it looks like an issue with your setup and not with react-apollo per se.
