### ISSUE TITLE
Query component does not clear error after success

### ISSUE THREAD

**Issue by vieira** [apollographql/react-apollo#2658]
**Intended outcome:**

After invoking a GraphQL endpoint with some invalid variable an error is thrown and shown to the user. After the user inputs a new valid value as variable a new Query should be performed and the component should render properly.

**Actual outcome:**

After the first query errors, even when the user inputs a new valid value, the same error referencing the old value keeps being shown.

**How to reproduce the issue:**

I created a repository [vieira/github-graphql-apollo](https://github.com/vieira/github-graphql-apollo) where the issue can be seen.

In `src/index.jsx` replace `<GITHUB_TOKEN_HERE>` with a valid token (when generating the token you do not need to select any scopes).

To reproduce type an invalid Github username, e.g. `slkçalfksçlfks` and then type a valid username, like `vieira`. Your second try should return a list of repositories but instead will show the same error as the first one, including the invalid username you first typed.

**Other notes:**

Passing a `key` prop to the Query component with the typed username works around the issue and makes things work, however it is not practical when there are multiple variables.

See: [6b51be](https://github.com/vieira/github-graphql-apollo/commit/6b51be4b8f5d0d40365ae15a32dca64c65756bc6)

**Version**

- apollo-client@2.4.7
- react-apollo@2.3.2

**Comment by zchwyng** [comment]
I'm having the same problem.

**Comment by rosskevin** [comment]
It would be great if you could submit a PR with a breaking test.

**Comment by JoviDeCroock** [comment]
I have been debugging this issue, with the newest versions of the libraries. It feels like something goes wrong in the render method of react-apollo since the error is being cleared the console warning states:

![image](https://user-images.githubusercontent.com/17125876/52130746-4be90880-263b-11e9-9aed-f95cfc99fb5a.png)

As you can see in this screenshot after refetch the error has been cleared.

**Comment by hwillson** [comment]
Fixed in https://github.com/apollographql/react-apollo/pull/2718. Thanks!
