### ISSUE TITLE
Upgrading from 2.2.4 to 2.3.3 breaks React-rendered content in <Query /> with fetchPolicy="network-only"

### ISSUE THREAD

**Issue by optunetobi** [apollographql/react-apollo#2670]
### Upgrading from 2.2.4 to 2.3.3 breaks React-rendered content in  `<Query />` with fetchPolicy="network-only"

**Intended outcome:**

Query with fetchPolicy="network-only" will display Component after fetching data over the network.

**Actual outcome:**

React renders the Loading component instead of the intended Component and gives the following warning in console:

```
Warning: render(...): It looks like the React-rendered content of this container was removed without using React. This is not supported and will cause errors. Instead, call ReactDOM.unmountComponentAtNode to empty a container.
```

**How to reproduce the issue:**

```
<Query key={'mykey'} query={QUERY} fetchPolicy="network-only">
          {({ loading, error, data, client }) =>
            loading ? (
              <div>Loading data...</div>
            ) : error ? (
              <div>Error...</div>
            ) : (
              <Component data={data} />
            )
          }
</Query>
```

It might be due to this Change: https://github.com/apollographql/react-apollo/pull/2493

**Version**

- apollo-client@2.4.7
- react-apollo@2.3.3
- react@16.6.3
- react-dom@16.6.3

**Comment by hwillson** [comment]
This should no longer be an issue. Please try out a current day version of `react-apollo`, and keep us posted. Thanks!
