### ISSUE TITLE
update: cache.readQuery throws error if query not found

### ISSUE THREAD

**Issue by sandorvasas** [apollographql/react-apollo#2679]
GraphQL HOC, update:

BUG 1: 
**Symptom**:
If the query doesn't exist, cache.readQuery throws an error and causes an infinite loop (then eventual freeze and crash) in dev tools and the page

**Intended outcome**:
cache.readQuery returns null without throwing an error and crashing everything

plus a cache.findQuery would be very useful to find and FILTER queries. 
e.g.

`cache.findQuery({ query: getStuff }) ` to return all getStuff queries with **ANY** kind of parameters

**Comment by rosskevin** [comment]
This is an apollo-client API, not a react-apollo API, please file an issue there
