### ISSUE TITLE
Two queries with the same name cause infinite loop

### ISSUE THREAD

**Issue by scottburch** [apollographql/react-apollo#2700]
I had to components that needed the same information so I inadvertently gave them each a query with the same name.  This causes an endless loop.

react-apollo 2.3.2
apollo-client 2.4.7

This code will cause the issue:
```
const XXX = gql`
    query xxx($userId: id!) {
        user(id: $userId) {
            id
        }
    }  
`;


<div>
        <Query query={XXX}>
            {() => console.log('query 1') || null}
        </Query>

        <Query query={XXX}>
            {() => console.log('query 2') || null}
        </Query>
</div>
```

**Comment by scottburch** [comment]
Please close this issue.  I found the problem and it was not about having two queries with the same name.  It was about having queries where one of the variables is undefined

**Comment by rosskevin** [comment]
FYI @scottburch you should be able to close your own issue.
