### ISSUE TITLE
Query goes into rapid infinite request loop when a variable is undefined

### ISSUE THREAD

**Issue by scottburch** [apollographql/react-apollo#2701]
When a variable is undefined in a query it will go into a very rapid request loop.  Rapid = > 100 requests per second, much faster than my testing server can resolve them. 

This will cause it.  Leaving out the variables property will also cause it.

```
const XXX = gql`
    query xxx($id: ID!) {
        user(id: $id) {
            id
            username
        }
    }
`;

<Query query={XXX} variables={{id: undefined}}>
         {() => null}
</Query>

**Comment by JoviDeCroock** [comment]
Does this happen aswell when you are using an empty object, since this actually comes down to sending an empty object? Could you test this for me or make a reproduction if you would feel like it?

**Comment by scottburch** [comment]
@JoviDeCroock I will make a reproduction today.

**Comment by JoviDeCroock** [comment]
Thanks for the reproduction, I'll take a look asap

**Comment by JoviDeCroock** [comment]
I see several issues in this. On one side you are querying an unexisting endpoint + you are saying ID is mandatory since you say `ID!`

**Comment by scottburch** [comment]
Yea, the not having a server is not part of the test since it happens on a valid endpoint with a server. I guess I can do the work around (or just never send undefined for a variable).  I just removed the '!' off id and I get the same problem, so that had nothing to do with it.

Without a server it should not go into a infinite loop like this with ~100 requests per second, it should error out.  So, definitely a bug someplace.  But, I can understand that this is an edge case.  

At least it is documented here.

**Comment by scottburch** [comment]
We can close it. There was no explanation.  Just a bug for a edge case.
