### ISSUE TITLE
TS2339: Property 'loading' does not exist on type 'DataValue<Response, Variables> | undefined'.

### ISSUE THREAD

**Issue by Thullner** [apollographql/react-apollo#2705]
I keep getting the following errors:

![image](https://user-images.githubusercontent.com/19549299/50577477-0f9e6e80-0e29-11e9-9645-144df4b0b2ae.png)

I copied the code from the tutorial (https://www.apollographql.com/docs/react/recipes/static-typing.html):

![image](https://user-images.githubusercontent.com/19549299/50577485-45435780-0e29-11e9-8c7a-e1a8d81203ef.png)

**Version**

- apollo-client@2.4.8
- react-apollo@2.3.3
- typescrypt@3.2.2

**Comment by JoviDeCroock** [comment]
I think your destructuring at the bottom should be: `({ loading, error, data : { hero } })`

**Comment by tkolsen** [comment]
I have the same problem. The destructuring in the docs and the one sugested by @JoviDeCroock does not work.

**Comment by tigrus** [comment]
Any updates/solutions about this error?

**Comment by rosskevin** [comment]
FYI - PRs for docs should be in the apollo-client repo - src https://github.com/apollographql/apollo-client/tree/master/docs

**Comment by danilobuerger** [comment]
See https://github.com/apollographql/apollo-client/pull/4340 for fix.
