### ISSUE TITLE
Extending Query component and adding componentDidUpdate results in a typing error

### ISSUE THREAD

**Issue by dozoisch** [apollographql/react-apollo#2722]
In Query.d.ts, componentDidMount is define like this, which is different than the React lifecycle 

```
// Query.d.ts
componentDidMount(): void;
// React lifecycle
componentDidUpdate?(prevProps: Readonly<P>, prevState: Readonly<S>, snapshot?: SS): void;
```

Which creates a typing error when trying to extends Query like

```
class MyQuery  extends Query<IMyQueryData, null> {
  public componentDidUpdate(prevProps: QueryProps<IMyQueryData, null>) {
    super.componentDidUpdate(/* .... */);
  }
}
```

Error:

```
Property 'componentDidUpdate' in type 'MyQuery' is not assignable to the same property in base type 'Query<IMyQueryData, null>'.
  Type '(prevProps: QueryProps<IMyQueryData, null>) => void' is not assignable to type '() => void'.ts(2416)
```

Because the cdu I use needs prevProps (which is passed just fine), but it's not in Query definition, it errors

**Version**

- apollo-client@2.4.8
- react-apollo@2.3.3

**Comment by rosskevin** [comment]
Extending components in React is not done typically and there is no intention to go against recommended react patterns and support it here.
