### ISSUE TITLE
loading=true and networkStatus=1 on request canceled

### ISSUE THREAD

**Issue by Fi1osof** [apollographql/react-apollo#2725]
**Intended outcome:**

Get "loading" prop = false when request canceled.

**Actual outcome:**

Now i get loading = true AND networkStatus = 1 on request canceled. I can not catch that request is closed (cancelled) and not loading now.

notifyOnNetworkStatusChange={true} does not helps.

**How to reproduce the issue:**

Maybe a few same request in loop with refetch.

**Version**

- apollo-client@2.4.8
- react-apollo@2.3.3

**Comment by rosskevin** [comment]
I know the sample repo is out of date, but the above does not qualify as actionable - it simply isn't enough and there would need to be quite a bit of work by a maintainer to attempt to reproduce your issue (hopefully) then move on to solving it.  

Please take more time to provide something reproducible.  I'm happy to reopen if you do.  Before you do, please be sure to check the open issues for a duplicate.
