### ISSUE TITLE
requesting clear and useful documentation for Typescript usage

### ISSUE THREAD

**Issue by peterschussheim** [apollographql/react-apollo#2730]
The [docs for using react-apollo with TypeScript](https://www.apollographql.com/docs/react/recipes/static-typing.html) along with the example in this repo are unintuitive and so minimal I have a hard time believing anyone uses them for help.

Please update the docs and the example with something more than a single query and perhaps provide something more complete and better annotated than the current documentation provides.

- [related issue with no response](https://github.com/apollographql/react-apollo/issues/2705)

**Comment by JoviDeCroock** [comment]
Hey, could you provide some feedback as to what specifically goes wrong for you? It's hard for anyone to predict what people understand and don't understand this is the whole challenge of writing docs. That's why some feedback apart from that one issue could come in handy.

**Comment by rosskevin** [comment]
I'm going to close this as not actionable.  We have the reported bug in the docs #2705 as referenced so this appears to be a duplicate.

@peteratticusberg please feel free to PR docs improvements to https://github.com/apollographql/apollo-client/tree/master/docs
