### ISSUE TITLE
compose graphql mutations on a function

### ISSUE THREAD

**Issue by davidalekna** [apollographql/react-apollo#2745]
Hi! It's not actually an issue. I was wondering is there an export like { graphql } from react-apollo, but to compose with a simple function, not react component? 

Something like

```
const someFunction = compose(
    mutation1,
    mutation2,
)(({ mutation1, mutation2, ...args }) => {
    // do something...
})

someFunction(args)
```

if not, would it be something useful to have?

Thanks!

**Comment by danilobuerger** [comment]
Issues here are reserved for bugs, but one of the following resources should help:

* Apollo's Slack: https://www.apollographql.com/slack
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests
