### ISSUE TITLE
Uses Object.assign, not supported in IE11

### ISSUE THREAD

**Issue by tamouse** [apollographql/react-apollo#2752]
**Intended outcome:**

Testing application in IE11, Component was calling `<Query>` to obtain data.

**Actual outcome:**

JavaScript error: Object doesn't support property or method "assign"

**How to reproduce the issue:**

Call `<Query>` in an app running in the IE11 browser.

**Version**

- apollo-client@2.3.5
- react-apollo@2.1.9

Note that master still contains `Object.assign`: https://github.com/apollographql/react-apollo/blob/master/src/Query.tsx#L359

![object assign error in react-apollo query](https://user-images.githubusercontent.com/363583/51561605-4e827b80-1e4d-11e9-9605-27e6d6e6bb8a.jpg)

**Comment by rosskevin** [comment]
In this case, my expectation is that you are using a web bundler such as webpack or parcel to create your application.  You will need to polyfill items like this for IE11.  Here's a note for babel polyfills with `preset-env`: https://babeljs.io/docs/en/babel-preset-env#usebuiltins-entry
