### ISSUE TITLE
Server-side render not waiting on one of my queries completing

### ISSUE THREAD

**Issue by EthanML** [apollographql/react-apollo#2757]
**Intended outcome:**

Server-side rendering a React app should wait on _all_ Apollo queries completing before sending a response (right?).

**Actual outcome:**

We have a server-side rendered React app making use of the react-apollo GraphQL client to fetch our data.

The way our app generally performs is that the server-side rendered contents include the fetched data required for the requested page. Meaning the server render waits on any requests for data to complete before returning a response. This is how I believe everything is supposed to work.

However, there is a particular query we make use of which, when I log the details of its resulting data prop during the server side render, has a loading state of true and no attached result object. The query in question is generated via the graphql HOC on a container component nested within our component tree - this is consistent with how all our other queries are set up, but the issue appears to only be present with this one. It's very noticeable since the UI in question typically has a loading spinner for several seconds after initial page render as a result.

Is anybody aware of any potential causes or reasons why this might occur for a particular query? 

**How to reproduce the issue:**

Not sure I can really set up a demo testcase for this issue unfortunately. However the code around the query in question is a fairly typical HOC-style `graphql` usage as mentioned. Something along the lines of:

```javascript
const withData = graphql(
  myQuery,
  {
    options: (props) => ({
      variables: { myArg: props.myArg },
    }),
  },
);

export default compose(
  withRedux,
  withData,
)(MyComponent);
```

The resulting `data` prop passed into `MyComponent` during server side render (and initial client-side render) looks like:

```javascript
{ variables: { myArg: 'foobar' },
  refetch: [Function],
  fetchMore: [Function: bound ],
  updateQuery: [Function: bound ],
  startPolling: [Function: bound ],
  stopPolling: [Function: bound ],
  subscribeToMore: [Function: bound ],
  loading: true,
  networkStatus: 1,
  error: [Getter] }
```

The app is using this library's `renderToStringWithData` function for SSR. It also uses `react-router`.

**Version**

- apollo-client@<2.2.0>
- react-apollo@<2.0.4>

**Comment by benjamn** [comment]
@EthanML Is react-apollo@2.0.4 a typo for 2.4.0? The 2.0.4 version was published a year ago.

**Comment by rosskevin** [comment]
I'm closing this since there is no response and no reproduction.

**Comment by reduxdj** [comment]
I'm having this problem, with the older version of apollo, it's documented here:
https://github.com/leebenson/reactql/issues/158

**Comment by reduxdj** [comment]
We had this same issue and then we just solved it, it seems like ErrorBoundary doesn't allow play nicely with react-apollo
