### ISSUE TITLE
fetchMore pagination handle error?

### ISSUE THREAD

**Issue by asgeirfri** [apollographql/react-apollo#2759]
**Intended outcome:**
Im trying to use fetchMore with react-infinite-scroll (https://www.npmjs.com/package/react-infinite-scroller). It works most of the times, but I want to be able to catch a server error and handle it. I am talking to a service that 'throttles' me a lot so what I do is I wait 1 sek and I try again.

**Actual outcome:**
It works perfectly except when the server responds with an error. What I want to do is catch that error but I havent been able to so far

![image](https://user-images.githubusercontent.com/12255244/51898034-f2b57680-23a7-11e9-8bc8-b36dfb940506.png)

**How to reproduce the issue:**
Create a query component
Call fetchMore with another query (to paginate)
Server returns some error

**Version**

- apollo-client@2.4.7
- react-apollo@2.3.1

**Comment by danilobuerger** [comment]
Issues here are reserved for bugs, but one of the following resources should help:

* Apollo's Slack: https://www.apollographql.com/slack
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests

**Comment by bristoljon** [comment]
For future ref, `fetchMore` returns a Promise so you can use `.catch()`:

https://stackoverflow.com/questions/54437901/how-to-error-handle-in-fetchmore-pagination/56341411#56341411
