### ISSUE TITLE
react-dom upgrade to latest causes graphql to refetch with every state change

### ISSUE THREAD

**Issue by smschick** [apollographql/react-apollo#2761]
Updated react-dom from v. 16.3.2 => 16.7 and now when I export my component with a graphql query:

```
export default compose(
  withApollo,
  graphql(GRADE_QUERY, {
    name: 'gradeQuery',
    options: props => ({
      variables: { url: props.match.params.url },
      fetchPolicy: 'network-only'
    })
  })
)(withRouter(Grade))
```

Anytime I set/change state of my component the query will refetch.  I know because I'm utilizing getDerivedStateFromProps and I'm logging nextProps and prevState.  The query results come in on nextProps anytime state is updated.

```
static getDerivedStateFromProps(nextProps, prevState) {
    console.log('nextProps: ', nextProps)
    console.log('prevState: ', nextProps)
    if (!nextProps.gradeQuery.loading) {
      const { grade } = nextProps.gradeQuery

      if (grade && grade !== prevState.grade) {
        const newState = update(prevState, {
          grade: { $set: grade }
        })
        newState.validationErrors = run(newState, fieldValidations)
        newState.submitErrors = []
        return newState
      }
    }

    return null
  }
```

I've also stripped out compose, withApollo and withRouter on the export so it was just:
```
export default graphql(GRADE_QUERY, {
  name: 'gradeQuery',
  options: props => ({
    variables: { url: props.match.params.url },
    fetchPolicy: 'network-only'
  })
})(Grade)
```

And got the same results of the query refetching with state change.

If I revert back to react-dom 16.3.2 this does not happen. 

currently have in my project:
```
"apollo-cache-inmemory": "^1.2.10",
"apollo-client": "^2.4.2", 
"apollo-link": "^1.2.3",
"apollo-link-http": "^1.5.5",
"graphql": "^0.13.1",
"graphql-tag": "^2.8.0",
"react": "^16.3.2",
"react-apollo": "^2.1.11"
```

I also updated all of the listed modules to @latest and get the same undesired outcome.

**Intended outcome:**

Setting state shouldn't re-fetch the graphql query exported with the component

Eventually I will re-factor many of my projects components to use the Apollo HOCs which would more than likely get around this, but if there is a fix/workaround for the present it would be greatly appreciated.

**Comment by rosskevin** [comment]
You have set `fetchPolicy: 'network-only'` , this means that any re-render is going to refetch from the server.

**Comment by smschick** [comment]
> You have set `fetchPolicy: 'network-only'` , this means that any re-render is going to refetch from the server.

Then why on react-dom v. 16.3.2 and I have 'network-only' in place I don't get the re-fetch, and why when I remove the 'network-only' policy on react-dom version 16.7 do I get the same undesired outcome?

**Comment by rosskevin** [comment]
> Then why on react-dom v. 16.3.2 and I have 'network-only' in place I don't get the re-fetch, and why when I remove the 'network-only' policy on react-dom version 16.7 do I get the same undesired outcome?

I responded to your original post - which appears to be as-designed behavior.  Using `fetchPolicy: 'network-only'` with a react state change causing a re-render will cause a network fetch.

I don't know your setup react-apollo doesn't have control of react-dom rendering nor the react lifecycle.  If you have found a provable bug that is different than your OP, then please file a new issue with a reproduction repo or a codesandbox minimal test case.

**Comment by smschick** [comment]
I was under the assumption, and you know what means, that if I export my component with the apollo client and query on the props it would only fire the query when that component was first mounted/loaded and had nothing to do with the component's render method? That could be totally wrong and my ignorance.  So if updating state makes my component re-render I also ASSumed that the query on props wouldn't fire again, which is the outcome when I use react-dom 16.3.2.  However if I use 16.7 that query on props gets fired whenever the component re-renders.  So I'm at a loss other than not updating and re-factoring which I'm in the process of and then upgrading.
