### ISSUE TITLE
[Question] hydrate once with SSR cache with cache-first fetchPolicy

### ISSUE THREAD

**Issue by jeroentradecast** [apollographql/react-apollo#2778]
Hi all, 

We have a passive SSR (prerender) system running in which the SSR data can be stale. Clientside we use a lot of 'cache-first' fetchPolicies. The problem I'm currently running into is that with a cache-first policy, the SSR cache is injected and considered as done, or up-to-date. 
 
I could fix this by using the 'cache-and-network' fetchPolicy, but I don't really want clients to make unnecessary roundtrips to the AP during one browsersession, because content isn't updated regularly.
 
Do you guys have any idea? Would it be possible to query the local cache, then maybe flip the fetchPolicy per query?

**Comment by danilobuerger** [comment]
Issues here are reserved for bugs, but one of the following resources should help:

* Apollo's Slack: https://www.apollographql.com/slack
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests
