### ISSUE TITLE
Data object is recreated on each Query rerender

### ISSUE THREAD

**Issue by kmrachko** [apollographql/react-apollo#2780]
**Intended outcome:**

Rerendering Query with the same props will provide **strictly equal** arguments inside children function.

Background: we are trying to optimize our application as much as possible and avoid rerendering expensive components when it's not necessary, therefore we expect non-primitive props (i.e. data) to change only when their content is changed as they are passed down to our components that implement **shouldComponentUpdate**.

**Actual outcome:**

The **data** object inside render props function's arguments is re-created each time Query is rerendered, which leads to incorrect behavior of shouldComponentUpdate inside PureComponent or memo[ized] functional components.

**How to reproduce the issue:**

https://codesandbox.io/s/nwk0p8l49p

All is set up, just run the sandbox and check the rendered output.

**Version**

- apollo-client@2.4.1
- react-apollo@2.4.1

**Comment by dospolov** [comment]
same problem

**Comment by knyshh** [comment]
same problem

**Comment by mefjuu** [comment]
Just take into an account a fact that `data` is Apollo's container for real _data_. If only the comparison looks like `const isStrictlyEqual = data.country === cachedData.country;` it will be true.

**Comment by kmrachko** [comment]
Yeap already figured that out. I think the issue is not relevant anymore (at least for our case), but that chapter should be definitely covered in the documentation. I'll try to find some spare time and submit PR with updated docs.

Anyway, the issue may be closed, I think.
