### ISSUE TITLE
Mock refetch() using MockedProvider

### ISSUE THREAD

**Issue by essaji** [apollographql/react-apollo#2783]
Using MockedProvider we can mock the output which is pretty straight, e.g.
```javascript
let mocks = [{
    request: { query: DATA_QUERY, variables: {...} }
    result: {
        data: {...},
        refetch: () => console.log('refetch mocked') 
    }
}]
<MockedProvider mocks={mocks} addTypename={false}>
    <ComponentToTest />
</MockedProvider>
```
This gives me successful mocked output when executing DATA_QUERY

```javascript
<Query query={DATA_QUERY} variables={...} fetchPolicy='cache-and-network' >
      {({data, refetch}) => refetch()
</Query>
```
Which should log refetch mocked on the console which is not happening in my case. May be it is not the right way to mock the refetch function, is it? If not, is there any way to mock the refetch function using MockedProvider

Thanks in anticipation

**Comment by danilobuerger** [comment]
Issues here are reserved for bugs, but one of the following resources should help:

* Apollo's Slack: https://www.apollographql.com/slack
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests

**Comment by garrettmaring** [comment]
@danilobuerger there are several questions on this topic out there and none of them have any answers from the community. We could update this issue to be "document mocking refetch()" for `MockedProvider`.

Would you be willing to point us in the right direction?
