### ISSUE TITLE
(feature idea) Include query in QueryResult

### ISSUE THREAD

**Issue by good-idea** [apollographql/react-apollo#2789]
It would be handy if the render prop from a `<Query>` included the actual query in it -- in my use case, I have a lot of `refetchQueries` happening with my mutations and it would be nice to have the query provided through props instead of importing them. `QueryResult` already includes the `variables`, so it's halfway there..

**Comment by danilobuerger** [comment]
Feature requests and non-bug related discussions are no longer managed in this repo. Feature requests should be opened in https://github.com/apollographql/apollo-feature-requests.
