### ISSUE TITLE
package.json devDependencies for React outdated?

### ISSUE THREAD

**Issue by rsokz** [apollographql/react-apollo#2792]
**Intended outcome:**

An error is stated when trying to use React hooks:

> Hooks can only be called inside the body of a function component. 

I believe the cause may be react & react-dom devDependency mismatch.

**Actual outcome:**

Thanks to @ryancogswell for the catch.

The devDependencies in `package.json` have React listed as: 16.5.2
> "react": "16.5.2", "react-dom": "16.8.1"

This may be causing an issue with React hooks.

**How to reproduce the issue:**

Open package.json

Possibly related issue: [https://github.com/facebook/react/issues/14823](url)

**Version**

- apollo-client@2.4.12
- react-apollo@2.4.1

**Comment by sapkra** [comment]
I created a PR, but the builds are failing. Maybe someone can help with the breaking changes. 😉

**Comment by MitchTalmadge** [comment]
This is breaking my stuff too. Hope we see an update soon.

**Comment by sapkra** [comment]
They commented my PR that they are working on it.

**Comment by rosskevin** [comment]
PR https://github.com/apollographql/react-apollo/pull/2892 is open and tracking the changes needed to update react.

**Comment by djamaile** [comment]
Is there a workaround for this?

**Comment by blakedietz** [comment]
Bump, is there a workaround for this?

**Comment by sandorfr** [comment]
Same issue here :( quite desperate to find a workaround.

**Comment by sapkra** [comment]
I think there is no other solution than waiting for version 3.0.0. I think it will not take that long anymore. See [this](https://github.com/apollographql/react-apollo/pull/2892#issuecomment-480882737) and [this](https://github.com/apollographql/react-apollo/issues/2539#issuecomment-502358618) comment.
