### ISSUE TITLE
Variables are merged on Mutation when calling mutate

### ISSUE THREAD

**Issue by moretti** [apollographql/react-apollo#2793]
Hello, I think I found an inconsistency in the docs regarding [`Mutation.mutate`](https://www.apollographql.com/docs/react/api/react-apollo.html#mutation-render-prop):

> `mutate: (options?: MutationOptions) => Promise`
> A function to trigger a mutation from your UI. You can optionally pass `variables`, `optimisticResponse`, `refetchQueries`, and `update` in as options, which will override any props passed to the Mutation component. The function returns a promise that fulfills with your mutation result.

where it says that any option in `mutate` will override the corresponding prop passed to the `Mutation` component.

It doesn't seem the case for `variables`, which instead are merged:

https://github.com/apollographql/react-apollo/blob/c02d30d4e2a5f7781e9f81a18f4b397619baa070/src/Mutation.tsx#L217

I'm opening this ticket to ask if this is the intended behaviour and if we should update the docs to reflect what the source code actually does.

**Version**

- react-apollo@2.4.1

**Comment by danilobuerger** [comment]
This is intentional. See https://github.com/apollographql/react-apollo/pull/2216
The docs can be changed to reflect that. However, the docs are maintained at https://github.com/apollographql/apollo-client so closing here.
