### ISSUE TITLE
Query component failing on status code 400

### ISSUE THREAD

**Issue by stonebat** [apollographql/react-apollo#2794]
**Intended outcome:**
The server side returns ApolloError with status code 400.  I expect the Query component's callback function to be invoked with non-empty error object.

```
      <Query
        query={query}
        fetchPolicy={fetchPolicy}
        errorPolicy="all"
        variables={...someVariables}
      >
        {
          ({loading, error, data, networkStatus}) => {
             ...
          }
     }
```
           
**Actual outcome:**
It seems runtime exception is thrown, and the callback function inside <Query> component is never invoked. This is the console output.

```
Unhandled promise rejection Error: Network error: Response not successful: Received status code 400
    at new ApolloError (ApolloError.js:33)
    at QueryManager.js:360
    at QueryManager.js:808
    at Array.forEach (<anonymous>)
    at QueryManager.js:807
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (QueryManager.js:803)
    at QueryManager.js:317
    at run (es6.promise.js:98)
    at es6.promise.js:119
    at MutationObserver.flush (_microtask.js:22)
```

**How to reproduce the issue:**
From Apollo Server running in AWS Lambda ("apollo-server-lambda": "2.4.0"), throw new ApolloError from the context initialization function.

```
const server = new ApolloServer({
  schema: SomeSchema,
  context: async ({ event }) => {
      ...
     throw new ApolloError(...)
```
See if <Query> component in Chrome browser works properly.

**Version**

- apollo-client@2.4.12
- react-apollo@2.4.1

**Comment by stonebat** [comment]
Never mind. It was my fault. Closing this.

**Comment by pederklev** [comment]
It would be helpful to know how you solved it.

**Comment by stonebat** [comment]
Sorry. It was so trivial one that I can't recall...

I recall it had really nothing to do with apollo server and the query component.
