### ISSUE TITLE
Return empty object when do a mutation in the same page

### ISSUE THREAD

**Issue by imakou** [apollographql/react-apollo#2795]
Scenario: 

A todo list which queries gq server and a form with mutation a behavior(adding) on the same page.

Problem:

The list page will access empty obejct which is returned by gq when users use the form to create a new todo item.
In addition, the page will refresh automaticly while sumbit the form.

**Version**
"react-apollo": "^2.4.1",
"apollo-boost": "^0.1.27",
"react": "^16.8.1",

**Comment by danilobuerger** [comment]
Issues here are reserved for bugs, but one of the following resources should help:

* Apollo Spectrum community: https://spectrum.chat/apollo
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests
