### ISSUE TITLE
Provide an alternative to `skip` property that works nicely with typescript

### ISSUE THREAD

**Issue by leighman** [apollographql/react-apollo#2797]
Using the `graphql` component and typescript with `react-apollo` 2.2.4.

**Intended outcome:**

The type of `props` for `options` function would be constrained by checks made in `skip`.

**Actual outcome:**

There is no way, afaik, for typescript to know that the type of `props` to `options` should be constrained in some way.

**Suggestion**

Allow some shape to be returned from `options` that will act like `skip: true` has been set on the component.
Apologies if this is already possible and I've missed it.

**Version**

- apollo-client@2.4.12
- react-apollo@2.2.4

**Comment by danilobuerger** [comment]
Thanks for your interest in helping make Apollo Client better!

Feature requests and non-bug related discussions are no longer managed in this repo. Feature requests should be opened in https://github.com/apollographql/apollo-feature-requests.

**Comment by SimenB** [comment]
(GitHub has a "move issue" feature, although you might need to be an admin in both repos to use it?)
