### ISSUE TITLE
No error displayed

### ISSUE THREAD

**Issue by tomitrescak** [apollographql/react-apollo#282]
Hi, I was browsing through closed issues such as #57 but I cannot find a solution to the problem that Apollo silently swallows all errors. The only error I see is from React "Attempted to update component that failed to mount".

I have a container that fetches data (using graphql from react-apollo) the code is below.
The component then renders data. The problem is that I forgot to add the waiting for "loading=false" and component mount. But, it would be great to see that error "null reference" somewhere.

``` js
import Component, { IComponentProps, IComponentActions } from '../components/schedule_list_view';
import { connect, loadingContainer } from 'apollo-mantra';
import * as actions from '../actions/schedule_actions';
import { graphql } from 'react-apollo';

interface IProps {
  context?: () => App.Context;
  clearSearch?: Function;
  header: string;
  route: string;
  showBadges: boolean;
  icon: string;
}

const withSchedules = graphql(gql`
      query schedules($userId: String) {
        schedules(userId: $userId) {
          _id
          name
          description
        }
      }`, {
    options: (ownProps: IComponentProps) =>
      ({
        variables: { userId: ownProps.userId }
      })
  });

export const mapStateToProps = (context: App.Context, state: App.State, _ownProps: IProps): IComponentProps => ({
  context,
  userId: state.accounts.userId,
  filter: state.schedule.filter
});

export const mapDispatchToProps = (_context: App.Context, dispatch: any): IComponentActions => ({
  handleSearch(filter: string) {
    dispatch(actions.handleSearch(filter));
  },
});

const WithScheduleData = withSchedules(Component);
export default connect<IProps>(mapStateToProps, mapDispatchToProps)(WithScheduleData);
```

How and where can I catch errors and display them in the console?

**Comment by stubailo** [comment]
Which versions of react-apollo and apollo-client are you running?

**Comment by tomitrescak** [comment]
Apollo Client: 0.4.21
React Apollo: 0.5.10

This is the workflow:

1. There is a component that shows two containers A and B
2. In the beginning only A is shown
3. Through user activity (login) B is supposed to show
4. But, B contains error and never renders and no error is shown on the screen.

**Comment by dpiccone** [comment]
It seems I have the same situation here with this withData decorator

```
const withData = graphql(
    getConversation,
    {
        options: props => ({
            variables:  {
                conversationId: 1
            }
        }),
        props: ({ data }) => ({
            entries:  data.conversationById.conversationEntriesByConversationId.edges.map(e => e.node)
        })
    }
);
```
and then
```
entries = props.entries.map(....)
```

This causes the frontend to crash silently, I noticed because the app started using server side routing instead of the client instance of `react-router`, but no error were thrown to the console.

The page loaded fine when fetched using SSR, because of the preloaded state.

Using

react-apollo@0.8.1
apollo-client@0.7.1

**Comment by jbaxleyiii** [comment]
This has been vastly improved (though errors still need some love) so I'm going to close it out
