### ISSUE TITLE
subscribeToMore and MockedProvider doesn't seem to work

### ISSUE THREAD

**Issue by hourliert** [apollographql/react-apollo#2820]
**Intended outcome:**
When mocking a subscription and passing it to `MockedProvider`, it should work as expected when a Component as a `Query` and call `subscribeToMore` in the child function.

**Actual outcome:**
When running my test, I **always** get:

```
Unhandled GraphQL subscription error Error: No more mocked responses for the query: subscription onRecipeImported($numberOfVersions: Int)
```

when using `subscribeToMore` from the `Query` component.

If instead I pass my gql subscription query  to the `Subscription` component and render it, the `MockedProvider` doesn't raise anything, _everything works_.

**How to reproduce the issue:**

* In a test (using react-testing-library here)
* Wrape the component in a MockedProvider
* Call `subscribeToMore` in a child function of a `Query` component.
* Render the component and call `await wait()`
* Excepection is raised with the message above.

**Version**

- apollo-client@2.4.13
- react-apollo@2.4.1

**Notes**

I saw in that the `test-links` module export a function called: `mockObservableLink`. Can this be of any help? (https://github.com/apollographql/react-apollo/blob/master/src/test-links.ts#L179)
This function doesn't seem to be used in this project though 🤔

**EDIT:**
I have added debugger inside react-apollo/test-utils code and it seems that the MockLink.request handler is called 9 times with my subscription operator. I only subscribe once to it. Am I doing something wrong? Is there a way of not firing this at all?

**Comment by hourliert** [comment]
Found the root cause. It seemed that my component was unmount/remounting (and therefore subscribing again). During the component unmounting, I was calling unsubscribe, but this had no effect in test.

**Comment by email2vimalraj** [comment]
Hi @hourliert,

I'm facing a similar issue. Can you please help me with the reproducible code and the fix you had put in?

**Comment by hourliert** [comment]
Here is the code I am using:

```js

  state = { unsubscribe: null };

  static getDerivedStateFromProps(nextProps, prevState) {
    if (!prevState.unsubscribe) {
      const unsubscribe = nextProps.subscribeToNewRecipes();
      return { unsubscribe };
    }

    return null;
  }

  componentWillUnmount() {
    if (this.state.unsubscribe) {
      this.state.unsubscribe();
    }
  }
```

Also, I wrote my tests to make sure I am not unecessary unmounting the component.
