### ISSUE TITLE
Breaking typescript change in 2.5

### ISSUE THREAD

**Issue by VincentLanglet** [apollographql/react-apollo#2824]
In 2.4.1, this was valid:
```
import { Context } from 'react-apollo';
```

In 2.5, it's now
```
import { Context } from 'react-apollo/walkTree';
```

I think it's because of this commit https://github.com/apollographql/react-apollo/commit/66b09459c6e948d7a662ffa980ea9a7554994cae

The walkTree definitions are not exported in `index.d.ts`

**Comment by benjamn** [comment]
This change was documented in the changelog for 2.4.0: https://github.com/apollographql/react-apollo/blob/master/Changelog.md#240

**Comment by VincentLanglet** [comment]
I had no use of the walkTree. Only the `Context` type.

```
import { GraphQLRequest } from 'apollo-link';
import { setContext } from 'apollo-link-context';
import { Context } from 'react-apollo';

import authenticator from '../../services/authenticator';

export const authorize = (_: GraphQLRequest, context: Context): Context => {
  const token = authenticator.getUserToken();

  if (!token) {
    return context;
  }

  return {
    ...context,
    headers: {
      ...context.headers,
      Authorization: `Bearer ${token}`,
    },
  };
};

export default setContext(authorize);
```

The fact `walkTree` is deprecated, shouldn't deprecate the `Context` type.
Maybe should it be defined somewhere else.

**Comment by benjamn** [comment]
@VincentLanglet Ahh, I agree it was a mistake to stop exporting that `Context` interface. Does #2832 look like it will restore the previous behavior?

**Comment by VincentLanglet** [comment]
Yes, I think it'll be good since `index` has `export * from './types';`
