### ISSUE TITLE
[meta] Releases page does not show 2.5.1

### ISSUE THREAD

**Issue by ceich** [apollographql/react-apollo#2826]
**Intended outcome:**
The Github [releases](https://github.com/apollographql/react-apollo/releases) page for this project should show the version currently offered via npm, 2.5.1

**Actual outcome:**
The last release shown is 2.4.0 with 4 newer releases (non-official) collapsed above. 2.5.1 is not shown.

**Comment by hwillson** [comment]
Fixed @ceich - thanks!

**Comment by ceich** [comment]
Thanks, was this an actual issue, or a race condition?

**Comment by hwillson** [comment]
More like a memory issue ... mine! 🙂
