### ISSUE TITLE
Bundle size increase from =>2.3.0: react-dom-server.browser.production added. Why?

### ISSUE THREAD

**Issue by frederikhors** [apollographql/react-apollo#2828]
Simply updating `react-apollo` from `2.2.4` to `2.3.0` alter bundle size like in the screens below:

**- from this:**
![image](https://user-images.githubusercontent.com/41120635/53606934-f877c500-3bbc-11e9-9b93-f340a0450f24.png)

**- to this:**
![image](https://user-images.githubusercontent.com/41120635/53606973-1cd3a180-3bbd-11e9-9f06-063649a00092.png)

Are you aware?
**Why?**

**Version**

- `apollo-client@2.4.5`

**Comment by JoviDeCroock** [comment]
Bundle size has been heavily focussed on in 2.5.0 and is much smaller in that version.

**Comment by frederikhors** [comment]
> Bundle size has been heavily focussed on in 2.5.0 and is much smaller in that version.

2.5.0 still with this "problem".

**Comment by JoviDeCroock** [comment]
I think this issue is situated at your end judging from what I'm looking at: https://bundlephobia.com/result?p=react-apollo@2.5.1

This lists the included dependencies, which does not include react-dom. Could you give some more information about your setup please?

**Comment by frederikhors** [comment]
@JoviDeCroock, what you need?

Asked also here: https://github.com/facebook/react/issues/15060

**Comment by frederikhors** [comment]
@JoviDeCroock

- **package.json**:

```json
    "apollo-client": "2.5.1",
    "apollo-link": "1.2.9",
    "apollo-link-context": "1.0.15",
    "apollo-link-error": "1.1.8",
    "apollo-link-http": "1.5.12",
    "apollo-link-persisted-queries": "0.2.2",
    "apollo-link-ws": "1.0.15",
    "apollo-utilities": "1.2.1",
    "bootstrap": "4.3.1",
    "lodash": "4.17.11",
    "node-sass": "4.11.0",
    "react": "16.8.4",
    "react-apollo": "2.5.2",
    "react-dom": "16.8.4",
    "react-loadable": "5.5.0",
    "react-onclickoutside": "6.8.0",
    "react-router-dom": "4.3.1",
    "react-scripts": "2.1.8",
```

**Comment by frederikhors** [comment]
Ok I just found the problem: https://github.com/apollographql/react-apollo/blob/master/Changelog.md#improvements-9

Is this problem fixable?

**Comment by smably** [comment]
I'm running into this issue too. I had a look into this and the best solution I came up with (at least until dynamic import is safe for library use: https://github.com/apollographql/react-apollo/pull/2533#discussion_r230061804) is to move `getDataFromTree` and `renderToStringWithData` into separate bundle (`react-apollo/server`?) similar to how `react-dom` bundles all its server rendering logic in `react-dom/server`. This would avoid bundling extra `react-dom` logic for the vast majority of users who never call `renderToStringWithData` from the browser.

Of course, that would be a breaking change, but maybe it could be considered for 3.0?

**Comment by smably** [comment]
@JoviDeCroock Threw up a minimal repro here in case you want to verify for yourself: https://github.com/smably/react-apollo-test

**Comment by JoviDeCroock** [comment]
If you use ESM then it should be tree-shaken off if you're not using `renderToStringWithData`. Thus if that repository contains `Query` etc. Then there's something wrong with how tree-shakeable this repo is.

**Comment by damusnet** [comment]
FWIW 2.5.0, 2.5.1 and 2.5.2 had reduced size considerably, but 2.5.3 seems to revert the trend. See https://github.com/apollographql/react-apollo/issues/2918

**Comment by JoviDeCroock** [comment]
@damusnet the reason behind this is because they bundled in `lodash.isequal`

**Comment by frederikhors** [comment]
This thread is about `getDataFromTree` problem.

The @damusnet's one thread (https://github.com/apollographql/react-apollo/issues/2918) is for `lodash.isEqual` problem.

Am I right?

**Comment by damusnet** [comment]
@frederikhors I think you are correct that there might be 2 issues. I don't know if it's better to track them separately or to treat bundlesize as a whole.

**Comment by frederikhors** [comment]
@damusnet separately.

**Comment by hwillson** [comment]
`lodash.isequal` was improperly marked as a dev dependency. The bundle size increase comes from correcting this. React Apollo 3 won't have this problem however, since it uses the `apollo-utilities` `isEqual` function instead, which is much smaller than `lodash.isequal` (see https://github.com/apollographql/apollo-client/pull/4924). RA 3 is landing very soon, so closing this for now. Thanks!

**Comment by frederikhors** [comment]
@hwillson please re-open. The problem is in `react-dom` not with lodash.

**Comment by hwillson** [comment]
@frederikhors Do you still have the `react-dom` issue after updating to `react-apollo` >= 2.3.2? [This](https://github.com/apollographql/react-apollo/blob/master/Changelog.md#232) should fix that issue, but let me know if not.

**Comment by Aghassi** [comment]
@hwillson 2.5.7 experiences the same issue if you run it through webpack for use as a standalone asset on a CDN. Treeshaking does not apply to our app architecture (SPA with microfrontends) since our code is sharing a single package of react-apollo. As mentioned earlier in this thread, can things that use `react-dom/server` safely be separated into standalone packages or something that we can then server separately?

**Comment by Aghassi** [comment]
For now I've opened a feature request to have this stuff omitted from the UMD bundle https://github.com/apollographql/apollo-feature-requests/issues/118

**Comment by hwillson** [comment]
Valid points @Aghassi - I'll follow up in the FR. Thanks!
