### ISSUE TITLE
test-utils mock provider will only mock error OR data and NOT both

### ISSUE THREAD

**Issue by joepuzzo** [apollographql/react-apollo#2837]
**Intended outcome:**

Our goal is to write a test that mocks a scenario where an error occurs BUT only for a portion of the query. In other words, we want to test a case where both data AND errors exist. 

**Actual outcome:**

Only errors end up existing

**How to reproduce the issue:**

Try to mock a case with both data and errors

**Version**

- apollo-client@2.4.7
- react-apollo@2.3.2

**Notes: **

I believe the issue is here. If the `if( error )` resolves ( no pun intended ) then it will never resolve the data.

https://github.com/apollographql/react-apollo/blob/master/src/test-links.ts#L96

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, React Apollo feature requests are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=test-utils%20mock%20provider%20will%20only%20mock%20error%20OR%20data%20and%20NOT%20both&body=Migrated%20from:%20apollographql/react-apollo%232837) to start the feature request migration process. This manual migration process is intended to help identify which of the outstanding feature requests are still considered to be of value to the community. Thanks!
