### ISSUE TITLE
What's up with react-apollo maintenance plans?

### ISSUE THREAD

**Issue by jfrolich** [apollographql/react-apollo#2846]
Hi I was wondering what is the background around not keeping react-apollo up to date with React and still using legacy lifecycle methods and context API. Reading the blog post (1 year ago), shows the intention to keep up to date with React's developments (https://blog.apollographql.com/introducing-react-apollo-2-1-c837cc23d926).

> We’re eagerly anticipating the release of React 16.3 and its awesome features like the new context API. Once it arrives, we will release a new major version of React Apollo that’s 100% compatible with async strict mode and all of the latest features.

It is now one year later, and there is not even a pull-request addressing this. Have priorities changed? (also the blog posts pretty much stopped after this post).

As a high profile, and large open source project I was wondering if there was a roadmap or release target from the apollo core team, with when or which version concurrent react are planned to be supported now that they have been shipped for some time.

**Comment by hwillson** [comment]
@jfrolich we're working on updating React Apollo right now, and will have a new release out shortly. Our priorities haven't changed - we're still 100% committed to React Apollo, and have plans to not only keep it up to date, but also expand its functionality. If you (or anyone else) is interested in helping in any way, let us know! Also, [we're hiring](https://www.apollographql.com/careers/positions/) if anyone is interested in working on React Apollo (and related projects) full-time!

**Comment by jfrolich** [comment]
Thanks @hwillson. Great to hear. Will potentially looking in getting in a pull-request.
