### ISSUE TITLE
Announcing Errors

### ISSUE THREAD

**Issue by tomitrescak** [apollographql/react-apollo#286]
Hi, in the current state the errors are fed to component via props. Unless there is a custom mechanism that catches these errors they are silently swallowed and do not appear in console.

Would you consider to add a functionality to your graphql component that would announce errors from Apollo?

For example add console.error at following line? 

https://github.com/apollostack/react-apollo/blob/eb9d588309e6fb861eb656779ead3ef1d85e2a58/src/graphql.tsx#L431

Or maybe something more sophisticated with some global logger. 

[EDIT]

I usually just monkey patch it and add following before the if statement:

``` js
if (error.networkError) {
  console.error(error.networkError.stack);
} else if (error.message) {
  console.error(error.stack);
} else {
  console.error(error);
}
```

With this I even get clickable stack in my console ;)

**Comment by HriBB** [comment]
@tomitrescak your monkey patch just helped me find a bug in my app. Thx!

+1

**Comment by jbaxleyiii** [comment]
@tomitrescak I've been working on adding a logging method on the `<ApolloProvider>` component which would allow for custom dev tooling / something like this.

No timeline as of yet though 👎 I'm pretty busy ATM. If anyone wants to pick it up, I'd be happy to give direction!

**Comment by stubailo** [comment]
Can we set a getter function on `error` that warns if it isn't accessed? That's the only way I can think of to know if the component is handling the error or not.

**Comment by tomitrescak** [comment]
Guys, better yet as per component basis, can logger be set globally via some config file? You probably will not change logging component by component

**Comment by jbaxleyiii** [comment]
This has been improved! If you don't handle errors, they will log out now
