### ISSUE TITLE
Pass mutateFn variables to update

### ISSUE THREAD

**Issue by adrienharnay** [apollographql/react-apollo#2868]
**Intended outcome:**

It is currently impossible (to my knowledge) to access the variables used in a mutation in the update function:

```js
<MutateFunction update={(proxy, { data }) => { doSomething(); }>
  {mutate => (
    <>
      <div onClick={() => { mutate({ variables: id: 1 } }); }} />
      <div onClick={() => { mutate({ variables: id: 2 } }); }} />
    </>
  )}
</MutateFunction>
```

**Actual outcome:**

Sometimes to properly update the cache we need to access the variables (e.g. we delete something on the server and it returns a 204 / Boolean, so we can't access the payload to guess the variables).

**How to reproduce the issue:**

I think the code above is pretty self-explanatory. Let me know if you need more context though!

**Version**

- apollo-client@2.5.1
- react-apollo@2.5.2

Thanks in advance!

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, React Apollo feature requests are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Pass%20mutateFn%20variables%20to%20update&body=Migrated%20from:%20apollographql/react-apollo%232868) to start the feature request migration process. This manual migration process is intended to help identify which of the outstanding feature requests are still considered to be of value to the community. Thanks!
