### ISSUE TITLE
Variable defaults to null but has been omitted before

### ISSUE THREAD

**Issue by eliias** [apollographql/react-apollo#2890]
This [commit](https://github.com/apollographql/react-apollo/commit/3f72fef0263d12769c41a6d8ce103594fc7d364f#diff-752fa63ef9932eb40562c367c6ad6d1c) has removed a condition that previously made the function return if a variable was optional and not set. From 2.5.0 on, every variable is set to null, if optional and not provided any value. I wonder if the new behaviour is intentional and just right or if this is a regression (could not find anything related in [changelog](https://github.com/apollographql/react-apollo/blob/master/Changelog.md)).

**Intended outcome:**

```
variables: {}
```

<img width="165" alt="Bildschirmfoto 2019-03-22 um 01 13 19" src="https://user-images.githubusercontent.com/1222696/54801974-b8e24d00-4c3f-11e9-9979-7a523f86df6b.png">

**Actual outcome:**

```
variables: {
  transform: null
}
```

<img width="161" alt="Bildschirmfoto 2019-03-22 um 01 09 55" src="https://user-images.githubusercontent.com/1222696/54801980-c0095b00-4c3f-11e9-99e9-b4593b55787e.png">

**How to reproduce the issue:**

Create a mutation with at least one optional variable. Call the mutation without a value for the optional variable. 

Compared versions:
- 2.4.1 (variable is not set)
- 2.5.0, 2.5.1, 2.5.2 (all 2.5.x seems to have the regression)

The GraphQL query has an optional variable `transform`.

```
mutation saveX ($transform: Transform) {
  myX(transform: $transform) {
    …
  }
}
```

**Version**

- apollo-client@2.5.1
- react-apollo@2.5.1

**Comment by hwillson** [comment]
@eliias Can you confirm if this is still happening with `react-apollo` 2.5.3?

**Comment by eliias** [comment]
@hwillson Can report in the evening. 👋 to a fellow Ottawa citizen :D

**Comment by eliias** [comment]
Did a quick check on `2.5.3` and tested locally. It still adds `{transform: null}` to the request payload in case the variable is not set.

**Comment by ShepelievD** [comment]
Can also confirm in `2.5.3`

**Comment by AdamTyler** [comment]
This issue is preventing me from creating queries with default values. Since omitted variables come in as `null` it won't replace them with the defaults

**Comment by hwillson** [comment]
This was fixed in https://github.com/apollographql/react-apollo/pull/3056 and will be published in the next RA release. Thanks!

**Comment by silentsakky** [comment]
@hwillson  Any dates for next RA release? it's almost 5 months and fix is not released yet
