### ISSUE TITLE
Query not re-firing when using a client field as a variable

### ISSUE THREAD

**Issue by jwld** [apollographql/react-apollo#2898]
**Intended outcome:**

I'm trying to use a client field in my query as a variable, as detailed [here](https://www.apollographql.com/docs/react/essentials/local-state.html#client-variables). I want to fetch a new item each time the `activeItemId` is changed.

```
const QUERY = gql`
  query Items($itemId: ID!) {
    activeItemId @client @export(as: "itemId")
    item(itemId: $itemId) {
      name
    }
  }
`
```

**Actual outcome:**

When the client field changes, the item remains the same. Changing the default value of `activeItemId` and reloading the page correctly fetches different results (so I know the query works fine) - it's just not being re-fetched when `activeItemId` changes at runtime. I can see from the network tab that the query is only fired off to the backend once on page load.

**Version**

- apollo-boost@0.3.1
- react-apollo@2.5.2

**Comment by hwillson** [comment]
@jwld This is being tracked in https://github.com/apollographql/apollo-client/issues/4530, and a fix is ready for this in https://github.com/apollographql/apollo-client/pull/4604. We still have a few things to tweak before merging, but we should have it ready shortly.

**Comment by jwld** [comment]
Ah perfect, thanks!
