### ISSUE TITLE
refetchQueries returning data twice

### ISSUE THREAD

**Issue by borisyordanov** [apollographql/react-apollo#2906]
**Intended outcome:**

Expected a query to return the latest data.

**Actual outcome:**

Query returned the latest data, then return another set of data with false values (not outdated, but false)

**How to reproduce the issue:**

I was not able to create a reproduction, but here is all the relevant code.

My mutation
```
const { data }: ExecutionResult<any> = await ledgerClient.mutate({
    mutation: CREATE_FUND_EVENT_MUTATION,
    refetchQueries: [
        {
            query: FUNDS_QUERY
        }
    ],
    variables: {
        inputData: fundData
    }
});
```

The GraphQL query
```
export const FUNDS_QUERY = gql`
    query FUNDS_QUERY {
        funds {
            edges {
                node {
                    ... on Fund {
                        cashValue
                        id
                        name
                        identifier
                        info
                        totalShares
                        equity
                        isin
                    }
                }
            }
            pageInfo {
                hasPreviousPage
                hasNextPage
                startCursor
                endCursor
            }
        }
    }
`;
```

My Query component
```
<Query client={ledgerClient} query={FUNDS_QUERY} fetchPolicy="network-only">
    {({ loading, error, data }: QueryResult) => {
        if (loading) {
            return <Loader />;
        }
        if (error) {
            return <p>{error.message}</p>;
        }
        console.log(data.funds.edges.map((i: any) => i.node.name));
    }}
</Query>
```

My client:
```
const fragmentMatcher = new IntrospectionFragmentMatcher({
    // Relevant issue - https://github.com/apollographql/apollo-client/issues/3397#issuecomment-421433032
    introspectionQueryResultData: {
        __schema: {
            types: []
        }
    }
});
const cache = new InMemoryCache({ fragmentMatcher });

const ledgerClient = new ApolloClient({
    cache,
    link: ApolloLink.from([
        errorHandler,
        createUploadLink({
            headers,
            uri: EndpointHelper.getLedger('')
        })
    ])
});
```

After the mutation is made, the query is refetched and it returns the correct updated data. The cache is also updated(checked with Apollo Dev Tools) and it contains the correct data.

The issue is after the Query component gets the updated data, **it rerenders again with another set of data with incorrect values. It's not the old value, nor the new value.** I have no idea where this faulty data comes from.

Example:
1. Inital list of funds is rendered - ['Test', 'Test 22', 'Test 33']
2. I run the mutation to rename `Test 22` into `Test 222` (one more digit)
3. The mutation is executed, the query returns the new list (both in the netowrk response and in the `data` variable) - ['Test', 'Test 222', 'Test 33']
4. The query component rerenders with this data `['Test', 'Test 2', 'Test 33']`

The fund was NEVER called `Test 2`. It seems to me some kind of concatenation happens, but i can't figure out why or how to stop it. I don't want step 4 to happen.

Can anyone tell me why this is happening and how to fix it?

**Version**

- apollo-client@2.5.1
- react-apollo@2.5.2

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
