### ISSUE TITLE
Testing Improvement: onCompleted, onError runs after render for Mutations and before render for Queries

### ISSUE THREAD

**Issue by mbergeronupgrade** [apollographql/react-apollo#2908]
**Intended outcome:**
Both Queries and Mutations will have the response state rendered after onCompleted

**Actual outcome:**

Note that I am trying to use onComplete to get away from the setTimeout based approach for testing final states of both queries and mutations (i.e `wait(0)` is ok on my machine, however on the jenkins build machine it needs to be approximately `wait(10)` and yet is still pretty flaky if multiple builds are run concurrently). If not onCompleted, Query and mutation components should have a callback to be able to test rendered component after a response has been received and rendered.

Turns out mutations have the final state rendered and queries don't when either onCompleted or onError is invoked.

**How to reproduce the issue:**

**Version**

- apollo-client@2.5.1
- react-apollo@2.5.3

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, React Apollo feature requests are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Testing%20Improvement%3A%20onCompleted%2C%20onError%20runs%20after%20render%20for%20Mutations%20and%20before%20render%20for%20Queries&body=Migrated%20from:%20apollographql/react-apollo%232908) to start the feature request migration process. This manual migration process is intended to help identify which of the outstanding feature requests are still considered to be of value to the community. Thanks!
