### ISSUE TITLE
<Query /> not updating after local state is updated in tests

### ISSUE THREAD

**Issue by nshoes** [apollographql/react-apollo#2909]
**Intended outcome:**

When I update local state via `cache.writeQuery`, I expect my `<Query />` component to update. Here's the important bits of code:

- `withApollo` test helper:
```js
export default Component => props => {
  const cache = new InMemoryCache({ addTypename: false })
  cache.writeData({
    data: {
      modal: null
    }
  })
  return (
    <MockedProvider mocks={global.mocks} cache={cache} addTypename={false}>
      <Component {...props} client={cache} />
    </MockedProvider>
  )
}
```
- `openModal` helper:
```js
export const openModal = (client, modal) => client.writeQuery({ query, data: { modal } })
```

- `<Query />`
```js
const QueryWrap = props => (
  <Query query={query}>
    {({ data: { modal } }) => <LayoutModal modal={modal} {...props} />}
  </Query>
)
```

**Actual outcome:**
In the browser this all works, but in my tests it does not. I can `console.log` before and after `client.writeQuery`, and it does indeed change. If I `console.log` within the `<Query />`, it does not update `data.modal` (just stays at the initial state, `null`). I'm hoping I'm just missing something obvious.

**How to reproduce the issue:**
I would be glad to put together a test repro if needed.

**Version**

- apollo-client@2.5.1
- react-apollo@2.5.3

**Comment by nshoes** [comment]
Fat fingered shift + enter before I finished writing it, it's done now! :)

**Comment by rosskevin** [comment]
You are not showing your queries - which is the most important part.  You are likely not including the id in the payload (very common error), making the observable mismatch and the query is never updated.  You likely see the update in react due to a simple case of re-rendering.

Tests for `writeQuery` are in the apollo-client repo and are very thorough for this.

**Comment by nshoes** [comment]
@rosskevin My bad, my query looks like this:

```js
const query = gql`
  {
    modal @client
  }
`
```

There is no`id` in the payload because I'm querying for the value off local state. Am I using `<Query />` and the cache wrong?

**Comment by rosskevin** [comment]
Sorry, I was too hasty.

This looks like a duplicate of #2869
