### ISSUE TITLE
OnCompleted not firing inside of mutate prop with graphql hoc.

### ISSUE THREAD

**Issue by xvandish** [apollographql/react-apollo#2916]
**Intended outcome:**
Be able to use `onCompleted` inside of the `mutate` prop passed by the `graphql()` hoc.

Going off of this snippet from the docs. 
> The properties accepted in this options object may also be accepted by the props.mutate function. Any options passed into the mutate function will take precedence over the options defined in the config object.

[Link to section of the docs](https://www.apollographql.com/docs/react/api/react-apollo#graphql-mutation-config-options)

This is what I want to be able to do. 
``` javascript
<Button
     variant="contained"
     disabled={selectedTimesheetsToApprove.size === 0}
      onClick={() =>
         mutate({
            variables: {
               supervisorLoginName: supervisorLoginName,
               timesheetsToApprove: Array.from(selectedTimesheetsToApprove)
             },
             onCompleted: () => console.log('inside of mutate')
          })
      }
>
      Approve Selected Timesheets
</Button>
```
In this case, nothing at all is printed.

**Actual outcome:**
Can only use `onCompleted` inside of the options directly passed to the `graphql` hoc. The `onCompleted` callback doesn't fire if passed in the `mutate` prop.

This is the only thing that works at the moment.
```javascript
export default compose(
  graphql(GET_ALL_SUPERVISED_UNNAPROVED_TIMESHEETS_FOR_SUPERVISOR),
  graphql(SUPERVISOR_APPROVE_MANY_TIMESHEETS, {
    options: props => ({
      refetchQueries: [{
        query: GET_ALL_SUPERVISED_UNNAPROVED_TIMESHEETS_FOR_SUPERVISOR,
        variables: { supervisorLoginName: props.supervisorLoginName }
      }],
      awaitRefetchQueries: true,
      onCompleted: () => console.log('inside of options')
    }),
  })
)(UnapprovedTimesheetsApproval);
```
Here, the callback executes and `inside of options` is printed to console.

If both `onCompleted` options are set, `inside of options` is printed, so the `onCompleted` inside of mutate for sure isn't overriding the defaults provided in the` graphql` call.

Did I misread/misinterpret the documentation? Thanks for any help!

**How to reproduce the issue:**
I went to produce an example, but the codesandbox linked points to a bad schema and server.

**Version**

- apollo-client@2.5.1
- react-apollo@2.5.3

**Comment by n-kolodziej** [comment]
Try putting `onCompleted` into an object called `options`, just as you did within the compose statement.

**Comment by xvandish** [comment]
@n-kolodziej Good thought! Didn't work though, here what I tried. (Different mutation being used).

**Comment by xvandish** [comment]
@n-kolodziej Good thought! Didn't work though, here what I tried. (Different mutation being used).
Let me know if anything looks off. 

Here's the compose statement. 
```javascript
compose(
  graphql(UPDATE_TEMPLATE, {
    name: 'updateTemplate',
    options: props => ({
      onCompleted: () => console.log('inside of options'),
      refetchQueries: props.refetchQueries
    })
  }),
  graphql(DELETE_TEMPLATE, {
    name: 'deleteTemplate',
    options: props => ({
      onCompleted: () => props.onCompleted('deleted'),
      refetchQueries: props.refetchQueries
    })
  })
)(EditEmailTemplate);
```

Here's the button that triggers the mutation
```javascript
<Button
            variant="contained"
            onClick={() =>
              updateTemplate({
                variables: {
                  templateId: emailTemplate.templateId,
                  body: newBody,
                  label: newLabel,
                  subject: newSubject
                },
                options: {
                  onCompleted: () => console.log('inside of mutate'),
                }
              })
            }
          >
            Update Template
          </Button>
```

This is whats printed to console.
> inside of options EditEmailTemplate.jsx:71

Same thing happens if I remove the onCompleted from the compose(graphql()) statement.

**Comment by n-kolodziej** [comment]
`updateTemplate()` should return a Promise if I'm not mistaken. You could try removing the options object and adding a `then`-block or awaiting the update call.

**Comment by xvandish** [comment]
@n-kolodziej  That worked, thanks! I've also taken a look at the source for withMutation and now understand whats going on. Again, thanks!
