### ISSUE TITLE
Bundle size increase of >50% on upgrade from 2.5.2 to 2.5.3

### ISSUE THREAD

**Issue by damusnet** [apollographql/react-apollo#2918]
Hi everyone,

The patch update from `2.5.2` to `2.5.3` seems to be adding 3.6KB min+gzipped, or a 52% increase from 6.9KB min + gzipped:

![image](https://user-images.githubusercontent.com/433409/55351115-5fb1bf00-5472-11e9-8372-dccd89d9eb52.png)
source: https://bundlephobia.com/result?p=react-apollo@2.5.3

Minified went from 24.2KB to 34.6KB (+10.4KB, +43%).

In my case it failed the size budget on one Webpack chunk by going from 73.99KB to 77.45KB (+3.46KB also, consistent with Bundle Phobia):
![image](https://user-images.githubusercontent.com/433409/55351175-8112ab00-5472-11e9-99e8-8d291045426b.png)

**Version**

- apollo-client@2.5.1
- react-apollo@2.5.3

**Comment by damusnet** [comment]
Update: seems related to the use of `lodash.isEqual`:

![image](https://user-images.githubusercontent.com/433409/55351806-1d897d00-5474-11e9-892d-48e7fd70bc29.png)

~10.13KB seems consistent with the 10.4KB increase between versions.

# 2.5.3

![2 5 3](https://user-images.githubusercontent.com/433409/55351757-fd59be00-5473-11e9-8edd-add2fe0a7fca.png)

# 2.5.2

![2 5 2](https://user-images.githubusercontent.com/433409/55351760-0185db80-5474-11e9-85ec-87135c8c0a02.png)

**Comment by rosskevin** [comment]
Thanks for the stats, let's continue this on the earlier reported issue #2828

**Comment by frederikhors** [comment]
@rosskevin my thread (https://github.com/apollographql/react-apollo/issues/2828) is not about this problem (is about `getDataFromTree`).

This thread is for another one (`lodash.isEqual`).

So I think you should re-open this one. Am I right, @damusnet?

**Comment by damusnet** [comment]
@frederikhors yes. And `lodash,isEqual` is probably easier to fix alone.

**Comment by frederikhors** [comment]
@damusnet, they should reopen this.

**Comment by hwillson** [comment]
This was caused by correcting the fact that `lodash.isequal` was improperly listed as a dev dep. We're no longer using `lodash.isequal` in RA 3 (which will be landing shortly), so this won't be a problem after the next RA major version bump. Thanks!
