### ISSUE TITLE
When Query's query changes, data remains the same

### ISSUE THREAD

**Issue by lorensr** [apollographql/react-apollo#2945]
**Intended outcome:**

When a `<Query>`'s `query` prop changes, `data` becomes `{}` until the data from the new query has arrived from the server.

**Actual outcome:**

`data` contains the data from the previous query until the new data arrives from the server.

**How to reproduce the issue:**

```js
// change `query`

<Query query={query}>
  {({ data }) => console.log(data)}
</Query>
```

https://codesandbox.io/embed/8x6nm1084l

**Version**

- apollo-client@2.5.1
- react-apollo@2.5.2

Similar to #2202

**Comment by hwillson** [comment]
As of `react-apollo` 2.5.6, this can be addressed by using the `returnPartialData` prop. See the [changelog](https://github.com/apollographql/react-apollo/blob/master/Changelog.md#256-2019-05-22) for details. Thanks!
