### ISSUE TITLE
withMutation/withSubscription/withQuery HOCs are undocumented

### ISSUE THREAD

**Issue by slikts** [apollographql/react-apollo#2954]
The document-type-specific HOCs that `graphql()` delegates to (`withMutation`, `withSubscription`, `withQuery`) are currently undocumented but are exported and thus part of the public API; reading the source to `graphql()` makes their role clear, but someone who encounters these HOCs in use and wants to look them up in the docs could be confused, since they're undocumented, and google results for terms like "react-apollo withMutation" are also ambiguous.

**Comment by hwillson** [comment]
If anyone wants to work on a docs PR to correct this, we'll get it in. Thanks!

**Comment by slikts** [comment]
I'm not sure it's correct to close unresolved issues.

**Comment by hwillson** [comment]
@slikts Issues in the repo are now intended to only be used for bugs. This isn't a bug (not documenting these was originally intentional), so it was closed. We're managing feature requests over in https://github.com/apollographql/apollo-feature-requests if you're interested in migrating this issue over there.

**Comment by mauritsl** [comment]
This issue pops up on Google when searching for its docs.

The hooks are documented here:
https://www.apollographql.com/docs/react/essentials/mutations/

**Comment by ackvf** [comment]
Stumbled upon this while trying to search for withQuery documentation.

I need to execute a query manually on user interaction without hooks.
hook approach: https://www.apollographql.com/docs/react/essentials/queries/#executing-queries-manually
