### ISSUE TITLE
Undefined data after upgrade in Query body result

### ISSUE THREAD

**Issue by sashberd** [apollographql/react-apollo#2966]
Hi guys,

May be this issue is related to #1314 however, I did not found exact match of this issue in #1314 conversations.

We used before a week old version of react-apollo - 2.1.3 and we decided to upgrade it to latest one 2.5.4. After upgrade we found that all our queries, at most Query tag components does not provides data as their were before. We found that breaking changes were made in v2.2.0 (PR #1916 as we understood and see provided example). The issue is that by PR #1983 the data should be empty object and we got undefined (no error) and that is because we have skip true in our code example. In my vision skip should not execute query at all, it should not render any html or data.  The question is that a bug or this is normal feature? 
If this is normal feature so how we should know the result is well or there is an error.

 ```
<Query
          fetchPolicy={process.browser ? 'cache-first' : 'network-only'}
          skip={
            !projectId ||
            !project.owner ||
            !this.props.currentUser ||
            !this.props.currentUser.userId ||
            isOwner 
          }
          query={getUserSubscriptionToOwner}
          variables={{
            subscriptionCondition: {
              follower: this.props.currentUser && this.props.currentUser.userId,
              followee: projectByShortId && projectByShortId.owner,
            },
          }}>
          {(result) => {/*The result.data is undefined in case of skip=true*/}}</Query>
```

The versions are: 
    "apollo-cache-inmemory": "1.1.4",
   "apollo-client": "2.3.8",
    "apollo-link": "1.1.0",
    "apollo-link-error": "1.1.2",
    "apollo-link-http": "1.3.2",
    "apollo-link-persisted-queries": "0.2.0",
    "apollo-utilities": "1.0.11",
    "react-apollo": "2.2.0"

Thanks for you help

**Comment by sashberd** [comment]
@hwillson Can you help with this issue?

**Comment by bristoljon** [comment]
Hitting this too, after upgrading. Seems that skip now results in `undefined` data property

**Comment by lifeiscontent** [comment]
running into `undefined` here as well without skip I have my fetchPolicy set to `cache-and-network`

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
