### ISSUE TITLE
Feature Request: Optimistic Response Identifier

### ISSUE THREAD

**Issue by sAnti09** [apollographql/react-apollo#2967]
It would be nice if there's a way to know if the data is a result of an optimistic response or from the server.

A `__cached` property would be great.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, React Apollo feature requests are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Feature%20Request%3A%20Optimistic%20Response%20Identifier&body=Migrated%20from:%20apollographql/react-apollo%232967) to start the feature request migration process. This manual migration process is intended to help identify which of the outstanding feature requests are still considered to be of value to the community. Thanks!
