### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by sigfriedCub1990** [apollographql/react-apollo#2979]
Hello guys:
I was looking at the implementation of `Query.tsx` just to get my head around React `render-props` and this line got my attention:
https://github.com/apollographql/react-apollo/blob/70f63abb7a0dd138e245f1db131dd121097823e5/src/Query.tsx#L186
According to [React documentation](https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops) this method will be deprecated in React v17. Cheers and keep up with this great library, sigfried.

**Comment by hwillson** [comment]
Thanks @sigfriedCub1990 - we're currently working on `react-apollo` 3.0, which will no longer use React lifecycle methods. You can follow along [here](https://github.com/apollographql/react-apollo/pull/2892).
