### ISSUE TITLE
renderToNodeStream and window.__APOLLO_STATE__ in footer

### ISSUE THREAD

**Issue by secretlifeof** [apollographql/react-apollo#2986]
**Intended outcome:**
Apollo Client (client side) to restore cache from server rendered window.__APOLLO_STATE__.

**Actual outcome:**
Apollo Client performs all the GraphQL query client-side.

I am actually using react-apollo-hooks but I do not believe this is a problem with this but a global apollo-client problem. Already posted to react-apollo-hooks repository.
[react-apollo-hooks #139](https://github.com/trojanowski/react-apollo-hooks/issues/139)

Using renderToNodeStream apollo adds another graphQL-query client-side, when window.APOLLO_STATE is located in the footer/at the bottom of the HTML-document.

I can see a flickering resulting from a re-rendering of the react-component (useQuery loading is shown). If I turn off javascript in the browser everything renders as expected.

This behaviour is not observed when window.APOLLO_STATE is added to HTML-head.

Being a beginner I imagine this behaviour coming from: The javascript/apollo-app loads quicker and before the footer has been streamed, leading to window.APOLLO_STATE being interpret as being null.

**How to reproduce the issue:**
I have created this small repository to recreate the problem from my bigger app:
https://github.com/secretlifeof/firstParcel.

**It might be related to:**
[#4639](https://github.com/apollographql/apollo-client/issues/4639)

**What I have tried:**
Using Parcel and Razzle without change
SSRForceDelay to ApolloClient without change

Do you know any solution to this? Is the cause of this behaviour the query result being too big?

**Versions:**
react-apollo-hooks: 0.4.5
react-dom: 16.8.6
node: 11.9
apollo-cache-inmemory: 1.5.1
apollo-client: ^2.5.1
apollo-link-http: ^1.5.14
apollo-utilities: ^1.2.1

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
