### ISSUE TITLE
How to skip query on component load?

### ISSUE THREAD

**Issue by bintoll** [apollographql/react-apollo#3004]
Hi)
It is not an issue, it is a question. (or in case if there is no answer for this (I did not find) it could be also a proposal for new feature)
How to skip a query on component load, in a right way, using compose and graphql HOC function? 
Please, do not suggest me to pass "skip" option to graphql function, it is not the right way in my case because:
- I had to run some business logic inside the wrapped component. And only after that pass a variable to the query.
Currently I keep query on component load with error and then refetch query with needed variables. But it is not the right way, I do not want the query to be executed first time with error.
Also please do not suggest ApolloConsumer and renderProp solution, because I really think that logic should be separated from rendering and would like to keep render method clean. Also it would lead to many base changes. I am looking for simple, elegant solution for such an easy case.
UPD: I found in doc exactly what I want - "Manually firing a query" but it uses ApolloConsumer and renderProp and manual firing a query using a client (not helper function like refetch). But I can not understand why there is such a strange approach when it is really meaningful to add an option to graphql HOC function like, ```skipOnComponentLoad``` for example. Wonder to hear, that there is something like this.=)

- The really strange way is that skip option completely removes the query from props (I know it is stated in doc), however I can not understand the reason of that. But it leads to an interesting problem:
If one query depends on other query like query "user" depends on query "checkToken". So the query user is skipped and it means that it would be undefined in nextProps.
And it lead to the problem when it is not possible to use this assign:
```
const {
        checkToken: {checkToken: checkTokenResult},
        user: { user: userResult }  } = this.props
```
Because user in this case will be undefined. So I have to move back to the old *nice* syntax
const userResult = this.props.user && this.props.user.user
And in case if there would be many queries that are depend on each other it will lead to many lines of code like this. (I handled it with the helper function, however I am sure that it should be handled by the library itself somehow)
Also you probably noticed the naming - ```this.props.user.user```. It is really strange to have this naming (I set the alias as "user") and I can not understand what is the reason to specify query name after the alias is set. (but the alias is a must, otherwise it will be called as ```data``` and all queries will rewrite each other under this key) But this is not a big problem, just thought to point it out.
UPDATED: Found another very important use case where the issue also presents. In case if I would like to fire query after mutation, there is no way to handle this right when query fires on component load.

**Comment by hp0210** [comment]
+1 for this

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, React Apollo feature requests are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=How%20to%20skip%20query%20on%20component%20load%3F&body=Migrated%20from:%20apollographql/react-apollo%233004) to start the feature request migration process. This manual migration process is intended to help identify which of the outstanding feature requests are still considered to be of value to the community. Thanks!
