### ISSUE TITLE
Feature Request: Named props should have sub prop called "data"

### ISSUE THREAD

**Issue by derblitz** [apollographql/react-apollo#3005]
**Intended outcome:**
Using HOC with multiple queries and named props, the actual data should be accessible using a sub-prop called "data" (like it is possible when not using named props).

Example Query:
```
export const QUERY_GET_OWN_COLLECTIONS = gql`
  query {
    getOwnCollections {
      id
      name
    }
  }
`
```

Example HOC:
```
export default compose(
    graphql(QUERY_GET_DASHBOARD_STATE, { name: "QGetDashboardState" }),
    graphql(QUERY_GET_OWN_COLLECTIONS, {name: "QGetOwnCollections"})
)(SidebarContainer);
```
I want to access the data like this:
```
this.props.QGetOwnCollections.data.name
```

**Actual outcome:**

However, currently I need to access the returned data using:
```
this.props.QGetOwnCollections.getOwnCollections.name
```

**Version**

- apollo-client@<2.5.4>

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, React Apollo feature requests are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Feature%20Request%3A%20Named%20props%20should%20have%20sub%20prop%20called%20%22data%22&body=Migrated%20from:%20apollographql/react-apollo%233005) to start the feature request migration process. This manual migration process is intended to help identify which of the outstanding feature requests are still considered to be of value to the community. Thanks!
