### ISSUE TITLE
Mutation component triggers componentWillReceiveProps deprecation warning

### ISSUE THREAD

**Issue by Glennrs** [apollographql/react-apollo#3007]
**How to reproduce the issue:**

After upgrading to React Native 0.59.5, using the Mutation component triggers a deprecation warning for componentWillReceiveProps.

**Version**

- apollo-client@2.5.1
- react-apollo@2.5.5

**Comment by JoviDeCroock** [comment]
This PR: https://github.com/apollographql/react-apollo/pull/2892

Is focussed on removing deprecated React features aswell as lay the foundation to moving forward.

**Comment by hwillson** [comment]
As mentioned in https://github.com/apollographql/react-apollo/issues/3007#issuecomment-489219627, this has been addressed in the RA 3 branch, which will be launching soon. Thanks!
