### ISSUE TITLE
Loading state `true` for client-side only query on init

### ISSUE THREAD

**Issue by giggo1604** [apollographql/react-apollo#3009]
**Intended outcome:**
A client side only query should not have a loading state as hinted?! in the docs. 

**Actual outcome:**
The Query component synchronously?! renders twice. For the first render with `loading===true` and an empty `data` object.

**How to reproduce the issue:**
I made an minimal example in this codesandbox:
https://codesandbox.io/s/mjnp449kkj       

**Version**

- apollo-client@<2.5.1>
- react-apollo@<2.5.5>

**Comment by OurMajesty** [comment]
I did came across this too, but thought this did happen because of `defaultOptions`'es `fetchPolicy` set to `'network-only'` for all queries. So, I was wrong then.

**Comment by giggo1604** [comment]
Any Input/Update on this? I was able to hack around it but just recently discovered a second problem where you can't rely on the data object not to be empty for queries which combine remote data and local state.

Any guidance if this is expected behavior, or if I'm doing something wrong in my example, would be appreciated.

**Comment by pdemarino** [comment]
I am witnessing the same thing. A client-only query stuck on "loading".

Intriguingly...

1. The very same query resolves immediately, and correctly, is I use `client.query` instead of `useQuery` / `<Query>`
1. If I modify the query to contain any non-`@client` field, it resolves correctly.

**Comment by pdemarino** [comment]
This seems to be related to #3270

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
