### ISSUE TITLE
Mutation onCompleted not running when set to the render prop

### ISSUE THREAD

**Issue by tafelito** [apollographql/react-apollo#3017]
I run into an issue where I need to navigate to a new screen when a mutation is completed. Debugging the code I can see that the OnCompleted callback is only being fired if is passed as a prop to the mutation, but it does not if is passed as a prop of the render prop. Pretty much what I need to do is the same as with the variables prop. 

**Intended outcome:**
this is an example of what I'm trying to do
```
<Mutation mutation={mut}>
            {updateMutation => {
              return (
                <Component {...{ updateMutation }} />
              );
            }}
</Mutation>
```
Then, within the component 
```
function Component({updateMutation}) {
    return (
        <Button onPress={()=> {
                updateMutation({
                    variables: {...},
                    onCompleted: ()=> {...}
                })
        } />
    )
}
```

**Actual outcome:**
The onCompleted callback not being fired. The onCompleted has to be assigned to the Mutation component, but I can't do that because I need some values for the child component.

The variables prop is merged but the callbacks are not

https://github.com/apollographql/react-apollo/blob/2a330a770d96b8849abb40906b2dacdf69187d3b/src/Mutation.tsx#L222
 
https://github.com/apollographql/react-apollo/blob/2a330a770d96b8849abb40906b2dacdf69187d3b/src/Mutation.tsx#L250

**Versions**
```
  System:
    OS: macOS Mojave 10.14.4
  Binaries:
    Node: 11.11.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 73.0.3683.103
    Safari: 12.1
  npmPackages:
    apollo-link-state: ^0.4.2 => 0.4.2 
    react-apollo: ^2.5.5 => 2.5.5 
```

**Comment by JoviDeCroock** [comment]
I have double-checked the typings for MutationOptions and these are the following: 

```export declare type MutationOptions<
  TData = Record<string, any>,
  TVariables = OperationVariables
> = {
  variables?: TVariables;
  optimisticResponse?: TData;
  refetchQueries?: Array<string | PureQueryOptions> | RefetchQueriesProviderFn;
  awaitRefetchQueries?: boolean;
  update?: MutationUpdaterFn<TData>;
  context?: Record<string, any>;
  fetchPolicy?: FetchPolicy;
};```

It can't be passed into the function, sorry for the misguided information on Spectrum.

You can however do this:
```
await mutationFunc() --> RETURNS promise
onCompleted();
```

**Comment by tafelito** [comment]
thanks @JoviDeCroock I didn't realize it returned a promise. That works
