### ISSUE TITLE
Document used mock removal in MockProvider

### ISSUE THREAD

**Issue by bannier** [apollographql/react-apollo#3023]
Apparently, mock are removed once used.

https://github.com/apollographql/react-apollo/blob/e5f272b2556b38f5d0c0391fc16e8579f7223c06/src/test-links.ts#L85

If so, this should be documented here : 
https://www.apollographql.com/docs/react/recipes/testing

**Comment by hwillson** [comment]
Issues here are reserved for React Apollo bugs. Would you mind opening this request over in the [Apollo Feature Request repo](https://github.com/apollographql/apollo-feature-requests)? Thanks!
