### ISSUE TITLE
getDataFromTree not working on react router's render function

### ISSUE THREAD

**Issue by Pixelatex** [apollographql/react-apollo#3033]
**Intended outcome:**

getDataFromTree should detect my queries and return the data correctly.

**Actual outcome:**

getDataFromTree ignores the queries and returns 0 data.

**How to reproduce the issue:**

Routes use`render={(props) => <Page {...props} config="test" />}` instead of `component={Page}`
- My site is dynamic and requires a config per page, that's why I use the render function of RR.

**Version**

- apollo-client@^2.5.1
- react-apollo@^2.5.5

**Comment by jasonpaulos** [comment]
Hi @Pixelatex, thanks for the bug report! Could you provide a small runnable reproduction (either as a github repo or in codesandbox.io) that demonstrates this issue?

**Comment by hwillson** [comment]
We haven't heard back regarding a reproduction for this, so closing for now. Happy to re-open if anyone can provide a repro. Thanks!

**Comment by Pixelatex** [comment]
Ah I never saw an comment update for this, I'll see if I can make a repo with this issue in it.

**Comment by igorlimansky** [comment]
@Pixelatex did you resolve this issue? Looks like I'm facing the same problem
