### ISSUE TITLE
How to implement next-with-apollo with react-apollo SSR?

### ISSUE THREAD

**Issue by KumarAbhirup** [apollographql/react-apollo#3038]
**This is not any bug-report. Just a question.**

I am using `react-apollo` with `Next.js` the way it is illustrated in the [example from the Next.js repo](https://github.com/zeit/next.js/tree/canary/examples/with-apollo).

Complete question detail on [Spectrum Next.js community](https://spectrum.chat/next-js/general/how-to-implement-next-with-apollo-with-react-apollo-ssr~20914c2c-b8ae-4bc7-aac0-45a14a1eacb7).

**Version**

- apollo-client@2.5.1
- react-apollo@2.5.4

**Comment by jasonpaulos** [comment]
It looks like you got help in https://github.com/lfades/next-with-apollo/issues/58, so I'm going to close this. Feel free to reopen the issue if you have further questions.

**Comment by KumarAbhirup** [comment]
Now in 2020, when I use hooks, it turns out the problem isn't solved with Next.js 9.
This time, I am not sending a cookie from the backend, I only send a token from the backend.

But it only renders on the Client Side.

I think we should reopen this issue.
