### ISSUE TITLE
Allow embedding the types of the GraphQL document so they can be inferred

### ISSUE THREAD

**Issue by lemonmade** [apollographql/react-apollo#3054]
**Problem:**

One of the potentially frustrating things of using Apollo and TypeScript together is that the types for a document don’t "travel" with the document. This means that any usage of an API that needs access to those types — `graphql`, `Query`, `Mutation`, future hooks, etc — needs to manually supply the data and variable typings.

(Note: I know this isn't strictly an issue with the React library, but felt like a reasonable place to discuss it. Let me know if I should move this issue elsewhere.)

**Userspace solution:**

Here's how we've dealt with this at Shopify (presented to show both what is possible, and the lengths a team needs to go to in userspace to actually get strong typing):

- Wrote our own `DocumentNode` type that extends the base one, but has generics for `Data`, `Variables`, and a special `DeepPartial` version of the data we use in testing: https://github.com/Shopify/graphql-tools-web/blob/master/packages/graphql-typed/index.ts#L17-L19.
- Wrote our own TypeScript type generator, which spits out a `.d.ts` file per `.graphql` file, which uses the special `DocumentNode` outlined above: https://github.com/Shopify/graphql-tools-web/tree/master/packages/graphql-typescript-definitions
- Wrote our own versions of `graphql`, `Query`, `Mutation`, and hooks that know to infer the types of data/ variables from the special `DocumentNode` type: https://github.com/Shopify/quilt/blob/master/packages/react-graphql/src/Query.tsx#L7-L13

With these in place, developers do not need to worry about when or where to pass generics; they're safely passed throughout the system without any manual involvement:

```tsx
import {Query} from '@shopify/react-graphql';

// TypeScript imports the MyQuery.graphql.d.ts file, which shows the default export of
// type DocumentNode<DataType, VariableType>
import myQuery from './MyQuery.graphql';

function MyComponent() {
  // Forgot to supply required variables? The component will actually complain!
  <Query query={myQuery}>{({data}) => { /* data is correctly typed! */ }}</Query>;
}
```

With this embedded type information you can do a lot of other useful things, too. We use it in tests to provide the type of data that a user must supply as a fixture to our library for "filling in" partial query results in tests (https://github.com/Shopify/graphql-tools-web/tree/master/packages/graphql-fixtures):

```tsx
// TypeScript complains if myQuery’s `fieldWithWrongType` field is not boolean/ optional boolean
const graphQLResult = fillGraphQL(myQuery, {fieldWithWrongType: true});
```

**Proposal:**

I am not really sure what my proposal is here. My preference would certainly be to see some of the special sauce Shopify uses become more standard. At a minimum, having Apollo respect a `DocumentNode` with generic arguments for data/ variables would allow people to get a bit more automatic behaviour, although with most type generation solutions out there, they'd still need to cast their document to be the right type. Having the type generator enhanced to generate a `DocumentNode` type with the correct generics would allow it to be about as automatic as we have in our own codebase right now, which to me does a better job of fulfilling the promise of strongly typed data throughout the system.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, React Apollo feature requests are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Allow%20embedding%20the%20types%20of%20the%20GraphQL%20document%20so%20they%20can%20be%20inferred&body=Migrated%20from:%20apollographql/react-apollo%233054) to start the feature request migration process. This manual migration process is intended to help identify which of the outstanding feature requests are still considered to be of value to the community. Thanks!
