### ISSUE TITLE
Hooks and server side rendering

### ISSUE THREAD

**Issue by mattiasewers** [apollographql/react-apollo#3057]
This not a bug report just about hooks and if it supports ssr? I've tried to use the new react-hooks library but it does not seem to work.

**Comment by gridviewdesign** [comment]
From what I can tell, it does not work yet.  Hopefully, this is something that they are actively working on. The app and data will still load to the DOM, but viewing the source shows the loading state is what actually got rendered most of the time. The `react-apollo-hooks` library appears to work properly since they use their own implementation of `getDataFromTree` called `getMarkupFromTree`.

**Comment by hwillson** [comment]
@mattiasewers The latest `@apollo/react-hooks@beta` has SSR support for Hooks. The version you tested didn't have SSR enabled as the non-SSR parts were needed first (and we wanted to get a beta out sooner than later), but everything should now be in the latest `beta` (0.1.0-beta.6).

**Comment by kirankalyan5** [comment]
Hi, @hwillson I'm using the latest  @apollo/react-hooks@beta, but hooks for SSR don't seem to work for me with { getDataFromTree } from react-apollo.

I'm not sure If I'm missing something to enable hooks for SSR to prefetch the data.
Appreciate your help.

**Comment by hwillson** [comment]
@kirankalyan5 could you provide more details that show what you're trying, and what the outcome is? I'm currently working on a few SSR related changes, but SSR should be working with the current `beta`. Also, would you mind opening a new issue with these details? Thanks!

**Comment by kirankalyan5** [comment]
Hi @hwillson I do something like this at the moment

```javascript
import { ApolloProvider } from '@apollo/react-hooks';
import { ApolloClient } from 'apollo-client';
import { getDataFromTree } from "react-apollo"
import { InMemoryCache } from 'apollo-cache-inmemory';
import { HttpLink } from 'apollo-link-http';

const client = new ApolloClient(
link: new HttpLink({
      uri: location,
      headers: {
        authorization: '', //token
      },
    }),
    cache: new InMemoryCache(),
    ssrMode: true,
); // all client set up

  const WrappedApp = (
    <ApolloProvider client={client}>
      <App />
    </ApolloProvider>
  );
  await getDataFromTree(WrappedApp)
  const initialState = client.extract();
  const content = ReactDOM.renderToString(WrappedApp);

  const html = getHtml( content, initialState); >;

// finally send the rendered HTML with data
  res.status(200);
  res.send(`<!doctype html>\n${ReactDOM.renderToStaticMarkup(html)}`);
  res.end();
});
```

But currently, the Html from a server and the window variable doesn't include any data.

The same setup works which I use the ApolloProvider from 'react-apollo-hooks' with their `getMarkupFromTree`.

let me know if I'm missing something or I shall create a new issue.

Thanks
