### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'linkClientUser' of undefined

### ISSUE THREAD

**Issue by Huzaifaahmed20** [apollographql/react-apollo#3058]
**Intended outcome:**
Api is working fine from playground as well as from frontend

i am making mutation like 
```javascript
import gql from 'graphql-tag';

export default gql`
  mutation linkClientUser($client_id: [Int], $user_id: [Int]) {
    linkClientUser(client_id: $client_id, user_id: $user_id) {
      user {
        name
      }
    }
  }
`;
```

it gives correct response and mutation is working.

Where mutation is using
```javascript
handleSubmit = () => {
    const { userID, mutate, refetch } = this.props;
    const { clientsData } = this.state;
    if (!clientsData.length) {
      this.setState({
        error: 'No clients selected'
      });
      return;
    }
    const client_ids = clientsData.map(client => Number(client.id));
    mutate({
      variables: { client_id: client_ids, user_id: Number(userID) }
    })
      .then(response => {
        console.log('response', response); // this console is not working
        this.setState({
          successMessage: response.data.success.message,
          successMessageAlert: true,
          open: false,
          clientsData: []
        });
        refetch();
      
        this.setState({
          error: response.data.error.message
        });
      })
      .catch(err => console.log(err));
  };
```

```javascript
export default graphql(linkClientUser)(SimpleModalWrapped);
```

**Actual outcome:**
But this error comes and crashes 
![error](https://user-images.githubusercontent.com/26674425/58240786-1ccee200-7d65-11e9-9252-dee69202299f.png)

**Version**
- react-apollo@2.3.3

**Comment by jasonpaulos** [comment]
Hi @Huzaifaahmed20, can you provide a small runnable reproduction (either as a github repo or in codesandbox.io) that demonstrates this issue? Thanks

**Comment by Huzaifaahmed20** [comment]
> Hi @Huzaifaahmed20, can you provide a small runnable reproduction (either as a github repo or in codesandbox.io) that demonstrates this issue? Thanks

Thanks for replying you can checkout this issue in sandbox in App.js file the console is not printing response but api is working 
https://codesandbox.io/s/dreamy-wildflower-msupf?fontsize=14

**Comment by jasonpaulos** [comment]
@Huzaifaahmed20 did you find a fix for this problem?

**Comment by Huzaifaahmed20** [comment]
Yeah the issue is from backend, i.e the response from backend is not correctly configured, so that's why this error came.
