### ISSUE TITLE
Query component fetchPolicy 'no-cache' does not work

### ISSUE THREAD

**Issue by EmmanuelPonnudurai** [apollographql/react-apollo#3060]
**Intended outcome:**

When using the `Query` render prop along with fetchPolicy of 'no-cache', it should not lead to any errors and should bypass cache as the name suggests.

**Actual outcome:**

It doesn't work. We get null value from the data returned from the render prop. 

**How to reproduce the issue:**

This sandbox clearly shows the issue -  https://codesandbox.io/s/apollofetchpolicy-4z4jy

In the sandbox, you will find 2 components, 
- `<App />`. This uses the `Query` render prop and shows the error in action. 
- `<AppWithNoQueryComponent />` This uses the ApolloClient directly and a funtional stateful component with hooks, to make the graphql call. This version works without issues even when I use 'no-cache'. 

I'd like to know how to fix this OR if I am doing something wrong OR  is this a known issue?

Please note that in our application we use the `Query` component heavily since that is mostly advocated in the docs. 

Background: 
We are in the process of troubleshooting an important performance issue when using react apollo client in our application, for backend graphQL calls which returns lot of data. From the initial performance profiling that was done using Chrome browser,  it appears that the scripting tasks by apollo are taking longer than expected. Before digging further into that, we tried to rule this out by totally detaching dependency on cache by using 'no-cache', but looks like it doesn't work. 

Any direction or assistance would be highly appreciated. 

Thank you in advance for your help. 

**Version**

- apollo-boost@0.3.1
- react-apollo@2.5.6

Note: For some strange reason when I use apollo-boost@0.4.0, I get some other errors while importing `ApolloClient` but I'm unsure if that is related to the library or code sand box app. But I just wanted to add it in here too so FYI.

**Comment by AndrewKovalenko** [comment]
I have the same problem with 

```
"apollo-boost": "0.4.0",
"graphql": "14.3.1",
"react-apollo": "2.5.6",
```

Digging into the code showed that it happens because of 

```

https://github.com/apollographql/react-apollo/blob/master/src/Query.tsx#L155

**Comment by gandhirachana** [comment]
Is there any update on this issue? I am seeing similar issue in my application.

**Comment by scf4** [comment]
make sure you do not have `ssrMode: true` in ApolloClient options

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!

**Comment by AndreiCalazans** [comment]
@hwillson is there any workarounds for us stuck at older versions? 

"react-apollo": "2.1.9"
