### ISSUE TITLE
TypeScript example does not work

### ISSUE THREAD

**Issue by AlanFoster** [apollographql/react-apollo#3061]
**Intended outcome:**

The command runs succesfully

**Actual outcome:**

```
error: Error while fetching introspection query result: request to https://mpjk0plp9.lp.gql.zone/graphql failed, reason: certificate has expired
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! typescript-example@0.1.0 schema: `apollo-codegen introspect-schema https://mpjk0plp9.lp.gql.zone/graphql --output ./src/schema.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the typescript-example@0.1.0 schema script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**How to reproduce the issue:**

```
git clone git@github.com:apollographql/react-apollo.git
cd react-apollo
cd examples
cd typescript
npm install
npm run schema
```

You can see this the specific error in the browser when visiting the URL:

> 503 Service Unavailable: No healthy endpoints to handle the request. If you're the owner of this app, see this article for more information: http://bit.ly/2uCFzOo

**Version**

[Apollo@fff08ff5d6b599a9ed1be6fcc171519e6c22cae1](https://github.com/apollographql/react-apollo/commit/fff08ff5d6b599a9ed1be6fcc171519e6c22cae1)

**Comment by hwillson** [comment]
This has been resolved in the [RA 3 branch](https://github.com/apollographql/react-apollo/tree/release-3.0.0). Thanks!
