### ISSUE TITLE
Passing a client via props don't work if skip is true

### ISSUE THREAD

**Issue by rui-ribeiro** [apollographql/react-apollo#3062]
**Intended outcome:**

I don't want to provide a client trough ApolloProvider instead I want to pass one via props. Like this:

```js
const WrappedComponent = graphql(QueryExample, {
  skip: props => props.shouldSkip,
  options: { client: MyClient }
})(Component);
```

I think the client property should follow the same approach of the skip property and be removed from the options object. (#245)

The problem is if the query is skipped the options is not called, so the client is not present and I receive the following error:

>Could not find "client" in the context or passed in as a prop. Wrap the root component in an <ApolloProvider>, or pass an ApolloClient instance in via props.

**Actual outcome:**

If I pass a client via props on a component that has a skip rule, when the query is skipped I receive an error saying that the client was not found.

**How to reproduce the issue:**

Just try to provide a Client trough props and then define skip always as true and you will receive the error.

```js
const WrappedComponent = graphql(QueryExample, {
  skip: true
  options: { client: MyClient }
})(Component);
```

This only happens after the version 2.x.x, because of this merge request #1330

**Version**
- apollo-client@2.5.1
- react-apollo@2.4.1

**Comment by OurMajesty** [comment]
There's `window._APOLLO_CLIENT__`, but it's not the best solution.

**Comment by rui-ribeiro** [comment]
My solution was to create a dummy client with ApolloProvider. So react-apollo can always find a client either on props and on context.

If it finds the client on the context is because I want to skip the query so is not a problem that this dummy client doesn't work at all.

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
