### ISSUE TITLE
How can I fetch per Apollo client to create dynamic drawer routes (React Navigation)?

### ISSUE THREAD

**Issue by donni106** [apollographql/react-apollo#3069]
I already posted this yesterday in https://github.com/react-navigation/react-navigation/issues/5935 but maybe it is more appropriate here?

I cannot use the `client` inside my creation of navigation items.

**1. I create my Apollo stuff and return**
```
<ApolloProvider client={client}>
  <AppContainer />
</ApolloProvider>
```

**2. `AppContainer` is in a separate file**
```
createAppContainer(AppDrawerNavigator)
```

**3. `AppDrawerNavigator` is in a separate file**
```
createDrawerNavigator(
  {
    HomeStack: {
      screen: HomeStackNavigator
    },
    ...drawerRoutes
  },
  {
    initialRouteName: 'HomeStack',
    drawerPosition: 'right'
  }
);
```

**4. `drawerRoutes` is an hard coded object**
```
const drawerRoutes = {
  First: {
    screen: IndexStackNavigator
  },
  Second: {
    screen: IndexStackNavigator
  }
};
```

Now I want to dynamically create the `drawerRoutes` after querying the Apollo client.
But I did not manage to access the client inside `createDrawerNavigator`.
Also I cannot pass something down to the `createDrawerNavigator`. Is there a tricky way to do that?
Best would be to create the `drawerRoutes` in the 1. step an than pass down the route object to the 3. step.

When I put everything in one file, it is working. But the file gets messy.

Can anybody help? Do you need more information?

**Comment by jasonpaulos** [comment]
It looks like you found a solution to your issue on the react-navigation thread, so I'll close this. Feel free to reopen if you still have an issue.

**Comment by donni106** [comment]
Thanks @jasonpaulos. I also posted it on StackOverflow and found `ApolloConsumer` https://stackoverflow.com/a/56426697/9956365. I have not tried out yet, but it sounds the best way for me to access the `client` directly elsewhere, right?

**Comment by jasonpaulos** [comment]
Yep! That's the idea behind ApolloConsumer, and you can read more about it in the docs: https://www.apollographql.com/docs/react/api/react-apollo/#apolloconsumer
