### ISSUE TITLE
package.json: peerDeps: apollo-client beta, maybe can move to 2.6.0?

### ISSUE THREAD

**Issue by gabor** [apollographql/react-apollo#3077]
**Intended outcome:**
when doing a `yarn install`, i do not get an incorrect-peer-dependency warning.

**Actual outcome:**
when doing a `yarn install`, i get: `react-apollo@2.5.6" has incorrect peer dependency "apollo-client@beta"`

**How to reproduce the issue:**
create an empty project, add `react-apollo` and `apollo-client@2.6.0`. run `yarn install`

i checked the react-apollo changelog, and the peer-dependency on apollo-client@beta was added in https://github.com/apollographql/react-apollo/commit/cfb5391911706022f2a951fa453867358b89ab70 , saying `Wire in Apollo Client 2.6 beta's`. now that apollo-client@2.6.0 is released, could the peer-dep be moved to the non-beta apollo-client@2.6.0?

**Version**

- apollo-client@2.6.0
- react-apollo@2.5.6

**Comment by hwillson** [comment]
Fixed in https://github.com/apollographql/react-apollo/pull/3064. Changes will be deployed shortly. Thanks!

**Comment by dipta007** [comment]
I am facing the same issue
Is there any way to solve?
```
warning " > react-apollo@2.5.6" has incorrect peer dependency "apollo-client@beta".
```

**Comment by vfonic** [comment]
:+1: Is this released? Thanks!

**Comment by vladshcherbin** [comment]
This one should be released as it still shows this warning.
