### ISSUE TITLE
Query component ignores fetchPolicy `network-only`

### ISSUE THREAD

**Issue by AndrewKovalenko** [apollographql/react-apollo#3084]
**Intended outcome:**

`<Query fetchPolicy='network-only'` fetches data from a GraphQl end-point instead of returning cached data

**Actual outcome:**

`<Query fetchPolicy='network-only'` returns data from client cache not making a network request

**How to reproduce the issue:**

1. Query data with `<Query fetchPolicy='network-only'`
2. Change the data returned by endpoint
3. Re-query same data

**Version**
```
apollo-boost@0.4.0
graphql@14.3.1
react-apollo@2.5.6
```

**Comment by ozanmanav** [comment]
I reproduced your case with my api here https://codesandbox.io/s/fragrant-wood-j889m. I think it's working. 

Can you check your network requests and check data from playground?

**Comment by AndrewKovalenko** [comment]
@ozanmanav in your example how do you reproduce "step 2"?

**Comment by AndrewKovalenko** [comment]
Deeper digging showed that this issue is not caused by `Query` HOC. The root cause of the problem lives in apollo-client way of [storing data in memory cache](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-cache-inmemory/src/writeToStore.ts#L152). 

Because of apollo uses some kind of [flyweight patter](https://en.wikipedia.org/wiki/Flyweight_pattern) to store data in memory cache - if I have a local state object with the same `id` as an object in a network response - apollo-client doesn't update the cache with network response even if other fields of this object are differ from cached one.

**Comment by CVarisco** [comment]
Hi @AndrewKovalenko !

Could you share how did you solve this issue? Thank you!

**Comment by saschb2b** [comment]
@AndrewKovalenko also run into the same problem. I have the same object in two different spots with different attributes but same id and _typename. How did you solve this?

**Comment by AndrewKovalenko** [comment]
@saschb2b I could not find a clean solution for this problem, so for now I ended up just prefixing all ids for locally saved objects with `local_` (if network retrieved object id is `1s3d4f` then I save it to client state as `local_1s3d4f`). This way there is no conflict in a local apollo cache.

**Comment by thicit** [comment]
@AndrewKovalenko @saschb2b


he reason for fetchPolicy to be ignored lies within Apollo Client. The "disableNetworkFetches" flag of the client gets set to true by default. (haven't yet found out exactly why it is default set to true).
So in order to fix this, a much cleaner solution is to set "`client.disableNetworkFetches = false`" in your client creation. (that you provide to the ApolloProvider)

Extract of ApolloClient that overrides the fetchPolicy:
```
// apollo-client/packages/apollo-client/src/ApolloClient.ts  - 
 public watchQuery<T = any, TVariables = OperationVariables>(
    options: WatchQueryOptions<TVariables>,
  ): ObservableQuery<T, TVariables> {
    if (this.defaultOptions.watchQuery) {
      options = {
        ...this.defaultOptions.watchQuery,
        ...options,
      } as WatchQueryOptions<TVariables>;
    }

    // XXX Overwriting options is probably not the best way to do this long term...
    if (
      this.disableNetworkFetches &&
      (options.fetchPolicy === 'network-only' ||
        options.fetchPolicy === 'cache-and-network')
    ) {
      options = { ...options, fetchPolicy: 'cache-first' };
    }

    return this.queryManager.watchQuery<T, TVariables>(options);
  }
```
