### ISSUE TITLE
Debounce tech doesn't work with useQuery

### ISSUE THREAD

**Issue by Jamikk** [apollographql/react-apollo#3088]
**Intended outcome:**
I tried to implement debounce tech with userQuery on my project and it didn't work. 

**Actual outcome:**
I would like something like this implementation, but with the use of ```useQuery```
```
const debouncedSearchTerm = useDebounce(offersQueryVariables, 200);
    useEffect(() => {
      (async () => {
        await client.query({ query: getSupportOffers, variables: offersQueryVariables });
      })();
    }, [debouncedSearchTerm]);
```

**How to reproduce the issue:**

**Version**

- apollo-boost@0.3.1
- react-apollo@2.5

**Comment by josephsiefers** [comment]
@Jamikk Just curious, what was your solution here?

**Comment by Jamikk** [comment]
> @Jamikk I'm finding myself in a similar situation - what was your solution here?

Hi!
For Example
`  const debounceSearch = useDebounce(state.searchValue, SEARCH_DEBOUNCE_TIMEOUT);`
