### ISSUE TITLE
Chain is not defined when trying to use compose()

### ISSUE THREAD

**Issue by vemundeldegard** [apollographql/react-apollo#3093]
**Intended outcome:**

I am trying to fire two Queries by using compose(). My code is as follows: 

```
export default compose(
    withApollo,
    graphql(salesData, {
        options: {
            variables: {
                "start": "2019-06-01T08:32:31.616Z",
                "end": "2019-06-30T08:32:31.616Z"
            }
        }
    }),
    graphql(advertismentData, {
        options: {
            variables: {
                "start": "2019-06-01T08:32:31.616Z",
                "end": "2019-06-30T08:32:31.616Z"
            }
        }
    }),
  )(Dashboard);
```

**Actual outcome:**

![Skjermbilde 2019-06-04 kl  15 43 20](https://user-images.githubusercontent.com/36489034/58883871-9361cd00-86df-11e9-9689-ccda35cd2692.png)

This error gets thrown right away. It works when using only one graphql(), but when using multiple and compose() it does not work. 

**How to reproduce the issue:**

See the code above to reproduce. 

**Version**

- apollo-boost@0.3.1
- react-apollo@2.5.2

**Comment by hwillson** [comment]
@vemundeldegard Any chance you could provide a small runnable reproduction that demonstrates this?

**Comment by OurMajesty** [comment]
I think you are trying use previous query results before they are ready;  
I if remember correctly, composed queries aren't executed in order.  
Just `skip` if previous result are still `loading`

**Comment by hwillson** [comment]
The response in https://github.com/apollographql/react-apollo/issues/3093#issuecomment-499824134 sounds quite likely. Thanks!
