### ISSUE TITLE
React Hooks

### ISSUE THREAD

**Issue by lekoaf** [apollographql/react-apollo#3094]
Hi,

What's the status of the `useQuery`, `useMutation` etc React Hooks?
I can't seem to find any official statements, websites, repository or anything.

All I could find was a basically empty [NPM page](https://www.npmjs.com/package/@apollo/react-hooks) for the beta, a [Twitter post](https://twitter.com/peggyrayzis/status/1128280687470100480?s=21) and a [CodeSandbox Demo](https://codesandbox.io/s/5v1ol0nkjx).

These Hooks looks very promising for myself and my team but we would like to have a bit more meat on the bone before we decide to try them out for real.

Can someone point me towards something a bit more official regarding these Hooks?

Thanks.

**Comment by lekoaf** [comment]
After a bit more digging I found this on another branch of this repository.
https://github.com/apollographql/react-apollo/tree/release-3.0.0/packages/hooks

**Comment by lekoaf** [comment]
What's the timeframe for v3.0.0?

**Comment by hwillson** [comment]
@lekoaf We're getting close to a release, but the biggest hold up right now is around documentation. We have a fairly significant overhaul of the docs to complete before finalizing the release. You can follow along in https://github.com/apollographql/react-apollo/pull/2892.

**Comment by lekoaf** [comment]
Thanks @hwillson. You're doing great work. Can't wait for the hooks to be released. :)
