### ISSUE TITLE
Still get error "WARNING: heuristic fragment matching going on!" when using fragmentMatcher for UNION

### ISSUE THREAD

**Issue by daocuong11** [apollographql/react-apollo#3099]
I used introspectionQueryResultData like https://www.apollographql.com/docs/react/advanced/fragments/#fragments-on-unions-and-interfaces but I still get the error message 

Here is my code: 
Server side schema: 

![img1](https://user-images.githubusercontent.com/29220969/59077006-06975900-8903-11e9-9230-6abc3553eb26.PNG)
![img2](https://user-images.githubusercontent.com/29220969/59077047-2b8bcc00-8903-11e9-9535-ae4491828274.PNG)

Client: 
![3](https://user-images.githubusercontent.com/29220969/59077073-4100f600-8903-11e9-9d91-59ba33109b63.PNG)
![4](https://user-images.githubusercontent.com/29220969/59077074-41998c80-8903-11e9-98b0-e07b723c2dc4.PNG)

Error Message
![5](https://user-images.githubusercontent.com/29220969/59077085-49f1c780-8903-11e9-8e0d-b1c2c30ead80.PNG)

Client Config:
![6](https://user-images.githubusercontent.com/29220969/59077107-55dd8980-8903-11e9-8b30-9011117575c0.PNG)
![7](https://user-images.githubusercontent.com/29220969/59077108-55dd8980-8903-11e9-9d9d-996e7998fab2.PNG)

**Comment by chandan-reddy-k** [comment]
I guess you are not fetching the entire schema into your application during build time. Check out this article : https://medium.com/@chandan.reddy/whats-going-on-with-the-heuristic-fragment-matcher-in-graphql-apollo-client-e721075e92be
Let me know if this helped 🙂

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
