### ISSUE TITLE
Allow MockedProvider to accept a schema plus resolver mocks.

### ISSUE THREAD

**Issue by tdeedlesATX** [apollographql/react-apollo#3108]
**Use Case**
As a developer, I build new feature using `addMockFunctionsToSchema` (adding "faked" resolvers that provide mocked data) to develop features fast when back-end api resource changes have not taken effect. 

**Problem**
While the flexibility of `MockedProvider` is great, it requires much data coordination. This can be very good at times, and is a stronger assertion when testing. 

But for many test situations, I have a set of mocked responses pre-built during development that can satisfy many use cases when writing tests.

Hence, I'm having to re-duplicate effort to write more`mocks` for tests that are very similar to my canned data in the resolver `mocks`.

**Solution**
I'd like to be able to re-use the mock resolvers used during development in my tests that use `MockedProvider`.

**Proposal**
I think it would be great to support a second type of mocking with MockedProvider. 

Option one:
passing `mocks` as today

Option two:
(instead of mocks) 
pass a `schema` and a set of `resolverMocks`
```
        schema
        resolverMocks
```
where both schema and  resolverMocks are congruent with `schema` and  `mocks` arguments, respectively, in the `addMockFunctionsToSchema` method from `graphql-tools':
```
require('graphql-tools').addMockFunctionsToSchema({
        schema,
        mocks,
        preserveResolvers: false
    });
```

Schema option need only satisfy the schema associated with the data needed to be resolved under test, similar to how the `mocks` attribute of `MockedProvider` need only provide request, response to the queries under test.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests and bugs, and to help clean up the feature request backlog, React Apollo feature requests are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request will be closed here, but anyone interested in migrating this feature request to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Allow%20MockedProvider%20to%20accept%20a%20schema%20plus%20resolver%20mocks.&body=Migrated%20from:%20apollographql/react-apollo%233108) to start the feature request migration process. This manual migration process is intended to help identify which of the outstanding feature requests are still considered to be of value to the community. Thanks!
