### ISSUE TITLE
Why apollo hooks need the react-dom dependencie?

### ISSUE THREAD

**Issue by isacjunior** [apollographql/react-apollo#3115]
I started using `@apollo/react-hooks` for testing hooks with apollo in `react-native` and when starting application, I have a warning about `react-dom` dependency. The question is, I need `react-dom` dependence on `react-native`?

```
Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `react-dom/server` from `/Users/isac/Projects/React/apollo-hooks/node_modules/@apollo/react-hooks/lib/react-hooks.cjs.js`: Module `react-dom/server` does not exist in the Haste module map
```

**Version**
```json
"@apollo/react-hooks": "^0.1.0-beta.7",
"apollo-cache-inmemory": "^1.6.0",
"apollo-client": "^2.6.0",
"apollo-link-http": "^1.5.14",
"graphql": "^14.3.1",
"graphql-tag": "^2.10.1",
```

**Comment by jasonpaulos** [comment]
Thanks for the bug report @isacjunior. It looks like the `react-native` tag from https://github.com/apollographql/react-apollo/blob/fc18c4180922dd31229f892f966845cf13fd3e7a/packages/hooks/package.json#L15 is not propagating to the final package.json generated by lerna for the `react-hooks` package. Adding this section back into the generated package.json for `@apollo/react-hooks` fixes this error. I'll look into why this is not happening properly.
