### ISSUE TITLE
React Native | 3.0.0-beta.1 | Could not find "client" in the context of ApolloConsumer. Wrap the root component in an <ApolloProvider>.

### ISSUE THREAD

**Issue by IsaacHardy** [apollographql/react-apollo#3127]
While using React Native, upgrading to react-apollo `3.0.0-beta.1` throws an initial error:

![Simulator Screen Shot - iPhone X - 2019-06-17 at 15 28 19](https://user-images.githubusercontent.com/10745699/59632068-505c1c80-9117-11e9-9d55-d494bd3d4980.png)

Custom Client Provider:

```js
import React, { PureComponent } from 'react';
import PropTypes from 'prop-types';
import { ApolloProvider } from 'react-apollo';
import { ApolloClient } from 'apollo-client';
import { ApolloLink } from 'apollo-link';
import SplashScreen from 'react-native-splash-screen';

import { authLink } from '@apollosproject/ui-auth';
import { resolvers, schema, defaults } from '../store';
import { bugsnagLink } from '../bugsnag';
import httpLink from './httpLink';
import cache, { ensureCacheHydration, MARK_CACHE_LOADED } from './cache';

const link = ApolloLink.from([bugsnagLink, authLink, httpLink]);

export const client = new ApolloClient({
  link,
  cache,
  queryDeduplication: false,
  shouldBatch: true,
  resolvers,
  typeDefs: schema,
});

cache.writeData({ data: defaults });
// Ensure that media player still works after logout.
client.onResetStore(() => cache.writeData({ data: defaults }));

class ClientProvider extends PureComponent {
  static propTypes = {
    client: PropTypes.shape({
      cache: PropTypes.shape({}),
    }),
  };

  static defaultProps = {
    client,
  };

  async componentDidMount() {
    try {
      await ensureCacheHydration;
    } catch (e) {
      throw e;
    } finally {
      if (SplashScreen && SplashScreen.hide) SplashScreen.hide();
      client.mutate({ mutation: MARK_CACHE_LOADED });
    }
  }

  render() {
    return <ApolloProvider {...this.props} client={client} />;
  }
}

export default ClientProvider;

```
**Version**

##### System:
    OS: macOS 10.14
#####  Binaries:
    Node: 8.11.2 - ~/.nvm/versions/node/v8.11.2/bin/node
    Yarn: 1.15.2 - ~/.nvm/versions/node/v8.11.2/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v8.11.2/bin/npm
#####  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 66.0.3
    Safari: 12.0
#####  npmPackages:
    apollo: ^1.9.2 => 1.9.2
    apollo-client: 2.6.1
    apollo-link: 1.2.8

**Comment by jasonpaulos** [comment]
Hi @IsaacHardy, thanks for the bug report! Could you please provide a runnable reproduction of this in a github repo?

**Comment by IsaacHardy** [comment]
@jasonpaulos Both choices in the PR template are using non React Native apps to create the runnable reproduction. What type of mechanism should I use for a React Native application to best suit the Apollo team needs?

**Comment by jasonpaulos** [comment]
@IsaacHardy You should be able to create a new React Native app with `react-native init`, then copy over the functionality that you need from https://github.com/apollographql/react-apollo-error-template. Alternatively, it seems like your issue is unrelated to specific GraphQL schema, so you may be able to just use a public GraphQL API like https://api.graph.cool/simple/v1/swapi instead of using the code from the error template repo to simulate a network request. Let me know if you have any trouble!

**Comment by IsaacHardy** [comment]
@jasonpaulos I've determined that this is not a core `react-apollo` issue. It seems that within our monorepo the `peerDependencies` were not working as intended, allowing us to have multiple ApolloProviders from different contexts. 

Closing this issue.
