### ISSUE TITLE
Hooks error when using components with React Native

### ISSUE THREAD

**Issue by hwillson** [apollographql/react-apollo#3144]
Migrated from: https://github.com/apollographql/react-apollo/pull/2892#issuecomment-503579070

cc @IsaacHardy

----

I receive an error (Hooks can only be called inside the body of a function component.) after upgrading to 3.0.0-beta.1. The odd thing here, is that I am not using any hooks but just a simple <Query> component inside a class.

Is this error a symptom of the deprecation of support for class base components within react-apollo?

Error:
![Simulator Screen Shot - iPhone X - 2019-06-19 at 10 09 06](https://user-images.githubusercontent.com/10745699/59772732-59b1ca00-927a-11e9-9e6e-7c2c51f89c45.png)

Code from top of stack:
```js

1. import React, { Component } from 'react';
2. import { Query } from 'react-apollo';
3. 
4. import FullscreenPlayer from './FullscreenPlayer';
5. 
6. import { GET_MEDIA_PLAYER_VISIBILITY } from './queries';
7. 
8. /**
9.  * Selectively renders FullscreenPlayer component is MediaPlayer is visible
10.  */
11. class MediaPlayer extends Component {
12.   shouldComponentUpdate() {
13.     return false; // 🚀
14.   }
15. 
16.   renderPlayer = ({ data = {} }) => {
17.     if (!data.mediaPlayer || !data.mediaPlayer.isVisible) return null;
18.     return <FullscreenPlayer />;
19.   };
20. 
21.   render() {
22.     return (
23.       <Query query={GET_MEDIA_PLAYER_VISIBILITY}>{this.renderPlayer}</Query>
24.     );
25.   }
26. }
27. 
28. export default MediaPlayer;

```

**Comment by jasonpaulos** [comment]
I also ran into this issue, and it appears to happen when something is wrong with React. It could be that react and react-dom are different versions, or that there are two versions of react lurking somewhere in your project. For me it happened when installing apollo-client as a relative file dependency, but the steps here still helped (see the npm link section): https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react

For those curious, the Query component uses hooks under-the-hood in RA 3, which is this error happens.

**Comment by Titozzz** [comment]
Prob cause react-native has a different react dependency version. You either need to wait for react-native to align to the version apollo is using, or force apollo to use the same version (hoping there won't be bugs). You can do that in your metro.config.js

**Comment by hwillson** [comment]
Thanks @jasonpaulos and @Titozzz - that definitely sounds likely. I'm not sure what else we can do to mitigate this on React Apollo's side; we have the `react` and `react-dom` peer deps set to start at 16.8.0, which is the lowest we can go. I believe React Native is 16.8.x as well, so as long as the same versions are used, this should all work. I'll close this for now, but I'm happy to re-open if anyone thinks we should do something differently to handle this more appropriately. Thanks!

**Comment by klaaz0r** [comment]
Even while using the right version of React and checking that only one version is used. I'm working in yarn workspaces and the web app has no problem (same react version) the react-native app has this problem (also when detaching it completely from workspaces/lerna).
