### ISSUE TITLE
TypeScript weirdness, why is mutate in a HOC possibly undefined?

### ISSUE THREAD

**Issue by KyleMcNutt** [apollographql/react-apollo#3150]
Currently, when you use the `withMutation` HOC, the `mutate` function passed to you via `props` is typed to be possibly undefined. Is that ever actually the case though? Wouldn't `mutate` always be defined? If so, this should be updated so that `mutate` is always defined in the types, so that folks with `strictNullChecks` don't have to do an unnecessary null check.

I think that it is currently set to be possibly undefined because of this line:

https://github.com/apollographql/react-apollo/blob/592d88a3b050377eade9c4299c18d063972872cc/packages/hoc/src/types.ts#L71

Where the `MutateProps` is wrapped in a `Partial`, meaning that some of these props could be defined, or undefined. 

If this is done this way because the `OptionProps` deals with both the Query and Mutation scenarios, could those be separated, in order to remove the `Partial`'s?

You can reproduce this by turning on `strictNullChecks` and then using `withMutation`, TypeScript won't let you use `mutate` without wrapping it in an `if` check first similar to:

```
if (mutate) {
  mutate({...});
}
```

**Version**

System:
    OS: Windows 10
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    apollo-boost: ^0.3.1 => 0.3.1
    apollo-cache-persist: ^0.1.1 => 0.1.1
    apollo-link-schema: ^1.2.2 => 1.2.2
    apollo-link-state: ^0.4.2 => 0.4.2
    react-apollo: ^2.5.5 => 2.5.5

**Comment by KyleMcNutt** [comment]
Note: Trying out `useMutation`, it doesn't seem to have the above problem, the `MutationTuple` type always returns the associated mutation function.

So this does seem to be a specific bug with HOC's?

**Comment by hwillson** [comment]
Fixed in React Apollo 3.1.0 - thanks!
