### ISSUE TITLE
ApolloClient defaultOptions.query.fetchPolicy not respected by query hooks and components

### ISSUE THREAD

**Issue by cazzer** [apollographql/react-apollo#3163]
**Intended outcome:**
The default `fetchPolicy` should be respected by any component using it as context.
```ts
const client = new ApolloClient({
  link: ApolloLink.from([
    new HttpLink({
      uri: process.env.GRAPHQL_ENDPOINT
    }),
  ]),
  cache,
  defaultOptions: {
    query: {
      fetchPolicy: 'network-only'
    }
  }
})
```
**Actual outcome:**
Unless `fetchPolicy` is explicitly defined in each query's options, it is `undefined` causing no network request to occur by default, if there is something in the cache already. So basically the first load works but subsequent loads won't hit the network.

I probably just did something wrong in how I configured my client, above, but I also couldn't find any place where `defaultOptions.query.fetchPolicy` got accessed when stepping through execution. In fact, `defaultOptions` only showed up [three times](https://github.com/apollographql/react-apollo/search?q=defaultoptions&type=Code) when searching the repository.

**If you point me to where the default options are handled I can figure out how I misconfigured my client.**

**How to reproduce the issue:**
I put together a StackBlitz which reproduces this issue: https://stackblitz.com/edit/apollo-client-cache-issue?file=index.js

1. Define a global `query.fetchPolicy` as `network-only` on the ApolloClient, but don't explicitly set the `fetchPolicy` on a `<Query>` or `useQuery`.
2. Run the query once to get some stuff in the cache
2. On the second run, note that `fetchPolicy` is `undefined` [here](https://github.com/apollographql/react-apollo/blob/master/packages/hooks/src/data/QueryData.ts#L286), and since there is some data in the cache already the condition around `query.refetch()` is falsy causing it to not run.
1. Confirm that `this.context.client.defaultOptions.query.fetchPolicy` is correctly set to `network-only`

**Version**
This was also an issue in `react-apollo@2.*`.
```
  System:
    OS: macOS 10.14.3
  Binaries:
    Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
    Yarn: 1.6.0 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 60.5.0
    Safari: 12.0.3
  npmPackages:
    apollo-cache-inmemory: ^1.6.2 => 1.6.2 
    apollo-cache-persist: ^0.1.1 => 0.1.1 
    apollo-client: ^2.6.2 => 2.6.2 
    apollo-link: ^1.2.12 => 1.2.12 
    apollo-link-context: ^1.0.18 => 1.0.18 
    apollo-link-error: ^1.1.11 => 1.1.11 
    apollo-link-http: ^1.5.15 => 1.5.15 
    apollo-link-retry: ^2.2.4 => 2.2.5 
    react-apollo: ^3.0.0-beta.1 => 3.0.0-beta.1 
    react-apollo-hooks: ^0.4.5 => 0.4.5 
```

**Comment by hwillson** [comment]
Interesting @cazzer - I'll take a look. And thanks for the great reproduction!

**Comment by hwillson** [comment]
@cazzer Sorry I should have noticed this right away. React Apollo uses Apollo Client's `watchQuery` internally, not `query`. That means the `defaultOptions` have to be set for `watchQuery` to be enabled. So changing your `defaultOptions` as follows will help:

```js
const client = new ApolloClient({
  link: new HttpLink({
    uri: 'https://countries.trevorblades.com/'
  }),
  cache: new InMemoryCache(),
  defaultOptions: {
    watchQuery: {
      // this doesn't seem to be having any effect
      fetchPolicy: 'network-only'
    }
  }
});
```

We definitely realize this is confusing, and in Apollo Client 3 (or maybe sooner) we will get getting rid of the distinction between `query` and `watchQuery` completely (every query can be either a one off or expected to return future results). In the meantime though, I'll make sure this is mentioned more prominently in the docs. We do mention it in the [`ApolloClient` API section](https://www.apollographql.com/docs/react/api/apollo-client/#apolloclient), but we should probably mention it in a few other places as well:

> **Note:** The React Apollo `<Query />` component uses Apollo Client's `watchQuery` functionality, so if you would like to set `defaultOptions` when using `<Query />`, be sure to set them under the `defaultOptions.watchQuery` property.

Thanks!

**Comment by cazzer** [comment]
Wow, no idea how I missed that. Thanks for the quick solution @hwillson!
