### ISSUE TITLE
Local query resolver doesn't re-render after mutation adds data

### ISSUE THREAD

**Issue by patrikniebur** [apollographql/react-apollo#3170]
**Intended outcome:**
When I use local resolver to read data from cache and then update it using mutation component is re-rendered with new data. When I add new item into array, component should re-render with this new item.

**Actual outcome:**
Component renders with updated data, but doesn't re-render with new item when added. This only happens when I use local resolver. When I read directly from cache this is updated.

**How to reproduce the issue:**
```js
const client = new ApolloClient({
  clientState: {
    resolvers: {
      Query: {
        getPeople: (_, args, ctx) => {
            const data = ctx.client.readQuery({ query: PEOPLE });
            return data.people;
        }
      },
     Mutation: {
         doUpdatePeople: async (_, args, ctx) => {
           // Omitted... 
           // recreates people array from scatch and writes to cache using:
           ctx.client.writeData({ data: newData });
         }
     }
    },
    defaults: {
       people: [{__typename:'Person', id: 0, name: 'Dave'}],
    },
  }
});
```

Component query:
```gql
  query {
    getPeople @client {
      id
      name
      hours
    }
  }
```

Querying data like this updates component when `name` property in people array changes but no update when new item is added. If I change query to avoid local resolver and use cache directly like this:  

```gql
  query {
    people @client {
      id
      name
      hours
    }
  }
```

All works as expected and component is re-rendered when new item is added.

Reproduction:
https://codesandbox.io/s/simple-apollo-example-9eo49?fontsize=14&module=%2Fsrc%2FComponents%2FPeople.js
You should be able to edit names in textarea and add new person by adding a new row.
_changing `queryProperty` to `"people"` avoids local resolver and behaves correctly_

**Version**
```
    "apollo-boost": "0.4.3",
    "graphql": "14.3.1",
    "react": "16.8.6",
    "react-apollo": "2.5.8",
```

**Comment by patrikniebur** [comment]
I did solve it. Problem was in a format I wrote data back:
```
           ctx.client.writeData({
             data: {
                people: newPeople
             }
           });
```
I wrote updated data in `people` property but in my getPeople query they were cached under `getPeople` property. When I changed that it fixed the problem, but then I guess I need to update `people` property too since `getPeople` will be updated from that on refetch?

I'm still confused if this was an issue why did the updating existing entries in array work? Perhaps reference issue?

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
