### ISSUE TITLE
v3.0.0-beta: "Hooked" component is re-rendered too often

### ISSUE THREAD

**Issue by vjsingh** [apollographql/react-apollo#3172]
**Intended outcome:**

When using apollo-hooks like so:
```
const [ someOtherData ] = useSomeHook('myHook');
const {data, loading, error,}: QueryResult<MyQuery> = useQuery(myQuery, {});
const listData = someFunc(data);
const childView = React.useMemo(() => <ChildView listData={listData}/>, [data]);

```

It appears that when someOtherData is updated, which triggers a re-render of the component, "data" changes as well, which cause a re-rendering of ChildView. I am trying to use 'useMemo' to avoid re-rendering the child component unless the data has actually changed. Is this expected, and if so is there a way around it?

**Actual outcome:**

"Data" changes on every load of the component, even if the data hasn't changed.

**How to reproduce the issue:**

Unsure how to use the code sandbox with the 3.0 hooks beta.

**Version**
```
  System:
    OS: macOS 10.14.4
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 4.0b11
    Safari: 12.1
  npmPackages:
    apollo-boost: ^0.1.19 => 0.1.28
    apollo-link-context: ^1.0.8 => 1.0.17
    react-apollo: ^2.5.8 => 2.5.8
  npmGlobalPackages:
    apollo-codegen: 0.19.1
```

**Comment by hwillson** [comment]
https://github.com/apollographql/react-apollo/pull/3188 has been merged, and should address this. I'll have a new beta published shortly. Thanks!

**Comment by vjsingh** [comment]
@hwillson Wooo well done! Thank you =) Glad to know I interpreted this right, and happy you guys managed to fix it so quickly without a repro.
