### ISSUE TITLE
react-hoc: hoist-non-react-statics is missing from dependencies

### ISSUE THREAD

**Issue by wmertens** [apollographql/react-apollo#3173]
Trying out react-apollo@3 beta, and I use pnpm, and I had to add hoist-non-react-statics to my dependencies for react-hoc to see it.

**Comment by hwillson** [comment]
Thanks for reporting this @wmertens. This should be fixed via https://github.com/apollographql/react-apollo/pull/3198 (the dep was in the wrong package), and I'll have a new beta published shortly.
