### ISSUE TITLE
How to use multiple queries with dependent data?

### ISSUE THREAD

**Issue by XenTerSeO** [apollographql/react-apollo#3180]
An example that seems correct:

```javascript
export default () => {
  const {loading: loading_user, data: data_user} = useQuery(USER)

  if (loading_user) return null

  const {loading: loading_sort, data: data_sort} = useQuery(SORT, {
    variables: {
      id: data_user.user.id
    }
  })

  if (loading_sort) return null

  const {loading: loading_posts, data: data_posts} = useQuery(POSTS, {
    variables: {
      sort: data_sort.sort
    }
  })

  if (loading_posts) return null

  return (
    <Posters posts={data_posts.posts}/>
  )
}
```

But it does not work, because:
> React Hook "useQuery" is called conditionally. React Hooks must be called in the exact same order in every component render. (react-hooks/rules-of-hooks)

![chrome_2019-06-26_00-24-30](https://user-images.githubusercontent.com/14257845/60134978-65851b00-97a9-11e9-9b1f-8b99d1bb571b.png)

**Comment by jgfidelis** [comment]
There are two issues here:
1 - You always have to return after the same amount of hooks
```
export default () => {
  const {loading: loading_user, data: data_user} = useQuery(USER)

  const {loading: loading_sort, data: data_sort} = useQuery(SORT, {
    variables: {
      id: data_user.user.id
    }
  })

  const {loading: loading_posts, data: data_posts} = useQuery(POSTS, {
    variables: {
      sort: data_sort.sort
    }
  })

  if (loading_posts) return null

  return (
    <Posters posts={data_posts.posts}/>
  )
}

```
Something like that this could work.
You can create hooks with useEffect and useQuery to wait for the change in other queries and avoid returning null.
You could wrap each query/step in a component of its own.

The second issue I think is in your Graphql. You should not do that, you should be able to create a query that given your user, it would respond with your posts, and not do two queries to then do a third one

**Comment by capaj** [comment]
> The second issue I think is in your Graphql. You should not do that, you should be able to create a query that given your user, it would respond with your posts, and not do two queries to then do a third one

this is totally correct. Your graphQL endpoint should allow to query for anything frontend might need without resorting to waterfall requests.

**Comment by ekfn** [comment]
I think as workarond you can use skip option
```js
export default () => {
  const { data: data_user } = useQuery(USER)

  const { data: data_sort } = useQuery(SORT, {
    skip: !data_user,
    variables: {
      id: data_user && data_user.user.id
    }
  })

  const { data: data_posts } = useQuery(POSTS, {
    skip:  !data_sort,
    variables: {
      sort: data_sort && data_sort.sort
    }
  })

  if (!data_posts) return null

  return (
    <Posters posts={data_posts.posts}/>
  )
}
```

**Comment by hwillson** [comment]
Closing as the answers in previous comments are great. Thanks!

**Comment by ysz** [comment]
> The second issue I think is in your Graphql.

> You should not do that, you should be able to create a query that given your user, it would respond with your posts

@jgfidelis & @capaj what if dependency is in local state? 

e.g. I write `foo` to the cache which comes from the query string or user input and then I want to query server using `foo`

I would have to cascade queries , where first one will be with `@client` and second one will use `{variables: {foo}}`

**Comment by ysz** [comment]
i.e. something like this is invalid 

```
  query GetSomeIdAndFoo {
    someId @client
    fooBySomeId(someId: someId)
  }
```

**Comment by NiestrojMateusz** [comment]
> > The second issue I think is in your Graphql.
> 
> > You should not do that, you should be able to create a query that given your user, it would respond with your posts
> 
> @jgfidelis & @capaj what if dependency is in local state?
> 
> e.g. I write `foo` to the cache which comes from the query string or user input and then I want to query server using `foo`
> 
> I would have to cascade queries , where first one will be with `@client` and second one will use `{variables: {foo}}`


@ysz did you find the solution? I have a similar issue

**Comment by sobrinho** [comment]
I am in the same issue here (in Vue but same concept).

We have a component that queries for the current user and another component (in a different level of the components tree) that needs to wait for the user token to be fetched (to query against another graphql endpoint).

In fact, this component of ours stores a token in the session storage and I would need to "wait" for it before performing the request to this other endpoint.
