### ISSUE TITLE
FetchPolicy missing cache-and-network in type?

### ISSUE THREAD

**Issue by zackify** [apollographql/react-apollo#3181]
Version: apollo-client 2.6.3

![image](https://user-images.githubusercontent.com/449136/60145701-aa925880-977b-11e9-9678-5fa77f374c55.png)

When attempting to use `cache-and-network` it looks like it is not included in the type definition

**Comment by scf4** [comment]
If this is for `defaultOptions` you should use `watchQuery: { fetchPolicy }` instead of `query: {}`
