### ISSUE TITLE
Alternate API for useQuery / useMutation

### ISSUE THREAD

**Issue by cowboy** [apollographql/react-apollo#3187]
A particular problem I'm trying to avoid is in a complex component with multiple `useQuery` and `useMutation` calls, I might need to use multiple data+error+loading simultaneously, and I want to avoid this:

```js
const { data: fooData, loading: fooLoading, error: fooError } = useQuery(FOO_QUERY)
const { data: barData, loading: barLoading, error: barError } = useQuery(BAR_QUERY)
const [mutateBaz, { data: bazData, loading: bazLoading, error: bazError }] = useMutation(BAZ_QUERY)

if (fooLoading || barLoading || bazLoading) {
  return <Loading />
}
```

Or this:

```js
const fooQueryResult = useQuery(FOO_QUERY)
const barQueryResult = useQuery(BAR_QUERY)
const [mutateBaz, bazQueryResult] = useMutation(BAZ_QUERY)

if (fooQueryResult.loading || barQueryResult.loading || bazQueryResult.loading) {
  return <Loading />
}
```

I was thinking of something that behaves roughly like this (since it's not built-in), to make `useQuery` and `useMutation` behave more like `useState`:

```js
import {
  useQuery as useQueryOrig,
  useMutation as useMutationOrig
} from '@apollo/react-hooks'

const createExtraFancyTuple = obj => {
  const { data, error, loading } = obj
  return Object.entries(obj).reduce((acc, [k, v]) => {
    acc[k] = v
    return acc
  }, [data, error, loading])
}

export const useQuery = (...args) => createExtraFancyTuple(useQueryOrig(...args))
export const useMutation = (...args) => {
  const [mutate, result] = useMutationOrig(...args)
  return [mutate, createExtraFancyTuple(result)]
}
```

Then I could do something like:

```js
const [fooData, fooError, fooLoading] = useQuery(FOO_QUERY)
const [barData, barError, barLoading] = useQuery(BAR_QUERY)
const [mutateBaz, [bazData, bazError, bazLoading]] = useMutation(BAZ_QUERY)

if (fooLoading || barLoading || bazLoading) {
  return <Loading />
}
```

(This would retain compatibility with either of the 2 original examples, if I preferred to use them)

I can't think of a good way to get `useMutation` to return `[mutate, data, error, loading]` (without the nested array) and still retain compatibility with the current return value of `[mutate, resultObj]`.

Thoughts? If it's too "clever," I understand, I just wanted to make sure you had a chance to consider it!

**Comment by jinshin1013** [comment]
But you also need to consider other fields from `useQuery` like `refetch`, `networkStatus` and etc. Then all of a sudden the array becomes unmanageable and people will need to start remembering the order of variables. Unless the API looks like this:

```tsx
const [loading, error, data, { refetch, networkStatus }] = useQuery(QUERY)
```

I think what you have here can be useful and seems easy to implement in your own project so don't think it's needed to come from the library itself. It's coming from a guy who always uses `networkStatus` instead of `loading` so don't take my words too seriously though :)

**Comment by cowboy** [comment]
In my example, you could still just do this:

```js
const { loading, error, data, refetch, networkStatus } = useQuery(QUERY)
```

I was just trying to create an API that facilitates what I imagine to be the most common use cases, which in my (undoubtedly limited) experience are getting data, data + error, or data + error + loading.

**Comment by hwillson** [comment]
Thanks for this suggestion @cowboy. Would you mind opening a feature request for this over in the https://github.com/apollographql/apollo-feature-requests repo?
