### ISSUE TITLE
Unable to use Subscription with `graphql` wrapper? (setOptions error)

### ISSUE THREAD

**Issue by dotansimha** [apollographql/react-apollo#319]
## Steps to Reproduce

Using: `graphql-subscriptions` and `subscriptions-transport-ws`, created React Component and try to extend it with graphql object, with Subscription:
```
const withSubscription = graphql(subscription, {
  name: 'mySubscription',
  options: ({user}) => ({
    variables: {
      name: user.name
    }
  })
});

export default MyComponentWithData = withSubscription(MyComponent);
```

When the subscription executed, I am getting the following errors:
```
TypeError: this.queryObservable.setOptions is not a function
    at GraphQL.meteorInstall.node_modules.react-apollo.graphql.js.GraphQL.subscribeToQuery (graphql.js:251)
    at GraphQL.meteorInstall.node_modules.react-apollo.graphql.js.GraphQL.componentWillReceiveProps (graphql.js:171)
    at ReactCompositeComponent.js:608
    at measureLifeCyclePerf (ReactCompositeComponent.js:74)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:607)
    at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js:544)
    at Object.receiveComponent (ReactReconciler.js:126)
    at Object.updateChildren (ReactChildReconciler.js:110)
    at ReactDOMComponent._reconcilerUpdateChildren (ReactMultiChild.js:210)
    at ReactDOMComponent._updateChildren (ReactMultiChild.js:314)
```

This is the line with the issue: https://github.com/apollostack/react-apollo/blob/71bad833733904a5fda427830479d159ddeca016/src/graphql.tsx#L388

The object that created as `this.queryObservable` does not have the `setOptions` method (it's of type `Observable`), it's only have the following properties: `subscriberFunction`, `subscribe`.

Also, if this will work, the same issue will occur with the next lines (`currentResult()` also does not exists on type `Observable`).

The actual error thrown sometimes when the subscription gets a new message, and sometimes when the Component initialized.

### Buggy Behavior

Exception thrown, the rest of the code does not run, and it's `loading` forever the subscription.

### Expected Behavior

Maybe verify if `setOptions` actually exists before trying to execute it? 

### Version
- apollo-client@0.5.0 (Also tried latest 0.5.1)
- react-apollo@0.5.16
- graphql-subscriptions@0.2.1

**Comment by tmeasday** [comment]
Ahh! @jbaxleyiii this is the issue I was talking about! I guess it only happens if you set options on the subscription.

@helfer - do we have plans to make the subscription `Observable` take a similar API to `ObservableQuery` (or even be an `ObservableQuery`)?

It would help RA a lot if you could call `setOptions` and `currentResult` on a subscription.

**Comment by tmeasday** [comment]
I'm not sure we can really work around this without tracking options etc in RA for subscriptions.

One option would be to make it work but throw an exception if you change propTypes of subscription container. That's pretty crappy but would at least allow you to use `graphql('subscription ... '`
