### ISSUE TITLE
MockedProvider with subscribeToMore cycles when calling refetch() in tests

### ISSUE THREAD

**Issue by obrejla** [apollographql/react-apollo#3190]
Hi all,

if I have a component, which uses `Query` and its `subscribeToMore` function for subscriptions and I use Query's `refetch()` method in the `subscribeToMore updateQuery` option, then the encapsulating component rerenders, remounts subscribed component, triggers subscription again...refetches...etc...just cycling. In fact it does not cycle because instead of that it runs out of supplied `mocks` to `MockedProvider` so it starts to complain that there are `No more mocked responses for query: ...`. 

Imho it's actually impossible to test such a code without possibility to stop refetching... That's why I think that it should be handled as a bug.

**Intended outcome:**

Normally I would solve it by mocking of `refetch()` function which is provided by `Query` component but I do not see a possibility of doing it. If you have a suggestion about how to do that, then it would be great.

It would be **awesome** if also other props could be supplied in `mocks` I mean I would really like to do something like:

```
const mocks = [{
    request: {
        query: ALL_COUNTRIES,
    },
    result: {
        data: {
            allCountries: [
                { id: '10', name: 'Third Country', code: 'TC' },
            ],
        },
        refetch: jest.fn(), // HERE to provide also all other props, not just "data"...
    },
}];
```

**Actual outcome:**

`No more mocked responses for query: ...`

**How to reproduce the issue:**

Just have a simple component which returns something like this:
```
function Countries() {
    return (
        <Query query={ALL_COUNTRIES}>
                {({
                    subscribeToMore,
                    refetch,
                    loading,
                    error,
                    data,
                }) => {
                    let result = null;
                    if (loading) {
                        result = <p className="countries-loading">Loading...</p>;
                    } else if (error) {
                        result = <p className="countries-error">Error!</p>;
                    } else {
                        result = (
                            <CountriesList
                                countries={data.allCountries}
                                subscribeToChanges={() => subscribeToMore({
                                    document: ON_COUNTRY_CHANGED,
                                    updateQuery: (prev) => {
                                        refetch();
                                        return prev;
                                    },
                                })}
                            />
                        );
                    }
                    return result;
                }}
            </Query>
    );
}
```
Then `CountriesList` could be something like this:
```
function CountriesList(props) {
    const { countries, subscribeToChanges } = props;
    useEffect(() => subscribeToChanges(), [subscribeToChanges]);
    return (
        <div className="countries-list">
            {countries.map(country => <CountryRow country={country} key={country.id} />)}
        </div>
    );
}
```

And if you have a test like this, it would fail:

```
it('should...', async () => {
        const mocks = [{
            request: {
                query: ALL_COUNTRIES,
            },
            result: {
                data: {
                    allCountries: [
                        { id: '10', name: 'Third Country', code: 'TC' },
                    ],
                },
            },
        }, {
            request: {
                query: ON_COUNTRY_CHANGED,
            },
            result: {
                data: {
                    countryChanged: { id: '10', name: 'Third Country', code: 'TC' },
                },
            },
        }];

        const { getByText } = render(
            <MockedProvider mocks={mocks} addTypename={false}>
                <MemoryRouter initialEntries={['/countries']}>
                    <Countries />
                </MemoryRouter>
            </MockedProvider>,
        );

        await wait(300);

        expect(getByText('Third Country')).toBeTruthy();
    });
```

**Version**

System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
  Binaries:
    Node: 10.14.0 - ~/.nvm/versions/node/v10.14.0/bin/node
    Yarn: 1.16.0 - /usr/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.14.0/bin/npm
  Browsers:
    Chrome: 74.0.3729.131
    Firefox: 67.0.4
  npmPackages:
    apollo-cache-inmemory: ^1.6.2 => 1.6.2 
    apollo-client: ^2.6.3 => 2.6.3 
    apollo-link: ^1.2.12 => 1.2.12 
    apollo-link-error: ^1.1.11 => 1.1.11 
    apollo-link-http: ^1.5.15 => 1.5.15 
    apollo-link-ws: ^1.0.18 => 1.0.18 
    apollo-utilities: ^1.3.2 => 1.3.2 
    react-apollo: ^2.5.6 => 2.5.6 

Thanks for the response.

**Comment by obrejla** [comment]
It can be workaround by this (before rendering component)
```
ObservableQuery.prototype.refetch = jest.fn();
```
But that's imho ugly hack...isn't it...

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!

**Comment by garrettmaring** [comment]
I am still experiencing this with React Apollo ( `"@apollo/react-hooks": "^3.1.3"`)

**Comment by obrejla** [comment]
Yep, still same for me.

**Comment by digitalhank** [comment]
same here!
