### ISSUE TITLE
5.0 Release - Mixing hooks and non-hooks

### ISSUE THREAD

**Issue by vjsingh** [apollographql/react-apollo#3193]
Per this discussion - https://spectrum.chat/apollo/react-apollo/error-using-hooks-beta-could-not-find-client~777fcc0e-d590-44f1-99e1-d709a7df5c35

In order to enable hooks to work, I have to import `ApolloProvider` from `@apollo/react-hooks`.
In order to enable HOCs to work, I have to import `ApolloProvider` from `react-apollo`.
This makes it unclear how to mix hooks and HOCs in the same application.

It's possible that this is something related to the beta, but just wanted to mention it so it's tracked before the release.

Thank you @hwillson for your hard work on Apollo.
```
  System:
    OS: macOS 10.14.4
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 4.0b11
    Safari: 12.1
  npmPackages:
    apollo-boost: ^0.1.19 => 0.1.28
    apollo-link-context: ^1.0.8 => 1.0.17
    react-apollo: ^2.5.8 => 2.5.8
  npmGlobalPackages:
    apollo-codegen: 0.19.1
```

**Comment by hwillson** [comment]
@vjsingh You shouldn't have to do this. `@apollo/react-hoc`, `@apollo/react-hooks` and the `react-apollo` beta all use `@apollo/react-common`, which houses the `ApolloProvider`. As long as you're using the new RA 3 `beta` packages, you should always be referring to the same `ApolloProvider` code. Can you provide a small runnable reproduction that shows the issue you're encountering? 

As a side note, the environment info you've posted shows that you're using `react-apollo` 2.5.8, so not the `beta`. To share the same `ApolloProvider`, you'll want to make sure you're using either `@apollo/react-hooks` and `@apollo/react-hoc` OR `react-apollo@beta`.

**Comment by hwillson** [comment]
@vjsingh I'm reasonably sure this isn't an issue with the React Apollo 3 beta. I've added a test to verify this here: https://github.com/apollographql/react-apollo/pull/3207

I'll close this off, but definitely let me know if you're still encountering this issue (and if you can provide a small runnable reproduction that demonstrates this). Thanks!

**Comment by vjsingh** [comment]
@hwillson Late to the party, but I can confirm it is because I was using ```react-apollo``` 2.5.8, and not the ```beta```.

Thanks for your hard work! Looking forward to the 3.0 release
