### ISSUE TITLE
3.0 Beta 3: "cache-and-network" <Query> rendering changed 

### ISSUE THREAD

**Issue by fenok** [apollographql/react-apollo#3206]
**Intended outcome:**
After switching to 3.0 beta I expected no changes in how components with queries (`fetch-policy: "cache-and-network"`) are rendered. They should render with loading `false -> true -> false` (if there is cached value).

**Actual outcome:**
Now they are rendered with `loading: true` first. That causes server-rendered page to contain preloaders. This happens regardless of how query is used (React Hook or `<Query/>` component).

**How to reproduce the issue:**
Old behaviour: https://codesandbox.io/s/uxq90
Current behaviour: https://codesandbox.io/s/p0j7n
(console)

**Version**
See codesandbox. `react-apollo` is the only updated dependency.

**Comment by fenok** [comment]
Actually, I forgot about `ssrMode: true` option on apollo client, so the issue is that server-side render result doesn't contain preloaders, but client-side does, which is a mismatch.

**Comment by hwillson** [comment]
Thanks for reporting this @fenok (and the great reproductions). This should be fixed by https://github.com/apollographql/react-apollo/pull/3213. We'll have these changes published in the morning.
