### ISSUE TITLE
The git tag for v2.5.8 appears to be incorrect

### ISSUE THREAD

**Issue by GreenGremlin** [apollographql/react-apollo#3209]
The git tag for v2.5.8 [appears to be pointing to 3.0.0-beta.2](https://github.com/apollographql/react-apollo/blob/v2.5.8/packages/all/package.json). When browsing the repo under [v2.5.8](https://github.com/apollographql/react-apollo/tree/v2.5.8/packages), v3 features like hooks [appear to be available](https://github.com/apollographql/react-apollo/tree/v2.5.8/packages/hooks).

**Comment by hwillson** [comment]
This should now be fixed. Thanks for pointing this out @GreenGremlin!

**Comment by GreenGremlin** [comment]
The links above still [show hooks](https://github.com/apollographql/react-apollo/tree/v2.5.8/packages) and [the wrong version](https://github.com/apollographql/react-apollo/blob/v2.5.8/packages/all/package.json) for v2.5.8.

**Comment by GreenGremlin** [comment]
@hwillson can you reopen this issue, please?
