### ISSUE TITLE
Resetting query store errors means the error is lost when the parent component triggers a re-render

### ISSUE THREAD

**Issue by novemberborn** [apollographql/react-apollo#3211]
**Intended outcome:**

I have a `<Query>` that errored. The error is exposed to the `children` function and I can communicate it to the user. Then, the parent component triggers a re-render. The `<Query>` keeps rendering the same error.

**Actual outcome:**

The `error` disappears, though the network status remains `8`. Since we're not loading and there is no error, my code assumes there is data. There isn't and my App crashes.

**How to reproduce the issue:**

I've made this reproduction: https://codesandbox.io/embed/apollo-client-error-template-jb8e3

Note that initially the error message is shown, but after two seconds there is a state change in the `<App>` component and the `<Query>` is re-rendered. The error disappears.

I believe this is due to https://github.com/apollographql/react-apollo/pull/3107 which, as a side-effect, causes the error to be cleared some time after it's rendered.

**Version**

  npmPackages:
    apollo-cache-inmemory: ^1.6.2 => 1.6.2
    apollo-client: ^2.6.3 => 2.6.3
    apollo-link: ^1.2.12 => 1.2.12
    apollo-link-context: ^1.0.18 => 1.0.18
    apollo-link-error: ^1.1.11 => 1.1.11
    apollo-link-http: ^1.5.15 => 1.5.15
    react-apollo: ^2.5.8 => 2.5.8

I'm running this inside React Native.

**Comment by jasonpaulos** [comment]
Hi @novemberborn, this was solved by #3188 which will be included in the upcoming v3 release. You can preview it now by using `@apollo/react-components`. I've updated your example to show this: https://codesandbox.io/s/react-apollo-issue-3211-y4nr6

Please let me know if there's still an issue and I'll gladly reopen.

Note: when creating this example, I discovered a different bug: when the local link reports an error immediately (or after waiting for less than ~10ms) the component gets stuck with `loading: true` forever. I've created a new issue for this here: #3299
