### ISSUE TITLE
Add networkStatus prop to connected components

### ISSUE THREAD

**Issue by cannoneyed** [apollographql/react-apollo#322]
## Steps to Reproduce

When fetching more data, using a pattern identical to that proposed in the docs, the `loading` prop that is passed down to the wrapped component is `false` after `fetchMore` is invoked. 

```javascript
const Query = gql`
query paginatedQuery ($offset: Int) {
    paginatedItems (offset: $offset) {
        ... item
    }
}
`
@graphql(Query, {
    props:  ({ data }) => {
        const { fetchMore } = data
        const queryResult = data.paginatedItems

        data.loadNextPage = () => fetchMore({
            variables: {
                offset: queryResult.length
            },
            updateQuery: (prev, { fetchMoreResult }) => {
                if (!fetchMoreResult.data) {
                    return prev
                }

                return Object.assign({}, prev, {
                    [queryName]: [
                        ...prev[queryName],
                        ...fetchMoreResult.data.paginatedItems
                    ]
                })
            }
        })

        return { data }
    }
}
class View extends Component {
    render() {
        const { data: { paginatedItems, loading, loadNextPage } } = this.props
        // Loading is false after loadNextPage is invoked
    }
}
```

### Buggy Behavior

It seems the `loading` prop is only ever tied to the initial load of data. For simple components that don't need to update or paginate, this is fine. However, the workaround for this (managing refetch / loadMore status with local component state) is not ideal.  

### Expected Behavior

The following PR https://github.com/apollostack/apollo-client/issues/707 in apollo client exposes a `networkStatus` object for handling the status of non-initial-load network requests, such as refetch, fetchMore, and subscriptions.

It would be very nice to have the `networkStatus` object exposed as a prop to wrapped components (perhaps if specified as an option), so that paginated / more complex query operations loading/error state can be managed by the react-apollo wrapper rather than using local ad-hoc local component state.

### Version
- apollo-client@0.5.0
- react-apollo@0.5.16

**Comment by helfer** [comment]
@cannoneyed FYI, the `fetchingMore` network status isn't implemented in apollo-client yet. All others should be.

**Comment by wizardzloy** [comment]
I would like to implement this functionality since my app depends on it. @jbaxleyiii  @cannoneyed @helfer Is anybody working on it now?

**Comment by cannoneyed** [comment]
@wizardzloy I'm starting to look into this now.

**Comment by cannoneyed** [comment]
@helfer @wizardzloy So what I've found so far is that there seems to be some work needed in `apollo-client`... it looks like when `ObservableQuery.fetchMore` is called, a new query is created but no corresponding listener is tied to it. I'm going to dig in a little bit to check out what the implications of attaching the observer to the newly created `fetchMore` query are

**Comment by imthehell** [comment]
+1this feature will be very useful

**Comment by helfer** [comment]
@cannoneyed I think we can implement this kind of tracking internally in Apollo Client and expose it just through a `fetchingMore` network status. Would that be enough information for your use-case?

**Comment by czert** [comment]
@helfer It would be for mine :)

**Comment by czert** [comment]
We've had the `data.networkStatus` prop for a while, and until 1.0.0 it worked beautifully. While "fetching more", its value was 3. In 1.0.0, though, its value doesn't change back from 7.

Is this a known effect of some other change that I missed, or should I open an issue for this?

**Comment by helfer** [comment]
@czert are you using the query option `notifyOnNetworkStatusChange`? If not, the component wouldn't be notified of changes in network status unless the data has also changed. If you are using that option but still aren't seeing the network status update, then it's a bug and a repro would be much appreciated! 🙂

**Comment by czert** [comment]
@helfer thanks, I wasn't using the new `notifyOnNetworkStatusChange` until a different issue brought it to my attention. All works fine now, thanks! :)

**Comment by jbaxleyiii** [comment]
networkStatus is included in props now
