### ISSUE TITLE
Uncaught TypeError: _this.currentObservable.query.resetQueryStoreErrors is not a function

### ISSUE THREAD

**Issue by simPod** [apollographql/react-apollo#3224]
I'm getting this error when using `"@apollo/react-hooks": "^0.1.0-beta.10"`

Simple `useQuery` as 
```ts
  const { loading, data } = useQuery<Q, V>(Document);
```

Results in

![image](https://user-images.githubusercontent.com/327717/60774960-fa323600-a124-11e9-98f8-013465f02de4.png)

**Comment by pie6k** [comment]
I'm also seeing this error

When I'm looking into the source:
![image](https://user-images.githubusercontent.com/7311462/60799951-799b2600-a174-11e9-9747-8c1d721a6d2e.png)

It looks like it's not a big deal, but we're using it in production and it worries us a bit.

**Comment by hwillson** [comment]
Please try updating to the latest version of `apollo-client` (2.6.3).

**Comment by simPod** [comment]
Confirming, it's 👌 with 2.6.3
