### ISSUE TITLE
ApolloConsumer client bug due to strange babel conversion

### ISSUE THREAD

**Issue by xandervr** [apollographql/react-apollo#3225]
**Intended outcome:**

The code in file lib/ApolloConsumer should look like:

```javascript
...
var ApolloConsumer = function (props, legacyContext) {
    function finish(context) {
        if (!context || !context.client) {
            throw new ts_invariant_1.InvariantError('Could not find "client" in the context of ApolloConsumer. ' + 'Wrap the root component in an <ApolloProvider>.');
        }
        return props.children(context.client);
    }
    return ApolloContext_1.ApolloContext ? (React.createElement(ApolloContext_1.ApolloContext.Consumer, null, function () { return finish(legacyContext); })) : (finish(legacyContext));
};
...
```

**Actual outcome:**

The code compiles as following:

```javascript
...
var ApolloConsumer = function (props, legacyContext) {
    function finish(context) {
        if (!context || !context.client) {
            throw new ts_invariant_1.InvariantError('Could not find "client" in the context of ApolloConsumer. ' + 'Wrap the root component in an <ApolloProvider>.');
        }
        return props.children(context.client);
    }
    return ApolloContext_1.ApolloContext ? (React.createElement(ApolloContext_1.ApolloContext.Consumer, null, finish)) : (finish(legacyContext));
};
...

```

**How to reproduce the issue:**

Just compile the release version with the latest babel version.

ApolloConsumer complains that there is no context passed through its provider.
This occurs when the react element is created while passing the **finish** function without its argument **legacyContext**. Manually fixing the compiled source by replacing it with an anonymous function where this argument is passed, fixes this issue!

Now why does babel compile the source this way??

**Version**

v2.5.3 - v2.5.8

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
