### ISSUE TITLE
Nested Queries stuck in loading state

### ISSUE THREAD

**Issue by jasonpaulos** [apollographql/react-apollo#3226]
Moved here from #2899, reported by @TroyWolf.

---

This thread (#2899) _appeared_ to be the same issue I'm having except I have now updated to `apollo-client 2.6.3` and still have a loading indicator that occasionally stays true despite the query returning from my API quickly and successfully.

I believe I have found the pattern that is the difference. The issue appears to be caused by having more than one `<Query>` polling at the same time. I have a parent component using `<Query>` to poll every 10 seconds for fresh data.

```
    <Query query={query} variables={{ id: 1234 }}>
      {({ loading, error, data, startPolling }) => {
        if (error) {
          return <div>Error!</div>;
        }

        if (!loading) {
          startPolling(5000);
        }      
```

There is a child component with a 2nd `<Query>` also doing 10s polling for a different set of data.

**When both requests kick off at the same time (or very close), the loading problem occurs.** 

To be clear, the API requests are coming back fast and successful. They are, in fact, not loading despite the fact `loading=true` is returned by `<Query>`. 

If I turn off polling on my parent component (`<Query>` #1), the loading indicator issue goes away in the child component (`<Query>` #2).

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
