### ISSUE TITLE
MockedProvider inconsistent behavior when resolving

### ISSUE THREAD

**Issue by kaueburiti** [apollographql/react-apollo#3227]
MockerProvider presents an inconsistent behavior when trying to resolve multiple queries.

**Intended outcome:**

In the Search component we at first get the user from @client, after that we use the `user.username` do get the repositories from that user. 

The expected outcome was that, when passing the mocked content and using `await wait(0);` **once** the Promise that returns that username would be resolved, but the Promise with the repository search would be loading.

```
// Search Container
const Search = () => {
  return (
      <Query query={queryUser}>
        {({ loading: loadingUserFromClient, data = {} }) => {
          const { user: userFromClient = {} } = data;

          if (loadingUserFromClient) return <p>Getting user from client...</p>;

          if (!userFromClient.username) return null;

          return (
            <Query
              variables={{ login: userFromClient.username }}
              query={querySearchRepository}
            >
              {({ loading, error, data: { user } = {} }) => {
                if (loading) return <p>Searching for user repository...</p>;
                if (error) return <p>Error in getting user repository.</p>;

                return <SearchDropdown  user={user} />
              }}
            </Query>
          );
        }}
      </Query>
  );
};
```

```
// Test file
 describe("when has username", () => {
    describe("when is loading the repositories", () => {
      it("should render a loading message", async () => {
        const { getByText } = render(
          <MockedProvider
             mocks={[
              ...queryUserMockContent,
              ...querySearchRepositoryMockContent
             ]} 
            addTypename={false}>
            <Search />
          </MockedProvider>
        );
        
        await wait(0);

        expect(
          getByText("Searching for user repository...")
        ).toBeInTheDocument();
      });
    });
});
```

```
// Mocks

export const queryUserMockContent = [
  {
    request: {
      query: queryUser
    },
    result: {
      data: {
        user: {
          username: "john.doe"
        }
      }
    }
  }
];

export const querySearchRepositoryMockContent = [
  {
    request: {
      query: querySearchRepository,
      variables: {
        login: "john.doe"
      }
    },
    result: {
      data: {
        user: {
          name: "John",
          repositories: {
            totalCount: 2,
            nodes: [
              { name: "my-blog", isPrivate: true },
              { name: "my-news", isPrivate: true }
            ]
          }
        }
      }
    }
  }
];
```
**Actual outcome:**
The outcome is that sometimes the test runs and it pass, but sometimes it runs but it fails. **Without any code modification**. 

**Version**

 System:
    OS: macOS 10.14.5
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 66.0.3
    Safari: 12.1.1
  npmPackages:
    apollo-boost: ^0.4.2 => 0.4.2 
    apollo-cache-inmemory: ^1.6.2 => 1.6.2 
    apollo-client: ^2.6.2 => 2.6.2 
    apollo-link-context: ^1.0.17 => 1.0.17 
    apollo-link-http: ^1.5.14 => 1.5.14 
    react-apollo: ^2.5.6 => 2.5.6

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
