### ISSUE TITLE
useSubscription hooks & skip config

### ISSUE THREAD

**Issue by Vincz** [apollographql/react-apollo#3228]
Hi! I'm migrating from react-apollo-hook to the official implementation and noticed that the `skip` option is missing for `useSubscription` hook.  
Hope this is the right place for this :)

**Comment by mattfwood** [comment]
@hwillson I could pick this up if someone isn't already working on it

**Comment by hwillson** [comment]
@mattfwood Sorry for the delay - if you're still interested that would be awesome!

**Comment by hwillson** [comment]
This feature request is being tracked in https://github.com/apollographql/apollo-feature-requests/issues/121, so I'll close it here. If anyone is interested in working on this, let us know over in the FR. Thanks!
