### ISSUE TITLE
Static fragment defs aren't compatible with static propTypes {} syntax.

### ISSUE THREAD

**Issue by richburdon** [apollographql/react-apollo#323]
One disadvantage of the convention to declare fragments as static members of the component is you can't reference these from static propTypes {} member functions. Also, while the fragments proptype is useful, it sort of "infects" the component (whereas, graphql and redux's connect go to pains to leave the component alone; but I don't see how you could have both...)

So the following is the path I took:

```
export const ItemFragments = {
  item: new Fragment(gql`
    fragment ItemFragment on Item {
      id
      title
    }
  `)
};

export class Item extends React.Component {
  static propTypes = {
    item: ItemFragments.item.propType
  };
  render() {
    let { item } = this.props;
    return (
      <div>{ this.props.title }</div>
    );
  }
}
```

**Comment by stubailo** [comment]
Basically we didn't specify a convention at all, but a lot of people were really adamant about wanting to attach their fragments to a specific component.

So you can't do `Item.fragments.item.propType` if you use a static property?

**Comment by tmeasday** [comment]
@richburdon could you make `fragments` a static class property too?

**Comment by tmeasday** [comment]
> Also, while the fragments proptype is useful, it sort of "infects" the component (whereas, graphql and redux's connect go to pains to leave the component alone; but I don't see how you could have both...)

Can you say a little more about what you mean by this?
