### ISSUE TITLE
compose() function does not return correct type

### ISSUE THREAD

**Issue by mchong-teal** [apollographql/react-apollo#3230]
**Intended outcome:**

Am using the compose() function to apply HOCs, and want the resulting component to have the correct types so I can get type-checking and autocomplete, etc. (similar to redux's compose, actually I expect them to behave the same..).

**Actual outcome:**

The type of the component returned by the compose() function is 'any'

**How to reproduce the issue:**
use a higher-order component to wrap any component using compose, e.g.:
`export const WrappedComponent = compose(withHOC)(InnerComponent);`

Um a ts template might be more helpful in this case, but if you really need I can provide a reproduction.  But the function declaration in 'flowRight.d.ts' is:
`export declare function compose(...funcs: Function[]): (...args: any[]) => any;`

**Version**
2.5.5

npx: installed 1 in 1.361s

  System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
  Binaries:
    Node: 8.10.0 - /usr/bin/node
    npm: 6.10.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 67.0.4
  npmPackages:
    apollo-cache-inmemory: ^1.6.0 => 1.6.0 
    apollo-client: ^2.5.1 => 2.5.1 
    apollo-link-context: ^1.0.17 => 1.0.17 
    apollo-link-error: ^1.1.11 => 1.1.11 
    apollo-link-http: ^1.5.14 => 1.5.14 
    react-apollo: ^2.5.5 => 2.5.5

**Comment by yaroslavgribov** [comment]
Hi @mchong-teal

Could you please give an example from where do you import `compose` function from?

**Comment by mchong-teal** [comment]
I import the react-apollo compose function using `import { compose } from 'react-apollo';`.  Thanks!

**Comment by yaroslavgribov** [comment]
exporting `compose` function was removed just recently in [e6089a](https://github.com/apollographql/react-apollo/commit/e6089a716b2b19b57f36200db378b8613a91612d), so may I suggest you stop importing  it from `react-apollo` to avoid future issues, and try using one from `redux` if you have it, they're the same

if you don't have `redux` you could either use [lodash.flowRight](https://www.npmjs.com/package/lodash.flowright) (which was actually [exported](https://github.com/apollographql/react-apollo/pull/2332/files) as `compose` by `react-apollo` before it was removed) or find some other compose implementations, I think there should be handful of those on npm

**Comment by Jaikant** [comment]
@yaroslavgribov That was helpful

**Comment by AnselmMarie** [comment]
@yaroslavgribov Thank you!!

**Comment by michaelolo24** [comment]
Thanks, this helps a lot! Also, this definitely wasn't updated in the docs, so I expect a good number of people to run in to this issue.

**Comment by hwillson** [comment]
@michaelolo24 or anyone here; if there are ever any glaring issues or things like this missing in the docs, please feel free to open a PR and tag me on it. I'll make sure docs changes get in place as quickly as possible. Thanks!

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
