### ISSUE TITLE
MockProvider is not reporting results.errors

### ISSUE THREAD

**Issue by barbieri** [apollographql/react-apollo#3233]
**Intended outcome:**

Following https://www.apollographql.com/docs/react/recipes/testing/#testing-error-states we have:

> To simulate GraphQL errors, define errors with an instantiated `GraphQLError` object that represents your error, along with any data in your result.

```js
const dogMock = {
  // ...
  result: {
    errors: [new GraphQLError('Error!')],
  },
};
```

It should return `errors` with `useQuery()`, but it's not.

**Actual outcome:**

The `useQuery()` returned `errors` remain `undefined`, however `networkStatus` becomes 8 (error).

Using `error` instead of `result.error` provides the same behavior.

**How to reproduce the issue:**
```js
// jest test:
import React from 'react';
import renderer from 'react-test-renderer';
import { useQuery } from 'react-apollo';
import { MockedProvider } from '@apollo/react-testing';
import { GraphQLError } from 'graphql';
import gql from 'graphql-tag';

it('renders errors', (): void => {
  const query = gql`
    query TestQuery {
      rates(currency: "USD") {
        rate
      }
    }
  `;
  const mocks = [
    {
      request: { query },
      result: {
        errors: [new GraphQLError('forced error')],
      },
    },
  ];
  const TestComponent = (): JSX.Element => {
    const { error } = useQuery(query);
    return <>{`error: ${error}`}</>;
  };

  jest.useFakeTimers();
  const instance = renderer.create(
    <MockedProvider mocks={mocks} addTypename={false}>
      <TestComponent />
    </MockedProvider>,
  );
  renderer.act((): void => {
    jest.runAllTimers();
  });
  expect(instance.toJSON()).not.toBe('error: undefined');
});
```

Currently fails:
```
$ jest bugreport.tsx
 FAIL bugreport.tsx
  ✕ renders errors (32ms)

  ● renders errors

    expect(received).not.toBe(expected) // Object.is equality

    Expected: not "error: undefined"

      37 |     jest.runAllTimers();
      38 |   });
    > 39 |   expect(instance.toJSON()).not.toBe('error: undefined');
         |                                 ^
      40 | });
      41 | 

      at Object.toBe (bugreport.tsx:39:33)
```

**Version**
```
$ npx envinfo@latest --preset apollo --clipboard
npx: installed 1 in 1.624s

  System:
    OS: macOS 10.14.5
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.16.0 - ~/Development/git/test/node_modules/.bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 67.0.4
    Safari: 12.1.1
  npmPackages:
    apollo: ^2.15.0 => 2.15.0 
    apollo-boost: ^0.4.3 => 0.4.3 
    apollo-cache-inmemory: ^1.6.2 => 1.6.2 
    apollo-client: ^2.6.3 => 2.6.3 
    apollo-link: ^1.2.12 => 1.2.12 
    apollo-link-error: ^1.1.11 => 1.1.11 
    apollo-link-http: ^1.5.15 => 1.5.15 
    react-apollo: 3.0.0-beta.3 => 3.0.0-beta.3 
```
Other:
```
@apollo/react-hooks: ^0.1.0-beta.10
@apollo/react-testing: ^0.1.0-beta.5
```

**Comment by MaxwellGover** [comment]
@barbieri Getting same issue but w/ data being `undefined`

**Comment by gregkerzhner** [comment]
Same issue here

**Comment by definitelycarter** [comment]
I believe it is a bug in [this section of code](https://github.com/apollographql/react-apollo/blob/master/packages/testing/src/mocks/mockLink.ts#L106-L115) where we are destructuring errors and data to send through to the Observable.

According to the QueryManager [here](https://github.com/apollographql/apollo-client/blob/a0948dcdd8b02788c697e9cf49f595dba6eda888/packages/apollo-client/src/core/QueryManager.ts#L226) and [here](https://github.com/apollographql/apollo-client/blob/a0948dcdd8b02788c697e9cf49f595dba6eda888/packages/apollo-client/src/core/QueryManager.ts#L1253), what gets passed through the Observable should be an object with a `data` or `errors` property.

```ts
      const mocks: ReadonlyArray<MockedResponse> = [
        {
          request: { query: SPACE_QUERY, variables: { id: space.id } },
          result: {
            errors: [new Error('fake error')],
            data: {
                // your response
            }
          },
        }
      ];
```

**Comment by hwillson** [comment]
Thanks for reporting this @barbieri. For some reason Jest is having a hard time working with the `setTimeout` calls we make in `MockLink`, to allow people to set a delay on the `Observable`. If I  disable the `setTimeout` calls, everything works properly (the error is properly set). 

@definitelycarter I believe you're pointing to the correct source of the issue, but the error destructuring should be okay. It's that `setTimeout` that is giving Jest grief. If that block of the `MockLink` code is updated to be:

```js
return new Observable(observer => {
  if (error) {
    observer.error(error);
  } else {
    if (result) {
      observer.next(
        typeof result === 'function'
          ? (result as ResultFunction<FetchResult>)()
          : result
      );
    }
    observer.complete();
  }
});
```

the following test passes properly:

```js
it("should render GraphQLError's", () => {
  const query = gql`
    query TestQuery {
      rates(currency: "USD") {
        rate
      }
    }
  `;

  const mocks = [
    {
      request: { query },
      result: {
        errors: [new GraphQLError('forced error')]
      }
    }
  ];

  const Component = () => {
    const result = useQuery(query);
    console.log(result.error);
    if (!result.loading) {
      expect(result.error).toBeDefined();
      expect(result.error!.message).toEqual('GraphQL error: forced error');
    }
    return null;
  };

  render(
    <MockedProvider mocks={mocks}>
      <Component />
    </MockedProvider>
  );
});
```

More details coming shortly.

**Comment by definitelycarter** [comment]
You are correct @hwillson that derestructuring `errors` should be fine.  I was more referring to @MaxwellGover's issue about `data` being undefined.  According to [this line](https://github.com/apollographql/apollo-client/blob/a0948dcdd8b02788c697e9cf49f595dba6eda888/packages/apollo-client/src/core/QueryManager.ts#L1253) we look for a `data` property on the result.

**Comment by hwillson** [comment]
@barbieri Actually, it looks like this is just a timing issue with the test itself. I've added a test in https://github.com/apollographql/react-apollo/pull/3256 that essentially does what you're doing, but I'm making sure the timing issues are dealt with by using Jest's `done` callback. You should be able to achieve the same affect using `jest.useFakeTimers` / `jest.runAllTimers`, but we tend to prefer leveraging Jest's built in async handling capabilities when testing HOC's / Components / Hooks. Please take a look at that PR to see what I mean.

@definitelycarter Thanks for the clarification. I don't quite follow what the issue is with `data` being `undefined`. Can you give me an example of when this is happening? Is this a separate issue, or is it related to `MockedProvider`'s error handling?

**Comment by barbieri** [comment]
yeah, I'm having many more issues with jest and react-test-renderer... basically `act()` is not async-friendly until the last (unreleased) version... so it keeps complaining and a mix of useFakeTimers/runAll{timers,immediates...} are not working for every case :-(

A major nightmare I could only solve by going to the alpha version -- but our project didn't accept to use that until it's released :-(

**Comment by hwillson** [comment]
@barbieri I hear you - definitely painful. I've merged in the test and will close this for now. 

@definitelycarter @MaxwellGover if you're able to open a separate issue for the `data` `undefined` issue (ideally with a small runnable reproduction), that would be great. 

Thanks all!

**Comment by PhilippSpo** [comment]
For us it was the node version. Didn't work with Node 10, works with Node 12 🤷‍♂

**Comment by HugoLiconV** [comment]
I'm having the same issue, this is my code: 
```javascript
  it('should show an error if cannot get orders', () => {
    const { debug } = getWrapper([
      {
      request: meQueryRequest,
      result: {
        data: meQueryResponse
      }
    }, {
      request: getMultipicksQueryRequest,
        result: {
          errors: [new GraphQLError('Error!')]
        }
    }], cache)
    debug() // here it shows the loading state
    act(() => {
      jest.runAllTimers()
    })
    debug() // here it should show the error but I'm getting undefined
  });
```

**Comment by andihaki** [comment]
@HugoLiconV using await solved my `undefined` error issue

```
it('should show an error if cannot get orders', async () => {
    const { debug } = getWrapper([
      {
      request: meQueryRequest,
      result: {
        data: meQueryResponse
      }
    }, {
      request: getMultipicksQueryRequest,
        result: {
          errors: [new GraphQLError('Error!')]
        }
    }], cache)
    debug() // here it shows the loading state
    act(() => {
      jest.runAllTimers()
    })
    await wait(() => {}, 1000)
    debug() // here it should show the error but I'm getting undefined
  });
```
