### ISSUE TITLE
Add @apollo/react-ssr to npm

### ISSUE THREAD

**Issue by lfades** [apollographql/react-apollo#3236]
Related to [next-with-apollo#62](https://github.com/lfades/next-with-apollo/issues/62)

**Intended outcome:**

The package should be available here https://www.npmjs.com/package/@apollo/react-ssr

**Actual outcome:**

I can't download the package

**How to reproduce the issue:**

Trying to download the package

**Version**

I want one

**Comment by benjamn** [comment]
Just published `@apollo/react-ssr@0.1.0-beta.1` for the first time. Sorry for the wait!
