### ISSUE TITLE
Incorrect BaseMutationOptions type

### ISSUE THREAD

**Issue by gauthierrodaro** [apollographql/react-apollo#3248]
**Intended outcome:**

No type error when using a function for the field `optimisticResponse` in the mutation options. The type should be:

```typescript
export interface BaseMutationOptions<TData = any, TVariables = OperationVariables> {
  ...
  optimisticResponse?: (data: TVariables) => TData |  TData
  ...
}
```

**Actual outcome:**

The current type is  

```typescript
export interface BaseMutationOptions<TData = any, TVariables = OperationVariables> {
  ...
  optimisticResponse?: TData
  ...
}
```

**How to reproduce the issue:**

Using a mutation with a function  for the field `optimisticResponse` in the mutation options will trigger the type error in a typescript project.

**Work around:**

You can do this ugly hack...
```typescript
// FIXME: this is an ugly hack...
optimisticResponse: ((variables) => ({
   __typename: "Mutation",
  yourMutation: {...}
}) as unknown) as TData
```

**Version**

This is present in all the versions from what I saw in the repo. But I am using 3.0.0
```
  System:
    OS: macOS 10.14.5
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 67.0.4
    Safari: 12.1.1
  npmPackages:
    apollo-boost: ^0.4.3 => 0.4.3 
    apollo-link-context: ^1.0.17 => 1.0.17 
    apollo-link-ws: ^1.0.17 => 1.0.17 
    react-apollo: 3.0.0-beta.3 => 3.0.0-beta.3 
```

**Comment by hwillson** [comment]
Thanks for pointing out this longstanding issue @gauthierrodaro. This should now be resolved by  https://github.com/apollographql/react-apollo/pull/3257.
