### ISSUE TITLE
Could someone provide an example of how to test a component that uses useQuery?

### ISSUE THREAD

**Issue by MaxwellGover** [apollographql/react-apollo#3254]
I've been attempting to find a way to test a component that uses `useQuery` but haven't been having much luck. I posted a question on StackOverflow with how I'm currently trying to test

https://stackoverflow.com/questions/57060842/example-of-how-to-test-a-component-that-uses-usequery

`data` is always `undefined` when running the tests.

Was wondering if someone could help provide me w/ a successful example of how they tested a component that uses useQuery. 

Thanks!

* Apollo Spectrum community: https://spectrum.chat/apollo
* StackOverflow (`react-apollo` tag): https://stackoverflow.com/questions/tagged/react-apollo
* Apollo Feature Request repo: https://github.com/apollographql/apollo-feature-requests

**Comment by hwillson** [comment]
@MaxwellGover The `useQuery` test suite should help:

https://github.com/apollographql/react-apollo/blob/bd87da901113c81e3e7e2a7edaeac791895abb96/packages/hooks/src/__tests__/useQuery.test.tsx

**Comment by damiangreen** [comment]
The example provided above requires we modify the component under test to have the test assertions within them.

This isn't possible of course when testing our own components that use `useQuery`.

I've tried with `await new Promise(resolve => setTimeout(resolve)) , 
with`waitForExpect`, 
with `await wait(1000) ` 

but can never get back the response that should be returned when `loading` is false

**Comment by MaxwellGover** [comment]
@damiangreen Same issue

**Comment by damiangreen** [comment]
I solved it, my answer is on https://stackoverflow.com/questions/57060842/example-of-how-to-test-a-component-that-uses-usequery
