### ISSUE TITLE
 Child component stuck in loading state, but the data is already loaded. 

### ISSUE THREAD

**Issue by developdeez** [apollographql/react-apollo#3258]
Similar to this issue but I'm using cache-first and getting the behavior: https://github.com/apollographql/react-apollo/issues/2899#issuecomment-513025327

I'm using "apollo-client": "^2.6.2" and "react-apollo": "^2.5.6" 
I noticed in my HOC when I refresh the page it will get stuck in loading...
The HOC checks if user is logged in but uses cache-first for speed.

**Comment by mikevercoelen** [comment]
Confirmed, exactly the same use case too...

**Comment by mikevercoelen** [comment]
Another thing to note is: in our use case, it seems to happen randomly that the loading never gets set to true, even tho I see the request is successfully executed. 

The `data` object also always stays `undefined`

How we reproduce it is: we reload the page, and while the page is reloading -> in Chrome we open another tab, and switch back to our app, and there you go the problem happens.

I'm not sure how it works internally, but ... does it have anything to do with active tabs?

**Comment by WhoAteDaCake** [comment]
@mikevercoelen Did you ended up finding a solution?

**Comment by mikevercoelen** [comment]
@WhoAteDaCake Yep upgrading to the latest react hooks did it

**Comment by hwillson** [comment]
This issue should be resolved in more recent versions of React Apollo. Thanks!
