### ISSUE TITLE
[Android] Query component can not catch Network error: Network request failed in case server is down

### ISSUE THREAD

**Issue by ext-vt-vfa-trungbb** [apollographql/react-apollo#3259]
I have problem on only android device with Query component  , error will be undefined in case backend server is down 
but on IOS device it work well , can catch Network error: Network request failed
```
//setup backend server 
import ApolloClient from 'apollo-client'
import { ApolloLink } from 'apollo-link'
import { InMemoryCache } from 'apollo-cache-inmemory'
import Config from 'react-native-config'
import { createLink } from '@dailydrip/apollo-absinthe-upload-link'


let CreateApolloClient = () => { 
  //let httpLink = createLink({ uri: `${Config.GRAPHQL_ENDPOINT}/graphql` })
  let httpLink = createLink({ uri: "http://192.168.4.165:3001/graphql" })
  let inner = function (operation, forward) {
    operation.setContext({
      headers: {}
    })

    return forward(operation)
  }

  let middlewareLink = new ApolloLink(inner)
  let clientToReturn = new ApolloClient({
    link: middlewareLink.concat(httpLink),
    cache: new InMemoryCache().restore(window.__APOLLO_STATE__)
  })

  return clientToReturn
}

export default CreateApolloClient
// using Query to fetch data 

const query = gql'
        query {
          getAllRoles {
            _id
              name
            }
        }
';
const Roles = React.memo((props) => (
  <Query
    query={query}
    fetchPolicy={'cache-and-network'}
  >
   {({ loading, error, data }) => {
      console.log('result data ->',data,'loading -> ',loading,'error->',error);
      if (loading) return <Text>loading....</Text>
      if (error) return <Text>error....</Text>
      return data.getAllRoles.map((item,index)=>{
        return(
          <View key={index}> 
          <Text style={styles.text}>{item.name}</Text>
          </View>
        )
      })
    }}
  </Query>
));
```
**Intended outcome:**
i expected in case backend server is down android device can catch error ( network error )
**Actual outcome:**

- Log on Android device in case **backend server is down**  as below

![Screen Shot 2019-07-19 at 08 29 07](https://user-images.githubusercontent.com/13307020/61504339-3a3ac800-aa05-11e9-984b-a369b9db5a36.png)

![error-android](https://user-images.githubusercontent.com/13307020/61504615-3ce9ed00-aa06-11e9-8c5f-fdb89176bdac.png)

- Log on IOS device in case **backend server is down**  as below

![Screen Shot 2019-07-19 at 08 49 55](https://user-images.githubusercontent.com/13307020/61504402-68b8a300-aa05-11e9-87e7-150f3570f5cd.png)

**In case backend server is up both ios and android work well** 

**How to reproduce the issue:**

- it very simple , just shutdown backend server ( graphQL server ) and run above code 

**Conclusion:**
On android device in case backend end server is down it can not fire callback function 
```
{({ loading, error, data }) => {

 })
    }}
```
**Version**
System:
    OS: macOS 10.14.5
  Binaries:
    Node: 12.5.0 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.142
    Safari: 12.1.1
  npmPackages:
    apollo-cache-inmemory: ^1.2.1 => 1.6.2
    apollo-client: 2.6.3 => 2.6.3
    apollo-link: ^1.2.12 => 1.2.12
    react-apollo: ^2.5.8 => 2.5.8

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!

**Comment by renato** [comment]
@hwillson I'm facing a similar issue on `@apollo/react-hooks` 3.1.3 using `apollo-boost` 0.4.7 (tried with `apollo-client` directly and the same thing happens).

If my `uri` is an address that denies the request (i.e. a running machine with no server running on given port) I get a `Network request failed`, but if the destination machine doesn't exist at all (i.e. it's unreachable), the `error` object is `undefined` on `useQuery`, `onError` is not triggered and `loading` is forever true.

Should I submit a new issue?
