### ISSUE TITLE
useSubscription don't return an ApolloError

### ISSUE THREAD

**Issue by ArnaudBarre** [apollographql/react-apollo#3263]
Version: `3.0.0-beta.4`

```ts
const { error } = useSubscription<UserInteraction>(...)
console.log(isApolloError(error)); // false
```

**Comment by hwillson** [comment]
@ArnaudBarre Apollo Client's `isApolloError` function just checks to see if an error has a `graphQLErrors` property. `useSubscription` can return an `ApolloError` instance, but it can also return `undefined` for the `error` (which of course doesn't have a `graphQLErrors` property). Are you checking for `undefined` first? If you still think this is a problem, could you share a small runnable reproduction that shows the issue?

**Comment by ArnaudBarre** [comment]
Yeah the was set but it was returning something like one graphQLError instead of an objects with a list of graphQLErrors. Have you a codesanbox base with Apollo provider setup ?

**Comment by hwillson** [comment]
@ArnaudBarre You can use https://github.com/apollographql/react-apollo-error-template or https://codesandbox.io/s/apollo-client-error-template-7762p, but they aren't setup to use subscriptions. It might be easier if you create a repro using the hooks example app in the `react-apollo` repo itself - it uses subscriptions. You can find it [here](https://github.com/apollographql/react-apollo/tree/38567ea3c2ecb49f4c6937a1a1fb3caf32f3a5a0/examples/hooks). Thanks!

**Comment by hwillson** [comment]
We'll close this for now, but if anyone running into this issue can provide a small runnable reproduction, we'll re-open. Thanks!
