### ISSUE TITLE
How to get previous data when query is fetching ? 

### ISSUE THREAD

**Issue by George874248** [apollographql/react-apollo#3271]
Hello, i make query request on input change, my data becomes empty when you re-request

Example 

1)
input = test
result  = [1,2,3,4,5]
loading = false

2)
input = testR
result  = []
loading = true

3)
input = testR
result  = [1,2,3,4,5, 6]
loading = false

Because of this, I have a flicker in the drop-down list

some code example 
app.tsx

```
const link = new HttpLink({
  uri: "rest/test",
})
const apiLink = new RestLink({
  endpoints: {
    test: "test",
  },
})

const client = new ApolloClient({
  link: ApolloLink.from([apiLink, link]),
  cache: new InMemoryCache(),
})
```

component

```
const UserChooser: React.FC<TeamMemberChooserProps> = props => {
  const [userName, setUserName] = React.useState("")

  const { data, loading, error } = useSearchTeamQuery({
    variables: {
      userName
    }
  })

  const handleSearchChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setUserName(event.target.value)
  }

  return (
      <div>
        <SearchInput
          value={userName}
          placeholder="search"
          onChange={handleSearchChange}
        />
        <div>
          {data.users.map(teamMember => <div>{teamMember}</div>)}
        </div>
      </div>
  )
}

```
how do i solve this problem without using react component state?

**Comment by Grmiade** [comment]
@George874248 Did you try the `refetch` feature?
https://www.apollographql.com/docs/react/essentials/queries/#polling-and-refetching

**Comment by George874248** [comment]
@Grmiade, yes, and get the same result

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!
