### ISSUE TITLE
How to skip ssr with graphql() hoc ?

### ISSUE THREAD

**Issue by YUFENGWANG** [apollographql/react-apollo#3274]
I know that we can skip a query during ssr by passing  `ssr={false}` to `Query` componet, but how can we do that by using `graphql()` hoc ?

**Comment by ivansky** [comment]
Hey, it took me only 1 minute to check how to pass options to actual hoc, there is a second argument which consumes `OperationOption` where we have `options` object with `ssr` property.

Here we go:
1. https://github.com/apollographql/react-apollo/blob/master/packages/hoc/src/types.ts#L81
2. https://github.com/apollographql/react-apollo/blob/master/packages/common/src/types/types.ts#L31

I think this kind of question might be asked on stackoverflow.

**Comment by YUFENGWANG** [comment]
@ivansky Thanks for that, maybe the apollo client docs should update. [react apollo docs](https://www.apollographql.com/docs/react/api/react-apollo/#graphql-options-for-queries)
