### ISSUE TITLE
cache.writeQuery doesn’t broadcast optimisticResponse for mutation

### ISSUE THREAD

**Issue by lensbart** [apollographql/react-apollo#3290]
**Intended outcome:**

When specifying an `optimisticResponse`, the update function of a mutation is called twice: once with the optimistic response and once again with the data returned by the mutation resolver.

The Apollo documentation [states](https://www.apollographql.com/docs/react/essentials/mutations/#updating-the-cache) that `cache.writeQuery` broadcasts the new data to any queries listening to the changes, specifically when used inside the `update` function of a mutation. It also [mentions](https://www.apollographql.com/docs/react/features/optimistic-ui/#adding-to-a-list) that “`update `works exactly the same way for optimistic results and the real results returned from the server”.

**Actual outcome:**

However, when adding an item to a list via a mutation with an update function and optimistic response, and when this `update` function updates the store using `cache.writeQuery`, I can _only_ see the changes in the store by calling `cache.readQuery` inside the same component that contains the mutation. That is, calling `cache.readQuery` elsewhere in the app shows the previous state of the Apollo store, insofar the optimistic response is concerned. The second update call (with real data) is available everywhere throughout the app.

I console.logged calls to `cache.writeQuery` (which happens first), `cache.readQuery` (in the same component, which shows the expected results), and `cache.readQuery` (in any of the parent components, showing stale data), and they happen in that order, so there’s no confusion about whether the optimistic response has already been written to the store when we read the query.

If relevant:
1. I’m using the hooks implementation from `react-apollo-hooks`,
2. the query that is updated is used (via `useQuery`) in a parent component, which rerenders twice: once for the optimistic response (which data is not available outside of the component where it was written), and once again for the real data (which does show up).

I tried making a codeplayground but couldn’t set up a working mutation example. I’d be happy to clarify further if necessary!

**Version**

System:
    OS: macOS 10.14.5
  Binaries:
    Node: 10.4.1 - /usr/local/bin/node
    Yarn: 1.17.3 - ~/Documents/GitHub/codebase/node_modules/.bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 68.0.1
    Safari: 12.1.1
  npmPackages:
    apollo: ^2.3.1 => 2.16.3 
    apollo-cache-inmemory: ^1.0.0 => 1.6.2 
    apollo-client: ^2.2.5 => 2.6.3 
    apollo-link: ^1.2.3 => 1.2.12 
    apollo-link-error: ^1.0.5 => 1.1.11 
    apollo-link-http: ^1.3.2 => 1.5.15 
    apollo-link-schema: ^1.2.2 => 1.2.3 
    apollo-server: ^2.0.5 => 2.8.0 
    apollo-server-express: ^2.0.3 => 2.8.0 
    react-apollo: ^2.0.0 => 2.5.8 
    react-apollo-hooks: ^0.5.0 => 0.5.0

**Comment by lensbart** [comment]
I finally resolved the issue by avoiding mutating the local store data in all mutations, see https://github.com/apollographql/apollo-client/pull/4543.

**Comment by hwillson** [comment]
React Apollo has been refactored to use React Hooks behind the scenes for everything, which means a lot has changed since this issue was opened (and a lot of outstanding issues have been resolved). We'll close this issue off, but please let us know if you're still encountering this problem using React Apollo >= 3.1.0. Thanks!

**Comment by lensbart** [comment]
FYI the issue was files after the hooks change, so I guess the behaviour is still present. But it doesn’t affect me anymore due to the workaround described above

**Comment by lensbart** [comment]
@hwillson yes it’s still happening with the latest version of apollo (hooks) — see https://github.com/apollographql/react-apollo/issues/3639
