### ISSUE TITLE
how to keep staying loading status is true - @apollo/react-hooks

### ISSUE THREAD

**Issue by huurray** [apollographql/react-apollo#3291]
version: 0.1.0-beta.10

hello, 
i wanted to use the "A" Mutation  in "B"  Mutation after i got specific error status. so i tried to use "A" Mutation in onError option of "B" Mutation. 

but i find it difficult to keep staying loading status of "B" Mutation is true, by the time "A" Mutation is finished.

could you tell me how i can do that?

**Comment by Ayc0** [comment]
Can you do `const isLoading = A.isLoading && B.isLoading`?

**Comment by hwillson** [comment]
If the recommendation in https://github.com/apollographql/react-apollo/issues/3291#issuecomment-521960856 doesn't help, please post your question in [Spectrum](https://spectrum.chat/apollo). Thanks!
