### ISSUE TITLE
React Apollo 3 Migration Guide page is not working

### ISSUE THREAD

**Issue by AnselmMarie** [apollographql/react-apollo#3318]
I was looking at the Apollo Client 3 Changelog information and clicked the link for the **React Apollo 3 Migration Guide page** (https://www.apollographql.com/docs/react/migrating-to-react-apollo-3/). Instead of seeing information about migration I got this:

Page Not Found

Looks like you've followed a broken link or entered a URL that doesn't exist on this site.

**Comment by Taraluktus** [comment]
In the Medium article about 3.0 the correct link was used:
https://www.apollographql.com/docs/react/hooks-migration/

**Comment by hwillson** [comment]
Oops - fixed. Thanks!
