### ISSUE TITLE
[Docs] useMutation hook `update` Function incorrect example

### ISSUE THREAD

**Issue by TimFL** [apollographql/react-apollo#3321]
Hello,

the `update` function displayed on the useMutation hooks documentation under 'Updating the cache' seems to be incorrect.

Displayed in example: 
`update({ cache, { data: { addTodo } } }) { ... }`

Should be:
`update( cache, { data: { addTodo } } ) { ... }`

[Direct link to section](https://www.apollographql.com/docs/react/essentials/mutations/#updating-the-cache)

**Comment by hwillson** [comment]
Great catch @TimFL - I'll get that fixed. Thanks!
