### ISSUE TITLE
Why can mutate function of MutationTuple resolve to void?

### ISSUE THREAD

**Issue by rovansteen** [apollographql/react-apollo#3322]
According to the [typing](https://github.com/apollographql/react-apollo/blob/master/packages/hooks/src/types.ts#L89), calling the first argument of `MutationTuple` returns a promise that resolves to either `void` or `ExecutionResult`. What is the reason that it can resolve to `void`? If there is an error in the promise it will be rejected, so in which scenario would the result be `void`?

It seems a bit redundant that you have to check for the existence of the result after calling the mutate function.

⚠ Type error `property 'data' does not exist on void | ExecutionResult`
```jsx
const { data } = await createPost({variables: { input }});
```

✅  Works, but feels weird.
```jsx
const response = await createPost({ variables: { input }});
if (!response) throw new Error();
const data = response.data;
```

**Version**
`react-apollo": "^3.0.0"`
`react-apollo-hooks": "^0.4.4"`

**Comment by davewasmer** [comment]
Agreed, this is odd. I'd suggest that function with a return type that is a union of `void` and _anything_ is contradictory. `void` means "this function doesn't really have any return value". It doesn't make much sense to say "this function doesn't have any return value, or, it has a return value".

**Comment by Misticek** [comment]
I was facing the same issue today. Would be nice to remove that void type. 
Quick fix for me was to type the mutation result to ExecutionResult, see example:

```
interface IResponseData {...}

const [createPost] = useMutation<IResponseData>(createPostMutation)

const { data } = (await createPost(variables)) as ExecutionResult<IResponseData>
```

**Comment by capaj** [comment]
This prevents TS users from doing destructuring. Please remove the `void`.

**Comment by SirensOfTitan** [comment]
Yeah, this is really odd and makes hooks effectively unusable, as both destructuring and use of `idx` don't work.

**Comment by hwillson** [comment]
We'll definitely get this fixed (🤞in the next couple of hours). Thanks all!

**Comment by hwillson** [comment]
I should have this fix published today (just squeezing in a few more bug fixes).

**Comment by capaj** [comment]
@hwillson can we get it published now? Just in case you didn't know in most node.js semver implementations you can have as many patch numbers as `Number.MAX_SAFE_INTEGER` so that should give you guys enough headroom to just publish a few patches every day :dancing_men: :dancing_women:

**Comment by hwillson** [comment]
Haha @capaj! Sorry, I was pulled into an emergency for a bit, but things are getting back to normal. Publishing momentarily - thanks!

**Comment by capaj** [comment]
@hwillson now this is the kind of customer service that makes me lobby my organizsation into paying for the pro version of apollo-engine.
