### ISSUE TITLE
Missing guidance on how to support both hooks and components in v3 migration doc

### ISSUE THREAD

**Issue by kafkahw** [apollographql/react-apollo#3325]
**Intended outcome:**  The migration doc should give examples about how to support both existing components built with apollo-component and building new components with apollo-hooks. For instance, should we import different `ApolloProvider` to support those two features?

**Actual outcome:** The v3 migration doc doesn't say anything about how to support both apollo-hooks and apollo-component. We need this because we don't want to refactor every single old component built with apollo-component and at the same time we'd like to use apollo-hooks for building new components.

**How to reproduce the issue:** Look at existing apollo doc on migration.

**Version**: v3

**Comment by dylanwulf** [comment]
I just tested it out, it seems like `ApolloProvider` from `@apollo/react-hooks` works fine with both hooks and components. I would assume it also works with HOC, considering HOC and components are just wrappers around the hooks now.
If you look at the "Getting Started" guide, it only ever imports `ApolloProvider` from the `@apollo/react-hooks` package. Never from anywhere else.
https://www.apollographql.com/docs/react/essentials/get-started/#connect-your-client-to-react

**Comment by kafkahw** [comment]
@dylanwulf Thank you! good to know that.

yeah, the doc on "Get Started" guide confused me as it only states how to import `ApolloProvider` from `@apollo/react-hooks`. It should give an example to show `import { ApolloProvider } from 'react-apollo'` as well. Basically I think all the usages with 'react-apollo' are missing in the migration/start doc (e.g. how to import hooks from `react-apollo` instead of `@apollo/react-hooks`). I think those will help mitigate the frictions we'll experience when migrating to v3.

An interesting finding: 
if you install both `react-apollo` and `@apollo/react-hooks`, and import `ApolloProvider` from `react-apollo` and `useQuery` from `@apollo/react-hooks`, those two won't work together.

**Comment by RIP21** [comment]
Actually, it's kinda buggy.
If I'm using ApolloProvider from @apollo/react-common it doesn't work at all.
Also, it randomly dies in tests T_T

**Comment by hwillson** [comment]
Thanks for the suggestions all. We're merging React Apollo into Apollo Client (for Apollo Client 3.0), and will be overhauling the docs shortly. We'll make sure using hooks alongside components is clearly explained.
