### ISSUE TITLE
Queries execute twice in StrictMode

### ISSUE THREAD

**Issue by zenios** [apollographql/react-apollo#3326]
using the new useQuery hook in StrictMode the queries are subscribed twice but cleaned up only once resulting in components that have been unmounted to receive updates.

The reason is that in StrictMode useDeepMemo which internally does useRef  is executed twice while the useEffect that does the cleanups is executed once.

in the attached screenshots you can see the same query being added twice into watched queries and when the component unmounts we are left with one query still there

![Screenshot from 2019-08-08 10-54-00](https://user-images.githubusercontent.com/89569/62685251-f6ffc380-b9ca-11e9-8492-e48dcc059a82.png)
![Screenshot from 2019-08-08 10-54-03](https://user-images.githubusercontent.com/89569/62685257-f9fab400-b9ca-11e9-806d-aae7ce1a540e.png)

.

**Comment by hwillson** [comment]
Please test with React Apollo 3.1.0 and if this is still an issue let us know (ideally with a small runnable reproduction). Thanks!
