### ISSUE TITLE
Extract PropTypes for GraphQL queries

### ISSUE THREAD

**Issue by swernerx** [apollographql/react-apollo#333]
Currently it seems that we a doing a lot of duplicate work where we define types for data structures all over different places. We are relatively consequent on using PropType definitions for every component. Therefor we have to use them, too, for our GraphQL query-connected components. When accessing the PropTypes inside our code eslint is complaining about the usage as these are typically not declared in our PropTypes section in first place. 

Libraries like redux-form are exporting their PropTypes so that we can simply import them and add them to our own PropTypes using the object-spread operator. There a some default properties which are passed via the GraphQL connection like "data.loading" and "data.error". These should be somehow importable from a common library. 

Also it would be nice to have some kind of access to the types defined in the GraphQL schema so that we can link them to the PropTypes. Managing this stuff all over the place is not a good concept to keep things DRY.

Example:

```js
Step.propTypes = {
  hasRequiredElectivesVariables: React.PropTypes.bool,
  electiveVariables: React.PropTypes.object,
  electiveCodes: React.PropTypes.array,
  loading: React.PropTypes.bool,
  error: React.PropTypes.object
}

const mapStateToProps = (state) => ({
  electiveVariables: getElectivesVariables(state),
  hasRequiredElectivesVariables: hasRequiredElectivesVariables(state)
})

const withElectivesData = graphql(ElectivesQuery, {
  options: (ownProps) => ({
    skip: !ownProps.hasRequiredElectivesVariables,
    variables: ownProps.electiveVariables
  }),

  props: ({ ownProps, data }) => ({
    electiveCodes: get(data, "customization.needAnalysis.electiveCodes"),
    loading: data.loading,
    error: data.error
  })
})

export default connect(mapStateToProps)(withElectivesData(Step))
```

Possibly improved version:

```js
Step.propTypes = {
  hasRequiredElectivesVariables: React.PropTypes.bool,
  electiveVariables: React.PropTypes.object,
  electiveCodes: PropFromApollo(schemaUrl, xPath-like-accessor),
  ...ApolloQueryTypes
}

const mapStateToProps = (state) => ({
  electiveVariables: getElectivesVariables(state),
  hasRequiredElectivesVariables: hasRequiredElectivesVariables(state)
})

const withElectivesData = graphql(ElectivesQuery, {
  options: (ownProps) => ({
    skip: !ownProps.hasRequiredElectivesVariables,
    variables: ownProps.electiveVariables
  }),

  props: ({ ownProps, data }) => ({
    electiveCodes: get(data, "customization.needAnalysis.electiveCodes"),
    loading: data.loading,
    error: data.error
  })
})

export default connect(mapStateToProps)(withElectivesData(Step))
```

BTW: We are using the Webpack GQL loader... so `ElectivesQuery` is actually being imported from a separate file.

Minor oddity: What's pretty cumbersome is the different signatures in some code e.g. why do 'options' and 'props' inside a graphQl HOC do not use the same parameter design?

**Comment by tmeasday** [comment]
Is all you are asking for here that we export propTypes for `loading` and `error`? I think we could do that! Maybe you could send a PR?

> why do 'options' and 'props' inside a graphQl HOC do not use the same parameter design?

Because `options` runs before we get the data, and `props` afterwards.

**Comment by swernerx** [comment]
Have no time for a PR right now.

Regarding the signature... still you could use the same idea of parameters e.g. using named parameters in both places for example.

**Comment by swernerx** [comment]
Generally what I meant was PropTypes for everything from the query. We already have all the types defined the the schema for the queries... why to reuse this information?

**Comment by tmeasday** [comment]
See https://github.com/apollostack/react-apollo/issues/302#issuecomment-262863047

**Comment by tmeasday** [comment]
> Regarding the signature... still you could use the same idea of parameters e.g. using named parameters in both places for example.

Does this mean that it should look like

```js
graphql(query, {
  options(ownProps) {
  },
  props(ownProps, data) {
  }
});
```

I think we considered that but decided against it simply because `data` was what you typically want to look at, and that makes it slightly harder to get to. IDK.

We could also consider something like `remapProps(props) {}` where `props` is `ownProps` combined with `data` -- i.e. what `graphql` would by default pass into the child component..

**Comment by jbaxleyiii** [comment]
I don't have any plans to put time into proptypes. Instead, we will be adding better typescript and flow support. If prop types are needed, I think the could be a separate package
