### ISSUE TITLE
Attempted import error: 'compose' is not exported from 'react-apollo'

### ISSUE THREAD

**Issue by luizdanieldesouza** [apollographql/react-apollo#3330]
After upgrading react-apollo to 3.0.0 the following error message is presented:

`Attempted import error: 'compose' is not exported from 'react-apollo'`

**Comment by hwillson** [comment]
@luizdanieldesouza `compose` was removed from React Apollo 3 (see the [Breaking Changes](https://github.com/apollographql/react-apollo/blob/e9190fac891dd7af3a1690a5d2a1305953fd5a6f/Changelog.md#breaking-changes) section of the `Changelog`). If you want to keep using `compose` though, it was just a copy of lodash's [`flowRight`](https://lodash.com/docs/4.17.15#flowRight).

**Comment by victors1681** [comment]
@hwillson any idea why it was removed? I'd like to know what is the best practice now because the documentation on `https://www.apollographql.com` still using `compose ` in their examples.

**Comment by hwillson** [comment]
@victors1681 It was removed to help reduce the React Apollo bundle size. Since `compose` was really just a copy of lodash's `flowRight`, it didn't make sense to keep it in the bundle. Especially when not everyone wanted to use it and when it's quite easy to add `flowRight` into a project (and alias it as `compose` if you want to):

```sh
npm install lodash.flowright
```

```js
import * as compose from 'lodash.flowright';
```

**Comment by rooch84** [comment]
`import * as compose from 'lodash.flowright';`

For some reason this didn't work for me.  I had to use:
`import flowright from "lodash.flowright";`

And simply rename `compose` to `flowRight`.

**Comment by brenopgarcia** [comment]
Thanks! It worked for me.

**Comment by Falieson** [comment]
@rooch84 any default import can be named whatever you want. these are all equivalent:
The reason @hwillson is probably using the  `* as ` notation is TypeScript.
```
import flowright from "lodash.flowright";
```
```
import foobar from "lodash.flowright";
```
```
import compose from "lodash.flowright";
```

**Comment by rooch84** [comment]
Thanks for the clarification.
