### ISSUE TITLE
TypeScript: No longer have MockedProviderProps exported from @apollo/react-testing (comparing to react-apollo/test-utils)

### ISSUE THREAD

**Issue by dturcotte** [apollographql/react-apollo#3336]
Loving 3.0.0 - but I hit a TypeScript snag during the upgrade:

**Intended outcome:**

When using `react-apollo/test-utils`, occasionally I found it helpful to have access to `MockedProviderProps`:

```
import {
  MockedProvider,
  MockedProviderProps,
} from 'react-apollo/test-utils';
```

**Actual outcome:**

After the reorganization, `@apollo/react-testing` no longer exports `MockedProviderProps`: https://github.com/apollographql/react-apollo/blob/master/packages/testing/src/index.ts#L1

**How to reproduce the issue:**

Try to do an equivalent import from `@apollo/react-testing`:
```
import {
  MockedProvider,
  MockedProviderProps,
} from '@apollo/react-testing';
```

**Version**

`@apollo/react-testing@3.0.0`

**Comment by hwillson** [comment]
Oops - this wasn't intentional @dturcotte; I'll get that fixed. Thanks for letting us know!
