### ISSUE TITLE
Add autoSkip option for query connection

### ISSUE THREAD

**Issue by swernerx** [apollographql/react-apollo#334]
We generally try to keep our code clean. Something we saw recently is that we do a lot of manual code to implement query skipping. Typically queries depend on some kind of user input. In our - pretty wizard hefty application - it's possible that some specific requirement is not yet correctly filled out. Instead of manually implementing a `skip` selector everytime it would be nicer to have another status code and some auto-magic dealing with this. Instead of setting `skip` to boolean it could be set to `"auto"`. In this case we get another status flag on `data`: `waiting`. So that we have `loading`, `error`, `waiting`. The newly added state could also have some kind of inner data structure which defines which variables are missing. This way we would be easily able to use this as a guidance for the application user to navigate her to the correct wizard page/destination.

**Comment by tmeasday** [comment]
Hi @swernerx, this is a little unclear.

Are you suggesting that `skip: 'auto'` would lead to this behaviour if not all variables were provided?

I think this is probably easier implemented as a helper function that generates options

**Comment by swernerx** [comment]
Yes that's what I meant.

**Comment by tmeasday** [comment]
Thinking about this a little more;

One of my goals was to try and simplify `react-apollo` so it didn't really need to understand the query etc. So RA simply passes props into `apollo-client` without understanding which are variables and which aren't. AC then works it out.

I think with this in mind, it would probably just make the most sense to simply pick up the error that AC passes down when you try and run a query w/o all variables defined in your wrapped component. You could insert an "autoskip" component in between your `graphql` component and wrapped component to transform this to make things simpler (or use a helper function for `props`).

If it's hard to differentiate that particular error, we should consider changing AC to make it easier.

**Comment by jbaxleyiii** [comment]
@swernerx I'm not sure I follow the need here? If this is still something you want to discuss feel free to reopen the issue!
