### ISSUE TITLE
useQuery: onCompleted called on every update

### ISSUE THREAD

**Issue by levrik** [apollographql/react-apollo#3353]
**Intended outcome:**

Updating some state in `onCompleted` based on the result from a query.

**Actual outcome:**

Ending up in an endless loop, since every update to the component which calls the query, results in `onCompleted` getting called again.

**How to reproduce the issue:**

https://codesandbox.io/embed/apollo-client-error-template-78jbq
Pay attention to the console.

**Version**

`@apollo/react-hooks 3.0.0`

**Comment by levrik** [comment]
Ah. I see where the issue lies.
The passed `onCompleted` callback is different on every render so it triggers a re-fetch.
Probably a change of `onCompleted` shouldn't result in a re-fetch.

**Comment by PovilasSlekys** [comment]
I noticed the same issue. This seems to be solved by passing variables: {} to the query options in the case where the query has no variables as in the example.

**Comment by oceandrama** [comment]
@PovilasSlekys Thanks, you saved a few hours of my life!

**Comment by rmalca** [comment]
@PovilasSlekys I don't know why but it's works!

**Comment by hwillson** [comment]
This has been fixed by https://github.com/apollographql/react-apollo/pull/3419, and will be released shortly. Thanks!
