### ISSUE TITLE
[BUG] useMutation fires twice first time without query

### ISSUE THREAD

**Issue by Sh1d0w** [apollographql/react-apollo#3358]
**Intended outcome:**

I've followed the example code:

```
import gql from 'graphql-tag';
import { useMutation } from '@apollo/react-hooks';

const ADD_TODO = gql`
  mutation AddTodo($type: String!) {
    addTodo(type: $type) {
      id
      type
    }
  }
`;

function AddTodo() {
  let input;
  const [addTodo, { data }] = useMutation(ADD_TODO);

  return (
    <div>
      <form
        onSubmit={e => {
          e.preventDefault();
          addTodo({ variables: { type: input.value } });
          input.value = '';
        }}
      >
        <input
          ref={node => {
            input = node;
          }}
        />
        <button type="submit">Add Todo</button>
      </form>
    </div>
  );
}
```

However it is no working as it should when I click Add Todo.

**Actual outcome:**

When I click Add Todo button Apollo fires two requests one after another. First one is without the mandatory query key in the payload, so it fails but the second one has it and passes. If after that I click the button again without refreshing the page it will fire only one request with correct query prop.

Here is a video of the problem:

![Screen Recording 2019-08-13 at 15 28 02](https://user-images.githubusercontent.com/5074917/62941991-007c9780-bde0-11e9-9231-53d4ab98aea1.gif)

**How to reproduce the issue:**

Just follow the code example here https://www.apollographql.com/docs/react/essentials/mutations/

**Version**

System:
    OS: macOS 10.14.6
  Binaries:
    Node: 10.15.2 - /usr/local/bin/node
    Yarn: 1.16.0 - ~/Npm/bin/yarn
    npm: 6.10.1 - ~/Npm/bin/npm
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 65.0
    Safari: 12.1.2
  npmPackages:
    apollo-boost: ^0.4.4 => 0.4.4 
    apollo-link-context: ^1.0.18 => 1.0.18 
    apollo-link-persisted-queries: ^0.2.2 => 0.2.2 
    react-apollo: ^3.0.0 => 3.0.0

**Comment by Sh1d0w** [comment]
After a short investigation it seems it is caused only when you add headers to HttpLink during SSR.

```
const httpLink = createPersistedQueryLink().concat(
    new HttpLink({
      uri,
      headers,
    }),
  );
```

**Comment by Sh1d0w** [comment]
The solution was to add `credentials: "same-origin"`

```
new HttpLink({
      uri,
      headers,
      fetchOptions: {
        credentials: "same-origin",
      },
    }),
```

**Comment by Asciant** [comment]
I came across this Github issue, as I was experiencing the same behaviour as described. 

After adding @Sh1d0w's `fetchOptions`, I eventually worked out that the mutation will also fire twice (with no variables in the second mutation) if you specify the `refetchQueries` option in the wrong place.

I had included the `refetchQueries` option within the useMutation declaration, like so:

```javascript
const [toggleLike, {
    data: mutationData
}] = useMutation(
    likeMutation, {
        refetchQueries: [{
            query: likedQuery,
            variables: {
                id
            }
        }]
    }
)

...

await toggleLike({
    variables: {
        id
    }
})
```

The code above will cause the mutation to fire a second time, in exactly the same manner as described in this issue (with no variables).

Moving the `refetchQueries` option into the mutation function declaration fixed the issues up right away. 

```javascript
const [toggleLike, {
    data: mutationData
}] = useMutation(likeMutation) // <- No options, just the mutation

...

await toggleLike({
    variables: {
        id
    },
    refetchQueries: [{
        query: likedQuery,
        variables: {
            id
        }
    }]
})
```

Hopefully this helps anyone stuck with the same problem.
