### ISSUE TITLE
refetchQueries run before Mutation get response

### ISSUE THREAD

**Issue by GeniousM** [apollographql/react-apollo#3363]
**Intended outcome:**

Hello, I use `React-Apollo` and `GraphQL`, and I made a function of [ Like button ] like instagram. It works well when i click button to add like but it works few times when it be cancel like.
"add like" works very well in every single event, but "cancel like" works few times randomly.
I found that when i click like - to add like - server runs and sends client response after mutation is done. but It send response before mutation is done when i cancel like.
it might be because cancel like function coded with deleting DB that it takes much more time than just update or add DB. Still, it response well.
It works in this code.

server
```
import { Like } from "../../../../models/index";

export default {
  Mutation: {
    toggleLike: async (_, args, { req }) => {
      const { userinfo } = req;

      if (userinfo !== undefined && userinfo.id !== undefined) {
        const { board, boardName } = args;
        const user = userinfo.id;
        return Like.findOrCreate({                 // find like, if it isn't, make like.
          where: { board, user },
          defaults: { board, user, boardName }
        })
          .then(([like, created]) => {
            if (!created) {                               // if there is like already, delete like
              const { id } = like;
              Like.destroy({ where: { board, user, id } }).then(_ => {
                console.log("Delete")
                return {
                  success: true,                    // response of cancel like
                  err: null,
                  isLogin: true
                };
              });
            }

            return {                                    // response of add like
              success: true,
              err: null,
              isLogin: true
            };
          })
          .catch(err => {
            return {
              success: false,
              err,
              isLogin: true
            };
          });
      }

      return {
        success: false,
        err: "token expire",
        isLogin: false
      };
    }
  }
};
```

client
```
import React from 'react';
import { Query, Mutation } from 'react-apollo';
import { LIKE, GET_LIKE } from './Query/QuariesAlbum';
import { Button, Icon } from 'antd';
import { Loading, Err } from '../../Shared/loading';

interface Data {
  getLikes: {
    isLike: boolean;
    likesCount: number;
    err: string;
  };
}

interface getLike {
  success: boolean;
  err: string;
  isLogin: boolean;
}

interface postLike {
  board: number;
  boardName: string;
}

interface Variables {
  id: number;
  boardName: string;
}

interface Props {
  boards: any;
}

interface State {}

export default class LikeBTN extends React.Component<Props, State> {
  state = {
    like: false,
    count: 0,
  };

  setLike = (like: any) => {
    console.log('after complete Query :', like);
    this.setState({
      like: like.isLike,
      count: like.likesCount,
    });
  };

  switchLike = async (e: any, mufu: any) => {
    let result: any = await mufu();

    console.log('Like result :', result);
    if (result.data.toggleLike.success === true) {
      console.log('clicked Like');
    } else {
      alert('login please');
    }
  };

  render() {
    return (
      <Query<Data, Variables>
        query={GET_LIKE}
        variables={{ id: this.props.boards.id, boardName: 'album' }}
        onCompleted={data => this.setLike(data.getLikes)}
      >
        {({ loading, error, data }: any) => {
          if (loading) return <Loading />;
          if (error) return <Err />;
          console.log('query successful :', data);

          return (
            <span>
              <Mutation<getLike, postLike>
                mutation={LIKE}
                variables={{
                  board: this.props.boards.id,
                  boardName: this.props.boards.boardName,
                }}
                refetchQueries={[
                  {
                    query: GET_LIKE,
                    variables: {
                      id: this.props.boards.id,
                      boardName: 'album',
                    },
                  },
                ]}
                awaitRefetchQueries={true}
              >
                {toggleLike => (
                  <Button onClick={e => this.switchLike(e, toggleLike)}>
                    {this.state.like ? (
                      <>
                        <Icon
                          type="heart"
                          theme="twoTone"
                          twoToneColor="#ff0000"
                        />
                        {this.state.count}
                      </>
                    ) : (
                      <>
                        <Icon type="heart" />
                        {this.state.count}
                      </>
                    )}
                  </Button>
                )}
              </Mutation>
              {console.log('like count :', data.getLikes.likesCount)}
            </span>
          );
        }}
      </Query>
    );
  }
}
```

i attach the console.log of server.

![image](https://user-images.githubusercontent.com/12226897/62996313-33d22b80-be9f-11e9-94d8-fe48d4e5923c.png)

you can find that mutation response complete before delete like is done

I tried some method to solve this problem.
And there are `[ awaitRefechQuaries={true}, onComplete={refetchQuaries} ]`
but they don't work clearly.

I just considered that refetchQuaries run after Mutation is done.
but it doest.

How can i solve problem..?

**Actual outcome:**

**How to reproduce the issue:**

**Version**

  System:
    OS: macOS 10.14.6
  Binaries:
    Node: 10.16.1 - ~/.nvm/versions/node/v10.16.1/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.1/bin/npm
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 63.0.3
    Safari: 12.1.2
  npmPackages:
    apollo-boost: ^0.4.3 => 0.4.3 
    apollo-cache-inmemory: ^1.6.2 => 1.6.2 
    apollo-client: ^2.6.3 => 2.6.3 
    apollo-link-context: ^1.0.18 => 1.0.18 
    apollo-link-http: ^1.5.15 => 1.5.15 
    apollo-link-state: ^0.4.2 => 0.4.2 
    react-apollo: ^2.5.8 => 2.5.8

**Comment by JoviDeCroock** [comment]
`awaitRefetchQueries` makes your refetchQueries execute before your mutation completes, if you set that to false it should be good.

**Comment by GeniousM** [comment]
@JoviDeCroock I did, but it doesn't work. you can see there is already awaitRefetchQuaries in my code.

```
<Mutation<getLike, postLike>
                mutation={LIKE}
                variables={{
                  board: this.props.boards.id,
                  boardName: this.props.boards.boardName,
                }}
                refetchQueries={[
                  {
                    query: GET_LIKE,
                    variables: {
                      id: this.props.boards.id,
                      boardName: 'album',
                    },
                  },
                ]}
                awaitRefetchQueries={true}
              >
```

**Comment by JoviDeCroock** [comment]
> set that to false it should be good.

**Comment by GeniousM** [comment]
@JoviDeCroock  yes, i know it. that is the reason i wrote this post.
I intended to make a toggle like button that send mutation to server.
when server get event of toggle like, it change Database both add like, and delete like.
after DB is changed, it send response to server and client.
I know that the refetchQuaries run after the mutation response is arrived.
so, when i [add like] it works perfect. but when i [delete like] ?

IT DOESN'T WORK.

I suspect that the cause of this problem is destroying DB cost much more time than creating.
but i still don't know why refetchQuaries run before mutation send response.

I also tried without awaitRefetchQuaries, or it be false, and - you can see - it be true.
every awaitRefetchQuaries gave me same result.

it works randomly.

**Comment by GeniousM** [comment]
I found that there was missing "return" in front of "Like.destroy()"

now it works well
