### ISSUE TITLE
onComplete never called

### ISSUE THREAD

**Issue by DominicTobias** [apollographql/react-apollo#3364]
**Intended outcome:**

After a successful request, `onComplete` should be called.

**Actual outcome:**

Neither `onComplete` (or `onError` are called). This is from a hard refresh so not a local graph caching issue.

**How to reproduce the issue:**

**Codepen:** If I get any random Codepen with hooks it doesn't work either, e.g: https://codesandbox.io/s/apollo-graphql-react-hooks-example-m2zr1

Client not set up in any special way:

```js
import ApolloClient from 'apollo-boost';

const client = new ApolloClient({
  uri: `absolute/path/to/graphql`,
});

// And:

import { ApolloProvider } from '@apollo/react-hooks';

const WrappedApp = (
  <ApolloProvider client={client}>
      <App />
  </ApolloProvider>
);
```

Make a query to graphql in a functional component:

```js
const teamQuery = gql`
  {
    teams {
      ...
    }
    teamLinks {
      ...
    }
  }
`;

const { loading, error, data } = useQuery(teamQuery, {
  onComplete: data => {
    // Not called
    console.log('onComplete');
  },
  onError: err => {
    // Not called
   console.log('onError');
  },
});
```

I observe the following:

![ql-response](https://user-images.githubusercontent.com/760314/63013678-a7b30a80-be84-11e9-8dc5-6e25d18cf25b.png)

As you can see the request successfully completes and `loading`, `error`, and `data` are as expected, but the callbacks are never called.

**Versions**

```
  System:
    OS: Windows 7
  Binaries:
    Node: 10.13.0 - C:\...\dev\tools\nodejs\v10.13.0\node.EXE
    npm: 6.4.1 - C:\...\dev\tools\nodejs\v10.13.0\npm.CMD
  npmPackages:
    apollo-boost: ^0.4.4 => 0.4.4
    @apollo/react-hooks ^3.0.0
    graphql ^14.4.2
```

**Comment by hwillson** [comment]
@DominicTobias The option should be called `onCompleted`. You have `onComplete` (missing the `d`) in both your code sample here and codesanbox. Adding the `d` will resolve this.

**Comment by DominicTobias** [comment]
Argg thanks!! Works, kind of, onCompleted is called infinitely but think I can workaround it with `useCallback`
