### ISSUE TITLE
@apollo/react-components Mutation : client missing in props & function render props

### ISSUE THREAD

**Issue by ridergoster** [apollographql/react-apollo#3366]
**Intended outcome:**
``<Mutation {...props} client={apolloClient}>{(mutate, {client}) => {...}}</Mutation>``

**Actual outcome:**
client is undefined in function render props and client seems to be missing in proptypes in Mutation components

**Version** 3.0.0

**Comment by joshalling** [comment]
I also noticed this. I think it may have been removed in favor of using the [useApolloClient](https://www.apollographql.com/docs/react/api/react-hooks/#useapolloclient) hook.

**Comment by Vaneste** [comment]
@ridergoster Maybe you could check your imports, see https://github.com/apollographql/react-apollo/issues/3373
I didn't tried with renders props anyway...
Good luck..

**Comment by htulipe** [comment]
@joshalling the documentation says it's supposed to be there and the change, if made on purpose, should be listed as a breaking change.

**Comment by htulipe** [comment]
Are you sure ? Though this issue relates to 3.0.0, the one I open up mistakenly 3 days ago (#3391) was about 3.0.1. Plus, nothing in 3.0.1 changelog mention such a fix.

**Comment by htulipe** [comment]
Great news, thanks!
