### ISSUE TITLE
Subscriptions testing and information about that in documentation

### ISSUE THREAD

**Issue by avasuro** [apollographql/react-apollo#3370]
Hi, sorry if I posted this in wrong place, but I can't decide where to ask this. I have both question and request:

1) How to test subscriptions in Apollo? e.g. I have react component (list of users) that uses subscription like "onUserUpdated" - how can I test this component to see that after new subscription message received (e.g. user changed his phone number) this changes applies to UsersList component?

2) Could you please add information related to testing Subscriptions to [this article](https://www.apollographql.com/docs/react/recipes/testing/) (because currently there is only information about testing Queries and Mutations)

**Comment by hwillson** [comment]
Issues here are reserved for React Apollo bugs. Would you mind opening this request over in the [Apollo Feature Request repo](https://github.com/apollographql/apollo-feature-requests)? Thanks!
