### ISSUE TITLE
Execute function of useLazyQuery should resolve FetchResult

### ISSUE THREAD

**Issue by tz5514** [apollographql/react-apollo#3371]
Hi, I just tried `useLazyQuery` for triggering query imperatively, and I found that the "execute function" would not resolve query result, but resolve with `undefined`.
This behavior make developer can't get query result by await the execute function. 

For example, if I want to imperatively trigger query in a `handleClick` function and instantly use this result to do some calculating or logic, we can't.

In addition, since `useMutation` has a similar returning API with `useLazyQuery` and Mutate function *will* resolve fetch result, and same on `refetch` function of `useQuery`.   I think `useLazyQuery` should has similar behavior.

![image](https://user-images.githubusercontent.com/6021943/63088005-38254400-bf86-11e9-967b-5f1917bada00.png)

![image](https://user-images.githubusercontent.com/6021943/63088339-3b6cff80-bf87-11e9-89ea-d7e3ff55b605.png)

Thanks!

**Comment by hwillson** [comment]
Issues here are reserved for React Apollo bugs. Would you mind opening this request over in the [Apollo Feature Request repo](https://github.com/apollographql/apollo-feature-requests)? Thanks!

**Comment by srijanrana** [comment]
I am facing the same issue as well. Please help
