### ISSUE TITLE
useQuery prevents from using `cache-and-network` fetchPolicy

### ISSUE THREAD

**Issue by wtrocki** [apollographql/react-apollo#3374]
Looks like there is an undocumented feature that updates `cache-and-network` policy to use cache only. When using hooks by default and persisting state there is no way to actually make network requests in the app without separate call.

**Comment by scf4** [comment]
I think I'm having this same issue:

https://spectrum.chat/apollo/apollo-client/changing-fetchpolicy-seems-to-have-no-effect~f951efd0-10ee-4f1c-90b8-707c4903c6be

**Comment by scf4** [comment]
I'm not familiar with the Apollo codebase, but it looks like this memoization is causing it:

```typescript
 const result = useDeepMemo(
    () => (lazy ? queryData.executeLazy() : queryData.execute()),
    memo
  );
```

https://github.com/apollographql/react-apollo/blob/master/packages/hooks/src/utils/useBaseQuery.ts#L38

**Comment by scf4** [comment]
This is a problem on my end, and I'm assuming your setup is the same.

You must use:

```typescript
ssrMode: typeof window === 'undefined',
```

rather than `ssrMode: true`

Such a silly mistake 😳

**Comment by hwillson** [comment]
@wtrocki Is this still an issue? Any chance you could provide a small runnable reproduction that shows this?

**Comment by wtrocki** [comment]
Same as above. Somehow ssr mode was set to true - despite not using this at all. 
Closing as I cannot reproduce that now.
