### ISSUE TITLE
onCompleted just called 1 or 2 times when use pollInterval

### ISSUE THREAD

**Issue by BurnhamZhang** [apollographql/react-apollo#3383]
**Intended outcome:**

**Actual outcome:**

**How to reproduce the issue:**

**Version**

![截屏2019-08-17下午6 45 18](https://user-images.githubusercontent.com/5702449/63210330-7ace5400-c11f-11e9-83fb-ff286f727aae.png)
![截屏2019-08-17下午6 45 03](https://user-images.githubusercontent.com/5702449/63210345-ce40a200-c11f-11e9-909f-4d2de2105dc5.png)

**Comment by kchamberlain-rms** [comment]
👍 on this, still looking for a workaround.

**Comment by hwillson** [comment]
This should be fixed by https://github.com/apollographql/react-apollo/pull/3461, and available in 3.1.0. Thanks!
