### ISSUE TITLE
useQuery side effect

### ISSUE THREAD

**Issue by WillSquire** [apollographql/react-apollo#3389]
Just migrated from `react-apollo-hooks` and a query that was triggering a rerender previously has stopped working. It uses react's `useEffect` hook to detect changes for an array returned from the query. The initial query is fine of course and `fetchMore` is working too (as I'm spreading the items into a new array), however if I change the variables for the query it returns the results without detecting a new array?

**Comment by vinaybedre** [comment]
@WillSquire How did you solved it?

**Comment by ivdma** [comment]
@WillSquire Yeah I am curious as well
