### ISSUE TITLE
In v3, neither Mutation component nor useMutation hook give access to the client

### ISSUE THREAD

**Issue by htulipe** [apollographql/react-apollo#3391]
**Intended outcome:**

[The documentation says](https://www.apollographql.com/docs/react/api/react-hooks/#usemutation) we can access the client instance from Mutation component (or useMutation hook). It is no longer the case since v3.

I just updated from v2 to v3 and part of my tests are failing. More precisely, tests that run on code using mutations then access the client instance given by the Mutation component (or the useMutation hook)

**Actual outcome:**

Right now I get errors such as `TypeError: Cannot read property 'readQuery' of undefined`. Those errors are thrown when manipulating the client instance usually given by the Mutation component.
 
**How to reproduce the issue:**

See this minimal reproduction project:
https://github.com/htulipe/react-apollo-mutation-client-bug

**Version**

  System:
    OS: macOS 10.14.5
  Binaries:
    Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.14.2/bin/npm
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 68.0.2
    Safari: 12.1.1
  npmPackages:
    apollo-cache-inmemory: ^1.5.1 => 1.6.3
    apollo-client: ^2.5.1 => 2.6.4
    apollo-link: ^1.2.11 => 1.2.12
    apollo-link-error: ^1.1.10 => 1.1.11
    apollo-link-http: ^1.5.14 => 1.5.15
    "@apollo/react-hooks": "^3.0.1"

Thanks!

**Comment by htulipe** [comment]
Contrary to what initally reported, the bug also appears on an actual provider, it is not limited to MockedProvider. I updated the issue accordingly.

**Comment by ridergoster** [comment]
maybe link to my issue ? #3366

**Comment by htulipe** [comment]
My bad, you're right.
