### ISSUE TITLE
useQuery error is undefined if another useQuery polls changed data

### ISSUE THREAD

**Issue by AlexandrKrivosheev** [apollographql/react-apollo#3399]
**Intended outcome:**

Display useQuery error

**Actual outcome:**

useQuery error is undefined

**How to reproduce the issue:**

https://github.com/AlexandrKrivosheev/apollo-poll-undefined-error-example

use query X that returns error, use query Y that polls changed data (like current time)
query X error becomes undefined when Y query polled changed data

**Version**

  System:
    OS: macOS 10.14.6
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v10.15.3/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 76.0.3809.100
    Safari: 12.1.2
  npmPackages:
    apollo-cache-inmemory: ^1.6.3 => 1.6.3 
    apollo-client: ^2.6.4 => 2.6.4 
    apollo-link-http: ^1.5.5 => 1.5.5 
    react-apollo: ^3.0.1 => 3.0.1

**Comment by hwillson** [comment]
This should be fixed by https://github.com/apollographql/react-apollo/pull/3419 and is available in React Apollo 3.1.0. Thanks!
