### ISSUE TITLE
Component data not recovering after a fail at initialization

### ISSUE THREAD

**Issue by pschupp01** [apollographql/react-apollo#340]
I have this bug on my app which cause some components to not be able to receive any props.

## Steps to Reproduce

Just run the tests added in the branches below:
  react-apollo: https://github.com/pschupp01/react-apollo/tree/recover-after-failed-query
  apollo-client: https://github.com/pschupp01/apollo-client/tree/repro-init-on-error-bug

### Buggy Behavior

If a component initialize with a query and that query return a graphQL error the component's data can't be updated even after the query is refetched.

 The test on apollo-client shows that after a first query return an error, the refetch of this query is still able to get the results correctly.

 The tests on react-apollo show two things:
  1. If the first query succeed and the refetch query receive an error, then the next refetch is still able to update the component props.
  2. If the first query receive an error, then the refetch is not able to update the component props

### Expected Behavior

  After the first query receive an error a refetch should be able to update the component props.

### Version
- apollo-client@0.6.0
- react-apollo@0.5.6

**Comment by pschupp01** [comment]
I'll try to find a fix for this bug. But i'm not really familiar with apollo's codebase.

**Comment by tmeasday** [comment]
The tests look generally good (with some comments). Are you saying all tests are failing in current AC / RA?
