### ISSUE TITLE
The `query` HOC does not update on `refetch` in Apollo 3

### ISSUE THREAD

**Issue by dchambers** [apollographql/react-apollo#3403]
Refetching (whether via `refetch` or `refetchQueries`) does cause:

1. A refetch within the network tab.
2. The cache to be updated using the refetched data.
3. The query to re-render based on the updated cache.

but does not directly make use of the update, such that updated lists are now ignored. This all worked fine in Apollo 2 OTOH.

Bizarrely, changing the `fetchPolicy` to `network-only` (which should have no affect given that the data was already being fetched using the default policy) did work around this bug 😕. Something similar was noted in #2827 back in January, so these incorrect consequences from changing the `fetchPolicy` seem to be a pre-existing bug that pre-dates Apollo 3.

**Comment by robbert229** [comment]
I have also encountered similar behavior but with the subscription HOC and subscription hooks. With both I have noticed that the apollo devtools shows that the cache has been updated, while the component itself hasn't rerendered. Will include some details momentarily.

**Comment by hwillson** [comment]
@dchambers Can you re-test using React Apollo 3.1.0 and let us know if this is still an issue? Thanks!

**Comment by hwillson** [comment]
I believe this should be fixed in 3.1.0, but let us know if it isn't. Thanks!
