### ISSUE TITLE
Implement suspense on useQuery

### ISSUE THREAD

**Issue by lstanden** [apollographql/react-apollo#3408]
I'm attempting to migrate from `react-apollo-hooks` to `@apollo/react-hooks` and running into a bunch of issues due to the missing Suspense support.  It would be great if the suspense flag could be incorporated.

For context, suspense simply means that the `{loading}` state is irrelevant, and the `useQuery` call will throw a promise in the event a query has not finished executing.

**Comment by zicodeng** [comment]
Feature request here: https://github.com/apollographql/apollo-feature-requests/issues/162, but it hasn't attracted much attention 😞

**Comment by hwillson** [comment]
Let's continue the discussion over in https://github.com/apollographql/apollo-feature-requests/issues/162 (but in a nutshell: we're waiting for the React team to finalize suspense + data fetching support before getting it implemented).
