### ISSUE TITLE
beta test major releases [EDIT: list beta releases in changelog/publicize betas to all users]

### ISSUE THREAD

**Issue by jedwards1211** [apollographql/react-apollo#3420]
After upgrading to 3.1.0 and doing some fairly major refactoring, I got burned by #3366.  I think this is the kind of issue that could have been caught by beta releases/release candidates coming out before the official major 3.0 release.

EDIT: I noticed when going through GitHub releases that there were beta releases for 3.0.0. However, they were not included in the changelog.  As far as I have seen, putting information about beta releases in changelogs is common practice.

Also, perhaps the beta release should have been publicized to all users to help catch more regressions (doesn't look like there are any blog entries about it?)

**Comment by hwillson** [comment]
@jedwards1211 We're always looking for ways to improve beta testing, so thanks for the feedback. Actually, we're working on new Apollo-wide changes to the way we build and release all Apollo libraries. As an example, see https://github.com/apollographql/apollo-server/pull/3246. One great benefit of this new process is that every PR submitted will have a prepped tarball available, that can be `npm install`ed directly. This should make it really easy for people to test new PR changes, and actually use those changes if they don't want to wait for an official release. I've made a note of your comments, and will bring them up internally as part of this work. Thanks again!
