### ISSUE TITLE
MutationFunction TypeScript type incorrect in react-components

### ISSUE THREAD

**Issue by Mike-Gibson** [apollographql/react-apollo#3432]
The type `MutationFunction` used in react-components returns a `Promise<void | MutationFetchResult<TData>>` which makes it hard to use the result without first checking the result is defined. 

This was discussed in #2095 and a fix was made for react-hooks in #3334 but the issue still remains in react-components.

As far as I'm aware, it would make sense that the mutation function does not return void in both  react-hooks _and_ react-components.

The type is defined here:
https://github.com/apollographql/react-apollo/blob/3c961c3a944350fa7b17119ab822177e4a8216e3/packages/common/src/types/types.ts#L140-L145

This occurs in react-apollo 3.0.1.

**Comment by rerissondaniel** [comment]
+1
