### ISSUE TITLE
@apollo/react-testing will always raise an error when using newData

### ISSUE THREAD

**Issue by zombiezen** [apollographql/react-apollo#3455]
tl;dr: I believe these lines are wrong: https://github.com/apollographql/react-apollo/blob/3c05b08ada16ea427d7fece649f48736734b55a7/packages/testing/src/mocks/mockLink.ts#L90-L101

IIUC the assignment on line 90 should be moved to after the `if (newData)` conditional.

**Intended outcome:**

Use the `newData` function in a `MockLink` response.

**Actual outcome:**

Error thrown: `Mocked response should contain either result or error`

**How to reproduce the issue:**

Try to mock a response with:

```javascript
const fakeData = [
  {
    request: {query: QUERY},
    newData: () => ({data: { /* ... */ }})
  }
];
const link = new MockLink(fakeData);
```

**Version**

```
  System:
    OS: Linux 4.4 Debian GNU/Linux 9 (stretch) 9 (stretch)
  Binaries:
    Node: 8.15.0 - /usr/bin/node
    Yarn: 1.16.0 - ~/bin/yarn
    npm: 6.4.1 - /usr/bin/npm
  npmPackages:
    apollo-boost: ^0.4.4 => 0.4.4
```

**Comment by pawelkleczek10c** [comment]
I have the same issue

**Comment by hwillson** [comment]
Fixed in https://github.com/apollographql/react-apollo/pull/3539 (new version coming soon). Thanks @zombiezen @pawelkleczek10c!
