### ISSUE TITLE
Didn't update state on @apollo/react-hooks@3.0.1

### ISSUE THREAD

**Issue by tomasgoodas** [apollographql/react-apollo#3456]
**Previous and current options every time should be to equal?**
https://github.com/apollographql/react-apollo/blob/master/packages/hooks/src/data/OperationData.ts#L34

**On this line checking current and previous values**
https://github.com/apollographql/react-apollo/blob/master/packages/hooks/src/data/QueryData.ts#L427

**Comment by hwillson** [comment]
@tomasgoodas I'm not quite sure what the issue is you're reporting. Can you provide a small runnable reproduction that clearly demonstrates the problem?
