### ISSUE TITLE
Invalid type for QueryResult#data

### ISSUE THREAD

**Issue by rothfels** [apollographql/react-apollo#3483]
**Intended outcome:**

Code like this:

```
interface MyQuery {
  requiredField: string
}

<Query query={myQueryFetcher}>
  {(res: QueryResult<MyQuery>) => <div>{res.data == null}</div>}
</Query>
```

Your typings say the type of `res.data` is `MyQuery | undefined`

**Actual outcome:**

The type of `res.data` is *actually* `MyQuery | undefined | {}`. It is `undefined` if you use the `skip` param, `{}` if the query is loading, and `MyQuery` if it's been resolved.

The mistyped value can lead to NPEs if the developer does something like this:

```
if (res.data != null) {
  willThrowWhenUndefinedArg(res.data.requiredField)
}
``` 

**How to reproduce the issue:**

See example code above.

**Version**

```
  System:
    OS: macOS 10.14.6
  Binaries:
    Node: 9.11.1 - ~/.nvm/versions/node/v9.11.1/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v9.11.1/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 68.0.2
    Safari: 12.1.2
  npmPackages:
    apollo-cache-inmemory: ^1.6.2 => 1.6.2 
    apollo-client: ^2.6.4 => 2.6.4 
    apollo-codegen: ^0.20.2 => 0.20.2 
    apollo-link: ^1.2.11 => 1.2.11 
    apollo-link-context: ^1.0.17 => 1.0.17 
    apollo-link-error: ^1.1.10 => 1.1.10 
    apollo-link-http: ^1.5.14 => 1.5.14 
    react-apollo: ^2.5.6 => 2.5.6 
```

**Comment by hwillson** [comment]
@rothfels Regarding

> {} if the query is loading

this is no longer the case, as of React Apollo 3.1.0. Which version of React Apollo are you using - your `envinfo` output says 2.5.6, and if that's the case updating to 3.1.0 should help. I'll close this for now since this should be resolved in 3.1.0, but let me know otherwise. Thanks!
