### ISSUE TITLE
fetchMore doesn't trigger re-rendering component after executed updateQuery

### ISSUE THREAD

**Issue by tndinhbao** [apollographql/react-apollo#3487]
**Intended outcome**:
The component will be triggered to re-render with data is the result of ### updateQuery function

**Actual outcome**:
The component is only triggered if the network status has changed, before executing the updateQuery function. The data which is composed by **updateQuery** is not "passing" to the data field of the query result.
The app only render the latest query data if any other state in the component changed.

here are some main parts of this process:
```
const MyComponent = (props) => {
  const hotelQueryResult = useQuery(
    SEARCH_HOTEL_QUERY,
    {
      variables: <some-variables-here>,
      notifyOnNetworkStatusChange: true
    }
  );
  
  ...
  
  function functionUseToFetchMore() {
    const currentTotalFetched = (_get(hotelQueryResult.data, "trip.searchProducts.nodes") || []).length;
    if (!hotelQueryResult.loading && currentTotalFetched < totalCount) {
      const nextPage = Math.floor(currentTotalFetched / TOTAL_ITEM_PER_PAGE);
      hotelQueryResult.fetchMore({
        variables: {
          pageNumber: nextPage
        },
        updateQuery: (previousResult: any, { fetchMoreResult }: any) => {
          const currentNodes = _get(previousResult, "trip.searchProducts.nodes");
          const incomingNodes = _get(fetchMoreResult, "trip.searchProducts.nodes");
          return _set(previousResult, "trip.searchProducts.nodes", [...currentNodes, ...incomingNodes]);
        }
      });
    }
  }

  return <map-to-render-data>
}
```

Scenario:
- First run:
data length = 10, component re-rendered

- Trigger fetch more
component re-rendered after network request completed.
after executing `updateQuery`, component is not triggered, `hotelQueryResult.data` is not updated.

**Version**
"@apollo/react-hooks": "^3.0.0",

**Comment by mjasnikovs** [comment]
Or, when you use fetchPolicy= no-cache 🤷

**Comment by Rapsac11** [comment]
> Or, when you use fetchPolicy= no-cache 🤷

Thank you! Had this set and couldn't work out why I wasn't receiving a new update.

**Comment by lenarmazitov** [comment]
I read that this bug was fixed in apollo-client 3 (I did not try it)

If it is need to use **fetchPolicy: no-cache** you can create new state variable and collect items in it as workaround for older versions of apollo-client:

```
const [list, setList] = useState([])
const [nextToken, setNextToken] = useState(undefined)

const { data: { list } = {}, fetchMore } = useQuery(gql(GET_LIST), {
    fetchPolicy: "no-cache",
    skip: !!list,
    onCompleted: (data) => {
      setNextToken(data.list.nextToken)
      setUsersList(data.list.items)
    },
  })

const loadMore = async () => {
    if (!nextToken) {
      return null
    }
    return await fetchMore({
      updateQuery: (previousResult, { fetchMoreResult, variables }) => {
        setNextToken(fetchMoreResult.list.nextToken)
        setUsersList([...usersList, ...fetchMoreResult.list.items])
        return null
      },
    })
  }
```
