### ISSUE TITLE
Persist a subscription after unmount?

### ISSUE THREAD

**Issue by at0g** [apollographql/react-apollo#349]
I may have missed something in the docs, but is there an option to keep a subscription active after the associated component unmounts? What I'd like to have happen is that once a query has been cached, any subscriptions associated with it will continue to update so that it does not become stale if revisited.

Basically I have 2 views (master and detail) and have implemented subscriptions on both.
The views are displayed via independent routes, and I can navigate between them with react-router.
The subscriptions work in 4 of the 5 scenarios below.

Assuming 2 browser windows (a reader and a writer):

_Scenario 1._
If the reader loads the master view, and the writer edits either of the items, the correct item is updated in the reader window.

_Scenario 2._
The reader and writer windows both load the detail view of item 1. The writer edits the item, it is updated in the reader window.

_Scenario 3._
The reader window loads the master view, then navigates using push state to the detail view of item 2.
The writer window loads the detail view of item 2 and then makes an edit.
The reader window updates to reflect the edit as per scenario 2. The reader window then navigates back to the master view (push state) and item 2 also shows the correct/updated item.

_Scenario 4._
The reader loads the detail of item 1, the writer loads the detail of item 2 (no push state/history for either). The writer edits the item, the reader does not update (item 1 !== item 2).
The reader navigates to the master view using push state, (which must load as it is not cached) and then shows the correct result.

_Scenario 5._
As per scenario 4, except that before the writer makes an edit:
- the reader loads the master view (caching the result) as the entry url
- the reader then navigates to item 1 using push state (thus ending it's subscription)

**In scenario 5, when the reader navigates back to the master view after the writer makes an edit to item 2, item 2 displays it's previous / cached values.**

**Comment by tmeasday** [comment]
@at0g would not just using `forceFetch: true` on your master view query solve this problem?

@stubailo FTR this is the kind of bug that makes me not a fan at all of this kind of caching (referencing a discussion of a while back about why I've never been a fan of the subs manager approach). I bet there are a whole host of other subtle issues that you can trigger if you navigate around this fairly simple sounding situation in the right order. This is like my nightmare.

**Comment by at0g** [comment]
Technically using `forceFetch: true` would solve the problem of the stale cache (effectively removing caching). That in turn would mean that every time the master view is visited, it would have to reload (not really what I want). Instead, I've added `pollInterval: 60000` so that the master view will eventually update, but it has fundamentally the same drawbacks as `forceFetch`.

In the scenarios in the OP, Scenario 1 works great and so I'd simply like that subscription to stick around.

I don't know that I would call this a bug, as I think the current behaviour would be desirable in many situations. For those situations where it's not suitable, it would be great to specify an option to adjust the behaviour. Perhaps something like:

```
data.subscribeToMore({
    unsubscribeOnUnmount: true | false
})
```

Perhaps the default value of unsubscribeOnUnmount should be false if `graphql` was not provided with either `forceFetch` or `pollInterval` options.

**Comment by stubailo** [comment]
@tmeasday I mean what you are referring to is essentially a situation where `forceFetch` is true by default right?

I don't think it's fundamentally bad to embrace the concept of a stale cache?

@at0g I don't think having `unsubscribeOnUnmount` is the right way to do this because the subscription will stay alive forever. IMO the right approach is to make sure that queries that are updated via subscriptions are simply refetched after becoming stale.

I think once there is enough data about different use cases for subscriptions, we should put together some more coherent tools around the idea of doing a query and then updating via a subscription. Or, perhaps having better support for something like a live query is the ultimate solution.

**Comment by tmeasday** [comment]
@at0g 

> That in turn would mean that every time the master view is visited, it would have to reload (not really what I want)

Is this from a UI perspective, or from an unnecessary network request perspective?

If the former, I'm pretty sure you can get data while `loading` is still true and simply render anyway.

If the latter, I'm not convinced it's the right tradeoff to keep streaming data you aren't looking at to avoid a single query later, but I guess it depends.

I guess there's also an argument that even if you render the old data, it's still the old data and there will be latency + a FOID[1], which is bad UX. 

However, I don't reckon holding *all* subscriptions ever open is the right call (chances are if you drinking the subs koolaid you ain't using `pollInterval` or `forceFetch` anywhere right? I wouldn't!). I think this is a case-by-case basis kind of situation.

I think maybe that the detail view should just subscribe to the master view's data?

[1] New term I invented. @stubailo can you guess what it is?

**Comment by at0g** [comment]
FOID Flash Of Indeterminate Data - AMIRITE?

@tmeasday 
>> That in turn would mean that every time the master view is visited, it would have to reload (not really what I want)

> Is this from a UI perspective, or from an unnecessary network request perspective?

For the most part, it's the network request - I have the following concerns:

- The items returned have an aggregate field that is moderately expensive to compute on the server.
- The query returns a connection / items are edges, if the master has loaded multiple pages of records, I don't understand how `forceFetch` or `pollInterval` can return an update to a record (especially if the record is from one of the old edges)
- The combination of the above 2 points

Regarding the subs koolaid, yes - I want subs everywhere.
**Given that the cache persists indefinitely, I don't see an issue with a subscription to update that cache having the same lifetime (forever).**

> So I think maybe that the detail view should just subscribe to the master view's data?
Not sure I understand - wouldn't this be akin to closing and opening the subscription on every route rather than keeping it alive?

**Comment by tmeasday** [comment]
I was thinking "flash of incorrect data" but close enough 💯

**Comment by tmeasday** [comment]
> Given that the cache persists indefinitely, I don't see an issue with a subscription to update that cache having the same lifetime (forever). I would at least like the option to do so.

Well I guess I mean if you do it for every single query on your entire site it sounds like a bit of a performance problem.

> Not sure I understand - wouldn't this be akin to closing and opening the subscription on every route rather than keeping it alive? Eg. There's not just a detail view, but other routes will cause the issue from the OP.

Is there a big hit in opening and closing it rather than keeping it open? In any case, I think it wouldn't be to hard to write a little reference counting library that does this (or maybe AC could do this bit somehow)

**Comment by helfer** [comment]
@at0g I think a workable solution for you would be to just run the query and subscription manually and update the query when the subscription data comes in. That way you're in full control of which queries are active and which ones aren't, and it's not tied to whether the component is currently rendered on screen.

However, I would first implement the simplest possible solution (which is to just refetch every time) and then see if that's really not good enough.
