### ISSUE TITLE
Upgrade React and Jest Presets

### ISSUE THREAD

**Issue by johnthepink** [apollographql/react-apollo#352]
We are currently locked at react 15.4.0-rc2. Upgrading to 15.4.1 introduced an issue on the CI with importing "React" vs "react". See [this comment](https://github.com/facebook/jest/issues/1840#issuecomment-263004102).

Using the jest preset included in react-native since 0.38 actually fixed this issue, and cleaned up a lot of logging, but caused tests to fail that were making actual network requests, see this [travis build](https://travis-ci.org/apollostack/react-apollo/jobs/180606263)

We should figure out the network issue and update react all the way.

**Comment by jbaxleyiii** [comment]
@johnthepink this should actually pretty really easy now that we are using jest. I'll try to mock those responses this weekend 👍

**Comment by johnthepink** [comment]
@jbaxleyiii oh sweet! I thought about doing that, but wasn't sure if we wanted the actual network requests.

**Comment by johnthepink** [comment]
I like mocking them better
