### ISSUE TITLE
How to dynamically evaluate GraphQL queries?

### ISSUE THREAD

**Issue by gajus** [apollographql/react-apollo#3529]
I have `MovieComparison` component that receives props:

```js
type PropsType = {|
  +movieIds: $ReadOnlyArray<string>,
|};

```

i.e. an array of movie IDs.

I also have a query that returns information about movie if you provide movie ID, i.e.

```js
gql`
  query UserQuery (
    $movieId: ID!
  ) {
    getMovieById (id: $movieId) {
      id
      name
    }
  }
`

```

I cannot figure out how to execute a multiple number of GraphQL queries based on an input, i.e.

```js
const MovieComparison = (props) => {
  const movies = useQuery(gql``, {
    variables: {
      movieIds: props.movieIds,
    }
  });

  // [..]
};

```

What is the correct solution?

**Comment by dylanwulf** [comment]
Would it be possible to change the server to return an array of movies instead of a single movie?

**Comment by gajus** [comment]
> Would it be possible to change the server to return an array of movies instead of a single movie?

No.

I ended up using Apollo client directly.
