### ISSUE TITLE
useMutation not exported from react-apollo

### ISSUE THREAD

**Issue by serendipity1004** [apollographql/react-apollo#3554]
https://www.apollographql.com/docs/react/migrating/hooks-migration/ here it says that all three packages (hoc, components, hooks) can be used together in react-apollo package.

I have `react-apollo 3.1.2` installed and when I try to import useMutation like below

`import {useMutation} from 'react-apollo'`

I get `Attempted import error: 'useMutation' is not exported from 'react-apollo'.`

How do I properly import `useMutation` hook from `react-apollo` package? I need to use both component and hooks together for a while until all the migrations are done.

**Comment by pcorey** [comment]
Are you sure you're using `react-apollo@3.1.2`? Try using `yarn why react-apollo`, or dig into your `yarn.lock` to see which version you're resolving to.

I don't see a `3.1.2` tag in this repo, but it looks like the latest `master` is [exporting `useMutation` from `@apollo/react-hooks`](https://github.com/apollographql/react-apollo/blob/master/packages/all/src/index.ts#L62), and [`@apollo/react-hooks` is exporting `useMutation`](https://github.com/apollographql/react-apollo/blob/master/packages/hooks/src/index.ts#L10) from itself, which [seems to exist](https://github.com/apollographql/react-apollo/blob/master/packages/hooks/src/useMutation.ts#L8-L36). /shrug

**Comment by serendipity1004** [comment]
@pcorey yes package version was the problem. Thanks
