### ISSUE TITLE
useQuery doesn't update props (`data`, `loading`) if the query string is updated but the result is exactly the same

### ISSUE THREAD

**Issue by itajaja** [apollographql/react-apollo#3622]
**Intended outcome:**

useQuery should always resolve to either error or data

**Actual outcome:**

if the returned payload in two different queries is the same, useQuery  never resolves error or data, and loading is always true. I checked the dev tools, the http request indeed completes.

**How to reproduce the issue:**

```js
const [query, setQuery] = useState(gql`{ query { foo(bar: 1) } }`);
const { loading } = useQuery(myQuery);

// in a callback I do:

const setQuery(gql`{ query { foo(bar: 2) } }`);
```

if the result of both queries happen to be exactly the same, then data and loading are never updated, I believe this has to do with `useDeepMemo`, but I might be wrong.

**Version**

```
  System:
    OS: macOS 10.15
  Binaries:
    Node: 12.12.0 - ~/.nvm/versions/node/v12.12.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v12.12.0/bin/npm
  Browsers:
    Chrome: 77.0.3865.120
    Firefox: 69.0
    Safari: 13.0.2
  npmPackages:
    @apollo/react-hooks: ^3.1.3 => 3.1.3
    apollo-boost: ^0.4.4 => 0.4.4
    apollo-link-http: ^1.5.16 => 1.5.16
```

**Comment by dylanwulf** [comment]
Could be related to #3425

**Comment by itajaja** [comment]
I think that's it! thanks @dylanwulf
