### ISSUE TITLE
Error handling not working with errorPolicy: 'all'

### ISSUE THREAD

**Issue by vyrruss** [apollographql/react-apollo#3625]
**Intended outcome:**

With option `{ errorPolicy: 'all' }` should be able to access `graphQLErrors` from `useQuery` hook returns.
Like the docs example: [here](https://www.apollographql.com/docs/react/data/error-handling/#error-policies)

**Actual outcome:**

Want to access `graphQLErrors` in my component from `useQuery` hook but return the message error instead of object even with `{ errorPolicy: 'all' }`

![image](https://user-images.githubusercontent.com/8026576/67595263-85801780-f766-11e9-860f-ce29bb07f8da.png)

**How to reproduce the issue:**

https://codesandbox.io/s/react-apollo-errors-ez47m

**Version**

Even with the latest version, got the same results

```
System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.70
    Firefox: 69.0.1
    Safari: 13.0.2
  npmPackages:
    @apollo/react-components: ^3.1.1 => 3.1.1 
    apollo-cache-inmemory: ^1.6.0 => 1.6.3 
    apollo-client: ^2.6.0 => 2.6.4 
    apollo-link: ^1.2.11 => 1.2.13 
    apollo-link-context: ^1.0.17 => 1.0.19 
    apollo-link-error: ^1.1.10 => 1.1.12 
    apollo-link-http: ^1.5.14 => 1.5.16 
    apollo-upload-client: ^11.0.0 => 11.0.0 
```

**Comment by raniel12345** [comment]
How did you fix this issue on your code?

**Comment by njbarrett** [comment]
What was the resolution?
