### ISSUE TITLE
Docs inconsistent about `errorPolicy`

### ISSUE THREAD

**Issue by lensbart** [apollographql/react-apollo#3643]
Greetings comrads

[Example `defaultOptions` object](https://www.apollographql.com/docs/react/api/apollo-client/#example-defaultoptions-object) mentions `errorPolicy` as a default option for the `mutate` function, whereas the [useMutation options](https://www.apollographql.com/docs/react/data/mutations/#options) in the useMutation API don’t include `errorPolicy` — but this hook returns a mutation function as well, so is supposed to have the same config shape, no?

**Comment by Auchindoun** [comment]
I don't think `useMutation` supports `errorPolicy`. I found this out the hard way.

**Comment by lensbart** [comment]
You’re right, it doesn’t!

**Comment by Jayphen** [comment]
The types for useMutation indicate that it does support `errorPolicy`. 

useMutation is typed with `OperationVariables` as the second parameter: https://github.com/apollographql/react-apollo/blob/master/packages/hooks/src/useMutation.ts#L8 

`OperationVariables` has an `errorPolicy` type https://github.com/apollographql/react-apollo/blob/master/packages/common/src/types/types.ts#L34
