### ISSUE TITLE
useLazyQuery cache access 

### ISSUE THREAD

**Issue by Adam-Burke** [apollographql/react-apollo#3655]
Hi,

If data is available in `InMemoryCache` then the following seems to occur.

On first render `useLazyQuery` returns `{loading: false, data: undefined}.`
On first render `useQuery` returns `{loading: false, data: **DataFromCache**}.`

Just wondering if it is possible for these to behave the same way? Otherwise it means there is an additional state to consider when you `useLazyQuery` aside from `loading` | `error` | `dataPopulated`.

**Comment by FredyC** [comment]
Well, the `useLazyQuery` includes `called` property that reflects exactly that. It certainly cannot behave the same way, what would be the purpose of `useLazyQuery` if it would execute right?

**Comment by Adam-Burke** [comment]
I see your point.

**Comment by kgregory** [comment]
@FredyC Is there a way to get `useLazyQuery` to return cached data before being `called`?

There are some use cases where I'd like the ability to execute a query on demand, but start with the cached results.  Something like this:

```
const { data: cachedData } = useQuery(MyQuery, { fetchPolicy: 'cache-first', variables });
const [executeMyQuery, { data: queryData, loading, error }] = useLazyQuery(MyQuery);
const data = queryData || cachedData;
```

**Comment by FredyC** [comment]
So just call that query with useEffect on mount, what's the problem? It won't get any faster.,

**Comment by kgregory** [comment]
@FredyC For my use case, I want to issue a query on demand, but if I've already done it, I'd like to present the results.  I was wondering if `useLazyQuery` could be configured to return results from the cache initially, but the combination of a cache-only `useQuery` and a network-only `useLazyQuery` seems to be working for now.

**Comment by FredyC** [comment]
Still applies what I've said. You can utilize `useRef` to remember you have requested data initially and combine that with `useEffect` that checks for that flag, calls lazy query handler and sets the flag. Nothing spectacular about it really. Having both hooks there feels like overkill, but your choice.

**Comment by david-a** [comment]
> Still applies what I've said. You can utilize `useRef` to remember you have requested data initially and combine that with `useEffect` that checks for that flag, calls lazy query handler and sets the flag. Nothing spectacular about it really. Having both query hooks there feels like overkill, but your choice.

@FredyC I think he wants to bring fresh data each time but show the previous data in the meanwhile. Your suggestion, if I understand it right, will only help in fetching the data once then show this data forever.

I've managed to do a smaller (and IMHO better but still a) hack in order to achieve the behaviour @kgregory wants. It goes something like -

```
const [cachedData, setCachedData] = useState();
const [executeMyQuery, { data: queryData, loading, error }] = useLazyQuery(MyQuery)
 useEffect(() => {
    if (queryData) {
      setCachedData(queryData);
    }
  }, [loading, queryData]);
```

Then just use `cachedData` wherever you need that data.

though I still don't quite understand why can't we have a config for `useLazyQuery` to allow showing the previous results while fetching new ones, much like in `useQuery`.

**Comment by FredyC** [comment]
@david-a That's basically what I have said 😆 Except you have `useState` instead of `useRef` which you will cause another unnecessary re-render. To keep the previous result, ref is enough.

**Comment by david-a** [comment]
@FredyC Oh, ok.. my bad. I thought when you wrote "flag" you meant to setting a flag that says you already fetched the data and never fetch it again. So now I guess you meant something like this:

```
const cachedData = useRef(null);
const [executeMyQuery, { data: queryData, loading, error }] = useLazyQuery(MyQuery)
 useEffect(() => {
    if (queryData) {
      cachedData.current = queryData;
    }
  }, [loading, queryData]);
```

Then use `cachedData.current` wherever you need that data.
right?

**Comment by david-a** [comment]
Just tried it, apparently whenever you need the data you should now use `queryData 
 || cachedData.current` since no re-render will occur after updating the `cachedData`

**Comment by FredyC** [comment]
This is my approach

```ts
import React from 'react'

/**
 * Utility hook that will remember previous result and
 * return it next time when next data are being fetched.
 *
 * The function to retrieve stashed data is returned which initially will
 * return `null` until some data are fetched for the first time.
 *
 * Function is always recreated so don't use it as dependency for effects,
 * memo or callbacks, use it in outer scope and depend on data directly.
 *
 * The resolver function needs to be supplied which gets `data` and should either return
 * whole `data` (the `RM.identity` is really useful) or directly select some field.
 * The resolver is executed only when `data` is available thus no checks are necessary.
 *
 * Optionally, second argument `shouldSkip` can be specified denoting that query was skipped.
 * That will forcefully clear previous cache and return `null`.
 *
 * @param loading
 * @param data
 */
export function useLoadingStash<TData>(
  loading: boolean,
  data: TData | undefined,
) {
  const cached = React.useRef<unknown | null>(null)

  const buildResult = <TResult = TData>(
    resolver: (data: TData) => TResult,
    shouldSkip: boolean = false,
  ): TResult | null => {
    if (shouldSkip) {
      cached.current = null
      return null
    }
    if (loading) {
      return cached.current as TResult | null
    } else if (data === undefined) {
      return null
    } else {
      const next = resolver(data)
      cached.current = next
      return next
    }
  }

  return buildResult
}
```

I am using it internally in customized `useQuery` / `useLazyQuery` and exposing as `getStash` method. I can then do simply `const user = getStash(R.prop('user'))`

**Comment by kgregory** [comment]
>Still applies what I've said. You can utilize useRef to remember you have requested data initially and combine that with useEffect that checks for that flag, calls lazy query handler and sets the flag. Nothing spectacular about it really. Having both query hooks there feels like overkill, but your choice.

That works if my component remains mounted, but my component will be unmounted on a route change and anything stored in the ref will be lost.  My ideal scenario be that `useLazyQuery` initially returns the data from the cache.  Since it doesn't do that, I'm using `useQuery` to get the cached data and `useLazyQuery` for on demand access.

I'm sure there's a better way than what I've come up with.

**Comment by david-a** [comment]
> This is my approach
> 
> ```ts
> import React from 'react'
> 
> /**
>  * Utility hook that will remember previous result and
>  * return it next time when next data are being fetched.
>  *
>  * The function to retrieve stashed data is returned which initially will
>  * return `null` until some data are fetched for the first time.
>  *
>  * Function is always recreated so don't use it as dependency for effects,
>  * memo or callbacks, use it in outer scope and depend on data directly.
>  *
>  * The resolver function needs to be supplied which gets `data` and should either return
>  * whole `data` (the `RM.identity` is really useful) or directly select some field.
>  * The resolver is executed only when `data` is available thus no checks are necessary.
>  *
>  * Optionally, second argument `shouldSkip` can be specified denoting that query was skipped.
>  * That will forcefully clear previous cache and return `null`.
>  *
>  * @param loading
>  * @param data
>  */
> export function useLoadingStash<TData>(
>   loading: boolean,
>   data: TData | undefined,
> ) {
>   const cached = React.useRef<unknown | null>(null)
> 
>   const buildResult = <TResult = TData>(
>     resolver: (data: TData) => TResult,
>     shouldSkip: boolean = false,
>   ): TResult | null => {
>     if (shouldSkip) {
>       cached.current = null
>       return null
>     }
>     if (loading) {
>       return cached.current as TResult | null
>     } else if (data === undefined) {
>       return null
>     } else {
>       const next = resolver(data)
>       cached.current = next
>       return next
>     }
>   }
> 
>   return buildResult
> }
> ```
> 
> I am using it internally in customized `useQuery` / `useLazyQuery` and exposing as `getStash` method. I can then do simply `const user = getStash(R.prop('user'))`. I like this lazy approach which gives me data more resilient.

Seems good, just still I haven't understood why isn't this the default useLazyQuery behavior...
