### ISSUE TITLE
network-only returns a cached value for a different query

### ISSUE THREAD

**Issue by Falieson** [apollographql/react-apollo#3684]
With 
    "@apollo/react-hooks": "3.0.0",

I make a useQuery request in one component, and then another makes a useQuery request,  whichever resolves last then becomes the value of the other component. They are different queries!

my client is configured for "network-only", adding "no-cache" option to useQuery fixed the issue.

Someone else posted the solution 8 days ago on this closed thread: https://github.com/apollographql/react-apollo/issues/556

**Comment by dylanwulf** [comment]
I think this is actually intentional behavior. Looking at the docs for `network-only`:
> This fetch policy will never return you initial data from the cache. Instead it will always make a request using your network interface to the server. This fetch policy optimizes for data consistency with the server, but at the cost of an instant response to the user when one is available.

I think the keyword here is _initial_. It will not return _initial_ data from the cache. But once the initial data has been returned, network-only queries are subscribed to the cache and receive updates from the cache.

**Comment by Falieson** [comment]
The problem I am having is that the useQuery hook is returning the cache update of a different query.

**Comment by dylanwulf** [comment]
I agree that that behavior is unexpected and (in most cases) unwanted. But I don't think it counts as a bug. Maybe you could file an issue over at https://github.com/apollographql/apollo-feature-requests/issues ?

**Comment by Falieson** [comment]
So the intended usage of `useQuery(query, options)` is to return the last value returned by any currently running instance of the hook? They don't register a new cache-id per query?
Essentially, out-of-the-box you can't ever use more than 1 useQuery at a time per view?

**Comment by Falieson** [comment]
I'm going to update the description here to say that this is an issue w/ 3.0.0 , I'm getting an issue that makes me believe I may not have rebuilt my dev server w/ 3.1.3 like I thought.

**Comment by dylanwulf** [comment]
You can definitely use more than 1 `useQuery` at a time. But if you use multiple `useQuery`s that fetch _the same data_ at the same time, then they will update each other. That's how the cache works.

**Comment by Falieson** [comment]
thanks dylan, that actually is very helpful in my understanding. I'm going to close this since its an old version, hopefully others will find this discussion helpful
