### ISSUE TITLE
useLazyQuery - onCompleted callback is called on every re-render.

### ISSUE THREAD

**Issue by MalikBagwala** [apollographql/react-apollo#3690]
Hey guys. I used `useLazyQuery` in my modal dialog

here is the code 
```
 const [inwardState, changeInwards] = useState([]);
  const parsedState = useMemo(() => {
    return inwardState.map(i => ({
      ...i,
      quality: i.quality ? i.quality : {}
    }));
  }, [inwardState]);
  const [getInwards, { error }] = useLazyQuery(BOOKING_QUALITY, {
    variables: {},
    onCompleted: data => {
      const inwards = get(data, "bookingDetails.inwards");
      const parsed = inwards.map(i => ({
        ...i,
        quality: i.quality ? i.quality : {}
      }));
      changeInwards(parsed);
    }
  });

const handleOpened = () => {
    getInwards({ variables: { id: booking.id } });
  };
```

The app crashes showing the following message

`Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`

However, removing the part
```
const parsed = inwards.map(i => ({
        ...i,
        quality: i.quality ? i.quality : {}
      }));
```

resolves this issue.

I am unable to understand the inconsistant behavior

**Comment by dylanwulf** [comment]
This sounds a lot like #3505. Are you using react-apollo v3.1.3?

**Comment by MalikBagwala** [comment]
@dylanwulf  No, I am using this package to be particular `@apollo/react-hooks@3.1.2`

**Comment by dylanwulf** [comment]
If you look at the last comment in #3505 you'll see that this issue was fixed in v3.1.3

**Comment by MalikBagwala** [comment]
I was able to fix this after upgrading the `@apollo/react-hooks` package to version `3.1.3`. Thanks a lot @dylanwulf

**Comment by MalikBagwala** [comment]
I was able to fix this after upgrading the @apollo/react-hooks package to version 3.1.3. Thanks a lot @dylanwulf
