### ISSUE TITLE
How to make components re-subscribe after websocket disconnect?

### ISSUE THREAD

**Issue by AlexLeung** [apollographql/react-apollo#371]
When using subscription queries, I've noticed that if I kill the websocket connection, the connection is never reestablished. What code do I need to add, and where, in order to prompt resubscribes?

**Comment by helfer** [comment]
@AlexLeung According to this [PR](https://github.com/apollostack/subscriptions-transport-ws/pull/31) you should be able to pass `reconnect: true` as an option when you construct the subscription client (i.e. it's not an option on the subscription, but on the websocket client).
