### ISSUE TITLE
Changing options while unskipping leads to unnecessary query.

### ISSUE THREAD

**Issue by tmeasday** [apollographql/react-apollo#381]
This [line](https://github.com/apollostack/react-apollo/blob/7eae575d4cf66b6c934fd34ce0db4f337fd6800d/test/react-web/client/graphql/queries.test.tsx#L524) should not be necessary.

The explanation is (copied from [here](https://github.com/apollostack/react-apollo/pull/376#issuecomment-268689798)):

1. We unsubscribe (when skipping).
2. We change the variables, which triggers a `fetchQuery` [here](https://github.com/apollostack/apollo-client/blob/master/src/core/ObservableQuery.ts#L301)
3. Immediately, we re-subscribe, which triggers the `ObservableQuery` to re-fetch [here](https://github.com/apollostack/apollo-client/blob/master/src/core/ObservableQuery.ts#L425)

Because 2+3 happen instantaneously in sequence, both queries hit the server. I'm not sure what we could do differently; if we reversed the order I would expect the same problem, except that the re-subscription would trigger the old query.

**Comment by stubailo** [comment]
I think your second link is wrong - it points to `setVariables`.

**Comment by tmeasday** [comment]
Chatting with @stubailo, I think the answer here is that in AC, `observable.setVariables` should not trigger a fetch if there are no subscribers. I'll open an issue on AC but leave this open so we remember to remove the extra line in the test.
