### ISSUE TITLE
useQuery trigger rerender when page change in nextjs

### ISSUE THREAD

**Issue by macrozone** [apollographql/react-apollo#3811]
I am using react-apollo with nextjs and i observed that every `useQuery` triggers a rerender when i change routes, even if the parent component of a component that uses `useQuery` does NOT rerender. This affects performance negativly.

**Intended outcome:**

`useQuery` only triggers a rerender when 

**Actual outcome:**

On every page navigation, every `useQuery` used in a shared AppLayout component does rerender. 

**How to reproduce the issue:**

before setting up a reproduction, i would like to see if someone has an idea what's going on.  I don't think that this is supposed to happen.

**Version**

  System:
    OS: macOS 10.15.2
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Browsers:
    Chrome: 79.0.3945.117
    Firefox: 71.0
    Safari: 13.0.4
  npmPackages:
    @apollo/react-hooks: ^3.0.0 => 3.1.3
    @apollo/react-ssr: ^3.0.0 => 3.1.3
    apollo-boost: ^0.4.3 => 0.4.4
    apollo-cache-inmemory: ^1.6.2 => 1.6.3
    apollo-link-batch-http: ^1.2.13 => 1.2.13
    apollo-link-context: ^1.0.17 => 1.0.19
    apollo-link-error: ^1.1.12 => 1.1.12
    apollo-link-persisted-queries: ^0.2.2 => 0.2.2
    apollo-link-schema: ^1.2.2 => 1.2.4

**Comment by dylanwulf** [comment]
Possible duplicate of #3595

**Comment by macrozone** [comment]
> Possible duplicate of #3595

exactly, i think that is indeed also my problem
