### ISSUE TITLE
UseQuery does not receive result when using a retry

### ISSUE THREAD

**Issue by faipmardoni** [apollographql/react-apollo#3844]
useQuery does not receive results when using retry from apollo-link-retry even though it has been obtained in the network status

**Intended outcome:**

the results from the useQuery follow the results from the network

**Actual outcome:**

the results from the use query does not follow the results from the network and still stuck in loading

**How to reproduce the issue:**

***client.js***

const httpLink = createHttpLink({
  uri: process.env.REACT_APP_GRAPH_QL_URL,
});

const authLink = new ApolloLink((operation, forward) => {
  const token = getToken()
  operation.setContext({
    headers: {
      Authorization: Bearer ${token},
    },
  });

  return forward(operation);
});

const batchHttpLink = new BatchHttpLink({
  uri: process.env.REACT_APP_GRAPH_QL_URL,
});

const errorHandle = onError(async ({ graphQLErrors, operation, forward }) => {
  const errorCode = Error.takeCodeFromString(graphQLErrors[0].message);
  if (errorCode === '401') {
    const userData = Storage.getUserData();
    const { data } = await createRefreshToken(
      process.env.REACT_APP_GRAPH_QL_CLIENT_ID,
      userData.authAgent.refreshToken,
    );
    if (data?.errors?.[0]?.message) {
      Storage.logout();
      window.location.href = '/login';
    }
    const token = data?.data?.refreshTokenAgent || '';
    const storage = setToken('userData', JSON.stringify({ authAgent: token }));
    return forward(operation);
  }

  return null;
});

const retryLink = new RetryLink();

const handleBatch = operation => operation.getContext().batch === true;

const linkSplit = split(handleBatch, batchHttpLink, httpLink);

const cache = new InMemoryCache();

const link = ApolloLink.from([errorHandle, retryLink, authLink, linkSplit]);

const client = new ApolloClient({ link, cache });

*** index.js ***

const { data, loading, error } = useQuery(QUERY_PROSPECT_MERCHANT, {
    fetchPolicy: 'network-only',
    variables: {
      payload: {
        companyName: '',
        pagePagination: {
          limit,
          page,
          sortBy: [],
        },
      },
    },
  });

  const { merchants } = data

**Version**

System:
    OS: macOS 10.15.2
  Binaries:
    Node: 13.2.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 72.0.2
    Safari: 13.0.4
  npmPackages:
    @apollo/react-hooks: ^3.1.3 => 3.1.3 
    @apollo/react-testing: ^3.1.3 => 3.1.3 
    apollo-cache-inmemory: ^1.6.5 => 1.6.5 
    apollo-client: ^2.6.8 => 2.6.8 
    apollo-link: ^1.2.13 => 1.2.13 
    apollo-link-batch-http: ^1.2.13 => 1.2.13 
    apollo-link-error: ^1.1.12 => 1.1.12 
    apollo-link-http: ^1.5.16 => 1.5.16 
    apollo-link-retry: ^2.2.15 => 2.2.15 
    apollo-link-schema: ^1.2.4 => 1.2.4 
    react-apollo: ^3.1.3 => 3.1.3

**Comment by mattclough1** [comment]
@faipmardoni did you resolve this?

**Comment by faipmardoni** [comment]
@mattclough1 yes sir.
i've found solution using Observable

**Comment by mjurincic** [comment]
@faipmardoni Could you share code snippet we are experiencing same problem.
