### ISSUE TITLE
"Cannot read property 'updateQuery' of undefined" when component unmounted and subscription message handling deferred

### ISSUE THREAD

**Issue by StefanSmith** [apollographql/react-apollo#3935]
**Intended outcome:**

For performance reasons, our application defers processing subscription messages until a minimum number of them have been received. We then batch process them. This means we call `data.updateQuery` asynchronously. When running tests, a component might be unmounted before the deferred `updateQuery` invocation. When the invocation eventually happens, we would expect Apollo to ignore the invocation since the component has been unmounted.

**Actual outcome:**

When the deferred `updateQuery` invocation eventually occurs,  Apollo has cleaned up the internal state associated with the query and we see the following exception:

```
TypeError: Cannot read property 'updateQuery' of undefined

    at updateQuery (***/***/node_modules/@apollo/react-hooks/lib/react-hooks.cjs.js:127:44)
    ...
```

**Workaround**

Currently, we are working around this issue by applying the following patch to @apollo/react-hooks@3.1.5:

```
diff --git a/node_modules/@apollo/react-hooks/lib/react-hooks.cjs.js b/node_modules/@apollo/react-hooks/lib/react-hooks.cjs.js
index 71168a2..c36b0e2 100644
--- a/node_modules/@apollo/react-hooks/lib/react-hooks.cjs.js
+++ b/node_modules/@apollo/react-hooks/lib/react-hooks.cjs.js
@@ -124,7 +124,7 @@ var QueryData = function (_super) {
     };
 
     _this.obsUpdateQuery = function (mapFn) {
-      return _this.currentObservable.query.updateQuery(mapFn);
+      return _this.currentObservable && _this.currentObservable.query && _this.currentObservable.query.updateQuery(mapFn);
     };
 
     _this.obsStartPolling = function (pollInterval) {
```

The patch simply uses the same pattern as adjacent methods in the same code file: it checks for undefined variables before invoking the method.

**Version**

  System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
  Binaries:
    Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
    npm: 6.14.4 - ~/dev/eisight/application/client-side/node_modules/.bin/npm
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: 75.0
  npmPackages:
    @apollo/client: ^3.0.0-beta.43 => 3.0.0-beta.43 
    @apollo/react-hoc: ^3.1.5 => 3.1.5 
    apollo-client: ^2.6.8 => 2.6.8 
    apollo-link: ^1.2.14 => 1.2.14

**Comment by StefanSmith** [comment]
Closed as I have found a work around in my code that avoids invoking `updateQuery` after a component is unmounted.

**Comment by davydkov** [comment]
Hit the same issue.
I would like the apollo client to manage it internally instead of workarounds.
