### ISSUE TITLE
3.1.4 is not backwards compatible with 3.1.3, should have been major version upgrade?

### ISSUE THREAD

**Issue by insidewhy** [apollographql/react-apollo#3945]
With 3.1.3 all my tests were working fine, with 3.1.4 I get the following error many times:

```
Invariant Violation: Could not find "client" in the context or passed in as an option. Wrap the root component in an <ApolloProvider>, or pass an ApolloClient instance in via options.
```

So it seems with `3.1.4` I must have an `ApolloProvider` above my `MockedProvider` and with `3.1.3` I didn't.

**Comment by insidewhy** [comment]
I added an `ApolloProvider` above every `MockedProvider` and now get a lot of test failures and timeouts. Going back to `3.1.3` for now. Doesn't feel like a minor version upgrade :pager:

**Comment by dylanwulf** [comment]
You should never have an `ApolloProvider` above a `MockedProvider`. This error happens if the `MockedProvider` is being imported from a different version than the react components. Check your package-lock and make sure you don't have multiple different versions installed.

**Comment by insidewhy** [comment]
I see, can this not be solved by using peer dependencies?
