### ISSUE TITLE
Identical field names in different places caches as single object

### ISSUE THREAD

**Issue by kitsoRik** [apollographql/react-apollo#3957]
When I've written my code, I collided with unpredictable behavior, my product owner field was quite different from what I expected.

When I load single product, I have predictable owner, but when I load chat message, my product owner becomes message owner.

Before load messages
![image](https://user-images.githubusercontent.com/48686795/81406642-9dd3e480-9142-11ea-9e05-d380a2dbc320.png)

After load messages
![image](https://user-images.githubusercontent.com/48686795/81406623-957ba980-9142-11ea-8d1a-5d9654484f8a.png)

I can fix this problem for two ways:
- Disable cache
- Rename messages field "owner" (example, rename to 'writter')

But, I think, it's bad behavior.

How to reproduce the issue:

Clone https://github.com/kitsoRik/apollo-react-bug 

At the web folder: npm start
At the server folder: node .

(if you don't want create your server or you don't have mongodb, you can connect to my server, change uri in apollo-client to: 'http://5.45.118.116:3501/graphql' )

A view browser.

My versions:

- node - 13.12.0
- apollo-server - 2.12
- react - 16.13.1
- apollo-client - 3.0.0-beta.44
- mongo - 4.2.5

Video: https://youtu.be/80Ma8Twml2w

**Comment by benjamn** [comment]
Please give `@apollo/client` (Apollo Client 3) a try. Many things have been improved about how the cache works, and we will not be back-porting those changes to the old `apollo-client` package.

**Comment by kitsoRik** [comment]
> Please give `@apollo/client` (Apollo Client 3) a try. Many things have been improved about how the cache works, and we will not be back-porting those changes to the old `apollo-client` package.

Ok, i tried to use @apollo/client and got same problem, i updated my repo to new code.

**Comment by kitsoRik** [comment]
Ok, I've collided with similar problem,  when cached object by id, I had thought that it link with __typename, but this is not the case. so I thought, maybe here is the same problem? But, why changes field name is work?
