### ISSUE TITLE
data.refetch() in componentDidMount does not update the store

### ISSUE THREAD

**Issue by Chris-R3** [apollographql/react-apollo#416]
## Goal
I'd like to refetch data from the server every time the `componentDidMount` 😉 

## Steps to Reproduce

```js
...
componentDidMount () {
 this.props.data.refetch()
}
...
```

### Buggy Behavior
The first time the component mounts everything is working as expected, on consecutive
mounts however the refetch request gets sent to the server and returns with the correct results, but the store never gets updated.

When I call `refetch` in the `render` method the store gets updated as expected!

### Expected Behavior

After the refetch request returns from the server, the store should get updated with the new data

### Version
- apollo-client@0.6.0
- react-apollo@0.7.3
- apollo-client-devtools@1.0.3

**Comment by calebmer** [comment]
Related: https://github.com/apollographql/apollo-client/issues/1214

**Comment by mdebbar** [comment]
I'm also seeing this issue. To be clear, `refetch` sends a request to the server and the response is correct. But the Apollo store doesn't get updated.

**Comment by calebmer** [comment]
This problem should be fixed in `apollo-client@0.8.6` by this PR: https://github.com/apollographql/apollo-client/pull/1264

Let me know if you still have this problem after `0.8.6` 😊

**Comment by Chris-R3** [comment]
I switched to the new version, but the issue remains. The Apollo store only get's updated when I use your `forceFetch: true` workaround from the other issue.

**Comment by calebmer** [comment]
Hmm, then I’m not entirely sure what is causing your issue @Chris-R3. Could you fork [`react-apollo-error-template`](https://github.com/apollographql/react-apollo-error-template) and put together a small case which reproduces your error? This would go a long way in helping us debug the issue.

**Comment by Chris-R3** [comment]
Sure I'll look into it next week. Vacation starts tomorrow 😉 .

**Comment by pajasevi** [comment]
I'm having same problem - data is fetched but the store is not updated. Relevant code snippet is here:
```javascript
class AccountsPage extends React.Component {
  constructor(props) {
    super(props);

    this.state = initialState;
  }
  componentDidMount() {
    this.props.data.refetch();
  }
  render() {
    /* this.props.data.allAccounts.map render */
  }
}

const FeedQuery = gql`query allAccounts {
  allAccounts {
    id
    name
    pin
  }
}`;

const AccountsPageWithData = graphql(FeedQuery)(AccountsPage);

export default AccountsPageWithData;
```

**Comment by jbaxleyiii** [comment]
@pajasevi if you update to the latest versions, does this still exist?

**Comment by pajasevi** [comment]
I updated all necessary dependencies and it's ok now. I had to use `componentDidUpdate` in one instance, but it works properly. Thanks @jbaxleyiii

**Comment by cnatis** [comment]
Im using react-apollo 1.4.11 and I have noticed this issue as well, specifically referring to arrays as a property of one of my objects. In my case I can see the graphQL query result in the network tab shows that my object has an empty array for a property, however the UI and react show the props data as containing a previous value, I would have expected the refetch to have set the property to an empty array in react as returned from the server.

**Comment by BossGrand** [comment]
I'm also seeing this issue
