### ISSUE TITLE
Typescript error:  Cannot find module 'apollo-client/transport/networkInterface'

### ISSUE THREAD

**Issue by Pajn** [apollographql/react-apollo#423]
## Steps to Reproduce

Describe how to reproduce this issue.

In test-utils the file `apollo-client/transport/networkInterface` is imported.
With `apollo-client` version `0.7.3` and `react-apollo` version `0.8.1` the file `apollo-client/transport/networkInterface` is exported as `apollo-client/lib/src/transport/networkInterface`.
This creates a Typescript error due to the invalid import in the generated .d.ts file.
Changing the import is an easy fix to the problem, however I assume that the import looks as it does for a reason, does react-apollo expect another version of apollo-client?

### Version
- apollo-client@0.7.3
- react-apollo@0.8.1

**Comment by abhiaiyer91** [comment]
Well current peer dependencies are set 0.6.0! I do think these path based imports are brittle if the file path changes.

**Comment by tmeasday** [comment]
I think `apollo-client` exports this directly now, no?

**Comment by benhjames** [comment]
Once the above PR (apollographql/apollo-client#1621) is merged, we can remove the relative file import from `apollo-client/transport/networkInterface` and just import everything straight from `apollo-client`. :)

**Comment by jbaxleyiii** [comment]
Fixed by https://github.com/apollographql/react-apollo/pull/679
