### ISSUE TITLE
Context missing on server side render after `getDataFromTree`

### ISSUE THREAD

**Issue by codepunkt** [apollographql/react-apollo#425]
## Steps to Reproduce

1. Set context in top-most component on server-side render. `ApolloProvider` is nested into that topmost component.

```javascript
// Create server context
class ServerContext extends React.Component {
  getChildContext() {
    return { isServer: true };
  }
  render() {
    return React.Children.only(this.props.children);
  }
}
ServerContext.propTypes = {
  children: React.PropTypes.node.isRequired,
};
ServerContext.childContextTypes = {
  isServer: React.PropTypes.bool.isRequired,
};

// Create our React application element.
const reactAppElement = (
  <ServerContext>
    <ApolloProvider store={store} client={apolloClient}>
      <App />
    </ApolloProvider>
  </ServerContext>
);

getDataFromTree(reactAppElement).then(() => {
  const content = ReactDOM.renderToString(reactAppElement);
  // ...
})
```

2. Have a child of `App` not render when on server.
```javascript
const App = (_, { isServer }) => {
  console.log(isServer)
  return (
    <div>
      {isServer && <h1>Not rendered on server</h1>}
      <h2>Rendered on server</h2>
    </div>
  );
}
```
### Buggy Behavior

Both `h1` and `h2` are contained in `content` returned from `ReactDOM.renderToString`. First console.log in app render logs `true`, second logs `undefined`.

### Expected Behavior

`h1` should not be included in `content` returned from `ReactDOM.renderToString`. Both console.log in app render log `true`.

### Version
- apollo-client@0.6.0
- react-apollo@0.8.1

**Comment by tmeasday** [comment]
Hi @codepunkt -- interesting; I would have expected this to work; we do pass the `context` into stateless functional components [here](https://github.com/apollostack/react-apollo/blob/master/src/server.ts).

Would you be interested in sending a PR with a failing test demonstrating the problem? Perhaps you could add a test to the `walkTree` [tests](https://github.com/apollostack/react-apollo/blob/master/test/react-web/server/index.test.tsx#L38) that checks context is properly passed around?

**Comment by jbaxleyiii** [comment]
@codepunkt why wouldn't the h1 be included on the server? It looks like it *should*?

**Comment by makamekm** [comment]
I see that this problem has not been solved.

**Comment by piglovesyou** [comment]
@tmeasday @makamekm This can be reproduced in `feature/apollo` branch in React Starter Kit.
https://github.com/kriasoft/react-starter-kit/blob/d5cf707e44c3b930c4c5fce46db3c53dee22dedd/src/server.js#L199
