### ISSUE TITLE
Upgrade to 0.8.2 fails to resolve react-apollo module

### ISSUE THREAD

**Issue by 0x6e6562** [apollographql/react-apollo#427]
## Steps to Reproduce

After upgrading

- apollo-client@0.5.26
- react-apollo@0.6.0

to

- apollo-client@0.6.0
- react-apollo@0.8.2

I run into the long running [4968](https://github.com/facebook/react-native/issues/4968) issue:

```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 670): UnableToResolveError: Unable to resolve module react-apollo from
```

### Buggy Behavior

I've followed the  [4968](https://github.com/facebook/react-native/issues/4968) issue to see if there is a react native solution for this.

I think I tried every single suggestion people have posted. The only solution I have found is to revert back to the previous version.

By flipping between the previous and updated versions I can reliably make this problem occur and then go away again.

Does anybody know of any apollo specific issues or things one could try?

**Comment by 0x6e6562** [comment]
I think I might have made some progress, but I still need to test this:

```
$ rm -rf node_modules/react-apollo
$ git clone https://github.com/apollostack/react-apollo node_modules/react-apollo
$ cd node_modules/react-apollo
$ vim package.json
```

After this I updated the peer dependency to apollo-client@0.6.0 in `package.json`'.

Then I compiled the typescript

```
$ npm run compile
```

And now the `react-apollo` dependency appears to resolve in my project.

**Comment by 0x6e6562** [comment]
My motivation for upgrading was because of the error handling in 0.6.0. Before I upgraded, server errors were being silently swallowed, now that I've got 0.8.2 working, server errors are being populated in the component props.

So the workaround is to run a local clone of react-apollo and uprev the apollo-client peer dependency.

**Comment by jbaxleyiii** [comment]
This should be fixed
