### ISSUE TITLE
Option to skip but retain the data

### ISSUE THREAD

**Issue by asyschikov** [apollographql/react-apollo#432]
I am using apollo by wrapping my component with a query. One of the query variables changes and it should trigger the fetching of data, but my `skip` evaluates to true. What happens in the result is that all my data disappears from the component. I am wondering if there a way to retain the data if the query was skipped.

**Comment by tmeasday** [comment]
If you want data why would you skip? Is it to avoid the variables changing? If so, why not just make the `options` function always return the same variables?

**Comment by asyschikov** [comment]
@tmeasday that is what I did in the end, but it can get messy. It would be convenient sometimes to be able to retain the data while skipping.

**Comment by tmeasday** [comment]
I tend to be of the opinion that non-declarative behavior (like the data in the component relying on past arguments rather than just the current options) causes more trouble than it's worth.

**Comment by tmeasday** [comment]
Still we do do something similar to this during `loading` states, so it wouldn't be completely different to the current design. Anyone else have thoughts about this?

**Comment by machard** [comment]
hey :) please take a look at my proposition https://github.com/apollostack/react-apollo/pull/439
