### ISSUE TITLE
Fields not populated with Union type on types starting from the second one

### ISSUE THREAD

**Issue by imthehell** [apollographql/react-apollo#441]
## Steps to Reproduce

Very strange issue: when there is a query like the one below, with two different types (type is defined by an Union),   "bar" field in FirstType is populated. "foo" field on SecondType is not populated. 

```
query Query($page: Int!, $size: Int!) {
  getByFoo(page: $page, size: $size) {
    docs {
      ... on FirstType {
        _id
        list{
          bar{
            bar1
            bar2
          }
        }
      }
     ... on SecondType {
        _id
        list{
          foo
        }
  }
}

```
Switching FirstType with SecondType like below, only "foo" on SecondType is populated, bar on first type is not populated

```
query Query($page: Int!, $size: Int!) {
  getByFoo(page: $page, size: $size) {
    docs {
      ... on  SecondType{
        _id
         list{
          foo
        }
        }
      }
     ... on FirstType {
        _id
        list{
          bar{
            bar1
            bar2
          }
        }
  }
}

```
The query is working as expected using Graphiql.
Parent fields are populated correctly.

**It seams that on SecondType are used the types of FirstType, since if I add foo also on FirstType like below, foo on SecondType is populated**

```
query Query($page: Int!, $size: Int!) {
  getByFoo(page: $page, size: $size) {
    docs {
      ... on FirstType {
        _id
        list{
          bar{
            bar1
            bar2
          }
          foo
        }
      }
     ... on SecondType {
        _id
        list{
          foo
        }
  }
}

```

### Buggy Behavior

Field starting from the second type are not populated correctly

### Expected Behavior

All the field should be populated

### Version
- apollo-client@0.8.1
- react-apollo@0.9.0

Same behavior on previous versions

**Comment by imthehell** [comment]
any news?

**Comment by calebmer** [comment]
Are you getting this error with `react-apollo@1.0.0-rc.2`? I believe it was fixed.

**Comment by helfer** [comment]
@imthehell are you still seeing this error with the latest RC?

**Comment by imthehell** [comment]
@calebmer and @helfer thank you very much for the support.

I can confirm that with the latest RC  (react-apollo@1.0.0-rc) the problem is resolved.
