### ISSUE TITLE
Compose not working as expected with multiple queries

### ISSUE THREAD

**Issue by thisbejim** [apollographql/react-apollo#445]
In the example below `MeQuery` will override `EntitiesQuery` and the `entities` prop will never be passed to `Component`. You can switch the two around and the reverse will happen, so whatever comes last overrides the previous query. Am I missing anything here? Thanks.

```
const EntitiesQuery = gql`query Entities {
  entities {
    id
    name
  }
}`

const MeQuery = gql`query Me {
  me {
    username
    id
  }
}`

const Container = compose(
  graphql(EntitiesQuery),
  graphql(MeQuery),
)(Component);
```

I'm on 0.8.3 btw.

**Comment by thisbejim** [comment]
nvm, you've gotta specify the name, e.g:
```
const Container = compose(
  graphql(EntitiesQuery, { name: 'entities' }),
  graphql(MeQuery, { name: 'me' }),
)(Component);
```
Then instead of accessing them of `props.data` e.g. `props.data.me` you just go `props.me`. However, as far as I can tell doing a composition like this fires off two requests rather than one, so I recommend avoiding this pattern.

**Comment by jorbs** [comment]
Weird... I'm using the approach but the responses for both queries are nested. In your example, some results of `EntitiesQuery` are returned in `MeQuery`. Have you ever had this issue?

**Comment by ZeeshanSafdarZee** [comment]
Doing Same, but get only the latest query result.

**Comment by yvesgurcan** [comment]
I'm having the same issue as @thisbejim.
