### ISSUE TITLE
NPM package of v0.9.0 should not contain TypeScript sources + dist files

### ISSUE THREAD

**Issue by swernerx** [apollographql/react-apollo#446]
The current npm package contains typescript sources, which IMHO should not be the case. NPM packages should only contain transpiled code.

It also contains the "dist" folder which is probably also not relevant for npm users.

I'd like suggest to add both folders to the .npmignore file.

While you are working there is might make sense to keep ES modules intact and add a "jsnext:main" and "module" definition to your package.json :)

**Comment by calebmer** [comment]
We explicitly include the source TypeScript files in the [`package.json`](https://github.com/apollographql/react-apollo/blob/master/package.json#L61). I don’t think it hurts anyone that the source files are there, and I could see how the source files could be useful for some users who want to hyper-optimize their builds.

Is there a reason why we shouldn’t include the TypeScript source files?

**Comment by swernerx** [comment]
It's just a common practise to not include these. If every package would include everything they have, we would have larger node_modules directories everywhere. You typically bundle source maps + add links to the Git repo to the readme. I figure that's enough.

**Comment by calebmer** [comment]
You make a good point. We probably won’t include the source files when we cut a `1.0` release, but right now it would be a breaking change, so we’ll put it off for later. I’m going to close, but I’ll keep this in mind. Thanks 👍
