### ISSUE TITLE
Question: How to tell if data prop fulfills current query or a previous one

### ISSUE THREAD

**Issue by dallonf** [apollographql/react-apollo#447]
This question may turn into a feature request depending on whether there's a way to do this... here's my use case:

I have a page that displays a list of objects. Because caching and mutations [are kind of weird in Apollo](https://github.com/apollographql/apollo-client/issues/951) at the moment, I have this list component set to `forceFetch: true`.

This query is somewhat expensive, so even though I need to run it every time you visit the page, if something's already cached for it, I want to render the page right away and have the `forceFetch` query run in the background, updating the results (if there is anything to update) once it's done.

I _also_ want this general sequence (immediately render from cache if available, then update in the background) to occur when changing query variables, and that's where I'm starting to run into trouble, because when variables change, one of two things will happen:
- If the new query can be fulfilled from cache, the component will be updated immediately with new data, and a request goes out in the background. The `networkStatus` will be changed to `setVariables` while this is happening.
- If the new query _cannot_ be fulfilled from cache, the component will still have the _old_ data while a request will go out for new data. I would like to render a spinner in this case. The `networkStatus` will be changed to `setVariables` while this is happening.

So... after a lot of rambling, my question is if there's a way to tell the difference between these two states, because I want the UX to be different. If there's not a way... _can_ there be? :)

**Comment by calebmer** [comment]
Currently, there is no way to do this on the client’s side. There is, of course, a lot you could do in your React components to get your desired behavior such as setting a `loading` prop to true whenever you call `setVariables`.

**Comment by dallonf** [comment]
Thanks for the reply! I'm actually _not_ calling `setVariables()`, I'm actually relying on state changes from Redux and React Router for that purpose... since my component is not necessarily the one changing the variables, it would be somewhere between impossible and hugely encapsulation-breaking to work around this issue in my app.

Can you help me understand the underlying problem so I can create an issue on `apollo-client` or wherever needs work? Might even be able to cook up a PR if I've got time.

**Comment by jbaxleyiii** [comment]
@dallonf is this still an issue?

**Comment by dallonf** [comment]
Yes; I have a PR open on apollo-client (https://github.com/apollographql/apollo-client/pull/1607) that may resolve this, although it has a pretty heavy impact, so there may be a better option.

**Comment by dallonf** [comment]
I think this issue is actually in Apollo Client rather than react-apollo, so I'll just point to https://github.com/apollographql/apollo-client/pull/1607 and close this
