### ISSUE TITLE
Variables can't be updated from nested props

### ISSUE THREAD

**Issue by jameswyse** [apollographql/react-apollo#449]
Assigning a variable from a nested prop prevents refetching when that prop is changed.

For example the following does not update the variable or refetch when `props.someObject.myVariable` is changed:
```
@graphql(myQuery, {
  options: props => ({
    variables: {
      myVariable: props.someObject.myVariable
    }
  })
})
```

It works correctly if I use `props.someVariable` instead. This seems to be due to the use of `shouldComponentUpdate`.. It only does a shallow comparison of props (using `shallowEquals`) so doesn't see the change and prevents the update.

**Comment by calebmer** [comment]
How does `myVariable` change in your case? Could you put together a small reproduction of this error?

**Comment by jameswyse** [comment]
In my case `someObject` is a `mobx` store but it seems to be true for any object prop where the reference doesn't change. I'll put together a reproduction :)

**Comment by jbaxleyiii** [comment]
closing as this is older than two weeks without a reproduction. Feel free to reopen if you still have this issue and can create a reproduction

**Comment by aperkaz** [comment]
Any new updates on this? Thanks
