### ISSUE TITLE
Reducer is not get called if the host component is not mounted on the mutation executed.

### ISSUE THREAD

**Issue by zhaoyao91** [apollographql/react-apollo#454]
Hi, from the doc, we should prefer `reducer` to `updateQueries`, so the component can take responsibility to keep itself informed, not bothering to inform other component.

But I am stuck in a situation.
Guess A is the querying comp and B is the mutating comp, and set a reducer on A, which will watches out B's mutations and try to update A's query result.
If A and B are rendered together, everything goes well: B makes some mutation and A gets updated.
But if they are rendered exclusively. say render A first, then switch to B, which then makes some mutation, and finally switch back to A, A will keep the old result for it can't see the mutation while it is unmount.

Please see [this branch](https://github.com/zhaoyao91/our-poems/tree/show_query_reducer_problem) as an example.

**Comment by calebmer** [comment]
This is a use case we are exploring providing better support for in the future. For now, you need to keep the components mounted if you want their data to update.
