### ISSUE TITLE
`skip` should still provide `data` prop

### ISSUE THREAD

**Issue by wmertens** [apollographql/react-apollo#456]
When using `skip()` on a query and it evaluates to true, the component no longer receives a `data` prop. This results in ugly code because this needs to be detected; you can't just use destructuring any more (`const {data: {loading, foo}} = this.props`)

I'd be happy with an empty `data` prop, put perhaps `skipped: true` and `refetch()` can be useful.

**Comment by calebmer** [comment]
We’d be happy to merge a PR that introduces this functionality 😊

**Comment by wmertens** [comment]
@calebmer commence the happy merging process ;)
