### ISSUE TITLE
updateQueries does not update this.props.data [HELP WANTED]

### ISSUE THREAD

**Issue by okbel** [apollographql/react-apollo#458]
First of all, thanks to all contributors and active core developers. It's amazing what you're building.

I'm facing an issue, I don't know if it's a bug or I'm doing something wrong. So, some clarification about this would be super helpful

I have a query like this, the first query works perfectly, then I click a Load More button and `loadMore` gets triggered, this one triggers a new query and when I try to update `this.props.data` returning the same result only modifying the `comments` array, nothing happens. I get the oldData back. I'm checking the reducers and it seems that it's working as expected but `this.props.data` is not getting updated.

```js
export const queryStream = graphql(STREAM_QUERY, {
  options: () => ({
    variables: {
      asset_url: getQueryVariable('asset_url')
    },
    forceFetch: true
  }),
  props: ({data}) => ({
    data,
    loadMore: ({limit, cursor, parent_id, asset_id, sort}) => {
      return data.fetchMore({
        query: LOAD_MORE,
        variables: {
          limit,
          cursor,
          parent_id,
          asset_id,
          sort
        },
        onError: (err) => console.error(err),
        updateQuery: (oldData, {fetchMoreResult:{data:{new_top_level_comments}}}) => {
          if (!new_top_level_comments) { return oldData; }
          console.log(oldData.asset)
          const finalResult = {
            ...oldData,
            asset: {
              ...oldData.asset,
              comments: [...oldData.asset.comments, ...new_top_level_comments]
            }
          };
          return finalResult;
        }
      });
    }})
});

```

### Version
- apollo-client@0.8.3
- react-apollo@0.10.0

Thank you!

**Comment by calebmer** [comment]
Hi @okbel 😊

It would make it a lot easier for us to debug your issue if we had a minimal reproducing test case. Is that something you could put together for us?

**Comment by okbel** [comment]
Thank you @calebmer. It turns out that the GraphQL query was returning undefined after 2 requests and `react-apollo` is not very good at handling errors. It was failing silently :(
I'd like to close this one.  But also, I'd like help to make apollo more developer friendly, so I might address this in another issue or pr.

Thanks for offering your help!

**Comment by calebmer** [comment]
That would be great! We are concerned about error handling in the client as well and it is something we will address for 1.0.
