### ISSUE TITLE
Continue polling after network up

### ISSUE THREAD

**Issue by DimitryDushkin** [apollographql/react-apollo#465]
## Steps to Reproduce

1. Add polling like:
```js
export default graphql(SamplesQuery, {
    options: {
        pollInterval: 5000,
        forceFetch: true
    }
})(PageLabSamples);
```
2. Turn on offline in dev tools (network tab)
3. You will receive empty data and error on next query and polling stops.

### Buggy Behavior
Polling shouldn't stop, it have to keep trying to get data.
Or there must be some mechanism to restart polling on network up.

### Expected Behavior
Continue polling tries even on network down.

### Version
- apollo-client@0.8.6
- react-apollo@0.10.1

**Comment by DimitryDushkin** [comment]
I've managed to fix it by manually calling refetch and adding `notifyOnNetworkStatusChange: true`. Looks like bad hack 😢 :

```jsx
import _throttle from 'lodash/throttle';
const refetchThrottled = _throttle(data => data.refetch(), 1000);

function PageLabSamples({ data, location }) {
    const { samples, loading, error } = data;
    if (error) {
        refetchThrottled(data);
    }
    return ...;
}

const SamplesQuery = gql`
    ...
`;

export default graphql(SamplesQuery, {
    options: {
        pollInterval: 5000,
        forceFetch: true,
        notifyOnNetworkStatusChange: true
    }
})(PageLabSamples);
```

**Comment by calebmer** [comment]
This is probably an issue with [`apollo-graphql`](https://github.com/apollographql/apollo-client), and it looks like there is already an issue: https://github.com/apollographql/apollo-client/issues/1099

Feel free to contribute to that issue. We’d love to discuss a PR fixing this issue 😊

**Comment by Kureev** [comment]
This is still a bug and proposed workaround doesn't work anymore as far as in the latest Apollo Client it doesn't return any error if polling fails due to out-of-network error. How can we solve/workaround it?
