### ISSUE TITLE
Mutation response with nested object breaks cache when store has further nested object with query 

### ISSUE THREAD

**Issue by jaydenseric** [apollographql/react-apollo#467]
Requesting a mutation response with a nested object somehow breaks the cache when the store has a further nested object that has a query.

Basically if a component renders with a query like this:

```graphql
query populate ($userId: String!, $avatarSize: Int!) {
  user (userId: $userId) {
    id
    username
    name
    avatar {
      id
      thumbnail (width: $avatarSize, height: $avatarSize) {
        id
        url
      }
    }
  }
}
```

And the user avatar is later updated with a mutation to a new Image with a new ID:

```graphql
mutation mutate ($userId: String!, $files: [UploadedFile!]!) {
  updateUserAvatar (userId: $userId, files: $files) {
    id
    avatar {
      id
    }
  }
}
```

Despite actually having worked if you refresh the page, the mutation responds with an error and React freaks out:

```
Caught an exception! TypeError: Cannot read property 'username' of undefined
    at AccountMenuLoggedIn.render (index.js:29)
    ...
```

This is pretty weird because the error reports on the mutation, to do with a render failure somewhere else in another component.

If you change the mutation return data to not include the nested avatar, but other shallow properties:

```graphql
mutation mutate ($userId: String!, $files: [UploadedFile!]!) {
  updateUserAvatar (userId: $userId, files: $files) {
    id
    email
    username
  }
}
```

There are no errors, although you have to refresh the page to see the avatar update.

Object id's are globally unique and derived the standard way:

```js
const client = new ApolloClient({
  networkInterface,
  dataIdFromObject: ({id, __typename}) => id && __typename ? `${__typename}:${id}` : null
})
```

Here are just the relevant types:

```graphql
type Thumbnail {
  id: String!
  url: String!
  width: Int!
  height: Int!
  format: String!
}

type Image {
  id: String!
  thumbnail (width: Int, height: Int, format: String): Thumbnail!
}

type User {
  id: String!
  username: String!
  email: String!
  name: String!
  bio: String!
  latitude: Float
  longitude: Float
  avatar: Image
  artworks (available: Boolean = true): [Artwork]
}

type Query {
  user (userId: String, username: String): User
}

type Mutation {
  updateUserAvatar (userId: String!, files: [UploadedFile!]!): User!
}
```

### Version

- apollo-client@0.8.6
- react-apollo@0.11.1

**Comment by jaydenseric** [comment]
Even if it turns out a manual flush is needed somehow to see new data rendered, it seems fragile and scary that just by asking for some data in your mutation response that is completely permissible according to your schema somewhere else your app can terribly crash.

Hopefully I'm missing something.

**Comment by calebmer** [comment]
So what’s happening here is that an error is being thrown, so `user` is undefined and an `error` object is exposed but you are likely not catching the error:

```js
const { loading, error, user } = this.props.data;
if (error) {
  console.error(error);
}
```

This is a known error that happens in exactly the case that you describe 😊

Your mutation is changing the `id` of the user’s avatar, and so a new object is created in the store with the new id, but _without_ the thumbnail.

So when your React component goes to re-render it can’t find a thumbnail for the avatar with the new id and will throw an error.

To fix this error, just do the following:

```graphql
mutation mutate ($userId: String!, $files: [UploadedFile!]!, $avatarSize: Int!) {
  updateUserAvatar (userId: $userId, files: $files) {
    id
    avatar {
      id
      thumbnail (width: $avatarSize, height: $avatarSize) {
        id
        url
      }
    }
  }
}
```

Just make sure the arguments to `thumbnail` are the _exact_ same as in your initial request.

We have a PR open (https://github.com/apollographql/apollo-client/pull/1306) that will stop throwing the error, and instead simply return the old data while also setting a `stale` flag to `true` so you can refetch the query if you would like.

Hope this helps. Let us know if you have any further questions 😊

**Comment by jaydenseric** [comment]
Thanks for explaining 🙂

I imagined the cache worked just like a browser; if something does not exist in the cache it simply gets fetched.

Is there a way to get components to automatically refetch themselves if their cached query has been nuked?

> instead simply return the old data while also setting a stale flag to true so you can refetch the query if you would like.

How do you get the refetch to work exactly? Does `this.props.data.stale` appear, and if so, how do you use that to trigger the refetch before the renderer freaks out about missing data? Will the flag be available once your pull request is merged?

Originally my `Image` and `Thumbnail` types were one; `Image` took thumbnailing arguments. I was tediously busting the cache as you suggest, and realized it didn't scale. I created the `Thumbnail` sub-object to own the parameters, expecting all possible thumbnail variations to get purged from the cache simply by replacing the holding `Image`.

Ideally an ID is all a mutation should use to bust the cache as the mutation component has no idea how data is queried throughout the rest of the app. Even if it did somehow know every possible query variation for that node of data, it is still wasteful to fetch data that may or may not be viewed.

Thumbnail sizes are determined according to placement and the client's device pixel ratio. Thumbnailing is expensive, so ideally every size possible to view in the app is not generated at once via a large mutation response, but on demand. A thumbnail may never need to be generated if no one views certain parts of the site.

Thanks again, you guys are legends.

**Comment by calebmer** [comment]
You could use `refetchQueries` which allows you to refetch entire queries by name, or in the future you could use the `stale` field. You would most likely call refetch if the stale flag is true from a `componentDidUpdate` function.

**Comment by jaydenseric** [comment]
Sounds like a new query option `refetchOnStale` would be really handy:

```js
@graphql(populate, {
  options: ({userId}) => ({
    variables: {
      userId,
      avatarSize: Math.round(avatarSize * window.devicePixelRatio)
    },
    refetchOnStale: true
  })
})
class AccountMenuLoggedIn extends Component {
```

Less complicated than using `componentDidUpdate`, which I would add to every component with a query. Perhaps even make `refetchOnStale` true by default – opt out rather than opt in.

**Comment by calebmer** [comment]
This is something we have discussed, but it isn’t something I’m personally comfortable with if we don’t also log a warning. @stubailo would be interested in hearing this.

**Comment by stubailo** [comment]
Yeah I'm worried about infinite refetching loops - maybe we can have `refetchOnStale` but have it only work once and throw an error if we try to refetch more than once?

**Comment by jaydenseric** [comment]
Does refetching cause `this.props.data.loading == true`? Everything would flicker to a bunch of loading spinners while updating. Updating the store via a mutation response does not cause loading states.

**Comment by calebmer** [comment]
Refetching would cause `this.props.data.loading === true`, however, you would also have your data unlike in the first load where you had no data. So you could always make the check `this.props.data. user` and if you have data always render whether or not `loading` is `true.`
