### ISSUE TITLE
Cannot find type definition file for 'chai'.

### ISSUE THREAD

**Issue by davidye** [apollographql/react-apollo#469]
Getting this when I compile my app:

```
ERROR in ***/node_modules/react-apollo/lib/graphql.d.ts
(1,1): error TS2688: Cannot find type definition file for 'chai'.
```

This line is:

`
/// <reference types="chai" />
`

### Version
- apollo-client@0.8.7
- react-apollo@0.11.1

**Comment by calebmer** [comment]
Thanks for reporting. Fixed by `0.11.2` in https://github.com/apollographql/react-apollo/pull/471 🎉
