### ISSUE TITLE
ownProps does not have correct data when wrapping a component with 'graphql' after wrapping it with redux 'connect'

### ISSUE THREAD

**Issue by yash0087** [apollographql/react-apollo#470]
When i wrap a component with 'graphql' function after the component is wrapped with redux 'connect' function, i dont receive all the props as 'ownProps'.

Consider the following,

```javascript
class TestClass extends Component {
   ..
}

const mapDispatchToProps= () => ({
    callbackFunction: () => {}
})

const mapStateToProps = (state) => ({
    test: state.test
})

```

In the following code 'cb' has the actual 'callbackFunction' and 'testState' has the 'test' value

```javascript
const TestClassWithData = qraphql(QUERY, {
   props: ({ownProps}) => {
       const cb = ownProps.callbackFunction;
       const testState = ownProps.test;
   }
})(TestClass);

export default connect(mapStateToProps, mapDispatchToProps)(TestClassWithData)
```

In the following code 'cb' and 'testState' are undefined

```javascript
const TestClassWithRedux = connect(mapStateToProps, mapDispatchToProps)(TestClass)

export default qraphql(QUERY, {
   props: ({ownProps}) => {
       const cb = ownProps.callbackFunction;
       const testState = ownProps.test;
   }
})(TestClassWithRedux);

```

This means that when I 'compose' them, I need to maintain the order in which I pass them.

The following will pass the props,

```javascript
compose(
    connect(mapStateToProps, mapDispatchToProps),
    qraphql(QUERY,{})
)(TestClass)
```

while the following will not pass the props

```javascript
compose(
    qraphql(QUERY,{}),
    connect(mapStateToProps, mapDispatchToProps)
)(TestClass)
```

**Comment by 1st8** [comment]
Yes, the order is of course important. `a(b(c))` is not equal to `b(a(c))`.

I always imagine these composed components like an onion. Each HoC is another layer around the core Component and passes its props down to the next and finally to the core.
This way its easy to see, why the inner `graphql` layer receives stuff from the outer `connect`, but not the other way around.

Hope I understood you correctly, did I?

**Comment by yash0087** [comment]
Thanks for the explanation, i get that point.
But since the compose function executes from right-to-left, i was expecting the following to work rather than the other one.

```javascript
compose(
    qraphql(QUERY,{}),
    connect(mapStateToProps, mapDispatchToProps)
)(TestClass)
```

The other point is from the apollo docs, 'http://dev.apollodata.com/react/redux.html' it says you can use redux connect function either before or after graphql function.

> You can continue to use react-redux‘s connect higher order component to wire state into and out of your components. You can connect before or after (or both!) attaching GraphQL data to your component with graphql

So should my example not work irrespective of the order?

**Comment by calebmer** [comment]
If the `graphql` HOC has a dependency on the `connect` HOC then order does matter 😣

I agree that the `compose` ordering feels unnatural and tricky to reason about. If you want an implementation that makes more sense, check out the Lodash `flow` function: https://lodash.com/docs/4.17.4#flow

It does the same thing as `compose`, but in the reverse order. Lodash’s `flowRight` does the same thing as `compose`.
