### ISSUE TITLE
Nesting Mutations as Mutation Variables

### ISSUE THREAD

**Issue by etaheri** [apollographql/react-apollo#473]
I have created the following mutations:
```
const createCampaignMutation = gql `
  mutation ($name: String!){
    addCampaign(
      data: {
        name: $name
      }) {
       _id
      }
  }`;

const createClientCampaignMutation = gql `
  mutation ($id: ID!, $campaignId: String!){
    addClientCampaign(id:$id, campaignId:createCampaignMutation(name:"test"){
      _id
    }) {
      _id
    }
}`;

export default graphql(createCampaignMutation, {name: 'createCampaignMutation'})(graphql(createClientCampaignMutation, {name: 'createClientCampaignMutation'})(injectSheet(styles)(ClientsPageAdd)));
```

`createCampaignMutation` creates a 'campaign' object and `createClientCampaignMutation` adds the id of the object that holds all of the references to the 'campaign' objects. Is there a way that I can call `createCampaignMutation` inside of `createClientCampaignMutation` and use the returned `_id` value for a variable in the nested mutations?

I tried to achieve this above, but get:

```
Uncaught Error: Syntax Error GraphQL (3:64) Expected Name, found (
     mutation addClientCampaign($id: ID!, $campaignId: String!){
     addClientCampaign(id:$id, campaignId:createCampaignMutation(name:"test"){
      _id`
```

I would like to avoid calling:
```
this.props.createCampaignMutation({variables: ... })
```
and then
```
this.createClientCampaignMutation({variables: ... })
```

**Comment by calebmer** [comment]
You should be able to do:

```js
this.props.createCampaignMutation({
  variables: { ... },
}).then(({ data }) => {
  this.props.createClientCampaignMutation({
    variables: {
      id: data.addCampaign._id,
      ...
    },
  });
});
```

Let me know if you have any more questions 😊

**Comment by etaheri** [comment]
Amazing! Thanks calebmer!  

Is it possible to nest the mutations in the graphql statement? Or is that not possible?

**Comment by calebmer** [comment]
No, not at the moment 😣

Although I have thought about making a GraphQL library that implements this with directives for PostGraphQL (see https://github.com/calebmer/postgraphql/issues/361). This does not work in GraphQL today, but it should be easy to write a small library which implements it:

```graphql
mutation A($text: String!) {
  createTodo(text: $text) {
    id @provideVariable(name: "id")
    ...
  }
  toggleTodoCopmlete(id: $id) {
    ...
  }
}
```
