### ISSUE TITLE
Data from props function is empty when outer variable is changed. updateQuery doesn't re-render wrapped component.

### ISSUE THREAD

**Issue by NiallBrickell** [apollographql/react-apollo#482]
I'm using Redux & Apollo to wrap a component, ie:

```
const ApolloComponent = graphql(GetSearchResult, {
  options: ({ search }) => ({
    variables: {
      search,
    },
  }),
  props: ({ data }) => {
    // When `search` is updated in Redux, no `data.result` is returned here.
    return {
      result: data.result,
    };
  },
})(Component);

const mapStateToProps = state => ({
  search: state.search,
});
const mapDispatchToProps = {
  searchAction,
};
const ReduxComponent = [react-redux].connect(mapStateToProps, mapDispatchToProps)(ApolloComponent);
```

When the outer variable from Redux, `search`, is updated, a new request is made the the GQL server and the correct response, with data, is returned. This data is stored in Apollo-client's redux store, however the result isn't returned in the `data` object in the `props` func params.

Not sure if this is an issue in `react-apollo` or `apollo-client`.

I've tried doing this:
```
graphql(...
  props: ({ data }) => {
    if (!data.result && !data.loading) {
      data.fetchMore({
        variables: {
          search,
        },
        updateQuery: (prev, { fetchMoreResult }) => ({
          // fetchMoreResult.data.result exists! But wrapped component doesn't re-render
          ...prev,
          result: fetchMoreResult.data.result,
        }),
      });
    }
    return {
      result: data.result,
    };
  },
...)
```

However, while this returns the correct data in the `data` param, it doesn't re-render the wrapped component!

I've also tried using `updateQuery` in the traditional way:
```
graphql(...
  props: ({ data, ownProps }) => ({
    result: data.result,
    
    // Actions
    searchAction: (str) => {
      data.fetchMore({
        variables: {
          search,
        },
        updateQuery: (prev, { fetchMoreResult }) => ({
          // fetchMoreResult.data.result exists! But wrapped component doesn't re-render
          ...prev,
          result: fetchMoreResult.data.result,
        }),
      });
      ownProps.searchAction(str);
    },
  }),
...)
```
In this situation the data is returned correctly, but again the wrapped component isn't re-rendered. Two requests also get created - I'm guessing one from `fetchMore` and one from the `graphql` wrapper being re-rendered by react-redux.

Are these bugs, or am I using the library incorrectly?

**Comment by calebmer** [comment]
You definitely shouldn’t be calling `fetchMore` from the `props` function, although I don’t think that’s your error 😊

Could you reproduce this error using [`react-apollo-error-template`](https://github.com/apollographql/react-apollo-error-template)? It would go a long way in helping us debug your issue.

**Comment by NiallBrickell** [comment]
Ah so I was using `query: ...` in options to conditionally use a query which seems to throw it off. Simplified the code to just use the redux actions and it's all working 😊
