### ISSUE TITLE
Component keeps polling for data even though that was never specified after remounting it

### ISSUE THREAD

**Issue by leoasis** [apollographql/react-apollo#483]
## Steps to Reproduce

I've started off from the Pokemon example in the repo, I just changed the app component to this:

```js
class App extends Component {
  state = { showPokemon: true, startAndStop: true };

  handleCheckboxChange = () => {
    this.setState({ startAndStop: !this.state.startAndStop });
  };

  handleButtonClick = () => {
    this.setState({ showPokemon: !this.state.showPokemon });
  };

  render() {
    return (
      <ApolloProvider client={client}>
        <div>
          {this.state.showPokemon && <Pokemon startAndStop={this.state.startAndStop} />}
          <label>
            <input
              type="checkbox"
              checked={this.state.startAndStop}
              onChange={this.handleCheckboxChange}
            />
            Start and stop polling
          </label>

          <button onClick={this.handleButtonClick}>
            {this.state.showPokemon ? 'Hide Pokemon' : 'Show Pokemon'}
          </button>
        </div>
      </ApolloProvider>
    );
  }
}
```

And made the `Pokemon` component a class component like this:

```js
export class Pokemon extends React.Component {
  componentDidMount() {
    if (this.props.startAndStop) {
      this.props.data.startPolling(2000);
    }
  }

  componentWillReceiveProps(nextProps) {
    if (nextProps.startAndStop) {
      this.props.data.stopPolling();
    }
  }

  render() {
    const { data: { loading, pokemon, error } } = this.props;

    if (loading) return <div>Loading</div>;
    if (error) return <h1>ERROR</h1>;
    return (
      <div>
        {pokemon && (
          <div>
            <h3>{pokemon.name}</h3>
            <img alt={pokemon.name} src={pokemon.image} />
          </div>
        )}
      </div>
    );
  }
}
```

Basically the idea is that from the `App` I can toggle wether to show or not the `Pokemon` component and wether to start and stop polling for data in that component as well. In `Pokemon`, if `startAndStop` is set, it starts polling on did mount, and stops polling whenever the component receives new props.

With this, the steps to reproduce the issue are:

1. Start the app, notice that the `Pokemon` component mounts and starts polling. Whenever it gets new data from the graphql query, it stops polling since it executes `componentWillReceiveProps`. As expected, the component is not polling for data since it stopped.
2. Uncheck the checkbox to start and stop polling and click the button to hide the pokemon component.
3. Click the button again to show the pokemon component, while leaving the checkbox unchecked, so that the component mounts but it doesn't attempt to start or stop polling.
4. Check the Network tab in the dev tools, notice that even when the component never started polling this second time, the polling requests are being made.

### Buggy Behavior

It seems that a component can land in a weird state when starting and stopping polling manually and then remounting it, making the poll queries still being run even if a poll was never started the second time.

### Expected Behavior

The expected behavior is that the component should not trigger more queries from polling the second time it mounts, since it never started polling.

### Version
- apollo-client@0.8.7
- react-apollo@0.11.2

**Comment by leoasis** [comment]
Looks like the problem is around the fact that since we're reusing the same observable query, and `stopPolling` doesn't reset the pollInterval option, the query when it is reused with `setOptions` (which only uses the options defined in the `graphql` HoC, and doesn't contain `pollInterval`) ends up setting the last `pollInterval` used, and ultimately restarts the polling in `setUpQuery`.

I think this would all be solved if `stopPolling` removed the `pollInterval` option, or set it to `undefined` or something. Is there a reason this is not the case?

**Comment by helfer** [comment]
@leoasis Thanks for the bug report! My guess would be that we simply didn't anticipate this problem. We would gladly merge a PR of yours that sets `pollInterval` to `undefined` in `stopPolling()`!

**Comment by leoasis** [comment]
Awesome! Will send a PR then 😄 thanks!

**Comment by leoasis** [comment]
The fix was already merged in apollo-client
