### ISSUE TITLE
How do I handle localization?

### ISSUE THREAD

**Issue by developer239** [apollographql/react-apollo#491]
It would be extremelly helpful if you could provide simple localization guide.

a) How to handle client localization possibly with react-intl
b) How to handle localization when communicating with graphql server

Thank you :)

## Steps to Reproduce

Google "apollographql react-appollo localization".

### Buggy Behavior

There are 0 relevant results.

### Expected Behavior

There should be at least 1 relevant result.

### Version
All versions.

**Comment by calebmer** [comment]
This is a question that is best suited for the [Apollo Slack](http://www.apollodata.com/#slack), or StackOverflow 😊

`react-apollo` has no opinions on how localization should be done, allowing you to handle localization in the way that is best for your app!
