### ISSUE TITLE
Call client.resetStore() from dispatched action

### ISSUE THREAD

**Issue by colophonemes** [apollographql/react-apollo#494]
It'd be good to be able to call the equivalent of `client.resetStore()` by dispatching an action, say from within a [saga](https://redux-saga.github.io/redux-saga/docs/api/index.html)

For example:

```js
// rootSagas.js
export function* watchLogout () {
  yield takeEvery(LOGOUT, function* () {
    cookie.remove('token')
    yield put({type: 'APOLLO_STORE_RESET' /* observableQueryIds here maybe??? */})
    yield put(push('/'))
  })
}
```

Context: https://github.com/apollographql/apollo-client/issues/1349

**Comment by helfer** [comment]
@colophonemes I don't know the ins and outs of redux-saga, but can't you just call `client.resetStore()` directly and then let that dispatch the action? Is it critical that the action be dispatched through redux-saga's `put` function?

**Comment by colophonemes** [comment]
The problem is accessing the current instance of `client`. Because sagas are isolated from components, they don't have access to component props. I can access the current instance of `client` as a prop if I wire up a component using the `withApollo` HOC from `react-apollo`, but I'm not sure how to get to it from outside of the component.

**Comment by colophonemes** [comment]
Yeah, that works fine. I was being an idiot and trying to figure out how to get the current instance of `client` from the component hierarchy. Derp. Importing the client into the sagas and calling the `.resetStore()` directly worked like a charm.

Thanks for the help.
