### ISSUE TITLE
Uncaught (in react-apollo) errors being thrown on re-render

### ISSUE THREAD

**Issue by davidye** [apollographql/react-apollo#503]
## Steps to Reproduce

1) Create a component wrapped by graphql(...)
2) Make the query return a error
3) Re-rendering component several times will trigger "Uncaught (in react-apollo)" errors

- apollo-client@0.10.1
- react-apollo@0.13.2

**Comment by calebmer** [comment]
This message will log if you are not handling errors in your render method 😊. Make sure to handle `data.error` and the uncaught messages will go away. The following will not log an error:

```js
render() {
  const { data: { loading, error, ...rest } } = this.props;
  if (loading) {
    return <div>Loading...</div>;
  } else if (error) {
    return <div>Error...</div>;
  } else {
    // Render your UI...
  }
}
```

However, the following code will log an error:

```js
render() {
  const { data: { loading, ...rest } } = this.props;
  if (loading) {
    return <div>Loading...</div>;
  } else {
    // Render your UI...
  }
}
```

Notice how `error` is not handled in the second example.

This is intended behavior 😊

**Comment by davidye** [comment]
I believe I am doing this. On the very first render no error is logged. It's only subsequent re-renders that seem to cause this. I'll see if I can more details and narrow this down more.

**Comment by davidye** [comment]
@calebmer I traced this down the error to this usage pattern:

```
// Uncaught Error Message (logged after a second render, not the initial render)
compose(
  graphql(...),
  connect(...),
)(Component)

// No Error Message
compose(
  connect(...),
  graphql(...),
)(Component)
```

Component does handle error in its render() method, but the ordering within compose() matters. The documentation here will also trigger this error: http://dev.apollodata.com/react/higher-order-components.html
