### ISSUE TITLE
Return multiple ids from customResolvers. 

### ISSUE THREAD

**Issue by nosovsh** [apollographql/react-apollo#508]
Is it possible to use `customResolvers` option for queries that return an array of objects?
Talking about example from http://dev.apollodata.com/react/cache-updates.html#cacheRedirect lets say I have a method `booksById` that look like:
```
query ListViewByIds($ids: Array) {
  booksByIds(ids: $ids) {
    id
    title
    abstract
  }
}
```
Is it possible to write customer resolver to give apollo a hint how to check cache for this request? Something like this:
```
const client = new ApolloClient({
      networkInterface,
      customResolvers: {
        Query: {
          book: (_, args) => toIdValue(dataIdFromObject({ __typename: 'book', id: args['id'] })),
          booksById: (_, args) => {
            // some code to return multiple ids to check cache
            return args['ids'].map(id => toIdValue(dataIdFromObject({ __typename: 'book', id: id})))
          }
        },
      },
      dataIdFromObject,
    });
```

If it is not possible then consider this as a feature request. if it is possible then please tell me how to write this resolver correctly and I will make a PR to put it in docs.
Thanks

**Comment by calebmer** [comment]
Hmm, this should work. cc @helfer is there any reason this shouldn’t work?

**Comment by nosovsh** [comment]
@calebmer After you said that it is possible I've found mistake in my code and seems its working, thanks :) Maybe it should be added to docs for clarity?

**Comment by calebmer** [comment]
Yep, if you want to submit a PR @nosovsh we’d be happy to merge 😊
