### ISSUE TITLE
The prop `client` is marked as required in `withApollo(Signin)`, but its value is `undefined`

### ISSUE THREAD

**Issue by ryancole** [apollographql/react-apollo#511]
Whenever I try to specify `client` as a prop type, I get this warning that it's initially `undefined`. I also get this warning when specifying `mutate` as a prop type.

## Steps to Reproduce

Unfortunately, I do not have a condensed example ready to go. I'm encountering this warning in a project that uses several context providers (react hot loader, react router and apollo client).

I have many components, making use of the `graphql` decorator, specifying `data` as a prop type. No warning there, likely because it's not specified as required.

I have one component making use of the `withApollo` decorator, because I need to run a one-off query. I have `client` specified as a required prop type, as described in the documentation. I'm just now noticing that this prop type is causing a run-time warning.

I also have a second component that uses `graphql` decorator, but includes a mutation. I'm also seeing a warning when I specify a required `mutate` function prop type.

Here's a link to my component that uses `withApollo`. This component is causing a run-time prop type warning because `client` is `undefined` ...

https://gist.github.com/ryancole/ac9e9a18878b93e48f0adc827fcf84e3#file-apollo-js-L10

... but, strangely, when I attempt to make use of the `client` prop value, it's there and everything works fine ...

https://gist.github.com/ryancole/ac9e9a18878b93e48f0adc827fcf84e3#file-apollo-js-L32-L35

### Version
- apollo-client@0.10.0
- react-apollo@0.13.1

**Comment by calebmer** [comment]
Hmm, the only chance where the client may be undefined is if it were not defined in the context which would throw an error here: https://github.com/apollographql/react-apollo/blob/85700147a6d3a2229fa850186a7397a6afafbd5c/src/graphql.tsx#L116

Without a small test case reproducing your error, this will be really hard to track down and fix. Especially because of your hot loading setup 😣

If you could reproduce the bug with [`react-apollo-error-template`](https://github.com/apollographql/react-apollo-error-template) it would go a _long_ way in helping us debug and fix your issue.

**Comment by ryancole** [comment]
Alright. I'll give it a shot.

**Comment by ryancole** [comment]
I removed the hot reloading all together and still see the warning. I don't recall having this warning originally, and I had always used hot reloading, so I don't think it has to do with that anymore.

I recently switched to react router 4 and I have a feeling it started appearing after that. I'll be trying to follow that assumption for now. 

I can't quite create a reproduction case yet because I'm not sure what's causing it yet.

**Comment by ryancole** [comment]
Hmm. If I add a constructor and log the props for my component (in the original post), it has `client` and it is indeed an instance of `ApolloClient`.

**Comment by ryancole** [comment]
@calebmer well, I've narrowed it down to having something to do with using `@withApollo` decorator. When I do not use `@withApollo`, but instead `export default withApollo(Signin)`, I no longer see the warning.

I had forked the error template repo you provided, and started coding out the scenario, but create-react-app does not seem to support `@decorators`.

Does this information help more? Now that I know it has to do with decorators, and likely the combo of react router 4, I could maybe throw together a test project but it'd be a bit more time consuming without create-react-app.

**Comment by ryancole** [comment]
I'm looking at the webpack / babel generated output from my own project and I think I see the issue.

In my project, I'm exporting my component class, with decorators, in the following way ...

```
@withApollo
export default class Foo {
  static propTypes = { ... };
}
```

Webpack and babel generate output like so ...

```
let Foo = withApollo(class Foo { ... })
Foo.propTypes = { ... };
```

Well, in that scenario, `Foo` is not my `Foo` class, it is `WithApollo`. So, these prop types are being applied not to my component class but instead `WithApollo`.

If I switch away from decorators to just `export default withApollo(Foo)`, then the webpack and babel output is a bit more sane and works as expected.

Kind of sounds like a gotcha of using decorators, at the moment. This issue seems more related to the webpack / babel output. Not sure how I haven't seen this before, yet.

**Comment by calebmer** [comment]
Yep. This is definitely a Babel error 😣

Looking at the [`babel-plugin-transform-decorators-legacy`](https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy) repo it would appear that your plugin order matters in this case! From the `README`:

> #### NOTE: Order of Plugins Matters!
> If you are including your plugins manually and using `transform-class-properties`, make sure that `transform-decorators-legacy` comes *before* `transform-class-properties`.
>
> ```js
> /// WRONG
>
> "plugins": [
>   "transform-class-properties",
>   "transform-decorators-legacy"
> ]
>
> // RIGHT
>
> "plugins": [
>   "transform-decorators-legacy",
>   "transform-class-properties"
> ]
> ```

Let me know if that fixes it 😊

**Comment by ryancole** [comment]
Yup. That fixes it. I indeed had the order the other way around.
