### ISSUE TITLE
Ensure the recycler keys on the client

### ISSUE THREAD

**Issue by tmeasday** [apollographql/react-apollo#513]
See this series of comments: https://github.com/apollographql/react-apollo/pull/462#issuecomment-284306070

The principal issue is in testing, where the same HoC will cache queries even if you render a new tree with a completely different client.

And @calebmer's proposed solution:

> A solution would be to, as you suggest, create a WeakMap<ApolloClient, ObservableQueryRecycler> and then we use the recycler for whichever client reference we have at the time.

**Comment by rcoedo** [comment]
I stumbled upon this problem yesterday and I was really confused. In my case, I got problems using react-apollo with [storybook](https://github.com/storybooks/storybook). I made a small playground that shows the problem [here](https://github.com/rcoedo/react-apollo-playground).

**Comment by jbaxleyiii** [comment]
There is a PR in progress on this! Thanks @probot-stale[bot]
