### ISSUE TITLE
Uncaught errors message when using compose()

### ISSUE THREAD

**Issue by davidye** [apollographql/react-apollo#517]
When using compose() with connect() and graphql(), the ordering matters. Using graphql() and then connect() will trigger the 'Uncaught errors message' even if the component handles the error in tis render method. The documentation here would also trigger this error: http://dev.apollodata.com/react/higher-order-components.html

```
// Uncaught error message (logged after a second render, not the initial render)
compose(
  graphql(...),
  connect(...),
)(Component)

// No error message
compose(
  connect(...),
  graphql(...),
)(Component)
```

**Comment by davidye** [comment]
Update: sorry very confused... if I just use

`
graphql(Component)
`

I also get these errors. It seems like wrapping a connect() around it is what fixes this issue for me, but I have no idea why that might be.

**Comment by calebmer** [comment]
You need to make sure that you are handling your errors. That is in your component you need to:

```js
const { data } = this.props;
console.log(data.error); // Handle the error somehow.
```

The warning is disabled when you access the `data.error` property.  `react-redux` is probably accessing the error property and (unfortunately) disabling the error.

Handling the error in your component should stop triggering an error 👍
