### ISSUE TITLE
Weird loading prop behaviour on external prop change

### ISSUE THREAD

**Issue by kouak** [apollographql/react-apollo#518]
Hello,

There seems to be some kind of race condition issue with how `watchQuery` reacts to external prop changes.

### Versions
* apollo-client 0.10.1
* react-apollo 0.13.2

### Steps to reproduce
* Have a simple graphql component polling a slow graphql endpoint (just add delay in your resolvers)
* Make an external prop change while a query is in flight

A second prop change afterwards seems to set things right.

Video demonstrating the issue : https://gfycat.com/MeatyMeanFurseal

Repro code : https://gist.github.com/kouak/8d509b124a0a0dbe5dc9abef39b096df

### Expected behaviour
I should expect my component to receive the `data.loading` prop only on initial mount. Changing props while the query is in flight should not change this behaviour (at least as long as the prop change didn't generate new query variables, invalidating the inflight query).

### Actual behaviour
Component stuck in loading state (`data.loading: true` and `networkStatus: 6`) after the query comes back from the endpoint.

This could seem minor but consider this case :
```Javascript
const withGraphQL = grahql(SomeQuery, {});
const withReduxState = connect(
  () => ({
    newPropAfterEachReduxAction: [],
  }),
);

const Component = ( ... ) => ( ... );

const WorksFine = compose(
  withGraphQL,
  withReduxState,
)(Component);

const DoesNotWork = compose(
  withReduxState,
  withGraphQL,
)(Component);
```

`DoesNotWork` will flash at each request :
* query starts
* `APOLLO_QUERY_INIT` is dispatched
* `mapStateToProps` generates a new set of props
* `DoesNotWork` gets stuck in loading state
* query comes back
* `APOLLO_QUERY_RESULT` is dispatched
* `mapStateToProps` generates a new set of props
* `DoesNotWork` gets unstuck

This type of redux selectors (`mapStateToProps` generating new objects after each call) is definitely an antipattern in the redux world but I suppose they are pretty common amongst codebases since they only affect performance moderately.

**Comment by calebmer** [comment]
This seems related to https://github.com/apollographql/apollo-client/issues/1186. Thank you so much for the detailed error report! Could you go one step further and get your reproduction running in https://github.com/apollographql/react-apollo-error-template? It will go a long way in helping us debug the issue 😊

**Comment by kouak** [comment]
Sure thing, repro here : https://github.com/kouak/react-apollo-error-template/tree/loading-stuck-repro

**Comment by derek-duncan** [comment]
I'm experiencing this error as well. Any progress here or ways I can help @helfer?

**Comment by Florentijn** [comment]
What is the status of this? :)

**Comment by tylerjbainbridge** [comment]
I also have this issue -- would love to help/know the progress this.
