### ISSUE TITLE
Make sure all important things from Apollo Client are re-exported

### ISSUE THREAD

**Issue by helfer** [apollographql/react-apollo#521]
Right now this package only re-exports `ApolloClient` and `createNetworkInterface`, but it should probably re-export a lot more things.

**Comment by calebmer** [comment]
We should just re-export everything. It does not hurt 😉

**Comment by benhjames** [comment]
It would be great to have `IntrospectionFragmentMatcher` re-exported - found myself wanting that today!

**Comment by helfer** [comment]
Hey @benhjames, would you mind making a PR that re-exports everything?

**Comment by benhjames** [comment]
Done as #650. :)
