### ISSUE TITLE
Wrong build on Yarn (1.0.0-rc2)

### ISSUE THREAD

**Issue by rovansteen** [apollographql/react-apollo#524]
There seems to be a wrong build on Yarn for version `1.0.0-rc2`. When running `yarn` it resolves to [this build](https://registry.yarnpkg.com/react-apollo/-/react-apollo-1.0.0-rc2.tgz#26da3dfd8cd9542456d7069a83a2f999f6125980). But that seems to be a wrong version or build, it tries to reference `apollo-client/errors` but that does not exist.

Running `npm install` works fine and fetches the correct version, so I'm guessing this is an issue with Yarn cache or something?

**Comment by swernerx** [comment]
Interestinly the version inside `package.json` for "react-apollo" is actually `"version": "1.0.0-rc2",`

**Comment by swernerx** [comment]
Just letting you know. Doing a cleanup of "node_modules", executing "yarn cache clean" and then doing another "yarn install" does not fix anything at all.

**Comment by dsifford** [comment]
Confirmed for me as well. `npm install` works, `yarn` does not.

**Comment by swernerx** [comment]
Tested this too. Works with npm. Unfortunately our CI env is using Yarn... a fix would be very appreciated.

**Comment by calebmer** [comment]
It appears that a long time ago a version of `react-apollo` was published with a version `1.0.0-rc2`. This is *not* the latest version of `react-apollo`. The latest version is `1.0.0-rc.2`. Note the `.` between the `rc` and the `2`. That version should work. Sorry for the confusion! If this does not fix the issue let us reopen.

**Comment by rovansteen** [comment]
@calebmer it looks like Yarn ignores the dot. I have `1.0.0-rc.2` in my package.json but even after removing `node_modules` folder and `yarn.lock` file it still fetches the one without the dot.

**Comment by vlasenko** [comment]
@calebmer The problem is that for `yarn` users the dependency line in `package.json`:
```"react-apollo": "^1.0.0-rc.2"```
(note the dot) resolves to that old `react-apollo` `1.0.0-rc2`, please also note that for `yarn` users
```"react-apollo": "1.0.0-rc.2"``` (note the absence of `^`) resolves correctly to the latest `react-apollo`
So it might be the case that there is issue with `yarn` thinking the old package is the newest actually.

**Comment by rovansteen** [comment]
Ah of course. The caret was the issue here, thanks @vlasenko

**Comment by vlasenko** [comment]
@calebmer and @rovansteen Please also see this issue in Yarn, which is really not a `yarn` bug:
https://github.com/yarnpkg/yarn/issues/2883
but it helps to understand how yarn determines the latest version of the package

**Comment by stubailo** [comment]
Oh boy!

Maybe we can unpublish that other version? Usually that sounds like a bad idea, but in this case it's clearly not something people should be downloading.

**Comment by helfer** [comment]
@stubailo yeah, that's what I ended up doing. I unpublished 1.0.0-rc1 and 1.0.0-rc2
