### ISSUE TITLE
rc2 throws error during import 

### ISSUE THREAD

**Issue by swernerx** [apollographql/react-apollo#526]
Updating to rc2 I get the following error during build.

```
ERROR in ./~/react-apollo/graphql.js
Module not found: Error: Can't resolve 'apollo-client/errors' in '/Users/sebastian/Workspace/sebastian-software/edgestack/node_modules/react-apollo'
 @ ./~/react-apollo/graphql.js 14:15-46
 @ ./~/react-apollo/index.js
 @ ./src/client/index.js
```

I am currently not sure what the replacement for the "errors" import is. I figured when two related packages have the same version number that they were somehow tested together ;) - Hopefully that's a quick fix and we have not to wait too long for rc3.

**Comment by swernerx** [comment]
This is what is in my `package.json`: 

⚡ grep apollo package.json 
    "apollo-client": "^1.0.0-rc.2",
    "react-apollo": "^1.0.0-rc.2",

**Comment by swernerx** [comment]
Possibly duplicate of https://github.com/apollographql/react-apollo/issues/524

**Comment by calebmer** [comment]
In `react-apollo` 1.0 you do not need to install `apollo-client` or `graphql-tag` 😊. They are dependencies of `react-apollo` now and their exports are re-exported from `react-apollo`. Try removing your dependency on `apollo-client` and let me know if that fixes things 👍

**Comment by calebmer** [comment]
From #524:

It appears that a long time ago a version of `react-apollo` was published with a version `1.0.0-rc2`. This is *not* the latest version of `react-apollo`. The latest version is `1.0.0-rc.2`. Note the `.` between the `rc` and the `2`. That version should work. Sorry for the confusion! If this does not fix the issue let us reopen.

**Comment by dsifford** [comment]
@calebmer That did the trick! Thanks 😄

**Comment by swernerx** [comment]
Good idea by @calebmer 

    In react-apollo 1.0 you do not need to install apollo-client or graphql-tag

Unfortunately does not contain everything. At the moment the additional export code looks like:

```js
export { default as ApolloClient, createNetworkInterface } from 'apollo-client';
export { default as gql } from 'graphql-tag'
```

This does not seem to contain:

1. Webpack loader for gql
2. `createBatchingNetworkInterface` which is highly needed

+ a ton of other stuff.  The export from Apollo-Client contains these symbols:

```js
export { createNetworkInterface, createBatchingNetworkInterface, createApolloStore, createApolloReducer, readQueryFromStore, writeQueryToStore, print as printAST, addTypenameToDocument, createFragmentMap, NetworkStatus, ApolloError, getQueryDefinition, getFragmentDefinitions, toIdValue, HTTPFetchNetworkInterface, ObservableQuery, ApolloClient };
```

Not sure if we should pass over all these symbols, I just think that the current promise of "no need to install" is actually not true (yet).

**Comment by swernerx** [comment]
@calebmer for the basic imports of `createNetworkInterface` and `ApolloClient` the solution via importing through `react-apollo` works fine for me together with Yarn.

**Comment by calebmer** [comment]
@swernerx you want to submit a PR that exports everything from `apollo-client`? There is no reason we shouldn’t 😊

We would change the exports to:

```js
export { default as ApolloClient } from 'apollo-client';
export * from 'apollo-client';
```

The GraphQL tag loader will probably stay in `graphql-tag` for now, however.

**Comment by stubailo** [comment]
@calebmer we were talking about moving the webpack into a separate package, which would make sense since you never need it at runtime.

**Comment by jaydenseric** [comment]
@calebmer Those would be much better exports. Just got stung; assumed that `createBatchingNetworkInterface` was be available like `createNetworkInterface`.
