### ISSUE TITLE
Broken Array index, on query data response

### ISSUE THREAD

**Issue by manuelLandreau** [apollographql/react-apollo#533]
Hi, maybe i'm wrong, but i've been trough a strange issue, the response data array indexes were broken.
Here's my component:

```
import React from 'react';
import { gql, graphql } from 'react-apollo';

const Talk = ({data}) => {

    const talks = Object.assign([], data.talks);
    const talk = Object.assign({}, talks[0]);
    const user = Object.assign({}, talk.user);

    return (
        <div>
            <p>
                {talk.text}
            </p>
            <small class="fr">{user.username}</small>
            <br/>
            <button class="fr" onClick={() => data.refetch()}>Next</button>
            <div class="clearfix"></div>
        </div>
    );
}

export default graphql(gql`
  query SingleQueryType {talks{text, _id}}
`)(Talk);
```

So i had to assign the Array, and then the object inside which is wierd because it return the exact same type of object.

Is somebody got a tip to make it cleaner, or just explain this.
thx.

**Comment by calebmer** [comment]
What are you trying to do hear? What’s not working? Why do you have `Object.assign`?

Perhaps it may help to create a reproduction of your use case with [`react-apollo-error-template`](https://github.com/apollographql/react-apollo-error-template) 😊

**Comment by manuelLandreau** [comment]
Actually I can't access to the response data, when I console.log(data) and everything 's ok, but I can't acces to them like data.talks[0], ('0' of undefined), in graphiQL everything works (like this exemple) but i have to reassign datas..
weird no ?

**Comment by helfer** [comment]
@manuelLandreau I strongly suspect that you're rendering your component while the data is still loading. You should always check `data.loading` and `data.error` before rendering.
