### ISSUE TITLE
Broken link on mutate.options.update docs

### ISSUE THREAD

**Issue by lucasconstantino** [apollographql/react-apollo#543]
**Where:** http://dev.apollodata.com/react/api.html#graphql-mutation-options\.update
**Which paragraph:** 

> For more information on updating your cache after a mutation with the options.update function make sure to read the [Apollo Client technical documentation on the subject](http://dev.apollodata.com/core/data-control.html#updating-the-cache-after-a-mutation).

**Broken link:** http://dev.apollodata.com/core/data-control.html#updating-the-cache-after-a-mutation

I did not submit a pull request for I don't now where should this link point to.

**Comment by helfer** [comment]
Thanks @lucasconstantino , fix in the works here: https://github.com/apollographql/react-docs/pull/178
