### ISSUE TITLE
ApolloProvider/graphql should not put `store` on context

### ISSUE THREAD

**Issue by wmertens** [apollographql/react-apollo#547]
If you use Redux and react-apollo without wanting to share the store, `ApolloProvider` and `graphql` will put Apollo's `store` on the child context.

This overrides the `store` passed to react-redux's `Provider`, even if `Provider` is mounted inside `ApolloProvider`.

IMHO, react-apollo should only add `client` to context, and if you want access to Apollo's Redux store, you can store that on e.g. `client.store`. (even better: name the context `apollo`, and you can put whatever you like under that without clashing with other context provided by other projects)

**Comment by stubailo** [comment]
That's a pretty good point!

**Comment by helfer** [comment]
@jbaxleyiii what was the intended usage here? Was the idea that `ApolloProvider` would replace the react-redux provider?

**Comment by wmertens** [comment]
Even if that is the case, you can accommodate both behaviors by passing the
parent store from context if one is not provided. I don't understand why
@graphql provides childContext, though.

**Comment by jbaxleyiii** [comment]
@helfer it was originally. However, I agree with this issue and think we should remove the store! @wmertens could you PR this?

**Comment by wmertens** [comment]
Done :)
