### ISSUE TITLE
queryVariables in updateQuery returns initial variables

### ISSUE THREAD

**Issue by alfonsoperez** [apollographql/react-apollo#566]
## Steps to Reproduce

Describe how to reproduce this issue.

https://github.com/alfonsoperez/react-apollo-error-template/tree/bug/props-not-passed-and-setQueryVariables

### Buggy Behavior

- updateQuery's queryVariables giving me the initial variables but not those that were used in `fetchMore` call.

### Expected Behavior

- updateQuery's queryVariables should be the variables that were used as `variables` in the `fetchMore` call

### Version
- react-apollo@1.0.0-rc.3

**Comment by simenbrekken** [comment]
It looks like the test case for ["exposes fetchMore as part of the props api"](https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries.test.tsx#L1166) incorrectly compares `props.data.variables` to `variables` when it should be comparing against `variables2` to be correct.

**Comment by alfonsoperez** [comment]
@simenbrekken It seems that that test doesn't arrive to `componentWillReceiveProps`. Adding a `expect(true).toBe(false);` in the first line inside it passes the test equally.

**Comment by helfer** [comment]
@simenbrekken @alfonsoperez if someone could make a PR to fix the test, that would be great! If the test fails afterwards, we can take it from there.

**Comment by simenbrekken** [comment]
@alfonsoperez Were you able to get the test to fail?

**Comment by alfonsoperez** [comment]
@simenbrekken see https://github.com/apollographql/react-apollo/pull/608
