### ISSUE TITLE
renderToStringWithData does not wait for `APOLLO_QUERY_STOP` action

### ISSUE THREAD

**Issue by langpavel** [apollographql/react-apollo#567]
If you use `renderToStringWithData` on server you will see that `APOLLO_QUERY_STOP` is dispatched after accepting promise.
So you cannot rely on this redux action.

It will be helpful if someone explain meaning of `APOLLO_QUERY_STOP` action.

> code samples are greatly appreciated!

You can clone [`feature/apollo`](https://github.com/kriasoft/react-starter-kit/tree/feature/apollo) or [`feature/react-intl` of React Starter Kit](https://github.com/kriasoft/react-starter-kit/tree/feature/react-intl)

### Buggy Behavior

`renderToStringWithData` fires `APOLLO_QUERY_STOP` action after promise is fulfilled

### Expected Behavior

`renderToStringWithData` should keep actions in balance

### Version
```
    "apollo-client": "^1.0.0-rc.2",
    "react-apollo": "^1.0.0-rc.2",
```

### My SSR roundtrip (slightly customized project)

```
 * @@INIT: { type: '@@INIT' }
 * SET_RUNTIME_VARIABLE: { name: 'availableLocales', value: [ 'cs-CZ' ] }
 * loading-bar/SHOW: { type: 'loading-bar/SHOW' }
 * SET_LOCALE_START: { locale: 'cs-CZ' }
 * loading-bar/HIDE: { type: 'loading-bar/HIDE' }
 * SET_LOCALE_SUCCESS: locale cs-CZ: 8 messages
 * APOLLO_QUERY_INIT: queryId:2 variables:{ after: null, first: 10, before: null, last: null }
   query articleList($after: String, $first: Int, $before: String, $last: Int) { articles(after: $after, first: $first, before: $before, last: $last) { edges { node { ...articleListFragment __typename } cursor __typename } pageInfo { ...pageInfoFragment __typename } __typename } } fragment articleListFragment on Article { id articleId slug title perex published created updated keywords tags { tagId position __typename } __typename } fragment pageInfoFragment on PageInfo { hasNextPage hasPreviousPage startCursor endCursor __typename } 
 * APOLLO_QUERY_RESULT: queryId:2
   { data: { articles: { edges: [Object], pageInfo: [Object], __typename: 'ArticleConnection' } } }
ArticleList render true 1 // <-- console.log('ArticleList render', this.props.data.loading, this.props.data.networkStatus);
// THIS IS DIFFERENT BUG I CANNOT DESCRIBE YET :-\
ArticleList render true 1 // <-- console.log('ArticleList render', this.props.data.loading, this.props.data.networkStatus);
Serializing store... // ROUND TRIP FINISHED
 * APOLLO_QUERY_STOP: queryId:2
```

**Comment by langpavel** [comment]
@stubailo @calebmer please.. :pray: I really don't know what's causing this.. opinions, speculations welcomed.. I will prepare PR if I someone gives me a clue!

**Comment by stubailo** [comment]
The `APOLLO_QUERY_STOP` action is fired when `react-apollo` unsubscribes from the query, and there are no more subscribers. It's not currently intended to correlate in any way with the server-side rendering promise.

What are you trying to achieve by listening for that action?

**Comment by langpavel** [comment]
@stubailo Thanks for clarification

I'm observing server actions when debugging. But

I asked myself how to present some pending action on client. If I reate redux action to count up and down Apollo actions, this one will not serialize in store because it will happen after. So how I can implement something like [react-redux-loading-bar](https://github.com/mironov/react-redux-loading-bar)?

**Comment by helfer** [comment]
@langpavel I'm not 100% sure what you mean, but for pending requests/queries could you look at APOLLO_QUERY_INIT, APOLLO_QUERY_RESULT_CLIENT and APOLLO_QUERY_RESULT?

**Comment by langpavel** [comment]
Thanks @helfer.
Can `APOLLO_QUERY_STOP` affect redux store?
Because if yes, it means that I serializing store earlier than I should..
I discovered, that simply delaying response with timeout 0 can do the job, with bluebird like this:
```js
await Promise.delay(0);
```
