### ISSUE TITLE
Invariant Violation: Operation is expecting a variable

### ISSUE THREAD

**Issue by mxmtsk** [apollographql/react-apollo#578]
When I execute a mutation with Apollo I get the following error, everything else works.

>Invariant Violation: The operation 'login' wrapping 'Login' is expecting a variable: 'email' but it was not found in the props passed to 'Apollo(Login)'

I have no idea what the issue is trying to tell me.

My component looks like this:
```Javascript
    class Login extends React.Component {
      static propTypes = {
        login: React.PropTypes.func.isRequired,
      }

      loginUser = (email, password) => {
        this.props.login({
          variables: {
            email,
            password,
          },
        }).then(({ data }) => {
          // does get resolved, I have all the data from the response
          console.log(data);
        }).catch((error) => {
          console.log(error);
        });
      }

      render() {
        return (
          <Button onClick={() => { this.loginUser('my@email.com', 'test'); }}>Try apollo</Button>
        );
      }
    }

    const login = gql`
      mutation login($email: String!, $password: String!) {
        login(email: $email, password: $password) {
          id
          email
          token
        }
      }
    `;

    export default inject('store')(withStyles(s)(graphql(login, { name: 'login' })(observer(Login))));
```
### Version
- react-apollo@1.0.0-rc.3

**Comment by helfer** [comment]
@mxmtsk Are you still seeing this issue? I think the error is trying to tell you that `email` is either not passed, or it's `undefined`.

**Comment by jbaxleyiii** [comment]
Closing this as its over two weeks old without a response. Feel free to open if its still an issue

**Comment by piyushcoader** [comment]
I am getting similar error though have all variables correct

**Comment by THook** [comment]
i have the exact same issue. It's only happening when I pass a name to the config object. The error message is also pretty different from the one you get when some expected variable is not passed or undefined.

Any idea on that? React-apollo@1.0.0

**Comment by Vitiell0** [comment]
@THook I am also started getting this error when passing a name config. The mutation was working before it was assigned a name.

**Comment by savovs** [comment]
You need to pass an object with variables to the mutation because you've used the 'name' option.

`this.props.mutation({ variables: yourStuffHere })`

Personally, I think this is counter intuitive and inhibits the adoption of the library, can we do something to avoid having to do that?

Reference [here](https://stackoverflow.com/questions/40643719/apollo-data-mutation-prop-not-passed-to-component)

**Comment by mytee306** [comment]
> This issue needs to be resolved in react-apollo.
> You need to pass an object with variables to the mutation because you've used the 'name' option.
> 
> If you do this:
> 
> ```js
> graphql(login, { name: 'login' }
> ```
> 
> You need to pass variables like this:
> 
> ```js
> this.props.login({ variables: yourStuffHere })
> ```
> 
> I think this is counter intuitive and inhibits the adoption of the react-apollo. Might be easier to have a default behavior that doesn't expect you to wrap variables in an object.
> 
> Reference [here](https://stackoverflow.com/questions/40643719/apollo-data-mutation-prop-not-passed-to-component)
> 
> cc: @jbaxleyiii is there anything I can do to help with this?

I was thinking the same, but unfortunately even before the query / mutation is being used in the component itself the error is thrown, and even if the variable is passed the error is still thrown.

**Comment by migueljomartinezs** [comment]
> > This issue needs to be resolved in react-apollo.
> > You need to pass an object with variables to the mutation because you've used the 'name' option.
> > If you do this:
> > ```js
> > graphql(login, { name: 'login' }
> > ```
> > 
> > 
> > You need to pass variables like this:
> > ```js
> > this.props.login({ variables: yourStuffHere })
> > ```
> > 
> > 
> > I think this is counter intuitive and inhibits the adoption of the react-apollo. Might be easier to have a default behavior that doesn't expect you to wrap variables in an object.
> > Reference [here](https://stackoverflow.com/questions/40643719/apollo-data-mutation-prop-not-passed-to-component)
> > cc: @jbaxleyiii is there anything I can do to help with this?
> 
> I was thinking the same, but unfortunately even before the query / mutation is being used in the component itself the error is thrown, and even if the variable is passed when using the query / mutation inside the component the error is still thrown

I have the same issue, @mytee306 did you find a way around it?
