### ISSUE TITLE
Ability to add additional request body values

### ISSUE THREAD

**Issue by zackhall** [apollographql/react-apollo#579]
I'm using Apollo with the Scaphold.io service and for writing blobs to that service I need to be able to add additional options to the request body. 

The full Scaphold example can be found here: https://scaphold.io/docs/#uploading-files

But it does something like this:

```js
form.append("variables", JSON.stringify({
  "input": {
    "name": "Mark Zuck Profile Picture",
    "userId": "VXNlcjoxMA==",
    "blobFieldName": "myBlobField"
  }
}));
// The file's key matches the value of the field `blobFieldName` in the variables
form.append("myBlobField", fs.createReadStream('./mark-zuckerberg.jpg'));

fetch("https://us-west-2.api.scaphold.io/graphql/scaphold-graphql", {
  method: 'POST',
  body: form
}).then(function(res) {
  return res.text();
}).then(function(body) {
  console.log(body);
});
```

Where it adds a blobField to the request body.

Based on this, I need to pass into the variables a blobFieldName property, and then add to the request body the value passed to that property with the blob. However, using Apollo I can't add to the request body. I tried the following, but it's absent from the request body when I check in the network inspector: 

```js
export const withCreateCoverPhoto = graphql(CreateCoverPhoto, {
  props: ({mutate}) => ({
    createCoverPhoto: (name, file) => mutate({
      variables: {
        input: {
          blobFieldName: name,
        },
      },
      [name]: file
    }),
  }),
});
```

This feature would be greatly appreciated.

**Comment by helfer** [comment]
Hi @zackhall, you should be able to use middleware for that: http://dev.apollodata.com/core/network.html

**Comment by nathanqueija** [comment]
How do I add additional body params to the api call? I tried to use a middleware and pass body config to fetchOptions but it does not work.

**Comment by carolpettirossi** [comment]
> How do I add additional body params to the request body? I tried to use a middleware and pass body config to fetchOptions but it does not work. I'm using `HttpLink`.

I have the same question. How do I add params to body?
