### ISSUE TITLE
mutation: updateQueries causes component `data` to be removed.

### ISSUE THREAD

**Issue by cusxio** [apollographql/react-apollo#580]
## Possibly Related

https://github.com/apollographql/apollo-client/issues/1282

## Steps to Reproduce

Let's say I have a component (`TopicListComponent`) that displays a list of topics and subtopics.

- **QUERY.graphql** (to query the needed list)
```graphql
query TopicsPage($topicId: Int!) {
  currentUser {
    id
  }
  topic: topicById(id: $topicId) {
    id
    title
    followersCount
    description
    links: linksByTopicId {
      edges {
        node {
          id
          title
        }
      }
    }
    childrenTopics: topicsByParentTopicId {
      edges {
        node {
          id
          title
          description
          childrenTopicsTopics: topicsByParentTopicId {
            edges {
              node {
                id
                title
              }
            }
          }
          childrenTopicsLinks: linksByTopicId {
            edges {
              node {
                id
                title
              }
            }
          }
        }
      }
    }
  }
}
```

And I can create new topics via a GraphQL mutation.

- **MUTATION.graphql** (to create new topics)

```graphql

mutation CreateTopic(
  $currentUserId: Int!,
  $title: String!,
  $parentTopicId: Int!,
  $description: String,
) {
  createTopic(
    input: {
      topic: {
        userId: $currentUserId,
        title: $title,
        parentTopicId: $parentTopicId,
        description: $description
      }
    }
  ) {
    topic {
      id
      title
      description
      childrenTopicsTopics: topicsByParentTopicId {
        edges {
          node {
            id
            title
          }
        }
      }
      childrenTopicsLinks: linksByTopicId {
        edges {
          node {
            id
            title
          }
        }
      }
    }
  }
}
```

### Buggy Behavior

The following mutation, will "drop/delete", the existing `data` prop on `TopicListComponent`, i.e the `data` prop that initially contains `data.currentUser`, `data.topic` that resulted from the GraphQL query.

The `data` prop will then be _substituted_ by a _"fresh"_/new `data` prop that contains all the initial GraphQL methods.

Because the `data` prop was completely _"refreshed"_, React's PropTypes will result in the following error.

```
Warning: Failed prop type: The prop `topic` is marked as required in `Topics`, but its value is `undefined`.
Warning: Failed prop type: The prop `currentUser` is marked as required in `Topics`, but its value is `undefined`.
```

```js
  graphql(createTopicMutation, {
    props: ({ mutate }) => ({
      createSubtopicMutation: variables =>
        mutate({
          variables: { ...variables },
          updateQueries: {
            TopicsPage: (prevState, { mutationResult }) => {
              const updatedState = update(prevState, { // from immutability-helper
                topic: {
                  childrenTopics: {
                    edges: {
                      $push: [{ node: mutationResult.data.createTopic.topic }]
                    }
                  }
                }
              });
              return updatedState;
            }
          }
        }),
    })
  })
```

### Expected Behavior

- The `data` prop should not be _"refreshed"_ with a brand new `data` prop.

### Version
- apollo-client@1.0.0-rc.2
- react-apollo@1.0.0-rc.3

**Comment by helfer** [comment]
Thanks for filing the issue @cusxio! Can you check if this issue still occurs with the latest version of react-apollo and apollo-client? If so, it would help a lot if you could provide a reproduction here: https://github.com/apollographql/react-apollo-error-template

**Comment by cusxio** [comment]
@helfer I managed to find out the problem ! and it has nothing to do with apollo.

Basically in my query, I was requesting for a list of `Topics`, and the `__typename ` for each topic queried was `TopicEdge`.

However, when I've done some mutation, i.e. delete a topic, I return the deleted topic which has a different `__typename` of `Topic` rather than `TopicEdge`, causing apollo to completely remove the queried result on the `data` prop.

To be honest, I spent a lot of time on this, due to my lack of understanding of how everything works internally.

Is this an error that can be catch in apollo so that an appropriate error can be thrown?

**Comment by thomasMary** [comment]
@cusxio I'm glad you found a solution to your problem. Do you mind sharing the changes you've made to make it work?
Thanks

**Comment by cusxio** [comment]
@thomasMary basically all I did was change my mutation to return the right **__typename**, so that I can use the result directly in `updateQueries`. The problem that I was facing has nothing to do with the `updateQueries` function I [wrote](https://github.com/apollographql/react-apollo/issues/580#issue-217840864).

Here's the changes, not sure if it's helpful though...

```graphql
mutation CreateTopic(
  $currentUserId: Int!,
  $title: String!,
  $parentTopicId: Int!,
  $description: String,
) {
  createTopic(
    input: {
      topic: {
        userId: $currentUserId,
        title: $title,
        parentTopicId: $parentTopicId,
        description: $description
      }
    }
  ) {
    topicEdge { # <-------- Notice this
      node {
        id
        title
        description
        childrenTopicsTopics: topicsByParentTopicId {
          edges {
            node {
              id
              title
            }
          }
        }
        childrenTopicsLinks: linksByTopicId {
          edges {
            node {
              id
              title
            }
          }
        }
      }
    }
  }
}
```
The important thing to know is that `Topics` type in edges, has a different `__typename`, i.e. `TopicsEdge` type even though both of them return the same result.

Hope this helps !
