### ISSUE TITLE
Expand data loading/error to include operation type

### ISSUE THREAD

**Issue by msmfsd** [apollographql/react-apollo#584]
## Feature request
To avoid developers having to write custom HOCs or states to manage mutation/refetching loading/error states would it be possible to expand the data.loading and data.error props to be objects with the state of loading/error for all graphql request types. Eg:
```
data: {
  loading: {
    querying: boolean,
    mutating: boolean,
    refetching: boolean,
  },
  error: {
    queryError: null | ApolloError,
    mutateError: null | ApolloError,
    refetchError: null | ApolloError,
  },
  variables: { ... },
  refetch() { ... },
  fetchMore() { ... },
  startPolling() { ... },
  stopPolling() { ... },
  // ... more methods
}
```

### Related issues
https://github.com/apollographql/react-apollo/issues/421
https://github.com/apollographql/react-apollo/issues/430

### Expected Behavior
Components can connect props for mutation/refetch loading/error states from the graphql HOC.

### Version
For future versions

**Comment by helfer** [comment]
Hi @msmfsd! I think what you're looking for is `networkStatus`. If you pass `notifyOnNetworkStatusChange: true` to the query, then you can see what is currently happening by looking at `networkStatus`: http://dev.apollodata.com/react/api-queries.html#graphql-query-data-networkStatus

**Comment by msmfsd** [comment]
@helfer thanks, much appreciated!

**Comment by msmfsd** [comment]
@helfer NOTE that `networkStatus` does not reflect mutation loading state. Is there anyway to know if a mutation is currently happening?

**Comment by msmfsd** [comment]
@helfer mutation errors are not reflected in `networkStatus` either

**Comment by msmfsd** [comment]
@helfer also note that on refetch `loading` `error` & `networkStatus` do update but your component will not re-render unless you change your state/props on refetch. To me this makes `networkStatus` no help at all with mutate and refetch states. Am I missing something?
