### ISSUE TITLE
Multiple re-renders with queryDuplication (perf issue)

### ISSUE THREAD

**Issue by davidye** [apollographql/react-apollo#588]
I have a component that is wrapped by graphql().

When I mount N of these components at the same time, query deduplication makes it so that only one of these queries is run.

This is great - however, when the single query resolves, it triggers N render() calls, in parent components that also reference this data, because react-apollo thinks that the data has been updated N times.

### Version
- apollo-client@1.0-rc.7
- react-apollo@1.0-rc.3

**Comment by jbaxleyiii** [comment]
@davidye would you be able to put together a test case or a reproduction of this?
