### ISSUE TITLE
Query response is missing in the data object

### ISSUE THREAD

**Issue by gauravtiwari** [apollographql/react-apollo#598]
## Steps to Reproduce

1. Setup a new app with React router and apollo
2. Setup a basic component as described in readme 

### Buggy Behavior

![screen shot 2017-04-05 at 12 52 10](https://cloud.githubusercontent.com/assets/771039/24704353/2ff03d50-19ff-11e7-9f4b-eeb2bde94a6d.png)

### Expected Behavior

1. Server response 
![screen shot 2017-04-05 at 12 52 32](https://cloud.githubusercontent.com/assets/771039/24704359/35f73d16-19ff-11e7-9d71-bd05d415325f.png)

### Version
- apollo-client@1.0.2
- react-apollo@1.0.0
- react-router@4.0.0

**Comment by gauravtiwari** [comment]
So, removed react-router and it still doesn't return the query response within data object. Is I am missing something? 

![screen shot 2017-04-05 at 13 08 14](https://cloud.githubusercontent.com/assets/771039/24704803/08f94b40-1a01-11e7-8501-d7e9cd8765c6.png)

**Comment by gauravtiwari** [comment]
Although `apollo-dev-tools` returns correct response.

![screen shot 2017-04-05 at 13 10 40](https://cloud.githubusercontent.com/assets/771039/24704870/5b390d8c-1a01-11e7-818c-0b131858ccac.png)

**Comment by gauravtiwari** [comment]
Alright, it seems this option caused the problem `addTypename: false`

**Comment by helfer** [comment]
Hi @gauravtiwari! Thanks for filing the issue and figuring it out on your own. This reminds me that we should deprecate the `addTypename` option and always set it to true, because things might break in unexpected ways when typenames aren't present.

**Comment by gauravtiwari** [comment]
@helfer No problem. I am not sure, but is it important to set `typeName` in queries ? Consider a case where you are have persisted queries on server (which was the case with me) and using `operationName` to identify graphql documents. The `apollo-client` sents the queries with `typeName` and the offline queries didn't have typeName in it, which will cause query mismatch, and no data in store.

**Comment by gauravtiwari** [comment]
So, I guess we should leave it to the developer to specify `typeName` if needed? Or have better documentation for this.
