### ISSUE TITLE
unmounting ApolloProvider not clearing cache

### ISSUE THREAD

**Issue by stantoncbradley** [apollographql/react-apollo#600]
## Steps to Reproduce

1. Mount ApolloProvider and run gql queries.
2. Unmount Provider
3. When you remount provider (even with new client) original data still shows up

example app @ https://github.com/stantoncbradley/react-apollo-error-template
notes on example app:
1. `npm start` didn't work for me on react-apollo-error-template out of the box.  You may have to use `npm build` and work from the built version
2. the app demonstrates that timestamps resolved from GQL do not change between mounts/unmounts

### Buggy Behavior

Unmounting ApolloProvider doesn't clear Apollo cache.

### Expected Behavior

Unmount ApolloProvider should clear Apollo cache.

### Version
- apollo-client@1.0.0-rc.5
- react-apollo@1.0.0-rc.2

UPDATE 4/11/17:
issue still persists
### Version
- apollo-client@1.0.2
- react-apollo@1.0.1

**Comment by helfer** [comment]
Thanks for the repro @stantoncbradley. I took a quick look at the code in Apollo Client, and my current hypothesis is that `createStore` from Redux will return the same store that was previously created, so your best bet might be to dispatch a `clearStore` action that nukes the store after you've reinitialized Apollo Client.

That said, it might be that this PR will solve your `resetStore` issue without needing to dispatch any action of your own: https://github.com/apollographql/react-apollo/pull/531

**Comment by stantoncbradley** [comment]
thanks @helfer.  Upgrading the react-apollo-error-template included above to `"react-apollo": "^1.0.1",` does not resolve this issue.
current solution is to change the backend to respond to gql requests that don't have a session with valid gql response with all null values.  Is this how gql is supposed to work though?  seems strange there is not an apollo-client api for just clearing the data?
also dispatching `clearStore` after Apollo Client is reinitialized would be too late.  We have sensitive customer data in our store that needs to be cleared immediately when they sign out.  I can't find `clearStore` in react-apollo, apollo-client, or redux.  are you suggesting building a custom `clearStore` method?  `clearStore` really sounds like all I need.  Maybe you can help me understand how to implement that?  thanks so much!!!

**Comment by wmertens** [comment]
@stantoncbradley you should use `resetStore` as soon as the user signs out, and maybe something like https://twitter.com/erikras/status/851866533068513281

**Comment by stantoncbradley** [comment]
`resetStore` appears to work for me correctly now.  @helfer looks like #531 fixed my problem--unmounted queries were being refetched, which was throwing 404s.  @wmertens thanks for clarifying re the role of the Provider.  Like I said, my issue is resolved by #531.  Unmounting Apollo doesn't clear the cache, but also doesn't call `resetStore`.  So I don't need that behavior since `resetStore` works correctly now.  Closing this issue.  Thanks guys for all the help and the awesome library!  Keep up the great work!!!
