### ISSUE TITLE
Missing readQuery, writeQuery 

### ISSUE THREAD

**Issue by bwanlin** [apollographql/react-apollo#601]
Hi, i dont' have on my client readQuery and writeQuery :

![missing readquery](https://cloud.githubusercontent.com/assets/9287012/24755988/7553a336-1adc-11e7-9988-3d7ed7da8f87.png)

i read this article:
[https://dev-blog.apollodata.com/apollo-clients-new-imperative-store-api-6cb69318a1e3](url)

can someone tell me if its normal or if i do somehting wrong ?
### Version
- apollo-client@1.0.2
- react-apollo@1.0.0

**Comment by helfer** [comment]
Hi @bwanlin are you sure those are the versions that are bundled in your app? If so, please provide a reproduction using the [error template](https://github.com/apollographql/react-apollo-error-template) so we can investigate. Thanks!

**Comment by THook** [comment]
Hello @helfer! I have the same problem. I also tried to reproduce but react-apollo@1.0.0 defaults the Graphql package to 0.9.2! Rewriting the package.json and reinstalling with --force didn't do the trick for me

**Comment by bwanlin** [comment]
hello @helfer , i reproduce this on your error template [https://github.com/bwanlin/react-apollo-error-template](url)

**Comment by joshjg** [comment]
The `readQuery` and `writeQuery` methods should be under `__proto__`
