### ISSUE TITLE
How to use with Flow

### ISSUE THREAD

**Issue by blackxored** [apollographql/react-apollo#606]
I'm using Flow for prop validation, and I can't find a way to go deeper than `ApolloQueryResult<*>` for the `data` prop on my components, so I guess the question is, how do I use this with Flow?

**Comment by helfer** [comment]
Hi @blackxored. To get typings for results, we usually use something like apollo-codegen. @lewisf from Coursera is currently working on the library, and on making the workflow nicer. Let us know if you have time to help, we could definitely use it! 🙂

**Comment by blackxored** [comment]
I've tricked watchman to generate it via gql2flow but I think in general
having decent flow defs for react apollo and apollo would be great. I've
compiled some from TS manually, let me know if that's useful.

—
Best Regards,

Adrian Perez
https://adrianperez.codes
