### ISSUE TITLE
writeQuery doesn't affect data passed to components

### ISSUE THREAD

**Issue by joshjg** [apollographql/react-apollo#607]
## Steps to Reproduce

[writeQuery with additional data](https://gist.github.com/calebmer/4ffcb549a729ab4eb67ed641314ac4c0#file-example-js) - I basically followed this example from the [blog post](https://dev-blog.apollodata.com/apollo-clients-new-imperative-store-api-6cb69318a1e3).

EDIT: [Reproduction can be found here (branch write-query-bug).](https://github.com/joshjg/react-apollo-error-template/tree/write-query-bug) I have traced the cause to the use of inline fragments.

### Buggy Behavior

The data gets added to the underlying redux store, but it does not get sent to any of the components that rely on data from that query. 

### Expected Behavior

Calling `writeQuery` should update the `data` prop passed to a component wrapped with `graphql(...)`.

### Version
- apollo-client@1.0.2
- react-apollo@1.0.1

**Comment by helfer** [comment]
Hi @joshjg. Would you be able to provide a reproduction for this using the [error template](https://github.com/apollographql/react-apollo-error-template)? That would help us figure out what's wrong and fix it. Thanks!

**Comment by joshjg** [comment]
Will do, thanks.

**Comment by joshjg** [comment]
Hey @helfer, having trouble reproducing due to the complex nature of my app. Is it possible that, for example, too shallow of a comparison is done when deciding whether to update a wrapped component?

**Comment by joshjg** [comment]
Noticed something else: if I supply a `reducer` function to the `graphql(...)` wrapper options, it never gets called for this same component. If I supply it to other wrappers it works fine. Not sure what's different about this one, still investigating.

**Comment by joshjg** [comment]
I think I've traced the cause to the use of inline fragments. Will put the reproduction up soon.

**Comment by joshjg** [comment]
[Here's my reproduction.](https://github.com/joshjg/react-apollo-error-template/tree/write-query-bug) - on the write-query-bug branch

Note that the Add Person button does nothing to the list. Now, try removing `pets { ... }` from the query. Clicking Add Person works as expected.

**Comment by joshjg** [comment]
So this relates to [another issue](https://github.com/apollographql/apollo-client/issues/1363). I was able to solve my problem by implementing `IntrospectionFragmentMatcher` as described in one of the later comments on that issue.

**Comment by dcworldwide** [comment]
I have the same issue, writeQuery updates the store but doesn't trigger new props to be passed into my react components. 

React component query (with graphQL HOC)
------------

    query stats($sId: String!) {                
        stats(sId: $sId)
    }

This query returns a JSON data object that is defined using a Graphql custom JSON type (npm package 'graphql-type-json')

I'm modifying the JSON object in the apollo store cache using readQuery and then writeQuery.

WriteQuery logic
---------------------

    const statsQuery = gql`
        query stats($sId: String!) {                
            stats(sId: $sId)
        }
    `;

    let res = readQuery({
        query: statsQuery,
        variables: { sId }
    });

    res.stats.somefield = newValue 

    writeQuery({
        query: statsQuery,
        data: storeStatCache[sId],
        variables: {
            sId
        }
    })

**Comment by helfer** [comment]
@dcworldwide The most common reason for updates not happening is if the store write didn't contain all the necessary data that the component needs to update. I have an open PR on Apollo Client that should make it much easier to recognize this kind of issues: https://github.com/apollographql/apollo-client/pull/1638

**Comment by dcworldwide** [comment]
OK thanks looking forward to this fix.. good to know that my use of a scalar json return type isn't the issue
