### ISSUE TITLE
Switch from React.PropTypes to prop-types package

### ISSUE THREAD

**Issue by kachkaev** [apollographql/react-apollo#609]
After upgrading to react 15.5, I started seeing:

```
Warning: Accessing PropTypes via the main React package is deprecated.
Use the prop-types package from npm instead.
```

It'd be great if `react-apollo` was refactored a bit so that fewer developers saw this warning in their consoles.

See https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes on how to migrate.

**Comment by obartra** [comment]
Looks like this was fixed as of https://github.com/apollographql/react-apollo/pull/628
