### ISSUE TITLE
Using MockedProvider results in error "No more mocked responses for the query: ..."

### ISSUE THREAD

**Issue by tkiethanom** [apollographql/react-apollo#617]
I'm not sure why this happens, it seems I need to set up some MockedResponses but I don't know how to do that. When I console.log `_this.mockedResponsesByKey` and `key` in `MockNetworkInterface.prototype.query` it looks like the keys don't match because one is a string and the other is an object.  I could be reading this wrong though.

## Steps to Reproduce

Mount a MockedProvider using enzyme. 

```
const query = addTypenameToDocument(myQuery);

const mounted = mount(
	<MockedProvider mocks={[
		{
			request: { query, variables },
			result: { data: mockedData },
		}
	]}>
		<ConnectedComponent { ... routerParams } store={store} />
	</MockedProvider>
);
```

### Buggy Behavior

The component receives `No more mocked responses for the query: ...` in `this.props.data.error`

### Expected Behavior

Should not throw an error

### Version
- apollo-client@1.0.1
- react-apollo@0.9.0

**Comment by helfer** [comment]
@tkiethanom As you correctly noted this is likely not an issue with react-apollo but with your code. Make sure the query and variables exactly match. Also note that you need a mock request and response for every time your query is fired. If you refetch the query twice you will need three identical mock requests and responses.

If you can't figure it out after a while, I recommend asking for help on the apollo slack or stackoverflow. 🙂

**Comment by tkiethanom** [comment]
@helfer Thanks for the quick response. I found the issue to my problem. I noticed the ID of my variables are getting encoded in the query that's why they don't match. I know Apollo does some ID encoding for deduplication. I believe the `MockedProvider` makes some assumptions about the `dataIdFromObject` configuration. Is this correct?

**Comment by allexysleeps** [comment]
@grimunit should I add this prop to `MockProvider`?
I've tried add it but still got this error.
I've actually just copied real response from server, that works fine in app, but get error in testing.  
with typenames provided and without  😩

```
const query = CATEGORIES_QUERY
  const variables = { cache: false }
  const mockedData = mockedCategories
  const wrapper = (props) => mount(
    <MockedProvider
      removeTypename
      mocks={[{ request: { query, variables }, result: { data: mockedData } }]}>
      <CategoriesBody {...props} />
    </MockedProvider>,
  )
```

**Comment by stolinski** [comment]
@allexysleeps did you get yours working? I'm still getting the error myself after adding removeTypename.

**Comment by allexysleeps** [comment]
@stolinski No, we've skipped those tests for now 😞

**Comment by joepuzzo** [comment]
Hey guys i am also getting this :( any updates? I have triple checked my query definitions and it should match.

**Comment by joepuzzo** [comment]
Ok i figured it out.. internally there is a line that looks up your responce via the key where the key is the query and the variables.. if your variables are in a different order then the key is different and it all gets fubared.

**Comment by joepuzzo** [comment]
Also once you get that working you may need to call `update()` on your component wrapper if you use apollo.

**Comment by scottmcpherson** [comment]
This is still an issue that applies to MockProvider. I'm opening a new issue since this one has been closed. [Here](https://github.com/scottmcpherson/react-graphql-apollo-semanticui-starter/tree/56ded3ac973cb234ffaf3f551be5c3d3f502928c) is a commit that can be used to reproduce.

**Comment by stolinski** [comment]
@scottmcpherson I've found that you need your mocked response, variables and query to all be the exact same data 100%. Chances are if you are getting this you aren't passing the right variable or you aren't returning thee right data in your mocks. Where in your repo are you having this issue, it's a pretty big repo to paw through.

**Comment by scottmcpherson** [comment]
Yeah, I tripple checked the vars, query, and response, but maybe I'm missing something.
Here's the test file
https://github.com/scottmcpherson/react-graphql-apollo-semanticui-starter/blob/56ded3ac973cb234ffaf3f551be5c3d3f502928c/client/src/routes/Tasks/components/AddTask/AddTask.test.js

**Comment by stolinski** [comment]
I could be wrong since I just started looking at this, but it looks like you are setting your input value to 
'Test title' on line 32 of the test but setting the mock response to be 'Task One' here `  const createPublicTask = { id: 1, title: 'Task one' }`

**Comment by scottmcpherson** [comment]
That was it. Thanks @stolinski! I should have just referenced my `createPublicTask.title` to avoid that.

**Comment by stolinski** [comment]
Awesome! Every time I see this error it's because the response and the data aren't the same. It's so easy to do.

**Comment by FernandoBasso** [comment]
> If you refetch the query twice you will need three identical mock requests and responses.

This part of the answer was especially important for me. I don't think it is mentioned the docs.

**Comment by philberryman** [comment]
I struggled with this error for way too long. I double checked everything. I though ...

Turned out it was a variable that expected an Int but I was sending through as a String. A simple Number(myVariable) fixed it.

**Comment by steelx** [comment]
@philberryman it helped me too, variables type wasnt matching. I was sending it an int `123456`, instead of String `"123456"`

**Comment by mattfwood** [comment]
I feel like this is a common issue people run into when trying to create tests using `<MockedProvider />`, and I feel like there's some room to improve the dev experience.

I'd be glad to work on this pull request myself, but I was thinking this error could be more clear by showing a visual "diff" of the mocked responses and the queries that were run, similar to how Jest does it:

![image](https://user-images.githubusercontent.com/22530815/62812796-f0597500-bacc-11e9-8b81-201ac1e606f4.png)

I've definitely run into errors like @steelx is describing, and it can be hard to compare bigger queries and figure out which parts are different.

**Comment by CarlGranstrom** [comment]
> I'd be glad to work on this pull request myself, but I was thinking this error could be more clear by showing a visual "diff" of the mocked responses and the queries that were run, similar to how Jest does it:

That'd be amazing!

**Comment by SimenB** [comment]
There is #2883

**Comment by ARMATAV** [comment]
#2883 definitely needs a cleanup and a merge, without a diff it's incredibly hard to tell what the error is.

**Comment by NickolasBenakis** [comment]
> twice
@helfer 
@FernandoBasso 
Guys That's awesome.
I faced the same problem too. 

How you provide twice the requests, responses to the mock array?
By duplicated them?
This is an example of structuring my mock response

```
    mocks = [
      {
        request: {
          query: gql`
            ${comments.INSERT_COMMENT}
          `,
          variables: {
            commentObject: {
              body: "testing",
              drug_id: 1
            }
          }
        },
        result: {
          data: {
            insert_comment_one: {
              body: "testing",
              comment_id: 1,
              __typename: "comment"
            }
          }
        }
      }
    ];
```

**Comment by digitalhank** [comment]
@NickolasBenakis 

you can pass a function to the `result` property. it will receive the variables from your mutation request.

**Comment by luan-vieira** [comment]
I ran into this issue after adding a `refetch()` to my component. Duplicating the mocks provided to `MockedProvider` fixed it @NickolasBenakis 
```javascript
const listUploadsMock = {
  request: {
    query: ListUploads
  },
  result: {
    data: {
      numberManagementUploads: uploadsData.numberManagementUploads,
    }
  }
};

const mountAppWithRouter = (mountPath, mocks = [listUploadsMock]) => {
  const cache = new InMemoryCache();

  // seed some pre-existing data
  cache.writeQuery({
    query: gql`
      {
        numberManagementUploads {
          // fields
        }
      }
    `,
    data: {
      numberManagementUploads: uploadsData.numberManagementUploads,
    }
  });

  return (
    mount(
      <MockedProvider
        mocks={mocks}
        cache={cache}
        resolvers={{}}
      >
        <MemoryRouter initialEntries={[mountPath]}>
          <Route
            path="*"
            render={({ history }) => (
              <App config="/url/create?ajax=1" history={history} />;
            )}
          />
        </MemoryRouter>
      </MockedProvider>
    )
  );
};

// rendering my component with an array of 2 identical listUploadsMock fixed it
component = mountAppWithRouter("/new/create_numbers", [listUploadsMock, listUploadsMock]);
```

**Comment by michelalbers** [comment]
> not sure if possible but it would go a loooong way if the mocked response gave some sort of reason into what is not matching. This is a rather painful process and not very well documented

THIS would be awesome.
