### ISSUE TITLE
Unable to use React Native 0.43 

### ISSUE THREAD

**Issue by ligaz** [apollographql/react-apollo#619]
Hey guys,

React Native 0.43 has been recently released and uses `"react": "16.0.0-alpha.6"` as peer dependency. However React Apollo has a requirement of `"react": "0.14.x || 15.* || ^15.0.0"` which renders both modules incompatible.

Do you plan to address this issue?

**Comment by helfer** [comment]
Hi @ligaz! Please feel free to update the peer dependency to include the 16 alpha in the range! If possible, please run the tests with it to make sure it actually works.

**Comment by ligaz** [comment]
Done https://github.com/apollographql/react-apollo/pull/647.

**Comment by jbaxleyiii** [comment]
shipped!
