### ISSUE TITLE
Convert React.PropTypes to PropTypes provided by prop-types package 

### ISSUE THREAD

**Issue by dsifford** [apollographql/react-apollo#623]
Hi there, 

Just following your contributing guidelines. I'm able to submit a PR for this if you decide that's okay for me to do.

I'm sure you're all aware that React 15.5 deprecates `React.PropTypes` and moves it to its own module. Would this be something you are all okay with me doing in a PR?

Not a dire issue by any means, but it is somewhat annoying to see the console.error messages in my CI pipeline.

Thanks so much! Also, thanks for all your work on the Apollo project in general. 👍 👍

**Comment by alfonsoperez** [comment]
@dsifford if you end up doing, FYI there is a codemod for it in here: https://github.com/reactjs/react-codemod#react-proptypes-to-prop-types,

**Comment by dsifford** [comment]
@alfonsoperez Was not aware of that. Thanks, that'll definitely be helpful!

**Comment by helfer** [comment]
Hi @dsifford. That would definitely be a great PR that I would be extremely happy to merge 😃 

Also, hi @alfonsoperez, great to see you here! :wave:

**Comment by dsifford** [comment]
@helfer Great! Thanks for the hospitality 😄 

It's quittin' time here in my neck of the woods, but I should be able to knock this out tomorrow sometime.

(If anybody else happens to be reading this and feels like beating me to it, by all means, go right ahead!)
