### ISSUE TITLE
withApollo client.query & APOLLO_QUERY_STOP

### ISSUE THREAD

**Issue by jonmanzo** [apollographql/react-apollo#627]
Is it expected for queries run through client.query (withApollo) to always fire APOLLO_QUERY_STOP, hence always being removed from state.apollo.queries, making the query unavailable for update via UpdateQueries from mutations down the tree?  If so, is there a (good) way to force these to be observable and stick around?  Have it working with DataProxy, but more curious as to why it is no longer observable.

Our use case:

We're prefetching 3 queries with the only purpose being to instantiate their records in cache such that we can run UpdateQueries on them even if a user has yet to navigate to one of their specific components where they are implemented via react-apollo graphql.  If I watch redux, A_Q_S is fired for each thus they do not persist in state.apollo.queries. Upon continuing, when we fire a mutation and check ownProps.client.queryManager.queryIdsByName, these queries are not present, hence they will be omitted from the UpdateQueries execution.  Seems the only way they become persistent is by navigating to one of their dedicated components that implements the query via react-apollo graphql.

The prefetch looks like this:

`
async doQuery(employee_id) {
    const result = await this.props.client.query({
      query: EMPLOYEE_PROFILE_QUERY,
      variables: {
        employee_id,
      },
    });
    
    const baseVars = {
      cursor: 'initial',
      sortAttribute: 'last_updated',
      order: 'desc',
      ...coverImageVars,
      limit: 35,
      lucene: null,
    }
      
    await this.props.client.query({
      query: ALL_ITEMS_QUERY,
      variables: {
         ...baseVars
      },
    });
  
    await this.props.client.query({
      query: EMPLOYEE_ITEMS_QUERY,
      variables: {
         ...baseVars,
        employee_id,
      },
    });
  
    await this.props.client.query({
      query: QUEUE_ITEMS_QUERY,
      variables: {
        status: 'submitted',
         ...baseVars
      },
    });
    
    this.props.login('/app/dashboard', result);
  }
`

After pre-fetching, that component unmounts, though this should have no impact as the query ref is already gone from the store...

### Version
- apollo-client@1.0.2
- react-apollo@1.0.1

**Comment by helfer** [comment]
Hi @jonmanzo! Yes, if you simple use `client.query`, the query will be removed. However, it's still updatable through the new `update` API (which we now recommend over other ways of updating the store), or by specifying a query document (instead of query name) in `updateQueries`. I hope that helps!

PS: here's a post that explains the `update` API: https://medium.com/p/apollo-clients-new-imperative-store-api-6cb69318a1e3

**Comment by jonmanzo** [comment]
Assumed as much, so thanks for the confirmation.  BTW,  the Data Proxy update is working quite well.
