### ISSUE TITLE
Using getDataFromTree on the client for preloading?

### ISSUE THREAD

**Issue by miracle2k** [apollographql/react-apollo#631]
I was thinking that I could try to use `getDataFromTree` to prefetch data (http://dev.apollodata.com/react/prefetching.html). If I know the next route, I render the root for that route, pass it to  `getDataFromTree` and let it handle the rest.

It seems that  `getDataFromTree` is only available server side? Why? Is there a reason this is not suitable to use on the client?

**Comment by helfer** [comment]
Hi @miracle2k. The way we recommend people do preloading is by simply running the query before the view is loaded. That will put all the data in the cache, where it will be available once the component is mounted. If you want to pre-render the component, you can always do that and make it hidden, you don't need `getDataFromTree` for that. Here's a link to the docs for prefetching: http://dev.apollodata.com/react/prefetching.html

**Comment by miracle2k** [comment]
You mean I should do a `ReactDOM.render()` to a hidden DOM node? I didn't think about this, it should probably work. I do worry about performance though. Interacting with the DOM seems unnecessary here? 

Is there a better way to trigger a load of all the queries in a render tree, given that I have only the root react component for the target route? Besides ReactDOM.render()?

**Comment by helfer** [comment]
Oh, now I see what you mean. I think it would be interesting to try running `getDataFromTree` on the client. If it works I'd be happy to include it in the browser bundle as long as it doesn't increase the size by too much. Can you try it and report back?

**Comment by jbaxleyiii** [comment]
It seems more and more people want to use `getDataFromTree` on the client. I see no reason why we shouldn't export it there except client side weight. Instead, we are going to make it its own package which can be used!

**Comment by steida** [comment]
Please, allow getDataFromTree usage on the client. It's very clean approach to avoid the flash of loading content.

**Comment by jbaxleyiii** [comment]
This is fixed in the latest 2.0 rc!!
