### ISSUE TITLE
TS2304: Cannot find name 'DocumentNode'.

### ISSUE THREAD

**Issue by dcworldwide** [apollographql/react-apollo#632]
## Steps to Reproduce

Upgraded to version:

- "apollo-client": "^1.0.3",
- "react-apollo": "^1.0.1",

### Buggy Behavior

ERROR in /Users/Danijel/projects/am/am-web/node_modules/react-apollo/lib/graphql.d.ts
(51,43): error TS2304: Cannot find name 'DocumentNode'.

### Expected Behavior

No error

**Comment by helfer** [comment]
Hi @dcworldwide, I think this error is probably because you haven't installed `graphql` as a peer dependency, or some similar issue. I'm 99% sure this is something in your setup, and not an issue with react-apollo.

**Comment by dcworldwide** [comment]
Most probably ... will investigate. Thanks
