### ISSUE TITLE
refetch result can be ignored if variables change

### ISSUE THREAD

**Issue by NeoPhi** [apollographql/react-apollo#633]
If a refetch is issued with new variables and the incoming props on a wrapped component change (even if the changed props are not used in the query) the new variables from the refetch are ignored and the component reissues its initial query.

## Steps to Reproduce

A sample repository that demonstrates this issue is available at:
https://github.com/NeoPhi/refetch-bug

Once launched there are instructions to reproduce the issue.

### Expected Behavior

This is subtle behavior and I'm not sure what the correct behavior should be. I'm thinking that while the component is mounted if the original variables are unchanged the once issued by refetch should take precedence.

**Comment by helfer** [comment]
Thanks for the repro @NeoPhi. This is a tricky situation indeed, and it's one of the things that made me a bit wary about using refetch in the first place. When both refetch and props updates can change the variables, it's not always clear which one should take precedence. I'm not even sure how we would go about preserving the variables from the refetch if the component receives new props.

Could you sketch out what a PR would look like that would preserve the variables from `refetch` if the props change doesn't affect the variables?

**Comment by arvinsim** [comment]
I have a problem where `refetch` always calls the query with the default arguments I supplied in the `graphql` function instead of the argument I provided to `refetch`.

So far I haven't seen any other issues related to it but this.
