### ISSUE TITLE
ApolloProvider blocks react-router-dom's BrowserRouter

### ISSUE THREAD

**Issue by hendrikniemann** [apollographql/react-apollo#637]
I am using `react-apollo` together with `react-router-dom`. After upgrading to version 1.0 of `react-apollo` my router updates were not propagating through the `<ApolloProvider>` anymore. When I changed the order of `<BrowserRouter>` and `<ApolloProvider>` the code worked again. 

## Steps to Reproduce

Connecting your app like this does not work. ApolloProvider blocks my router after upgrading to v1.0.
```js
<BrowserRouter>
  <ApolloProvider client={client}>
    <App />
  </ApolloProvider>
</BrowserRouter>
```

This way around the router works again.
```js
<ApolloProvider client={client}>
  <BrowserRouter>
    <App />
  </BrowserRouter>
</ApolloProvider>
```

I also created a `create-react-app` repo for this: https://github.com/hendrikniemann/apollo-provider-context-blocking
```js
import React from 'react';
import ReactDOM from 'react-dom';
import { ApolloProvider, ApolloClient } from 'react-apollo';
import { BrowserRouter, Link, Route, Switch } from 'react-router-dom';

function App() {
  return (
    <div>
      <Link to="/first">first</Link> | <Link to="/second">second</Link>
      <Switch>
        <Route path="/first" render={() => <p>first</p>} />
        <Route path="/second" render={() => <p>second</p>} />
        <Route render={() => <p>other</p>} />
      </Switch>
    </div>
  );
}

const client = new ApolloClient({
  // This is just a fake network interface since we don't do any queries here
  networkInterface: {
    query: () => Promise.resolve({ data: null, errors: null }),
  },
})

ReactDOM.render(
  <div>
    <BrowserRouter>
      <ApolloProvider client={client}>
        <App />
      </ApolloProvider>
    </BrowserRouter>
    <ApolloProvider client={client}>
      <BrowserRouter>
        <App />
      </BrowserRouter>
    </ApolloProvider>
  </div>,
  document.getElementById('root')
);
```

### Version
- apollo-client@1.0.3
- react-apollo@1.0.1
- react-router-dom@4.1.1

**Comment by helfer** [comment]
Hi @hendrikniemann, I think this is the same issue as #557, so I'll close it in favor of that. If you have time, it would be great if you could fix or remove the `shouldComponentUpdate` function and see if any of the tests in react-apollo break after that.
