### ISSUE TITLE
Server side rendering and initial render

### ISSUE THREAD

**Issue by khankuan** [apollographql/react-apollo#639]
Hi, I'm following the server side rendering guide with next.js. It seems like for `network-only` policy, the client loads the data again upon initial render even when data is ready. Has anyone encountered the same issue before?

**Comment by helfer** [comment]
Hi @khankuan. That should not be the case if the client has a forceFetchDelay (which it does for this exact reason). If you find that you can reproduce the problem, please file an issue on apollo-client, or (even better) make a PR with a failing test case 🙂

**Comment by Fonger** [comment]
@helfer Sorry for bumping this question but I'm confused by `ssrMode` and `ssrForceFetchDelay`.

`ssrMode` should be false in browser and true in server to prevent forceFetch on the server.
Then what is `ssrForceFetchDelay` and what **delay** means here?
It seems I can set an arbitrary value > 0 to address the OP's issue for `network-only` and `cache-and-network` but I don't know the difference between 1ms and 1000ms delay.

This is how I configure my apollo client but I'm not sure why it works.

```js
  const client = new ApolloClient({
    connectToDevTools: isBrowser,
    ssrMode: !isBrowser,
    ssrForceFetchDelay: isBrowser ? 1 : 0
    ...
```
