### ISSUE TITLE
Inconsistent errors on server and client

### ISSUE THREAD

**Issue by choonkending** [apollographql/react-apollo#641]
## Steps to Reproduce

**1. Client-side rendering** Make a query on the client which fails. The ApolloError returned will be in `data.error` as specified [here](http://dev.apollodata.com/react/api-queries.html#graphql-query-data-error).

**2. Server-side rendering** Fetch data using `getDataFromTree` on server side:
```js
    getDataFromTree(app)
        .then(() => {
            // Success case
        })
        .catch(error => {
            const content = ReactDOMServer.renderToString(app);

           // When rendering app into string
           // !!! data.error is not populated with ApolloError similar to the client !!!!
           // Instead it gets thrown and caught in this clause 
            
            // send html back as response
        });

```

You get a rejected promise with an exception instead of `data` being populated with errors. 

### Why do we need this

This relates to https://github.com/apollographql/react-apollo/issues/615. 

We need to handle errors on the server in 2 ways:
- Render an error message to the screen
- Send the HTML back with the correct response code

We wish for a consistent way to handle errors both on the server and client. When an error gets thrown on the server, we cannot rely on the same error checking functions we used on the client. 

### Version
- apollo-client@1.0.0-rc2
- react-apollo@1.0.1

**Comment by helfer** [comment]
Hey @choonkending, thanks for filing the issue! I just wrote a longer reply in #615, so I will close this in favor of that. Let's continue the conversation there!
