### ISSUE TITLE
refetch issues on new rc versions

### ISSUE THREAD

**Issue by msmfsd** [apollographql/react-apollo#642]
_NOTE: this is an issue only with release candidate v1.0.0+ of `react-apollo` and `apollo-client`. If this has been fixed in newer versions this can be closed._

## Steps to Reproduce
1. Update `react-apollo` & `apollo-client` to `1.0.0-rc.3` & `1.0.0-rc.6`.
2. Replace forceFetch config option with new `fetchPolicy: 'network-only'` option on any queries.
3. Have a refetch button `onClick={() => refetch()}` that appears on any graphql error on your graphql component.
4. Load that component and simulate a network status error, eg stop your local server.
5. Click your refetch button, start server again, click refetch again etc.

### Buggy Behavior
On click of refetch no new request is made to the server, it appears, possibly, that `react-apollo` initiates an action but sees the error in the apollo store and doesnt make a new network request.

### Expected Behavior
Refetch should make a new network request to the server and change `loading` to `true`, `networkStatus` to `4` and then update `loading`, `networkStatus` & `error` depending on the network response.

### Version
- apollo-client@1.0.0-rc.6
- react-apollo@1.0.0-rc.3

### Related issue
https://github.com/apollographql/react-apollo/issues/636

**Comment by helfer** [comment]
Hi @msmfsd, could you try this with the most recent versions of react-apollo and apollo-client? The rc's are a few weeks old and we've fixed a couple of bugs since then.

**Comment by msmfsd** [comment]
Thanks @helfer I have updated and can confirm `fetchPolicy: 'network-status'` works as expected.

However after an error if you do a refetch the `networkStatus` remains at 8 (error) and thus loading remains false. Only once refetch is successfull does `networkStatus` change to 7.

So my question, is refetch meant to update the loading status to 4 and thus loading to true?

**Comment by helfer** [comment]
@msmfsd yes, I think the loading status should change to 4 if a refetch is happening, even if there was an error before. If that's not the case in the latest version, could you try making a PR to fix it? 🙏

**Comment by msmfsd** [comment]
Thanks, will look to do this on the weekend.

**Comment by msmfsd** [comment]
@helfer I cloned the `Apollo Client Error Template` and networkStatus and refetch all work perfectly and as expected. I think that means the issue is not with `react-apollo` at all and is with `apollo-client` or possibly our app. As such can you close this issue. I will look at our app and if it is an issue with `apollo-client` I will log an issue and link it to here.

Thanks for the help.

**Comment by helfer** [comment]
Thanks @msmfsd! I still think there could be an issue in Apollo Client, so don't exclude that as a possibility when investigating.  Maybe it's just not that easy to reproduce.

**Comment by msmfsd** [comment]
@helfer you may be right, on refetch after a network status error i continue to see networkStatus not updated as expected. Have raised an issue on `apollo-client`: https://github.com/apollographql/apollo-client/issues/1622

**Comment by msmfsd** [comment]
See this: https://github.com/apollographql/apollo-client/issues/1622#issuecomment-298073094
