### ISSUE TITLE
Subscription to CREATED event not rerendering

### ISSUE THREAD

**Issue by jonheslop** [apollographql/react-apollo#643]
Hello, I’ve been playing round with subscriptions. I hacked up Graph.cool's [World chat example](https://github.com/graphcool-examples/worldchat-subscriptions-example) and it works great for `[UPDATED]` but not for `[CREATED]`, I get the new array back fine but instead it doesn't render the change — this is my code https://github.com/jonheslop/pizza-tracker/blob/master/src/Tracker.js#L63 

[video of it working for `UPDATED`](http://cl.ly/k6P5)
[video of it *not* working for `CREATED`](http://cl.ly/k6Nr)

Both return the altered array but one causes a re-render the other doesn't?

I [asked on Graph.cool's Slack](https://graphcool.slack.com/archives/C0MQJ62NL/p1492700056193617) and they couldn't see an issue and sent me here.

Any help would be greatly appreciated, thanks

### Versions
    "apollo-client": "^1.0.4",
    "react-apollo": "^1.0.1",

**Comment by helfer** [comment]
I believe you have a typo on line 62, where it should say `allOrders` instead of `allOrder`. Let me know if that doesn't fix it.

**Comment by jonheslop** [comment]
Oh man, that totally worked, so dumb

Thanks so much
