### ISSUE TITLE
ApolloProvider ts errors

### ISSUE THREAD

**Issue by morriq** [apollographql/react-apollo#648]
ERROR in [at-loader] ./node_modules/react-apollo/src/ApolloProvider.tsx:13:28 
    TS7016: Could not find a declaration file for module 'invariant'. '/www/sites/xxx/wwwroot/node_modules/invariant/invariant.js' implicitly has an 'any' type.

ERROR in [at-loader] ./node_modules/react-apollo/src/ApolloProvider.tsx:42:15 
    TS7006: Parameter 'props' implicitly has an 'any' type.

ERROR in [at-loader] ./node_modules/react-apollo/src/ApolloProvider.tsx:42:22 
    TS7006: Parameter 'context' implicitly has an 'any' type.

ERROR in [at-loader] ./node_modules/react-apollo/src/ApolloProvider.tsx:56:25 
    TS7006: Parameter 'nextProps' implicitly has an 'any' type.

ERROR in [at-loader] ./node_modules/react-apollo/src/ApolloProvider.tsx:62:29 
    TS7006: Parameter 'nextProps' implicitly has an 'any' type.

**Comment by jakelacey2012** [comment]
@morriq Could you add the react-apollo & apollo-client versions please.

**Comment by jbaxleyiii** [comment]
This looks like a typescript loader issue. I'm going to close it since its not directly related to RA
