### ISSUE TITLE
How to pass from router param (react-router-dom)

### ISSUE THREAD

**Issue by lagmanzaza** [apollographql/react-apollo#668]
this my code 
![capture](https://cloud.githubusercontent.com/assets/5283709/25564916/bbadfbc4-2de7-11e7-991a-2948e4031187.PNG)

when getting param from router but variable not define
![4](https://cloud.githubusercontent.com/assets/5283709/25564917/bbaf4786-2de7-11e7-887f-dbadbc70632c.PNG)

**Comment by argallo** [comment]
I'm having the same issue
