### ISSUE TITLE
Co-location of data and props passed to components

### ISSUE THREAD

**Issue by leoasis** [apollographql/react-apollo#672]
React Apollo shows in the [docs](http://dev.apollodata.com/react/fragments.html#colocating-fragments) a convention for colocating fragments with the corresponding components, and suggest the usage of `graphql-anywhere` to [filter](http://dev.apollodata.com/react/fragments.html#filtering-with-fragments) the props that belong to the component's fragment. 

However that only works by filtering props from up in the tree, but does nothing to filter props that are specified by the component's children.

So what I think would be useful is this:

```js
// Here people should be an array of person objects only with an id property.
function People(people) {
  return (
    <ul>
      {people.map((person) => <Person key={person.id} person={person} />}
    </ul>
  );
}
People.fragments.people = gql`
  fragment People_people on Person {
    id
    ...Person_person
  }
  ${Person.fragments.person}
`;

// Here person should be an object with only firstName and lastName.
function Person(person) {
  return (
    <div>
      <h1>{person.firstName} {person.lastName}</h1>
      <PersonExtraDetails person={person} />
    </div>
  );
}
Person.fragments.person = gql`
  fragment Person_person on Person {
    firstName
    lastName
    ...PersonExtraDetails_person
  }
  {PersonExtraDetails.fragments.person}
`;

// Here person should be an object with only age and address.
function PersonExtraDetails(person) {
  return (
    <dl>
      <dt>Age</dt>
      <dd>{person.age}</dd>
      <dt>Address</dt>
      <dd>{person.address}</dd>
    </dl>
  );
}
Person.fragments.person = gql`
  fragment Person_person on Person {
    age
    address
  }
`;
```

I believe this is very useful for achieving true component modularity, as components this way won't mistakenly use props that are there just because a child component declared them in their fragments.

Relay (and Relay Modern) do this with the `createFragmentContainer`, where they provide the data as props but **only filled with the explicit fields that the component's fragment declares**. 

You can see how this works in Relay in this PR for the hello world example https://github.com/apollographql/relay-modern-hello-world/pull/5. Notice how the props fed to the component only contain the fields explicitly specified in the component's fragment, and if the component has children that also have fragments, some private fields are in there so that when passing those props to the children, the container is able to get the correct fields for that child component, and so on.

We briefly discussed this with @helfer in Slack, but posting it here so that we can start a discussion on wether this is a thing that would make sense to be part of the library, and if so, how should the API for these containers be, or if there's another way to achieve this.

**Comment by slightlytyler** [comment]
Would love to see more discussion on techniques for colocating fragments with components. Right now my process is very manual but it seems it could be more streamlined

**Comment by leoasis** [comment]
@jbaxleyiii has this been considered? Are there any similar efforts going on somewhere else?
