### ISSUE TITLE
How does cache trimming/invalidation work with apollo?

### ISSUE THREAD

**Issue by tnrich** [apollographql/react-apollo#675]
Hi there,

I couldn't find a description of how cache invalidation/trimming works with apollo-client anywhere in the documentation (sorry if it is there I must have missed it). 

In particular I am curious if the cache gets trimmed after a particular event or maybe after the total data store size grows above a certain limit (assuming the component(s) relying on the queries aren't still being rendered).

Thanks!

**Comment by cesarsolorzano** [comment]
I'm closing this. Please refer to apollographql/apollo-client#1640 for the same issue.
