### ISSUE TITLE
.refetch doesn't trigger componentWillReceiveProps

### ISSUE THREAD

**Issue by MichaelDeBoey** [apollographql/react-apollo#677]
## Steps to Reproduce

I tested it with the [example code](http://dev.apollodata.com/react/receiving-updates.html#refetch) from the docs

### Buggy Behavior

When I inspect the Apollo store (via the [DevTools](https://github.com/apollographql/apollo-client-devtools)), I see the store gets updated correctly, but my wrapped component doesn't re-render and it's `componentWillReceiveProps` function isn't triggered.

### Expected Behavior

Describe what you think should actually happen.

### Version
- apollo-client@1.1.1
- react-apollo@1.1.3

**Comment by thomasdelobel** [comment]
Almost same situation for me.

I have a query on an object, fetching well data and updating the wrapped component at first.

After a mutation on this object (made with success), the store is well updated with the new value, but the wrapped component is not notified (componentWillReceiveProps, shouldComponentUpdate, ...)

**Comment by MichaelDeBoey** [comment]
Also having that problem @thomasdelobel is having, but thought it had something to do with the one above, so didn't wanted to make a dupe issue

**Comment by jbaxleyiii** [comment]
@thomasdelobel or @MichaelDeBoey could you create a reproduction or a failing test using https://github.com/apollographql/react-apollo-error-template or the current test suite?

**Comment by MichaelDeBoey** [comment]
@jbaxleyiii Just saw apollographql/apollo-client#1555 and [@dfee's solution](https://github.com/apollographql/apollo-client/issues/1555#issuecomment-295834774) helped fixing my problem 🙂

CC: @thomasdelobel

**Comment by thomasdelobel** [comment]
Well spotted @MichaelDeBoey, thanks !

I was trying to reproduce it in a lighter app than the one I'm working on, and can't figured out what it was.

Actually I deal with a union and especially through fragments. Applying the @dfee's solution also solved my issue.
