### ISSUE TITLE
updateQueries for empty list

### ISSUE THREAD

**Issue by morriq** [apollographql/react-apollo#680]
Hello, I'm using postgraphql with react and I struggle with weird issue..
When array from query is empty `this.props.data.allUsers.edges.length === 0` and I'm trying to add new record via mutate method then I'll get `this.props.data.allUsers === undefined`. Is this issue or am I doing something wrong?

## Steps to Reproduce

1. Truncate your table
2. push new record in updateQueries prop

It's my query:

`query allUsers($after: Cursor) {
    allUsers(after: $after, first: 5, orderBy: ID_DESC) {
        totalCount
        edges {
            cursor
            node {
                id
                login
                password
            }
        }
        pageInfo {
            startCursor
            endCursor
            hasPreviousPage
            hasNextPage
        }
    }
}`

It's my mutate method:

`   
 this.props.mutate({
      variables: {
        input: {
          user
        }
      },
      optimisticResponse: {
        __typename: 'Mutation',
        createUser: {
          __typename: 'UsersConnection',
          userEdge: {
            __typename: 'UsersEdge',
            node: {
              __typename: 'User',
              id: +new Date(),
              ...user
            }
          }
        }
      },
      updateQueries: {
        allUsers: (previousQueryResult: any, {mutationResult}: any) => {
          return update(previousQueryResult, {
            allUsers: {
              edges: {
                $unshift: [mutationResult.data.createUser.userEdge]
              }
            }
          });
        }
      }
    });
`

### Version
- apollo-client@1.1.2
- react-apollo@1.1.3

**Comment by jurajkrivda** [comment]
Did you try $push?

**Comment by morriq** [comment]
Yes. It's the same, even if i do it in vanila js.

**Comment by helfer** [comment]
@morriq what are the contents of the store after the query? You can see it with the apollo devtools or redux devtools.

**Comment by morriq** [comment]
It looks like store did react on query well:
before:
<img width="580" alt="screen shot 2017-05-06 at 18 17 25" src="https://cloud.githubusercontent.com/assets/2962338/25774028/722abd02-3288-11e7-944e-e44ae659af1d.png">
after:
<img width="604" alt="screen shot 2017-05-06 at 18 17 38" src="https://cloud.githubusercontent.com/assets/2962338/25774031/77cf0d6c-3288-11e7-8e0e-38b77de5ff2e.png">

before:
this.props.data.allTests = Object {totalCount: 0, edges: Array(0), pageInfo: Object, __typename: "TestsConnection", Symbol(id): "$ROOT_QUERY.allTests({"after":null,"first":5,"orderBy":"ID_DESC"})"}

after:
this.props.data.allTests = undefiend

Thank you for your interest.

**Comment by helfer** [comment]
Looks like your userEdge is missing a cursor. If you update to the latest version of Apollo Client you should get an error saying that the shape of your result doesn't match the query and that the cursor field is missing.

**Comment by morriq** [comment]
Thank you, I've added cursor to userEdge and it's fine now.
