### ISSUE TITLE
warning in console [PropTypes validators]

### ISSUE THREAD

**Issue by sarkistlt** [apollographql/react-apollo#683]
In dev mode I have this annoying warning it comes from ApolloProvider, any way to solve this problem besides using production env. for development?

<img width="671" alt="screen shot 2017-05-03 at 8 13 04 pm" src="https://cloud.githubusercontent.com/assets/5773343/25689479/346fe3cc-303d-11e7-9772-7b88c3b85a2b.png">
<img width="1680" alt="screen shot 2017-05-03 at 8 12 51 pm" src="https://cloud.githubusercontent.com/assets/5773343/25689478/346eb484-303d-11e7-9931-80ad7774e010.png">

**Comment by jbaxleyiii** [comment]
@sarkistlt that's odd! I'm not seeing it n any of my projects, what version of the client and of react are you using?

**Comment by sarkistlt** [comment]
Hi, thanks for quick response!
Here:
```json
"apollo-server": "^0.3.3",
"react-apollo": "^1.2.0",
"react": "15.1.0",
"react-dom": "15.1.0",
"react-router": "2.5.2",
"graphql": "^0.9.3",
```

**Comment by jbaxleyiii** [comment]
I'm wondering if it has to do with the react 15.5 (or was it 4) update that made prop types it's own package. Could you try updating react and react dom?

**Comment by sarkistlt** [comment]
I've got bunch of other warnings but it fixed issue with apollo, thanks!
