### ISSUE TITLE
Support Tree Shaking though module field

### ISSUE THREAD

**Issue by jwickens** [apollographql/react-apollo#686]
Apollo Client supports tree shaking through the module field in package.json. React-apollo however serves a transpiled and minified file only. The combination of react-apollo, apollo-client and graphql add 300kb to my build.

**Comment by jwickens** [comment]
https://github.com/graphql/graphql-js/issues/843

**Comment by jbaxleyiii** [comment]
@jwickens I would love to support this! Do you have any experience setting it up?

@helfer who did this work for AC?

**Comment by helfer** [comment]
@jbaxleyiii I believe it was @kamilkisiela who did this for Apollo Client.

**Comment by jbaxleyiii** [comment]
awesome!

Looks like https://github.com/apollographql/apollo-client/pull/1069, https://github.com/apollographql/apollo-client/pull/1130, and https://github.com/apollographql/apollo-client/pull/1177 will be a good place to start!

@jwickens I'll work on this as soon as I can!

**Comment by jbaxleyiii** [comment]
@jwickens I've deployed a version as `react-apollo@next` would you be open to giving it a shot?

**Comment by jbaxleyiii** [comment]
If anyone is able / willing, I'm working to support tree shaking for react-apollo. If you have an app (one that would use tree shaking OR one that that doesnt), I'd love for some volunteers to try it out! `npm i --save react-apollo@next`. If / when you run into issues with the build, can you report them here!

**Comment by vlasenko** [comment]
@jbaxleyiii I've checked `react-apollo@next` and it works without issues with our Apollo isomorphic starter kit:
https://github.com/sysgears/apollo-fullstack-starter-kit

However because we are using Webpack 2 and ES6 Tree Shaking is known to not work with Webpack 2:
https://github.com/webpack/webpack/issues/2867
 the effect is neglible, the bundle size is only 600 bytes less with `react-apollo@next` compared to `react-apollo@1.2.0`

**Comment by jbaxleyiii** [comment]
@vlasenko thats great news! I'll take any savings I can get! Along with the linked PR, I'm going to move `withApollo` into its own file (still exported at the root). Then I'll release this as a minor version bump and see how it goes in the wild!

Thanks for testing it!

**Comment by jwickens** [comment]
@jbaxleyiii I can confirm that I'm saving 3.4 KB after gzip between react-apollo@1.2 and react-apollo@next. Thanks

However one issue i'm seeing is with source map support I'm getting the following error:
```
/~/apollo-client/transport/Deduplicator.js
Cannot find source file '../../../src/transport/Deduplicator.ts': Error: Can't resolve '../../../src/transport/Deduplicator.ts' in '/Users/jonathanwickens/dev/h-agent-app/node_modules/apollo-client/transport'
```

This is because the source map in lib refers to the src dir which is not published to npm. 

For those using webpack you should be in theory able to use source maps of imported modules with
```    
 {
        test: /\.js$/,
        use: ['source-map-loader'],
        enforce: 'pre'
  },
```

@jdwuarin this should eventually help you with your debugging issues
