### ISSUE TITLE
Need Help, fetchMore is failing when using with withApollo

### ISSUE THREAD

**Issue by kishorevarma** [apollographql/react-apollo#687]
Hi,

I am using withApollo HOC.  My component does pagination. I am facing following issue 
```
QueryManager.js:561 Uncaught (in promise) Error: ObservableQuery with this id doesn't exist: 62
    at QueryManager.webpackJsonp../node_modules/apollo-client/core/QueryManager.js.QueryManager.getQueryWithPreviousResult (QueryManager.js:561)
    at ObservableQuery.webpackJsonp../node_modules/apollo-client/core/ObservableQuery.js.ObservableQuery.updateQuery (ObservableQuery.js:210)
```
My code is as follow
```
onSearch = () => {
    const query = this.props.client.watchQuery({
      query: spaceQuery,
      fetchPolicy: 'network-only'
    });
    // I have tried currentResult also faced the same issue
   query.result().then(this.onQueryResult).catch(this.onQueryError);
    this.setState({ query });
}

loadMore = () => {
    this.state.query.fetchMore({
      updateQuery: (previousResult, { fetchMoreResult }) => {
        if (!fetchMoreResult) {
          return previousResult;
        }
       // ignore the below logic , I have to combine rev and current logic
        return previousResult;
      }
    });
  };
```

### Version
- apollo-client@1.0.2
- react-apollo@1.0.0

**Comment by helfer** [comment]
@kishorevarma you need to subscribe to the observableQuery you get back from watchQuery in order for the query to be started. BTW, I would recommend using the `graphql` HOC from react-apollo, it handles a lot of things for you.

**Comment by kishorevarma** [comment]
@helfer I am using graphql HOC in all other places in my project. but in specific use case I have two queries one is executed while page load (I am using graphql HOC) and another query should be  executed when user click on button, as per my knowledge I can't use grahql HOC because I can't control execution of query(execute only with user interaction example search button)

**Comment by kishorevarma** [comment]
@helfer I just checked source code. I will use subscribe Thanks

**Comment by kishorevarma** [comment]
sorry ignore my previous comments I see that I can use graphql HOC with skip option. I will try that
