### ISSUE TITLE
BatchingNetworkInterface does not batch on SSR

### ISSUE THREAD

**Issue by Zn4rK** [apollographql/react-apollo#698]
I initially encountered this bug while I was developing a Next.js application. I posted an issue with them [over here](https://github.com/zeit/next.js/issues/1900). There is a Next.js specific reproduction in that issue.

But I've set up a reproduction based on the template you guys have provided. It's also a bit crude, but it illustrates the point. 

https://github.com/Zn4rK/react-apollo-batching-reproduction

## Steps to Reproduce

The batching works in the client `npm start`.

Run `npm run withFetchPolicy` and see how Apollo finds the queries it's going to fetch, but the promise seems to resolve before the fetching is done.

Run `npm run withoutFetchPolicy` and see how Apollo fails to batch the queries, and they run in a sequential order. 

### Buggy Behavior

When Apollo actually fetches the data, it seems to do it in an sequential order, instead of actually batching the queries it can batch...

### Expected Behavior

I was under the impression that the batching would work serverside as well:
```
The getDataFromTree function takes your React tree, determines which queries are needed to render them, and then fetches them all. It does this recursively down the whole tree if you have nested queries. It returns a promise which resolves when the data is ready in your Apollo Client store.
```
(from the [documentation](http://dev.apollodata.com/react/server-side-rendering.html#getDataFromTree))

### Version
- react-apollo@1.2.0

I also tried react-apollo@1.3.0-alpha.1, but that only makes it behave like the `npm run withoutFetchPolicy` example.

**Comment by helfer** [comment]
@Zn4rK I'm not 100% sure, but I think this could be because the parent component needs to have its query resolved before it even knows which child components to render. @jbaxleyiii might know more.

**Comment by thebigredgeek** [comment]
@helfer yeah that sounds right.

**Comment by Zn4rK** [comment]
@helfer I do agree that it makes sense if it works like that. If that's the intended behaviour - I really think that it should be documented though.

If the queries live together it does batch them, but if it has any kind of hierarchy (an HOC) we have to wait for the network.

If I look at the client side behaviour it batches correctly and expected. It runs the queries it can access before loading any more data.

Client side:
```js
["PeopleLastName", "PeopleFirstName"]
["PeopleAge"]
```

And on the server side:
```js
[ 'PeopleFirstName' ]
[ 'PeopleLastName', 'PeopleAge' ]
```

With the code
```js 
class PeopleFirstName extends Component {
    render() {
        const { data, data: { people } } = this.props;

        return (
            <div>
                <PeopleLastName />
                <div id="firstName">{people ? people.length : 0}</div>
                {!data.loading && <PeopleAge />}
            </div>
        );
    }
}
```

I get that the client side has a different lifecycle than what server side could ever have, but afaik the queries are static, and it should theoretically be possible to see which queries are needed to run before we can continue with the render?

Either way, I have a feeling that the Promise from `getDataFromTree` shouldn't resolve without data. That might have been addressed in v1.3.0.

**Comment by thebigredgeek** [comment]
@Zn4rK The trick here is that queries only run when their attached components are being mounted.  If you have two queries, A and B, where A lives on the parent and B lives on the child, Apollo can't very well tell whether or not the child is going to render or mount if it's rendering is conditional upon data returned from query A on the parent.

**Comment by huangbong** [comment]
@Zn4rK did you end up finding a solution to this problem? Same thing happening with me. Client side requests are batched fine, but SSR is still resulting in multiple queries to GraphQL.
