### ISSUE TITLE
v1.3.0 not yet released on npm?

### ISSUE THREAD

**Issue by MichaelDeBoey** [apollographql/react-apollo#702]
The release is present in the repo, but not yet on npm? 😕 

CC: @helfer

**Comment by stubailo** [comment]
(By the way, no need to mention Jonas here, he gets these notifications anyway)

**Comment by jbaxleyiii** [comment]
Also, you should ping me 😎 

1.3 will be released soon! I want to ship better types with it and that PR is almost done

**Comment by MichaelDeBoey** [comment]
C'mon @jbaxleyiii you can do it! 😉

**Comment by jbaxleyiii** [comment]
@MichaelDeBoey sorry for the delay! I wasn't able to devote enough time to RA / AC following the enhanced types release until now. After AC releases the flow PR, I'll release 1.4 (which is 1.3 + better type support)

Btw, 1.3 is released on npm as an alpha!
