### ISSUE TITLE
unexpected behaviour when not querying for `id`

### ISSUE THREAD

**Issue by ksmth** [apollographql/react-apollo#703]
## Steps to Reproduce

Query for `<First />`:
```
people {
  id
  firstName
}
```

Query for `<Second />`:
```
people {
  lastName
}
```

- mount `<First />`
- `<First />` will receive props in the shape of `{ data: { people: [ ... ], /* other Apollo props */ } }`
- some time later mount `<Second />`

### Buggy Behavior

- `<First />` receives props in the shape of `{ data: { /* other Apollo props */ } }`, where `people` is missing

### Expected Behavior

- `<First />` should receive `data.people`
- Apollo should query for the missing data automatically maybe?

### Version
- apollo-client@1.0.0-rc.9
- react-apollo@1.0.0

https://github.com/ksmth/react-apollo-error-template/tree/error-when-not-fetching-id

**Comment by stubailo** [comment]
> <First /> doesn't receive any data

What do you mean by "doesn't receive any data"? Like, it doesn't get any props in the component?

**Comment by helfer** [comment]
I'm pretty sure this is another example of what I ran into with @daniman today: https://github.com/apollographql/apollo-client/issues/1693

**Comment by ksmth** [comment]
@stubailo I've updated the comment to be more explicit on what is missing and what is passed to the component

If there's anything else I can do to help debug this issue, let me know. I'll take a look at https://github.com/apollographql/apollo-client/issues/1693 to see if I can make sense of it all or produce a failing test case, but I wouldn't hold my breath. ;)
