### ISSUE TITLE
Subscriptions and mapping to props

### ISSUE THREAD

**Issue by ChrisGitter** [apollographql/react-apollo#705]
I'm not sure if I understand the whole thing correctly, but when I use the example in the Apollo guide for subscriptions it just doesn't work.

http://dev.apollodata.com/react/subscriptions.html

I'm confused about the section where the `graphql(...)` container is created and the `props` property. When I return only an object with the `subscribeToNewData` property on it, doesn't that remove all the other props on my component? The `data.loading` property, that determines if the component is visible doesn't exist anymore.

**Comment by helfer** [comment]
@Urigo I think you're best equipped to answer this question
