### ISSUE TITLE
Infinite scroll and fetchMore don't work right when going offline and then online again

### ISSUE THREAD

**Issue by ablbol** [apollographql/react-apollo#710]
am using "react-apollo": "^1.0.0". I am experimenting with infinite scrolling. So I have a query that is supposed to load the first 20 users and when I scroll down to the bottom of the page, I get the next 20 users. Every thing works great. But then I turn the network off and log the error and networkStatus from within the component. I get:
```
Network error: Failed to fetch
networkStatus 8
```
Seem fine so far but when I turn the network on again, the following is logged:
```
Network error: Failed to fetch
networkStatus 7
```
That does not look right. Also, after turning the network on, I run into an infinite loop where the net is hit and the component never gets updated.
Any idea why I am getting this behavior?
Thanks

**Comment by sreucherand** [comment]
I am also experiencing an unexpected behaviour when using fetchMore after going offline.

### Reproduction test instructions

https://github.com/sreucherand/react-apollo-error-template#demo-instructions

### Version

apollo-client@1.2.2
react-apollo@1.2.0

**Comment by jbaxleyiii** [comment]
@helfer I imagine this is an AC issue under the hood yes? With the reproduction I'm game to take a look but I don't know if we will have a good solution until the new network transport design? Is this the expected behavior for network errors?
