### ISSUE TITLE
React Router 4 not playing well with React Apollo

### ISSUE THREAD

**Issue by benwiley4000** [apollographql/react-apollo#712]
I'm honestly unsure whether the "cause" of this problem is Apollo, or React Router, or me - but it appears that when using React Router 4 and react-router-redux 5 middleware, a call to `history.push(...)` either before **or** after a call to a refetching function passed down from the `graphql` component ends up canceling the apollo request.

Keep in mind the react-router-redux middleware sends a `LOCATION_CHANGE` action in response to any changes to the history object it uses.

**Intended outcome:**
~The react-router-redux `LOCATION_CHANGE` action~ *The change to the history* should have no effect on the apollo fetch.

**Actual outcome:**
~`LOCATION_CHANGE`~ *Changing the history* seems to preempt the fetch completing successfully, somehow.

When I run this code:
```javascript
history.push('/new/url');
functionFromGraphqlHOCWhichRefetchesAnApolloQueryWithSomeNewFilters();
```
These changes occur in the state:

![bad_state_1](http://i.imgur.com/GmCfyij.png)

![bad_state_2](http://i.imgur.com/OHqrkfy.png)

![bad_state_3](http://i.imgur.com/tbiN4lu.png)

![bad_state_4](http://i.imgur.com/1c7nHzT.png)

![bad_state_5](http://i.imgur.com/gfn1h5y.png)

However if I comment out the history push, stuff tends to work, besides the fact our url didn't update.
```javascript
//history.push('/new/url');
functionFromGraphqlHOCWhichRefetchesAnApolloQueryWithSomeNewFilters();
```
Query init...

![ok_state_1](http://i.imgur.com/Xqb4uu4.png)

Several unrelated actions later, we have our new data...

![ok_state_2](http://i.imgur.com/IZj9YiH.png)

**How to reproduce the issue:**
That's gonna be hard - I'm hoping someone can just eyeball this one, but I'll put together an example repo if needed.

For what it's worth, I don't seem to have this same problem when I use the React Router `Link` component to push history changes.

**Comment by benwiley4000** [comment]
P.S. I just did some more testing... and determined that this problem occurs regardless of whether the `LOCATION_CHANGE` action actually gets dispatched in response to the history change. If I cancel that action, but still change the location, my data will not load correctly, and we'll see the odd sequence of Apollo actions shown above.

**Comment by benwiley4000** [comment]
Some of my statements above may have been erroneous. Long story short, I found the problem: Previously, the only prop received by my topmost `graphql` component was an initial filter state variable that never changed. But that data wasn't being refetched with the original `mapPropsToQueries` again - it was being refetched via a `refetch` function receiving modified variables.

When I added React Router to my app, my component also started receiving route-related props. When the route changed, and the props changed, the query got refetched, but since my initial filter state variable HADN'T changed, it overwrote the `refetch`ed query using the new filter, with another one using the old filter.

My new solution is to actually take advantage of `graphql`'s `mapPropsToQueries` by sending in the variable filter state as props, setting the `cache-and-network` `fetchStrategy`, and no longer using `refetch`.

**Comment by sakhmedbayev** [comment]
@benwiley4000 can you please show me how you actually done this part:

> My new solution is to actually take advantage of graphql's mapPropsToQueries by sending in the variable filter state as props, setting the cache-and-network fetchStrategy, and no longer using refetch

I am having hard time to find documentation for how to use `mapPropsToQueries`

Thanks in advance!

**Comment by benwiley4000** [comment]
I definitely had to do some searching to figure out exactly what I meant...

Anyway, this is how you can use map props to queries in conjunction with something like react-redux connect:

```javascript
import { connect } from 'react-redux';
import { graphql, compose } from 'react-apollo';

import query from './query';
import MyComponent from './MyComponent';
import myFilterStringSelector from './myFilterStringSelector';

export default compose(
    connect(state => ({
        myFilterString: myFilterStringSelector(state)
    })),
    graphql(query, {
        options: ({ myFilterString }) => ({
            variables: { filter: myFilterString },
            fetchPolicy: 'cache-and-network'
        })
    })
)(MyComponent);
```

This will refetch your query whenever `myFilterString` changes.

@sakhmedbayev

**Comment by sakhmedbayev** [comment]
Thanks @benwilley4000.  Is 'myFilterStringSelector' react component? Can you show how it look like?

**Comment by benwiley4000** [comment]
@sakhmedbayev it's just a shortcut to get your redux state that abstracts away the structure of the state. Not really important to have this, but it could look like:
```js
function myFilterStringSelector (state) {
    return state.app.filters.myFilterString;
}
```
If that's what your reducer looks like.

If you're not using redux at all then this is irrelevant.
