### ISSUE TITLE
component won't rerender after the graphql query gives different data 

### ISSUE THREAD

**Issue by devarashetty** [apollographql/react-apollo#713]
I tried a component with graphql query in the following way 

```
const query = gql`
  query {
       currentUser {
       
      }
    }
  }`;

@graphql(query)
 class extends Testing React.Component {
}

const mapStateToProps = (state, ownProps) => {
  return {
    storedState:Object.assign({},state.apollo)
  }
}

const LayoutWithData = connect(
  mapStateToProps
)(Layout)
```

MyUnderstanding: From `Apollo-client` has default `store` and `reducers which will update the state whenever the data observed from graphql query changes` .If this is true regarding my issue above , the `currentUser` data changes after login but the component is not rerendered .

**Comment by jbaxleyiii** [comment]
@devarashetty how are you updating currentUser? If the same query isn't used between the update and this component, it won't re-render. ApolloClient does not diff queries anymore so either you have to use the `update` function or use the same query
