### ISSUE TITLE
Setting skip: true will remove any previously loaded data

### ISSUE THREAD

**Issue by kadikraman** [apollographql/react-apollo#714]
I am using a decorator on a modal component that has an `isOpen` prop being passed in. If `isOpen=true`, do the fetch, else skip. This ensures that the content is only loaded when the modal is open.

My problem is that when I close the modal, there's an extra 500ms where the modal fades out, however, because `isOpen=true`, the decorated function removes all previously fetched data so while my modal is animating out, I get 500ms or all the data flickering to undefined.

Is there a way to retain previously fetched data?

## Steps to Reproduce
Toggle skipping a query based on a passed in prop

### Buggy Behavior
When skipping a query, all previously fetched data is removed

### Expected Behavior
The previously fetched data is retained in the component

### Version
- apollo-client@0.8.4
- react-apollo@0.9.0

**Comment by ksmth** [comment]
This is the intended behaviour of the `skip` option. [From the docs](http://dev.apollodata.com/react/queries.html#graphql-skip):
```
Passing the skip config completely bypasses the higher-order component, as if it weren’t there at all. This means your child component doesn’t get a data prop at all, and the options or props methods are not called.
```

**Comment by jbaxleyiii** [comment]
This is currently the intended behavior!

**Comment by serranoarevalo** [comment]
@jbaxleyiii In my case when using ```compose``` it will also remove other queries' data:

````js
export default compose(
  graphql(GET_DRIVERS, {
    options: {
      pollInterval: 1000
    },
    skip: props => {
      if (props.data.me.user.isDriving) {
        return true;
      } else {
        return false;
      }
    }
  }),
  graphql(ME)
)(HomeContainer);
`````

The props from the ME query are passed down to the GET_DRIVERS' skip function which is great but if I return true from the skip function then my component is not getting the props from the ME query.
Shouldn't the `skip` only skip the query where it was called for and not the whole compose() queries?
