### ISSUE TITLE
mutate() should return optimistic response if defined

### ISSUE THREAD

**Issue by serle** [apollographql/react-apollo#716]
This may be debatable, but when an optimistic response is defined does it not make more sense to return the optimistic response from a mutate() for immediate use, as opposed to a promise to the real result which will be received later in update props.

**Comment by jbaxleyiii** [comment]
@serle why would this be the correct behavior? I would expect `mutate` to return the server result

**Comment by stubailo** [comment]
This is kind of the main problem with a promise - that it can only return one result. Give that, I think returning the final server result is best.

**Comment by serle** [comment]
The mutate method in my case is invoked via a button-click handler. At that point I would like to update the state of my component with the optimistic result. When the real result comes back the whole component gets re-rendered as a result of the property change, so my component gets the real response at a later data, but through the react re-render cycle as opposed to the promise.

**Comment by stubailo** [comment]
Why not use the optimistic result to update the store just the same way?
