### ISSUE TITLE
Cannot use addTypenameToDocument from queryTransform in create-react-app test

### ISSUE THREAD

**Issue by mvanlonden** [apollographql/react-apollo#721]
## Steps to Reproduce
1. Upgrade to latest version of `react-scripts`, `yarn upgrade react-scripts`
2. Create test that includes `import { addTypenameToDocument } from 'apollo-client/queries/queryTransform'`
3. `yarn test`

### Buggy Behavior

```
/node_modules/apollo-client/queries/queryTransform.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { checkDocument, } from './getFromAST';
                                                                                             ^^^^^^
    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at Object.<anonymous> (src/Model.test.js:4:23)
```

### Expected Behavior
Should have umd version of file to import into jest test.

### Version
- apollo-client@1.2.2
- react-apollo@1.0.0-rc.3

**Comment by helfer** [comment]
Closing this here since it's an apollo-client issue.
