### ISSUE TITLE
fetchMore does not respect options.fetchPolicy

### ISSUE THREAD

**Issue by dylanmoz** [apollographql/react-apollo#723]
## Steps to Reproduce

```javascript
graphql(gql`query getItems($page: Int) { items( { id } }`, {
  options: {
    fetchPolicy: 'cache-only',
    variables: { page: 1 }
  },
  props: (props) => {
    changePage(page) {
      return props.data.fetchMore({
        variables: { page },
        updateQuery: (prev, { fetchMoreResult }) => fetchMoreResult
      })
    }
  }
})(MyComponent)
```

### Issue

`fetchMore` makes a network request even though the fetchPolicy is set to 'cache-only'

### Expected Behavior

`fetchMore` respects `fetchPolicy` or there is another configuration such as `options.fetchMorePolicy`?

### Version
- apollo-client@1.2.2
- react-apollo@1.2.0

**Comment by stubailo** [comment]
I feel like that is expected behavior.

**Comment by psamim** [comment]
@DylanMoz Hi, Did you find any workaround? I want to use cached pages for pagination.

**Comment by DylanMoz** [comment]
@psamim I just ditched `fetchMore` and instead went for the standard usage of the higher order component with the variables for the query determined by passed in props.

**Comment by psamim** [comment]
@DylanMoz Thanks for the quick reply! You mean you use `withApollo` and access Apollo client via props?

**Comment by DylanMoz** [comment]
@psamim like so:
```
const Pagination = graphql(theQuery, {
  options: props => ({
    variables: {
      page: props.page,
      count: props.count,
      filter: createFilter(props.filter),
      sort: props.sort
    }
  })
])
```

You can then use the component like so: 
```
<Pagination page={3} sort={{ field: 'name', order: 'ASC' }} count={20} filter={{}}/>
```
