### ISSUE TITLE
data.loading stays false during a fetchMore

### ISSUE THREAD

**Issue by lorensr** [apollographql/react-apollo#727]
Inside render:

      console.log('render', User.length, loading, networkStatus)
    
When I call `data.fetchMore` twice, I get:

    render 100 false 7
    render 200 false 7
    render 300 false 7

Whereas I expect:

    render 100 false 7
    render 100 true 1
    render 200 false 7
    render 200 true 1
    render 300 false 7

- repo: https://github.com/lorensr/graphql-leaderboard/tree/a331af803b36ee2d65c85795d747e6cf4c83ba27
- here's the [render log](https://github.com/lorensr/graphql-leaderboard/blob/a331af803b36ee2d65c85795d747e6cf4c83ba27/components/ReputationLeaderboard.js#L8-L9) and the [fetchMore call](https://github.com/lorensr/graphql-leaderboard/blob/a331af803b36ee2d65c85795d747e6cf4c83ba27/components/ReputationLeaderboard.js#L89-L104)
- deployed: https://out-bkathectgx.now.sh/

### Version
- apollo-client@1.2.2
- react-apollo@1.2.0

**Comment by jbaxleyiii** [comment]
@lorensr I'll take a look! Would you be able to isolate this to a reproduction GitHub repo?

**Comment by lorensr** [comment]
Thanks! The repo I linked felt like a small reproduction to me—what should
I take out or what should I isolate?

**Comment by kombucha** [comment]
Hey @lorensr, 

I had the same issue and I investigated a bit.

In [`ReputationLeaderboard.js`](https://github.com/lorensr/graphql-leaderboard/blob/a331af803b36ee2d65c85795d747e6cf4c83ba27/components/ReputationLeaderboard.js), you have to the set `notifyOnNetworkStatusChange` to `true` in the options of your container : 

```js
export default graphql(usersByReputation, {
  options: {
    variables: {
      offset: USERS_STARTING_OFFSET,
      first: USERS_PER_PAGE
    },
    notifyOnNetworkStatusChange: true
  },
  // ...
})(ReputationLeaderboard)
```

Only then will you see the `data.loading` change to true (and `networkStatus` change to `3`, which is the value for `fetchMore`) in your component.

See [documentation about the notifyOnNetworkStatusChange option](http://dev.apollodata.com/react/api-queries.html#graphql-config-options-notifyOnNetworkStatusChange)

I wish it was true by default :/. Or maybe documented in the Pagination recipe !
Could be a PR if you're interested :)

Cheers

**Comment by lorensr** [comment]
Thank you @kombucha! 😄 Suggested the default change in #753

**Comment by stubailo** [comment]
I think this is an independent issue - we should make sure `loading` updates correctly even without that option, regardless of the decision for #753.
