### ISSUE TITLE
[RN 0.44]: Red Screen if unauthorized

### ISSUE THREAD

**Issue by spoeck** [apollographql/react-apollo#730]
If I set an invalid/expired token, I get following red screen in my react-native app:
`Error: Network error: Server response was missing for query 'undefined'. at new ApolloError`
<img src="https://cloud.githubusercontent.com/assets/8719777/26499717/e495e690-4233-11e7-9322-14830cc9fc16.png" width="45%">

The response code of the server is `401 Unauthorized` as expected. 

### Expected Behavior

I want that this kind of error is caught and the error is set to my props.
Or is it possible to handle the error with a middleware?

### Version
- react-apollo@1.2.0/1.3.0-alpha.1
- react-native@0.44

**Comment by jbaxleyiii** [comment]
@spoeck are you handling the error in props?

@helfer have you seen something like this before with 401's in AC?

**Comment by cyrus-za** [comment]
I am suddenly seeing this. I am not sure what code change triggered it. I am using next.js so got SSR going. If I refresh my page it throws the error, but navigating to the page from another does not. So clearly it has something to do with SSR.
