### ISSUE TITLE
childContext store shadows store from redux Provider

### ISSUE THREAD

**Issue by ivome** [apollographql/react-apollo#731]
The childContext property `store` shadows a potentially available store that was set in an outer `Provider` from the react-redux package. 

## Steps to Reproduce

```jsx
import Provider from 'react-redux';

<Provider store={mainStore}>
   // This component gets mainStore as context
   <ReduxConnectedComponent />
   <ApolloProvider store={apolloStore} client={apolloClient}>
      // This component gets apolloStore from context because
      // store childContext shadows the store from Provider
      <ReduxConnectedComponent />
   </ApolloClient>
</Provider>
```

### Buggy Behavior
ApolloProvider returns unnecessary child context value `store`.

### Expected Behavior
Could we remove the store from the childContext? If we need the redux store to manipulate data ourselves, we can always pass the store via the `Provider` from `react-redux`.

**Comment by jbaxleyiii** [comment]
@ivome thanks for this! We used to interact with the store directly, however its not used anymore!

Removing it should be pretty simple. Remove it in the ApolloProvider and graphql.jsx files and update tests which expect it.

Would you be able to do this?

**Comment by ivome** [comment]
@jbaxleyiii I started to look into this briefly. There is still the `client.initStore()` logic in the provider. It feels like this does not belong into the provider and should rather be handled inside of the ApolloClient. Could that also be removed or do we still need this?

**Comment by jbaxleyiii** [comment]
@ivome hmm, we used to need it but we may not anymore. Try taking it out and see what breaks?
