### ISSUE TITLE
Non-graphql data stored in apollo?

### ISSUE THREAD

**Issue by mmahalwy** [apollographql/react-apollo#732]
Would it be possible to store data that is not graphql related that typically in a redux app you can store inside the store?

For example, I'd like to grab the navigator's geolocation and utilize it in mutations. How can I store the geolocation with apollo and reuse it?

Thanks

**Comment by stubailo** [comment]
If you just want to use it in mutations, no need to store it! You can just pass it with the query.

Right now you can use the writeQuery and readQuery methods on the client with a fake query to save any data you want, that could be one approach!
