### ISSUE TITLE
Using query result in mutation passes through the __typename field

### ISSUE THREAD

**Issue by JonathanWbn** [apollographql/react-apollo#741]
I have mutation like this:
```
async updateGroceryList(_, { input: { grocery_list } }, { user }) {
  return await Customer.findByIdUpdate(
    user.roles.customer_id,
    { grocery_list },
    { 'new': true }
  );
}
```
Mutation type: 
```
updateGroceryList(input: updateGroceryListInput): Customer
input updateGroceryListInput {
  grocery_list: [groceryItem]
}
input groceryItem {
  item: String
  quantity: String
}
```

I am calling my mutation in React like so:
```
// fields: [{ item: 'hello', quantity: 'world' }, {...}, ...]

this.props.mutate({ variables: { input: { grocery_list: fields } } })
    .then(res => console.log(res))
    .catch(err => console.log(`error sending the query: ${err}`));
```
And I define the mutation in the component like this:
```
const mutation = gql`
  mutation updateGroceryList($input: updateGroceryListInput) {
    updateGroceryList(input: $input) {
      grocery_list {
        item
        quantity
      }
    }
  }
`;

export default graphql(mutation)(Grocery);
```
But when I send the mutation, this is my request payload:
```
mutation updateGroceryList($input: updateGroceryListInput) {
  updateGroceryList(input: $input) {
    grocery_list {
      item
      quantity
      __typename
    }
    __typename
  }
}
```
Which throws this error:
```
Variable "$input" got invalid value {"grocery_list":[{"item":"hello","quantity":"world"},{"item":"bye","quantity":"world","__typename":"Grocery"}]}.↵In field "grocery_list": In element #1: In field "__typename": Unknown field.
```

**Comment by stubailo** [comment]
Yeah this is because the queries have `__typename` added to them to make data normalization work better, and when you pass that result through to the mutation it's still there.

**Comment by JonathanWbn** [comment]
Okay, that makes sense. How can I approach to solve this problem tho? 
Should I add __typename when I define the input, like so?
```
```

**Comment by stubailo** [comment]
No I think the best workaround right now is to strip out the typename before passing the object into the mutation.

**Comment by JonathanWbn** [comment]
But the moment I call the mutation, there is nothing to strip out:
```
// fields: [{ item: 'hello', quantity: 'world' }, {...}, ...]

this.props.mutate({ variables: { input: { grocery_list: fields } } })
    .then(res => console.log(res))
    .catch(err => console.log(`error sending the query: ${err}`));
```

**Comment by aryo** [comment]
Are you sure each item in `fields` doesn't have `__typename` in it? Unless you've explicitly stripped them out from the query results, they'll be in there.

**Comment by JonathanWbn** [comment]
Okay, I guess I didn't do it correctly then. Will try again.
Thanks for the help, @aryo @stubailo !

**Comment by omt66** [comment]
Any solution for this other than the workaround suggested by @stubailo ?

**Comment by JonathanWbn** [comment]
@omt66 You can set up you ApolloClient to not add the `__typename` to your query results, like so:
```
new ApolloClient({
  addTypename: false,
  networkInterface: createNetworkInterface({ uri: '/graphql' })
});
```

**Comment by omt66** [comment]
Thanks, that's much better. I will give it a try.

**Comment by Rogant** [comment]
@JonathanWbn I guess that option is not available anymore https://www.apollographql.com/docs/react/basics/setup.html#ApolloClient

**Comment by mikefowler** [comment]
Before adding `addTypename: false` to your cache initializer, be aware that this solution will prevent you resolving fragments on unions and interfaces, [as described in the Apollo documentation for IntrospectionFragmentMatcher](https://www.apollographql.com/docs/react/recipes/fragment-matching.html).

**Comment by barbalex** [comment]
Looks like in a recent update warnings were added:
![2017-12-13_17h31_17](https://user-images.githubusercontent.com/669783/33950030-8e4d6966-e02b-11e7-9653-c5855b6544c5.png)

So now this is becoming a real pain.

Why was this issue closed? Is this not a bug?

**Comment by javorosas** [comment]
It would be nice to have a per-query option to strip out the `__typename`s. Something like:

```javascript
import { graphql } from 'react-apollo';
import myQuery from './query.gql';

const MyComponent = () => { ... };

export default graphql(myQuery, {
  addTypename: false
});
```

This could potentially provide cleaner data results in `this.props.data` and still be compatible with fragments/interfaces.

**Comment by mattfysh** [comment]
@JonathanWbn I was under the impression that fields not requested by the component are not passed into the component?

**Comment by JonathanZWhite** [comment]
Seems like stripping `__typename` from all query results with `addTypename: false` is too broad of a solution that could cause unintended consequences like @mikefowler pointed out. 

Another solution could be to use `filter` with a fragment using `graphql-anywhere`. 

```
<VoteButtons
  entry={filter(VoteButtons.fragments.entry, entry)}
  canVote={loggedIn}
/>
```

Where the fragment does not have `__typename` listed as an attribute. 

https://github.com/apollographql/apollo-client/blob/master/docs/source/features/fragments.md#filtering-with-fragments

**Comment by ikatun** [comment]
You can also use this package: `https://www.npmjs.com/package/typename-monkey-patch` which filters out `__typename` fields without doing `addTypename: false`.

You just require the module somewhere near the entry point of your app.

**Comment by djmgh** [comment]
This is still a nuisance. We shouldn't have to implement hacks or become an Apollo expert to perform basic functionality.

**Comment by arafel** [comment]
> ```js
> const { __typename, ...otherAttributes } = someQueryResultObject
> mutate(otherAttributes)
> ```

Thanks @speakingcode - that does the trick nicely.

**Comment by simkessy** [comment]
> ```js
> const { __typename, ...otherAttributes } = someQueryResultObject
> mutate(otherAttributes)
> ```


@speakingcode  doesn't really work if you have __typenames nested in your response.
