### ISSUE TITLE
GraphQL error: Schema must be an instance of GraphQLSchema

### ISSUE THREAD

**Issue by Ayc0** [apollographql/react-apollo#742]
When I run react-apollo with a mockNetworkInterface (last versions of react-apollo and apollo-test-utils, an error is constantly poping : 

```
GraphQL error: Schema must be an instance of GraphQLSchema.
Also ensure that there are not multiple versions of GraphQL installed
in your node_modules directory.
```

**Comment by mairh** [comment]
@Ayc0 Are you using `graphql-server-express`? If yes then you need to upgrade it to `0.8.0`. I don't think it is coming directly from `react-apollo`.

P.S -> Assuming you are running latest version of `graphql`

**Comment by Ayc0** [comment]
I am not connected to a server: I mock the data as the tuto says.

But I'm sure that It comes either from react-apollo or from apollo-test-utils: when I git clone, it works but with old packages and when I upgrade every packages, it crashes on both of them (this error with react-apollo)

**Comment by stubailo** [comment]
Can you post a reproduction with some code? We can't tell where that is coming without being able to see what you are doing.

**Comment by helfer** [comment]
@Ayc0 what's the output of `npm list | grep graphql`?

**Comment by Ayc0** [comment]
https://github.com/Ayc0/apollo

In the folder `client`, there is a version of the code which is working with old packages.
In the folder `client2`, there is exactly the same code but with the newest packages.

**Comment by Ayc0** [comment]
Last updates of apollo fix my problem
Thanks apollo team <3

**Comment by erlangxk** [comment]
install the same version of graphql as the one in react-apollo devDependencies list, for example, for react-apollo 1.4.15, just yarn add graphql@0.10.5.

**Comment by therealedsheenan** [comment]
this is just a version compatibility error between react-apollo ang graphql.

**Comment by fxlemire** [comment]
@stubailo Here's a reproduction: https://github.com/fxlemire/graphql-react-tutorial

It's basically the entire part 1 of [this tutorial](https://dev-blog.apollodata.com/full-stack-react-graphql-tutorial-582ac8d24e3b)

I've also tried with graphql@^0.10.5, to no avail.

Any help on how to fix this would be much appreciated!

**Comment by ivarmlee11** [comment]
This tutorial doesn't work anymore but it helps me understand how Apollo sets up a Higher Order Component.

**Comment by linhdsv** [comment]
I tried `yarn add graphql@0.10.5` and restarted the app, everything worked well to me.

**Comment by fxlemire** [comment]
Thanks @linhdsv ! Indeed the `^` was the culprit.

**Comment by zhoukekestar** [comment]
Thanks @linhdsv , `sudo npm install -g npm` & `npm install graphql@0.10.5` works for me.

**Comment by maximeg** [comment]
For those arriving after the battle, I solved things by adding this into my packages.json:

```
  "resolutions": {
    "graphql": "^0.11.0"
  },
```

This will instruct Yarn not to nest `graphql`and keep only one version (like the flat mode).

**Comment by pricetula** [comment]
I have tried all the above but still running to dep issues
```
npm list | grep graphql           
│ └── graphql-anywhere@4.0.2
│ │ └── UNMET PEER DEPENDENCY graphql@^0.11.3
│ ├── UNMET PEER DEPENDENCY graphql@^0.11.3
│ └── UNMET PEER DEPENDENCY graphql@^0.11.3
│ └── UNMET PEER DEPENDENCY graphql@^0.11.3
│ │ └─┬ graphql-extensions@0.0.5
│ ├─┬ graphql@0.10.5
│ └─┬ graphql-tools@1.2.3
│   └── @types/graphql@0.9.4
├── UNMET PEER DEPENDENCY graphql@0.10.5 extraneous
├── graphql-tag@2.5.0
├─┬ graphql-tools@2.11.0
npm ERR! peer dep missing: graphql@0.11.7, required by apollo-cache-inmemory@1.1.2
npm ERR! peer dep missing: graphql@^0.11.0, required by apollo-client@2.1.0
npm ERR! peer dep missing: graphql@^0.11.0, required by apollo-link-http@1.3.0
npm ERR! peer dep missing: apollo-client@^1.0.0, required by apollo-test-utils@0.3.2
npm ERR! peer dep missing: graphql@^0.11.3, required by apollo-link@1.0.5
npm ERR! peer dep missing: graphql@^0.11.3, required by apollo-link@1.0.5
```

**Comment by pricetula** [comment]
I have tried all above but still encountering below error
``` 
Error: Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory.
    at t.default (/Project/react-coolcat/dist/bundle.server.js:1:13926)
    at Object.t.validate (/Project/react-coolcat/dist/bundle.server.js:1:270198)
    at /Project/react-coolcat/dist/bundle.server.js:1:268684
    at /Project/react-coolcat/dist/bundle.server.js:1:269337
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

I checked graphql packages
 ```
npm list | grep graphql     
│ └── graphql-anywhere@4.0.2
│ │ └─┬ graphql-extensions@0.0.5
│ ├── graphql@0.10.5
│ └─┬ graphql-tools@1.2.3
│   └── @types/graphql@0.9.4
├─┬ graphql@0.11.7
├── graphql-tag@2.5.0
├─┬ graphql-tools@2.11.0
npm ERR! peer dep missing: apollo-client@^1.0.0, required by apollo-test-utils@0.3.2
```

Packages installed
```
"dependencies": {
    "apollo-cache-inmemory": "^1.1.2",
    "apollo-client": "^2.1.0",
    "apollo-link-error": "^1.0.2",
    "apollo-link-http": "^1.3.0",
    "apollo-server-express": "^1.2.0",
    "apollo-test-utils": "^0.3.2",
    "babel-polyfill": "^6.26.0",
    "babel-runtime": "^6.26.0",
    "body-parser": "^1.18.2",
    "express": "^4.16.2",
    "graphql": "^0.11.7",
    "graphql-tag": "^2.5.0",
    "graphql-tools": "^2.11.0",
    "react": "^16.1.1",
    "react-dom": "^16.1.1",
    ...
  },
```

**Comment by zhoukekestar** [comment]
@pricetula You have two versions of GraphQL include `0.10.5` & `0.11.7`. You should `npm install graphql@0.10.5 --save` to solve this issue.

**Comment by pricetula** [comment]
Hi @zhoukekestar  thanks i got it resolved nothing to do with multiple graphql copies.
I was using typeDefs incorrectly without making it executable using ```makeExecutableSchema({ typeDefs })``` on graphqlExpress()

**Comment by jiku** [comment]
Can also happen trying to import a makeExecutableSchema(...) exported in a different package.
