### ISSUE TITLE
Typescript Error: Types of property 'client' are incompatible

### ISSUE THREAD

**Issue by dlindenkreuz** [apollographql/react-apollo#743]
## Steps to Reproduce

```typescript
import ApolloClient, { createNetworkInterface } from "apollo-client"
import { ApolloProvider } from "react-apollo"

const client = new ApolloClient({
  networkInterface: createNetworkInterface({ uri: "/graphql" }),
})
const store = createStore(combineReducers({
  ...reducers,
  apollo: client.reducer(),
}), {}, applyMiddleware(client.middleware()))

ReactDOM.render(
    <ApolloProvider store={store} client={client}>
//                                        ^ error TS2322, see below
      <Layout />
    </ApolloProvider>,
    document.getElementById("root") as HTMLElement,
)
```

### Buggy Behavior

During setup of react-apollo and apollo-client, typescript throws the following error (highlights by me):

> TS2322: Type '{ store: Store<{}>; client: ApolloClient; children: Element; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<ApolloProvider> & Readonly<{ children?: ReactNode;...'.
  Type '{ store: Store<{}>; client: ApolloClient; children: Element; }' is not assignable to type 'Readonly<ProviderProps>'.
    Types of property 'client' are incompatible.
      Type 'ApolloClient' is not assignable to type 'ApolloClient'. Two different types with this name exist, but they are unrelated.

> src/index.tsx(22,21): error TS2322: Type '{ store: Store<{}>; client: ApolloClient; children: Element; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<ApolloProvider> & Readonly<{ children?: ReactNode;...'.
  Type '{ store: Store<{}>; client: ApolloClient; children: Element; }' is not assignable to type 'Readonly<ProviderProps>'.
    Types of property 'client' are incompatible.
      Type 'ApolloClient' is not assignable to type 'ApolloClient'. Two different types with this name exist, but they are unrelated.
        Types of property 'queryManager' are incompatible.
          Type 'QueryManager' is not assignable to type 'QueryManager'. Two different types with this name exist, but they are unrelated.
            Types of property 'scheduler' are incompatible.
              **Type 'QueryScheduler' is not assignable to type 'QueryScheduler'. Two different types with this name exist, but they are unrelated.
                Types have separate declarations of a private property 'pollingTimers'.**

### Expected Behavior

Typescript should be fine with the above code. The error did not occur with apollo-client@1.3.0 and react-apollo@1.2.0. I guess it just boils down to apollo-client@1.4.0 and react-apollo not having matching type defs.

### Version
- apollo-client@1.4.0
- react-apollo@1.2.0
- typescript@2.3.4

### Workaround

(duh)

```diff
- <ApolloProvider store={store} client={client}>
+ <ApolloProvider store={store} client={client as any}>
```

**Comment by jbaxleyiii** [comment]
This is now fixed via 1.4.0! You will need to update apollo-client to the same version!

**Comment by dlindenkreuz** [comment]
Dope. Congrats on the release, the new TypeScript annotations arrived just in time!

**Comment by cramhead** [comment]
I'm seeing this exact problem with as https://github.com/apollographql/react-apollo/issues/743

-   "react-apollo": "^2.5.6"
-  "apollo-client": "^2.6.0-rc.3"
-  "typescript": "3.5.1"

**Comment by chrisbchrist** [comment]
Same problems with most recent versions.  Any workarounds/plans to fix this?

**Comment by sprazzeus** [comment]
Slightly different but similar Typescript error:
`Property 'client' does not exist on type '{ children?: ReactNode; }'.  TS2339`

Versions used:
```
"react-apollo": "^3.1.5"
"apollo-client": "^2.6.10"
"typescript": "~3.7.2"
```

Code snippet:
```
const HelloUser = compose(withApollo)(({ client }) => {
  const auth = useAuth();
  const logout = async () => {
    await client.clearStore();

    auth.authClient.logout();
  };

  return (
    <Query query={CURRENT_USER_QUERY}>
      {({ loading, data }) => {
        if (loading) {
          return <p>Loading...</p>;
        }

        return (
          <div>
            <p>Hello {data.user.email}!</p>
            <button type="button" onClick={logout}>
              Logout
            </button>
          </div>
        );
      }}
    </Query>
  );
});
```
