### ISSUE TITLE
Error adding Component state when using graphql wrapper as decorator

### ISSUE THREAD

**Issue by joeldn** [apollographql/react-apollo#755]
## Steps to Reproduce

Adding a state type to a React Component class when decorated with the `graphql` wrapper function.

```ts
@graphql<IData, IProps>(query)
class TodoApp extends React.Component<IProps, IState> {
  public render() {
    const { todos } = this.props;
    return (
      <ul>
        {todos.map(({ id, text }) => (
          <li key={id}>{text}</li>
        ))}
      </ul>
    );
  }
}
```

### Buggy Behavior

The newly added type checking breaks my code with a `error TS1238: Unable to resolve signature of class decorator when called as an expression.` when adding state type, but only if the `graphql` wrapper function is used as a decorator. With 'normal' wrapping (see below) everything is fine.

```ts
const withData = graphql<IData, IProps>(query);

class TodoApp extends React.Component<IProps, IState> {
  public render() {
    const { todos } = this.props;
    return (
      <ul>
        {todos.map(({ id, text }) => (
          <li key={id}>{text}</li>
        ))}
      </ul>
    );
  }
}

const container = withData(TodoApp);
```

And of course in the initial decorated code, replacing `IState` with `any` works (which might be the reason why the tests are succeeding).

ADDITION:
I'm also unable to add functions to a react class as it starts complaining: `Property 'foo' is missing in type 'Component<IProps, ComponentState>'.` Again only when decorating the classes. Am I using this correctly?

### Version
- apollo-client@1.0.4
- react-apollo@1.4.2

**Comment by OneCyrus** [comment]
same issue here

**Comment by joeldn** [comment]
Is there any update on this? I'm now stuck with using version 1.2.0..

**Comment by joshmadewell** [comment]
seeing this as well

**Comment by samvik** [comment]
I'm seeing this issue on react-apollo 1.4.8. I'm unable to add any methods or variables to the component class or using a typed state (any-type works as reported above). When doing so I get the error message "Unable to resolve signature of class decorator when called as an expression. ...".

Have anyone got this to work?

So unless I do something wrong the decorator is at the moment unusable. I vote to reopen this issue.

"react": "^15.6.1",
"react-apollo": "^1.4.8",
"react-dom": "^15.6.1",

**Comment by mctep** [comment]
I have found some workaround:

```ts
@graphql<IData, IProps>(query)
class TodoApp extends React.Component<IProps, IState> {
  public render() {
    const { todos } = this.props;
    return (
      <ul>
        {todos.map(({ id, text }) => (
          <li key={id}>{text}</li>
        ))}
      </ul>
    ) as JSX.Element | false | null; // or `) as any;`
  }
}
```
May be it is a `TS` bug or not 😄 . See more: https://github.com/Microsoft/TypeScript/issues/17989

**Comment by mctep** [comment]
It's possible to patch original `graphql` decorator (oversee from `mobx-react`) but there is need to define additional property for typesafe: https://gist.github.com/mctep/adda5750271f8b0d181e0328e68afb56

**Comment by vcollado** [comment]
@samvik same here, using @mctep seems to fix the msg

**Comment by sijad** [comment]
same here. decorations make code looks very cleaner.
please fix this.
