### ISSUE TITLE
Support React 16

### ISSUE THREAD

**Issue by jpshelley** [apollographql/react-apollo#760]
## Steps to Reproduce

It seems apollo will need to support React 16 sooner rather then later. React-Native under the hood is already using `react@16.0.0-alpha`

https://github.com/facebook/react-native/issues/13291

See the couple of issues linked to that specific issue ^^

Yes its dumb that they depend on an alpha version. Is there anyway for Apollo to support it?
For what its worth my build currently seems to function okay minus some warnings, but jest testing support is failing due to conflicts between dependencies.

### Buggy Behavior

```bash
Test suite failed to run

    TypeError: Cannot read property 'ReactCurrentOwner' of undefined
      
      at Object.<anonymous> (node_modules/react-dom/cjs/react-dom-server.development.js:5861:36)
      at Object.<anonymous> (node_modules/react-dom/server.js:6:20)
      at Object.<anonymous>.graphqlTag (node_modules/react-apollo/lib/react-apollo.umd.js:2:191)
      at Object.<anonymous> (node_modules/react-apollo/lib/react-apollo.umd.js:5:2)
```

### Expected Behavior

Tests should pass.

### Version
- apollo-client@1.4.0
- react-apollo@1.4.2

**Comment by nouh** [comment]
+1

**Comment by helfer** [comment]
@jpshelley @nouh we've already included react@16-alpha to peer dependencies. If there are any other changes we need to make, please send over a PR!

**Comment by viczam** [comment]
Even though I have react-dom@15 included as a dependency of my project, react-dom@16 gets installed as a dependency of react-apollo, which causes rendering incompatibilities. 
Is this happening because react-dom@16 is listed as an optionalDependencies? 

Note: this doesn't happen for react package itself.

**Comment by helfer** [comment]
Yes, that could very well be the reason. Which version of npm are you using?

@jbaxleyiii do you remember why we moved this to an optional dependency? I feel like it had something to do with typescript types.

**Comment by viczam** [comment]
I'm using yarn, haven't tried with npm.
And I believe you made that change to better support react-native.

**Comment by jpshelley** [comment]
@helfer it might not be development related but only test related. My React Native app runs fine with the apollo versions listed, but my tests are failing. I know Enzyme is broken currently against React 16 so maybe thats the issue? https://github.com/airbnb/enzyme/pull/1007

**Comment by kernelgonnapanic** [comment]
I also have a problem with having react-dom@16 in optional dependencies in yarn.lock, as tests are failing due to: `Cannot read property 'ReactCurrentOwner' of undefined`. I've read somewhere that this kind of error is related to having two versions of react-dom in the app.
If I manually remove react-dom@16 from dependencies in yarn.lock, react-dom@15 gets installed and tests run smoothly. (I'm using all the libs in versions that use react 15).

**Comment by jcheroske** [comment]
Same issue here:
```
yarn list v0.27.5
├─ react-apollo@1.4.3
│  └─ react-dom@16.0.0-alpha.13
└─ react-dom@15.6.1
```
This is breaking my build.

**Comment by Danilo-Araujo-Silva** [comment]
For me when react-apollo is doing this:

```
optionalDependencies:
    react-dom "0.14.x || 15.* || ^15.0.0 || ^16.0.0-alpha"
```

it resolves like this:

```
"react-dom@0.14.x || 15.* || ^15.0.0 || ^16.0.0-alpha":
  version "16.0.0-alpha.13"
  resolved "https://registry.yarnpkg.com/react-dom/-/react-dom-16.0.0-alpha.13.tgz#c2b39aaf8645f1d664619fb49a1fbb9f60719c23"
  dependencies:
    fbjs "^0.8.9"
    loose-envify "^1.1.0"
    object-assign "^4.1.0"
    prop-types "^15.5.6"
```

But in my dependencies I have:

```
"dependencies": {
    "react": ">=15.5.4",
    "react-dom": ">=15.5.4"
},
```

which resolves with this:

```
react-dom@>=15.5.4:
  version "15.6.1"
  resolved "https://registry.yarnpkg.com/react-dom/-/react-dom-15.6.1.tgz#2cb0ed4191038e53c209eb3a79a23e2a4cf99470"
  dependencies:
    fbjs "^0.8.9"
    loose-envify "^1.1.0"
    object-assign "^4.1.0"
    prop-types "^15.5.10"
```
So the versions is mismatching.

**Comment by WickyNilliams** [comment]
Can i suggest rolling back the change to add react alpha, and adding that in a new major version, since it's clearly a breaking change. That way anyone who wants to upgrade can, whilst the rest of us can continue without issue

**Comment by eugene1g** [comment]
For me forcing react-dom to v15 by requiring it as `"react-dom": "<15.99"` resolved the conflict

**Comment by MichaelDeBoey** [comment]
I don't think this should be closed 😕
