### ISSUE TITLE
fetchMore doesn't work anymore after first error

### ISSUE THREAD

**Issue by koenpunt** [apollographql/react-apollo#761]
## Steps to Reproduce

1. Data is fetched using `graphql` HOC
2. Backend is made unreachable
3. `fetchMore` is called, an error is returned, which is correct
4. Backend is made reachable again
5. `fetchMore` is called again, the request succeeds and `updateQuery` is called, but the result passed down is still the old data, including the error of the previous request

### Buggy Behavior

Error and data of previous request is recycled, even when the current request succeeds.

### Expected Behavior

The error should disappear, and the updated result from `updateQuery` should be passed down to the child component.

For reference; these are the redux actions being called, so you see after the second init there's no more error, but the result is apparently handled incorrectly:

![image](https://user-images.githubusercontent.com/351038/26879509-9857b986-4b91-11e7-9bf3-8e84ce0124d6.png)

Also `fetchMore` starts working again after a `refetch`.

### Version
- `apollo-client@1.1.2`
- `react-apollo@1.2.0`

**Comment by koenpunt** [comment]
Anyone? ✨

**Comment by cesarsolorzano** [comment]
@koenpunt Could you provide a reproduction of this using [react-apollo-error-template](https://github.com/apollographql/react-apollo-error-template)? It would be helpful in tracking down this issue!
