### ISSUE TITLE
request headers are converted to lower case

### ISSUE THREAD

**Issue by chanan** [apollographql/react-apollo#762]
Using: "react-apollo": "^1.2.0"

Added the following middleware:

```
networkInterface.use([{
    applyMiddleware(req, next) {
        if (!req.options.headers) {
            req.options.headers = {}  // Create the header object if needed.
        }
        
        req.options.headers['X-Request-ID'] = uuid()
        next()
    }
}])
```

Looking at my headers in chrome network tab and in Fiddler4 (Windows debugging proxy) I see:

```
x-request-id: 0f5d506e-3aaa-48e9-87d9-c722eaae396f
```

expected result:

```
X-Request-ID: 0f5d506e-3aaa-48e9-87d9-c722eaae396f
```

**Comment by helfer** [comment]
@chanan I'm pretty sure apollo-client doesn't somehow manipulate the headers, so it's probably being done by the `fetch` implementation. However, according to RFC 2616 (see [here](https://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive)), header names are case-insensitive, so you should never write code that deals with HTTP header names in a case sensitive way.
