### ISSUE TITLE
Uncaught Error: Network Error: Failed to Fetch

### ISSUE THREAD

**Issue by kristojorg** [apollographql/react-apollo#763]
I am seeing some unfortunate uncaught errors in Chrome 55. I am making simple graphql queries using the HOC `query` component, but am getting errors. Not sure if the root of the problem is an actual timeout as shown, or if it is something else in `react-apollo` or `apollo-client`, but either way it seems like this should be handled more smoothly?

Any ideas how to begin debugging this?

<img width="508" alt="screen shot 2017-06-07 at 1 49 01 pm" src="https://user-images.githubusercontent.com/4398775/26894087-6213b6d2-4b8b-11e7-9db7-51049d231d6c.png">

### Version
- apollo-client@N/A
- react-apollo@^1.2.0

**Comment by AdamYee** [comment]
Hi @kristojorg, I believe there is an ongoing struggle with error handling. See https://github.com/apollographql/react-apollo/issues/57.

But for your scenario:
- If you look in the debugger Network tab, what do you see?
- If you can, try to hit a break point in your render function and see if `props.data.error` has anything more revealing.

Feel free to ask any follow up question in the react-apollo slack channel.

**Comment by townmulti** [comment]
This error seems to happen directly after the app loses connection or goes idle.

**Comment by dmarkow** [comment]
Having this happen too. Failed to Fetch errors when our users have left the page open for at least a couple minutes. Seems to never happen within the first 2 minutes of loading our page.

**Comment by townmulti** [comment]
@dmarkow 
Catching the error seems to be how others are handling this. 
Like in this closed issue:
https://github.com/apollographql/react-apollo/issues/758

**Comment by trevordmiller** [comment]
We are getting these `Network error: Failed to fetch` errors from Apollo randomly. We don't have any related errors in the API. It seems to be when the user leaves the app open for a while; does Apollo have any bugs related to this when the user leaves an app open for a while?

**Comment by trevordmiller** [comment]
@acomito Nope, but it went away when we upgraded to Apollo 2 :)

**Comment by vicacid** [comment]
same issue

**Comment by webmobiles** [comment]
yes, having same problem oto with 2.2.0

**Comment by serranoarevalo** [comment]
Any workaround for this?

**Comment by corysimmons** [comment]
Might help others: I had the Chrome extension HTTPS Everywhere installed and enabled everywhere so it was trying to force `http://localhost` to be `https` which caused the problem.

Disabling it for `localhost` and navigating to `http://localhost` fixed it.

**Comment by CarlFMateus** [comment]
Good morning there is some solution for this problem I have tried in those ways and I can not give solution to this problem.
This is the problem
Error: Network error: Failed to fetch

**Comment by hariantara** [comment]
@CarlFMateus  may I see your root code for integration with apollo and your query in HOC mode ?

**Comment by corysimmons** [comment]
Thank you Me-from-22-days-ago 🤗

**Comment by kasaiee** [comment]
I had this problem too with django as back-end, my front was ran on `localhost:3000` but the django settings was:

```
# settings.py
CORS_ORIGIN_WHITELIST = [
    'http://127.0.0.1:3000',
]
```

I changed the settings as bellow and error fixed.

```
CORS_ORIGIN_WHITELIST = [
    'http://127.0.0.1:3000',
    'http://localhost:3000',
]
```
