### ISSUE TITLE
Automatic cache update after mutation not working

### ISSUE THREAD

**Issue by figo77ll** [apollographql/react-apollo#767]
## Steps to Reproduce

I made an example react-native expo project to demo this:

[expo demo link](https://snack.expo.io/S12MoHvfW)

![screen shot 2017-06-08 at 3 09 46 pm](https://user-images.githubusercontent.com/2785470/26952948-8b39ab6c-4c5c-11e7-91a5-5fa3c28cabd4.png)

(adapted from the official appollo githunt app demo): The app shows a list of car brands with price. Total of 3 car are listed. Clicking the "update" button should suppose mutate the BMW car into "WWW" car.

### Buggy Behavior

Although server is successfully updated with "WWW", the app itself is not auto refreshed to reflect it.

### Expected Behavior

I would imagine it to auto refresh with a new car model name. I have to click on "refresh manually" to see the new data. This is based on my understanding of http://dev.apollodata.com/react/cache-updates.html#automatic-updates

Quote:

> If the id field on both results matches up, then the score field everywhere in our UI will be updated automatically!

In my demo, the id is guaranteed to be unique across all objects returned. So the redux internal cache is supposed to have all 3 car objects. When the mutation updates one of them by id, I'd expect the cache to be updated along the way, which in return will cause the app to re-render with latest data from cache.

### Version
- apollo-client@latest
- react-apollo@latest

Expo doesn't tell me pkg versions, so I'd assume they are latest.

**Comment by ksmth** [comment]
In line 27 of your example I can see that you're only querying for the ID of the mutation result. In order for the store to be updated, you need to query all fields you're interested in.
