### ISSUE TITLE
UpdateQuery does not update props.

### ISSUE THREAD

**Issue by khankuan** [apollographql/react-apollo#768]
## Steps to Reproduce
```
class MyEntriesPage extends Component {
  render() {
    ... // omitted
  }
}

export default graphql(LoadEntriesQuery, {
  props({ data }) {
    return {
      data,
      loadMoreEntries: () => {
        return data.fetchMore({
          query: LoadEntriesQuery,
          variables: {
            cursor: data.entries.pageInfo.endCursor,
          },
          updateQuery: (previousResult, { fetchMoreResult }) => {
            if (!fetchMoreResult) { return previousResult; }
            const final = {
              entries: {
                edges: [...previousResult.entries.edges, ...fetchMoreResult.entries.edges],
                pageInfo: fetchMoreResult.entries.pageInfo,
              },
            };
            return final;
          },
        });
      },
    };
  },
})(MyEntriesPage);
```

### Buggy Behavior
UI does not update after fetchMore.
Data in the redux store is updated but not the component.
Update: `next` function in subscribeToQuery does not get called even though store is updated.

### Expected Behavior
Props should be updated after updateQuery.

### Version
- apollo-client@1.4.2
- react-apollo@1.4.2

**Comment by khankuan** [comment]
I've tried pagination on another component and it worked but not the one above. Also, when i click load more again, the ui instantly updates to show the new item. It feels like either queryObservable is not triggering an update or the update is behind by 1 iteration.

**Comment by stevelacey** [comment]
I don't really know what I am doing with this but just to note, I am using `update` to muck around with the results and trying to implement `fetchMore` with `updateQuery` as per the docs and I was not getting new results in the UI... until I removed `cache-and-network`, and now it works as I expected

**Comment by jochienabuurs** [comment]
@khankuan coud you elaborate on fragment introspection? I've got the same issue where i have a page that uses a query to fetch its data, and it contains a modal with which the user can add something. it triggers a mutation, using refetchQueries and the same query that is used to provide the page with data to refresh the cache. Using the apollo dev tools i can see that the cache is updated, but the UI is only updated on refresh of the page

**Comment by dcDalin** [comment]
For some weird reason what @stevelacey suggested is kinda working out for me. I got rid of the `fetchPolicy="cache-and-network"` and voilà, the query is now updating. However, the loading state is no longer showing 😩
