### ISSUE TITLE
The "mutate" function in the client (obtained using "withApollo" on a react component) doesn't properly check the for a mutation parameter

### ISSUE THREAD

**Issue by RichardWepnerTU** [apollographql/react-apollo#771]
## Steps to Reproduce

- Create a react component using "withApollo" (e. g. `export default withApollo(MyComponent)`)
- call the mutate function of the client (`this.props.client.mutate`)
- don't pass a mutation in the parameter object (but as a "query" instead, e. g. `this.props.client.mutate({query: myMutation, variables: {[...]}})`)

### Buggy Behavior

As a result of the reproduction steps, you'll get a non-descriptive error message 

> Uncaught TypeError: Cannot read property 'kind' of undefined

### Expected Behavior

A proper error message like "no mutation"

### Version
- apollo-client@0.8.7
- react-apollo@0.11.2

**Comment by helfer** [comment]
Hi @RichardWepnerTU, thanks for filing an issue! This could easily be fixed by a simple PR to apollo-client, do you want to give it a try? 🙂
