### ISSUE TITLE
Is it possible to use the default 'dataIdFromObject' when specifying 'customResolvers'

### ISSUE THREAD

**Issue by MichaelDeBoey** [apollographql/react-apollo#774]
After reading [part 5](https://dev-blog.apollodata.com/tutorial-graphql-input-types-and-client-caching-f11fa0421cfd#b01d) of the _Full-stack GraphQL + React Tutorial_, I was just wondering if it's possible to use the default `dataIdFromObject` when specifying the `customResolvers`?

It looks a bit cumbersome to _reïmplement_ the default `dataIdFromObject` if you're happy with that one isn't it?
But I couldn't find a way to access it so I could use it in the `customResolvers` definition. 😕

**Comment by helfer** [comment]
@MichaelDeBoey yes you can! Maybe it's not well documented, but you can get the function that Apollo Client uses as `client.dataIdFromObject`.

**Comment by MichaelDeBoey** [comment]
@helfer So you could use the following then?
```js
import {ApolloClient, toIdValue} from 'react-apollo';

const client = new ApolloClient({
  customResolvers: {
    Query: {
      channel: (_, args) => {
        return toIdValue(ApolloClient.dataIdFromObject({ __typename: 'Channel', id: args['id'] }))
      },
    },
  },
});
```

**Comment by helfer** [comment]
Yes, but you'll have to replace `ApolloClient.dataIdFromObject` with `client.dataIdFromObject`.

**Comment by MichaelDeBoey** [comment]
But I'm still initializing the client here (i.e `new ApolloClient`) so...

**Comment by helfer** [comment]
I know, but just give it a try, it should work. The wonders of JavaScript! 😉

**Comment by MichaelDeBoey** [comment]
OK now I feel really dumb 😛 😓 😞 
Why's this even possible? 😮

**Comment by helfer** [comment]
It's only possible because the custom resolve function only runs after the client has been initialized. If it was run during the initialization then you're definitely right that it wouldn't work. GraphQL-js uses thunks for defining fields for the same reason (circular references).

**Comment by MichaelDeBoey** [comment]
Thanks for the explanation @helfer 😉
