### ISSUE TITLE
data.networkStatus is defined in absence of options.notifyOnNetworkStatusChange

### ISSUE THREAD

**Issue by lorensr** [apollographql/react-apollo#776]
## Steps to Reproduce

https://codesandbox.io/s/N2DMB7pv

Displays `props.data.networkStatus` on the page. 

### Buggy Behavior

On load, starts as `1` and changes to `7`. 

### Expected Behavior

Should instead be `undefined`. (As discussed [here](https://github.com/apollographql/react-apollo/issues/753#issuecomment-306098020))

### Version
- apollo-client@1.2.2
- react-apollo@1.2.0

**Comment by helfer** [comment]
This is not a bug, it's currently the intended behavior. Happy to talk about changing it if it's a real issue.

**Comment by lorensr** [comment]
Okay! Idc, was just following up on Sashko's comment 😊

**Comment by helfer** [comment]
Just to be clear, I think it would be better if we changed it, but that doesn't change the fact that it's currently the intended behavior 😄
