### ISSUE TITLE
Add support function for operationOptions

### ISSUE THREAD

**Issue by giautm** [apollographql/react-apollo#778]
## Steps to Reproduce

I want to do something like this. It make a selector for reselector: [sharing-selectors-with-props-across-multiple-components](https://github.com/reactjs/reselect#sharing-selectors-with-props-across-multiple-components)

```
  graphql(ORDER_DETAIL_QUERY, () => {
    const mapSelector = makeMapCausesText();
    return {
      options: ({ orderId }) => ({
        fetchPolicy: 'cache-first',
        variables: {
          id: orderId,
        },
      }),
      props: ({ ownProps, data }) => ({
        data,
        causesText: mapSelector(null, data),
      }),
    };
  }),
```
But currently `operationOptions` just accept a Object.

The transform of my `mapSelector` transform a array of item to `Immutable.Map()`, so i want it do only once.

### Buggy Behavior

Can't create selector for multiple-components.

### Expected Behavior

Can create selector for multiple-components.

### Version
- apollo-client@1.4.2
- react-apollo@1.4.2

**Comment by helfer** [comment]
@giautm I'm not sure I understand correctly. You would like to be able to run a function on some props before passing them into the component?

**Comment by giautm** [comment]
Sorry, my English too bad to explain. Please check out the first agrument of redux-react `connect` api: https://github.com/reactjs/react-redux/blob/master/docs/api.md#arguments

> Note: in advanced scenarios where you need more control over the rendering performance, mapStateToProps() can also return a function. In this case, that function will be used as mapStateToProps() for a particular component instance. This allows you to do per-instance memoization. You can refer to #279 and the tests it adds for more details. Most apps never need this.
