### ISSUE TITLE
MockedProvider does not return data when fetchPolicy is set to "cache-and-network"

### ISSUE THREAD

**Issue by eskimoblood** [apollographql/react-apollo#779]
MockedProvider does not return data when fetchPolicy is set to `cache-and-network`. When removing the fetchPolicy part from my `graphql` call, the test data are returned.

### Version
- apollo-client@<1.1.2r>
- react-apollo@<1.4.2>

**Comment by helfer** [comment]
Thanks for filing an issue @eskimoblood. Would you be able to provide a reproduction of this using the [react-apollo-error-template](https://github.com/apollographql/react-apollo-error-template)?

**Comment by derek-duncan** [comment]
Same issue. Try mounting a `graphql` component with `fetchPolicy: 'cache-and-network` wrapped in a `<MockedProvider>`.

**Comment by Carlows** [comment]
I'm also having this issue, I get:

```
Network error: No more mocked responses for the query: query allPublications
```

When using 'cache-and-network' as fetchPolicy.

**Comment by stubailo** [comment]
Can you provide a reproduction we can run please?

**Comment by jbreckel** [comment]
not a complete reproduction, but `cache-only` is also not working with a mock:

```
graphql(gql`
query {
  __schema {
    types {
      name
    }
  }
}`, {
  options: () => ({
    fetchPolicy: 'cache-only',
  }),
  props: ({ data }) => ({
    data: console.log(data) || data,
  }),
})
```
logs twice:
```
{ 
      refetch: [Function: bound ],
      fetchMore: [Function: bound ],
      updateQuery: [Function: bound ],
      startPolling: [Function: bound ],
      stopPolling: [Function: bound ],
      subscribeToMore: [Function: bound ],
      loading: false,
      networkStatus: 7,
      error: [Getter],
}
``` 

when changing to:
```
graphql(gql`
query {
  __schema {
    types {
      name
    }
  }
}`, {
  options: () => ({}),
  props: ({ data }) => ({
    data: console.log(data) || data,
  }),
})
```

it logs the second time:
```
{
      refetch: [Function: bound ],
      fetchMore: [Function: bound ],
      updateQuery: [Function: bound ],
      startPolling: [Function: bound ],
      stopPolling: [Function: bound ],
      subscribeToMore: [Function: bound ],
      loading: false,
      networkStatus: 7,
      error: [Getter],
      __schema: {...},
}
```

**Comment by polmann** [comment]
@stubailo @helfer using what @jbreckel provided above were you able to reproduce this issue?

**Comment by flpStrri** [comment]
Any update on this issue?

**Comment by vctormb** [comment]
I'm having this problem too when trying to update the cache with a MockedProvider.

**Comment by jozanza** [comment]
I'm also running into this issue when using a `Query` component with a `cache-only` fetchPolicy.

**Comment by hashina** [comment]
The same to me

**Comment by kpruden** [comment]
Any way to get this issue re-opened? I'm seeing it too when using `fetchPolicy: cache-only`
