### ISSUE TITLE
Batching doesn't batch redux actions

### ISSUE THREAD

**Issue by jalooc** [apollographql/react-apollo#780]
Not sure if it's by design or just an overlook, but batching in react-apollo fires as many redux-actions as queries, even though there's just one, properly batched network request. Imho it's a big, potential performance issue, as firing whole redux lifecycle several times jeopardises the whole batching purpose (not in terms of network usage, but in terms of cpu performance).

Maybe batching APOLLO_QUERY_INIT and APOLLO_QUERY_RESULT in form of [such middleware](https://github.com/tshelburne/redux-batched-actions) would be possible? The batching mechanism could be moved to the `graphql()` function and batch even before any action is fired.

**Comment by helfer** [comment]
@jalooc That is indeed the case. Has it been a performance issue in practice for you? We're currently actively working on refactoring the store, which should enable you to make changes like this yourself and share them with the community.

**Comment by jalooc** [comment]
@helfer Yes it has: the main thread time needed by redux to apply 26 batched queries rises to over 200ms (comparing to 5-10ms when 1 query is processed). The relation between the number of queries and the time spent in redux is most probably linear, so the overall win in batching isn't that big after all.

Anyway, I'm glad this is already under your consideration. If you need any help or further insight, please let me know.

**Comment by helfer** [comment]
Thanks @jalooc! Once we have a clear spec for the new store API would you be interested in helping us build out the Redux version of the store? That way we could make sure that batching support is considered from the start 🙂

**Comment by jalooc** [comment]
I'd be glad ;)
