### ISSUE TITLE
Flow definitions causing error: "Named import from module `react`."

### ISSUE THREAD

**Issue by pitr12** [apollographql/react-apollo#785]
Using typedefs from react-apollo causes flow error to appear: `Named import from module 'react'. This module has no named export called 'Component'.`

Issue is exactly same as one referred here: https://github.com/facebook/flow/issues/3685

The cause of problem is probably that in index.js.flow
`import type { Component } from 'react';`is  outside of a declare module block.

When it is moved into declare module block, errors disappear.

### Version
- apollo-client@1.4.1
- react-apollo@1.4.2

**Comment by helfer** [comment]
Hey @pitr12, thanks for filing the issue. Yeah, it seems like we could easily fix this by importing it in the proper way. Would you mind making a PR? 🙂  🙏

**Comment by trevordmiller** [comment]
Has this been released? Also running into it. Thank you.

**Comment by steida** [comment]
Here is quick fix https://github.com/este/este/commit/00b86b75bef79095c789683388f1fb1332983c16

**Comment by hyusetiawan** [comment]
any news on this?
