### ISSUE TITLE
New TypeScript definitions broken + cause critical slowdowns of the language server

### ISSUE THREAD

**Issue by dsifford** [apollographql/react-apollo#786]
Opening this issue from per the request of @jbaxleyiii in https://github.com/apollographql/react-apollo/pull/695#issuecomment-307812329

## The Gist
My personal issue in detail can be found in #695. In short, here's the issues I'm experiencing:

#### 1. The nested deeply-dependent type definitions are causing Visual Studio Code to freeze on any file that contains the `graphql` function provided by this library.

- I'm running a Linux machine with a 4-year-old intel i7 quad-core processor and that's still not enough to make VSCode not be completely sluggish.\*
- When I "click to definition" on the `graphql` function, my editor crashes completely.

> \* Machine specifics: `Linux archlinux 4.11.3-1-ARCH #1 SMP PREEMPT Sun May 28 10:40:17 CEST 2017 x86_64 GNU/Linux`

#### 2. Types will not compile even after adjusting the code in my application.

- The types currently do not compile in their current form (after adjusting per the suggestions in both the PR and the changelog) for in the application where I'm using react-apollo. ([this file specifically](https://github.com/aliemteam/aliemcards/blob/master/app/cards/Card.tsx)).
- The types currently do not compile **in this repository** in this file: https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/api.test.tsx.
- Other known users to be affected by this are @alexzielenski and @exihuatl (based on comments/reactions in the pull request thread).

#### 3. The tests for the new type definitions are being tested against components that all have the `any` type for both `Props` and `State`, which seems dangerous.

<details>
  <summary>[Click me] Literally every query test case is affected by this potentially dangerous type casting.</summary>
<ul>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/api.test.tsx#L50">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/api.test.tsx#L50</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/api.test.tsx#L93">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/api.test.tsx#L93</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/api.test.tsx#L124">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/api.test.tsx#L124</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/api.test.tsx#L202">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/api.test.tsx#L202</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/errors.test.tsx#L81">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/errors.test.tsx#L81</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/errors.test.tsx#L124">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/errors.test.tsx#L124</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/errors.test.tsx#L162">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/errors.test.tsx#L162</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/errors.test.tsx#L212">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/errors.test.tsx#L212</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/errors.test.tsx#L264">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/errors.test.tsx#L264</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/index.test.tsx#L99">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/index.test.tsx#L99</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/index.test.tsx#L126">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/index.test.tsx#L126</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/index.test.tsx#L156">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/index.test.tsx#L156</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/index.test.tsx#L186">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/index.test.tsx#L186</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/index.test.tsx#L256">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/index.test.tsx#L256</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/index.test.tsx#L329">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/index.test.tsx#L329</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/index.test.tsx#L359">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/index.test.tsx#L359</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/lifecycle.test.tsx#L61">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/lifecycle.test.tsx#L61</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/lifecycle.test.tsx#L155">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/lifecycle.test.tsx#L155</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/lifecycle.test.tsx#L211">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/lifecycle.test.tsx#L211</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/lifecycle.test.tsx#L258">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/lifecycle.test.tsx#L258</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/lifecycle.test.tsx#L311">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/lifecycle.test.tsx#L311</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/lifecycle.test.tsx#L367">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/lifecycle.test.tsx#L367</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/loading.test.tsx#L44">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/loading.test.tsx#L44</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/loading.test.tsx#L68">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/loading.test.tsx#L68</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/loading.test.tsx#L94">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/loading.test.tsx#L94</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/loading.test.tsx#L134">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/loading.test.tsx#L134</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/loading.test.tsx#L187">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/loading.test.tsx#L187</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/loading.test.tsx#L232">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/loading.test.tsx#L232</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/loading.test.tsx#L280">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/loading.test.tsx#L280</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/loading.test.tsx#L329">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/loading.test.tsx#L329</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/loading.test.tsx#L402">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/loading.test.tsx#L402</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/observableQuery.test.tsx#L66">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/observableQuery.test.tsx#L66</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/observableQuery.test.tsx#L179">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/observableQuery.test.tsx#L179</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/observableQuery.test.tsx#L215">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/observableQuery.test.tsx#L215</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/observableQuery.test.tsx#L267">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/observableQuery.test.tsx#L267</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/observableQuery.test.tsx#L335">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/observableQuery.test.tsx#L335</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/polling.test.tsx#L70">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/polling.test.tsx#L70</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/polling.test.tsx#L94">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/polling.test.tsx#L94</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/skip.test.tsx#L45">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/skip.test.tsx#L45</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/skip.test.tsx#L71">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/skip.test.tsx#L71</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/skip.test.tsx#L101">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/skip.test.tsx#L101</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/skip.test.tsx#L138">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/skip.test.tsx#L138</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/skip.test.tsx#L164">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/skip.test.tsx#L164</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/skip.test.tsx#L192">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/skip.test.tsx#L192</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/skip.test.tsx#L236">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/skip.test.tsx#L236</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/skip.test.tsx#L296">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/skip.test.tsx#L296</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/skip.test.tsx#L366">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/skip.test.tsx#L366</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/skip.test.tsx#L413">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/skip.test.tsx#L413</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/updateQuery.test.tsx#L44">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/updateQuery.test.tsx#L44</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/updateQuery.test.tsx#L69">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/updateQuery.test.tsx#L69</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/updateQuery.test.tsx#L90">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/updateQuery.test.tsx#L90</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/updateQuery.test.tsx#L122">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/updateQuery.test.tsx#L122</a></li>
<li><a href="https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/updateQuery.test.tsx#L159">https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/updateQuery.test.tsx#L159</a></li>
</ul>
</details>

## Suggestions

Aside from fixing the compile issues and the `any` type casting described above, perhaps there might be a way to make the type dependency chain not so long? This singular problem I think is the issue for users (like me) who depend on realtime type checking using the typescript language server. (This is a standard feature in Visual Studio Code).

> **Aside:** From the images that @jbaxleyiii posted in his pull-request, it _appears_ that he's also using VSCode. I'm wondering why these issues are not also affecting him? I wonder what type of machine he's running?

## Steps to Reproduce

(This should be the easiest thing to reproduce from the list of issues I described above).
1. Open https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/api.test.tsx in this repository in Visual Studio Code. Does this compile for you?

### Version
- apollo-client@1.4.2
- react-apollo@1.4.2
- typescript@2.4.0

## Final Notes

I'm happy to help in any way I can. Regardless of these issues, you all deserve a huge high-five for such amazing work on the apollo platform. It seriously has made my API development experience much more enjoyable! Thanks for all you and the rest of apollo team do! 😄 👏

**Comment by alexzielenski** [comment]
I've been able to use the types without loss of information (but have seen the TS server slowdown mentioned in VS code) without casting to `any` through the following:

Some helper file:
```typescript
import { QueryProps as QP } from 'react-apollo';

interface MutationOpts<T> {
    variables?: Object;
    optimisticResponse?: Object | Function;
    updateQueries?: MutationQueryReducersMap;
    refetchQueries?: string[] | /*PureQueryOptions*/any[];
    update?: (proxy: DataProxy, data: { data: T }) => void;
}
export type MutationFunc<T> = (options: MutationOpts<T>) => Promise<ApolloQueryResult<T>>;
export type QueryProps<P, R> = P & {
    data: QP & R;
}
```

and in my components:
```typescript
interface MyResults {
  currentUser: IServerUserResponse;
}
interface MyProps {
  exposedProp: boolean;
}
interface MyMutations {
  login: MutationFunc<IServerUserResponse>;
}
interface MyState {
  searchQuery: string;
}

export default graphql<MyResults, MyProps>(query, opts)(class ApolloComponent extends React.Component<QueryProps<MyProps & MyMutations, MyResults>, MyState> {
...
});
```
Where `IServerUserResponse` is an interface describing your GraphQL response for something like a user object as specified by your schema. This method returns a component exposing only `MyProps` to be used like:

```typescript
import ApolloComponent from './component';
import * as React from 'react';
React.render(
  <ApolloComponent exposedProp />
);
```
where omitting `exposedProp` will trigger an error unless it's optional since it is a member of `MyProps`

**Comment by dsifford** [comment]
Any updates on this @helfer @stubailo @jbaxleyiii? Still stuck pre 1.4.0 because of this.

Also, I noticed that one of your tests has a typo in it that would render the test broken. This leads me to believe that these tests aren't actually being ran?

https://github.com/apollographql/react-apollo/blob/master/test/react-web/client/graphql/queries/skip.test.tsx#L101

Here's the typo from the link above:

```diff
- class Container extends React.Component<any, any> {8
+ class Container extends React.Component<any, any> {
```

**Comment by alexzielenski** [comment]
I'll also note that the current definitions do not include the `update` mutation option.

**Comment by skosch** [comment]
> I'll also note that the current definitions do not include the update mutation option.

Am I correct in assuming that this is the reason for #769 and #810?
Getting those typings in order really would be a big step forward.

**Comment by alexzielenski** [comment]
@skosch I don't think so. Those issues seem to be stemmed from incomplete typings and improper explicit types. A lot of our headaches could be solved if the typescript language server had stronger type inference built into it but unfortunately we need to keep annotating the types for invocations of the `graphql` function in `typescript` (atleast in my case) to avoid compiler errors.

**Comment by alexzielenski** [comment]
@skosch I don't think so. Those issues seem to be stemmed from incomplete typings and improper explicit types. A lot of our headaches could be solved if the typescript language server had stronger type inference built into it but unfortunately we need to keep annotating the types for invocations of the `graphql` function in `typescript` (atleast in my case) to avoid compiler errors.

**Comment by itajaja** [comment]
Hi, I think the editor problems are strictly not related to react-apollo, but to the experimental decorator feature. I had problems using other decorators from other libs, and switching the syntax from decorator to normal curry solves any perf problem, both with react-apollo and with other decorators. I can reproduce this quite reliably

**Comment by jbaxleyiii** [comment]
@dsifford I've started working on some of this now! I'm not 100% how to get around the crashing? Maybe by moving the types to a different file and importing them? I can give that a try and see if it helps!

I'm currently working on the react typings bug that is preventing people from using the latest! I'll keep you posted on progress!

**Comment by dsifford** [comment]
@jbaxleyiii 🙏 You are awesome. Many thanks for all your hard work!

If there's anything you'd like me to assist with, let me know and I'd be happy to help where needed / able.

**Comment by dsifford** [comment]
@jbaxleyiii I finally got around to looking at both your changes and the associated blog post you wrote. Thanks for taking the time to do that.

Unfortunately, it is looking like your changes will still not work for me.

Your blog post describes in great detail on how to apply the changes to stateless functional components. However, it makes no mention on how to apply these changes to stateful component classes (i.e. `Component` and `PureComponent`).

There are some areas in my application where I cannot use functional components as the components carry state. In these circumstances, no matter what I do I get the following errors...

### Without any type casting (`@graphql()`)

```
Argument of type 'typeof CardListContainer' is not assignable to parameter of type 'CompositeComponent<{ data?: QueryProps | undefined; mutate?: MutationFunc<{}> | undefined; }>'.
  Type 'typeof CardListContainer' is not assignable to type 'StatelessComponent<{ data?: QueryProps | undefined; mutate?: MutationFunc<{}> | undefined; }>'.
    Type 'typeof CardListContainer' provides no match for the signature '(props: { data?: QueryProps | undefined; mutate?: MutationFunc<{}> | undefined; } & { children?: ReactNode; }, context?: any): ReactElement<any> | null'.
```

### Single `any` cast (`@graphql<any>()`)

```
Unable to resolve signature of class decorator when called as an expression.
  Type 'ComponentClass<{}>' is not assignable to type 'typeof CardListContainer'.
    Type 'Component<{}, ComponentState>' is not assignable to type 'CardListContainer'.
      Property 'handleChange' is missing in type 'Component<{}, ComponentState>'.
```

### Double `any` cast (`@graphql<any, any>()`)

```
Unable to resolve signature of class decorator when called as an expression.
  Type 'ComponentClass<{}>' is not assignable to type 'typeof CardListContainer'.
    Type 'Component<{}, ComponentState>' is not assignable to type 'CardListContainer'.
      Property 'handleChange' is missing in type 'Component<{}, ComponentState>'.
```

### Triple `any` cast (`@graphql<any, any, any>()`)

```
Unable to resolve signature of class decorator when called as an expression.
  Type 'ComponentClass<any>' is not assignable to type 'typeof CardListContainer'.
    Type 'Component<any, ComponentState>' is not assignable to type 'CardListContainer'.
      Property 'handleChange' is missing in type 'Component<any, ComponentState>'.
```

With respect, these changes have made my personal development experience plummet. Static typing should not do this; _especially_ when receiving it from a library. 

Can we please work on something better? I would love to help. Please reach out to me by email if you'd like to chat more about it. I think it would be much easier to express my thoughts and hear yours verbally, rather than type them all out here.

**Comment by jbaxleyiii** [comment]
@dsifford I'm so sorry to hear this! What about the class methods listed here http://dev.apollodata.com/react/using-with-types.html#classes-vs-functions

Does that help?

**Comment by dsifford** [comment]
@jbaxleyiii Thanks for the response. The docs you've linked to provide further clarification. I'm pretty sure that way will work.

However, I'm going to still continue stubbing the types because I still don't see how casting merged props from the decorator into the component is any better than just merging the props and explicitly setting `Props` on the component class.

There very well might be situations that your way provides a clear benefit, but for my application, the API is fairly simple and doesn't require all the extra complex sugar. 

Thanks again for taking the time to respond.

**Comment by domachine** [comment]
I'm currently running into the same issue with slowdowns of the language server. Is there anything I can do to work around?

**Comment by gilbert** [comment]
Slowdowns are happening for me too in Sublime Text. Today was the first day it crashed on me!

Not only is it slow, but the example from the documentation doesn't seem to be working. I get the following errors:

```
components/profile/my-groups.tsx(23,41): error TS2459: Type '(QueryProps & Response) | undefined' has no property 'loading' and no string index signature.
[0] components/profile/my-groups.tsx(23,50): error TS2459: Type '(QueryProps & Response) | undefined' has no property 'error' and no string index signature.
[0] components/profile/my-groups.tsx(23,57): error TS2459: Type '(QueryProps & Response) | undefined' has no property 'self' and no string index signature.
```

Using the following code:

<details>
  <summary>Click me to see the code</summary>

```jsx
import * as React from 'react'
import gql from 'graphql-tag'
import { graphql } from 'react-apollo'


export const GROUPS_QUERY = gql`
  query self {
    groups {
      name
      name_id
    }
  }
`
type MemberedGroup = {
  name: string,
  name_id: string
}
type Response = { self: { groups: MemberedGroup[] } }


const withGroupData = graphql<Response>(GROUPS_QUERY, {})

export default withGroupData(({ data: { loading, error, self } }) => {
  if (loading) return <div>Loading...</div>
  if (error) return <h2>ERROR!</h2>

  return <div className="my-groups"></div>
})
```
</details>

.

and using the following package versions:

- apollo-client: 1.9.1
- react-apollo: 1.4.14
- typescript: 2.3.4
- react: 15.6.1

**Comment by nmuth** [comment]
I have some `tsserver` logs related to the slowdown bug. Three lines, 22 megabytes 😮. Summary:

```
Info 251  request: {"command":"quickinfo-full","seq":"2011","arguments":{"file":"/Users/nmuth/Projects/fulgid/v2.fulgid.io/pages/post/details.js","line":42,"offset":17}}
Perf 252  2011::quickinfo-full: elapsed time (in milliseconds) 17022.3773
Info 253  response: (22MB of JSON)
```

[Here's the full file on Google Drive](https://drive.google.com/open?id=0BxyeMzvR9926eVIxNlZZeEswMGc). Let me know if you can make any sense of it.

And [here's the source file as a gist](https://gist.github.com/nmuth/223d765c89b0055926d0b359c81641ff).

**Comment by filtudo** [comment]
+1 here

**Comment by bitrix1** [comment]
@alexzielenski 
You are the only one who gave a ready-made example ... In other places there is not even a hint of difference
state and props from gql``
and
options: {variables: {identityId: 'user-id'}}
Now I understand how this works, thanks.
