### ISSUE TITLE
Server Side Rending: first noSSR component get no data

### ISSUE THREAD

**Issue by ClemensSahs** [apollographql/react-apollo#793]
## Steps to Reproduce

Hope this isn't isolated to much. In out case we have much more wrapper components. But I don't think this compromise the general situation.

```JSX
const childWithoutSSR = (props) {
  if (props.data.loading) {
    return <Loading />
  return (
    <div>{props.data.widget.onlyLoadedOnClient}</div>
  ));
}

const childWithoutSSRAndData = graphql(...)(childWithoutSSR);

const parentWithSSR = (props) {
  return props.widgetList.map((widget) => (
    <childWithoutSSRAndData key={widget.id} id={widget.id} />
  ));
}

const parentWithSSRAndData = graphql(...)(parentWithSSR);


<html><body>
<parentWithSSRAndData id={1} />
<parentWithSSRAndData id={2} />
</body></html>

```

### Buggy Behavior

The first```Child``` never have a ```props.data.widget```, but any following child work as expected!

If ```parent``` has ```ssr=false``` anything work fine, too.
In the second parent any child thing work fine, too.

DevTool Network: data fetch correct
Redux DevTool: data stored correct
Apollo DevTool: data stored correct (in my mind only a redux display?)
Apollo DevTool: first child was not logged... but parent query 2 times ?!?

### Expected Behavior

Frist noSSR component get data correct.

### Version
- apollo-client@1.4.2
- react-apollo@1.4.2
- react-redux@5.0.5

Im not sure we made some thing wrong or this is a bug.

**Comment by helfer** [comment]
Hi @ClemensSahs thanks for filing an issue! Could you please provide a reproduction for it using https://github.com/apollographql/react-apollo-error-template so we can try to fix it? Thanks! 🙂

**Comment by ClemensSahs** [comment]
@helfer the reproduction template is only a Client Side Rendere Template ;) in this issue we have a mixed case CSR and SSR

sure we can reproduction repo ASAP

**Comment by ClemensSahs** [comment]
@helfer repoduction is ready ;)
https://github.com/ClemensSahs/kit/tree/react-apollo-793

**Comment by wmertens** [comment]
I have the same problem. Some of my components are not getting their props when the getDataFromTree is walking the tree.

To inspect what's happening I just run the server with the --inspect flag and put a conditional breakpoint on a component with the issue.

The odd thing is that it's happening on e.g. an Icon component that is not directly connected with react-apollo.

**Comment by wmertens** [comment]
@helfer any idea on what could be happening? Anything I can do to pinpoint the problem?

**Comment by wmertens** [comment]
No change with React v16 beta1…

**Comment by jbaxleyiii** [comment]
I'll be taking a look at this today!

**Comment by jbaxleyiii** [comment]
@ClemensSahs can you describe the issue in that repo? It all looks like it is working as expected to me?

**Comment by wmertens** [comment]
I managed to repro the problem all the way to me :) so I don't actually have this issue. If @ClemensSahs doesn't have it anymore either I suppose this can be closed…

**Comment by ClemensSahs** [comment]
It looks like the reproduction repo work fine? 

Not sure how... but I will check our codebase and check the version off the dependencies.

@jbaxleyiii 
In the case of that issue. The first message component run in to this line. https://github.com/ClemensSahs/kit/blob/react-apollo-793/src/app.js#L115
