### ISSUE TITLE
Query Does Not Run After Bug/Fix (in dev)

### ISSUE THREAD

**Issue by timscott** [apollographql/react-apollo#796]
## Steps to Reproduce

I have a component like so:

```js
Thing = graphql(ThingQuery, {
  options: ({thing}) => {
    return {
      fetchPolicy: 'network-only',
      variables: thing
    };
  }
})(Thing);
```

In development, I get some error with the query -- e.g., the query syntax is bad or the variables are bad. The server gives a 500.

### Buggy Behavior

Then I fix the bug. But the query never again runs. On the first render, `data.loading` is `false`, `data.error` is `undefined`, and `data.thing` is also `undefined`, which causes an error in the component.  The network panel shows that the query is never called on the server.

The only way I can ever get the query to run again is to manually delete `reduxPersist:apollo` from local storage.

### Expected Behavior

Because I have set `options.fetchPolicy` to "network-only", the query should be called from the server every time.

I think it should be called to the server with any `fetchPolicy`, since it has failed.

### Version
- apollo-client@1.4.2
- react-apollo@1.4.2

**Comment by helfer** [comment]
Hey @timscott, thanks for filing an issue. That sounds very strange. Could you provide a reproduction of this using react-apollo-error-template? That would help us a lot in tracking down the issue.

**Comment by timscott** [comment]
@helfer - I will try to do that.

Meanwhile, I did a little debugging. The case I'm looking at hits [this line](https://github.com/apollographql/apollo-client/blob/8f362ae8f1f8026adf287dacc93b3ba42b57d259/src/data/readFromStore.ts#L160): 

```js
if (! context.returnPartialData) {
  throw new Error(`Can't find field ${storeKeyName} on object (${objId}) ${JSON.stringify(obj, null, 2)}.`);
}
```

It gets there because on [this line](https://github.com/apollographql/apollo-client/blob/8f362ae8f1f8026adf287dacc93b3ba42b57d259/src/data/readFromStore.ts#L150) ```type``` is `undefined`. At this point `typename` equals 'Query'. I can see that there is no key in the store for this query.

The throw is caught [here](https://github.com/apollographql/apollo-client/blob/479099ee0793939ecc2744ca805d11096c04192d/src/core/QueryManager.ts#L963) which seems to swallow the error and just pass on empty data instead of failing loudly.

It seems like it just not handling a cache miss, but it's very hard for me to understand exactly what's going on. If you have any thoughts, let me know. Otherwise I will try to replicate.

**Comment by timscott** [comment]
I should also point out that I had been integrating Apollo with my store.

```js
const store = createStore(
  combineReducers({
    // other reducers
    apollo: apolloClient.reducer()
  }),
  {},
  compose(
    applyMiddleware(
      // other middleware
      apolloClient.middleware()
    ),
    autoRehydrate()
  )
);
persistStore(store);
```

When I remove this integration, things seem to work again...so far. I don't know that I give up anything by doing that, so it might be an adequate solution.
