### ISSUE TITLE
What's the right way to combine query subscription and initial subscribeToMore into one HOC?

### ISSUE THREAD

**Issue by cncolder** [apollographql/react-apollo#798]
I need show comments and subscribe new comment append to current query result.
Query and subscription are happen in component initialized.
I don't want manual subscribe it in my component. Because subscription is always needed.

## Steps to Reproduce

Describe how to reproduce this issue.

> code samples are greatly appreciated!

```jsx
const commentsSchema = gql`
  query {
    comments {
      title
      content
    }
  }
`

const commentAddedSchema = gql`
  subscription {
    commentAdded {
      title
      content
    }
  }
`

export const comments = graphql(commentsSchema, {
  name: 'comments'
})
```

At beginning I try to hold `subscribeToMore` results in a global object. But I found if HOC unmount the subscription stop and I cannot detect this.

```jsx
const unsubscribe = {}

export const comments = graphql(commentsSchema, {
  name: 'comments'
  props({ comments, ownProps }) {
    const subscribeCommentAdded = () => comments.subscribeToMore({
      document: commentAddedSchema,
      updateQuery(prev, { subscriptionData }) {
        const { commentAdded } = subscriptionData.data
        return {
          ...prev,
          comments: [...comments, commentAdded]
        })
      }
    })

    unsubscribe.subscribeCommentAdded = unsubscribe.subscribeCommentAdded || subscribeCommentAdded()

    return { comments }
  }
})
```

The I try another way. Split query and subscription into 2 HOC. But `props` function will run 2 times.

```jsx
export const commentAdded = graphql(commentAddedSchema, {
  props({ data, ownProps }) {
    setImmediate(() => ownProps.comments.updateQuery(prev => ({
      ...prev,
      comments: [...comments, data.commentAdded]
    })
  }
})
```

### Buggy Behavior

There is not bug.

### Expected Behavior

How to check if a subscription is running?

```jsx
graphql(schema, {
  props() {
    if (!hasSubscribed) comments.subscribeToMore()
  }
})
```

### Version
- apollo-client@1.4.0
- react-apollo@1.4.2

**Comment by tiwuz** [comment]
Yes, I still have the same doubt. How can we use subscribeToMore in a Higher Order Component?

**Comment by tiwuz** [comment]
@cncolder did you solve it?
