### ISSUE TITLE
react-hot-loader still broken for nested graphql HOC compositions

### ISSUE THREAD

**Issue by brandonbloom** [apollographql/react-apollo#800]
### Buggy Behavior

If you use `compose(graphql(...), graphql(...))(...`, react-hot-loader is broken in the same way as described #174.

Single-stepping shows that the `renderedElement.type === WrappedComponent` test introduced by https://github.com/apollographql/react-apollo/pull/505 returns false.

### Expected Behavior

Nested graphql compositions should not break react-hot-loader's no-remounting behavior.

### Version
- react-apollo@1.4.2

**Comment by jonathanphz** [comment]
I think I have the same issue - followed along #174 and got here. Whenever I make an edit the component remounts. Even editing a simple (no data) component causes a different component to  re fetch data.

## Version

react-apollo@1.4.2

**Comment by jbaxleyiii** [comment]
@brandonbloom or @jonathanphz would you be able to create a sample reproduction so we can get this working correctly?

**Comment by brandonbloom** [comment]
It reproduces with a naive use of react-apollo and the compose function on the hot loader example. However, this issue no longer pains me for reasons explained below.

For others who wind up here the same way I did: I've decided to completely avoid react-apollo for mutations, which is where the need for nesting surfaced frequently. I'm not sure react-apollo makes much sense for mutations vs just using the vanilla js client. For queries, I compose fragments, not components to get a single network round trip.

**Comment by jonathanphz** [comment]
Ok - I will try to create a small demo but maybe it might be easier to just show you the files for hot loader config and react-apollo.

Thanks

**Comment by jonathanphz** [comment]
Ok - been working on a smaller scale reproduction of this. 

My problem is that when I edit the code apollo seems to re-fetch data which makes me lose state. This also happens if I edit different component not using apollo too. 

How do I send you the sample project ? Drop a zip file right here?

**Comment by jonathanphz** [comment]
Any updates on this? - Label says waiting-response but I already responded 19 days ago.

Thanks

**Comment by jbaxleyiii** [comment]
@jonathanphz sorry about that! I missed your response! I'll take a look and thank you for the project!

**Comment by jonathanphz** [comment]
Hey no problem  at all - Thank you for taking the time!

**Comment by jonathanphz** [comment]
Oh issues is stale :( So no solution found @jbaxleyiii ?

Thanks for the hard work you guys are doing btw :)
