### ISSUE TITLE
Fixed Flow types

### ISSUE THREAD

**Issue by steida** [apollographql/react-apollo#802]
Just quick workaround for currently broken Flow types.

- imports of React and Redux moved to namespace
- gql, ApolloClient, createNetworkInterface errors are ignored

https://github.com/este/este/commit/00b86b75bef79095c789683388f1fb1332983c16

**Comment by steida** [comment]
https://github.com/flowtype/flow-typed ftw btw

**Comment by jbaxleyiii** [comment]
@steida I believe this should be fixed in the latest release of both AC and RA. We decided to not use flow-typed because it is much harder to maintain types across different organizations / keep up with the actual flow releases.

**Comment by nthtran** [comment]
@jbaxleyiii This hasn't been fixed at all on latest `react-apollo`. Importing `gql`, `ApolloClient`, `createNetworkInterface`, etc. results in Flow errors because these are not exported from `index.js.flow`.
