### ISSUE TITLE
refetchQueries should have "skip" option

### ISSUE THREAD

**Issue by HeatherZh** [apollographql/react-apollo#806]
## Steps to Reproduce

const ADD_THING = gql`
  mutation addThing($var1: String!, $var2: String) {
   addThing(var1: $var1, var2: $var2) {
     _id
     name
   }
  }
`

const withAddThing = graphql(ADD_THING,  {
  props:({ mutate }) => ({
    addThing: ({ var1, var2 }) => mutate({
      variables: {var1, var2},
      refetchQueries: [{
        query: ANOTHER_QUERY,
        skip: !!var2,
        variables: { _id: var2 },
        fetchPolicy: 'network-only'
      }]
    })
  })
})

In example above,  var2 is an optional variable,  if *only* it is there, we want to do a refetch query.

Currently *skip* option seem to be completely ignored.

### Version
- react-apollo@<1.2.0>

**Comment by helfer** [comment]
Thanks @HeatherZh! I didn't know there even is a `skip` argument on refetchQueries! Where did you find that? It's definitely a feature we could add, if it would be useful.

**Comment by HeatherZh** [comment]
Maybe it is my wishful thinking :) I figured if graphql query wrapper supports "skip" as documented in http://dev.apollodata.com/react/queries.html#graphql-skip, all the other query wrappers would support the same options.   

I do think it could be very useful if one can conditionally control refetchQueries based on variables, results or errors returned from the mutation.   

I am getting around this by doing a conditional client.query after a successful mutation for now.

Thanks for your response!

**Comment by jbaxleyiii** [comment]
@HeatherZh currently `skip` is only managed by the react integration, not part of the core api. This does sound like a great feature though!

**Comment by cmnstmntmn** [comment]
@helfer what's the status of this feature?
