### ISSUE TITLE
Separate mutate from query HOC instead of just having graphql

### ISSUE THREAD

**Issue by clayne11** [apollographql/react-apollo#808]
Instead of having a single `graphql` HOC for both `query` and `mutate` I think we should have separate HOCs. This will have a much more obvious semantic intent as well as allowing us to use better type definitions such as ensuring `data` exists or queries and `mutate` exists for mutations rather than having them be optional.

**Comment by cesarsolorzano** [comment]
related #736

**Comment by jbaxleyiii** [comment]
@clayne11 @cesarsolorzano I totally agree! I think we should keep the `graphql` one but export out `query`, `mutate`, and `subscribe` with more specific types!

**Comment by clayne11** [comment]
This is still valid and important IMO.
