### ISSUE TITLE
Typescript Typings for graphql does not allow custom name

### ISSUE THREAD

**Issue by tomitrescak** [apollographql/react-apollo#809]
Hi, first let me thank you for the excellent support for typescript.
I have on problem though.
When I model my data with custom name, there is no way of capturing this.

For example:

```ts
const withOrganisation = graphql<...>(gql`...`,
  {
    name: 'organisationData',
    ...
    props: ({ organisationData }) => { // no way Jose
      return {
         ...
      }
    }
   });
```

The `data` bit is renamed to `organisationData` and I am not sure how can I capture this so that I can access this in "props".

**Comment by jbaxleyiii** [comment]
Sadly this isn't fixed yet 😥 I'm hoping to get to it soon!

**Comment by jbaxleyiii** [comment]
working on this today!

**Comment by RoberMac** [comment]
any updates?
