### ISSUE TITLE
Unhandled JS Exception: Must contain a query definition.

### ISSUE THREAD

**Issue by ngxiaoyi** [apollographql/react-apollo#812]
## Steps to Reproduce

Just lost the detail context why this happened at my project. 

### Buggy Behavior

Error occurred once launched the app:
![screen shot 2017-07-02 at 9 39 25 pm](https://user-images.githubusercontent.com/3183116/27770328-587a6600-5f6f-11e7-8de8-dbd00b710b6b.png)

### Version
- react-apollo@1.4.2
- react-native@16.0.0-alpha.12

**Comment by ngxiaoyi** [comment]
Seems i broke my project, close this as it has no reference value

**Comment by haris-ramzan** [comment]
I have an same error when i change my "createNetworkInterface" uri from one host to another.

**Comment by lfernando-silva** [comment]
For me, the problem happend when I compose methods with recompose. Just modified the order of method, putting the mutations before queries and everything worked.
