### ISSUE TITLE
Mutation result does not update props

### ISSUE THREAD

**Issue by akomm** [apollographql/react-apollo#815]
## Steps to Reproduce

I can not 100% reproduce the bug, but it happens under the following circumstances (removed detail fields):

```graphql
type Query {
  projects: [Project]!
}
type Project {
  id: Int!
  reviews: [Review]!
}
type Review {
  id: Int!
}
type Mutation {
  createReview(input: CreateReviewInput!): Project
}
input CreateReviewInput {
  projectId: Int!
}
```

Following query is executed/loaded:
```graphql
query Projects {
  projects {
    id
    reviews {
      id
    }
  }
}
```
Later, while the above is still in use in a mounted component:
```graphql
mutation CreateReview($input: CreateReviewInput!) {
  createReview(input: $input) {
    id
    reviews {
      id
    }
  }
}
```
### Buggy Behavior

Correct:
- The mutation is successfully executed on the backend side.
- Expected data with `Project` and its new full `Review` collection is returned
- Apollo store did update/merge the data & query correctly - checked via devtools/apollo plugin chrome.

Buggy:
- The component using the data from the query query get its data removed from prop resulting in no `Project`s rendered - they all disappear. After next update above the graphql HOC in the tree, the data gets passed correctly via props.

My assumption what causes the issue: 
Updates on Items from mutation result, which are already in store (& in use), always worked for me until I made a change. Before, my createReview mutation did return the new Review. Now to circumvent the need of updating the query on the client-side, I changed the mutation result to a Project returned with its new review collection. This is when it stopped working.

Before, works with updateQuery logic:
```graphql
type Mutation {
  createReview(input: CreateReviewInput!): Review
}
```
This does not update (return type):
```graphql
type Mutation {
  createReview(input: CreateReviewInput!): Project
}
```

### Expected Behavior

The component should immediately receive new props from changed query/data.

### Version
- apollo-client@1.4.2 (^1.4.0)
- react-apollo@1.4.2 (^1.4.0)

**Comment by akomm** [comment]
Exact same situation, same component, same data, but removing item from a collection works:

```graphql
  mutation DeleteReview($input: DeleteEntityInput!) {
    deleteReview(input: $input) {
      id
      reviews {
        id
      }
    }
  }
```
Merges correctly and updates props correctly.

**Comment by akomm** [comment]
I try another approach, returning parent node and the directly affected node shallow as trow result fields. This is sure also faster, but I have to define more return types. I still think this is a buggy behavior. Will report whether the alternative approach works.

**Comment by akomm** [comment]
Okay. Even when I do something like this:

```graphql
mutation x(...) {
  xx(...) {
    project {...}
    review {...}
  }
}
```

Basically returning probably affected types by the mutation, I end up having exact same issue.

**Comment by akomm** [comment]
I came closer to the issue. It looks like it happens when I have cached items from a query and a later executed mutation's result is resolved to a cached item (by type and id), but the mutation does not select all fields the query did. Then this results in components get the whole query data passed as undefined until next update, even though the store contains the data.

**Comment by jbaxleyiii** [comment]
@akomm currently the mutation HOC doesn't pass any data down as props, it relies on you using the promise to set local state, or to update queries which are also watched

**Comment by akomm** [comment]
@jbaxleyiii It is not a mutation HOC which does not pass props down the component. It is an query HOC.

I have a query HOC (mounted) and a mutation HOC. When the mutation HOC returns result in described fashion, the query HOC, while mounted, suddenly passes undefined instead of the actual data. Even though when checking the apollo's store state there is data for the given query.

As far as I know the result from mutation HOC is merged into store by resolving objects identity recursively using the specified/default object -> id map function. When the query HOC has an object in store and the mutation HOC returns one, the object from query HOC get updated. This works, except when I return less properties, than the query HOC queried for same object. At least this is what I could reproduce so far.

**Comment by adamdonahue** [comment]
+1

I'm having a similar issue.  I run a mutation, refetch the relevant queries, but my component does not update.

**Comment by akomm** [comment]
If it is confirmed to be the same, as mentioned here: https://github.com/apollographql/react-apollo/issues/874#issuecomment-316962511

This can be closed I think. I'm still not sure, wait for reply there.
