### ISSUE TITLE
best practice: watchQuery per component

### ISSUE THREAD

**Issue by hyusetiawan** [apollographql/react-apollo#827]
This is not an issue/bug. I am trying to figure out the best way to do this.

I have set up my store to use mobx and I pull the data using apollo-client. I put in the effort to do a diffing + patching and it has been work wonderfully, where I would get the data using watchQuery, diff it with what I have, and then patch the store. Piggy backing on mobx observer system, only the components referencing the data would get re-rendered.

My issue is, it seems that when I do watchQuery, I need to manually pass the variables, if not, I will get back undefined data. What I mean is this:

```
@graphql(Query, { options: () => ({variables: {bla: 123}})})
class Item {
}

// what if we have multiple Item components mounted and with different bla values?
client.watchQuery(Query, {pass variables again}).subscribe(() => {
  // do the diffing/patching here to mobx store
})

module.exports = Component
```
another way that I am thinking of is to do the diffing during componentWillReceiveProps like so:

```
@graphql(Query, { options: () => ({variables: {bla: 123}})})
class Item {
   componentWillReceiveProps(props, nextProps) {
       // do diffing and patching with nextProps.data.mydata
   }
}
module.exports = Component
```
I wonder if the community has a better suggestion for what I am trying to do?

**Comment by michalpleszczynski** [comment]
@hyusetiawan with what solution did you end up? I have the same problem and can't decide between doing one of the above or going with a package like mobx-apollo.

**Comment by hyusetiawan** [comment]
@michalpleszczynski I gave up on having mobx as the centralized store, I ended up using mobx for ui state specific for ex: (which tab is open)
