### ISSUE TITLE
1.4.3 introduced a config.skip bug

### ISSUE THREAD

**Issue by dnalborczyk** [apollographql/react-apollo#830]
if not intentional, v1.4.3 introduced a bug where **config.skip** is not being called first anymore, but some time later, e.g. after **config.options**, which makes skip in this case pretty much useless.

**Version**
- apollo-client@1.7.0
- react-apollo@1.4.3

**How to reproduce the issue:**
```
  graphql( SOME_QUERY, {
    skip: ( props ) => {
      console.log( 'skip' );
      return true;
    },
    options: ( props ) => {
      console.log( 'options' );
    }
```

**Intended outcome:**
```
skip
```

**Actual outcome:**
```
options
skip
```

**Comment by enjoitheburger** [comment]
Also seeing this issue in our project.

**Comment by jbaxleyiii** [comment]
This may be related to the new option to allow for passing a client in the options. I'll take a look! Thanks for the report!

**Comment by SterlingSmith** [comment]
Reporting that my project is seeing this error as well. Hope it is an easy fix!

**Comment by jbaxleyiii** [comment]
@SterlingSmith yep it will be a quick one, I should have it out today with a fix

**Comment by jbaxleyiii** [comment]
This will be out in a fix today
