### ISSUE TITLE
Type error is shown after running "react-native run-android"

### ISSUE THREAD

**Issue by OscarYuen** [apollographql/react-apollo#836]
After upgrade to 1.4.3,  I got the following error on my android.

`Type error
hoistNonReactStatics
    index.android.bundle?platform=android&dev=false&hot=false&minify=false:61727:90
hoistNonReactStatics
    index.android.bundle?platform=android&dev=false&hot=false&minify=false:61714:37
wrapWithApolloComponent
    index.android.bundle?platform=android&dev=false&hot=false&minify=false:54606:40
<unknown>
    index.android.bundle?platform=android&dev=false&hot=false&minify=false:46892:15
<unknown>
    index.android.bundle?platform=android&dev=false&hot=false&minify=false:63744:4
loadModuleImplementation
    index.android.bundle?platform=android&dev=false&hot=false&minify=false:109:12
guardedLoadModule
    index.android.bundle?platform=android&dev=false&hot=false&minify=false:70:36
_require
    index.android.bundle?platform=android&dev=false&hot=false&minify=false:54:77
<unknown>
    index.android.bundle?platform=android&dev=false&hot=false&minify=false:62800:27
loadModuleImplementation
    index.android.bundle?platform=android&dev=false&hot=false&minify=false:109:12
guardedLoadModule
    index.android.bundle?platform=android&dev=false&hot=false&minify=false:70:36
_require
    index.android.bundle?platform=android&dev=false&hot=false&minify=false:54:77
<unknown>
    index.android.bundle?platform=android&dev=false&hot=false&minify=false:46228:22
loadModuleImplementation
    index.android.bundle?platform=android&dev=false&hot=false&minify=false:109:12
guardedLoadModule
    index.android.bundle?platform=android&dev=false&hot=false&minify=false:70:36
_require
    index.android.bundle?platform=android&dev=false&hot=false&minify=false:54:77
<unknown>
    index.android.bundle?platform=android&dev=false&hot=false&minify=false:1236:19
loadModuleImplementation
    index.android.bundle?platform=android&dev=false&hot=false&minify=false:109:12
guardedLoadModule
    index.android.bundle?platform=android&dev=false&hot=false&minify=false:63:45
_require
    index.android.bundle?platform=android&dev=false&hot=false&minify=false:54:77
global code
    index.android.bundle?platform=android&dev=false&hot=false&minify=false:170906:9`

Even I fallback my react-apollo version, I still got this error.

**Version**
- react-apollo@1.4.3

**Comment by OscarYuen** [comment]
Finally I can fallback my apollo-react by manually running npm uninstall @type/enzyme @type/react and install old version react-apollo to fallback those dev dependency

**Comment by vspedr** [comment]
+1, same problem here

**Comment by jbaxleyiii** [comment]
It is a duplicate, and it will be fixed today!
