### ISSUE TITLE
React Apollo fails with http2 turned on

### ISSUE THREAD

**Issue by chanan** [apollographql/react-apollo#842]
Our server is behind a netscaler. All was good for a while.
Yesterday our ops team turned on http2 on the netscaler. Apollo stopped working. The first query works but the second fails with: net::ERR_SPDY_PROTOCOL_ERROR - when I change the url I hit to bypass the netscaler and hit the server directly, all is good again.

**Intended outcome:**
Not get an error with http2

**Actual outcome:**
Error when using http2

**How to reproduce the issue:**
Setup up an http proxy in front of the graphql server

**Version**
- react-apollo@1.2.0
- graphql@0.10.1
- graphql-server-express@0.7.2

**Comment by chanan** [comment]
I updated to the latest versions of apollo react and apollo graphql - didnt fix the issue.

**Comment by jbaxleyiii** [comment]
@chanan I'm not sure this is an Apollo issue? Apollo just uses `fetch` to make the requests under the hood. It sounds like a potential issue with the proxy?
