### ISSUE TITLE
React navigation fails stacking query reducers

### ISSUE THREAD

**Issue by nenti** [apollographql/react-apollo#848]
When stacking multiple views in react-navigation that each is connected to the apollo store the reducer of one query is also hit by the results of the other query.

```
graphql(orders, {
  options: props => ({
    reducer: (previousResult, action, variables) => {
  })
})
```

Reducer is also called for results of stacked component results.

```
graphql(store, {
    options: {
      variables: { geo_hash: '' },
    },
  })
```

"react-apollo": "^1.2.0",

**Comment by jbaxleyiii** [comment]
@nenti I'm not sure I follow? Could you setup a reproduction for me to take a look at?
