### ISSUE TITLE
If I name the queries I can't access the `data.loading` prop

### ISSUE THREAD

**Issue by johhansantana** [apollographql/react-apollo#857]
Hello, I'm new to graphql and am having a bit of trouble.

I have the following code

```javascript
const login = gql`
    mutation($email: String!, $password: String!) {
        signinUser(email: {
            email: $email,
            password: $password
        }) {
            token
        }
    }
`;
const currentUser = gql`
    query {
        user {
            id
            email
        }
    }
`;
const videos = gql`
  query {
      allVideos {
          id
          videoId
          videoPreview
      }
  }
`;
function mapStateToProps(state: Object): Object {
  return {
    form: state.form
  };
}

const withC = withCookies(Home);

export default compose(
  graphql(login, { name: 'login' }),
  graphql(currentUser, { name: 'currentUser' }),
  graphql(videos, { name: 'videos' }),
  connect(mapStateToProps)
)(withC);
```

First issue:
I normally do:
`const { data: {loading} } = this.props;`
to see if the data is still being fetched.

This is not the case when I use the previous code as I don't see the `data` prop being passed:
<img width="680" alt="screen shot 2017-07-16 at 5 12 40 pm" src="https://user-images.githubusercontent.com/9933887/28251395-48b0ae56-6a4a-11e7-880f-58027bad7ac9.png">

Second issue:
As I can see, the query `currentUser` and `videos` get called automatically when component mounts, is there a way for me to call these queries manually instead since they convert into the returned `Object` instead of a `Function` like the `login` query/mutation

Thanks!

**Edit**

I see that they individually get the `loading` prop, so that's good.

I guess the only question I have is how to execute manually the regular non-mutation queries

**Comment by jbaxleyiii** [comment]
@johhansantana the `graphql` wrapper will fetch the queries automatically when they mount so you shouldn't have to execute them manually. If you wan't to, you can use `refetch`, or use the `withApollo` helper to manually inject Apollo Client into your component.

Does this make sense
