### ISSUE TITLE
react-dom being installed within react-apollo/node_modules (why?)

### ISSUE THREAD

**Issue by philcockfield** [apollographql/react-apollo#860]
**Intended outcome:**
Reference `react-apollo` without it installing it's own version of `react-dom` within it's own `node_modules` folder.

**Actual outcome:**
When referencing `react-apollo` within a module that is also referencing `react / react-dom` the `react-apollo` is installing it's own version of `react-dom` within it's own `node_modules` folder.

This causes an error to occur when parsing a file that references it:

    /code/my-module/node_modules/react-apollo/node_modules/react-dom/cjs/react-dom-server.development.js:3534
      ReactCurrentOwner: ReactInternals.ReactCurrentOwner
                                       ^

    TypeError: Cannot read property 'ReactCurrentOwner' of undefined

![image](https://user-images.githubusercontent.com/185555/28298344-d56b6930-6bc6-11e7-84fa-0fb742ad07d5.png)

This appears to be because `react-dom` is being referenced as an `optionalDependencies`:

      package.json

      "optionalDependencies": {
        "react-dom": "0.14.x || 15.* || ^15.0.0 || ^16.0.0-alpha"
      },

Why is that?

**How to reproduce the issue:**

Add `react-apollo` to a module.

**Version**
- react-apollo@1.4.3

**Comment by philcockfield** [comment]
I've created a sample repo to show the problem: https://github.com/philcockfield/sample-react-apollo-problem

**Comment by WickyNilliams** [comment]
This has been fixed in v1.4.4 btw

**Comment by jbaxleyiii** [comment]
@WickyNilliams thanks for responding to this! @philcockfield this was an issue with previous versions, it is fixed in 1.4.4 👍
