### ISSUE TITLE
Export types in version 1.4.4

### ISSUE THREAD

**Issue by pawsong** [apollographql/react-apollo#864]
**Version**
- apollo-client@latest
- react-apollo@1.4.4

I guess `import` in this line (https://github.com/apollographql/react-apollo/blob/master/src/browser.ts#L3) should be fixed to `export` so that we can consume typings in the following way:

```typescript
import { QueryProps } from 'react-apollo';
```

**Comment by vlutton** [comment]
yes, I am having same issue, updated and found that `DefaultChildProps` had been renamed to `ChildProps` but is no longer importable

**Comment by jbaxleyiii** [comment]
@pawsong dangit! I'll fix it right away

**Comment by jbaxleyiii** [comment]
Thanks for the report! Its being fixed right now!

This week I'm going to add a sample project with flow and typescript which will link this project so we can ensure application integrations won't break going forward

**Comment by jbaxleyiii** [comment]
This is out in 1.4.5! Sorry again for any issues!

**Comment by jbaxleyiii** [comment]
@pawsong @vlutton would you have any interest in taking a look at our docs for static typing https://github.com/apollographql/react-docs/pull/258

**Comment by jatsrt** [comment]
@jbaxleyiii Just added #867, missing built code, just has TS src.
