### ISSUE TITLE
Release 1.4.5 Broken

### ISSUE THREAD

**Issue by jatsrt** [apollographql/react-apollo#867]
Missing build files, just includes source.

**Comment by jatsrt** [comment]
To be clear the released NPM package is missing the generated JS code.  It only contains the source TS code.

**Comment by benwiley4000** [comment]
Confirmed - `lib` directory is missing.

**Comment by VNadygin** [comment]
+1

**Comment by jbaxleyiii** [comment]
thats bizarre! The build process hasn't changed. I'll take a look now!

**Comment by jbaxleyiii** [comment]
Sorry about this everyone! I'm not sure what happened! We have an automatic release process setup with Travis, so I'll have to debug that build. Regardless, 1.4.6 is out and should fix those issues

**Comment by benwiley4000** [comment]
The fix works!

Thanks for the fast response. Helped us avoid having to lock down our dependency version across our test deployments. 🙂
