### ISSUE TITLE
ROOT_QUERY gets removed from the store when accessing the same component twice

### ISSUE THREAD

**Issue by habovh** [apollographql/react-apollo#869]
I'm currently working on a chat app on iOS using React-Native and React-Apollo.

When on a discussion, the messages load properly using the `graphql` decorator.

Then I can post a message using a mutation, which uses `update` to add the newly created message to the discussion query (non-optimistic ui).

Works fine, no issue whatsoever, the message gets properly added to the list, and the list is rendered properly.

Now if I navigate back to the discussions list, and again to the discussion (be it the same discussion or another one), the `update` of the new message mutation would fail with the following:

> Can't find field discussion({ "id":1429}) on object (ROOT_QUERY) undefined.

![simulator screen shot 19 juil 2017 a 18 49 21](https://user-images.githubusercontent.com/4186230/28379283-6fc15c3c-6cb3-11e7-82d0-6c6fdc6235a9.png)

If I understand right, the query that originally gets called when the component mounts, gets cached in the store under `ROOT_QUERY` query key.

In the first case (before navigation), I can `console.log` the content of the store, and I see there is a `ROOT_QUERY` key having the proper original query:
<img width="392" alt="capture d ecran 2017-07-19 a 18 52 21" src="https://user-images.githubusercontent.com/4186230/28379313-85cd1386-6cb3-11e7-9693-ef1fd252274a.png">

However, when navigating back and forth, the `ROOT_QUERY` key simply disappears:
<img width="351" alt="capture d ecran 2017-07-19 a 18 53 58" src="https://user-images.githubusercontent.com/4186230/28379370-ada8cd00-6cb3-11e7-8160-677ef081afaa.png">

Here's the content of my `update` function, used for my mutation:

```javascript
    (store, { data: { writeMessage } }) => {
          console.log('Store :', store) // < This is where I got the screenshots above
          // Reading the data in order to put back the list with the new message
          const data = store.readQuery({
            query: query.getMessages, // The same as the one used on component mount
            variables: ownProps.originalVariables, // Using this to avoid having to repeat every query param one by one
          })

         // Adding the message received from the mutation
          data.discussion.messages.edges.unshift(writeMessage.discussion.messages.edges[0])

         // Updating the initial query with the updated data
          store.writeQuery({
            query: query.getMessages,
            variables: ownProps.originalVariables,
            data,
          })
```

**Intended outcome:**

Store should contain `ROOT_QUERY` when navigating to an apollo-react decorated container.

**Actual outcome:**

Store only contains `ROOT_QUERY` on full reload (CMD + R in `react-native`, on iOS project, equivalent to a full page reload on the web)

**Version**
- apollo-client@1.8.0
- react-apollo@1.4.3

**Comment by jbaxleyiii** [comment]
@habovh hmm that is really odd! I'll see if I can figure out why that might be happening? Would you be able to create a small reproduction of this in a repo / code sandbox so I can better debug?

**Comment by habovh** [comment]
It might be really complicated to create a smaller app reproducing this setup, you might as well get access to the repository if you wish. Or we could share screens if you don't want to bother running Xcode to run the app.

**Comment by mrkidsan** [comment]
Currently having a similar issue as above.

On page load my ROOT_QUERY is defined and I am able to update as normal.

However if I navigate ( without a page reload ) to a location where that component unmounts and then back to a location where the component does mount, then ROOT_QUERY is undefined.

If I do a full refresh of the page ROOT_QUERY will be defined again.

**Version**
-  react-apollo@1.4.3
- react-router-dom@4.1.1

**Comment by mrkidsan** [comment]
**Update**: For me this errror was caused because ApolloProvider was wrapped by BrowserRouter from react-router-dom. Wrapping BrowserRouter with ApolloProvider seemed to solve the issue in my case.
