### ISSUE TITLE
Normalization doesn't work consistently - components don't update

### ISSUE THREAD

**Issue by adamdonahue** [apollographql/react-apollo#874]
This document explains a very simple model that fits nicely to React:

http://dev.apollodata.com/core/how-it-works.html

But in practice this is not working at all.

Assume two queries, both using a shared fragment:

```
   query DocumentQueryA {
      docQueryA {
        ... DocumentFragment
      }
   }
   ${DocumentFragment}
```

and

```
   query DocumentQueryB(id: ID!) {
      docQueryB(id: $id) {
        ... DocumentFragment
      }
   }
   ${DocumentFragment}
```

One component uses DocumentQueryA, and accepts a list of documents as its property.

Another component uses DocumentQueryB, and accepts a single document as its property.

Finally, there is a mutation that changes a field on a document (indirectly), but doesn't return the new document data.

So, based on the URL I posted above and the way React works, I would expect the following to result in _both_ components getting the updated document object (given that both have DocumentType:documentId):

```
mutate({
    variables: {
        id: documentId
    },
   refetchQueries: [
       { query: DocumentQueryB, variables: { id: documentId } }
   ]
})
```

But in fact, I have to refetch _both_ queries.  (Note that the list of items is not shrinking or growing; just one field in a single document present in both lists is changing.)

Why do we need to refetch both queries?

**Comment by akomm** [comment]
Sounds like my issue. Can you try the following: Return the updated document 1. exact with the same fields as you queries for and then 2. with fewer fields.

It sometimes even lead to props passed from graphql being undefined, even though the query IS in the store.

**Comment by adamdonahue** [comment]
Thanks for responding.  (Sorry I'm just getting back to you.) . The explanation in the referred-to ticket makes sense, but there are certainly some assumptions there that are unintuitive.

**Comment by akomm** [comment]
@jbaxleyiii I think the issue is still there. Although there are other tickets with the same issue. I think @adamdonahue just gave it up on the problem. I assume it taking into account other posts from him related to this.
