### ISSUE TITLE
Old query data loaded, even though the redux store was cleared

### ISSUE THREAD

**Issue by akomm** [apollographql/react-apollo#890]
Reproduce:

- Make sure you run apollo state in your own redux store
- Execute a query via graphql HOC mounting successfully & ensure it is in store
- Clear the store & ensure it is cleared
- Execute the query again ~provoking any error~ - just execute it, no error needed.

Expected result:

No data from the query passed through the graphql HOC

Actual result:

Data, which was successfully loaded before store clear..

I'm trying to make a test reproducing it. My current assumption is that the observable is leaking data.

**update 1**
Checked the code. It looks like the apollo client has state outside the actual redux state, which is not cleared/reset, when you reset the redux state. Its coming from active observables. And using the ApolloClient.resetStore API is, as documented, not really resetting the data, but refetching queries. 

So when you have authorized APIs you can not return errors, you have to return blank results to make this work, or else whenever you logout a user and clear using resetStore, you get 100 errors everywhere. Else: when you clear via redux HOR or dispatching APOLLO_STORE_RESET, data is leaked through observables via last result.

This is totally flawed :(

**Version**
- apollo-client@^1.4.0
- react-apollo@^1.4.0

**Comment by stantoncbradley** [comment]
Related to #807?

**Comment by akomm** [comment]
Yes, the "load old data on error" part is related to #807, additional to the issue not being able to clear data properly.

**Comment by stantoncbradley** [comment]
yes this is a big problem for us.  we had to roll back to `1.1.3`

**Comment by du5rte** [comment]
Experiencing the same here also had to roll back to `~1.1.0`

**Comment by akomm** [comment]
@jbaxleyiii still relevant

**Comment by dozoisch** [comment]
Having this issue as well

**Comment by Ardhimas** [comment]
Is there anyone actively working on a PR for this issue, or at least know what to do to solve it? This is a pretty severe bug for any apps that involve authentication and user data.

**Comment by dozoisch** [comment]
(this should probably not be closed by staling)

**Comment by akomm** [comment]
Maybe the bot should ignore bug-tagged issues? :-7

**Comment by GuilhermeMedeiros** [comment]
Same here. And it's a big issue for us.

**Comment by GuilhermeMedeiros** [comment]
https://github.com/apollographql/react-apollo/issues/1281
https://github.com/apollographql/react-apollo/issues/976
https://github.com/apollographql/apollo-client/issues/1186
https://github.com/apollographql/apollo-client/issues/1387

At least 4 issues related to this.

**Comment by johnunclesam** [comment]
Same here.

**Comment by stantoncbradley** [comment]
graphql so great, leaking sensitive data b/c of 6 month old bugs still not addressed, not so much

**Comment by rosskevin** [comment]
Redux stores are no longer in use - closing - housekeeping.
