### ISSUE TITLE
react-native "Can't find variable: self" pointing to apollo-fetch and fetch-npm-browserfiy

### ISSUE THREAD

**Issue by acomito** [apollographql/react-apollo#891]
I'm getting the red screen of death with a new expo project using these packages. It seems to be pointing to something to do with fetch and apollo:

  "dependencies": {
    "antd-mobile": "^1.5.0",
    "apollo-client": "^1.9.0-1",
    "expo": "^19.0.0",
    "graphql-tag": "^2.4.2",
    "lodash": "^4.17.4",
    "meteor-apollo-accounts": "^2.0.1",
    "moment": "^2.18.1",
    "react": "16.0.0-alpha.12",
    "react-apollo": "^1.4.8",
    "react-native": "https://github.com/expo/react-native/archive/sdk-19.0.0.tar.gz",
    "react-native-aws3": "0.0.8",
    "react-native-elements": "^0.15.0",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.5",
    "redux": "^3.7.2",
    "redux-devtools-extension": "^2.13.2",
    "redux-persist": "^4.8.2",
    "redux-thunk": "^2.2.0",
    "sentry-expo": "^1.6.0"
  },
  "devDependencies": {
    "babel-plugin-import": "^1.2.1"
  }}

**Comment by acomito** [comment]
I can confirm that when I downgraded to 1.1.1 that the error went away... not sure where the break happened between 1.1 and 1.9

**Comment by mkozhukharenko** [comment]
Same issue with react native

"1.9.0-1" version throws en error. I downgraded to "1.9.0-0" and it works

**Comment by gardner** [comment]
I get this too. They already have it logged over at https://github.com/apollographql/apollo-client/issues/1956
