### ISSUE TITLE
trying to import `react-dom/server ` when running jest tests

### ISSUE THREAD

**Issue by peterp** [apollographql/react-apollo#892]
It seems that `react-apollo` is trying to import `react-dom/server` whilst trying to run my jest tests.

```terminal
 FAIL  __tests__/index.android-tests.js
  ● Test suite failed to run

    Cannot find module 'react-dom/server' from 'react-apollo.umd.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at node_modules/react-apollo/react-apollo.umd.js:2:191
      at Object.<anonymous> (node_modules/react-apollo/react-apollo.umd.js:5:2)
```

**Comment by jbaxleyiii** [comment]
@peterp is this for a react-native app (I'm assuming because of the `index.android`). What env do you have set? Currently the entry point imports the code for SSR, however we have a browser entry point. Can you set the environment for your tests to be `browser`? We used to ship react-dom as a dep but that caused other troubles with both react-native and react 16.

I'd love to figure out how to make this better!

**Comment by peterp** [comment]
Yup! It's react native, I'm using the standard preset: https://github.com/facebook/react-native/blob/master/jest-preset.json.

I've changed testEnviroment to "jsdom" and "browser" as suggested here: https://facebook.github.io/jest/docs/configuration.html#testenvironment-string, but the problem persists.

I guess I could install `react-dom` as a devDependency.

**Comment by lettertwo** [comment]
FWIW, I've managed to work around this problem by aliasing `react-apollo` using the [babel module resolver plugin](https://www.npmjs.com/package/babel-plugin-module-resolver):

in `.babel.rc`:
```json
{
  "presets": ["react-native"],
  "plugins": [
    ["module-resolver", {
      "alias": {
        "react-apollo": "react-apollo/react-apollo.browser.umd.js"
      }
    }]
  ]
}
```

**Comment by Philip-Nunoo** [comment]
Having the same issue here.

**Comment by mvaivre** [comment]
Same here. @lettertwo workaround didn't work for me.... Would be nice to find another solution than adding react-dom as a devDependency!

**Comment by enesTufekci** [comment]
>
```
"plugins": [
    ["module-resolver", {
        "alias": {
        "react-apollo": "./node_modules/react-apollo/react-apollo.browser.umd.js"
        }
    }]
  ]
```

that worked for me

**Comment by DavidKongDesheng** [comment]
same issue here

**Comment by 7ynk3r** [comment]
if you try to use `import { MockedProvider } from 'react-apollo/test-utils';` it won't work.

**Comment by 7ynk3r** [comment]
using
```
"plugins": [
    ["module-resolver", {
        "alias": {
        "react-apollo": "./node_modules/react-apollo/react-apollo.browser.umd.js"
        }
    }]
  ]
```
the normal usage of the react-native application.

**Comment by larryranches** [comment]
@7ynk3r I'm also having this issue with react-native. Can you provide this best option?

**Comment by 7ynk3r** [comment]
i was able to make it work with 
```
  "jest": {
    "browser": true,
    [...]
  }
```
you'll have to install `react/dom` as a `devDependency` and `https://github.com/pwnall/node-xhr2` to have support for `fetch`.

still i've opted to export all components without apollo
```
export Component; // <--
export default graphql(QUERY, Component);
```
and then unit test it, passing a mock. as long as you don't have a lot of transformations in `variables` or `props` you should be fine.

**Comment by larryranches** [comment]
@7ynk3r Thank you so much! I think I kind of got this to work with your info. I'm going to play with this a little bit more and let you know if I hit a roadblock or questions or even some of your best practices with this approach if you don't mind.

**Comment by richardgirges** [comment]
This is still a relevant issue with some pretty ugly workarounds. Please don't close this stalebot.

**Comment by geirman** [comment]
I'm also having this issue. I tried the plugins work around above, but that slows down the tests and also doesn't resolve the issue. It just threw a different error related to `./node_modules/react-apollo/react-apollo.browser.umd.js`

**Comment by jaredly** [comment]
I'm in react-native and had this problem too, and I was able to do 
```js
jest.mock('react-dom/server', () => {}, {virtual: true})
```
 and it worked just fine!

**Comment by mxmzb** [comment]
Still having this issue on an Expo (RN) app. @jaredly may I ask where that code is supposed to go? :)

**Comment by bryantAXS** [comment]
Any updates on this one? Are people still having the issue?

**Comment by KrifaYounes** [comment]
I have this error when I try to import react-apollo on a lambda in aws
Are people still having this issue?
```
Unable to import module 'lambda': Error
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at /var/task/node_modules/react-apollo/react-apollo.umd.js:2:152
at Object.<anonymous> (/var/task/node_modules/react-apollo/react-apollo.umd.js:5:2)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
```

**Comment by hwillson** [comment]
This issue has been resolved in current day versions of `react-apollo`. Thanks!
