### ISSUE TITLE
Flow types force query options to be a function, not an object

### ISSUE THREAD

**Issue by Strayer** [apollographql/react-apollo#899]
**Intended outcome:**
No flow errors when using an object as query options.

```
const withQuery: OperationComponent<Response> = graphql(query, {
    options: { fetchPolicy: "cache-and-network" },
    props: ({ data }) => ({ ...data }),
});
```

**Actual outcome:**
Flow complains that the options value is not an OptionDescription type, which describes a function.

```
node_modules/react-apollo/react-apollo.umd.js.flow:96
 96:   options?: OptionDescription<TProps>,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^ function type. Callable signature not found in
146:     { options: { fetchPolicy: "cache-and-network" } }
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object literal. See: src/....js:146
```

Using a function as query options doesn't cause Flow errors:
```
const withQuery: OperationComponent<Response> = graphql(contractsQuery, {
    options: (props) => ({ fetchPolicy: "cache-and-network" }),
    props: ({ data }) => ({ ...data }),
});
```

The problem is that OptionDescription is defined as:
`type OptionDescription<P> = (props: P) => QueryOpts | MutationOpts;`.
I guess the correct definition would be:
`type OptionDescription<P> = (props: P) => QueryOpts | QueryOpts | MutationOpts;`

See:
https://github.com/apollographql/react-apollo/blob/master/src/index.js.flow#L119
->
https://github.com/apollographql/react-apollo/blob/master/src/index.js.flow#L96
->
https://github.com/apollographql/react-apollo/blob/master/src/index.js.flow#L93

**Version**
- apollo-client@1.9.0-1
- react-apollo@1.4.8

**Comment by Strayer** [comment]
This seems to be valid still for react-apollo@1.4.12 – see https://github.com/Strayer/ApolloFlowIssues/tree/query-options-as-object to reproduce this error.

**Comment by wvteijlingen** [comment]
FWIW, the `skip` option does allow this because it is defined as: ` boolean | ((props: any) => boolean)`. I would assume that `options` would be defined as: 

```
(QueryOpts | MutationOpts) | (props: TProps) => QueryOpts | MutationOpts;
```

I'm not sure if the `OptionDescription` is used elsewhere, but it seems redundant to use a new type of this when it's just used in one place.

**Comment by Strayer** [comment]
@jbaxleyiii ping as requested by stale bot.

This is still causing errors in our project.

apollo-client@1.9.2
react-apollo@1.4.15

**Comment by msmfsd** [comment]
Update flow to `^0.57.3` worked for me
