### ISSUE TITLE
Skip does not prevent options from running

### ISSUE THREAD

**Issue by jbreckel** [apollographql/react-apollo#903]
Using `config.skip` on the `graphql`-hoc does not prevent `config.options` to be called.

Code:
```javascript
graphql(SomeQuery, {
    skip: ({ selected }: PropsT) => !(selected && selected.name),
    options: ({ id, selected }: PropsT) => ({
        variables: { id, name: selected.name },
    }),
})
```

**Intended outcome:**
The hoc should not execute `config.options` if `selected` is falsy.

**Actual outcome:**
Throws error in options if `selected` is falsy as it executes `config.options` and cannot read `selected.name`.
```
Uncaught TypeError: Cannot read property 'name' of null
    at options
```

**Version**
- apollo-client@1.8.1
- react-apollo@1.4.8

**Comment by HadiAkmal** [comment]
What happen if you hardcoded skip to:

`skip: true,`

**Comment by jbreckel** [comment]
does not change the behaviour

**Comment by valpet** [comment]
I have the same problem. In my code my query should not run until the user is logged in and a profile object has been set. 

```

const currentUserQueryConfig = {
  skip: props => {
    console.log('skip', props.profile)
    return !props.profile
  },
  options: props => {
    console.log('options', props.profile)
    return {
      variables: {
        id: props.profile.clientID
      }
    }
  }
}
```
**Output in console**

**skip** null
App.js:227 **skip** null
App.js:227 **skip** null
client?e36c:64 [WDS] Hot Module Replacement enabled.
redux-logger.js:1  action APOLLO_MUTATION_INIT @ 14:49:25.617
redux-logger.js:1  prev state {auth: {…}, apollo: {…}}
redux-logger.js:1  action     {type: "APOLLO_MUTATION_INIT", mutationString: "mutation upsertUser($id: String!, $name: String!, …picture: $picture) {↵    id↵    __typename↵  }↵}↵", mutation: {…}, variables: {…}, operationName: "upsertUser", …}
redux-logger.js:1  next state {auth: {…}, apollo: {…}}
App.js:231 **options** {email: "aa.bb@gmail.com", email_verified: true, name: "aa bb", given_name: "aa", family_name: "bb", …}
App.js:227 **skip** {email: "aa.bb@gmail.com", email_verified: true, name: "aa bb", given_name: "aa", family_name: "bb", …}
App.js:231 **options** {email: "aa.bb@gmail.com", email_verified: true, name: "aa bb", given_name: "aa", family_name: "bb", …}
App.js:231 **options** {email: "aa.bb@gmail.com", email_verified: true, name: "aa bb", given_name: "aa", family_name: "bb", …}
App.js:231 **options** null

**Version**

apollo-client@1.9.1
react-apollo@1.4.14

**Comment by Morphexe** [comment]
Sam situation as the above.
skip :true,
skip : (props) =>  true
any of those do no prevent the options from being called.

**Comment by chiss2906** [comment]
The reason is `willReceiveProps`: https://github.com/apollographql/react-apollo/blob/master/src/graphql.tsx#L171-L172

Shouldn't this also test skip first?

**Comment by rhberro** [comment]
I was facing the same issue, so I've opened a pull request to solve the problem. Check it out [here](https://github.com/apollographql/react-apollo/pull/1181) please.
