### ISSUE TITLE
`withApollo` doesn't support operation options when using with `compose`

### ISSUE THREAD

**Issue by koenpunt** [apollographql/react-apollo#907]
**Intended outcome:**
Be able to supply operation options when using `withApollo` with `compose`

**Actual outcome:**
Not able to pass options since the function isn't a factory.

**How to reproduce the issue:**

Take the following example:
```js
const MyComponent = () => (
  <Button title={this.props.title} onPress={() => this.props.client.query(...)} />
);

const WrappedMyComponent = compose(
  connect(state => ({ title: state.title }), null, null, { withRef: true }),
  withApollo,
)(MyComponent);
```

If I would like to pass the `withRef` option, this is not possible.

For now I worked around this by applying `withApollo` outside of `compose`:

```js
const WrappedMyComponent = compose(
  connect(state => ({ title: state.title }), null, null, { withRef: true }),
)(withApollo(MyComponent, { withRef: true }));
```

But ultimately it would be nice if `withApollo` differentiates between a component and a plain options object, and then for the latter function as a factory, so that one can also do this:

```js
const WrappedMyComponent = compose(
  connect(state => ({ title: state.title }), null, null, { withRef: true }),
  withApollo({ withRef: true }),
)(MyComponent);
```

**Version**
- apollo-client@1.3.0
- react-apollo@1.2.0

**Comment by koenpunt** [comment]
Any word on this? I could submit a PR, but I first want to know if the variable API (first argument can be an object or a function) is desired, or that a different API should be defined.

**Comment by sneerin** [comment]
@koenpunt please do

**Comment by mattbrunetti** [comment]
Yes, the proposed API would be much better.

**Comment by koenpunt** [comment]
Ping ✨

**Comment by Wishmaker888** [comment]
still waiting... :)

**Comment by koenpunt** [comment]
@jbaxleyiii the bot suggest me to ping you about this issue :)

**Comment by jnreynoso** [comment]
+1

**Comment by habovh** [comment]
This is **NOT** an ideal solution, but a good workaround.

> To be able to pass `{ withRef: true }` to `connect()` would be ideal.

You can simply use an anonymous function like so:

```javascript
export default connect(
  (comp) => withApollo(comp, { withRef: true }),
  graphql(query, { withRef: true }),
)(MyComponent)
```

**BUT** this would require you to call `getWrappedComponent()` twice (or as many times as you are using `graphql` or `withApollo` HOC) in order to get back to the `MyComponent` instance:

```javascript
const myComponentInstance = this.myDecoratedComponent.getWrappedComponent().getWrappedComponent()
```

**Comment by hwillson** [comment]
If this is still a concern, and anyone is interested in working on a PR, we'll definitely review it. Thanks!
