### ISSUE TITLE
Flow-types are out of sync

### ISSUE THREAD

**Issue by alfredringstad** [apollographql/react-apollo#909]
Flow-types are missing for the following exports:
- [x] withApollo
- [x] compose
- [x] gql
- [x] Everything that is imported from the apollo-client library and exported in index.js

Also, these methods are exported in the flow-types, but are not available in TS/JS:
- [ ] walkTree
- [ ] parser
- [ ] cleanupApolloState

**Intended outcome:**
Trying to import `withApollo` from `react-apollo`.

```import { withApollo } from 'react-apollo';```

**Actual outcome:**
```
Error: myFile.js:3
  3: import { withApollo } from 'react-apollo';
              ^^^^^^^^^^ Named import from module `react-apollo`. This module has no named export called `withApollo`.
```

**How to reproduce the issue:**
See code above.

**Version**
- apollo-client@1.9.0-1
- react-apollo@1.4.8

**Comment by jbaxleyiii** [comment]
@alfredringstad thank you for bringing this to my attention! I'll get it fixed asap!

**Comment by dozoisch** [comment]
Same thing with `gql`

`import { gql } from ' react-apollo';`
> This module has no named export called `gql`
