### ISSUE TITLE
FlowTypes is missing NamedProps

### ISSUE THREAD

**Issue by dozoisch** [apollographql/react-apollo#931]
**Intended outcome:**

```
import type { NamedProps } from 'react-apollo';
// Imports properly
```

**Actual outcome:**

> This module has no named export called `NamedProps`

**How to reproduce the issue:**

See intended

**Version**
- apollo-client@1.8.1
- react-apollo@1.4.10
---

Follow up of https://github.com/apollographql/react-apollo/issues/909. I see NamedProps in the `types.d.ts` but not in the react-apollo.umd.js.flow!

**Comment by jbaxleyiii** [comment]
@dozoisch could you take a look at adding this?

**Comment by dozoisch** [comment]
Sure
