### ISSUE TITLE
Feature Request: `cache-and-network-and-cache` fetch policy

### ISSUE THREAD

**Issue by neilff** [apollographql/react-apollo#936]
We feel like there would be a strong use case for something that loads initially from cache, in the background fetches latest, and then subsequently retrieves from cache for the duration of the client session.

**Example**: 

In our app, we want to load data as fast as possible for the client, so we use Redux Persist and persist our Apollo data to `localstorage`. When the user returns to our site, we load data immediately from cache. 

This works great, but we run into problems with stale data. So we need to leverage something like `cache-and-network`, but the problem with that is the request is then performed again when the user returns to the page that the request was made. This request can be quite heavy, and the chances the data changes during the duration of the session is slim, so it is a lot of wasted bytes being transferred.

Something like `cache-and-network-and-cache` would allow us to load quickly from cache, make a fresh network request, but then load from cache afterwards.

**Is there a workaround?** 

We've implemented a simple mechanism to track fetch history, where we check if Apollo had previously gone out to the network. We use a middleware to inform this mechanism when a network request is made, we use named queries combined with variables to manage this. If it has then we use the fetch policy of `cache-first`, otherwise it uses `cache-and-network`.

This works, but it seems like a lot of hoops to jump through in order to determine if a request has gone out to the network previously.

**Comment by reactionic127** [comment]
@neilff 
How did you renderView from your cache?
