### ISSUE TITLE
updateQuery doesn't update when performing arbitrary transformation

### ISSUE THREAD

**Issue by ramsaylanier** [apollographql/react-apollo#937]
I'm performing an arbitrary transformation on the data prop by renaming the name of the prop related to a query. I'm trying to do pagination, but the previousResult and fetchMoreResult use the original query name. When I return a new object with the transformed name, the UI doesn't actually get updated. I have to return both the transformed name, and the original query name.

Here's the code:
```
const ResultsWithData = graphql(Query, {
  options: (props) => ({
    variables: {
      index: props.index,
      type: props.entityType,
      terms: props.terms,
      fields: props.fields || {},
      ranges: props.ranges || {},
      offset: 0,
      limit: PER_PAGE
    }
  }),
  props: ({ownProps, data: {loading, termSearch, fetchMore}}) => ({
    loading: loading,
    results: termSearch,
    loadPage: (page) => {
      return fetchMore({
        variables: {
          offset: page * PER_PAGE
        },
        updateQuery: (prev, { fetchMoreResult }) => {
          if (!fetchMoreResult) { return prev }
          return Object.assign({}, prev, {
            termSearch: {...prev.termSearch, ...fetchMoreResult.termSearch},
            results: {...prev.termSearch, ...fetchMoreResult.termSearch}
          })
        }
      })
    }
  })
})(Results)
```

**Intended outcome:**

To be able to use the transformed prop name in updateQuery.

**Actual outcome:**

Above, when I return Object.assign() I have to return both termSearch and results. If I remove termSearch from the return, the query doesn't actually update. 

**Version**
- react-apollo@1.4.8

**Comment by ramsaylanier** [comment]
I have figured out the issue.

**Comment by necccc** [comment]
may I ask what was the issue? I might struggle with the same
