### ISSUE TITLE
[Flow] typing feature request: successful Response should not be assumed

### ISSUE THREAD

**Issue by rattrayalex** [apollographql/react-apollo#956]
**Intended outcome:**

Raise a type error when accessing a result without checking for its existence. 
That is, enforce `if (hero) return <div>{hero.name}</div>`

```jsx
type Response = {
  hero: Hero,
};

export type InputProps = {
  episode: string,
};

const withCharacterPlain: OperationComponent<
  Response,
  InputProps,
> = graphql(HERO_QUERY, {
  options: ({ episode }) => ({
    variables: { episode },
  }),
});

withCharacterPlain(({ data: { loading, hero, error } }) => {
  if (loading) return <div>Loading {hero.name}</div>;
  //                               ^^^^^^^^^^^ there should be an error here
  //                                             (but there isn't)
  if (error) return <h1>ERROR</h1>;
  return <div>{hero.name}</div>;
});
```

Note that changing type `Response` to:
```jsx
type Response = {
  hero?: Hero,
};
```
achieves the desired effect, but isn't accurate – the *Response* should always have a `hero`, only when there isn't a response should there be no `hero`. 

A bonus would be to typecheck such that `if (hero)` is not required if it has already been checked that `!loading && !error`. 

**Actual outcome:**

The above typechecks with `No errors!`, and throws at runtime.

**How to reproduce the issue:**

see above example

**Version**
- react-apollo@1.4.10

**Comment by gforge** [comment]
Lovely idea but I don't know how this would be solved in Flow (v. 0.53). The intuitive way would be to use unions but these don't play well with interfaces. I tried to add something like:

```js

type SuccessQuery = {
  networkStatus: number,
  loading: false,
  variables: Object,
  fetchMore: (
    fetchMoreOptions: FetchMoreQueryOptions & FetchMoreOptions,
  ) => Promise<ApolloQueryResult<any>>,
  refetch: (variables?: Object) => Promise<ApolloQueryResult<any>>,
  startPolling: (pollInterval: number) => void,
  stopPolling: () => void,
  subscribeToMore: (options: SubscribeToMoreOptions) => () => void,
  updateQuery: (
    mapFn: (previousQueryResult: any, options: UpdateQueryOptions) => any,
  ) => void,
}

type ErrorQuery = {
  error: ApolloError,
  loading: false,
}

type LoadingQuery = {
  loading: true,
}

export type QueryProps = LoadingQuery | ErrorQuery | SuccessQuery
```

but it doesn't work as one would hope :-(

**Comment by rattrayalex** [comment]
Yeah, we make heavy use of unions for this and it can be tough.

Probably just a docs change to recommend using 
```jsx
type Response = {
  hero?: Hero,
};
```
would be sufficient 😄
