### ISSUE TITLE
Race conditions

### ISSUE THREAD

**Issue by lifeiscontent** [apollographql/react-apollo#957]
Hi, I'm seeing race conditions in my app when developing with apollo.

when I do a graphql fetch, `data.loading` is true, then when `data.loading` is false, it returns a key of the data I asked for with `undefined`, and then sets it... is there a reason for this?

https://github.com/lifeiscontent/postgraphql-forum-example-apollo-client

**Version**
- apollo-client@1.4.0
- react-apollo@1.4.10

**Comment by fjaguero** [comment]
I think that's the expected behavior, not a race condition.

**Comment by lifeiscontent** [comment]
@fjaguero I would expect there to be only undefined only when loading is set to true, why would you expect it to be otherwise? Then you have to do more null checks...

**Comment by lifeiscontent** [comment]
@fjaguero any updates here?

**Comment by fjaguero** [comment]
Sorry @lifeiscontent, I'm not a maintainer. We should wait for a response from @jbaxleyiii
