### ISSUE TITLE
incorrect flow types file in react-apollo@1.4.10

### ISSUE THREAD

**Issue by KROT47** [apollographql/react-apollo#958]
Unexpectedly file [index.flow.js](https://github.com/apollographql/react-apollo/blob/master/src/index.js.flow) does not match `react-apollo.umd.js.flow` in npm dist. But as we can see [here](https://github.com/apollographql/react-apollo/blob/master/scripts/deploy.sh#L53) it should be exact same files.

**Intended outcome:**
Followed instructions from [http://dev.apollodata.com/react/using-with-types.html](http://dev.apollodata.com/react/using-with-types.html)

**Actual outcome:**
```sh
Error: src/queries/profile/profile.js:25
 25: import type { OperationComponent, NamedProps, QueryProps } from "react-apollo";
                                       ^^^^^^^^^^ Named import from module `react-apollo`. This module has no named export called `NamedProps`.


Found 1 error
```

**How to reproduce the issue:**
Follow instructions mentioned above.

**Version**
- apollo-client@1.4.10
- react-apollo@1.9.0

**Comment by dozoisch** [comment]
see https://github.com/apollographql/react-apollo/pull/952! Most of them should be fixed in next release.

**Comment by benhjames** [comment]
Also, in `1.4.11` there are no flow files at all in the npm distribution! Super weird.

**Comment by jbaxleyiii** [comment]
@benhjames looks like 1.4.11 was a bad deploy, try 1.4.12!

**Comment by benhjames** [comment]
Works great - 1.4.12 also fixed the last issue I had with typing `graphql` wrappers around stateful class components! 🎉
