### ISSUE TITLE
Major BC break with 1.4.13

### ISSUE THREAD

**Issue by eugene1g** [apollographql/react-apollo#981]
1.4.13 added support for `apollo-client@2.0`, which gets installed by default for users who just rely  on `react-apollo` and do not specify their own apollo-client version. My app crashes with `createBatchingNetworkInterface is not a function` as it seems to be no longer included in apollo-client.

I suggest the relaxed version requirement should be reverted back to work with apollo-client 1 by default until v2 is officially released and/or has a BC story.

/ping @jbaxleyiii

**Comment by jbaxleyiii** [comment]
@eugene1g 1.4.14 is published with that reverted and 1.4.13 is deprecated on npm!
